Fixes #12352 - password strength simulator
phpmyadmin/phpmyadmin pull request #12363
Opened 2016-07-02 17:23 UTC by Achilles-96

Before submitting pull request, please check that every commit:

- [ ] Has proper Signed-Off-By
- [ ] Has commit message which describes it
- [ ] Is needed on it's own, if you have just minor fixes to previous commits, you can squash them
- [ ] Any new functionality is covered by tests

Signed-off-by: Achilles-96 <raghuram.vadapalli@research.iiit.ac.in>

2016-07-03 15:51 UTC, devenbansod commented on js/server_privileges.js
> +        console.log(zxcvbn_obj);
Hi, I believe this was for debugging purpose ?

2016-07-03 15:55 UTC, devenbansod commented
Also, I think this is not working as expected while I edit an existing user. I create a user, the password strength indicator works. 
I again go and try to copy that user by User Accounts -> Edit Privileges -> Login information, then it does not change and is stuck at 'Good' .
Also, if we are introducing this, we can do so for the 'Change password' fields as well ?

2016-07-04 09:34 UTC, Achilles-96 commented
I checked it. That is because we are having two elements with same `id` on that page. I did not expect that.

2016-07-04 12:54 UTC, Achilles-96 commented
https://github.com/blog/2141-squash-your-commits. I think we can use this.

2016-07-29 11:36 UTC, nijel commented on libraries/display_change_password.lib.php
> +        . '<input type="password" name="pma_pw" id="text_pma_change_pw" size="10" '
Why are you changing ID of the inputs? It will most likely break other things (like password generating).

2016-08-03 04:55 UTC, Achilles-96 commented on libraries/display_change_password.lib.php
> +        . '<input type="password" name="pma_pw" id="text_pma_change_pw" size="10" '
@nijel , The form for changing the password and the form for editing login information are on the same page. It is operated by hiding one or the other at a time. Both the forms have the same id for the password field. We cannot have two elements with the same id in any HTML page. I changed the way generate password accesses input elements of form (i.e by name instead of id) as it makes sense to have two elements with same name in a HTML form provided they are in different forms.

2016-08-03 07:57 UTC, nijel commented
Somehow it doesn't work for me (tried on password change):

![localhost_localhost_phpmyadmin_4 7 0-dev_-_2016-08-03_09 56 49](https://cloud.githubusercontent.com/assets/212189/17358141/ada7c8c2-5960-11e6-8702-43d0e1fef80c.png)
![localhost_localhost_phpmyadmin_4 7 0-dev_-_2016-08-03_09 56 32](https://cloud.githubusercontent.com/assets/212189/17358142/adaa94da-5960-11e6-8f70-236f2d19ec2a.png)

2016-08-03 07:58 UTC, nijel commented
Also is it possible to have non minified version of zxcvbn.js?

2016-08-03 09:19 UTC, Achilles-96 commented
Please check now.

2016-08-04 09:21 UTC, nijel commented
Still same. I see you have CSS only for Webkit, isn't that the problem?

2016-08-25 08:02 UTC, nijel commented
Hmm, playing a bit with the upstream demo, I'm not really sure including this is a good idea. It might just give wrong feeling of security when there is none.

For example choosing password "phpMyAdmin123456" gains score 4 / 4...

2016-08-27 04:47 UTC, Achilles-96 commented
I think we cannot handle all the cases. For example, if user uses his/her name with 123456, then also it would give a score of 4. This happens in many websites. Eventhough we cannot give best score possible, it sure does prevent really weak passwords.

2016-09-16 08:53 UTC, nijel commented
In my opinion using password phpMyAdmin123456 in phpMyAdmin **is** really weak password and this code marks it as strong leading to false assumption of security, what is IMHO worse than no indicator at all.

Either the code should be extended to cover easiest to guess words for phpMyAdmin's use case (at least phpMyAdmin, MySQL and MariaDB, but maybe some others) or not used at all.

Overall I'm not really convinced this such feature is good security wise, but it probably can do something good to less experienced users. See also https://nakedsecurity.sophos.com/2016/08/17/why-you-still-cant-trust-password-strength-meters/

2016-09-16 08:54 UTC, nijel commented on js/server_privileges.js
> +    var zxcvbn_obj = zxcvbn(value);
Please add second parameter here with our customized word list.

2016-09-16 08:55 UTC, nijel commented on js/server_privileges.js
> +        case 0: meter_obj_label.html('Too short');
This is not just too short, but really weak password (eg. dictionary word), please adjust text.

2016-09-16 08:55 UTC, nijel commented on js/server_privileges.js
> +    }
All the strings should be properly localized.

2016-09-16 08:56 UTC, nijel commented on server_privileges.php
> +$scripts->addFile('zxcvbn.js');
Probably same needs to be done in index.php where password change form can be opened.

2016-09-16 08:57 UTC, nijel requested changes
I think once these issues are fixed and good words dictionary is created this can be merged.

2016-09-16 09:22 UTC, nijel commented on js/server_privileges.js
> +    var zxcvbn_obj = zxcvbn(value);
...and username from the form.

2016-10-25 08:13 UTC, nijel commented on js/server_privileges.js
> +    strength = Math.min(strength, custom_pw_checker(value, username));
You can simply pass the customDict as second parameter to zxcvbn, no need to implement own checks.

2016-11-10 09:48 UTC, merged

2016-11-10 09:49 UTC, nijel commented
Thanks, I've merged your code with some minor fixes:

* 2de2eb7 Changelog entry for #12352
* 6145a84 Use username for password change strength indicator
* 4cfe911 Upgrade zxcvbn
* eb57b8d Improve black list
* 3bf24ad Correctly initialize scripts on loading password change form
* ac2cfef Move scripts loading to correct location