Properly escape strings in MySQL statement values
phpmyadmin/phpmyadmin pull request #12564
Opened 2016-09-18 08:18 UTC by devenbansod

Before submitting pull request, please check that every commit:

- [x] Has proper Signed-Off-By
- [x] Has commit message which describes it
- [x] Is needed on it's own, if you have just minor fixes to previous commits, you can squash them
- [ ] Any new functionality is covered by tests

Use *_real_escape string functions provided by connectors to escape strings while exporting

Fix #12453

Signed-off-by: Deven Bansod <devenbansod.bits@gmail.com>

2016-09-19 08:37 UTC, nijel commented on libraries/dbi/DBIDummy.php
> +        return '';
IMHO it return either original or MySQL quoted string here, otherwise it's pretty confusing.

2016-09-19 08:39 UTC, nijel commented on libraries/DatabaseInterface.php
> +        return $this->_extension->escapeString($link, $str);
I'd prefer to have link optional and use $link = $this->getLink($link);. It's really not needed in most cases...

2016-09-19 08:41 UTC, nijel commented on libraries/plugins/export/ExportSql.php
> +                            )
Is it intentional to use escapeString and Util::sqlAddSlashes? IMHO it will produce double escaped slashes.

2016-09-19 08:42 UTC, nijel requested changes
Overall I'm not really sure how newly introduced DBI::escapeString relates to Util::sqlAddSlashes. They both IMHO do pretty much same thing.

2016-09-19 09:43 UTC, devenbansod commented on libraries/DatabaseInterface.php
> +        return $this->_extension->escapeString($link, $str);
Changes done in the latest commit.

2016-09-19 09:43 UTC, devenbansod commented on libraries/plugins/export/ExportSql.php
> +                            )
Indeed it would have been wrong. I have removed the extra call in the new commit.

2016-09-19 09:45 UTC, devenbansod commented
I feel that `sqlAddSlashes` does not take care of double quotes inside a SQL statement properly, while use of this inbuilt function(s) would do that.

2016-09-19 10:03 UTC, nijel commented
So probably all uses of sqlAddSlashes should be turned into this new function and sqlAddSlashes can be removed?

2016-09-27 04:12 UTC, devenbansod commented
I think so but I would welcome a second opinion here. 

The page [here] (http://php.net/manual/en/mysqli.real-escape-string.php) says it encodes the characters `NUL (ASCII 0)`, `\n`, `\r`, `\`, `'`, `"` and the backtick, while `sqlAddSlashes` is just meant to add slashes before the `'` and `\` characters and we also provide an option to encode `\r` and `\n`.

One of the [comment](http://php.net/manual/en/mysqli.real-escape-string.php#46339) on the same page provides some more info.

Also, do you think moving finally to usage of prepared statements might help us in tackling all this issues (as reported by [this person] (http://php.net/manual/en/mysqli.real-escape-string.php#102639) )?

2016-09-27 07:59 UTC, nijel commented
Using prepared statements would be way better than constructing the SQL queries manually as we do right now. AFAIK it would mean dropping support for the mysql extension, but that really should not matter these days...

As for escaping, the null byte probably should be escaped as well, but as it won't appear in the user input, it's not properly handled by our code. For the newlines I think it should be there as well automatically. It was introduced by 280336063.

2016-09-28 04:27 UTC, devenbansod commented
Would that mean, for the time till we move completely to prepared statements, we can use this instead of Util::sqlAddSlashes ? 
Also, if we decide to replace all sqlAddSlashes calls with this inbuilt-function, would it be okay to do it in QA_4_6 (like would it be a major change that may break some other thing ?) or should we include this small change for fixing the export bug in QA_4_6 and then target master for the complete replacement ?

2016-10-03 14:09 UTC, nijel commented
I think using mysql(i)_real_escape_string instead of sqlAddSlashes is correct approach (until we use prepared statements). I'm fine with doing this change in QA_4_6.

2016-10-05 06:34 UTC, devenbansod commented
Okay. Thanks for the comments. 
I will go ahead and make the changes across other places and would let you know once I feel the PR is ready.

2016-10-08 05:17 UTC, devenbansod commented
Changes on the way. 
Many tests will fail for now, as I would have to add the mock and stubs with the Mock object of `dbi`.

2016-11-07 16:26 UTC, devenbansod commented
Finally the tests are adjusted. :-) 
I think now it's ready for a review.

2016-11-08 14:02 UTC, nijel commented
I think it looks good, there are still some things to fix:

* There is still one usage left in DatabseInterface::getTablesFull (called by string)
* Another ones in libraries/rte/rte_list.lib.php
* I guess test/libraries/common/PMA_quoting_slashing_test.php should be migrated to test for this new code
* Why not remove sqlAddSlashes code?

2016-11-09 10:02 UTC, devenbansod commented
I have removed the old code (old tests for now as well) and fixed the remaining calls.

But I am not really sure how to cover the `escapeString` function in the tests, since we would have to again add a mock test-double for `GLOBALS['dbi']` to handle the `escapeString` call to the databaseInterface and define the escaped strings that it should return (using may be a `returnValueMap`). 

Any help would be appreciated.

2016-11-09 10:37 UTC, nijel commented
Hmm, it's true that it's now external code and hard to test...

2016-11-10 10:08 UTC, nijel commented
Okay, merging now. It would be great if you could review it in master, there were quite some fixes needed.

2016-11-10 10:09 UTC, merged