Fixes #12514
phpmyadmin/phpmyadmin pull request #12690
Opened 2016-11-11 13:04 UTC by ragnerok

Before submitting pull request, please check that every commit:

- [ ] Has proper Signed-Off-By
- [X] Has commit message which describes it
- [ ] Is needed on it's own, if you have just minor fixes to previous commits, you can squash them
- [ ] Any new functionality is covered by tests

Changed Encoding.php and File.php such that it takes temp directory from configfile.php

2016-11-11 13:10 UTC, ragnerok commented
I have a few doubts 
1. Do I have to sign off somewhere ? Cause I haven't . Although I don't plan to not agree with the agreement
2. I do not get the error that has been pointed out by the bot !

2016-11-11 13:46 UTC, ibennetch commented
Hello @ragnerok and thanks for your contribution.

Yes, for legal purposes we require agreement with the [DCO document](https://github.com/phpmyadmin/phpmyadmin/blob/master/DCO); the best way to do so is when committing in git with something like `git commit -s`. This automatically adds the proper signed-off-by line to the commit message.

The bot is stating that your commit adds a newline character at the end of libraries/config/ConfigFile.php which was probably done automatically by your editor. If I recall correctly, our template system does not deal well with newlines at the end of certain files, so the bot looks for this.

Finally, you seem to have added a few files that you have added some files that seem to be unnecessary (certainly .DS_Store, but probably also a few others), so it would be good if you could remove those from your commit.

I and the others might have some comment on specific parts of the code, but that should at least answer your questions so far. In order to fix the signed-off-by message and extra files, you can amend your existing commit and push (with --force) the changes back to your repository on github (git and the manuals warn about rewriting history, but since your change hasn't been merged such rewrites are currently harmless). That will update this pull request automatically with the changes.

Thanks for your enthusiasm and work.

2016-11-12 07:30 UTC, ragnerok commented
Hi, I am relatively new to git so I don't what to do to remove the extra files using git . What do I have to do exactly ?

2016-11-15 14:18 UTC, nijel requested changes
There is another copy of similar code in prefs_manage.php, can you please replace it with new function as well?

2016-11-15 14:18 UTC, nijel commented on libraries/config/ConfigFile.php
> +        $tmp_subdir = rtrim($tmp_subdir, DIRECTORY_SEPARATOR);
Can you please fix indentation in this function?

2016-11-18 15:05 UTC, ragnerok commented on libraries/config/ConfigFile.php
> +        $tmp_subdir = rtrim($tmp_subdir, DIRECTORY_SEPARATOR);
yeah ok i'll work on both of these

2016-11-22 10:06 UTC, ragnerok commented
@nijel i am not able to find the similar code in prefs_manage.php

2016-11-23 13:49 UTC, nijel commented
It's slightly different, and starts here: https://github.com/phpmyadmin/phpmyadmin/blob/master/prefs_manage.php#L73

2016-11-26 07:37 UTC, ragnerok commented
I kind of get how this works , correct me if I am wrong
we'll first call the function that I have added and then if it's returned value ==$GLOBALS['cfg']['TempDir']  then the code will be same from line 83-86

2016-11-28 11:07 UTC, nijel commented
Actually it should share even more code, I've adjusted it in df66e4fa080e2aa938bc415a5be9bfe7af611301.

2016-11-28 11:14 UTC, nijel commented
Thanks, your contributions have been merged as b8a9b0f30d3d83746967ef457cca641e014c32a5 (after rebasing and squashing the commits). Additional fix was needed to make it work: 84971eaf4f1b47a148e60a0042291e5ccb45ea3d

2016-11-28 11:14 UTC, closed without merging