Support TokuDB Maintainance Operations
phpmyadmin/phpmyadmin pull request #12693
Opened 2016-11-13 13:58 UTC by shtse8

Before submitting pull request, please check that every commit:

- [ * ] Has proper Signed-Off-By
- [ *  ] Has commit message which describes it
- [ * ] Is needed on it's own, if you have just minor fixes to previous commits, you can squash them
- [ *  ] Any new functionality is covered by tests

2016-11-13 15:15 UTC, shtse8 commented
What is Current Coverage? I have no ideas.

2016-11-13 15:30 UTC, ibennetch commented
Thanks for submitting your pull request.

The codecov-io bot is referring to coverage in unit tests (which are in the `tests` subdirectory); it always chimes in on pull requests to tell us what percentage of code is currently covered by tests. This is particularly useful if there's a large code contribution that doesn't include tests because then the bot complains and someone fixes it by writing tests. In this case, it's probably okay how it is (ultimately we should have a full test suite against the TokuDB engine, but it doesn't look like such tests currently exist).

2016-11-13 15:45 UTC, shtse8 commented
Thanks for your explanation.

phpMyAdmin still can't support TukoDB. We are hard to find a way (except SQLs) to maintain TokuDB tables using phpMyAdmin. Creating Clustered Indices, Analyze Single Table, Change Compression Format. Will it support this storage engine in the future?

2016-11-15 09:37 UTC, shtse8 commented
Should I update the test script to improve the coverage?

2016-11-15 14:14 UTC, nijel requested changes

2016-11-15 14:14 UTC, nijel commented on libraries/controllers/table/TableIndexesController.php
> +                while( ( $pos = strpos($sql_query, ";") ) !== false) {
I think this will break when the table name contains `;`. Maybe it would be better to let `getSqlQueryForIndexCreateOrEdit` return array of queries?

2016-11-15 14:14 UTC, nijel commented on libraries/operations.lib.php
> +        $is_tokudb
This is really becoming ridiculous, but it's not your fault, created #12703 to track this.

2016-11-16 12:26 UTC, shtse8 commented on libraries/controllers/table/TableIndexesController.php
> +                while( ( $pos = strpos($sql_query, ";") ) !== false) {
I have the same thought too, but I don't know will it affect others if I've changed the return of `getSqlQueryForIndexCreateOrEdit`. Let me check.

2016-11-16 12:28 UTC, shtse8 commented on libraries/operations.lib.php
> +        $is_tokudb
Yes, I'm agree. It should return `$engine` instead. More and more engines are coming out and phpMyAdmin should work for supporting all.

2016-11-16 14:51 UTC, nijel commented on libraries/controllers/table/TableIndexesController.php
> +                while( ( $pos = strpos($sql_query, ";") ) !== false) {
I think having it return array in all cases and fix consumers to deal with it is cleanest approach.

2016-11-30 12:46 UTC, nijel commented on libraries/operations.lib.php
> +        $is_tokudb
BTW: This is being addressed in https://github.com/phpmyadmin/phpmyadmin/pull/12719

2017-01-18 17:10 UTC, nijel commented
Any chance to get this updated on current master?

2017-02-14 13:03 UTC, nijel commented
I've applied most of this patch in fa051ff3e8 and 2b6e5f892966302281d623e429cd61945392bbb7. The only missing are changes to libraries/Table.php, which duplicated quite a lot of code and I'm not really sure what is desired outcome there.

2017-02-14 13:03 UTC, closed without merging