Fixes #12703
phpmyadmin/phpmyadmin pull request #12719
Opened 2016-11-19 18:57 UTC by arimourao

This commit refactors the over use of global variations to identify tables storage engine.

2016-11-19 21:06 UTC, arimourao commented
I noticed an obvious error in the isEngine method of the Table class. Please, close this PR, I will push another one later. Although it is interesting to notice that I was unable to detect this error running tests in my machine and also the checks of this PR was unable to detect it.

2016-11-21 20:51 UTC, arimourao commented
Ok, I think it is good to go. Let me now if I have to do any changes.

2016-11-28 13:28 UTC, nijel commented on libraries/Table.php
> +                if($e == $this->isEngine()){
This seems to be wrong, you should probably compare with tbl_storage_engine as on line 183.

2016-11-28 13:28 UTC, nijel commented on libraries/Table.php
> +            return $this->tbl_storage_engine == $engine ? true : false;
The ternary operator is not necessary here.

2016-11-28 15:08 UTC, arimourao commented on libraries/Table.php
> +            return $this->tbl_storage_engine == $engine ? true : false;
I think the ternary is necessary because I have to return a boolean informing if it is the engine informed or not. Otherwise I would have to place this logic when calling the function ie `if(Table::isEngine() == 'INNODB'){//Do Something}`. If you prefer that way I can change it.

2016-11-28 15:35 UTC, nijel commented on libraries/Table.php
> +            return $this->tbl_storage_engine == $engine ? true : false;
But the comparison already returns boolean, so it can be just: 

```php
return $this->tbl_storage_engine === $engine;
```

2016-11-28 15:45 UTC, arimourao commented on libraries/Table.php
> +            return $this->tbl_storage_engine == $engine ? true : false;
I will make the corrections as soon as I get home

2016-11-28 21:36 UTC, arimourao commented
Done nijel. Let me know if you need anything else.

2016-11-30 10:33 UTC, nijel requested changes
It looks good so far. However I think we could make the code even better :-).

2016-11-30 10:33 UTC, nijel commented on tbl_operations.php
> -        ) = PMA_setGlobalVariablesForEngine($new_tbl_storage_engine);
Now that PMA_setGlobalVariablesForEngine is not used it could be removed.

2016-11-30 10:33 UTC, nijel commented on tbl_operations.php
> +        $pma_table->isEngine('MYISAM', 'ARIA'), $pma_table->isEngine('ISAM'), $create_options['pack_keys'],
IMHO it would be better to pass `$pma_table` as parameter and evaluate the condition when needed later in the code. This applies to all function calls.

2016-12-01 12:52 UTC, nijel commented
This turned out to be less complete than I hoped for, have you even tested the code? It used non existing property of Table class.

I've merged it with following fixes:

* 6c93914 Rewrite PMA_getTableOptionDiv to use Table for engine flags
* 58f6e84 Make PMA_getTableAltersArray accept table instead of flags
* 1a99e00 Document todo
* 2f97016 Simplified parameters for PMA_getHtmlForTableMaintenance
* ffda016 Actually make isEngine work
* 1c337f4 Remove no longer used function

2016-12-01 12:52 UTC, closed without merging