Removed PMA_TEST_HEADERS checking as they have been defined
phpmyadmin/phpmyadmin pull request #12852
Opened 2016-12-24 17:04 UTC by ragnerok

Before submitting pull request, please check that every commit:

- [X] Has proper Signed-Off-By
- [X] Has commit message which describes it
- [X] Is needed on it's own, if you have just minor fixes to previous commits, you can squash them
- [X] Any new functionality is covered by tests

Signed-off-by : Osaid <osaid.nasir@gmail.com>

2016-12-29 17:19 UTC, ragnerok commented
@nijel  why is this causing an error ? All I've done is remove the if conditions which were useless as the header tests were defined and hence not needed

2017-01-02 15:12 UTC, nijel commented
You did not mock the Response::getInstance, so the function is working on real Response object instead of the mocked one...

2017-01-02 15:36 UTC, ragnerok commented
So basically I have to mock response object in both functions for this to work right like done [here](https://github.com/phpmyadmin/phpmyadmin/commit/2148e7cad879a9edbc6a82ab03115cd0957f9bee#diff-7cd1872ccc0c19cfaf814d634989604aR370)

2017-01-02 15:54 UTC, nijel commented
Yes

2017-01-02 15:59 UTC, ragnerok commented
I still do not get why it wasn't showing an error for this earlier when the if conditions were still there but anyways thanks

2017-01-02 16:03 UTC, nijel commented
Prior to the change the PHP's `header()` function has been mocked by runkit (or this was not tested on PHP 7 where runkit is not available), so it didn't actually sent headers...

2017-01-02 16:03 UTC, ragnerok commented
Also I think I have written same response mock code in 2-3 files and it would have been better if I had made some kind of function for it

2017-01-02 16:34 UTC, ragnerok commented
ok then I'll add a function responseMock with 2 arguments 1 is an array of strings for arguments for header() and $n which is the number of calls of header function to ConfigFile.php

2017-01-02 16:39 UTC, nijel commented
I think it would better fit to test/PMATestCase.php...

2017-01-02 16:50 UTC, ragnerok commented
Yeah makes sense
Thanks

2017-01-03 17:37 UTC, nijel commented on test/libraries/core/PMA_headerLocation_test.php
> +        PMATestCase::mockResponse('Location: ' . $testUri);
I think it's better to base the test class on PMATestCase and use it as $this->mockResponse....

2017-01-03 18:02 UTC, ragnerok commented on test/libraries/core/PMA_headerLocation_test.php
> +        PMATestCase::mockResponse('Location: ' . $testUri);
you mean PMA_HeaderLocation_Test should extend PMATestCase ?
but it already inherits from phpunit and multiple inheritance isn't allowed in php I think

2017-01-03 19:23 UTC, nijel commented on test/libraries/core/PMA_headerLocation_test.php
> +        PMATestCase::mockResponse('Location: ' . $testUri);
But PMATestCase does extend PHPUnit_Framework_TestCase, so there is no problem with that :-)

2017-01-04 05:21 UTC, ragnerok commented on test/libraries/core/PMA_headerLocation_test.php
> +        PMATestCase::mockResponse('Location: ' . $testUri);
oh I forgot about that nice !

2017-01-05 14:56 UTC, nijel commented on test/PMATestCase.php
> +        $restoreInstance = PMA\libraries\Response::getInstance();
You do not restore the instance anywhere...

2017-01-05 14:57 UTC, nijel requested changes

2017-01-05 14:57 UTC, nijel commented on test/libraries/core/PMA_headerLocation_test.php
> +        $this->mockResponse('Location: ' . $testUri);
The mock should be before function call....

2017-01-05 14:57 UTC, nijel commented on test/libraries/core/PMA_headerLocation_test.php
>          $attrInstance->setValue($restoreInstance);
The value is not set here.

2017-01-05 14:57 UTC, nijel commented on test/libraries/core/PMA_headerLocation_test.php
> +        unset($GLOBALS['header']);
No longer needed...

2017-01-05 15:09 UTC, ragnerok commented on test/libraries/core/PMA_headerLocation_test.php
> +        $this->mockResponse('Location: ' . $testUri);
sorry I just realised my mistake

2017-01-05 15:11 UTC, ragnerok commented on test/libraries/core/PMA_headerLocation_test.php
>          $attrInstance->setValue($restoreInstance);
this wasn't done by me but I'll correct it nonetheless

2017-01-05 15:25 UTC, nijel commented on test/libraries/core/PMA_headerLocation_test.php
>          $attrInstance->setValue($restoreInstance);
Ah, sorry, it works here because you're not using mockResponse in this method...

2017-01-05 15:36 UTC, ragnerok commented on test/libraries/core/PMA_headerLocation_test.php
>          $attrInstance->setValue($restoreInstance);
ok, but I was wondering is there a way to make use of mockResponse here as there is only the disable method that needs to be added

2017-01-06 08:34 UTC, nijel commented
Now the problem is that you're not restoring the original Response object after tests. Probably the mockResponse should return it and there should be method to restore it at the end of test...

2017-01-06 08:46 UTC, ragnerok commented
So the function should return $mockRespnse and then attrInstance 's value should be set to $mockResponse

2017-01-06 08:55 UTC, nijel commented
You need to call `$attrInstance->setValue($restoreInstance);` in the end. Probably it should be again wrapped by some method. Maybe the mockResponse should store both parameters as attributes. Or even better, if these attributes are set, the mock response would be automatically restored in tearDown method.

2017-01-06 09:27 UTC, ragnerok commented
why not make `$attrInstance` and `$mockResponse` as properties of PMATstCase then both are accessible using `$this`

2017-01-06 11:49 UTC, nijel commented
Yes, that is what I was thinking about:

* add these properties to the class
* set them in mockResponse
* add `tearDown` method (which is executed after each test) which will restore original instance and clear the attributes if they were set

This way it will work properly even in case of test failure.

2017-01-07 12:44 UTC, nijel commented on test/libraries/core/PMA_headerLocation_test.php
> +    public function tearDown()
Shouldn't the method rather go to the PMATestCase class?

2017-01-07 17:50 UTC, ragnerok commented on test/libraries/core/PMA_headerLocation_test.php
> +    public function tearDown()
Then the method will have to be protected but yeah that will be better

2017-01-08 09:28 UTC, merged

2017-01-08 09:28 UTC, nijel commented
Merged, thanks for your contribution!