Row coloring issue
phpmyadmin/phpmyadmin pull request #12890
Opened 2017-01-12 03:20 UTC by ShreyasSinha

Signed-off-by: Shreyas Sinha <shreyas.sinha14@gmail.com>

Before submitting pull request, please check that every commit:

- [ ] Has proper Signed-Off-By
- [ ] Has commit message which describes it
- [ ] Is needed on it's own, if you have just minor fixes to previous commits, you can squash them
- [ ] Any new functionality is covered by tests

I have tried to fix the issue by changing the rowspan to 1 and by keeping all the attributes (type,function,null,value) of a column in a single row and not two different row as was done in case of longtext.

2017-01-12 06:02 UTC, ibennetch requested changes
Your fix looks good and seems proper, however the dead code should be removed instead of simply commented.

I think this can safely be merged in to QA_4_6, and with the removal of lines 588-591 it should be a simple cherry-pick for us from your branch in to QA_4_6. In the future, though, it's better to target the proper branch when creating the pull request (at least, I don't think there's a way to change it from GitHub once the pull request is opened).

Can you remove the meaningless lines? Thanks.

2017-01-12 06:02 UTC, ibennetch commented on libraries/insert_edit.lib.php
> +    //        $html_output = '<td colspan="5" class="right">';
If this is dead code, it should be removed rather than just commented out.

2017-01-12 06:02 UTC, ibennetch commented on libraries/insert_edit.lib.php
> +//   $html_output .= '</td>'.'</tr>';
Same thing here, if this is dead code it should be removed outright.

2017-01-12 06:02 UTC, ibennetch commented on libraries/insert_edit.lib.php
> +  return $html_output;
I think this accidentally got moved over, it looks like there should be four spaces to match the indentation in the rest of the function.

2017-01-12 06:58 UTC, ShreyasSinha commented
Thank you @ibennetch for reviewing my pull request.
I have made the changes as requested.
Next time I will be careful which branch to target while creating pull request.

2017-01-12 19:09 UTC, ibennetch approved these changes

2017-01-17 15:59 UTC, nijel approved these changes
Looks good.

2017-01-17 16:24 UTC, ibennetch commented
It was tough to tell which branch you should have targeted, since the bug report lists 4.7 you technically did the right thing. However, the underlying problem with displaying the table cell was broken in 4.6, so I merged it there as well. When merging, I also squashed your commit in to one as 4a2695cf5b209d18374ed6c339cefd33abfea15b

Nice work, thanks.

2017-01-17 16:24 UTC, closed without merging