Incorrect protocol number at 401/303 headers
phpmyadmin/phpmyadmin pull request #12920
Opened 2017-01-23 20:50 UTC by ShreyasSinha

#12707 
Signed-off-by: Shreyas Sinha <shreyas.sinha14@gmail.com>

Before submitting pull request, please check that every commit:

- [ ] Has proper Signed-Off-By
- [ ] Has commit message which describes it
- [ ] Is needed on it's own, if you have just minor fixes to previous commits, you can squash them
- [ ] Any new functionality is covered by tests

2017-01-24 09:32 UTC, nijel requested changes
Thanks, there are some problems I've commented inline, additionally some tests now fail and the code needs to be rebased on top of current code (we've merged fixes from security branch).

2017-01-24 09:32 UTC, nijel commented on libraries/plugins/auth/AuthenticationHttp.php
>          }
Shouldn't this logic go to the the http_response_code method?

2017-01-24 09:32 UTC, nijel commented on setup/lib/form_processing.lib.php
> +function PMA_generateHeader303($location)
I'd probably move this to Response classs as well, it's not really related to the form processing where it's placed...

2017-01-24 09:58 UTC, ShreyasSinha commented
After merging fixes from security branch my phpmyadmin is not working.
It is giving a HTTP ERROR 500. How can I fix that?

2017-01-24 10:07 UTC, nijel commented
Have you looked at PHP/webserver server logs? You will find the error message there.

2017-01-25 00:16 UTC, ShreyasSinha commented on libraries/Response.php
> +            header('status: ' . $response_code . $httpStatusMsg);
Displaying a general 'Web server is down' for all response code in case of CGI and Fast CGI.

2017-01-29 09:52 UTC, ShreyasSinha commented
@nijel The test is failing because output is already started at  /phpmyadmin/vendor/phpunit/phpunit/src/Util/Printer.php:134 before I set the http_response_code. How can I fix this?

2017-01-30 13:28 UTC, nijel reviewed
You probably have to mock the header method in Response class for that test.

2017-01-30 13:28 UTC, nijel commented on libraries/Response.php
> +            header('status: ' . $response_code . $httpStatusMsg);
You should use `$this->header` here.

2017-02-02 11:58 UTC, nijel commented on libraries/Response.php
> +        $httpStatusMsg  = ' Web server is down';
The message should be sent based on the code.

2017-02-02 11:58 UTC, nijel commented on test/classes/plugin/auth/AuthenticationHttpTest.php
> +            array('WWW-Authenticate: Basic realm="phpMyAdmin hst"')
This looks strange, shouldn't the header be sent even in tests?

2017-02-02 11:58 UTC, nijel commented on libraries/Response.php
> +    public function PMA_generateHeader303($location)
Can you please remove the `PMA_` prefix here?

2017-02-02 12:22 UTC, ShreyasSinha commented on test/classes/plugin/auth/AuthenticationHttpTest.php
> +            array('WWW-Authenticate: Basic realm="phpMyAdmin hst"')
The size of the array which stores these messages ($param) is tested and should be equal to the number of times header() function is called.
` $header_method = $mockResponse->expects($this->exactly(count($param)))
                    ->method('header');
` PMATestCase.php line:55

Earlier header was called three time for these 3 messages but now it is being called just once. Rest of the time http_response_code() is called. I have not yet written test cases for http_response_code(). I am working on it.

2017-02-02 12:45 UTC, ShreyasSinha commented on libraries/Response.php
> +    public function PMA_generateHeader303($location)
Ok.

2017-02-02 12:46 UTC, ShreyasSinha commented on libraries/Response.php
> +        $httpStatusMsg  = ' Web server is down';
Ok I have added a unique message based on the code for every `$response_code`.

2017-02-02 13:29 UTC, nijel commented on test/classes/plugin/auth/AuthenticationHttpTest.php
> +            array('WWW-Authenticate: Basic realm="phpMyAdmin hst"')
But the `php_sapi_name()` should be `cli` on tests and the new code should still use the header path, so the header should be IMHO issued.

2017-02-02 13:31 UTC, nijel commented on libraries/Response.php
> +        }
Looking at the original code it did always use http_response_code and *additionally* call header, you have changed it to use one or other, was that intentional?

2017-02-13 20:37 UTC, ShreyasSinha commented on libraries/Response.php
> +        }
Thanks for pointing it out. It was a mistake, I have corrected it.

2017-02-13 20:44 UTC, ShreyasSinha commented on test/classes/plugin/auth/AuthenticationHttpTest.php
> +            array('WWW-Authenticate: Basic realm="phpMyAdmin hst"')
Yes, you are right `php_sapi_name()` is `cli` on tests and the new code uses the header path. Thus I have added back `array('status: 401 Unauthorized')` in the new commit.

2017-02-14 07:18 UTC, ShreyasSinha commented
The code coverage tests are failing even after I have added Test Cases for `http_response_code()`. How can I fix this?

2017-02-14 09:34 UTC, nijel reviewed
Thanks for fixes. The coverage is fine, it's more like an indicator for us rather than strict requirement. I think the code is now good to merge, I've just few minor comments to tests.

2017-02-14 09:34 UTC, nijel commented on test/PMATestCase.php
> +                        $header_method = $mockResponse->expects($this->exactly(count($http_response_code_param)))
This will be always one, right? So it's probably better to use `once` instead of `exactly`....

2017-02-14 09:34 UTC, nijel commented on test/PMATestCase.php
> +                        call_user_func_array(array($header_method, 'withConsecutive'), $http_response_code_param);
...and here the array will have just one member as well, so using `with` directly instead of call_user_func_array machinery sounds more reasonable.

2017-02-14 09:34 UTC, nijel commented on test/PMATestCase.php
> +                    if(count($param)>=2){
I'm not really sure this is good idea. How about checking whether last member is integer instead? That way it's still possible to use the method with only headers without status code.

```php
if (is_int(end($param))
```

2017-02-14 10:42 UTC, ShreyasSinha commented on test/PMATestCase.php
> +                    if(count($param)>=2){
Ok. That will be better.

2017-02-14 10:43 UTC, ShreyasSinha commented on test/PMATestCase.php
> +                        $header_method = $mockResponse->expects($this->exactly(count($http_response_code_param)))
Yes, that will be better.

2017-02-14 10:43 UTC, ShreyasSinha commented on test/PMATestCase.php
> +                        call_user_func_array(array($header_method, 'withConsecutive'), $http_response_code_param);
Ok. Made the changes.

2017-02-14 12:20 UTC, merged

2017-02-14 12:20 UTC, nijel commented
Thanks! I've squashed your commits and merged.