Tabl info.inc.php moved to table class #12567
phpmyadmin/phpmyadmin pull request #12931
Opened 2017-01-27 19:16 UTC by flash1452

Before submitting pull request, please check that every commit:

- [ ] Has proper Signed-Off-By
- [ ] Has commit message which describes it
- [ ] Is needed on it's own, if you have just minor fixes to previous commits, you can squash them
- [ ] Any new functionality is covered by tests

Signed-off-by: vishpandey2014@gmail.com

2017-01-27 19:17 UTC, flash1452 commented
@nijel kindly review my PR and suggest changes.

2017-01-29 12:00 UTC, flash1452 commented
@nijel Also if you can help me with this code coverage problem.

2017-01-30 13:32 UTC, nijel requested changes
I assume phpunit.phar file should not be there, please remove it.

Also the repeated getTable calls should be removed - it should be called just once and then use resulting Table object.

2017-01-30 13:32 UTC, nijel commented on libraries/Response.php
> +/* vim: set expandtab sw=4 ts=4 sts=4:  */
I guess this change is not intentional.

2017-01-30 13:32 UTC, nijel commented on libraries/controllers/table/TableChartController.php
> +                                        $GLOBALS['table']
You should really do the getTable call just once and then use the resulting class in subsequent calls.

2017-01-30 17:24 UTC, flash1452 commented on libraries/controllers/table/TableChartController.php
> +                                        $GLOBALS['table']
@nijel Yeah, you are damn right there is no point in calling getTable function so many times.

2017-01-30 21:13 UTC, flash1452 commented
@nijel I have made some of the changes that you suggested but code coverage still remains an issue.

2017-02-02 09:04 UTC, flash1452 commented
@nijel Should I consider a new PR?? Because Code coverage is not passing.

2017-02-02 12:28 UTC, nijel commented on libraries/Table.php
> +    public function getTableStorageEngine($showtable){
It really should use `$this->getStatusInfo('ENGINE', false, true)` instead of getting the data as parameter.

2017-02-02 12:28 UTC, nijel commented on libraries/Table.php
> +        }
Same here, you should rely on class data and not get it from elsewhere as this can lead to errors.

Use `$this->getStatusInfo('COMMENT', false, true)` instead.

2017-02-02 12:28 UTC, nijel commented on libraries/Table.php
> +            return empty($showtable['Collation']) ? '' : $showtable['Collation'];
Same here, you should rely on class data and not get it from elsewhere as this can lead to errors.

Use `$this->getStatusInfo('COLLATION', false, true)` instead.

2017-02-02 12:28 UTC, nijel commented on libraries/Table.php
> +    public function getTableNumRowInfo($showtable){
Again, do not rely on passed parameters.

2017-02-02 12:28 UTC, nijel commented on libraries/controllers/table/TableChartController.php
> +            );
You really should not need this, the Table class should handle this internally.

2017-02-02 12:28 UTC, nijel commented on libraries/controllers/table/TableIndexesController.php
> +        );
...and same here.

2017-02-02 12:28 UTC, nijel commented
Yes most of the code is not covered by tests, but that really does not matter for now as it was previously not covered as well

2017-02-04 06:42 UTC, flash1452 commented
@nijel Made the changes you suggested.

2017-02-09 20:16 UTC, flash1452 commented
@nijel Kindly review the updated PR. The code coverage has improved drastically.

2017-02-10 13:55 UTC, nijel commented
Thanks! I will get to it next week.

2017-02-13 11:15 UTC, nijel commented on libraries/Menu.php
> +                $reread_info = true;
This does not seem to be used anywhere now. You should instead forcing of reading the information again here, for example using:

```php
$table_class_object->getStatusInfo(null, true);
```

2017-02-13 11:15 UTC, nijel commented on libraries/Table.php
> +        if ($table_comment) {
You probably want to check this as `=== false` instead to avoid surprises with PHP automatic typecasting. Without this you would be ignoring comment consisting of `0`, try yourself:

```php

if ('0') {
    echo "HERE\n";
}
```

Same applies to other methods as well.

2017-02-28 10:17 UTC, flash1452 commented
@nijel I have made some of the suggested changes in this PR and also squashed all the commits.

2017-02-28 14:45 UTC, flash1452 commented
@nijel I forgot, Congratulations on getting selected for this years GSoC.

2017-03-01 08:05 UTC, nijel commented on libraries/Menu.php
> +                $reread_info = true;
What about this variable? You set it in several places but it really doesn't seem to be used. In case the rereading is really necessary here, you should actually reread the information as mentioned in above comment.

2017-03-02 01:08 UTC, flash1452 commented
I have made the changes related to rereading. But the code coverage seems to have taken a hit.

2017-03-06 04:48 UTC, flash1452 commented
@nijel Please review the PR.

2017-03-06 09:10 UTC, nijel commented
I did quick review and this is really far from being complete.

Following files do still use tbl_info.inc.php which you've removed:

* libraries/controllers/table/TableIndexesController.php
* libraries/controllers/table/TableRelationController.php
* libraries/controllers/table/TableSearchController.php
* libraries/controllers/table/TableStructureController.php
* libraries/mult_submits.inc.php
* tbl_addfield.php
* tbl_export.php
* tbl_find_replace.php
* tbl_import.php
* tbl_operations.php
* tbl_select.php
* tbl_sql.php
* tbl_structure.php
* tbl_zoom_select.php

There are some other things to improve in the code which I've fixed (I thought I could merge the code with such changes prior to realizing above):

* ba0f9785c3 Document return types
* 4c4f851d7a Remove documentation for non existing param
* bbef205ca4 Simplify getting table create options
* 5dbd529e69 Simplify getting row format
* f92cc062d4 Simplify getting table rows
* 8f121757c6 Simplify getting table collation
* 2344b79f70 Simplify getting table comment
* ff1427020d Simplify getting storage engine
* 1ddd344fb5 Fix comments indentation
* a90f2f2a08 Remove commented out code
* a7e6c07188 Remove unused variables
* 6899e8f6da Simplify rereading of information

And most important question: Have you actually tested the code you've written? Even table structure does not work with your changes...

2017-03-06 13:11 UTC, flash1452 commented
@nijel Thanks for you review. I will have to accept I have been careless while testing my code but yeah, I will  soon make the required changes.

2017-03-06 13:26 UTC, flash1452 commented
@nijel Please correct me if I am wrong but libraries/controllers/table/TableIndexesController.php,
libraries/controllers/table/TableRelationController.php, libraries/controllers/table/TableSearchController.php doesn't seem to be using any of the variables being set in tbl_info.inc.php.

2017-03-06 14:42 UTC, flash1452 commented
@nijel There are many such files where the lib_info.inc.php is included but the variables being set in lib_info.inc.php is not used. One such example is TableRelationController.php where these variables are passed as parameters to the constructor. What should be the way to handle these situations?

2017-03-07 12:58 UTC, nijel commented
Yes, it can be that the variables are not used there, I didn't look at the code, I've just noticed that it's still included. You need to go through these files and check whether they need some of the variables...

2017-03-09 14:53 UTC, flash1452 commented
@nijel I have updated the code with your mentioned changes. I have tested my code this time but still if you can test it and review it.

2017-03-09 22:29 UTC, flash1452 commented
@nijel There is a link broken in docs, that's why the TRAVIS build is failing.

 (line   41) broken    https://anonscm.debian.org/cgit/collab-maint/phpmyadmin.git/tree/debian/README.Debian - HTTPSConnectionPool(host='anonscm.debian.org', port=443): Max retries exceeded with url: /cgit/collab-maint/phpmyadmin.git/tree/debian/README.Debian (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x2b233231d8d0>: Failed to establish a new connection: [Errno 113] No route to host',)).

Should we remove this url from the doc or replace it.

2017-03-10 10:44 UTC, nijel commented
It was temporary failure, I've just restarted the job.

2017-03-11 11:39 UTC, flash1452 commented
@nijel Still the code coverage seems to drop. But, I guess this should not make much of difference?

2017-03-14 15:00 UTC, flash1452 commented
@nijel What can be done to improve the code coverage? Any suggestions.

2017-03-14 16:18 UTC, nijel commented
Have you tested the code? I got several errors, fixed them in f88971e34045eff61db397a0f33cfd48f2d69d43, you can merge it at https://github.com/flash1452/phpmyadmin/pull/2

As for coverage, it's probably okay, but you should really test it manually as well as the automated tests still don't cover everything...

2017-03-15 03:57 UTC, flash1452 commented
@nijel I am getting a Error 500 whenever I am trying to test my phpmyadmin branch. 
The apache error logs show - 
Class 'PhpMyAdmin\\MoTranslator\\Loader' not found in /usr/share/phpmyadmin/libraries/common.inc.php on line 90.

But the weird thing is my old version of the same branch works perfectly and in that version in common.inc.php instead of 'PhpMyAdmin\\MoTranslator\\Loader' only 'MoTranslator\Loader' has been used.

2017-03-15 14:35 UTC, nijel commented
You need to run composer, see https://docs.phpmyadmin.net/en/latest/setup.html#installing-from-git

2017-03-20 16:30 UTC, flash1452 commented
@nijel I have tried and tested the current version  of code with my changes. So, if you can have a look at it and give it a run.

2017-03-20 16:57 UTC, nijel commented
Thanks, I've manually merged and rebased your changes.

2017-03-20 16:57 UTC, closed without merging