templating getRadioFields(), getDropDown() in Util.php
phpmyadmin/phpmyadmin pull request #12937
Opened 2017-01-30 20:08 UTC by poush

Fixes #12006 
Updated all tests code to pass them on new changes.
Signed-off-by: Piyush Agrawal <poush12@gmail.com>

Before submitting pull request, please check that every commit:

- [x ] Has proper Signed-Off-By
- [x] Has commit message which describes it
- [x ] Is needed on it's own, if you have just minor fixes to previous commits, you can squash them
- [x] Any new functionality is covered by tests

2017-02-10 17:18 UTC, poush commented
@nijel @ibennetch Please look into this.

2017-02-20 10:33 UTC, nijel requested changes

2017-02-20 10:33 UTC, nijel commented on libraries/Util.php
> +                $checked = 0;
Please use {} parenthesis in if statement.

2017-02-20 10:33 UTC, nijel commented on libraries/Util.php
> +            // $radio_html .= "\n";
Please remove commented out code.

2017-02-22 09:24 UTC, poush commented
Thanks @nijel, updated my PR.

2017-02-27 10:15 UTC, merged

2017-02-27 10:15 UTC, nijel commented
Merged, thanks for your contribution!