Remove connect_type setting
phpmyadmin/phpmyadmin pull request #12950
Opened 2017-02-02 15:10 UTC by nijel

It is really not necessary as MySQL decides connection type rather based
on hostname than on anything else.

Signed-off-by: Michal Čihař <michal@cihar.com>

Before submitting pull request, please check that every commit:

- [x] Has proper Signed-Off-By
- [x] Has commit message which describes it
- [x] Is needed on it's own, if you have just minor fixes to previous commits, you can squash them
- [x] Any new functionality is covered by tests

2017-02-03 15:00 UTC, ibennetch commented
If, for some reason, we don't merge this, we should address an interesting situation where a user must use connect_type='socket' in order for `$cfg['Servers'][$i]['socket']` to take effect. It makes sense why it was implemented this way, but if this doesn't get merged we can improve that.

2017-02-03 15:01 UTC, ibennetch commented
Anyway, I like this and think it's a good improvement. I don't see a downside of merging this and it works for me.

2017-02-03 15:04 UTC, ibennetch approved these changes

2017-02-03 15:13 UTC, ibennetch requested changes
I have a few suggestions for documentation language.

2017-02-03 15:13 UTC, ibennetch commented on doc/config.rst
> +        ignores :config:option:`$cfg['Servers'][$i]['port']` in this case
I'd make this "The hostname ``localhost`` is handled specially by MySQL and it uses the socket based connection protocol. To use TCP/IP networking, use an IP address or hostname such as ``127.0.0.1`` or ``db.example.com``. You can configure socket address by :config:option:`$cfg['Servers'][$i]['socket']`."

2017-02-03 15:13 UTC, ibennetch commented on doc/config.rst
> +       This settings is no longer used as of 4.7.0, the MySQL anyway decides
I suggest "This setting is no longer used as of 4.7.0, since MySQL decides the"

2017-02-03 15:13 UTC, ibennetch commented on doc/config.rst
> +       Please set :config:option:`$cfg['Servers'][$i]['host']` accordingly
It's helpful how you direct users to 'host' here instead, good job.

2017-02-04 16:32 UTC, nijel commented
Applied your suggestions in 34946a285b.

2017-02-06 12:11 UTC, ibennetch commented
Great, I think this looks ready.

Do you really want to apply it to QA_4_7? I don't object because the modifications are relatively minor, but in general I think we should avoid such changes to a QA branch.

2017-02-06 12:12 UTC, nijel commented
I'm not sure, but I thought it is still reasonable to do that for 4.7 now.

2017-02-06 12:16 UTC, ibennetch commented
Sure, let's go ahead with putting it in 4.7.

2017-02-06 12:22 UTC, nijel commented
Okay, merging.

2017-02-06 12:22 UTC, merged

2017-02-06 14:17 UTC, ibennetch commented
Great. Did you use `--author` to add my name to this commit or is that part of the new Github review feature? Either way, it's pretty helpful!

2017-02-06 14:47 UTC, nijel commented
I've used commandline with ``-author``