Google reCaptcha feature
phpmyadmin/phpmyadmin pull request #13011
Opened 2017-02-17 19:38 UTC by ShreyasSinha

Signed-off-by: Shreyas Sinha <shreyas.sinha14@gmail.com>

Solves issue #12983 

Before submitting pull request, please check that every commit:

- [ ] Has proper Signed-Off-By
- [ ] Has commit message which describes it
- [ ] Is needed on it's own, if you have just minor fixes to previous commits, you can squash them
- [ ] Any new functionality is covered by tests

2017-02-18 14:12 UTC, ghost approved these changes
Yeah, This looks good too.

2017-02-18 15:01 UTC, ibennetch requested changes
When I tried this without reCAPTCHA enabled or configured, the Go button is disabled and I am unable to log in.

It does seem to work as expected when the Captcha is enabled, so nice work on that.

2017-02-18 15:01 UTC, ibennetch commented on js/functions.js
> +function captcha_enable() {
I think this implies enabling the captcha itself, not the "Go" button.

Perhaps a better function name would be `login_go_button_enable()` or something else more descriptive.

2017-02-18 15:01 UTC, ibennetch commented on js/functions.js
> +function captcha_disable() {
Likewise, this function name is also a bit misleading.

2017-02-18 15:01 UTC, ibennetch commented on js/functions.js
> +* Function to enable the 'Go' button on login.
Please align the asterisks by indenting by one space, like
```
/*
 * Function...
 */
```
That way it matches the style of the rest of the file.

2017-02-18 15:12 UTC, edwarddekker commented
Sadly, I am not a programmer. But do have still plenty ideas about new functions on phpMyAdmin.

2017-02-18 15:36 UTC, ibennetch commented
@edwarddekker Your input is valuable here. Thanks for taking an interest in improving the project.

To be clear in case I caused confusion, my feedback was specifically meant about the code that ShreyasSinha has proposed. You can feel free to keep making suggestions :)

2017-02-18 19:29 UTC, ShreyasSinha commented on js/functions.js
> +* Function to enable the 'Go' button on login.
ok

2017-02-18 19:30 UTC, ShreyasSinha commented on js/functions.js
> +function captcha_enable() {
Yes, that will be better.

2017-02-20 06:06 UTC, ShreyasSinha commented
@ibennetch I think this is ready for review.

2017-02-20 15:33 UTC, merged

2017-02-20 15:33 UTC, nijel commented
Merged with coding style cleanup in 1f819d8d505aae709c7a9397a82d1cbfbed52c23.

2017-02-20 16:16 UTC, ibennetch commented
Thanks @ShreyasSinha