Fixes #13029
phpmyadmin/phpmyadmin pull request #13054
Opened 2017-03-05 17:11 UTC by Achilles-96

Signed-off-by: Raghuram Vadapalli <raghuram.vadapalli@research.iiit.ac.in>

Before submitting pull request, please check that every commit:

- [ ] Has proper Signed-Off-By
- [ ] Has commit message which describes it
- [ ] Is needed on it's own, if you have just minor fixes to previous commits, you can squash them
- [ ] Any new functionality is covered by tests

2017-03-06 00:14 UTC, ibennetch commented
Thanks for your contribution. I haven't examined the code, but it's generally better to use a more descriptive commit message. Something like:

> Fix table tracking interface with grouped tables
> 
> Fixes #13029 

Whichever developer reviews and merges this may be able to improve it when merging, so don't worry about fixing it just yet.

2017-03-06 09:36 UTC, nijel commented
It would be great if you could create testcase for this code as well.

2017-03-06 16:12 UTC, Achilles-96 commented
Hi @nijel , I am new to writing tests. Do I have to create a fake db. If yes, how do I create? This is required because Tracker::getVersion($db, $table_name) actually executes an sql query to get the status. I think there must be a way without creating a db. I think I need some help here.

2017-03-07 13:00 UTC, nijel commented
You can use Dummy dbi driver, see for example [DatabaseInterfaceTest::testGetCurrentUser](https://github.com/phpmyadmin/phpmyadmin/blob/master/test/classes/DatabaseInterfaceTest.php#L42).

2017-03-07 16:48 UTC, Achilles-96 commented
I checked your comment a bit late. I tried to avoid testing getUntrackedTables itself. I just wrote a test to check the helper recursive function. I will change it if you recommend otherwise.

2017-03-08 16:08 UTC, nijel requested changes
No problem, that is good approach as well. However the function probably should get better name now. Also it would be great if you could provide reasonable description in the commit messages as @ibennetch has mentioned in https://github.com/phpmyadmin/phpmyadmin/pull/13054#issuecomment-284275619

2017-03-08 16:08 UTC, nijel commented on libraries/tracking.lib.php
> +function getList($table_list, $db, $testing=false) {
I guess it should now have the PMA prefix and probably also better name to indicate what it does.

2017-03-11 05:13 UTC, Achilles-96 commented
Any update on this?

2017-03-13 08:19 UTC, nijel commented
Merged into QA_4_7 as ebc935a91514bb3ca2faa6447227eb971da1469f, thanks for your contribution!

2017-03-13 08:19 UTC, closed without merging

2017-03-13 16:55 UTC, neogic commented
Thank you for the quick fix @Achilles-96 - fantastic! :)