Solved-Show default collation when creating new DB #12984
phpmyadmin/phpmyadmin pull request #13061
Opened 2017-03-09 15:12 UTC by Fenn-CS

Before submitting pull request, please check that every commit:

- [ ] Has proper Signed-Off-By
- [ ] Has commit message which describes it
- [ ] Is needed on it's own, if you have just minor fixes to previous commits, you can squash them
- [ ] Any new functionality is covered by tests
#12984

2017-03-09 15:53 UTC, ibennetch commented
Something may have gone wrong, because there are 2,268 files changed with this pull request.

Some of it looks like permission problems, but often this can be caused by working from one branch (such as QA_4_7) and creating a pull request against a different branch (master, for instance).

2017-03-09 16:23 UTC, Fenn-CS commented
@ibennetch  they are permission problems I work on ubuntu I had to change the permission to 777 to have full access on my apache server...How do I fix this pull request?

2017-03-09 16:55 UTC, Fenn-CS commented
@ibennetch I have fixed every issue and only the file that needs to be changed to fix the error is marked changed now. Thanks

2017-03-09 17:07 UTC, Fenn-CS commented
![changes](https://cloud.githubusercontent.com/assets/14317775/23761421/05eef5a8-04f3-11e7-8d0d-b119d48cae29.png)

2017-03-10 09:11 UTC, OlafvdSpek commented
The whitespace changes shouldn't be there.

2017-03-10 14:03 UTC, ibennetch commented
Indeed, the whitespace changes make it difficult to see what this accomplishes (even though, it seems the switch/case indentation could be fixed, that should be a different pull request). 

Perhaps your editor was making whitespace "fixes" without your knowledge; many editors that do autoindentation can do that inadvertently.

Also, your commit is missing the "signed off by" comment that indicates you agree with and abide by the terms of the "Developer Certificate of Origin"; more information about this is linked by phpmyadmin-bot above.

2017-03-10 14:07 UTC, ibennetch commented
I just tested this by changing the default collation of my server and the displayed value did not update; I'm not sure from where exactly you're gathering that information but it may not be correct.

2017-03-11 02:56 UTC, Fenn-CS commented
@ibennetch does this mean I supposed to close this pull request in order to fix the issue and then create a new pr?

2017-03-11 02:58 UTC, ibennetch commented
No, you can keep this open and push more commits to your branch. When you do so, the pull request automatically updates.

I prefer that because it's easier and less noisy than opening a new pull request.

2017-03-11 03:01 UTC, Fenn-CS commented
@ibennetch ok thanks, on the test that failed this is how I get the information about default collation 
`
$sql='SELECT DEFAULT_CHARACTER_SET_NAME, DEFAULT_COLLATION_NAME FROM INFORMATION_SCHEMA.SCHEMATA WHERE SCHEMA_NAME ='.'"information_schema"'`;

2017-03-11 04:01 UTC, Fenn-CS commented
It simply gets the information from the information_schema table. Maybe you check whether actually the default collation was actually changed. I think I have been able to fix the indentation problems (white space changes) with the pull request also thanks.

2017-03-11 06:24 UTC, ibennetch commented
If I'm not mistaken, that only tells you the default collation for the information_schema database, not for the whole system.

2017-03-11 06:42 UTC, devenbansod commented
@ibennetch yes. That's right. 

Also, @Fenn-CS I can still see the whitespace changes in this PR, please remove them while committing with the requested changes.

2017-03-11 06:42 UTC, devenbansod requested changes

2017-03-11 06:42 UTC, devenbansod commented on libraries/Charsets.php
> +            $res = $GLOBALS['dbi']->query($sql);
@Fenn-CS I suggest you use the existing function `getServerCollation()` defined in `libraries/DatabaseInterface.php` for getting the server collation (which will act as a default for a newly created database, if nothing is specified), instead of separately querying it using a raw query (which is not returning the correct value that we should look at actually) in the code here.

2017-03-11 13:32 UTC, Fenn-CS commented
I am using sublime text and am having a hard time with these white space changes... Any help will be appreciated thanks.

2017-03-11 15:19 UTC, Fenn-CS commented
@devenbansod I have applied the changes your requested. Thnks

2017-03-11 15:39 UTC, devenbansod commented on libraries/Charsets.php
Unused import ?

2017-03-11 15:39 UTC, devenbansod commented on libraries/Charsets.php
It seems that the whitespace problem still persists. Please fix this.

2017-03-11 15:39 UTC, devenbansod commented on libraries/Charsets.php
>          self::loadCharsets();
I believe that this is not the correct place to make this change. 
The function `getCharsetDropdownBox` already takes a default value as a parameter `$default` and we don't every charset dropdown to have a default value as the server collation.

For example, the table creation might use the database collation as the default value and not the server collation.

2017-03-11 15:43 UTC, Fenn-CS commented
@devenbansod I am having challenges fixing the white space issues...They seem to be created by sublime text how do I combat this?

2017-03-11 15:59 UTC, devenbansod commented
@Fenn-CS I am not sure what is the problem, since even I use Sublime text sometimes, but it does not create any issue at all. It might be some configuration issue, so you can better ask for a solution to your problem on their support forum or on Stackoverflow. Till then you may want to use a different text editor. 

Also, use `git commit -s` while commiting, to avoid the error regarding the missing Signed-Off-By line.

2017-03-11 16:44 UTC, Fenn-CS commented
@devenbansod I have moved the changes from the general function to the specific page where the performance was expected now the default collation value is passed like a parameter to the function I previously edited. I have also addressed the issue with Trailing white spaces as from my last commit. Thanks

2017-03-12 02:52 UTC, devenbansod commented on libraries/Charsets.php
> +}
There are just two extra space changes in unrelated files. Please remove them and then [squash](https://git-scm.com/book/id/v2/Git-Tools-Rewriting-History#_squashing) all the commits into one.

2017-03-12 13:29 UTC, Fenn-CS commented
Hello @devenbansod and @ibennetch I have made all the changes requested. I think every thing is ok now apart from the fact I have been unable to squash all the commits into one. I will need help on that I tried doing that and it seemed to revert my work bringing back old changes. Apart from that I think it solves the  problem as required right now...

2017-03-12 13:47 UTC, devenbansod approved these changes

2017-03-12 13:50 UTC, merged

2017-03-12 13:50 UTC, devenbansod commented
I am squashing and merging your commits.

Also a suggestion regarding your next PRs, please make a new branch while implementing a feature/fixing a bug, instead of directly working on master/QA_* branches on your fork.

Thanks for your contribution!

2017-03-12 15:47 UTC, Fenn-CS commented
@devenbansod thanks. My pleasure to work with phpMyAdmin! :)