Implement PSR-11
phpmyadmin/phpmyadmin pull request #13060
Opened 2017-03-08 19:49 UTC by mauriciofauth

Fixes #13052

Signed-off-by: Maurício Meneghini Fauth <mauriciofauth@gmail.com>

Before submitting pull request, please check that every commit:

- [x] Has proper Signed-Off-By
- [x] Has commit message which describes it
- [x] Is needed on it's own, if you have just minor fixes to previous commits, you can squash them
- [ ] Any new functionality is covered by tests

2017-03-10 20:55 UTC, mauriciofauth commented
I've never written tests before, so I do not know if the ones I've written are correct.

2017-03-13 08:54 UTC, nijel requested changes

2017-03-13 08:54 UTC, nijel commented on libraries/di/Container.php
> +        }
I really don't get the code here:

- Why is there `try { throw } catch {}` block at all?
- The echo is there for something else than debugging purposes?

2017-03-13 08:54 UTC, nijel commented on libraries/di/Container.php
> +     * @throws ContainerException Error while retrieving the entry.
It doesn't seem to throw these as they are always handled inside...

2017-03-13 08:54 UTC, nijel commented on libraries/di/Container.php
> +        return false;
Probably better to write whole method as:

```php
    return isset($this->content[$name]) || isset($GLOBALS[$name]);
```

2017-03-13 08:54 UTC, nijel commented on test/classes/di/ContainerTest.php
> +        $this->assertSame(null, $this->container->get('invalid'));
IMHO it should throw NotFoundExceptionInterface according to PSR-11.

2017-03-14 13:17 UTC, nijel commented
And now the code code which uses container needs to be adjusted to understand new behavior, see at least the test failures: https://travis-ci.org/phpmyadmin/phpmyadmin/jobs/210553712#L457

2017-03-14 14:22 UTC, mauriciofauth commented
I will do this @nijel 

And about the `get` method, I think it would not be appropriate to use `isset` since this already happens in the `has` method. I think it should check whether the value is valid or not. Maybe `!is_null`?

2017-03-14 14:57 UTC, nijel commented
Why should it check for null value? I think it's perfectly okay to return null if it has been set...

2017-03-14 15:22 UTC, mauriciofauth commented
Oh, of course. I was not thinking straight.
Looking at the code, I realized that all values are instances of `ValueItem`. Maybe check for it.
I'm wanting to check for something other than `isset`, otherwise `ContainerException` will never be thrown.

2017-03-21 22:14 UTC, mauriciofauth commented
I left `get` method the way it was and corrected the tests that were failing.
Is everything all right now, @nijel?

2017-03-22 08:24 UTC, merged

2017-03-22 08:25 UTC, nijel commented
Merged, thanks for your contribution!