Removed onmouseover and onmouseout inline javascript
phpmyadmin/phpmyadmin pull request #13073
Opened 2017-03-13 10:07 UTC by manishbisht

Fixes : #12261

- [ ] Has proper Signed-Off-By
- [ ] Has commit message which describes it
- [ ] Is needed on it's own, if you have just minor fixes to previous commits, you can squash them
- [ ] Any new functionality is covered by tests

2017-03-13 11:07 UTC, nijel requested changes
Thanks, I think your changes look generally good.

2017-03-13 11:07 UTC, nijel commented on templates/database/designer/database_tables.phtml
> +                    table_name="<?= htmlspecialchars($t_n_url); ?>">
You seem to have removed part of output here, was that intentional?

```php
<?= (! isset($tab_pos[$t_n]) || ! empty($tab_pos[$t_n]["V"])) ? 'v' : '&gt;'; ?>
```

2017-03-13 11:07 UTC, nijel commented on themes/pmahomme/css/pmd.css.php
> +.tab_field:hover, .tab_field_3:hover {
Can you please make same changes in the original theme as well?

2017-03-13 14:18 UTC, manishbisht commented on templates/database/designer/database_tables.phtml
> +                    table_name="<?= htmlspecialchars($t_n_url); ?>">
No, I haven't removed any extra output. I have removed only `onmouseover="this.className='small_tab2';"` and `onmouseout="this.className='small_tab';"`
Can you please tell me more if I am missing something.

2017-03-13 14:32 UTC, manishbisht commented on themes/pmahomme/css/pmd.css.php
> +.tab_field:hover, .tab_field_3:hover {
Is it outside of the main phpyadmin repo ? Because I can't find anything related to it to make changes in original theme.
![8](https://cloud.githubusercontent.com/assets/14255990/23858815/bbea9dee-0827-11e7-83e2-3d36badf5dc8.png)

2017-03-14 13:20 UTC, nijel commented on templates/database/designer/database_tables.phtml
> +                    table_name="<?= htmlspecialchars($t_n_url); ?>">
Yes, check the second removed line, there is additional content after `onmouseout="this.className='small_tab';"` which IMHO should stay.

2017-03-14 13:23 UTC, nijel commented on themes/pmahomme/css/pmd.css.php
> +.tab_field:hover, .tab_field_3:hover {
Sorry, you're right, the original theme does not use this. There are some third party themes in the themes repository which do use that, but those can be fixed later (but feel free to open PR).

2017-03-14 14:23 UTC, manishbisht commented on templates/database/designer/database_tables.phtml
> +                    table_name="<?= htmlspecialchars($t_n_url); ?>">
I think there is some issue in showing file difference on GitHub. Check this link it is present in line 32 https://github.com/manishbisht/phpmyadmin/blob/23ae0c5e88290eb6c2db973cb9d214d812b23fb8/templates/database/designer/database_tables.phtml#L32

2017-03-14 14:59 UTC, nijel approved these changes
Thanks, I'm going to merge this. But still it would be great if you could do the same changes for the themes in themes repository.

2017-03-14 14:59 UTC, nijel commented on templates/database/designer/database_tables.phtml
> +                    table_name="<?= htmlspecialchars($t_n_url); ?>">
Ah okay, I somehow didn't expect GitHub will show it wrongly :-)

2017-03-14 14:59 UTC, merged

2017-03-14 15:02 UTC, manishbisht commented
Yes, I will submit PR for the themes repo also.