Master
phpmyadmin/phpmyadmin pull request #13093
Opened 2017-03-17 16:18 UTC by mohdluqman

Fixed the automatic rounding off of time greater than 23. TIME type in MySql supports a long range of values. The PMA insert                                                      widget don't allow the values greater than 23 currently. So, it can be                                                      corrected by setting the timepicker function have a greater hourMax                                                     value than it have by default in the file functions.js.

2017-03-20 15:43 UTC, nijel requested changes

2017-03-20 15:43 UTC, nijel commented on js/functions.js
> +            if(type == 'time'){
Can you please add space here after if?

2017-03-20 15:43 UTC, nijel commented on js/functions.js
> +                hourMax = 99;
Why 99 when MySQL docs states that the maximal value is 838?

2017-03-24 14:50 UTC, mohdluqman commented
Sorry for the late reply as your comment was not showing on my dashboard. As per your first instruction I have added the space after if statement and for your second comment, I used 99 because

- The timepicker plugin doesn't work well with the 3 digit hour values (i.e. > 99) based on my input testing. Since I found 99 the greatest 2 digit hour value so i used it.

- As per @ibennetch comment which says "phpMyAdmin validation function doesn't like hour values of 24 through 99 and automatically converts them to 23" I derived the meaning that 99 should be the largest hour values.

If you want some other modifications or give some suggestions please describe.

2017-03-24 14:54 UTC, mohdluqman commented
Sorry for the late reply as your comment was not showing on my dashboard and also sorry for above closing mistake(being a newbie).  As per your first instruction I have added the space after if statement and for your second comment, I used 99 because

The timepicker plugin doesn't work well with the 3 digit hour values (i.e. > 99) based on my input testing. Since I found 99 the greatest 2 digit hour value so i used it.

As per @ibennetch comment which says "phpMyAdmin validation function doesn't like hour values of 24 through 99 and automatically converts them to 23" I derived the meaning that 99 should be the largest hour values.

If you want some other modifications or give some suggestions please describe.

2017-03-24 14:57 UTC, mohdluqman commented
Sorry for the late reply as your comment was not showing on my dashboard and also sorry for above closing mistake(being a newbie). As per your first instruction I have added the space after if statement and for your second comment, I used 99 because

- The timepicker plugin doesn't work well with the 3 digit hour values (i.e. > 99) based on my input testing. Since I found 99 the greatest 2 digit hour value so i used it.

- As per @ibennetch comment which says "phpMyAdmin validation function doesn't like hour values of 24 through 99 and automatically converts them to 23" I derived the meaning that 99 should be the largest hour values.

If you want some other modifications or give some suggestions please describe.

2017-03-24 19:23 UTC, ibennetch commented
The validation function seems to have some odd behavior which isn't the correct behavior. I was more documenting another layer of trouble with this functionality than explaining how it should work.

2017-03-25 14:20 UTC, mohdluqman commented
Then what should we do about the bug. IMO it would be better 

- to overload the method **'regstr'**  at L1188 in jquery-ui-timepicker-addon.js file to accept hour values of 3 digits or change its regex (according to my code reading).

- to use some other time checker plugin.

- to restrict hour values within two digit only.

2017-03-25 14:59 UTC, ibennetch commented
In my opinion, making the picker accept all possible values will make control of the scroller too unrefined to be useful. My preference is to have the picker go from 0 to 24 hours, 0 to 60 minutes, and 0 to 60 seconds combined with two fixes to the validator function. 1) it should not automatically correct values, instead it show just show the red warning text and the value is invalid to MySQL, and 2) it should accept valid values from 24-100.

That's my opinion of the best solution here.

2017-06-28 10:12 UTC, merged

2017-06-28 10:12 UTC, nijel commented
Merged, thanks for your contribution!