Fixes error in designer #13032
phpmyadmin/phpmyadmin pull request #13102
Opened 2017-03-19 06:00 UTC by Achilles-96

Signed-off-by: Raghuram Vadapalli <raghuram.vadapalli@research.iiit.ac.in>

Before submitting pull request, please check that every commit:

- [ ] Has proper Signed-Off-By
- [ ] Has commit message which describes it
- [ ] Is needed on it's own, if you have just minor fixes to previous commits, you can squash them
- [ ] Any new functionality is covered by tests

2017-03-20 15:24 UTC, nijel requested changes
I don't think this is good approach. We most likely need to encode the values rather than doing some transforms on it later.

2017-03-20 15:24 UTC, nijel commented on js/pmd/move.js
> +    var dom = parser.parseFromString('<!doctype html><body>' + str,'text/html');
This seems to open door to XSS.

2017-06-28 10:27 UTC, nijel commented
Sorry, but I still think this is wrong approach:

- trying to treat arbitrary value (database or table name) as identifier will never work reliably
- using something like md5 or similar hash is probably better approach

2017-06-28 10:27 UTC, closed without merging

2017-06-28 12:22 UTC, Achilles-96 commented
I am sorry I forgot about this. I will try to send a patch where tables will have their md5 sums as their ids. I already used that approach in my other work - #13342 . I will do this as soon as I am free if no one takes this up.