upgraded google recpatcha with google invisble recaptcha
phpmyadmin/phpmyadmin pull request #13101
Opened 2017-03-18 17:56 UTC by manishbisht

Fixes: #13086 

Before submitting pull request, please check that every commit:

- [ ] Has proper Signed-Off-By
- [ ] Has commit message which describes it
- [ ] Is needed on it's own, if you have just minor fixes to previous commits, you can squash them
- [ ] Any new functionality is covered by tests

2017-03-20 15:29 UTC, nijel requested changes
Can you please also adjust testcases to changed HTML? See  https://travis-ci.org/phpmyadmin/phpmyadmin/jobs/212502415#L461

2017-03-20 15:29 UTC, nijel commented on js/functions.js
> +    $('#login_form').submit();
By this change we've lost the disabling of the button when captcha is not solved, right?

2017-03-21 09:00 UTC, manishbisht commented on js/functions.js
> +    $('#login_form').submit();
Yes, I got your point. Will be fixing test cases according to it.

2017-03-21 15:57 UTC, manishbisht commented
I have tried fixing the tests. Only one build is failing https://travis-ci.org/phpmyadmin/phpmyadmin/jobs/213449603 How to fix this. 
`
Generating code coverage report in Clover XML format ...Segmentation fault (core dumped)
The command "./test/ci-$CI_MODE" exited with 139.
`

2017-03-21 16:03 UTC, nijel commented
Seems like some issue of Travis, I've restarted the job to see if that helps...

2017-03-21 16:09 UTC, manishbisht commented
The build has failed again.

2017-06-28 09:03 UTC, merged

2017-06-28 09:04 UTC, nijel commented
Merged, thanks for your contribution!