Adds error if target db has the same name as current db #13099
phpmyadmin/phpmyadmin pull request #13104
Opened 2017-03-19 07:13 UTC by TheSaturn

Adds error if target db has the same name as current db name to prevent data corrupt #13099

2017-03-19 13:29 UTC, ibennetch requested changes

2017-03-19 13:29 UTC, ibennetch commented on db_operations.php
> +        $message = PMA\libraries\Message::error(__('The new database name is equal to the current one!'));
I suggest changing this message to "Cannot copy database to the same name. Change the name and try again."

2017-03-19 13:29 UTC, ibennetch commented on templates/database/designer/database_tables.phtml
> +                    id="id_hide_tbody_<?= htmlspecialchars($t_n_url) ?>"
You should really split unrelated changes in to different pull requests, even though both of these changes are only one or two lines each.

I have a database named `p&?&` and this doesn't seem to fix the problem for that or with the database name in the original error report, either.

2017-03-19 14:10 UTC, ibennetch commented
Also note that there is #13103 which is working towards changing the defaults for the the copy/rename fields.

2017-03-20 15:26 UTC, nijel requested changes
As written by Isaac - try to submit one pull request with one fix. That way it's easier to merge parts of it when they are ready to get merged...

2017-03-21 08:51 UTC, nijel commented on templates/database/designer/database_tables.phtml
> +                    id="id_hide_tbody_<?= htmlspecialchars($t_n_url) ?>"
I've cherry picked this as 4119b5ca3d2af76543ccaa5ebe1a408d2cc4fb31.

2017-04-12 07:02 UTC, closed without merging

2017-04-12 07:02 UTC, nijel commented
I've committed dbdd7bcb9db9c7a54221aec6344c8c889768aea6 based on your fix and @ibennetch wording.