Fixes editing default value for ENUM #13120
phpmyadmin/phpmyadmin pull request #13171
Opened 2017-04-09 18:37 UTC by Achilles-96

Signed-off-by: Raghuram Vadapalli <raghuram.vadapalli@research.iiit.ac.in>

Before submitting pull request, please check that every commit:

- [ ] Has proper Signed-Off-By
- [ ] Has commit message which describes it
- [ ] Is needed on it's own, if you have just minor fixes to previous commits, you can squash them
- [ ] Any new functionality is covered by tests

2017-04-12 06:58 UTC, nijel commented on js/tbl_structure.js
> +    last_param = url.split('&')[url.split('&').length - 1];
The URL separator can be different on the server and it would break this code. Also isn't there other way to get this data instead of parsing URL?

2017-04-14 13:18 UTC, Achilles-96 commented on js/tbl_structure.js
> +    last_param = url.split('&')[url.split('&').length - 1];
I can't find any other way to get it as the page is loaded based on parameter. Any suggestions?

2017-04-28 09:34 UTC, nijel commented on js/tbl_structure.js
> +    last_param = url.split('&')[url.split('&').length - 1];
It's probably to better to store the value in HTML on the server and the load it here. Parsing request string this way is not really good approach. Besides the delimiter, the ordering can change as well....

2017-09-05 12:56 UTC, nijel commented
I've just tested this and while the selection is there, the value is not really  used:

  ```ALTER TABLE `test` ADD `en` ENUM('d','dsa','dsa','dsadsa') NOT NULL AFTER `date`;```

It seems to submit field_default_type instead of field_default_value parameter.

Also it seems to work only when editing first enum in the table, others get the usual dropdown...

2017-09-05 12:58 UTC, nijel requested changes

2017-09-05 12:58 UTC, nijel commented on js/tbl_structure.js
> +        text: 'As defined:'
This should use translated messages, not hardcoded English ones...

2017-09-05 12:58 UTC, nijel commented on js/tbl_structure.js
> +            if ($('#field_0_2').val() == 'ENUM') {
This makes it work only for ENUM being on first position when editing.

2017-09-05 12:58 UTC, nijel commented on templates/columns_definitions/table_fields_definitions.phtml
> +        <input type="hidden" id="page_type" value="change_column"/>
What is reason for this flag?

2017-11-11 13:59 UTC, closed without merging