Removed inline onchange
phpmyadmin/phpmyadmin pull request #13294
Opened 2017-05-23 15:36 UTC by manishbisht

Fixes #12261

- [x] Has proper Signed-Off-By
- [x] Has commit message which describes it
- [x] Is needed on it's own, if you have just minor fixes to previous commits, you can squash them
- [ ] Any new functionality is covered by tests

2017-05-23 16:55 UTC, manishbisht commented
@nijel Can you please restart the build. I think there is some timeout issue.

2017-05-24 08:07 UTC, nijel commented on templates/table/search/column_comparison_operators.phtml
> +</script>
This really doesn't help for CSP - both need unsafe-inline. Can you please move that to one of js files?

2017-05-25 04:09 UTC, manishbisht commented
@nijel I have updated the PR.

2017-05-29 10:32 UTC, manishbisht commented
@nijel @ibennetch Can we merge this PR ?

2017-05-29 14:28 UTC, ibennetch commented
I'd like to wait for Michal's comment since he's more familiar with the CSP issue than I am.

2017-06-01 13:22 UTC, nijel requested changes

2017-06-01 13:22 UTC, nijel commented on js/tbl_select.js
> +    var tableRows = $('.data tbody tr');
This selector looks too generic. Also it's probably better to use `$('...').each(...)` instead.

2017-06-01 13:22 UTC, nijel commented on templates/table/search/column_comparison_operators.phtml
> +<select id="ColumnOperator<?= $search_index; ?>" name="criteriaColumnOperators[<?= $search_index; ?>]">
Unfortunately I've merged migration of those templates to Twig meanwhile, can you please update your PR?

2017-06-01 16:06 UTC, manishbisht commented
@nijel I have update the PR

2017-06-02 15:16 UTC, nijel commented on js/tbl_select.js
> +    $(tableRows).each(function(index, item){
You don't need $() around tableRows here (it's already constructed as jQuery object list).

2017-06-02 15:16 UTC, nijel commented on js/tbl_select.js
> +    var tableRows = $('.data tbody tr');
Have you checked this generic selector is actually good?

2017-06-02 15:36 UTC, manishbisht commented
@nijel Updated the PR with the suggested changes.

2017-06-02 15:38 UTC, manishbisht commented on js/tbl_select.js
> +    var tableRows = $('.data tbody tr');
Yes, It will select the data which have `.data` class then the `tbody` tag and at the last all the `tr` tags inside it. And make an object of the result.

2017-06-06 12:02 UTC, nijel commented on js/tbl_select.js
> +    var tableRows = $('.data tbody tr');
But the data class is used in more situations, won't it match too many?

Also shouldn't you rather target on select instead of tr? The tr certainly doesn't have onchange...

2017-06-09 02:45 UTC, manishbisht commented
@nijel Yes, You were right `select`should be used instead of `tr` I have updated the PR.

2017-06-09 13:21 UTC, nijel commented on js/tbl_select.js
> +    var tableRows = $('select');
You can't just match all selects on the page. Probably adding class to the one you want to match is needed. Have you tested the change that it doesn't affect something else?

2017-06-09 15:07 UTC, manishbisht commented
@nijel I have added extra id selector `$('#fieldset_table_qbe select');` to get results more accurately. Yes I have tested the change by putting the `console.log()` statements before the function call and also verified that the length of `tableRows` should be equal to the number of columns in the table.

2017-06-12 11:07 UTC, nijel approved these changes

2017-06-12 11:08 UTC, merged

2017-06-12 11:08 UTC, nijel commented
Merged, thanks for your contribution!