Add 2-factor authentication support for phpMyAdmin.
phpmyadmin/phpmyadmin pull request #13495
Opened 2017-07-16 11:38 UTC by Achilles-96

Signed-off-by: Raghuram <raghuram.4350@gmail.com>

Before submitting pull request, please check that every commit:

- [ ] Has proper Signed-Off-By
- [ ] Has commit message which describes it
- [ ] Is needed on it's own, if you have just minor fixes to previous commits, you can squash them
- [ ] Any new functionality is covered by tests

2017-07-16 11:47 UTC, Achilles-96 commented
I described the procedure of setting up in my [blog post](https://raghuramvadapalli.wordpress.com/2017/07/14/2-factor-authentication-for-phpmyadmin/).

As I mentioned there, I need advice on where to place link to access `setup2FA.php`.

2017-07-17 15:35 UTC, nijel requested changes
I've quickly gone through your code, some general remarks:

* Please include documentation, having it in the blog is great, but it really should be part of our documentation.
* Any reason for not integrating 2FA into existing Settings tab?

2017-07-17 15:35 UTC, nijel commented on js/get_scripts.js.php
> +/* exit; */
I guess this is not intentional...

2017-07-17 15:35 UTC, nijel commented on libraries/phpqrcode.php
> + * It was auto-generated from full version for your convenience.
Please do not include third party libraries, can't this be loaded using composer? Also including generated code without source doesn't really play well with GPL, so we would have to distribute the source code as well.

2017-07-17 15:35 UTC, nijel commented on libraries/session.inc.php
> +if (!isset($_SESSION)){
What is purpose of this change? If really needed, please do that in separate commit explaining why it is needed.

2017-07-17 15:35 UTC, nijel commented on libraries/plugins/auth/AuthenticationCookie.php
> +        $check_2FA_db_query = 'SELECT `pma_user`, `secret` FROM `pma__2fa_secrets` WHERE `pma_user` LIKE \'' . $GLOBALS['PHP_AUTH_USER'] . '\';';
* Please do not hardcode table name, see how others are handled.
* Why using LIKE when doing exact match?

2017-07-17 15:35 UTC, nijel commented on libraries/plugins/auth/AuthenticationCookie.php
> +        );
I think this can fail, so you should handle false return value here.

2017-07-17 15:35 UTC, nijel commented on libraries/plugins/auth/AuthenticationCookie.php
> +        $check_2FA_db_query = 'SELECT `pma_user` FROM `pma__2fa_secrets` WHERE `pma_user` LIKE \'' . $GLOBALS['PHP_AUTH_USER'] . '\';';
Same as with auth2FA. Also these seem to share quite some amount of code, so you might want to factor that out.

2017-07-17 15:35 UTC, nijel commented on setup2FA.php
> +        echo 'true';
Really?

2017-07-17 15:35 UTC, nijel commented on setup2FA.php
> +        echo 'Sorry. The key does not match. Please ensure that server time and your app\'s time are in sync.' . $_SESSION['secret'];
Should be localized, also there is probably no point in showing the secret here. Especially not unescaped as it seems to be user input.

2017-07-17 15:35 UTC, nijel commented on setup2FA.php
> +        echo $GLOBALS['dbi']->getError($GLOBALS['controllink']);
In case you want to pass the error details to client, please use JSON. Definitely do not output unescaped error messages.

2017-07-18 13:50 UTC, Achilles-96 commented
@nijel, I addressed most of the issues you raised. I left comments for the rest. Please verify.

2017-07-18 13:51 UTC, Achilles-96 commented on setup2FA.php
> +        echo htmlspecialchars('Sorry. The key does not match. Please ensure that server time and your app\'s time are in sync.');
By this time, translations may not be possible.

2017-07-18 15:05 UTC, ibennetch commented on setup2FA.php
> +        echo htmlspecialchars('Sorry. The key does not match. Please ensure that server time and your app\'s time are in sync.');
Could you please add a comment to the code as well stating that translations may not be possible?

2017-07-18 15:07 UTC, ibennetch commented on setup2FA.php
> +            $add_secret_query = 'INSERT INTO ' . $cfg_2fa_table . ' VALUES (\'' . $GLOBALS['PHP_AUTH_USER'] . '\' ,\'' . $_SESSION['secret'] . '\');';
Forgive me if I missed you doing it earlier, but I think you need to escape PHP_AUTH_USER and secret here; you could use the Dbi function `escapeString` for that.

2017-07-18 15:22 UTC, ibennetch commented
I tried opening my main phpMyAdmin after pulling your branch (without configuring any user for 2FA or setting up config.inc.php) and got a number of errors. We should be more graceful about failing if the user hasn't configured their system for this.

> Error
> SQL query: DocumentationEdit Edit
> 
> 
> SELECT `pma_user` FROM `` WHERE `pma_user` = 'root';
> MySQL said: Documentation
> 
> #1103 - Incorrect table name ''
> Open new phpMyAdmin window
> Notice in ./libraries/plugins/auth/AuthenticationCookie.php#570
>  Undefined index: 2fa_secrets
> 
> Backtrace
> 
> ./libraries/plugins/auth/AuthenticationCookie.php#547: PMA\libraries\plugins\auth\AuthenticationCookie->check2FA()
> ./libraries/common.inc.php#656: PMA\libraries\plugins\auth\AuthenticationCookie->authCheck()
> ./index.php#22: require_once(./libraries/common.inc.php)
> Warning in ./libraries/dbi/DBIMysqli.php#556
>  mysqli_real_escape_string() expects parameter 1 to be mysqli, boolean given
> 
> Backtrace
> 
> ./libraries/dbi/DBIMysqli.php#556: mysqli_real_escape_string(
> boolean false,
> string '_',
> )
> ./libraries/classes/DatabaseInterface.php#2743: PMA\libraries\dbi\DBIMysqli->escapeString(
> boolean false,
> string '_',
> )
> ./libraries/navigation/nodes/Node.php#437: PhpMyAdmin\DatabaseInterface->escapeString(string '_')
> ./libraries/navigation/NavigationTree.php#289: PMA\libraries\navigation\nodes\Node->getData(
> string 'databases',
> integer 0,
> string '',
> )
> ./libraries/navigation/NavigationTree.php#847: PMA\libraries\navigation\NavigationTree->_buildPath()
> ./libraries/navigation/Navigation.php#45: PMA\libraries\navigation\NavigationTree->renderState()
> ./libraries/classes/Header.php#433: PMA\libraries\navigation\Navigation->getDisplay()
> ./libraries/classes/Response.php#266: PhpMyAdmin\Header->getDisplay()
> ./libraries/classes/Response.php#279: PhpMyAdmin\Response->_getDisplay()
> ./libraries/classes/Response.php#438: PhpMyAdmin\Response->_htmlResponse()
> PhpMyAdmin\Response->response()
> Warning in ./libraries/dbi/DBIMysqli.php#556
>  mysqli_real_escape_string() expects parameter 1 to be mysqli, boolean given
> 
> Backtrace
> 
> ./libraries/dbi/DBIMysqli.php#556: mysqli_real_escape_string(
> boolean false,
> string '_',
> )
> ./libraries/classes/DatabaseInterface.php#2743: PMA\libraries\dbi\DBIMysqli->escapeString(
> boolean false,
> string '_',
> )
> ./libraries/navigation/nodes/Node.php#447: PhpMyAdmin\DatabaseInterface->escapeString(string '_')
> ./libraries/navigation/NavigationTree.php#289: PMA\libraries\navigation\nodes\Node->getData(
> string 'databases',
> integer 0,
> string '',
> )
> ./libraries/navigation/NavigationTree.php#847: PMA\libraries\navigation\NavigationTree->_buildPath()
> ./libraries/navigation/Navigation.php#45: PMA\libraries\navigation\NavigationTree->renderState()
> ./libraries/classes/Header.php#433: PMA\libraries\navigation\Navigation->getDisplay()
> ./libraries/classes/Response.php#266: PhpMyAdmin\Header->getDisplay()
> ./libraries/classes/Response.php#279: PhpMyAdmin\Response->_getDisplay()
> ./libraries/classes/Response.php#438: PhpMyAdmin\Response->_htmlResponse()
> PhpMyAdmin\Response->response()
> Warning in ./libraries/dbi/DBIMysqli.php#556
>  mysqli_real_escape_string() expects parameter 1 to be mysqli, boolean given
> 
> Backtrace
> 
> ./libraries/dbi/DBIMysqli.php#556: mysqli_real_escape_string(
> boolean false,
> string '_',
> )
> ./libraries/classes/DatabaseInterface.php#2743: PMA\libraries\dbi\DBIMysqli->escapeString(
> boolean false,
> string '_',
> )
> ./libraries/navigation/nodes/Node.php#449: PhpMyAdmin\DatabaseInterface->escapeString(string '_')
> ./libraries/navigation/NavigationTree.php#289: PMA\libraries\navigation\nodes\Node->getData(
> string 'databases',
> integer 0,
> string '',
> )
> ./libraries/navigation/NavigationTree.php#847: PMA\libraries\navigation\NavigationTree->_buildPath()
> ./libraries/navigation/Navigation.php#45: PMA\libraries\navigation\NavigationTree->renderState()
> ./libraries/classes/Header.php#433: PMA\libraries\navigation\Navigation->getDisplay()
> ./libraries/classes/Response.php#266: PhpMyAdmin\Header->getDisplay()
> ./libraries/classes/Response.php#279: PhpMyAdmin\Response->_getDisplay()
> ./libraries/classes/Response.php#438: PhpMyAdmin\Response->_htmlResponse()
> PhpMyAdmin\Response->response()

2017-07-19 14:30 UTC, ibennetch commented
We'll have to deal gracefully with situations where the user either hasn't configured it or the table doesn't exist.

You can also see for instance libraries/classes/Bookmark.php:114 for an example of how we might deal with this. We have to test the array to make sure $cfgRelation['2fa_secret'] (or whatever configuration directive you use) isn't empty first, before trying to use it. We initialize it as part of the default configuration to an empty value, so before using we'll test if the user has configured it.

Also, you should add the new directive to libraries/config.default.php with a blank assignment such as $cfg['Servers'][$i]['2fa_secret'] = '';. You can add it right after the export_template area around line 503.

We should also add this new directive to libraries/relation.lib.php around line 353; this file is used by chk_rel.php which warns the user if their table structure is outdated.

Can you add the structure for the 2fa_secrets table to `sql/create_tables.sql`?

Instead of manually running the SQL, it might be more efficient to use PMA_queryAsControlUser such as
```
$sql_query
    = " SELECT `tables` FROM " . $this->_getPmaTable() .
    " WHERE `username` = '" . $GLOBALS['dbi']->escapeString($GLOBALS['cfg']['Server']['user']) . "'";
$result = PMA_queryAsControlUser($sql_query, false);
```

2017-07-21 09:53 UTC, nijel commented on setup2FA.php
> +        echo htmlspecialchars('Sorry. The key does not match. Please ensure that server time and your app\'s time are in sync.');
Hmm, maybe this should be part of the setup script in the end (which we indeed do not localize)?

2017-07-21 11:41 UTC, nijel commented on setup2FA.php
> +class PMAQRProvider implements IQRCodeProvider {
Can you please place the class to separate file and include tests for it?

2017-07-22 17:41 UTC, Achilles-96 commented on setup2FA.php
> +        echo htmlspecialchars('Sorry. The key does not match. Please ensure that server time and your app\'s time are in sync.');
By this time, user would not have completely authenticated i.e., it is in the middle of authentication. Including common.inc.php is not possible because it will circularly check for 2-factor authentication again.

This part is accessed only by ajax request and the error message is displayed in standard PMA error dialog once received.

2017-07-24 15:13 UTC, nijel commented on setup2FA.php
> +        echo htmlspecialchars('Sorry. The key does not match. Please ensure that server time and your app\'s time are in sync.');
Maybe it would be better to closer integrate this to the authentication so that it can use the authentication API to show the form

2017-07-25 08:02 UTC, Achilles-96 commented on setup2FA.php
> +        echo htmlspecialchars('Sorry. The key does not match. Please ensure that server time and your app\'s time are in sync.');
Authentication form is shown by `auth2FA` function in `AuthenticationCookie.php`. This is for verification. Do you mean I should move verification to a different file.

2017-08-09 03:19 UTC, ibennetch commented on libraries/session.inc.php
> +if (!isset($_SESSION)){
@nijel are you satisfied with this change?

2017-08-09 11:54 UTC, nijel commented on libraries/session.inc.php
> +if (!isset($_SESSION)){
I'd prefer to have the documentation in the code as well, not only in the commit message, but thanks for documenting this.

2017-08-23 01:09 UTC, ibennetch commented
Could you rebase this against current master to reflect the changes Maurício has done?

2017-10-30 07:10 UTC, closed without merging