#13512 Patch
phpmyadmin/phpmyadmin pull request #13590
Opened 2017-08-16 14:38 UTC by anantjain6

#13512 Patch

Signed-off-by: Anant Jain <anantjain60@gmail.com>

Before submitting pull request, please check that every commit:

- [x] Has proper Signed-Off-By
- [x] Has commit message which describes it
- [x] Is needed on it's own, if you have just minor fixes to previous commits, you can squash them
- [ ] Any new functionality is covered by tests

2017-08-17 14:03 UTC, nijel requested changes

2017-08-17 14:03 UTC, nijel commented on themes/pmahomme/css/common.css.php
> +    width: 17em;
This really doesn't fix the problem, but rather hide it. I think that we rather should not force any width on the button as the text is being translated and can really have different widths.

2017-08-17 16:15 UTC, anantjain6 commented on themes/pmahomme/css/common.css.php
> +    width: 17em;
@nijel Oh Ya, I forgot about different languages
Let me make its width flexible
Thanks for the guidance

2017-08-21 08:58 UTC, nijel commented
Thanks, I've merged your patch as 28143053df730e2fc93c95d666a4a3dfe5a71eb1.

2017-08-21 08:58 UTC, closed without merging