Added refresh button in export
phpmyadmin/phpmyadmin pull request #13674
Opened 2017-09-11 22:17 UTC by jakubstanecki

Signed-off-by: Jakub Stanecki <staneckijakub@gmail.com>

Before submitting pull request, please check that every commit:

- [ ] Has proper Signed-Off-By
- [ ] Has commit message which describes it
- [ ] Is needed on it's own, if you have just minor fixes to previous commits, you can squash them
- [ ] Any new functionality is covered by tests

2017-09-12 16:47 UTC, MauricioFauth requested changes

2017-09-12 16:47 UTC, mauriciofauth commented on libraries/classes/Export.php
> +        $refreshButton = '<form method="POST" action="export.php" class="disableAjax" style="margin-left: 20px;">';
Could you move these inline styles to another location? See #12262.

2017-09-14 00:36 UTC, jakubstanecki commented
@mauriciofauth changed

2017-09-14 03:37 UTC, mauriciofauth commented
The refresh link worked for me, however it gives an error when I press F5. Do you think it would be a good idea to implement this behavior for F5 as well?

2017-09-14 03:38 UTC, mauriciofauth commented
Related to #13660.

2017-09-14 03:45 UTC, MauricioFauth approved these changes

2017-09-14 22:45 UTC, mauriciofauth commented on js/export_output.js
> +        if ((e.which || e.keyCode) == 116) {
It's better to use `===` instead of `==`. See [Codacy results.](https://www.codacy.com/app/phpMyAdmin/phpmyadmin/pullRequest?prid=904796)

2017-09-15 00:10 UTC, merged

2017-09-15 00:12 UTC, mauriciofauth commented
Merged, thanks for your contribution and patience with my feedback!