Issue #13747 PR
phpmyadmin/phpmyadmin pull request #13752
Opened 2017-10-16 23:21 UTC by akritianand

Instead of 'Confirm' as title when clicking on DROP TABLE or DROP DATABASE, it now shows 'DROP TABLE <tablename>' or 'DROP DATABASE <database>'. This is in reference with issue #13747

Signed-off-by: Akriti Anand anand.akriti@gmail.com

Before submitting pull request, please check that every commit:

- [ ] Has proper Signed-Off-By
- [ ] Has commit message which describes it
- [ ] Is needed on it's own, if you have just minor fixes to previous commits, you can squash them
- [ ] Any new functionality is covered by tests

2017-10-18 13:10 UTC, ibennetch commented
Hi @akritianand, thanks for your submission. In the future, it would be helpful if you can use a more descriptive title for your pull request and for the commits. "Update functions.js" or "Issue #13747" aren't very helpful when looking through the git log. Something like "Improve drop table confirmation message" makes a better pull request title.

The bot is upset that you haven't set the Signed-Off-By line which indicates that you agree with the terms of the [Developer Certificate of Origin (DCO)](https://github.com/phpmyadmin/phpmyadmin/blob/master/DCO). You can read a bit more about adding this in the [CONTRIBUTING document](https://github.com/phpmyadmin/phpmyadmin/blob/master/CONTRIBUTING.md#patches-submission), but it's most easily accomplished by passing the `--signoff` argument to git commit.

2017-10-19 12:51 UTC, nijel commented on js/functions.js
> +        var heading = question.split('execute "')[1].split('"')[0];
Both these will break with localized messages.

2017-10-19 12:52 UTC, nijel commented on js/functions.js
> +    .prepend(question)
Any reason for changing indentation on existing code?

2017-10-19 12:53 UTC, nijel requested changes
Besides things @ibennetch has already mentioned, I think the patch itself is also wrong. Maybe it would be best to include the title as optional parameter for PMA_confirm, so that every caller could specify it instead of relying on parsing of passed text what will break with localized strings.

2017-10-20 04:07 UTC, akritianand commented on js/functions.js
> +        var heading = question.split('execute "')[1].split('"')[0];
Can you tell me how will these break localised messages? I'm new to this, so sorry for my ignorance.

2017-10-20 08:53 UTC, nijel commented on js/functions.js
> +        var heading = question.split('execute "')[1].split('"')[0];
They won't contain the "execute" string (and can contain different quote as well). For example in Czech the string will be "Opravdu si přejete provést „%s“?". So split will return just one string and the code will fail.

2017-12-26 10:13 UTC, closed without merging