Iss12262
phpmyadmin/phpmyadmin pull request #13777
Opened 2017-10-25 09:52 UTC by skokeers27

Before submitting pull request, please check that every commit:

- [x ] Has proper Signed-Off-By
- [x] Has commit message which describes it
- [x] Is needed on it's own, if you have just minor fixes to previous commits, you can squash them
- [x] Any new functionality is covered by tests

2017-10-25 10:10 UTC, nijel requested changes
Thanks for your patch. Besides things I've mentioned inline, the CSS changes should be also implemented in second theme we ship - in themes/original/css/common.css.php

2017-10-25 10:10 UTC, nijel commented on themes/pmahomme/css/common.css.php
> +}
This is most likely wrong for RTL languages (probably should match floatright).

2017-10-25 10:10 UTC, nijel commented on themes/pmahomme/css/common.css.php
> +}
There is already hide class doing this, no need to duplicate it.

2017-10-25 10:28 UTC, skokeers27 commented on themes/pmahomme/css/common.css.php
> +}
This is original line:
echo '<div class="choice floatright" style="clear:right;">';
Shoudl I left 2 classes, choice and floatright and remove "style="clear:right;" ?

2017-10-25 10:53 UTC, nijel commented on themes/pmahomme/css/common.css.php
> +}
Yes, the original code was wrong as well. Hmm, looking at it, this element seems to be hidden all the time anyway, so it's probably better remove anything else from it:

https://github.com/phpmyadmin/phpmyadmin/blob/701a8855fdb4c992e3882b76c40a92c2610891ba/themes/pmahomme/css/gis.css.php#L46-L48

2017-10-25 10:58 UTC, skokeers27 commented on themes/pmahomme/css/common.css.php
> +}
Ok, I left only choice class.

2017-10-27 09:14 UTC, ADFF2F reviewed
changes have been made

2017-10-30 08:27 UTC, merged

2017-10-30 08:28 UTC, nijel commented
Thanks, I've merged this PR with following fixes:

* 8109763b75 Remove not needed CSS for span elements
* 43cbcf6bd0 Remove unused class
* 636b22cb06 Remove clearright class