Fix Row coloring issue@Indexes
phpmyadmin/phpmyadmin pull request #13877
Opened 2017-12-18 19:32 UTC by shucon

Signed-off-by: Saksham Gupta [shucon01@gmail.com](shucon01@gmail.com)
Before submitting pull request, please check that every commit:

- [ ] Has proper Signed-Off-By
- [ ] Has commit message which describes it
- [ ] Is needed on it's own, if you have just minor fixes to previous commits, you can squash them
- [ ] Any new functionality is covered by tests
Fixes: https://github.com/phpmyadmin/phpmyadmin/issues/13090
Accidentally deleted PR : https://github.com/phpmyadmin/phpmyadmin/pull/13871

2017-12-21 01:48 UTC, MauricioFauth requested changes

2017-12-21 01:48 UTC, mauriciofauth commented on libraries/classes/Index.php
> +                        $r .= '<tr class="noclick" id="even_row" >';
I don't think this is the proper solution to this issue, as there is the CSS's [`:nth-child()`](https://developer.mozilla.org/en-US/docs/Web/CSS/:nth-child) pseudo-class that serves that purpose.
I think a more appropriate solution would be to wrap the entire row and apply the pseudo-class to the entire row instead of just applying to the `<tr>` tag.
Perhaps this happens with other tables that also make use of rowspan. It would be good to check this out.

2017-12-21 10:30 UTC, shucon commented on libraries/classes/Index.php
> +                        $r .= '<tr class="noclick" id="even_row" >';
@mauriciofauth the CSS's :nth-child() pseudo-class is creating the problems , that's why I created another class to override it . I'll see what else could be done.

2017-12-30 17:02 UTC, shucon commented
@mauriciofauth please review the changes.

2018-01-13 17:38 UTC, MauricioFauth requested changes

2018-01-13 17:38 UTC, mauriciofauth commented on libraries/classes/Index.php
> +                    if($iter%2 == 0){
I think that adding an iterator isn't the best option, besides not solving the problem completely, since `:nth-child()` pseudo-class already does this function.

A possible solution to this problem would be to add a `div`, or another tag, that wraps each index row and apply the pseudo-class to that `div` instead of applying it to the `tr`.

2018-01-23 18:52 UTC, shucon commented
@mauriciofauth I've done the required changes.

2018-01-25 22:48 UTC, MauricioFauth requested changes

2018-01-25 22:48 UTC, mauriciofauth commented on themes/pmahomme/css/common.css.php
> +#table_index tbody:nth-child(even) tr {
This solution is much closer to the expected result, but it still has some problems.
See:
![screenshot from 2018-01-25 19-50-31](https://user-images.githubusercontent.com/120970/35414307-39ed3e00-0209-11e8-9adf-de1d8cda143c.png)

The first problem is that the Keyname column is not being colored. But this can be solved by adding the `th` selector to the rule set. For example:
```css
#table_index tbody:nth-child(even) tr,
#table_index tbody:nth-child(even) th
```

Another problem is that the colors of the rows are inverted, because the `:nth-child()` pseudo-class is counting the `<thead>` as the first element. This can be solved by replacing `:nth-child()` with the [`:nth-of-type()`](https://developer.mozilla.org/en-US/docs/Web/CSS/:nth-of-type) pseudo-class.

2018-01-29 16:41 UTC, MauricioFauth approved these changes

2018-01-29 16:43 UTC, merged

2018-01-29 16:46 UTC, mauriciofauth commented
Merged, thanks for your contribution and patience with my feedback!