Remove font size feature
phpmyadmin/phpmyadmin pull request #13925
Opened 2018-01-11 09:41 UTC by shucon

https://github.com/phpmyadmin/phpmyadmin/issues/13919
Signed-off-by: Saksham Gupta <shucon01@gmail.com>

Before submitting pull request, please check that every commit:

- [ ] Has proper Signed-Off-By
- [ ] Has commit message which describes it
- [ ] Is needed on it's own, if you have just minor fixes to previous commits, you can squash them
- [ ] Any new functionality is covered by tests

2018-01-13 18:37 UTC, mauriciofauth commented
Apparently you just remove the font size form. The font size feature goes beyond that.

2018-01-23 18:23 UTC, shucon commented
@mauriciofauth is this good?

2018-01-27 18:00 UTC, mauriciofauth commented
In addition to removing the form, I think removing the [`FontSize` configuration directive](https://docs.phpmyadmin.net/en/latest/config.html#cfg_FontSize) is also necessary.

2018-01-29 17:02 UTC, devenbansod commented
Hi @shucon I tried restarting the selenium job but the same test `PhpMyAdmin\Tests\Selenium\SettingsTest::testHideDatabase` failed again. Attached is the screen recording of them same. 

I'd recommend you to try running the test locally (or run down the flow manually), if it fails that'd mean that your changes in this PR unknowingly seem to have broken the flow being tested in the above test or the test has been broken since a last few commits but no one caught it.

![bs-video-logs-use-2-](https://user-images.githubusercontent.com/5762808/35523147-2dbf414e-0544-11e8-8c24-607908bcb6e5.gif)

2018-01-29 17:04 UTC, devenbansod commented
Also, I can see an error on the settings page saying: 'Field FontSize has no type' which seems related to this PR.

2018-01-29 18:51 UTC, shucon commented
@devenbansod both the issues are fixed on my side , can you please confirm the same .

2018-02-01 00:24 UTC, mauriciofauth commented on test/classes/ConfigTest.php
> -        $fontsize = $GLOBALS['PMA_Config']->get('FontSize');
There are more places where the _FontSize_ setting is used with the Config class.

2018-02-16 15:17 UTC, mauriciofauth commented
This pull request is incomplete, there are still several places where the FontSize configuration is used.

2018-03-02 17:27 UTC, shucon commented
@mauriciofauth is this sufficient?

2018-03-15 01:46 UTC, mauriciofauth commented on themes/pmahomme/css/common.css.php
> -}
You need to keep the font-size property here.

2018-03-15 01:57 UTC, mauriciofauth commented on libraries/classes/Config.php
>      public function getThemeUniqueValue()
You should update the doc for this method to reflect the changes.

2018-03-15 02:05 UTC, mauriciofauth commented
I don't think it's a good idea to include this in 4.8 branch. This is a major change and should only be included in 5.0 branch.

2018-03-15 09:29 UTC, shucon commented on libraries/classes/Config.php
>      public function getThemeUniqueValue()
I can't find anything related to this in the doc, please help.

2018-03-15 22:25 UTC, shucon commented
@mauriciofauth everything good now?

2018-03-16 06:45 UTC, MauricioFauth approved these changes

2018-04-08 11:33 UTC, shucon commented on doc/config.rst
> -
Okay, got it! I'll fix it.

2018-04-13 23:19 UTC, MauricioFauth requested changes

2018-04-14 10:21 UTC, merged