change #tablefieldscontainer select height setting to syn better with .CodeMirror height for #13124
phpmyadmin/phpmyadmin pull request #13946
Opened 2018-01-18 16:12 UTC by xypXiong

Before submitting pull request, please check that every commit:

- [ ] Has proper Signed-Off-By
- [ ] Has commit message which describes it
- [ ] Is needed on it's own, if you have just minor fixes to previous commits, you can squash them
- [ ] Any new functionality is covered by tests

2018-01-18 16:14 UTC, xypXiong commented
after adjusting, firefox and chrome look nicer, however, IE looks more off. Seems can't make all three  good altogether

2018-01-19 19:24 UTC, xypXiong commented
If we use pixel instead of em, we could get all three browsers behave same . Pixel is independent with the font size. But they will be not something related with $cfg['TextareaRows'] settings. Any thought about it?

2018-01-29 17:27 UTC, mauriciofauth commented
Hi, @xypXiong. Thanks for your contribution!
You included the `.metadata` directory, but I don't think that was your intention. Could you remove it?

2018-01-29 17:52 UTC, ibennetch commented
There's certainly a place for using pixels instead of em or percentages, but in general I try to avoid defining sizes in pixels. I know we do it a lot in the theme code, and it may be the best way here, but just my two cents is that using pixels isn't always the best solution. Others may disagree, of course.

2018-01-30 15:39 UTC, xypXiong commented
@mauriciofauth I have removed the .meta dir, please take a look. @ibennetch the current version still uses em which makes firefox and chrome looks better. Hope this something at least better than before. thanks

2018-03-24 03:53 UTC, MauricioFauth requested changes

2018-03-24 03:53 UTC, mauriciofauth commented on themes/pmahomme/css/common.css.php
> +     height: 192px;
Using a fixed value in pixels is not a good choice because height is influenced by [`$cfg['TextareaRows']`](https://docs.phpmyadmin.net/en/latest/config.html#cfg_TextareaRows) and [`$cfg['CodemirrorEnable']`](https://docs.phpmyadmin.net/en/latest/config.html#cfg_CodemirrorEnable).

2018-03-26 13:33 UTC, xypXiong commented
Thanks, currently I don't use fixed pixels. 

    Maurício Meneghini Fauth <notifications@github.com> 于 2018年3月23日, 星期五, 下午 11:54 写道：
 

 @mauriciofauth requested changes on this pull request.In themes/pmahomme/css/common.css.php:> @@ -1622,7 +1622,8 @@
 div#tablefieldscontainer select {
     width: 100%;
     background: #fff;
-    /* height: 12em; */
+   /* height: <?php echo ceil($GLOBALS['cfg']['TextareaRows'] * 1.2)-3.35; ?>em; */
+     height: 192px;
Using a fixed value in pixels is not a good choice because height is influenced by $cfg['TextareaRows'] and $cfg['CodemirrorEnable'].—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.

2018-07-18 14:57 UTC, closed without merging