Prompt before reducing number of rows
phpmyadmin/phpmyadmin pull request #13987
Opened 2018-02-10 15:25 UTC by shucon

Fixes: https://github.com/phpmyadmin/phpmyadmin/issues/13952

Signed-off-by: Saksham Gupta <shucon01@gmail.com>

Before submitting pull request, please check that every commit:

- [ ] Has proper Signed-Off-By
- [ ] Has commit message which describes it
- [ ] Is needed on it's own, if you have just minor fixes to previous commits, you can squash them
- [ ] Any new functionality is covered by tests

2018-02-10 16:46 UTC, ibennetch commented on js/messages.php
> +    = __('You have unsaved changes; are you sure you want to reduce number of rows?');
Your message is okay, but I've been trying to make error messages and warnings more user-friendly. How does "You are trying to reduce the number of rows, but have already entered data in those rows which will be lost. Do you wish to continue?" sound to everyone?

2018-02-10 16:46 UTC, ibennetch commented
I haven't tested it but this looks quite good.

2018-02-10 17:23 UTC, mauriciofauth commented on js/ajax.js
> +        row.addEventListener("change", function(){
An event listener already exists for this selector. Why not use it?

https://github.com/phpmyadmin/phpmyadmin/blob/ef99fef8d6b760a2f3552c89afe50ba6d5562add/js/tbl_change.js#L463

2018-02-11 14:30 UTC, devenbansod commented on js/ajax.js
>      /**
@shucon I'm not sure if this file would be an ideal place to add this function. It's not related to AJAX as such, more related to a specific page.

2018-02-11 14:48 UTC, shucon commented on js/ajax.js
>      /**
@devenbansod I did this for two reasons.
1. A similar function for the same page is written here (line 249).
2. I had to use AJAX.lockedTargets . Although I could use it anywhere but writing it here seemed right because of the above reason.

2018-02-14 14:08 UTC, MauricioFauth requested changes

2018-02-14 14:08 UTC, mauriciofauth commented on js/ajax.js
> +        if (newCount < rowCount && !jQuery.isEmptyObject(AJAX.lockedTargets)
You don't need to check if the number of rows the user entered is less than or greater than the number of rows on the page. This check already exists, you only need to add the confirmation message.

2018-02-14 14:08 UTC, mauriciofauth commented on js/tbl_change.js
> +        rowCount = AJAX.rowCheck(row, rowCount);
You are returning a value, but you are not using it for anything.

2018-02-14 14:09 UTC, mauriciofauth commented on js/ajax.js
>      /**
I have to agree with Deven.

2018-02-14 14:12 UTC, shucon commented on js/ajax.js
> +        if (newCount < rowCount && !jQuery.isEmptyObject(AJAX.lockedTargets)
Where does this check exists? Also , I would have to provide some condition to show the confirmation message.

2018-02-14 14:13 UTC, shucon commented on js/tbl_change.js
> +        rowCount = AJAX.rowCheck(row, rowCount);
I'm using the returned value to update the old row count and compare it with the new count that the user wants to check the rowCheck condition.

2018-02-14 14:15 UTC, shucon commented on js/ajax.js
>      /**
Should I transfer the code to tbl_change.js ?

2018-02-14 14:19 UTC, mauriciofauth commented on js/ajax.js
> +        if (newCount < rowCount && !jQuery.isEmptyObject(AJAX.lockedTargets)
This check is already done when adding or removing lines from the page.

https://github.com/phpmyadmin/phpmyadmin/blob/ef99fef8d6b760a2f3552c89afe50ba6d5562add/js/tbl_change.js#L483

https://github.com/phpmyadmin/phpmyadmin/blob/ef99fef8d6b760a2f3552c89afe50ba6d5562add/js/tbl_change.js#L669

2018-02-14 14:53 UTC, shucon commented on js/ajax.js
> +        if (newCount < rowCount && !jQuery.isEmptyObject(AJAX.lockedTargets)
Thanks @mauriciofauth I've done the required changes.

2018-02-14 19:41 UTC, MauricioFauth requested changes

2018-02-14 19:41 UTC, mauriciofauth commented on js/tbl_change.js
> +            ) {
Don't perform complex actions in if statements. Put this jQuery call into a variable.

This second jQuery call is redundant and can be removed. The right side of the `||` will only run if the left side is false.

2018-02-14 19:41 UTC, mauriciofauth commented on js/tbl_change.js
> +                    document.getElementById('insert_rows').value = curr_rows;
Fix the indentation of this block.

2018-02-14 19:45 UTC, mauriciofauth commented on js/tbl_change.js
> +         */
Is this comment really necessary?

2018-02-14 19:48 UTC, shucon commented on js/tbl_change.js
> +         */
I left it by mistake , thanks.

2018-02-14 19:51 UTC, shucon commented on js/tbl_change.js
> +            ) {
@mauriciofauth this jQuery call is used in ajax.js too without variable

2018-02-14 20:25 UTC, MauricioFauth approved these changes

2018-02-14 21:35 UTC, merged

2018-02-14 21:38 UTC, mauriciofauth commented
Squashed and merged.
Thanks for your contribution and patience with the feedback.