Fix for issue #13959
phpmyadmin/phpmyadmin pull request #14001
Opened 2018-02-12 18:07 UTC by nulll-pointer

Changed files:
	themes/original/css/common.css.php
	themes/pmahomme/css/common.css.php
Added style definition for .responsivetable element to prevent horizontal overflow
Signed-Off-By: Lakshay arora (b16060@students.iitmandi.ac.in)

Before submitting pull request, please check that every commit:

- [ ] Has proper Signed-Off-By
- [ ] Has commit message which describes it
- [ ] Is needed on it's own, if you have just minor fixes to previous commits, you can squash them
- [ ] Any new functionality is covered by tests

2018-02-12 18:35 UTC, MauricioFauth requested changes

2018-02-12 18:35 UTC, mauriciofauth commented on themes/original/css/common.css.php
> +    overflow-x: auto !important;
Using `!important` is generally not recommended. Could you solve it differently?

2018-02-12 18:36 UTC, nulll-pointer commented on themes/original/css/common.css.php
> +    overflow-x: auto !important;
It works without important, i just added it for safety reasons.

2018-02-12 18:44 UTC, nulll-pointer commented on themes/original/css/common.css.php
> +    overflow-x: auto !important;
i could remove it if you suggest.

2018-02-16 14:43 UTC, merged

2018-02-16 14:44 UTC, mauriciofauth commented
Merged, thanks for your contribution!