Restore SQL query after session expire
phpmyadmin/phpmyadmin pull request #14046
Opened 2018-02-28 20:51 UTC by shucon

Partially Fixes: https://github.com/phpmyadmin/phpmyadmin/issues/13654

Signed-off-by: Saksham Gupta <shucon01@gmail.com>

Before submitting pull request, please check that every commit:

- [ ] Has proper Signed-Off-By
- [ ] Has commit message which describes it
- [ ] Is needed on it's own, if you have just minor fixes to previous commits, you can squash them
- [ ] Any new functionality is covered by tests

2018-02-28 20:54 UTC, shucon commented
Once this is approved I'll try to do something similar for Insert page.

2018-03-01 06:53 UTC, nijel requested changes
It should handle values stored in cookies as well, preferably reusing existing code.

2018-03-01 06:53 UTC, nijel commented on js/sql.js
> +    codemirror_editor.setValue(window.localStorage.auto_saved_sql);
There is already code to handle this:

https://github.com/phpmyadmin/phpmyadmin/blob/733a3f1c0b16ca0fe486fecf5940c3143fdda651/js/functions.js#L1180-L1187

So it should load it from cookies as well (`insertQuery('saved')` would do it, but it would also error on no saved query what is not desired behavior here).

2018-03-10 21:35 UTC, shucon commented
@nijel I think it's ok now, can you please review it?

2018-03-16 10:08 UTC, nijel commented on js/sql.js
> +        Cookies.set('auto_saved_sql', query);
Should it really save the empty query here?

2018-03-16 10:16 UTC, shucon commented on js/sql.js
> +        Cookies.set('auto_saved_sql', query);
Yes, because if the query is empty then on restore the last character was saved and got restored, that wasn't looking good.

2018-03-16 12:07 UTC, merged

2018-03-16 12:07 UTC, nijel commented
Merged, thanks for your contribution!