Enable columns names by default for CSV in issue #14007 solved
phpmyadmin/phpmyadmin pull request #14076
Opened 2018-03-13 06:41 UTC by rijaspk

Enable columns names by default for CSV
Added a export  type check for CSV 
IF true added csv columns 
fixes issue #14007

Signed-off-by: Rijas Ahammed PK Rijaspk5195@gmail.com

Before submitting pull request, please check that every commit:

- [x] Has proper Signed-Off-By
- [x] Has commit message which describes it
- [ ] Is needed on it's own, if you have just minor fixes to previous commits, you can squash them
- [ ] Any new functionality is covered by tests

2018-03-30 05:52 UTC, MauricioFauth requested changes

2018-03-30 05:52 UTC, mauriciofauth commented on libraries/classes/Plugins/Export/ExportCsv.php
> +            $GLOBALS['csv_columns'] = 'yes';
Hi, @rijaspk. Thanks for your contribution.
Before we can merge your pull request, we would like you to make the following changes.
The body of the `if` structure must be enclosed by braces and there must be a space between the `if` keyword and the parenthesis.

2018-04-02 05:58 UTC, rijaspk commented on libraries/classes/Plugins/Export/ExportCsv.php
> +            $GLOBALS['csv_columns'] = 'yes';
Hi, @mauriciofauth. Required changes are implemented.

2018-04-05 01:28 UTC, merged

2018-04-05 01:30 UTC, mauriciofauth commented
Merged, thanks for your contribution!

2018-04-06 05:25 UTC, rijaspk commented
Hi, @mauriciofauth Thanks for reveiwing and accepting my PR