added a keyboard shortcut n for directly jumping for creating a new database
phpmyadmin/phpmyadmin pull request #14095
Opened 2018-03-18 04:36 UTC by akshilshah

added a keyboard shortcut n for directly jumping for creating a new database

Signed-off-by: Akshil shah <akshilshah4444@gmail.com>

Before submitting pull request, please check that every commit:

- [x] Has proper Signed-Off-By
- [x] Has commit message which describes it
- [x] Is needed on it's own, if you have just minor fixes to previous commits, you can squash them
- [x] Any new functionality is covered by tests

2018-03-30 05:59 UTC, mauriciofauth commented on js/vendor/jquery/jquery-migrate.js
> +/*! jQuery Migrate v3.0.1 | (c) jQuery Foundation and other contributors | jquery.org/license */
Hi, @akshil4444. Updating jQuery Migrate does not seem to be related to this PR. Could you remove this change? Thank you.

2018-03-30 13:09 UTC, ibennetch requested changes

2018-03-30 13:09 UTC, ibennetch commented on js/shortcuts_handler.js
> +            window.open('http://localhost/phpmyadmin/server_databases.php?server=1', '_self');
This takes me to an error page that says "Unable to connect. Firefox can’t establish a connection to the server at localhost."

2018-03-30 13:15 UTC, ibennetch commented
I'm not sure how we want to handle shortcut keys; this may not be the best way (for instance, the last time this came up we discussed how "N" for "new" makes sense in English, but not for all other languages where the word "new" translates to something that doesn't start with an 'n'.

2018-03-31 03:03 UTC, akshil4444 commented on js/shortcuts_handler.js
> +            window.open('http://localhost/phpmyadmin/server_databases.php?server=1', '_self');
confirmed, working on this.

2018-04-15 04:38 UTC, akshil4444 commented on js/shortcuts_handler.js
> +            window.open('http://localhost/phpmyadmin/server_databases.php?server=1', '_self');
@ibennetch The firefox error gives only for the first time and it's actually not an error as it is working.  After that, if you try to do the same there won't be any error. I actually don't know for what reason is the error occurred for the initial time.

2018-05-12 12:56 UTC, saulotoledo commented on js/shortcuts_handler.js
> +            window.open('http://localhost/phpmyadmin/server_databases.php?server=1', '_self');
@akshil4444 I suggest to change the port of your local HTTP server and test again.

2018-07-18 13:57 UTC, closed without merging