Fix bugs in SQL query restore after session expire
phpmyadmin/phpmyadmin pull request #14094
Opened 2018-03-18 00:09 UTC by shucon

Fixes: https://github.com/phpmyadmin/phpmyadmin/issues/14093
Also, the sql query was getting stored in the browser indefinetly even after visiting another page and then coming back. So it had to be cleared from localstorage on page change.

Signed-off-by: Saksham Gupta <shucon01@gmail.com>

Before submitting pull request, please check that every commit:

- [ ] Has proper Signed-Off-By
- [ ] Has commit message which describes it
- [ ] Is needed on it's own, if you have just minor fixes to previous commits, you can squash them
- [ ] Any new functionality is covered by tests

2018-03-27 20:15 UTC, shucon commented on libraries/classes/SqlQueryForm.php
> +        $html .= ' onsubmit=window.localStorage.auto_saved_sql=""';
Most places have inline onsubmit present in forms so maintain the same coding style I preferred inline js.

2018-03-27 20:17 UTC, shucon commented on libraries/classes/SqlQueryForm.php
> +        $html .= ' onsubmit=window.localStorage.auto_saved_sql=""';
Okay, so all the onsubmit js are inline and needs to be changed, so I'll just fix this one here.

2018-03-30 23:35 UTC, MauricioFauth requested changes
The "Get auto-saved query" button has no more action after these changes.

2018-03-31 01:48 UTC, shucon commented
@mauriciofauth Get auto-saved query is not working on master branch too. I'll check it and try to fix that too.

2018-05-03 19:50 UTC, closed without merging

2018-05-03 19:56 UTC, mauriciofauth commented
Thanks for your contribution.
Closing this PR in favor of #14166.