Addapt getHtmlForAddColumn to use twig template
phpmyadmin/phpmyadmin pull request #14107
Opened 2018-03-21 02:26 UTC by laps15

I started to adapt some functions that returns html string and are not yet using Twig templates.

Signed-off-by: Leonardo Strozzi <laps15@inf.ufpr.br>

Before submitting pull request, please check that every commit:

- [x] Has proper Signed-Off-By
- [x] Has commit message which describes it
- [x] Is needed on it's own, if you have just minor fixes to previous commits, you can squash them
- [x] Any new functionality is covered by tests

2018-03-21 03:36 UTC, MauricioFauth requested changes
You need to change the test for this method to reflect the changes.

See https://travis-ci.org/phpmyadmin/phpmyadmin/jobs/356166110#L700

2018-03-21 03:36 UTC, mauriciofauth commented on libraries/classes/CentralColumns.php
> +         $hidden_inputs = Url::getHiddenInputs($db);
You can replace these methods with their respective Twig extensions.
For example: `{{ Url_getHiddenInputs(db) }}`

2018-03-21 03:36 UTC, mauriciofauth commented on templates/database/central_columns/add_column.twig
> +          <option value="" selected="selected">Select a column.</option>
You must make this string translatable. In that case you can use the `trans` tag.
For example: `{% trans 'Select a column.' %}`

2018-03-21 03:36 UTC, mauriciofauth commented on templates/database/central_columns/add_column.twig
> +  </tr>
We are using four spaces for the indentation of the twig files.

2018-03-22 03:40 UTC, merged

2018-03-22 03:41 UTC, mauriciofauth commented
Merged, thanks for your contribution!