Remove inline styles from Relation.php
phpmyadmin/phpmyadmin pull request #14141
Opened 2018-03-28 11:39 UTC by mohitjawanjal

Related to #12262 

Signed-off-by: Mohit Jawanjal <mohit.jawanjal@imnica.com>

Before submitting pull request, please check that every commit:

- [ ] Has proper Signed-Off-By
- [ ] Has commit message which describes it
- [ ] Is needed on it's own, if you have just minor fixes to previous commits, you can squash them
- [ ] Any new functionality is covered by tests

2018-03-28 16:50 UTC, mauriciofauth commented on libraries/classes/Relation.php
> +        $messages['error'] = '<span class="span_color_red"><strong>'
You can use the `caution` class here. See:
https://github.com/phpmyadmin/phpmyadmin/blob/695fe3a994b18ad21a4c1119305e25edd71c7036/themes/pmahomme/css/common.css.php#L1026-L1028

2018-03-30 21:14 UTC, mauriciofauth commented on libraries/classes/Relation.php
> +        $messages['enabled']  = '<span class="span_color_green">' . __('Enabled') . '</span>';
Great! Once you submit the new changes, we can merge this pull request.

2018-04-02 06:10 UTC, mohitjawanjal commented
Sorry my git kung-fu is not very good today. :( Going to re-submit it on a different PR. @mauriciofauth Do you think creating a new branch would be a good idea or should I work with master?

2018-04-02 08:40 UTC, MauricioFauth requested changes

2018-04-02 08:40 UTC, mauriciofauth commented on themes/original/css/common.css.php
> +}
Could you add the new line at the end of file again?

2018-04-02 08:40 UTC, mauriciofauth commented on themes/pmahomme/css/common.css.php
> +}
Could you add the new line at the end of file again?

2018-04-02 08:42 UTC, mauriciofauth commented
@mohitjawanjal You can keep the master branch in this PR, but it is recommended to use a separate branch.

2018-04-02 08:44 UTC, mauriciofauth commented on themes/pmahomme/css/common.css.php
> +    color: green;
This line contains trailing whitespace. Could you remove it?

2018-05-03 15:52 UTC, merged

2018-05-03 15:52 UTC, mauriciofauth commented
Merged, thanks for your contribution!