Fix for "No tables found" problem on deleting tables in the last tab, #14205
phpmyadmin/phpmyadmin pull request #14218
Opened 2018-04-20 19:52 UTC by nulll-pointer

Signed-Off-By: Lakshya arora <arora.lakshya123@gmail.com>

Before submitting pull request, please check that every commit:

- [ ] Has proper Signed-Off-By
- [ ] Has commit message which describes it
- [ ] Is needed on it's own, if you have just minor fixes to previous commits, you can squash them
- [ ] Any new functionality is covered by tests

2018-06-17 02:57 UTC, ibennetch commented
I apparently have better luck than Maurício did; it worked for me. After deleting the table, the navigation pane did not update; I had to manually use the `<` button to go to the previous page, but I did not get an error.

I wonder if a better solution would be to automatically refresh/move the user to the new last page.

This isn't a bad or wrong solution as-is, but I wonder if we can do better for presenting a smooth interface to the user.

2018-06-17 09:54 UTC, nulll-pointer commented
@mauriciofauth  @ibennetch , try hard reload. Probably, it's loading the script from the cache.

2018-06-28 18:12 UTC, MauricioFauth reviewed
I tried again, checked that the script had been loaded correctly, but the issue keeps happening.

2018-07-02 17:40 UTC, nulll-pointer commented
I'm looking into it.

2018-08-08 11:06 UTC, ibennetch commented
I know this one wasn't part of the GSoC plan, but did you figure out what was wrong?

2018-08-16 07:45 UTC, MauricioFauth requested changes

2018-08-16 07:45 UTC, mauriciofauth commented on js/navigation.js
> +            if( $('#pma_navigation_tree').find('li.database.selected').children('div.list_container').find('li.table').length === 1) {
ESLint failed. See: https://travis-ci.org/phpmyadmin/phpmyadmin/jobs/414006024#L744

2018-08-16 13:25 UTC, nulll-pointer commented on js/navigation.js
> +            if( $('#pma_navigation_tree').find('li.database.selected').children('div.list_container').find('li.table').length === 1) {
I've fixed it, kindly have a look.

2018-08-18 08:51 UTC, nulll-pointer commented
@mauriciofauth, fixed

2018-08-19 22:48 UTC, MauricioFauth reviewed
@nulll-pointer Now I realize that we are not seeing the same thing.
You are looking at the list of tables in the navigation menu. However, the issue is about the list of tables in the database Structure tab.
You can see the pagination if you change the maximum number of tables, for example: `$cfg['MaxTableList'] = 2;`
Now go to the last page and drop all the tables. You will see the message _No tables found in database._
The only ways I found to stop seeing this message was by changing the database or manually adding the `pos` parameter, for example: `db_structure.php?db=sakila&pos=0`

2018-08-20 09:10 UTC, nulll-pointer commented
oh, yes. But, this was also a bug :smile:

2018-08-21 19:43 UTC, mauriciofauth commented
@nulll-pointer Yes, you've found a related bug. :)

2019-03-01 12:58 UTC, williamdes commented
@sudo-bot Deploy PR

2019-03-01 19:36 UTC, williamdes requested changes
This PR did not solve the issue from my tests

2019-03-26 18:52 UTC, williamdes commented
Closing since this PR does not solve the issue, sorry.

2019-03-26 18:52 UTC, closed without merging