Date selection in search menu missing higher Z-index value
phpmyadmin/phpmyadmin pull request #14251
Opened 2018-05-03 10:02 UTC by rijaspk

Date selection in search menu missing a higher Z-index value
Issue #14248

Signed-off-by: Rijas Ahammed PK <rijaspk5195@gmail.com>

Before submitting pull request, please check that every commit:

- [x] Has proper Signed-Off-By
- [x] Has commit message which describes it
- [ ] Is needed on it's own, if you have just minor fixes to previous commits, you can squash them
- [ ] Any new functionality is covered by tests

2018-05-05 22:53 UTC, MauricioFauth reviewed
@rijaspk Thanks for your contribution.

2018-05-05 22:53 UTC, mauriciofauth commented on themes/original/jquery/jquery-ui.css
> +       z-index: 99 !important;
Do you have any other way to solve it without using `!important`?

2018-05-07 06:01 UTC, rijaspk commented on themes/original/jquery/jquery-ui.css
> +       z-index: 99 !important;
Hi @mauriciofauth, Date picker UI used Inline style and unfortunately I couldn't find the file where it is written. Can you help me find that file

2018-05-12 12:38 UTC, saulotoledo requested changes

2018-05-12 12:38 UTC, saulotoledo commented on themes/original/jquery/jquery-ui.css
> +       z-index: 100;
This file uses tab as indent, please fix it.

2018-05-12 12:38 UTC, saulotoledo commented on themes/original/jquery/jquery-ui.css
> +       z-index: 99 !important;
Hi everyone. I am new here, but I would like to head the opinion of an old repository reviewer about. This is a JQuery UI file, so I think we should do these changes in another place, not here. Are we really allowed do change these files?

2018-06-25 23:52 UTC, mauriciofauth commented on js/server_databases.js
> +        if (newDbNameInput.val() == '') {
This change does not appear to be related to this pull request.
If this is fixing another issue, it is better to open a new pull request with this change.

2018-06-26 00:09 UTC, mauriciofauth commented on themes/original/jquery/jquery-ui.css
> +       z-index: 99 !important;
Hi, @saulotoledo. You're right, this is a jQuery UI file. Although this file already contains some changes, I agree that we should not edit this file, and that those changes should go elsewhere.

2018-09-01 01:05 UTC, closed without merging