Automated Theme generator
phpmyadmin/phpmyadmin pull request #14293
Opened 2018-05-15 10:31 UTC by shucon

For easy access to my work progress and any suggestions.

Before submitting pull request, please check that every commit:

- [x] Has proper Signed-Off-By
- [x] Has commit message which describes it
- [x] Is needed on it's own, if you have just minor fixes to previous commits, you can squash them
- [x] Any new functionality is covered by tests

2018-05-15 16:51 UTC, Piyush3079 commented on js/theme_generator/color_picker.js
> +var UIColorPicker = (function UIColorPicker() {
Is this a library of javascript?

2018-05-16 08:16 UTC, shucon commented on js/theme_generator/color_picker.js
> +var UIColorPicker = (function UIColorPicker() {
yes

2018-05-16 17:04 UTC, shucon commented on theme_generator.php
> +$response->addHTML('<div id="container">');
I may go with creating a twig template, as I'll be making preview panels later.

2018-05-16 17:07 UTC, shucon commented on theme_generator.php
> +$response->addHTML('<div id="container">');
I have  created a mockup for the same https://researchweb.iiit.ac.in/~saksham.gupta/mockup2.jpg

2018-06-03 16:27 UTC, mauriciofauth commented on js/theme_generator/color_picker.js
> +var UIColorPicker = (function UIColorPicker() {
Did you write this library or is it a third-party library?

2018-06-03 16:32 UTC, mauriciofauth commented on libraries/classes/ThemeGenerator.php
> +        return $output;
It would be better to use Twig templates instead of adding HTML directly in the code.

2018-06-03 16:38 UTC, mauriciofauth commented on js/theme_generator/color_picker.js
> + * Library for the Color Picker Tool
Did you write this library or is it a third-party library?

2018-06-04 18:31 UTC, shucon commented on libraries/classes/ThemeGenerator.php
> +        return $output;
As I have to read about twig, I'll fix it in the end.

2018-06-04 18:33 UTC, shucon commented on js/theme_generator/color_picker.js
> + * Library for the Color Picker Tool
Part of it is written and edited by me and part of it is a third-party library from https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Colors/Color_picker_tool

2018-06-05 23:34 UTC, mauriciofauth commented on js/theme_generator/color_picker.js
> + * Library for the Color Picker Tool
I was only concerned with the license to use the code, but it seems that this code is under public domain, so no problems.

2018-06-05 23:42 UTC, mauriciofauth commented on libraries/classes/ThemeGenerator.php
> +        return $output;
No problem.

2018-06-09 22:47 UTC, shucon commented on libraries/classes/ThemeGenerator.php
> +        return $output;
Is it fine now?

2018-06-16 13:17 UTC, ibennetch reviewed
I think you're on a good path here. I've added some comments and suggestions about the tests.

2018-06-16 13:17 UTC, ibennetch commented on test/classes/Theme/LayoutTest.php
> +    public function createLayoutFile($post , $output)
I'm not sure about this test. It looks to me like it's just testing whether the layout.inc.php file exists and contains the NaviBackground directive. I'm a little weak on our unit tests, to be honest, but I don't think this is really testing any of your code; it's instead testing something on the file system which is sort of beyond the scope of what we should be testing, unless we use the function that directly writes the file and test against the output, but even then it's better to just test the function output directly as you do in testcolorPicker().

I _think_ this is unnecessary, but would love for another developer to chime in if I'm wrong.

2018-06-16 13:17 UTC, ibennetch commented on test/classes/ThemeGeneratorTest.php
> +    public function createJsonFile($name , $output)
This seems fine to me because you're creating the file and testing the output all at once.

2018-06-16 13:17 UTC, ibennetch commented on test/classes/ThemeGeneratorTest.php
> +    public function testcreateFileStructure()
I think testCreateFileStructure() is a better name here as well.

2018-06-16 13:17 UTC, ibennetch commented on test/classes/ThemeGeneratorTest.php
> +    public function testform()
I think testForm() would be a better name.

2018-06-16 13:35 UTC, shucon commented on test/classes/Theme/LayoutTest.php
> +    public function createLayoutFile($post , $output)
I haven't completed all my tests for this function, but I feel it is an important test as any failed tests in this function would mean that the whole theme would be screwed. The layout file would be used as a function for all other files. Any failed test would mean a lot of errors.

2018-06-16 19:13 UTC, ibennetch commented on libraries/classes/Theme/Common.php
> +        $txt .= '#main_p
I doubt all this was fun or glamorous to copy/paste and format! :-o

2018-06-16 19:13 UTC, ibennetch commented on libraries/classes/ThemeGenerator.php
> +        $txt .= '"version": "5.0",';
Do you plan to allow the user to set the version number from the theme generator interface?

2018-06-16 19:17 UTC, shucon commented on libraries/classes/ThemeGenerator.php
> +        $txt .= '"version": "5.0",';
I don't know what's the use of version number, so right now it's what the other themes are using.

2018-06-16 19:22 UTC, shucon commented on libraries/classes/Theme/Common.php
> +        $txt .= '#main_p
No it wasn't :stuck_out_tongue: . Although I learned a bit of regex and some efficient ways while formatting them.

2018-06-18 15:05 UTC, ibennetch commented on libraries/classes/Theme/Common.php
> +        $file = fopen("themes/" . $name . "/css/common.css.php", "w");
Just posting this here for completeness after our Hangouts chat earlier this weekend.

On further review, I think I was mistaken about fopen(). I believe I was incorrectly remembering the configuration directive `allow_url_fopen` which of course won't affect us.

Of course we should still fail gracefully if fopen() doesn't work, but we don't need to test for it as I first thought.

2018-06-18 15:22 UTC, ibennetch commented on libraries/classes/ThemeGenerator.php
> +        $txt .= '"version": "5.0",';
I can help a bit with this: version numbers are set by whoever makes the themes and they're completely arbitrary. From the themes repository, we have version numbers like 2.8, 1.0b, 0.2, and more...they don't really correspond to anything. Sometimes a pull request for a theme will bump the version number by a full number (from 2.5 to 3.0), other times it's an incremental change (from 2.7 to 2.8). I don't even know what the 1.0b is supposed to be.

There's nothing tying theme version numbers to phpMyAdmin version numbers, either.

I'd say we should let the theme designer add their own theme version number, description, author name, and URL.

2018-06-19 01:50 UTC, shucon commented on libraries/classes/ThemeGenerator.php
> +        $txt .= '"version": "5.0",';
What if the user leaves the fields? What should be the default value?

2018-07-11 05:52 UTC, mauriciofauth commented on libraries/classes/Theme/Common.php
> +namespace PhpMyAdmin\Theme;
I'm not very sure about this namespace. What if it was `PhpMyAdmin\Theme\Generator` or `PhpMyAdmin\ThemeGenerator`? What do you think?

2018-07-11 05:52 UTC, mauriciofauth commented on libraries/classes/Theme/Common.php
> +        $txt .= '#main_p
I think you would make good use of the [heredoc syntax](http://php.net/manual/en/language.types.string.php#language.types.string.syntax.heredoc) or [nowdoc syntax](http://php.net/manual/en/language.types.string.php#language.types.string.syntax.nowdoc) here.

2018-07-11 05:52 UTC, mauriciofauth commented on libraries/classes/Theme/Common.php
> +        $txt .= '#main_p
You can remove this return. This way, the return of the method will be considered as `void`.

2018-07-11 10:04 UTC, shucon commented on libraries/classes/Theme/Common.php
> +        $txt .= '#main_p
Is it necessary?? I have already changed the format once, so if it's not necessary can we leave it like this?

2018-07-11 10:07 UTC, shucon commented on libraries/classes/Theme/Common.php
> +namespace PhpMyAdmin\Theme;
Yes! I'll correct it.

2018-07-21 02:35 UTC, ibennetch commented on libraries/classes/ThemeGenerator.php
> +        $file = fopen("themes/" . $name . "/theme.json", "w");
We should test if $file is false (if the fopen failed) and handle the failure gracefully here.

2018-07-21 02:35 UTC, ibennetch commented on libraries/classes/ThemeGenerator/Layout.php
> +        $file = fopen("themes/" . $name . "/layout.inc.php", "w");
And here as well

2018-07-29 23:19 UTC, ibennetch requested changes
This is excellent, and I'm very pleased with your work here. There are a handful of suggestions and improvements I've made comments about in line.

There's one other thing I'd like to see if we can improve; after saving the file, the page just seems to reload for me, so I don't know if it's been successful. I think a popup message could be best saying "Theme saved, go to the main page to try it" or something along those lines. What do you think?

2018-07-29 23:19 UTC, ibennetch commented on libraries/classes/ThemeGenerator.php
> +            trigger_error("The 'themes' directory is not writable by the webserver process. You must change permissions for the theme generator to be able to write the generated theme.", E_USER_ERROR
This is a good solution, but the user will have already gone through and made their theme before realizing there's a problem. What about something like this as a slight tweak? https://gist.github.com/4788cd15d56c911b25be28d596f2d48c

2018-07-29 23:19 UTC, ibennetch commented on libraries/classes/ThemeGenerator.php
> +            trigger_error("The 'themes' directory is not writable by the webserver process. You must change permissions for the theme generator to be able to write the generated theme.", E_USER_ERROR
Regardless, this error message should be translatable: use the `__("translatable text here") wrapper around the message like
```
trigger_error(__("The 'themes' directory is not writable by the webserver process. You must change permissions for the theme generator to be able to write the generated theme."), E_USER_ERROR);
```

2018-07-29 23:19 UTC, ibennetch commented on libraries/classes/ThemeGenerator.php
> +            $txt .= '"author": "phpMyAdmin developers",';
In my opinion, since the phpMyAdmin developers didn't really make the theme, we can just leave this as an empty string.

2018-07-29 23:19 UTC, ibennetch commented on libraries/classes/ThemeGenerator.php
> +        $txt .= '"supports": ["5.0"]';
Is this meant to be changed by the phpMyAdmin development team as new phpMyAdmin versions are released? Perhaps it would be better as a form field on the page, automatically filled in with the current version of phpMyAdmin (which can be obtained from the `PMA_VERSION` constant from libraries/classes/Config.php).

2018-07-29 23:19 UTC, ibennetch commented on libraries/classes/ThemeGenerator.php
> +            trigger_error("The theme.json file is not writable by the webserver process. You must change permissions for the theme generator to be able to write the generated theme.", E_USER_ERROR);
This needs to be translatable as well.

2018-07-29 23:19 UTC, ibennetch commented on templates/theme_generator/form.twig
> +        <option value="0">Triadic</option>
These color types probably should be translatable as well.

2018-07-29 23:19 UTC, ibennetch commented on templates/theme_generator/form.twig
> +    <select name="font" id="font">
I'm not sure about whether we would make these font options translatable, since they really directly reference the font name. @nijel do you have an opinion about that?

2018-07-29 23:19 UTC, ibennetch commented on templates/theme_generator/form.twig
> +    &nbsp; Theme Name :<br>
This should be translatable as well.

2018-07-29 23:19 UTC, ibennetch commented on templates/theme_generator/form.twig
> +    &nbsp; Version :<br>
And this

2018-07-29 23:19 UTC, ibennetch commented on templates/theme_generator/form.twig
> +    &nbsp; Description :<br>
And this :)

2018-07-29 23:19 UTC, ibennetch commented on templates/theme_generator/form.twig
> +    &nbsp; Author :<br>
And this :)

2018-07-29 23:19 UTC, ibennetch commented on templates/theme_generator/form.twig
> +    <input type="checkbox" name="text_contrast">Automatically set text colours for best visibility<br>
And this :)

2018-07-29 23:19 UTC, ibennetch commented on templates/theme_generator/form.twig
> +    &nbsp; URL :<br>
And this :)

2018-07-29 23:19 UTC, ibennetch commented on templates/theme_generator/form.twig
> +    <input type="button" value="Preview" id="preview">
And this text

2018-07-29 23:19 UTC, ibennetch commented on templates/theme_generator/form.twig
> +    <input type="submit">
Let's give this a less generic text value as well, perhaps `value="Save theme"`?

2018-07-31 17:28 UTC, shucon commented on libraries/classes/ThemeGenerator.php
> +            trigger_error("The 'themes' directory is not writable by the webserver process. You must change permissions for the theme generator to be able to write the generated theme.", E_USER_ERROR
Yes! thanks for the idea :smile:

2018-07-31 17:29 UTC, shucon commented on libraries/classes/ThemeGenerator.php
> +            $txt .= '"author": "phpMyAdmin developers",';
Or could we write 'custom generated theme' ??

2018-07-31 17:41 UTC, shucon commented on libraries/classes/ThemeGenerator.php
> +        $txt .= '"supports": ["5.0"]';
PMA_VERSION is returning 5.0.0-dev for my case, so it's not valid. Should I trim it??

2018-07-31 17:48 UTC, shucon commented on templates/theme_generator/form.twig
> +        <option value="0">Triadic</option>
Does translation work the same way for twig files??

2018-08-10 05:25 UTC, ibennetch commented on libraries/classes/ThemeGenerator.php
> +        $txt .= '"supports": ["5.0"]';
Sorry, I thought I responded to this but don't see it posted here. I think you should take the first two digits only, so 5.0, or 4.8, or 9.2, but nothing after that.

2018-08-10 05:29 UTC, ibennetch approved these changes

2018-08-12 13:13 UTC, ibennetch requested changes
This is looking very good. There are three comments remaining, if you have time to check for a failed fopen() in two places and fix the ThemeGeneratorTest for `<input type="submit">` then I think everything else is set.

The documentation build warning/error is telling us that the theme_generator.rst document wasn't included in any table of contents. That can easily be fixed with this patch:
```
diff --git a/doc/user.rst b/doc/user.rst
index a98e2cb894..06843709b3 100644
--- a/doc/user.rst
+++ b/doc/user.rst
@@ -13,4 +13,5 @@ User Guide
     charts
     import_export
     themes
+    theme_generator
     other
```

2018-08-12 13:13 UTC, ibennetch commented on templates/theme_generator/form.twig
> +    <input type="submit" value="{% trans 'Save theme' %}">
This breaks the test at /home/travis/build/phpmyadmin/phpmyadmin/test/classes/ThemeGeneratorTest.php:83

2018-08-12 13:13 UTC, ibennetch commented on libraries/classes/ThemeGenerator.php
> +        $file = fopen("themes/" . $name . "/theme.json", "w");
Reminder about testing if the fopen failed.

2018-08-12 14:16 UTC, shucon commented on libraries/classes/ThemeGenerator.php
> +        $file = fopen("themes/" . $name . "/theme.json", "w");
It's being tested at line 155

2018-08-15 13:49 UTC, shucon commented
@ibennetch Can you please rerun Travis??

2018-09-05 15:32 UTC, shucon commented
@ibennetch can you please review this?? I think it's ready to be merged.

2018-10-01 21:00 UTC, MauricioFauth reviewed
I think we should have a setting to enable/disable the Theme Generator. What do you think, @ibennetch?

2018-10-04 20:48 UTC, williamdes commented
Related to: #6356

2018-12-04 06:59 UTC, shucon commented
Commenting as the PR went stale. @ibennetch @mauriciofauth

2018-12-04 15:40 UTC, mauriciofauth commented
As I commented before, I think we should have a setting to enable/disable the Theme Generator, because some people will not want to have this feature enabled.

2018-12-05 10:41 UTC, shucon commented
@mauriciofauth where do you think it would be best to add this feature?

2018-12-05 12:20 UTC, ibennetch commented
Maybe a configuration directive and a simple test early in the theme generator code. Plus of course hiding the link on the main page. Would that be suitable?

2018-12-07 12:36 UTC, shucon commented
@ibennetch @mauriciofauth can you have a look at it now?
Also, there are some errors in Travis, it's something new to me.
Can you please help me how to fix it.

2018-12-07 18:50 UTC, mauriciofauth commented
@shucon PHPStan found 15 errors in your code.
See: https://travis-ci.org/phpmyadmin/phpmyadmin/jobs/464923677#L639

You can run PHPStan with: `composer phpstan`

2019-01-29 14:28 UTC, merged

2022-08-20 01:59 UTC, sadaqtu reviewed
@phpmyadmin-bot