Login modal after session expiration
phpmyadmin/phpmyadmin pull request #14313
Opened 2018-05-20 19:23 UTC by nulll-pointer

Before submitting pull request, please check that every commit:

- [ ] Has proper Signed-Off-By
- [ ] Has commit message which describes it
- [ ] Is needed on it's own, if you have just minor fixes to previous commits, you can squash them
- [ ] Any new functionality is covered by tests

2018-05-20 19:41 UTC, nulll-pointer commented on libraries/common.inc.php
> +Tracker::enable();
I might have accidently added it while trying some implementations, I'm removing all these right now.

2018-05-21 09:30 UTC, shucon commented
I think instead of displaying a modal , it should redirect to login page , and on logging in the previous work should be displayed. @ibennetch and I have discussed it previously and both of us think it would be better for security.

2018-05-21 09:33 UTC, williamdes commented
@shucon I agree for security, but for productivity going back to login page is just a waste of time.

2018-05-21 10:49 UTC, nulll-pointer commented
@shucon, I agree that security is a major concern for a login modal as the user can easily monitor the page using browser inspector.
I think the user can't do anything when the session expires, because all the requests are first check if the user is authenticated, if not they autmoatically redirect the user to the login page.
So, if the user tries to delete the modal or do anything suspicious, they will be redirected to the login page.

2018-07-10 18:32 UTC, mauriciofauth commented on js/ajax.js
> +     * @param object e Event data
Is that correct? I think it should be `@param type name description`, shouldn't it?

2018-07-10 19:57 UTC, ibennetch requested changes
Overall this works excellently for me, I think it's a great improvement for the users and well done. I've made a few comments for you to look at when you can.

2018-07-10 19:57 UTC, ibennetch commented on libraries/classes/Plugins/Auth/AuthenticationCookie.php
> +            echo Template::get('login/header')->render(['theme' => $GLOBALS['PMA_Theme'], 'add_class' => ' modal_form', 'session_expired' => 1]);
The get method has been removed, the render function can be used as in 244d4e8e81e40ebd621a6c285a3b108922cb5109 or 5edbdf2063789d9bacb56804634ed77be6a0bb08. Could you make the adjustment here and the other few places in this code?

2018-07-10 19:59 UTC, ibennetch commented
Also, just to be clear: some of your earlier commits don't have the sign off line, was your intention to agree to the DCO for every commit? I believe for this commit we can squash and rebase the merge through Github but need to be explicitly clear about your intentions :)

2018-07-11 14:45 UTC, nulll-pointer commented on js/ajax.js
> +     * @param object e Event data
I was a little busy with the Add check constraint feature. I'm working on these now.

2018-07-11 14:45 UTC, nulll-pointer commented on js/ajax.js
> +                PMA_ajaxShowMessage("Loading...", false);
I was a little busy with the Add check constraint feature. I'm working on these now.

2018-07-11 14:47 UTC, ibennetch commented on js/ajax.js
> +                PMA_ajaxShowMessage("Loading...", false);
👍

2018-07-12 06:01 UTC, nulll-pointer commented
Sorry I forgot to add Sign-off earlier.

2018-07-12 07:14 UTC, nulll-pointer commented
I've applied git rebase to-
Resolve the merge conflicts.
Remove trailing whitespace.
Add Signed-Off-By to older commits.

2018-07-22 02:33 UTC, ibennetch commented on libraries/classes/Plugins/Auth/AuthenticationCookie.php
> +        $user_changed = !hash_equals($_COOKIE['pmaUserHashed-' . $GLOBALS['server']], crypt($this->user, "SillYSAlTstRInG"));
We already encrypt username and password cookies in the cookie authentication (https://github.com/phpmyadmin/phpmyadmin/blob/master/libraries/classes/Plugins/Auth/AuthenticationCookie.php#L534), would it make sense to use that (or re-use that code)?

2018-07-22 02:33 UTC, ibennetch commented on libraries/classes/Plugins/Auth/AuthenticationCookie.php
> +        $user_changed = !hash_equals($_COOKIE['pmaUserHashed-' . $GLOBALS['server']], crypt($this->user, "SillYSAlTstRInG"));
We already encrypt username and password cookies in the cookie authentication (https://github.com/phpmyadmin/phpmyadmin/blob/master/libraries/classes/Plugins/Auth/AuthenticationCookie.php#L534), would it make sense to use that (or re-use that code)?

2018-07-26 10:39 UTC, nulll-pointer commented on libraries/classes/Plugins/Auth/AuthenticationCookie.php
> +        $user_changed = !hash_equals($_COOKIE['pmaUserHashed-' . $GLOBALS['server']], crypt($this->user, "SillYSAlTstRInG"));
I have an idea, we can use session storage to store the hash of the user, whenever user logs in again, we can validate if the new user is different from the old one their, this way, we don't need an extra cookie. But, this won't work if session storage is not supported.

2018-08-15 13:40 UTC, merged

2018-08-15 13:43 UTC, ibennetch commented
Hm, this was working for me, but now I get this JavaScript message after logging in

```
Notice in ./libraries/classes/Plugins/Auth/AuthenticationCookie.php#557
Undefined variable: user_changed

Backtrace

./libraries/common.inc.php#379: PhpMyAdmin\Plugins\Auth\AuthenticationCookie->rememberCredentials()
./index.php#29: require_once(./libraries/common.inc.php)
```

2018-08-15 13:46 UTC, ibennetch commented
I missed this before merging. It looks like you're still using the `user_changed` variable at https://github.com/phpmyadmin/phpmyadmin/pull/14313/files#diff-7b7c059f64cce443122a835f56a2fb07R557, but removed where you set it in https://github.com/phpmyadmin/phpmyadmin/pull/14313/commits/9d2ebe7b79ff2e8ba1e1193c1a859cb94ee83798#diff-7b7c059f64cce443122a835f56a2fb07L517.

Could you take a look?

2018-08-15 13:53 UTC, nulll-pointer commented
definitely

On Wed, Aug 15, 2018 at 7:17 PM, Isaac Bennetch <notifications@github.com>
wrote:

> I missed this before merging. It looks like you're still using the
> user_changed variable at https://github.com/phpmyadmin/
> phpmyadmin/pull/14313/files#diff-7b7c059f64cce443122a835f56a2fb07R557,
> but removed where you set it in 9d2ebe7#diff-
> 7b7c059f64cce443122a835f56a2fb07L517
> <https://github.com/phpmyadmin/phpmyadmin/commit/9d2ebe7b79ff2e8ba1e1193c1a859cb94ee83798#diff-7b7c059f64cce443122a835f56a2fb07L517>
> .
>
> Could you take a look?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/phpmyadmin/phpmyadmin/pull/14313#issuecomment-413202407>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/ATZt-rcMkz02ataHTwQKu6OGz-3dTMkOks5uRCZagaJpZM4UGMPd>
> .
>

2018-08-16 02:35 UTC, mauriciofauth commented
@nulll-pointer @ibennetch I fixed in 12dfaafa3124ccc0826da8fd0a359bfbb3d921e0 the tests that were failing. I forgot to mention this PR in the commit message.

2018-08-16 13:29 UTC, nulll-pointer commented
@mauriciofauth thank you :smile: