Enh 2
phpmyadmin/phpmyadmin pull request #14330
Opened 2018-05-26 15:06 UTC by nulll-pointer

Following new features have been added in the csv import plugin:
1. For a new import, user can now directly enter the table or database name at the time of import
2. Partial import. User can enter how many rows they want to import.
Signed-Off-By: Lakshay arora <arora.lakshya123@gmail.com>

Before submitting pull request, please check that every commit:

- [ ] Has proper Signed-Off-By
- [ ] Has commit message which describes it
- [ ] Is needed on it's own, if you have just minor fixes to previous commits, you can squash them
- [ ] Any new functionality is covered by tests

2018-06-02 15:36 UTC, ibennetch requested changes

2018-07-03 23:28 UTC, MauricioFauth requested changes

2018-07-03 23:28 UTC, mauriciofauth commented on js/functions.js
> +                    $("<h3>You can change the table structure here</h3>" + data.message).insertAfter($("#new_csv_db_name").parent());
I think you forgot to make this string translatable.

2018-08-06 12:05 UTC, nulll-pointer commented
Applied changes and solved merge conflicts. I'll work on tests as soon as travis finishes.

2018-08-08 11:08 UTC, ibennetch commented
I think you forgot to make "<h3>You can change the table structure here</h3>" translatable here, other than that I think you got all of the requested changes.

2018-08-09 10:34 UTC, nulll-pointer commented
Done

2018-08-15 02:28 UTC, MauricioFauth requested changes

2018-08-15 02:28 UTC, mauriciofauth commented on js/import.js
> +                if(newDBName.length > 0 && $.trim(newDBName).length === 0) {
Some lines caused ESLint to fail. See: https://travis-ci.org/phpmyadmin/phpmyadmin/jobs/413992898#L742

2018-08-15 11:03 UTC, nulll-pointer commented on js/import.js
> +                if(newDBName.length > 0 && $.trim(newDBName).length === 0) {
These linting errors are in many of my PRs, it says it can be fixed using --fix option, how can I use this, I even asked this on the mailing list but got no reply.

2018-08-15 13:53 UTC, ibennetch commented on js/import.js
> +                if(newDBName.length > 0 && $.trim(newDBName).length === 0) {
Probably `./node_modules/.bin/eslint js/import.js --fix` will do what you're after. Sorry I missed your email!

2018-08-16 02:14 UTC, mauriciofauth commented on js/import.js
> +                if(newDBName.length > 0 && $.trim(newDBName).length === 0) {
And if you do not have the `node_modules` directory, you need to run the `yarn install` command

2018-08-18 08:39 UTC, nulll-pointer commented
I've fixed lint and other tests, but I don't understand this new selenium error?

2018-10-06 15:41 UTC, MauricioFauth approved these changes

2018-10-06 15:43 UTC, merged

2018-10-06 15:43 UTC, mauriciofauth commented
Merged, thanks for your contribution!