Increase input field width for varchar
phpmyadmin/phpmyadmin pull request #14379
Opened 2018-06-10 12:35 UTC by nulll-pointer

Signed-Off-By: Lakshay arora <arora.lakshya123@gmail.com>

Before submitting pull request, please check that every commit:

- [ ] Has proper Signed-Off-By
- [ ] Has commit message which describes it
- [ ] Is needed on it's own, if you have just minor fixes to previous commits, you can squash them
- [ ] Any new functionality is covered by tests

2018-06-15 23:23 UTC, MauricioFauth requested changes
@nulll-pointer Thanks for your contribution!
You need to fix the tests before we can merge your pull request.
See: https://travis-ci.org/phpmyadmin/phpmyadmin/jobs/390383283#L697

2018-06-15 23:52 UTC, mauriciofauth commented
I have the impression that [`$cfg['CharTextareaCols']`](https://docs.phpmyadmin.net/en/latest/config.html#cfg_CharTextareaCols) no longer works with this patch. Is this expected?

2018-06-16 08:05 UTC, nulll-pointer commented
"I have the impression that $cfg['CharTextareaCols'] no longer works with this patch. Is this expected?" 
Yes, this shouldn't work, I've set the width of the textarea to 90% of the page width(no matter what the configuration settings).
Should I set a minimum to the number of cols instead??

2018-06-16 09:57 UTC, nulll-pointer commented
I have made some changes in the tests for insertEdit, kindly have a look.

2018-07-30 20:55 UTC, nulll-pointer commented
I checked, this configuration isn't used anywhere else, I think using css to override it would be an overkill. Changing the default value sounds better.

2018-08-03 20:13 UTC, MauricioFauth approved these changes

2018-08-03 20:17 UTC, merged

2018-08-03 20:17 UTC, mauriciofauth commented
Merged, thanks for your contribution!

2018-08-06 01:16 UTC, ibennetch commented on libraries/classes/InsertEdit.php
> +            $textAreaRows = max($GLOBALS['cfg']['CharTextareaRows'], 7);
Is max() really a good choice here? What if (it's extremely unlikely, but still) a user deliberately wants more than 7 rows?