Adds features discussed in #13023
phpmyadmin/phpmyadmin pull request #14436
Opened 2018-06-28 11:53 UTC by nulll-pointer

#13023 
1. Show ajax errors at the bottom of the page, instead of showing them in a popup.
2. Add copy query button for errors in processing sql queries.
Signed-Off-By: Lakshay arora <arora.lakshya123@gmail.com>

Before submitting pull request, please check that every commit:

- [ ] Has proper Signed-Off-By
- [ ] Has commit message which describes it
- [ ] Is needed on it's own, if you have just minor fixes to previous commits, you can squash them
- [ ] Any new functionality is covered by tests

2018-09-13 20:39 UTC, williamdes commented on js/functions.js
> +            $(this).after('<span id=\'copyStatus\'> (Successfully copied!)</span>');
@nulll-pointer Can you add the text to https://github.com/phpmyadmin/phpmyadmin/blob/master/js/messages.php ?

2018-10-23 17:58 UTC, MauricioFauth requested changes

2018-10-23 17:58 UTC, mauriciofauth commented on js/functions.js
> +            $(this).after('<span id=\'copyStatus\'> (Coping Unsuccessful!)</span>');
@nulll-pointer Can you make these strings translatable?

2018-11-15 01:44 UTC, closed without merging

2018-11-15 01:45 UTC, mauriciofauth commented
Merged, thanks for your contribution!