Drop view and or replace added to exporting view #14404
phpmyadmin/phpmyadmin pull request #14446
Opened 2018-07-03 08:00 UTC by aswaniprakash

Has depenndancy in the CreateStatement.php file in sql-parser
PR: https://github.com/phpmyadmin/sql-parser/pull/198

Signed-off-by: Aswani Prakash <aswani15prakash@gmail.com>

Before submitting pull request, please check that every commit:

- [ ] Has proper Signed-Off-By
- [ ] Has commit message which describes it
- [ ] Is needed on it's own, if you have just minor fixes to previous commits, you can squash them
- [ ] Any new functionality is covered by tests

2018-09-10 00:45 UTC, MauricioFauth requested changes
Hello, thank you for this contribution.

2018-09-10 00:45 UTC, mauriciofauth commented on libraries/classes/Plugins/Export/ExportSql.php
> +
Please remove this blank line. See: https://travis-ci.org/phpmyadmin/phpmyadmin/jobs/399466397#L733

2018-09-10 00:45 UTC, mauriciofauth commented on libraries/classes/Plugins/Export/ExportSql.php
> +
Please remove this blank line. See: https://travis-ci.org/phpmyadmin/phpmyadmin/jobs/399466397#L736

2018-10-23 18:21 UTC, MauricioFauth requested changes
Tests for the PhpMyAdmin\Plugins\Export\ExportSql class failed.
See: https://travis-ci.org/phpmyadmin/phpmyadmin/jobs/438975086#L722

2018-10-29 23:33 UTC, mauriciofauth commented
Merged in cd752ad149410f4778cb0a60539f0856733c029b, thanks for your contribution!

2018-10-29 23:33 UTC, closed without merging