Basic initial webpack configuration for Modular js code
phpmyadmin/phpmyadmin pull request #14464
Opened 2018-07-06 18:50 UTC by Piyush3079

This pr contains the basic webpack configuration for modular js code with some basic changes in Header and Script class and the javascript AJAX handler for handling the new js code files.

Before submitting pull request, please check that every commit:

- [ ] Has proper Signed-Off-By
- [ ] Has commit message which describes it
- [ ] Is needed on it's own, if you have just minor fixes to previous commits, you can squash them
- [ ] Any new functionality is covered by tests

2018-07-08 05:31 UTC, devenbansod requested changes
A few comments/suggestions/requests for change.

2018-07-08 05:31 UTC, devenbansod commented on .scrutinizer.yml
> +                            format: 'php-cs-checkstyle'     # The supported format by Scrutinizer
/minor unneeded change

2018-07-08 05:31 UTC, devenbansod commented on .scrutinizer.yml
> +                node: '8.11.3'
Is the exact number required? I'd prefer to specify the latest in 8.x.x if it can automatically pick it up.

2018-07-08 05:31 UTC, devenbansod commented on config.sample.inc.php
> +$cfg['environment'] = 'production';
I think these should go to `libraries/config.default.php` instead

2018-07-08 05:31 UTC, devenbansod commented on js/ajax.js
> +                    script_src += 'http://localhost:' + PMA_commonParams.get('webpack_port') + '/js/dist/';
I think we should allow for specifying the `webpack_host` too. I've personally seen and used hosts like `localhost.xyz.com` while developing locally. Hardcoding anyway does not make sense, though the default value can be `localhost`.

2018-07-08 05:31 UTC, devenbansod commented on js/ajax.js
> +                    script_src = 'js/dist/';
Which one is better?
I see you have used `+=` on L651, but use `=` here. Is the initialization of `script_src` to `''` really required?

2018-07-08 05:31 UTC, devenbansod commented on js/src/db_search.js
> +/* vim: set expandtab sw=4 ts=4 sts=4: */
If this PR only focusses on `Basic initial webpack configuration for Modular js code`, I wonder if this change (js/src/db_search.js) should go in here.

2018-07-08 05:31 UTC, devenbansod commented on libraries/classes/Header.php
> +        $this->_scripts->addFile('messages.php', array('l' => $GLOBALS['lang']));
Any specific reason for moving this code for addition of `messages.php` to `$this->_scripts` above?

2018-07-08 05:31 UTC, devenbansod commented on libraries/classes/Scripts.php
> +                    $src = "http://localhost:" . $GLOBALS['cfg']['webpack_port'] . "/";
See above comment regarding `webpack_host`

2018-07-08 05:31 UTC, devenbansod commented on libraries/classes/Scripts.php
> +                } else if ($GLOBALS['cfg']['environment'] === 'production'){
I think instead of `else if`, we should initialize `$src = ""` and have only `if ($GLOBALS['cfg']['environment'] === 'development')` check

2018-07-08 07:44 UTC, Piyush3079 reviewed
I have made required changes with some comments regarding some of the requested changes.

2018-07-08 07:44 UTC, Piyush3079 commented on js/src/db_search.js
> +/* vim: set expandtab sw=4 ts=4 sts=4: */
Yeah this files is not required in this pr but as this pr is made from gsoc branch, the commits or later branch will require this files so I thought of not removing this files as doing this will cause conflicts in later prs.
Also one of the purpose fulfilled by this files is testing of webpack configuration.

2018-07-08 07:44 UTC, Piyush3079 commented on libraries/classes/Header.php
> +        $this->_scripts->addFile('messages.php', array('l' => $GLOBALS['lang']));
This files contains the message strings for js code so it should be loaded before any other other js files so that all the strings were available for any file being loaded.

2018-07-09 03:21 UTC, devenbansod commented on config.sample.inc.php
> +$cfg['environment'] = 'production';
Let's add them in this PR instead and remove it from the next PRs. We'll move to getting the next ones reviewed only when this one is ready and merged.

2018-07-09 03:23 UTC, devenbansod commented on js/ajax.js
> +                    script_src += 'http://localhost:' + PMA_commonParams.get('webpack_port') + '/js/dist/';
Hostname would just be `example.com` (and would not have port). We'd still require the `webpack_port` too.

2018-07-09 13:38 UTC, Piyush3079 commented on config.sample.inc.php
> +$cfg['environment'] = 'production';
I have added them.

2018-07-09 14:06 UTC, Piyush3079 commented on js/ajax.js
> +                    script_src += 'http://localhost:' + PMA_commonParams.get('webpack_port') + '/js/dist/';
So it should be like `hostname`:`port`.
Ok I am updating it.

2018-07-09 14:36 UTC, Piyush3079 commented
The failures were due to these tests stub the `Header` class and whenever these tests instantiate the class, they will call class method defined in constructor `_addDefaultScripts` and in this method, the value of `environment` in `$params` was undefined during the tests. But now I have added all the webpack and environment directives in `config.default.php` so tests will not fail now.

2018-07-09 15:03 UTC, devenbansod commented
You might want to delay enforcing the strict `eslint` standards, till we clean up the JS codebase. The 
 Lint Job seems to error right now: https://travis-ci.org/phpmyadmin/phpmyadmin/jobs/401785317

2018-07-09 15:24 UTC, Piyush3079 commented
I am working on this only. The ` "extends": "eslint:recommended",` part needs to be commented.

2018-07-10 02:57 UTC, Piyush3079 commented on js/src/db_search.js
> +/* vim: set expandtab sw=4 ts=4 sts=4: */
I am not sure about this file. If it create some problem then I think I should remove it otherwise I just added it here to check if webpack is building the files correctly and the urls are working proporly.
What do you think?

2018-07-10 10:30 UTC, devenbansod commented on js/src/db_search.js
> +/* vim: set expandtab sw=4 ts=4 sts=4: */
It's not a huge problem. But for any (potential) contributor, the PR looks cleaner w/o it. You can decide to remove it or keep it based on your judgement.

2018-07-11 05:14 UTC, mauriciofauth commented on libraries/config.default.php
> +$cfg['webpack_port'] = 3307;
I'm still not sure if these are the most appropriate default values. `$cfg['webpack_host']` and `$cfg['webpack_port']` values are only interesting to developers, right?

2018-07-11 05:14 UTC, mauriciofauth commented on package.json
> +    "babel-core": "^6.26.3",
I think you should replace `babel-core` by `babel-cli` here.

2018-07-11 05:14 UTC, mauriciofauth commented on .babelrc
> +}
If you want, you can use the [EditorConfig](https://editorconfig.org/#download) plugin to help with style issues like this and like most of the style issues pointed to by @phpmyadmin-bot.

2018-07-11 15:36 UTC, Piyush3079 commented on libraries/config.default.php
> +$cfg['webpack_port'] = 3307;
Yeah these configurations only need to be setup for developers. Normal users don't need these configurations.

2018-07-11 15:44 UTC, Piyush3079 commented on .eslintrc.json
> +    // "extends": "eslint:recommended",
`"extends": "eslint:recommended",` this helps in enabling eslint in files strictly. If it is removed travis will not show any failure in tests for undefined functions and variables in files.
Although it is not needed now but we need to add this in future to make sure that there should not be any undefined variables as complete code is going to run in strict mode.

2018-07-11 15:53 UTC, Piyush3079 commented on package.json
> +    "babel-core": "^6.26.3",
Yeah I have done this.

2018-07-11 16:22 UTC, Piyush3079 commented
`config.sample.inc.php` is intended to overwrite the default configurations in `config.default.php`. So if developer wants to make change in webpack port and webpack host then he has to make change in `config.default.php`. Is it the change required?
Also we need to make these directives available in `webpack.config.babel.js` as there also, we need to specify some sort of configuration for port and output path on the basis of environment.
Creating a `.env` file can solve `webpack.config.babel.js` directive issue.

2018-07-11 16:34 UTC, Piyush3079 commented on .babelrc
> +}
Is it related to this file?
Because this file contains the configuration for bebel-presets to enable various plugins for the `env` environment.

2018-07-11 16:38 UTC, Piyush3079 commented on config.sample.inc.php
> +$cfg['environment'] = 'production';
`config.sample.inc.php` is intended to overwrite the default configurations in `config.default.php`. So if developer wants to make change in webpack port and webpack host then he has to make change in `config.default.php`. Is it the change required?
Also we need to make these directives available in `webpack.config.babel.js` as there also, we need to specify some sort of configuration for port and output path on the basis of environment.
Creating a `.env` file can solve `webpack.config.babel.js` directive issue.

2018-07-11 16:39 UTC, Piyush3079 commented on .babelrc
> +}
Yeah I think this will be helpful. Thanks

2018-07-14 02:36 UTC, devenbansod commented on .eslintrc.json
> +    // "extends": "eslint:recommended",
We can remove it for now, and add it later then?

2018-07-14 02:37 UTC, devenbansod commented on config.sample.inc.php
> +$cfg['environment'] = 'production';
Please remove it from the `config.sample.inc.php`. It's meant for the users (not developers) who want minimum overhead of setting phpmyadmin up.

2018-07-14 02:38 UTC, devenbansod commented on js/src/db_search.js
> +/* vim: set expandtab sw=4 ts=4 sts=4: */
I guess you could remove it out, add it in a later PR

2018-07-14 02:50 UTC, devenbansod commented on package.json
> +    "prod:build": "rimraf js/lib js/dist && babel js/src/ -d js/lib --ignore .test.js && cross-env NODE_ENV=production webpack -p --progress",
@Piyush3079 Can we not use `rm -rf`? (Is it required for Windows compatibility?) 

It seems to have ISC license, which might require a review before adding it to our package.json (given that phpMyAdmin is GPL-v2 licensed).
cc: @ibennetch @nijel

2018-07-14 02:51 UTC, devenbansod approved these changes

2018-07-14 02:52 UTC, devenbansod commented
Looks good to me, except the few final comments.

2018-07-14 12:58 UTC, Piyush3079 commented on config.sample.inc.php
> +$cfg['environment'] = 'production';
Ok I am removing it

2018-07-14 12:59 UTC, Piyush3079 commented on js/src/db_search.js
> +/* vim: set expandtab sw=4 ts=4 sts=4: */
Yeah I am removing this file from this pr

2018-07-14 13:13 UTC, Piyush3079 commented on .eslintrc.json
> +    // "extends": "eslint:recommended",
Yeah that won't be problem I guess.

2018-07-14 13:16 UTC, Piyush3079 commented on package.json
> +    "prod:build": "rimraf js/lib js/dist && babel js/src/ -d js/lib --ignore .test.js && cross-env NODE_ENV=production webpack -p --progress",
Yeah, `rm -rf` will give error to Windows users. That's why I have used this package to have cross-platform compatibility for creating build.

2018-07-15 08:57 UTC, ibennetch requested changes

2018-07-15 08:57 UTC, ibennetch commented on libraries/config.default.php
> + * for making production build $cfg['environment'] = 'production'
I suggest adding a line here mentioning the need to also change CSPAllow, something like "You will probably also have to modify the `$cfg['CSPAllow']` directive in order to use the webpack development server."

2018-07-15 08:57 UTC, ibennetch commented on libraries/config.default.php
> + * cross-origin loading of js files for specified webpack host and webpack port.
I'd spell out JavaScript instead of "js" here

2018-07-15 08:57 UTC, ibennetch commented on libraries/config.default.php
> + * Eg. 'http://localhost:3307 ws://localhost:3307' for locahost and 3307 webpack pot
"port" rather than "pot" :)

2018-07-15 08:57 UTC, ibennetch commented on webpack.config.babel.js
> +    // envionment either development or production
typo: "environment"

2018-07-15 08:57 UTC, ibennetch commented on webpack.config.babel.js
> +        publicPath: 'http://localhost:3307/js/dist'
Will this work properly if the developer sets a different value for `$cfg['webpack_host']` or `cfg['webpack_port']`?

2018-07-15 08:57 UTC, ibennetch commented on webpack.config.babel.js
> +    // devtool: 'source-map',
Is this commented line unnecessary?

2018-07-15 08:57 UTC, ibennetch commented on libraries/config.default.php
> + * For working envionment to be development, this has to be changed to allow
Typo: "environment"

2018-07-15 08:57 UTC, ibennetch commented on doc/config.rst
> +    Enable you to set the working environment for loading js files
Can I suggest instead writing this?

> Sets the working environment for loading JavaScript files for webpack development
> 
> Possible values are 'production' or 'development'

2018-07-15 08:57 UTC, ibennetch commented on doc/config.rst
> +.. config:option:: $cfg['environment']
Would `$cfg['webpack_environment']` be more appropriate?

2018-07-15 08:57 UTC, ibennetch commented on doc/config.rst
> +    when working in the development environment
I'd just say:

> Webpack development server hostname for serving JavaScript files. Requires `$cfg['environment']` to be development.

2018-07-15 08:57 UTC, ibennetch commented on doc/config.rst
> +    when working in the development environment
Similarly,

> Webpack development server port for serving JavaScript files. Requires $cfg['environment'] to be development.

2018-07-15 09:03 UTC, ibennetch commented
According to https://www.gnu.org/licenses/license-list.en.html#ISC, the ISC license is compatible with the GPL, so rifraf should be okay according to GNU.

2018-07-15 16:49 UTC, Piyush3079 commented on doc/config.rst
> +.. config:option:: $cfg['environment']
Making it `webpack_environment` would restrict this directive to webpack only rather than making it for the complete application. With `environmet` only we can use this directive for other things also like adding debugging in development environment.

2018-07-15 16:57 UTC, Piyush3079 commented on libraries/config.default.php
> + * for making production build $cfg['environment'] = 'production'
I have done that.

2018-07-16 03:11 UTC, devenbansod commented
Hi @ibennetch @mauriciofauth, @Piyush3079 has done some of the suggested changes, rebased the PR and squashed the commits. How does the PR look to you? 
Could you please approve the changes if you are fine with them?

2018-07-16 14:16 UTC, MauricioFauth requested changes

2018-07-16 14:16 UTC, mauriciofauth commented on js/ajax.js
> +                } else if (PMA_commonParams.get('environment') === 'production') {
I think any value other than `development` must be considered as `production`.

2018-07-17 13:20 UTC, ibennetch commented on doc/config.rst
> +.. config:option:: $cfg['environment']
Personally, I think any other debugging functionality should have its own configuration directive (so developers can focus on debugging a specific module or functionality), but you have a valid point as well. It's not that important to change and besides, if a problem comes up later we can deal with it at that time.

If @mauriciofauth and @devenbansod are okay with this directive then it's fine for me as well.

2018-07-17 13:21 UTC, ibennetch approved these changes

2018-07-17 13:27 UTC, williamdes approved these changes

2018-07-17 23:22 UTC, MauricioFauth approved these changes

2018-07-18 11:42 UTC, devenbansod commented
Thanks everyone for the reviews.

@Piyush3079 Great work on this! Thanks for your contribution.

2018-07-18 11:42 UTC, merged