server_privileges and server_databases modularized
phpmyadmin/phpmyadmin pull request #14465
Opened 2018-07-08 05:02 UTC by Piyush3079

This pr contains the modular code for pages server_databases and server_privileges.
This pr is slight big because some of the core function required for these two files were copied and then imported.
This pr is in continuation of Mod_Js_Config. Before reviewing this pr, review Mod_Js_Config and merge and then compare this pr with merged one.

Before submitting pull request, please check that every commit:

- [ ] Has proper Signed-Off-By
- [ ] Has commit message which describes it
- [ ] Is needed on it's own, if you have just minor fixes to previous commits, you can squash them
- [ ] Any new functionality is covered by tests

2018-07-22 02:58 UTC, devenbansod requested changes
Leaving a few initial review comments and suggestions.

If you could record it, I'd love to see a working screen video though (to confirm nothing is broken as of now), although I would definitely verify the usage at a later stage before merging.

2018-07-22 02:58 UTC, devenbansod commented on js/functions.js
> + */
If these are to be removed later, please add a note in a TODO stating the same.

2018-07-22 02:58 UTC, devenbansod commented on js/src/ajax.js
> +import { PMA_ajaxShowMessage } from './utils/show_ajax_messages';
Try to remove these `PMA_` prefixes

2018-07-22 02:58 UTC, devenbansod commented on js/src/consts/doclinks.js
> +    /* Multi word */
Why is this file needed if everything is commented out?

Also, please avoid underscores in exports. Might want to use PascalCase.

2018-07-22 02:58 UTC, devenbansod commented on js/messages.php
Why are two files required? js/messages.php and js/src/messages.php

Is it possible to do away with one of them?

2018-07-22 02:58 UTC, devenbansod commented on webpack.config.babel.js
>      },
Why `index_new`?

2018-07-22 21:12 UTC, Piyush3079 commented on webpack.config.babel.js
>      },
The `_new.js` suffix helps us to identify that for this file we need to use `src='webhost+webport/js/dist'` and for other `.js` files we need to use `src=js/filename`.
When all the files get revamped we can drop the `_new` suffix and modify `Script.php` for single entrypoint `index.js`.

2018-07-22 21:13 UTC, Piyush3079 commented on js/messages.php
I have removed the duplicate files and merged the two into one and changed some of the js files accordingly.

2018-07-22 21:55 UTC, Piyush3079 commented on js/src/consts/doclinks.js
> +    /* Multi word */
This pr does not contain any of the case changes for variables and removal of `PMA_` prefix as this pr mainly contains the functions going to use in many files.
I was just thinking to create one or more pr once we create and merge some workable code, which will contain changes like using camelCase for variables, PascalCase for exports and dropping `PMA_` prefix.
What do you think about this?

2018-07-22 22:06 UTC, Piyush3079 commented on js/common_params.php
> +// }
Removed

2018-07-22 22:11 UTC, Piyush3079 commented on js/src/utils/show_ajax_messages.js
> +// import { PMA_highlightSQL } from './sql';
Removed

2018-07-22 22:18 UTC, Piyush3079 commented on libraries/classes/Header.php
> +        $this->_scripts->addFile('vendor/jquery/jquery-ui.min.js');/////////////////
Just checking all these plugins for compatibility with modular code.
Not required now, so I am removing them.

2018-07-22 22:19 UTC, Piyush3079 commented on js/src/variables/common_params.js
> +export const PMA_commonParams = (function () {
Answered in a comment below :)

2018-07-22 22:20 UTC, Piyush3079 commented on js/functions.js
> + */
Added a `TODO` in the comment itself.

2018-07-24 12:34 UTC, Piyush3079 commented on .babelrc
> +    "plugins": ["syntax-dynamic-import"]
Babel does not support dynamic imports so to compile that, this plugin is added

2018-07-24 13:41 UTC, Piyush3079 reviewed
General comments for files regarding the changes made.

2018-07-24 13:41 UTC, Piyush3079 commented on js/src/index.js
> +import { AJAX } from './ajax';
Entry-point for the modular code. Any function or file needs to be loaded at the time of initial loading or only once should be placed or included in this file

2018-07-24 13:41 UTC, Piyush3079 commented on js/src/server_databases.js
> +/* vim: set expandtab sw=4 ts=4 sts=4: */
This file is copied from the old server_databases.js and then modified accordingly for the modular code.

2018-07-24 13:41 UTC, Piyush3079 commented on js/src/server_privileges.js
> +/* vim: set expandtab sw=4 ts=4 sts=4: */
This file is copied from server_privileges.js and then modified accordingly for the modular code.

2018-07-24 13:41 UTC, Piyush3079 commented on js/src/utils/Sanitise.js
> +/**
File containing functions for escaping the html and javascript code strings.

2018-07-24 13:41 UTC, Piyush3079 commented on js/src/utils/JqueryExtended.js
> +import $ from 'jquery';
Extending jQuery in this file with some plugins and custom functions created for phpMyAdmin

2018-07-24 13:41 UTC, Piyush3079 commented on js/src/utils/menu_resizer.js
> +/* vim: set expandtab sw=4 ts=4 sts=4: */
Menu Resizer functions copied from menu_resizer.js and small changes are made to handle some global variables.

2018-07-24 13:41 UTC, Piyush3079 commented on js/src/utils/show_ajax_messages.js
> +/* vim: set expandtab sw=4 ts=4 sts=4: */
File containing PMA_ajaxShowMessage and PMA_ajaxRemoveMessage functions.

2018-07-24 13:41 UTC, Piyush3079 commented on js/src/utils/sprintf.js
> +import sprintf from 'sprintf-js';
Sprintf function modified for the new sprintf library.

2018-07-24 13:41 UTC, Piyush3079 commented on js/src/variables/common_params.js
> +import { PMA_sprintf } from '../utils/sprintf';
PMA_commonParams module for handling common params defined in Header.php

2018-07-24 13:41 UTC, Piyush3079 commented on js/src/variables/export_variables.js
> +import { Variables } from './global_variables';
Exporting variables from module serialised using global variables.

2018-07-24 13:41 UTC, Piyush3079 commented on js/src/variables/import_variables.js
> +import { Variables } from './global_variables';
Serialising global variables in the module.

2018-07-24 13:41 UTC, Piyush3079 commented on package.json
> +    "jquery-ui-bundle": "^1.12.1-migrate",
Jquery-ui does have a bundle so this additional library is added to use jquery-ui with jquery.

2018-07-24 13:41 UTC, Piyush3079 commented on package.json
> +    "jquery-migrate": "3.0.0",
The newer version is not compatible. It is throwing some warnings. So, for now, we can use 3.0.0.

2018-07-25 15:27 UTC, devenbansod approved these changes
Tested locally. Looks good to me.

Please fix the linter errors. I've restarted the selenium test job, let's see if it turns green.

2018-07-26 14:18 UTC, devenbansod commented
@Piyush3079 I am merging this for now given the shortage of time and dependency of next PR at #14466 on this PR. 

But we should take steps to take steps to move these changes fast, while also considering the steps needed to build out a workable release from this (i.e. run out of the box from the release zip export).

The selenium tests can't pass right now, since the Login page is itself broken out of the box (since it requires [additional setup](https://github.com/phpmyadmin/phpmyadmin/issues/14355#issue-328825520) right now to test out this code)

2018-07-26 14:20 UTC, merged