Fix for SYSTEM VERSIONED tables #14514, maybe #14516
phpmyadmin/phpmyadmin pull request #14536
Opened 2018-07-31 22:56 UTC by darkain

Fix for https://github.com/phpmyadmin/phpmyadmin/issues/14514
Possible fix for https://github.com/phpmyadmin/phpmyadmin/issues/14516

Tables which enable the new MariaDB 10.3 versioning show up as "SYSTEM VERSIONED" instead of "BASE TABLE" inside of information schema. This patch now checks for both, so these new table types don't incorrectly display as views.

The second bug cannot be fully tested and verified with current MariaDB builds. Version 10.3.9 (currently unreleased) corrects an issue with column information for SYSTEM VERSIONED columns that this patch relies on. https://jira.mariadb.org/browse/MDEV-16804 - the reason for checking with preg_match instead of adding to the list is because there are now combined "extra" information for columns, such as INVISIBLE columns. Just matching entire strings also has a bug with these other "extra" parameters.

Before submitting pull request, please check that every commit:

- [ ] Has proper Signed-Off-By
- [X] Has commit message which describes it
- [X] Is needed on it's own, if you have just minor fixes to previous commits, you can squash them
- [ ] Any new functionality is covered by tests

2018-09-13 19:25 UTC, williamdes approved these changes

2018-10-28 21:32 UTC, MauricioFauth approved these changes

2018-10-29 18:02 UTC, MauricioFauth requested changes
Thanks for your contribution!
I don't know why Travis CI didn't run, but you also need to fix the failing tests.

2019-02-15 16:16 UTC, merged

2019-02-15 16:18 UTC, mauriciofauth commented
Merged, thanks for your contribution!