Integrate user preferences with local storage
phpmyadmin/phpmyadmin pull request #14543
Opened 2018-08-02 21:28 UTC by nulll-pointer

#13843 
Signed-Off-By: Lakshay arora <arora.lakshya123@gmail.com>

Before submitting pull request, please check that every commit:

- [ ] Has proper Signed-Off-By
- [ ] Has commit message which describes it
- [ ] Is needed on it's own, if you have just minor fixes to previous commits, you can squash them
- [ ] Any new functionality is covered by tests

2018-08-03 13:08 UTC, nulll-pointer commented
I've given preference to the configuration stored in local storage if the data between local storage and database is inconsistent.

2018-08-13 13:08 UTC, saulotoledo requested changes

2018-08-13 13:08 UTC, saulotoledo commented on js/functions.js
> +        for(i = 0; i < configurations.length; ++i) {
Use `var` to declare the loop variable, or you are creating a global one in your script.

2018-08-13 13:08 UTC, saulotoledo commented on js/functions.js
> +        if(typeof configurations === 'undefined' || configurations === null) {
Try `if (configurations) {` here.

2018-08-13 13:08 UTC, saulotoledo commented on js/functions.js
> +            if(type === "") break;
I particularly do not like this `break` here. If says that if you have an empty value in the configuration you should stop the full processing. Why that happens? It is not easy to understand just by reading the code. Is there no other way to write this more clearly?

2018-08-15 11:00 UTC, nulll-pointer commented
@saulotoledo, thanks for the suggested changes.

2018-08-15 19:11 UTC, saulotoledo requested changes
Yw @nulll-pointer :smile:

I just found some other minor details. Please address them if possible.

In your next commit you can use a `git commit --amend`.

2018-08-15 19:11 UTC, saulotoledo commented on js/functions.js
> +        if (typeof configurations === 'undefined' || configurations === null) {
I still prefer just `if (configurations) {` here, but it is ok.

2018-08-15 19:13 UTC, saulotoledo commented
@nulll-pointer Ops, I forgot something: there is a codeclimate problem to be solved [here](https://codeclimate.com/github/phpmyadmin/phpmyadmin/pull/14543).

2018-08-16 13:11 UTC, nulll-pointer commented on js/functions.js
> +        if (typeof configurations === 'undefined' || configurations === null) {
Actually, getItem function explicitly returns null if the item is not found.
https://stackoverflow.com/questions/3262605/how-to-check-whether-a-storage-item-is-set

2018-08-17 07:43 UTC, saulotoledo commented on js/functions.js
> +        if (typeof configurations === 'undefined' || configurations === null) {
You are right, but if `configurations` is `null` or `undefined`, the expression `if (configurations)` will return `false`:

```javascript
if (undefined) {
  console.log("returning true");
} else {
  console.log("returning false"); // <- this is the result
}

if (null) {
  console.log("returning true");
} else {
  console.log("returning false"); // <- this is the result
}
```

2018-08-17 07:47 UTC, saulotoledo commented
@nulll-pointer There are still some lint errors found by travis, ok? You can find them by clicking on "Details" in the travis link below with a red "x".

2018-08-17 13:14 UTC, nulll-pointer commented
Yes, there are lint errors in some other prs as well. Im fixing these one
by one.

On Fri 17 Aug, 2018, 1:17 PM Saulo S. Toledo, <notifications@github.com>
wrote:

> @nulll-pointer <https://github.com/nulll-pointer> There are still some
> lint errors found by travis, ok? You can find them by clicking on "Details"
> in the travis link below with a red "x".
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/phpmyadmin/phpmyadmin/pull/14543#issuecomment-413786328>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/ATZt-nK352behgOWB5giBx2wfptU74mgks5uRnUQgaJpZM4VtCKO>
> .
>

2018-08-19 17:54 UTC, saulotoledo commented
I will give you my ok, but now you need a review from someone on the project team. @ibennetch, could you point to the right person to do it?

2018-08-19 17:57 UTC, saulotoledo approved these changes
@nulll-pointer I'm giving you my ok, but now you need a review from someone on the project team. @ibennetch, could you point to the right person to do it?

2018-10-25 18:06 UTC, closed without merging