Update GitHub templates
phpmyadmin/phpmyadmin pull request #14587
Opened 2018-08-23 04:55 UTC by mauriciofauth

- Add support for multiple issue templates
- Update pull request template

Based on https://help.github.com/articles/creating-issue-templates-for-your-repository/

2018-08-23 12:02 UTC, ibennetch requested changes
This is really great, I love it!

2018-08-23 12:02 UTC, ibennetch commented on .github/PULL_REQUEST_TEMPLATE.md
> +- [ ] Make sure you have read our [CONTRIBUTING.md](https://github.com/phpmyadmin/phpmyadmin/blob/master/CONTRIBUTING.md) document.
I'm not sure this is needed; IMHO the CONTRIBUTING document doesn't really add anything if the user has gotten to the point of submitting a pull request on their own.

2018-08-23 12:02 UTC, ibennetch commented on .github/PULL_REQUEST_TEMPLATE.md
> +- [ ] Make sure you are making a pull request against the correct branch. For example, for bug fixes in a released version use the corresponding QA branch and for new features use the _master_ branch
I might suggest adding "If you have a doubt, you can ask as a comment in the bug report or on the mailing list."

2018-08-23 12:02 UTC, ibennetch commented on .github/PULL_REQUEST_TEMPLATE.md
> +- [ ] Every commit has proper `Signed-off-by` line as described in our [DCO](https://github.com/phpmyadmin/phpmyadmin/blob/master/DCO).
I might suggest adding a sentence like "This ensures that the work you're submitting is your own creation."

2018-08-23 12:02 UTC, ibennetch commented on .github/PULL_REQUEST_TEMPLATE.md
> +- [ ] Every commit has a message which describes it.
I'd say instead "Every commit has a descriptive commit message" (or "descriptive log message" or some such).

2018-08-23 12:02 UTC, ibennetch commented on .github/PULL_REQUEST_TEMPLATE.md
> +- [ ] Every commit is needed on it's own, if you have just minor fixes to previous commits, you can squash them.
I believe this should be "its" not "it's."

2018-08-23 17:58 UTC, mauriciofauth commented on .github/ISSUE_TEMPLATE/bug_report.md
> +### Expected behavior
I think it can be repetitive, as this will probably be described in the _Describe the bug_ topic.

2018-08-23 18:03 UTC, mauriciofauth commented on .github/PULL_REQUEST_TEMPLATE.md
> +- [ ] Make sure you have read our [CONTRIBUTING.md](https://github.com/phpmyadmin/phpmyadmin/blob/master/CONTRIBUTING.md) document.
I agree, but I think it's good to keep that line there if the person has not seen it yet, and we can also improve the CONTRIBUTING document.

2018-08-23 18:07 UTC, mauriciofauth commented on .github/ISSUE_TEMPLATE/security_report.md
> +about: Do not create an issue for security reports, send an email to security@phpmyadmin.net
@ibennetch I'm not sure if we should keep the email here, or the url for the security page. Anyway, GitHub will not turn this into a clickable link.

2018-08-25 19:35 UTC, ibennetch approved these changes
This is really great, I love it!

2018-08-25 19:35 UTC, ibennetch commented on .github/ISSUE_TEMPLATE/security_report.md
> +about: Do not create an issue for security reports, send an email to security@phpmyadmin.net
Is "about: Disclose a security vulnerability responsibly by first reporting it to us privately" better?

2018-08-25 19:41 UTC, ibennetch commented
When merging this, we'll also want to remove https://github.com/phpmyadmin/phpmyadmin/blob/master/.github/ISSUE_TEMPLATE.md

2018-08-26 06:54 UTC, merged

2018-08-26 06:54 UTC, mauriciofauth commented
@ibennetch Thank you!