Issue #12158: auto expand the single database
phpmyadmin/phpmyadmin pull request #14650
Opened 2018-10-08 16:34 UTC by lkopo

### Description

Implemented a new feature as discussed in #12158 with the following scenario:
If the logged user has only one database in the navigation tree, that database will be automatically expanded. I've also added this as a configurable option with default value **true**, so people can disable this change whenever they want.

2018-10-08 17:12 UTC, lkopo commented
I see there is a problem with sign-off as I've signed-off my commits by my real name (as it is written in https://github.com/phpmyadmin/phpmyadmin/blob/master/DCO) which conflicts with my nickname. What should I do now?

2018-10-08 17:17 UTC, williamdes commented
@lkopo The DCO details show:
```
Commit sha: 7167a63, Author: Eduard Karpiel, Committer: Eduard Karpiel; Expected "Eduard Karpiel lkopo@lkopo.local", but got "Eduard Karpiel eduard@karpiel.sk".
Commit sha: 920be41, Author: lkopo, Committer: lkopo; Expected "lkopo eduard@karpiel.sk", but got "Eduard Karpiel eduard@karpiel.sk".
```

2018-10-08 17:28 UTC, williamdes commented
@lkopo I think that you can force ```--author``` and/or ```--commiter```
The best for me is to configure globally or for this repo you author settings:
```bash
git config --global user.name "John Doe"
git config --global user.email "john@doe.org"
```

2018-10-08 17:43 UTC, williamdes commented
@lkopo Only one left (double signoff) ;)

2018-10-08 18:56 UTC, lkopo commented
@williamdes all checks passed. Is it OK now? :)

2018-10-08 19:24 UTC, williamdes approved these changes

2018-10-08 19:25 UTC, williamdes commented
@lkopo Yes :)

2018-10-20 12:17 UTC, lkopo commented
Hi @williamdes. Is there something missing for merge or some reviews are still pending? :)

2018-10-20 19:07 UTC, williamdes commented
@lkopo For me everything is OK
@mauriciofauth Can you merge this PR if it seems good for you ?

2018-10-31 01:19 UTC, MauricioFauth requested changes

2018-10-31 01:19 UTC, mauriciofauth commented on js/navigation.js
> +    } else if (autoexpand && $('#pma_navigation_tree_content > ul > li').length === 1) {
`$('#pma_navigation_tree_content > ul > li').length` isn't equal to 1 if the user has permission to create new databases.
![db-list](https://user-images.githubusercontent.com/120970/47760126-6fde2c00-dc91-11e8-87da-33936c01d4cd.png)

2018-10-31 14:39 UTC, lkopo commented
@mauriciofauth Thank you, I didn't notice that! Already fixed. I've also fixed JS error when no database was in the tree, only link to create new database.

2018-10-31 19:16 UTC, mauriciofauth commented
Nice job. It's working now, however I noticed that it doesn't work the first time, when you just logged in, but when you refresh, it works. What do you think it could be?

2018-10-31 19:39 UTC, lkopo commented
@mauriciofauth I've found the issue, but I don't think it's not caused by my changes. The problem is here: in navigation.js:

Line 1814:
```
                if ($('#pma_navigation_tree').hasClass('synced')) {
                    PMA_selectCurrentDb();
                    PMA_showCurrentNavigation();
                }
```

If you open PMA in incognito window and log in, it will work as expected. But if you log out and log in again, it won't because of part of code mentioned above. I've checked and somehow after log out and log in, the `#pma_navigation_tree` element is not "synced" (the condition will fail).

I'm not sure what I can do here.

2018-10-31 20:34 UTC, lkopo commented
@mauriciofauth Ok, I'm sorry for previous deletions of my posts, but finally I've managed to find what is the real cause of this issue - Session storage. In navigation.js there is a function to reload navigation tree `PMA_reloadNavigation()`. It is called by multiple places, but after some debugging, the default behaviour when you log in from incognito window (so your session storage is empty), the condition on lines 640-641 will pass:

```
        if ($('#pma_navigation_tree_content').length &&
            typeof storage.navTreePaths === 'undefined'
        ) {
            PMA_reloadNavigation();
        }
```
Part `storage.navTreePaths` is undefined. But when you log out, session storage is not cleared so old data for navigation tree are here. After log in, `else` block is executed on line 649 which doesn't contain call for function `PMA_reloadNavigation()`, it calls instead `navTreeStateUpdate()` which will update three sessionStorage items: `navTreePaths`, `server` and `token`. Why it works on refresh is that `token` field was updated and now it evaluates the condition on lines 644-645:

```
        } else if (PMA_commonParams.get('server') === storage.server &&
            PMA_commonParams.get('token') === storage.token
        ) {
            // Reload the tree to the state before page refresh
            PMA_reloadNavigation(navFilterStateRestore, JSON.parse(storage.navTreePaths));
        }
```
as `true`. I've put the call for `PMA_reloadNavigation()` as a workaround for it, but I think it should be better for the future to somehow clear / remove sessionStorage fields after log out.

2018-10-31 22:18 UTC, MauricioFauth approved these changes

2018-10-31 22:21 UTC, merged

2018-10-31 22:31 UTC, mauriciofauth commented
Merged, thanks for your contribution!

> I've put the call for PMA_reloadNavigation() as a workaround for it, but I think it should be better for the future to somehow clear / remove sessionStorage fields after log out.

Can you open a new issue describing that?