Removed html inline Styles and removed destroyed auto formatting
phpmyadmin/phpmyadmin pull request #14684
Opened 2018-10-22 12:08 UTC by nborschke

Signed-off-by: nborschke <nicoborschke98@gmail.com>
### Description

Removed html inline Styles from all js files that are directly under the js folder.
Also removed destroyed auto formatting

Fixes #

Before submitting pull request, please review the following checklist:

- [x] Make sure you have read our [CONTRIBUTING.md](https://github.com/phpmyadmin/phpmyadmin/blob/master/CONTRIBUTING.md) document.
- [x] Make sure you are making a pull request against the correct branch. For example, for bug fixes in a released version use the corresponding QA branch and for new features use the _master_ branch. If you have a doubt, you can ask as a comment in the bug report or on the mailing list.
- [x] Every commit has proper `Signed-off-by` line as described in our [DCO](https://github.com/phpmyadmin/phpmyadmin/blob/master/DCO). This ensures that the work you're submitting is your own creation.
- [x] Every commit has a descriptive commit message.
- [x] Every commit is needed on its own, if you have just minor fixes to previous commits, you can squash them.
- [x] Any new functionality is covered by tests.

2018-10-23 13:56 UTC, shucon requested changes

2018-10-31 21:12 UTC, MauricioFauth requested changes
Hi, @nborschke. Thanks for your contribution.
You should revert the changes generated by the automatic formatter.
You should also add your changes to the other themes.

2018-10-31 21:12 UTC, mauriciofauth commented on js/error_report.js
> +            '<div class="error" id="error_notification"></div>'
I think you should use `class` here instead of `id`.

2018-10-31 21:12 UTC, mauriciofauth commented on js/functions.js
> +            seeMore = '<fieldset id=\'seeMoreFieldSet\' class=\'tblFooters center\'>' +
I think you should use `class` here instead of `id`.

2018-10-31 21:12 UTC, mauriciofauth commented on js/functions.js
> +        var central_columns_dialog = '<div id=\'central_columns_dialog\'>' +
I think you should use `class` here instead of `id`.

2018-10-31 21:12 UTC, mauriciofauth commented on js/server_status_monitor.js
> +            var tooltipHtml = '<div id="tooltipHtml">';
I think you should use `class` here instead of `id`.

2018-10-31 21:12 UTC, mauriciofauth commented on js/server_status_monitor.js
> +            tooltipHtml += '<span id="span1">';
I think you should use `class` here instead of `id`.

2019-01-19 03:02 UTC, closed without merging