Fixes bug #14339 - infinite loop in ajax : «sort by key» drop down menu
phpmyadmin/phpmyadmin pull request #14717
Opened 2018-11-09 16:56 UTC by drm-wntd

Whole array of sort expressions needed to correctly build "sort by key" drop down menu
Fixes bug #14339
Signed-off-by: Stephane Proulx <stephane@m-42.com>

### Description

By calling _getUnsortedSqlAndSortByKeyDropDown with only the first element ($sort_expression[0]), the _getSortByKeyDropDown function cannot set the "selected" element in the drop down list when the key has more than one column and that causes the refresh bug. The whole array is need to correctly build the drop down menu.

Fixes #14339

Before submitting pull request, please review the following checklist:

- [x] Make sure you have read our [CONTRIBUTING.md](https://github.com/phpmyadmin/phpmyadmin/blob/master/CONTRIBUTING.md) document.
- [x] Make sure you are making a pull request against the correct branch. For example, for bug fixes in a released version use the corresponding QA branch and for new features use the _master_ branch. If you have a doubt, you can ask as a comment in the bug report or on the mailing list.
- [x] Every commit has proper `Signed-off-by` line as described in our [DCO](https://github.com/phpmyadmin/phpmyadmin/blob/master/DCO). This ensures that the work you're submitting is your own creation.
- [x] Every commit has a descriptive commit message.
- [x] Every commit is needed on its own, if you have just minor fixes to previous commits, you can squash them.
- [x] Any new functionality is covered by tests.

2018-11-13 15:56 UTC, drm-wntd commented
I think bug fixes need to be on branch QA_4_8 instead of Master, right?  So how do I change that? Make a new pull request with the correct branch and close this one or is there another more direct way?

2018-11-13 20:26 UTC, williamdes requested changes
Looks good to me, some modifications can be made ;)

2018-11-13 21:01 UTC, drm-wntd commented on libraries/classes/Display/Results.php
> +        $local_order = (isset($sort_expression) ? implode(', ',$sort_expression) : '');
If I understand correctly, you want to replace «isset» by «!is_null» ?

In the function definition, the parameter was defined as 
«@param string|null $sort_expression»
So are you sure $sort_expression can't be null?

isset() will return FALSE if testing a variable that has been set to NULL.

2018-11-13 21:06 UTC, drm-wntd commented on libraries/classes/Display/Results.php
> +        $sort_expression,
Ok will do, but would be happy if you could tell me what the "?" in front of the type does actually. Never seen this before. (type casting?)

2018-11-13 21:23 UTC, williamdes commented on libraries/classes/Display/Results.php
> +        $sort_expression,
The `?` allows the value to be null or to be the type defined.
This is type hinting :)
See: https://secure.php.net/manual/en/functions.returning-values.php#functions.returning-values.type-declaration
See: https://secure.php.net/manual/en/functions.arguments.php#functions.arguments.type-declaration

2018-11-13 21:31 UTC, williamdes commented on libraries/classes/Display/Results.php
> +        $local_order = (isset($sort_expression) ? implode(', ',$sort_expression) : '');
Yes, is set and is null are different things
I know that you can use `isset` to check that the variable is not null but since is it always defined and that we use `phpstan` It is better to use `is_null`.

`$sort_expression` can be null or an array, this is why `array|null` is represented as `?array`.

2018-11-13 21:33 UTC, williamdes commented on libraries/classes/Display/Results.php
> +        $local_order = (isset($sort_expression) ? implode(', ',$sort_expression) : '');
@drm-wntd Even better: You can use `is_array($sort_expression)`

2018-11-13 21:41 UTC, drm-wntd commented on libraries/classes/Display/Results.php
> +        $sort_expression,
Thanks for the info.

2018-11-13 21:49 UTC, drm-wntd commented on libraries/classes/Display/Results.php
> +        $local_order = (isset($sort_expression) ? implode(', ',$sort_expression) : '');
The changes were made.

2018-11-13 21:53 UTC, williamdes approved these changes
Perfect @drm-wntd !
Looks good to me.
Thank you for the changes ;)

2018-11-24 22:23 UTC, MauricioFauth approved these changes

2018-11-24 22:28 UTC, MauricioFauth requested changes
Hi, @drm-wntd. Thanks for your contribution.

Before we can merge your pull request, can you [change the base branch](https://help.github.com/articles/changing-the-base-branch-of-a-pull-request/) to `QA_4_8`?

Thank you.

2018-11-24 22:41 UTC, drm-wntd commented
Changed the base, but now got conflicts, did I change the base at the right place? Or must I resubmit the pull request with the modifications on base QA_4_8? New to this, sorry. ;-)

2018-11-24 23:54 UTC, mauriciofauth commented
It's because your branch is based on _master_. You have create a branch based on _QA_4_8_, apply your changes and then you can force push (`git push -f`). If there are any doubts, just ask.

2018-11-25 02:20 UTC, drm-wntd commented
I created a new branch on QA_4_8 with the [fix](https://github.com/drm-wntd/phpmyadmin/commit/87f56c86009ac48e8538982d4ed2feecb509c40f), want me to create a new pull request with it? 

I guess we can close this pull request because it's based on master...

2018-11-25 02:41 UTC, mauriciofauth commented
If I am not mistaken, if you keep the same branch name, this pull pull request will be updated. But it's okay to close this pull request and open a new one. Feel free to do this. :smile:

2018-11-25 03:32 UTC, ibennetch commented
This is what I would do. It sounds worse than it is because I tried to verbosely explain each step.

* Checkout your branch drm-wntd-fix-bug-#14339 `git checkout drm-wntd-fix-bug-#14339`
* Find the commit you've authored (with `git log origin/master..`, which gives us 347cd3f6016896dc5fcaacde8d0758a448bdd903), so you can copy and paste that directly.
* Reset your drm-wntd-fix-bug-#14339 branch against the QA_4_8 branch. If you plan to do much more development on this branch, you'd want to [change the upstream branch](https://stackoverflow.com/a/4879224) in Git, but for what we're doing that isn't strictly needed. Run `git reset --hard origin/QA_4_8`. This replaces your entire branch with the upstream QA_4_8 branch, in the process your commit is becoming orphaned and not attached to any branch.
* Now you have to cherry-pick your work in to that branch. Remember the commit ID we got in the first step? You'll need that here: `git cherry-pick 347cd3f6016896dc5fcaacde8d0758a448bdd903`. Because Git keeps all commits until the garbage collector runs (which might be for 30 days, but I don't really know), your orphaned commit isn't lost even though it's not connected to any branch. So cherry-pick puts it in this branch again.
* Unfortunately, that would be it except I noticed your signoff message does not seem to include your real name, which we require for legal reasons. You can change the name used by Git with `git config --global user.name "Mona Lisa"`, using of course your real name instead of the example name used by the fine folks at Github.
* Now that Git knows who you are, you can amend the commit. I believe the command `git commit --amend -s` will accomplish that, but if not you could do `git commit --amend` and manually edit the name that appears in the commit log message.
* Finally, we're ready to force push the whole work back to your Github repository, which will automatically update this pull request. You'll need to use the proper name of your own remote (which you pushed to before and could see with `git remote -v`). Use `git push remote drm-wntd-fix-bug-#14339`, substituting your remote name for 'remote'.

If you get hung up on this, we can gladly help you out further.

2018-11-25 03:50 UTC, drm-wntd commented
Ok... thank you for all that info, but I already opened another pull request. I'll make a note of it in case it happens again.

2018-11-25 03:50 UTC, closed without merging