[cs] remove unused brackets, clean unused property assign, remove unused imports + sort them
phpmyadmin/phpmyadmin pull request #14741
Opened 2018-11-25 09:00 UTC by TomasVotruba

Follow-up to #14738 

Before submitting pull request, please review the following checklist:

- [x] Make sure you have read our [CONTRIBUTING.md](https://github.com/phpmyadmin/phpmyadmin/blob/master/CONTRIBUTING.md) document.
- [x] Make sure you are making a pull request against the correct branch. For example, for bug fixes in a released version use the corresponding QA branch and for new features use the _master_ branch. If you have a doubt, you can ask as a comment in the bug report or on the mailing list.
- [x] Every commit has proper `Signed-off-by` line as described in our [DCO](https://github.com/phpmyadmin/phpmyadmin/blob/master/DCO). This ensures that the work you're submitting is your own creation.
- [x] Every commit has a descriptive commit message.
- [x] Every commit is needed on its own, if you have just minor fixes to previous commits, you can squash them.
- [x] Any new functionality is covered by tests.

2018-11-25 09:04 UTC, TomasVotruba commented
Failing codeclimate are 2 suggestions to already existing code. Not related to change

2018-11-25 21:35 UTC, williamdes requested changes

2018-11-25 21:35 UTC, williamdes commented on libraries/classes/Header.php
> -use PhpMyAdmin\Url;
Maybe something needs to be fixed:
```
------ ---------------------------------------------------------------------- 
  Line   libraries/classes/Header.php                                          
 ------ ---------------------------------------------------------------------- 
  272    Class PhpMyAdmin\Url referenced with incorrect case: PhpMyAdmin\URL.  
 ------ ----------------------------------------------------------------------
```

2018-11-25 21:35 UTC, williamdes commented on libraries/classes/Controllers/Table/TableStructureController.php
> -use PhpMyAdmin\SqlParser\Statements\CreateStatement;
Please add back this line, used by phpdoc !
Rebase on latest master :)
And run phpstan `./vendor/bin/phpstan analyse`
You will see why I think this line is needed or the phpdoc must be fixed

2018-11-26 09:05 UTC, TomasVotruba commented on libraries/classes/Header.php
> -use PhpMyAdmin\Url;
Even if this is misscase, the `URL` is in the same namespace as this class, so it can be removed.

2018-11-26 09:07 UTC, TomasVotruba commented on libraries/classes/Header.php
> -use PhpMyAdmin\Url;
Fixed :+1:

2018-11-26 09:08 UTC, TomasVotruba commented on libraries/classes/Controllers/Table/TableStructureController.php
> -use PhpMyAdmin\SqlParser\Statements\CreateStatement;
Fixed :+1:  + I've added PHPStan to Travis, so you don't have to report these errors manually.

2018-11-26 13:48 UTC, TomasVotruba commented
Travis fails seem unrelated

2018-11-26 13:53 UTC, williamdes approved these changes

2018-11-26 14:36 UTC, MauricioFauth approved these changes

2018-11-26 15:29 UTC, mauriciofauth commented on libraries/classes/DatabaseInterface.php
> -        return $res;
This change seems to be causing the Travis failure.

2018-11-26 16:07 UTC, TomasVotruba commented on libraries/classes/DatabaseInterface.php
> -        return $res;
Oh, I'm sorry about that

2018-11-26 16:47 UTC, TomasVotruba commented on libraries/classes/DatabaseInterface.php
> -        return $res;
Is that really related to mariadb install?

https://travis-ci.org/phpmyadmin/phpmyadmin/jobs/459818713#L89

2018-11-26 16:52 UTC, TomasVotruba commented on libraries/classes/DatabaseInterface.php
> -        return $res;
Looks like `or` vs `||` behaves differently - [Stackoverflow](https://stackoverflow.com/a/5998330/1348344). I'll try to revert this change then to see if that fixes Travis

2018-11-26 17:05 UTC, TomasVotruba commented on libraries/classes/DatabaseInterface.php
> -        return $res;
It's still failing: https://travis-ci.org/phpmyadmin/phpmyadmin/jobs/459841731#L89 :+1:

2018-11-26 18:30 UTC, merged

2018-11-26 18:30 UTC, mauriciofauth commented
Merged, thanks for your contribution!

2018-11-26 18:57 UTC, TomasVotruba commented
Thanks, in next PR I'll add tool for checking all this in CI, so you never have to do it again.

Thank you for such open and reactions. It's very motivating to contribute

2018-11-26 18:58 UTC, williamdes commented
@TomasVotruba Thank you for contributing !