Extract HTML from view_operations.php to a Twig template
phpmyadmin/phpmyadmin pull request #14836
Opened 2019-01-09 00:00 UTC by thicolares

### Description
- Extract HTML from view_operations.php to a Twig template
- Performed some local smoke tests
    - Rename a view
    - Delete a view

Before submitting pull request, please review the following checklist:

- [x] Make sure you have read our [CONTRIBUTING.md](https://github.com/phpmyadmin/phpmyadmin/blob/master/CONTRIBUTING.md) document.
- [x] Make sure you are making a pull request against the correct branch. For example, for bug fixes in a released version use the corresponding QA branch and for new features use the _master_ branch. If you have a doubt, you can ask as a comment in the bug report or on the mailing list.
- [x] Every commit has proper `Signed-off-by` line as described in our [DCO](https://github.com/phpmyadmin/phpmyadmin/blob/master/DCO). This ensures that the work you're submitting is your own creation.
- [x] Every commit has a descriptive commit message.
- [x] Every commit is needed on its own, if you have just minor fixes to previous commits, you can squash them.
- [x] Any new functionality is covered by tests.

2019-01-09 00:15 UTC, thicolares commented
The Travis CI build failed. I going to check this out in a few minutes

2019-01-09 11:28 UTC, williamdes approved these changes
LGTM

Thank you @thicolares

2019-01-10 17:07 UTC, MauricioFauth requested changes
Hi, @thicolares. Thanks for your contribution.

Could you rename the template to `templates/table/operations/view.twig`?

2019-01-10 18:03 UTC, thicolares commented on templates/view_operations.twig
> +        <legend>{% trans 'Delete data or table' %} novo</legend>
OMG. Thank you for that

2019-01-10 18:04 UTC, thicolares commented on view_operations.php
> +    'table_name_in_html_entities' => htmlspecialchars($GLOBALS['table']),
Ok. I didn't know. Thank you for all your feedbacks

2019-01-10 18:12 UTC, thicolares commented on view_operations.php
> +    'table_name_in_html_entities' => htmlspecialchars($GLOBALS['table']),
Ok. Thank you for all your feedbacks

2019-01-11 01:08 UTC, MauricioFauth approved these changes

2019-01-11 01:11 UTC, merged

2019-01-11 01:11 UTC, mauriciofauth commented
Merged, thanks for your contribution!