Extracted html from transformation_overview.php to template/transformation_overview.twig
phpmyadmin/phpmyadmin pull request #14852
Opened 2019-01-12 04:28 UTC by sharik709

Signed-off-by: Sharik Shaikh <shaikhsharik709@gmail.com>

### Description

Extracted html from transformation_overview.php to template/transformation_overview.twig

Fixes #

Before submitting pull request, please review the following checklist:

- [Yes] Make sure you have read our [CONTRIBUTING.md](https://github.com/phpmyadmin/phpmyadmin/blob/master/CONTRIBUTING.md) document.
- [Yes] Make sure you are making a pull request against the correct branch. For example, for bug fixes in a released version use the corresponding QA branch and for new features use the _master_ branch. If you have a doubt, you can ask as a comment in the bug report or on the mailing list.
- [Yes] Every commit has proper `Signed-off-by` line as described in our [DCO](https://github.com/phpmyadmin/phpmyadmin/blob/master/DCO). This ensures that the work you're submitting is your own creation.
- [Yes] Every commit has a descriptive commit message.
- [Yes] Every commit is needed on its own, if you have just minor fixes to previous commits, you can squash them.
- [Yes] Any new functionality is covered by tests.

2019-01-12 16:44 UTC, williamdes approved these changes

2019-01-15 18:26 UTC, MauricioFauth requested changes
Hi, @sharik709. Thanks for your contribution.

2019-01-18 09:11 UTC, sharik709 commented on templates/transformation_overview.twig
> +		<i>{{ mimeType | escape }}</i>
OK got it. Ill remove them.

2019-01-18 09:11 UTC, sharik709 commented on templates/transformation_overview.twig
> +<h2>{{ label.available_MIME_types }}</h2>
Ok. Ill change it.

2019-01-18 09:12 UTC, sharik709 commented on templates/transformation_overview.twig
> +				{{ ttype._pgettext | escape }}
ok. Ill replace it.

2019-01-18 09:12 UTC, sharik709 commented on templates/transformation_overview.twig
> +{% for mimeType in types.mimetype %}
ok.

2019-01-18 09:13 UTC, sharik709 commented on templates/transformation_overview.twig
> +<br />
Ok got it.

2019-01-30 15:18 UTC, MauricioFauth approved these changes

2019-01-30 15:19 UTC, merged