fix issue #14840
phpmyadmin/phpmyadmin pull request #14879
Opened 2019-01-20 15:55 UTC by bahl24

Signed-off-by: Nitish Bahl <nitishbhal24@gmail.com>

### Description

css file modified to incorporate reset button

Fixes #14840 

Before submitting pull request, please review the following checklist:

- [ ] Make sure you have read our [CONTRIBUTING.md](https://github.com/phpmyadmin/phpmyadmin/blob/master/CONTRIBUTING.md) document.
- [ ] Make sure you are making a pull request against the correct branch. For example, for bug fixes in a released version use the corresponding QA branch and for new features use the _master_ branch. If you have a doubt, you can ask as a comment in the bug report or on the mailing list.
- [ ] Every commit has proper `Signed-off-by` line as described in our [DCO](https://github.com/phpmyadmin/phpmyadmin/blob/master/DCO). This ensures that the work you're submitting is your own creation.
- [ ] Every commit has a descriptive commit message.
- [ ] Every commit is needed on its own, if you have just minor fixes to previous commits, you can squash them.
- [ ] Any new functionality is covered by tests.

2019-01-21 04:12 UTC, bahl24 commented
@williamdes @mauriciofauth kindly review and give feedback on the pull request.

2019-01-28 22:04 UTC, shucon approved these changes

2019-01-28 22:27 UTC, williamdes approved these changes

2019-03-06 22:53 UTC, williamdes commented
@mauriciofauth Can you share your thoughts or merge ?

2019-03-12 17:40 UTC, MauricioFauth requested changes
Hi, @bahl24. Thanks for your contribution.

As I commented on https://github.com/phpmyadmin/phpmyadmin/issues/14840#issuecomment-470745964, I think the reset buttons should not be bold.

2019-05-18 18:44 UTC, closed without merging