fixes issue #14430
phpmyadmin/phpmyadmin pull request #14880
Opened 2019-01-20 16:09 UTC by bahl24

Signed-off-by: Nitish Bahl <nitishbhal24@gmail.com>

### Description

This is not a permanent fix for the issue but in order to justify
`There is a problem with Util::currentUserHasPrivilege():	// There is a problem with Util::currentUserHasPrivilege(): // it does not detect all kinds of privileges, for example // it does not detect all kinds of privileges, for example // a direct privilege on a specific routine. So, at this point,	// a direct privilege on a specific routine. So, at this point, // we show the Execute link, hoping that the user has the correct rights.`

this fix is the only solution until Util::currentUserHasPrivilege() is fully fixed

Fixes #14430 

Before submitting pull request, please review the following checklist:

- [ ] Make sure you have read our [CONTRIBUTING.md](https://github.com/phpmyadmin/phpmyadmin/blob/master/CONTRIBUTING.md) document.
- [ ] Make sure you are making a pull request against the correct branch. For example, for bug fixes in a released version use the corresponding QA branch and for new features use the _master_ branch. If you have a doubt, you can ask as a comment in the bug report or on the mailing list.
- [ ] Every commit has proper `Signed-off-by` line as described in our [DCO](https://github.com/phpmyadmin/phpmyadmin/blob/master/DCO). This ensures that the work you're submitting is your own creation.
- [ ] Every commit has a descriptive commit message.
- [ ] Every commit is needed on its own, if you have just minor fixes to previous commits, you can squash them.
- [ ] Any new functionality is covered by tests.

2019-01-21 04:11 UTC, bahl24 commented
@williamdes @mauriciofauth kindly review the pull request and suggest any changes.

2019-01-22 13:06 UTC, bahl24 commented
@williamdes kindly review, I realized that pr should be for QA_4_8 branch rather than master as this is a bug fix.
Sorry for confusion.

2019-01-28 22:01 UTC, shucon requested changes

2019-01-28 22:01 UTC, shucon commented on libraries/classes/Rte/RteList.php
> +            if (Util::currentUserHasPrivilege('EXECUTE', $db)||1) {
I'm a bit unsure about this. Why use if condition if you used `||1` ?

2019-01-29 02:31 UTC, bahl24 commented
This is because Util::currentUserHasPrivilege() is not working properly, as written in the same file, it is also mentioned that execute permission be granted until it is fixed. Thus I have provided a temporary fix for the same

2019-01-29 03:43 UTC, bahl24 commented on libraries/classes/Rte/RteList.php
> +            if (Util::currentUserHasPrivilege('EXECUTE', $db)||1) {
@shucon This is because Util::currentUserHasPrivilege() is not working properly, as written in the same file, it is also mentioned that execute permission be granted until it is fixed. Thus I have provided a temporary fix for the same
Kindly take a look at the comment just above the line I modified.
` // There is a problem with Util::currentUserHasPrivilege():
        // it does not detect all kinds of privileges, for example	        // it does not detect all kinds of privileges, for example
        // a direct privilege on a specific routine. So, at this point,	        // a direct privilege on a specific routine. So, at this point,
        // we show the Execute link, hoping that the user has the correct rights.	        // we show the Execute link, hoping that the user has the correct rights.
        // Also, information_schema might be hiding the ROUTINE_DEFINITION	        // Also, information_schema might be hiding the ROUTINE_DEFINITION
        // but a routine with no input parameters can be nonetheless executed.	        // but a routine with no input parameters can be nonetheless executed.
        // Check if the routine has any input parameters. If it does,	        // Check if the routine has any input parameters. If it does,
        // we will show a dialog to get values for these parameters,	        // we will show a dialog to get values for these parameters,
        // otherwise we can execute it directly.	        // otherwise we can execute it directly.`
For showing the execute link I have modified the if statement

2019-03-12 17:52 UTC, MauricioFauth requested changes
Hi, @bahl24. Thanks for your contribution.

It's best to fix the issue permanently. Temporary fixes tend to become permanent very often.

2019-03-12 17:52 UTC, mauriciofauth commented on libraries/classes/Rte/RteList.php
> +            if (Util::currentUserHasPrivilege('EXECUTE', $db)||1) {
It would be better to have the if removed completely.

2019-04-04 20:58 UTC, williamdes requested changes
Sorry, I can not merge this fix
Too much of a hack for me, can you please find another way to fix this issue ?

2019-04-11 00:23 UTC, mauriciofauth commented
Hi, @bahl24. Thank you for your contribution.
I am closing this based on the latest reviews.
If you have another solution you can open a new PR or reopen this one.

2019-04-11 00:23 UTC, closed without merging