Fixed 500 error in MultiTableQuery page
phpmyadmin/phpmyadmin pull request #14902
Opened 2019-01-25 06:49 UTC by Gaurav-Punjabi

Fixed the 500 error when a empty query is passed to MultiTableQuery.
This is in reference to solve issue #14298.

### Description
Fixed error 500 on MultiTableQuery page when a empty query is passed.

Please describe your pull request.

Fixes #14298 

Before submitting pull request, please review the following checklist:

- [ ] Make sure you have read our [CONTRIBUTING.md](https://github.com/phpmyadmin/phpmyadmin/blob/master/CONTRIBUTING.md) document.
- [ ] Make sure you are making a pull request against the correct branch. For example, for bug fixes in a released version use the corresponding QA branch and for new features use the _master_ branch. If you have a doubt, you can ask as a comment in the bug report or on the mailing list.
- [ ] Every commit has proper `Signed-off-by` line as described in our [DCO](https://github.com/phpmyadmin/phpmyadmin/blob/master/DCO). This ensures that the work you're submitting is your own creation.
- [ ] Every commit has a descriptive commit message.
- [ ] Every commit is needed on its own, if you have just minor fixes to previous commits, you can squash them.
- [ ] Any new functionality is covered by tests.

2019-01-25 08:22 UTC, williamdes requested changes

2019-01-25 08:22 UTC, williamdes commented on js/db_multi_table_query.js
> +            PMA_ajaxShowMessage('Please enter the sql query first.', false, 'error');
Can you use `PMA_messages` like in this example (for translation) https://github.com/phpmyadmin/phpmyadmin/blob/4d8310432f2c46a425cd1a61c5fec3b9e82b82a7/js/db_search.js#L55

Thank you for the PR :)

2019-01-25 11:53 UTC, Gaurav-Punjabi commented on js/db_multi_table_query.js
> +            PMA_ajaxShowMessage('Please enter the sql query first.', false, 'error');
Yeah sure

2019-01-27 07:32 UTC, williamdes approved these changes
LGTM
Thank you !

2019-01-27 08:29 UTC, ibennetch requested changes

2019-01-27 10:44 UTC, Gaurav-Punjabi commented on js/messages.php
> +/* DB MULTI TABLE QUERY */
Okay no problem

2019-01-27 10:44 UTC, Gaurav-Punjabi commented on js/messages.php
> +$js_messages['strEmptyQuery'] = __('Please enter the sql query first.');
Yeah sure. Will change it

2019-01-29 20:01 UTC, Gaurav-Punjabi commented on js/messages.php
> +$js_messages['strEmptyQuery'] = __('Please enter the sql query first.');
Done made the changes

2019-01-29 22:28 UTC, williamdes approved these changes

2019-02-27 02:27 UTC, MauricioFauth approved these changes

2019-02-27 16:39 UTC, merged

2019-02-27 16:39 UTC, mauriciofauth commented
Merged, thanks for your contribution!