Issue #14909 -
phpmyadmin/phpmyadmin pull request #14925
Opened 2019-02-01 10:01 UTC by saurass

# Description
Fixes #14909
- Add config option to server_settings -> settings -> config.
- A form (Time_form) enables you to configure first day of the week.
- This will cause datePicker to pick selected day as first day of week.

## Approach
- In libraries/classes/Config/Forms/User/UserFormList.php added 'Config' in user form list array .
- In libraries/user_preferences.inc.php added 'Config' Tab icon.
- Made Config Form in libraries/classes/Config/Forms/User/ConfigForm.php, adding required fields.
- In libraries/classes/Config/Descriptions.php we describe input fields, form name and description.
- In libraries/config.values.php added the list of possible values for input field 'FirstDay'.
- In js/messages.php declare JS variable 'firstDayCalendar' and set its value same as that selected by user in config.
- In js/functions.js we declare 'firstDay: firstDayCalendar'.

## Result
- The datepicker shows first day of week as per selection by user in config -> time form.
- Video illustrating the fix https://drive.google.com/open?id=189VmqBHofYQNYdrY1BklT9ow0vip5pze

## WIP tasks
- Writing tests for these new features.
- Fixing lint errors.

# Contribution Checklist
Before submitting pull request, please review the following checklist:

- [x] Make sure you have read our [CONTRIBUTING.md](https://github.com/phpmyadmin/phpmyadmin/blob/master/CONTRIBUTING.md) document.
- [x] Make sure you are making a pull request against the correct branch. For example, for bug fixes in a released version use the corresponding QA branch and for new features use the _master_ branch. If you have a doubt, you can ask as a comment in the bug report or on the mailing list.
- [x] Every commit has proper `Signed-off-by` line as described in our [DCO](https://github.com/phpmyadmin/phpmyadmin/blob/master/DCO). This ensures that the work you're submitting is your own creation.
- [x] Every commit has a descriptive commit message.
- [x] Every commit is needed on its own, if you have just minor fixes to previous commits, you can squash them.
- [ ] Any new functionality is covered by tests.

2019-02-01 11:59 UTC, williamdes approved these changes
LGTM
Thank you @saurass !

Maybe adding some documentation `.rst` ?
cc @ibennetch

2019-02-01 14:02 UTC, ibennetch requested changes
This looks great. It's very thorough and touches on several aspects of the phpMyAdmin code.

I think you missed adding this also to `libraries/config.default.php`, where you should set the default to Sunday. Users can then use a line in `config.inc.php` or the user preferences form to change the default.

This doesn't seem to work on the calendar when in "grid edit" mode, that is where I can double-click on an entry in the Browse view in order to quickly edit, or in the Event editor. I suspect there are other instances of calling `PMA_addDatepicker` sprinkled throughout the code and we should modify all of them.

I have a few other suggestions I'll post in-line as well.

2019-02-01 14:03 UTC, ibennetch commented on js/messages.php
> +echo "var firstDayCalendar = '" , $GLOBALS['cfg']['FirstDay'] , "';\n";
...or FirstDayOfCalendar, that would be suitable as well without being too long.

2019-02-01 14:05 UTC, ibennetch commented
It appears as if you have not used your real name in the signoff message. For compliance reasons, we are required to ask you for your name. You can modify your existing commit with `git commit —amend` and pushing again to your repository (it may be necessary to `—force` push), or we can rebase all of your commits in to one with a signoff, once this is complete.

If you have any questions or concerns, please let us know.

2019-02-01 14:12 UTC, saurass commented on js/messages.php
> +echo "var firstDayCalendar = '" , $GLOBALS['cfg']['FirstDay'] , "';\n";
Yeah 'FirstDayOfCalendar' is short and elaborative. I will change it to that.

2019-02-01 14:15 UTC, saurass commented on libraries/classes/Config/Forms/User/UserFormList.php
> +        'Config',
That would be great, but in case we need to add other configurations, in various aspects, Config Form may prove useful.

Anyways I will move it to the path as you specified for now.

2019-02-01 14:15 UTC, saurass commented on libraries/config.values.php
> +        '7' => __('Sunday'),
Lemme have a look at it once.

2019-02-01 14:17 UTC, saurass commented
Yeah I missed adding it to `libraries/config.default.php` . I will get it done

2019-02-01 14:23 UTC, ibennetch commented
I think the best place to add the documentation is probably the Design section: https://docs.phpmyadmin.net/en/latest/config.html#design-customization

2019-02-01 17:51 UTC, saurass commented
@ibennetch @williamdes , I just made changes. Please have a look .

2019-02-01 19:26 UTC, williamdes approved these changes

2019-02-02 18:10 UTC, saurass commented
@williamdes  @ibennetch I have added the documentations as well. Please review : )

2019-02-03 03:54 UTC, ibennetch requested changes
I think you're really close on this, there are a few additional changes I have suggested but this is very close to being ready to merge.

2019-02-03 03:54 UTC, ibennetch commented on doc/config.rst
> +    clickjacking. Setting this to 'sameorigin' prevents phpMyAdmin to be
While we don't like extra spaces at the end of lines, this change should be part of another commit to keep the commit history clear here; otherwise one might see this in the commit log for your other work and think it's related.

It's best to revert the removal of the extra space characters.

2019-02-03 03:54 UTC, ibennetch commented on doc/config.rst
> +    :default: 7
So it appears that the documented options for this are 0-6, but they seem to use the modulus operator to determine the number so 14 is also Sunday. That explains why both 0 and 7 are accepted values.

However, since the week starts on Sunday by most calendars, we should use the 0-6 range for Sunday-Saturday, rather than 1-7 with Monday-Sunday. It's a tradeoff between whether users will be more confused by starting counting with 0 or starting the week on Monday, and I think the right thing to do is default to 0 and change the help text to read Sunday to Saturday instead.

2019-02-03 03:54 UTC, ibennetch commented on libraries/config.values.php
> +        '7' => __('Sunday'),
I still think this should start on Sunday, as well.

2019-02-03 04:43 UTC, saurass commented on libraries/config.values.php
> +        '7' => __('Sunday'),
When I use 0 for 'sunday' here, Instead of saving 0 in $cfg['FirstDayOfWeek'] , it picks the week day name (Sunday, Monday etc..) instead of (0,1,2,3....) So, it dosen't work furthur. 

But yes in config.default, value by user can be set 0 to 6 (Sunday to Saturday). That is working well.

2019-02-03 04:43 UTC, saurass commented on doc/config.rst
> +    clickjacking. Setting this to 'sameorigin' prevents phpMyAdmin to be
Ok, I will revert the removal of extra space

2019-02-03 04:44 UTC, saurass commented on doc/config.rst
> +    :default: 7
Okay I will get that done.

2019-02-03 04:58 UTC, saurass commented
@ibennetch @williamdes , please review and suggest changes.

2019-02-05 18:21 UTC, saurass commented
@ibennetch @williamdes is something left ?
Please lemme know, I am eager to get it merged.

Thanks ( :

2019-04-17 13:25 UTC, saurass commented
@sudo-bot Deploy pr

2019-05-05 08:50 UTC, williamdes approved these changes

2019-08-20 09:47 UTC, williamdes commented
@mauriciofauth @ibennetch I really want to merge this enhancement, it is simple and well done.
Please review and comment

@lem9 Do you have comments about this enhancement ?

2019-10-15 01:13 UTC, MauricioFauth approved these changes

2019-11-07 20:44 UTC, merged

2019-11-07 20:44 UTC, mauriciofauth commented
Merged, thanks for your contribution!

2019-11-07 21:00 UTC, saurass commented
Great, thanks a lot 😊

2019-11-07 21:32 UTC, dddns commented
Thank you @saurass and @mauriciofauth !