Filling existing fields form while editing a view
phpmyadmin/phpmyadmin pull request #14941
Opened 2019-02-08 11:39 UTC by bahl24

### Description

Fills form based on GET params available

Fixes #14926 https://github.com/phpmyadmin/phpmyadmin/issues/14916#issuecomment-459736492
Testing-
Go to structure tab of a view and click on edit view.

Before submitting pull request, please review the following checklist:

- [ ] Make sure you have read our [CONTRIBUTING.md](https://github.com/phpmyadmin/phpmyadmin/blob/master/CONTRIBUTING.md) document.
- [ ] Make sure you are making a pull request against the correct branch. For example, for bug fixes in a released version use the corresponding QA branch and for new features use the _master_ branch. If you have a doubt, you can ask as a comment in the bug report or on the mailing list.
- [ ] Every commit has proper `Signed-off-by` line as described in our [DCO](https://github.com/phpmyadmin/phpmyadmin/blob/master/DCO). This ensures that the work you're submitting is your own creation.
- [ ] Every commit has a descriptive commit message.
- [ ] Every commit is needed on its own, if you have just minor fixes to previous commits, you can squash them.
- [ ] Any new functionality is covered by tests.

2019-02-08 11:43 UTC, bahl24 commented
@ibennetch @williamdes Kindly test the pr by Testing-
Go to structure tab of a view and click on edit view.
This is in response to https://github.com/phpmyadmin/phpmyadmin/issues/14916#issuecomment-459736492

2019-02-08 13:40 UTC, bahl24 commented
@ibennetch @williamdes Both the issues #14926 #14916  have been fixed, kindly check and test.

2019-02-18 06:19 UTC, bahl24 commented
@ibennetch @williamdes Can you test this?

2019-02-24 06:01 UTC, bahl24 commented
@williamdes @ibennetch Kindly take a look at it

2019-02-26 20:11 UTC, bahl24 commented
@ibennetch What do you think?

2019-03-01 13:00 UTC, williamdes commented
@sudo-bot Deploy pr

2019-03-14 23:50 UTC, williamdes commented
The code looks really good, when I have tested it I will merge this PR ;)

2019-03-15 01:15 UTC, bahl24 commented
> The code looks really good, when I have tested it I will merge this PR ;)

I am glad you liked it, while testing kindly check why codecov test is failing. Or maybe I should push recent changes to the branch.

2019-03-20 18:02 UTC, MauricioFauth requested changes

2019-03-20 18:02 UTC, mauriciofauth commented on view_create.php
> +    'operation' => (isset($_GET['view']['operation']) ? $_GET['view']['operation'] : ''),
You can use `'operation' => $_GET['view']['operation'] ?? '',`.

2019-03-20 18:06 UTC, mauriciofauth commented on view_create.php
> +    'operation' => (isset($_GET['view']['operation']) ? $_GET['view']['operation'] : ''),
Sorry, I forgot that the null coalescing operator is PHP 7+ and this PR is targeting _QA_4_8_.

2019-03-21 05:25 UTC, bahl24 commented
Kindly test this, I think there should be no issues

2019-03-25 16:42 UTC, bahl24 commented
@mauriciofauth @williamdes Did you test this PR?

2019-03-25 21:36 UTC, williamdes approved these changes
Merged, thank you @bahl24 for the contribution !
I have done some minor changes and rebased the branch before merge

2019-03-25 21:47 UTC, merged