Tooltip for truncated strings #14767
phpmyadmin/phpmyadmin pull request #14960
Opened 2019-02-17 11:49 UTC by amarjitsingh52922

Signed-off-by: amarjitaa <amarjitsingh52922@gmail.com>

### Description
Added enhancement as tooltip for truncated strings with limit set to 200 but it configurable in libraries/config.default.php as 
Line 2738
$cfg['CommentLimitChars'] = 200;

Fixes #
as described above in Description
Before submitting pull request, please review the following checklist:

- [x] Make sure you have read our [CONTRIBUTING.md](https://github.com/phpmyadmin/phpmyadmin/blob/master/CONTRIBUTING.md) document.
- [x] Make sure you are making a pull request against the correct branch. For example, for bug fixes in a released version use the corresponding QA branch and for new features use the _master_ branch. If you have a doubt, you can ask as a comment in the bug report or on the mailing list.
- [x] Every commit has proper `Signed-off-by` line as described in our [DCO](https://github.com/phpmyadmin/phpmyadmin/blob/master/DCO). This ensures that the work you're submitting is your own creation.
- [x] Every commit has a descriptive commit message.
- [x] Every commit is needed on its own, if you have just minor fixes to previous commits, you can squash them.
- [x] Any new functionality is covered by tests.

2019-02-17 21:12 UTC, williamdes approved these changes
LGTM
Can you also add `.rst` documentation ?

2019-02-18 10:52 UTC, amarjitsingh52922 commented
@williamdes  sorry didn't understand exactly
"Can you also add `.rst` documentation ?"
pl. elaborate

2019-03-02 11:36 UTC, williamdes commented
@amarjitsingh52922 Can you please add a block in `doc/config.rst` ?

2019-03-12 14:33 UTC, amarjitsingh52922 commented
@williamdes sorry was busy past few days will update by tomorrow and will try to do more commit

2019-03-16 09:37 UTC, williamdes approved these changes

2019-04-04 04:02 UTC, MauricioFauth requested changes
Hi, @amarjitsingh52922. Thank you for your contribution.

This pull request only truncate the strings in tooltips of the table's comment. The issue talks about truncate strings in table rows.
Look at an example here: https://demo.phpmyadmin.net/master-config/sql.php?server=1&db=sakila&table=film_text&pos=0

2019-04-04 04:07 UTC, mauriciofauth commented
Could you use your full name in the signature tag?
We require a full name for legal compliance reasons.
For example: `Signed-off-by: Jane Developer <jane@example.org>`
See [Developer's Certificate of Origin](https://github.com/phpmyadmin/phpmyadmin/blob/master/DCO#L39)

2019-04-09 18:34 UTC, amarjitsingh52922 commented on templates/display/results/comment_for_row.twig
> +            title="{{ comments_map[fields_meta.table][fields_meta.name]|slice(0, comment_limit_chars) }}…
oh ok will add that feature also
thanks

2019-04-09 18:37 UTC, amarjitsingh52922 commented on templates/display/results/comment_for_row.twig
> +            title="{{ comments_map[fields_meta.table][fields_meta.name] }}">
i am limiting length of title also thats why added in if else.
as  in if its limiting to first {comment_limit_chars} and in else its using full length
is it fine or i am missing something?

2019-08-15 05:37 UTC, closed without merging