Enhancement#14735 Empty String Removed
phpmyadmin/phpmyadmin pull request #14961
Opened 2019-02-18 12:10 UTC by kartik1000

Signed-off-by: Kartik Kathuria <kathuriakartik0@gmail.com>

### Description
The Enhancement will remove the empty string default as suggested in #14735 And will now display A 'NONE' String instead of an Empty String
Enhancement #14735 
### Steps to See the Changes
Go to the Form of Creating a new table in some database.
Now in Default value if you select 'as defined' and do not enter any default value or put simply blank spaces and create that column, now you will see a 'NONE' string instead of some empty value in that field.
Before submitting pull request, please review the following checklist:

- [ ] Make sure you have read our [CONTRIBUTING.md](https://github.com/phpmyadmin/phpmyadmin/blob/master/CONTRIBUTING.md) document.
- [ ] Make sure you are making a pull request against the correct branch. For example, for bug fixes in a released version use the corresponding QA branch and for new features use the _master_ branch. If you have a doubt, you can ask as a comment in the bug report or on the mailing list.
- [ ] Every commit has proper `Signed-off-by` line as described in our [DCO](https://github.com/phpmyadmin/phpmyadmin/blob/master/DCO). This ensures that the work you're submitting is your own creation.
- [ ] Every commit has a descriptive commit message.
- [ ] Every commit is needed on its own, if you have just minor fixes to previous commits, you can squash them.
- [ ] Any new functionality is covered by tests.

2019-02-28 12:38 UTC, williamdes commented
@sudo-bot Deploy PR

2019-02-28 12:47 UTC, williamdes commented
@sudo-bot /deploy pr

2019-02-28 12:49 UTC, williamdes commented
@sudo-bot /deploy pr

2019-02-28 13:02 UTC, williamdes commented
@kartik1000 I can not see the empty string, did I miss something ?
![PR](https://user-images.githubusercontent.com/7784660/53568071-5b3b7300-3b61-11e9-98f7-e5d220093a9e.png)

2019-02-28 13:25 UTC, kartik1000 commented
@williamdes, Hey did you go through the mentioned steps in the PR?(going through as defined sectioned)

2019-02-28 14:02 UTC, williamdes commented
@kartik1000 The PR breaks the export, see:
```sql
CREATE TABLE `aa` (
  `a` varchar(11) NOT NULL DEFAULT 'NONE'
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
```

@kartik1000 The following script should show `NONE` ?
```sql
CREATE TABLE `asa` (
  `a` varchar(11) NOT NULL DEFAULT ''
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
```

You can try on the deployed PR by @sudo-bot

2019-03-25 15:03 UTC, mauriciofauth commented
Hi, @kartik1000. Thank you for your contribution.

Since this is an enhancement and not a bug fix, you should target the _master_ branch instead of _QA_4_8_.

2019-03-25 16:25 UTC, kartik1000 commented
Thanks, @mauriciofauth Shall I make a new PR instead targeted at master branch?

2019-03-25 18:29 UTC, mauriciofauth commented
@kartik1000 You can either rebase this PR or close this PR and open a new one. Whichever is more comfortable for you.

2019-03-25 18:51 UTC, kartik1000 commented
@mauriciofauth, I'll do the required changes. Thanks :)

2019-04-17 21:18 UTC, mauriciofauth commented
@sudo-bot Deploy PR

2019-04-18 08:29 UTC, kartik1000 commented
@mauriciofauth, Hey I changed the base branch. Is it ok Now? Sorry forgot to do it at that point.

2019-05-03 15:27 UTC, MauricioFauth requested changes
This pull request does not fix the issue.
This PR changes the default value '' to 'NONE', which is not the intent.
The solution we are looking for is similar to how we handle NULL values.

2019-05-03 17:06 UTC, kartik1000 commented
Thanks @mauriciofauth for reviewing, I will make the required changes :)

2019-09-12 09:12 UTC, closed without merging