option to increase console font size
phpmyadmin/phpmyadmin pull request #15003
Opened 2019-03-06 18:25 UTC by bahl24

Signed-off-by: Nitish Bahl <nitishbahl24@gmail.com>

### Description

Option to change size of text in console
![screenshot from 2019-03-06 23-53-20](https://user-images.githubusercontent.com/36095178/53903970-ff924d80-406a-11e9-9a06-93a9f8085427.png)
### Testing Instructions
Go to options tab in console and select console size you want

Fixes #14989 

Before submitting pull request, please review the following checklist:

- [ ] Make sure you have read our [CONTRIBUTING.md](https://github.com/phpmyadmin/phpmyadmin/blob/master/CONTRIBUTING.md) document.
- [ ] Make sure you are making a pull request against the correct branch. For example, for bug fixes in a released version use the corresponding QA branch and for new features use the _master_ branch. If you have a doubt, you can ask as a comment in the bug report or on the mailing list.
- [ ] Every commit has proper `Signed-off-by` line as described in our [DCO](https://github.com/phpmyadmin/phpmyadmin/blob/master/DCO). This ensures that the work you're submitting is your own creation.
- [ ] Every commit has a descriptive commit message.
- [ ] Every commit is needed on its own, if you have just minor fixes to previous commits, you can squash them.
- [ ] Any new functionality is covered by tests.

2019-03-06 18:52 UTC, bahl24 commented
@williamdes I have added option to select size of console, should I add option for 
![screenshot from 2019-03-07 00-21-28](https://user-images.githubusercontent.com/36095178/53905596-ef7c6d00-406e-11e9-9180-9c375f03bdf1.png)
or not?
As the feature was removed deliberately earlier?

2019-03-06 19:24 UTC, williamdes commented
I think it makes sense to have it also in the SQL query box :)

@ibennetch ?

2019-03-06 22:35 UTC, shucon requested changes

2019-03-06 22:35 UTC, shucon commented on templates/console/display.twig
> +                        $('#pma_console')[0].style.fontSize = $('#pma_console_options').find('select[name=console_size]')[0].value;
It would be better if you remove inline JS and include it in a JS file.

2019-03-08 09:48 UTC, bahl24 commented
@shucon @williamdes Kindly check

2019-03-08 09:49 UTC, shucon approved these changes

2019-04-12 18:43 UTC, williamdes commented
@sudo-bot Deploy pull-request

2019-04-12 18:48 UTC, williamdes requested changes
![image](https://user-images.githubusercontent.com/7784660/56059387-3e02e280-5d64-11e9-99b7-98e42090f0e8.png)

Works well, @bahl24 can you implement "reset to default" ?

2019-05-04 20:22 UTC, MauricioFauth approved these changes

2019-05-18 16:44 UTC, MauricioFauth reviewed
I think it's better to just change the font size of the query text, not the entire console box. What do you think @williamdes.

2019-05-18 16:57 UTC, williamdes commented
@mauriciofauth yes, I agree

2019-07-24 19:40 UTC, closed without merging