Feat: #15042
phpmyadmin/phpmyadmin pull request #15052
Opened 2019-03-19 14:13 UTC by MrThanlon

Make the logo displaying/hiding in realtime.

Signed-off-by: MrThanlon <1@ch34k.tk>

### Description

Make the logo display/hide in realtime.
I try my best to fit the original code style. And it's my first time to contribute code to phpmyadmin. The method inserting DOM node is quite ugly, however I am actually not familiar with jQuery (I use vuejs most time), so if there are another elegant code, I would like to learn and modify it.
BTW, I do not know how to get the name of current theme so the img file path might not right. If anyone can do so, please tell me.

Feat #15042

Before submitting pull request, please review the following checklist:

- [x] Make sure you have read our [CONTRIBUTING.md](https://github.com/phpmyadmin/phpmyadmin/blob/master/CONTRIBUTING.md) document.
- [x] Make sure you are making a pull request against the correct branch. For example, for bug fixes in a released version use the corresponding QA branch and for new features use the _master_ branch. If you have a doubt, you can ask as a comment in the bug report or on the mailing list.
- [x] Every commit has proper `Signed-off-by` line as described in our [DCO](https://github.com/phpmyadmin/phpmyadmin/blob/master/DCO). This ensures that the work you're submitting is your own creation.
- [x] Every commit has a descriptive commit message.
- [x] Every commit is needed on its own, if you have just minor fixes to previous commits, you can squash them.
- [x] Any new functionality is covered by tests.

2019-03-20 15:40 UTC, MrThanlon commented
@ibennetch

2019-04-04 21:19 UTC, williamdes requested changes

2019-04-04 21:19 UTC, williamdes commented on js/navigation.js
> +                $('#imgpmalogo')[0].style.display = '';
Can you use `hide` and `show` from jquery ?

2019-04-04 21:19 UTC, williamdes commented on js/navigation.js
> +                    '<img src="./themes/pmahomme/img/logo_left.png" alt="phpMyAdmin" id="imgpmalogo">' +
I am not sure that `./themes/pmahomme/img/logo_left.png` is very multi theme friendly
What do you think @mauriciofauth ?

2019-04-04 21:19 UTC, williamdes commented on js/navigation.js
> +    /**
You can remove the comment

2019-04-04 21:21 UTC, williamdes commented
Can you please use your real name instead of `MrThanlon` in `Signed-off-by: MrThanlon <1@ch34k.tk>` line for legal reasons ?

2019-05-05 01:26 UTC, mauriciofauth commented on js/navigation.js
> +                    '<img src="./themes/pmahomme/img/logo_left.png" alt="phpMyAdmin" id="imgpmalogo">' +
You are correct @williamdes, this only works with the _pmahomme_ theme.

2019-05-05 01:42 UTC, ibennetch commented
As I just commented in the issue this refers to, I'd prefer not to implement this change.

2019-08-07 02:09 UTC, closed without merging