updated documentation #15041
phpmyadmin/phpmyadmin pull request #15124
Opened 2019-03-29 15:18 UTC by ravgeetdhillon

### Description

I have added the updated documentation for Navigation Logo Link's configuration in the section: Navigational Panel Setup.

Fixes #15041 

Before submitting pull request, please review the following checklist:

- [ ] Make sure you have read our [CONTRIBUTING.md](https://github.com/phpmyadmin/phpmyadmin/blob/master/CONTRIBUTING.md) document.
- [ ] Make sure you are making a pull request against the correct branch. For example, for bug fixes in a released version use the corresponding QA branch and for new features use the _master_ branch. If you have a doubt, you can ask as a comment in the bug report or on the mailing list.
- [ ] Every commit has proper `Signed-off-by` line as described in our [DCO](https://github.com/phpmyadmin/phpmyadmin/blob/master/DCO). This ensures that the work you're submitting is your own creation.
- [ ] Every commit has a descriptive commit message.
- [ ] Every commit is needed on its own, if you have just minor fixes to previous commits, you can squash them.
- [ ] Any new functionality is covered by tests.

2019-03-29 16:56 UTC, williamdes approved these changes

2019-04-13 22:41 UTC, ibennetch commented on doc/config.rst
> +    For relative/internal URLs, you need to have leading ``./`` or trailing characters ``?``.
This is pretty good, but I think I'd change this line a bit:

> leading \`\`./\`\` and trailing \`\`?\`\`, such as \`\`./sql.php?\`\`.

Does that sound reasonable?

2019-04-13 22:50 UTC, ibennetch requested changes

2019-04-13 22:50 UTC, ibennetch commented on doc/config.rst
> +    For relative/internal URLs, you need to have leading ``./`` or trailing characters ``?``.
This is pretty good, but I think I'd change this line a bit:

> leading \`\`./\`\` and trailing \`\`?\`\`, such as \`\`./sql.php?\`\`.

Does that sound reasonable?

2019-04-14 16:29 UTC, ravgeetdhillon commented on doc/config.rst
> +    For relative/internal URLs, you need to have leading ``./`` or trailing characters ``?``.
Yea. It would be better to give it as an example.

2019-04-14 17:41 UTC, williamdes approved these changes

2019-05-18 21:44 UTC, williamdes commented
@ravgeetdhillon Can you please post a comment with your [signoff](https://github.com/phpmyadmin/phpmyadmin/pull/15124/checks?check_run_id=101302646) line ?

2019-05-25 09:38 UTC, ravgeetdhillon commented
Signed-off-by: Ravgeet Dhillon <ravgeetdhillon@gmail.com>

2019-05-27 19:29 UTC, merged

2019-05-27 19:29 UTC, williamdes commented
Merged, thanks @ravgeetdhillon !