Fix #15064 - Export SQL option hidden on sql query export results
phpmyadmin/phpmyadmin pull request #15121
Opened 2019-03-28 15:36 UTC by saurass

# Description 
Fixes #15064 - Export SQL option hidden on sql query export results.

* Shows export as SQL option for queries that do not involve use of table.
* In case of such queries the raw query (entered by user) will be exported as *.sql file.

# Approach
* To recognize this kind of query (which do not use any DB or table) we need a flag to be passed
In `libraries/classes/Display/Results.php` added `free_query` parameter.
* This adds `free_query` parameter to the export link.
* Now this parameter is passed in the check in `libraries/classes/Plugins/Export/ExportSql.php` this makes the SQL option visible for export for these type of queries.
* Now further we need to pass this parameter to `export.php`
* So made changes to `templates/display/export/hidden_inputs.twig` and added a hidden field as `free_query`
* At the moment none of the export plugins are designed to dump raw query (as entered by user), so made changes to that.
* made a function `exportRawQuery()` in `libraries/classes/Plugins/Export/ExportSql.php`
* Now for this part function to be executed, we define `$whatStrucOrData` to `free_query` in `export.php`
* This way we dump the raw queries in sql dump file.

# Result
* Video illustrating the progress https://drive.google.com/open?id=15zS1U24ids9TFOvCe9Shi6p7DIn25p2d

# Further works
* Now I have implemented the `exportRawQuery()` only in `ExportSql.php` plugin, we need to implement this function for all other export plugins.

# Contribution Checklist
- [x] Make sure you have read our [CONTRIBUTING.md](https://github.com/phpmyadmin/phpmyadmin/blob/master/CONTRIBUTING.md) document.
- [x] Make sure you are making a pull request against the correct branch. For example, for bug fixes in a released version use the corresponding QA branch and for new features use the _master_ branch. If you have a doubt, you can ask as a comment in the bug report or on the mailing list.
- [x] Every commit has proper `Signed-off-by` line as described in our [DCO](https://github.com/phpmyadmin/phpmyadmin/blob/master/DCO). This ensures that the work you're submitting is your own creation.
- [x] Every commit has a descriptive commit message.
- [x] Every commit is needed on its own, if you have just minor fixes to previous commits, you can squash them.
- [x] Any new functionality is covered by tests.

2019-03-28 15:37 UTC, saurass commented
@williamdes @ibennetch please review and suggest changes : )

2019-04-08 04:30 UTC, saurass commented
@williamdes @mauriciofauth 

I found that the SQL option isn't coming because it is not initialized from `libraries/classes/Plugins/Export/ExportSql.php` on line 72 to 79

## Reason
* When we are calling to export any table, we are sending `single_table` as parameter (boolean).
* In case we export a table we are setting it to true.
* But in case of join queries or independent union queries (as in the issue mentioned by William) we do not send single_table and it is set to false and thus SQL option is not initialized.

## Possible Solutions
* Solution could be that when we enter a query that doesn't involve any table, we can pass a new param like `free_query` and add this to enable the SQL option and the user can further download the SQL file for it.

## Work So far
I have made following progress till now-
* Initializing a `free_query` parameter in case queries do not require any table or database.
* Use this to show the SQL option while exporting.
* Again this is used to export the raw query
* Fixed any problem with mime_type, (already working)
* When exporting such queries, the default file name will be like `export.extension`

Video illustrating progress https://drive.google.com/open?id=1oQeBUCpXLGWxIbZI_zP2BH9G-W3sM7RG

Please lemme know if I am going in the right direction.

Thank You : )

2019-04-08 04:31 UTC, saurass commented
Now I am working on removing DB and Table comments in the file that are exported. Will update soon : )

2019-04-10 07:43 UTC, williamdes commented
@sudo-bot Deploy pr

2019-04-10 08:27 UTC, saurass commented
I have just made few more changes @williamdes . Please review this and try to deploy.
Hope this goes well : )

2019-04-10 10:37 UTC, williamdes commented
@sudo-bot Deploy pr

@saurass you have Deploy access, so you can ask the bot to do so :)

2019-04-10 10:54 UTC, saurass commented
Okay that sounds cool : )

2019-04-10 11:00 UTC, saurass commented
@sudo-bot Deploy pr

2019-04-10 11:56 UTC, saurass commented
@williamdes , The bot seems to be unhappy, any idea what's going wrong?

2019-04-10 12:12 UTC, williamdes commented
@saurass I am fixing the infrastructure, I have memory issues with `composer install`
I will re trigger a build when fixed ;)

2019-04-10 12:51 UTC, saurass commented
updates...

## Approach
#### After clicking GO to execute query
* `import.php` is called which contains `Export` link
![tempsnip](https://user-images.githubusercontent.com/31488093/55878045-3eab4580-5bb9-11e9-80ea-4e14980d750a.png)
* This link must contain a parameter to identify that the query doesn't require use of table or database. This parameter will be passed to `tbl_export.php`
* So in `libraries/classes/Display/Results.php` initialize new parameter `raw_query` in case no table is selected. (see line 4964)
* This will give us a parameter `raw_query` when `tbl_export.php` is called (Export is clicked)

#### After export in called (when opening `tbl_export.php`)
* We use the above initialized parameter `raw_query` to show the SQL option
* So in `libraries/classes/ExportSql.php` we use the parameter `raw_query` to unhide the SQL option. (See line 81)
* In `tbl_export.php` we initialize `$export_type` and set it to "raw" if `raw_query` parameter is passed. (see line 138)
* Now we are able to see SQL option as shown below -
![Capture](https://user-images.githubusercontent.com/31488093/55878528-415a6a80-5bba-11e9-9aa2-ab285d191808.PNG)

#### After we click GO to export in SQL format. (`export.php` will be called)
* We need to export the raw query as the user inputs.
* So, we set `$err_url` as `server_sql.php` in case any error occurs, redirect to this page. (see line 289 `export.php`)
* In `export.php` we call `Export::exportRaw()` in case the `$export_type == 'raw'` (see line 477)
* Now we make static function `exportRaw()` in `libraries/classes/Export.php`. (see line 796)
* This function further calls `exportRawQuery()` function of export plugin (here `ExportSql` plugin) [This function has to be implemented in all types of export plugins]
* Now in `libraries/classes/Plugins/Export/ExportSql.php` we define function `exportRawQuery()` (see line 1969)


This downloads a file names `localhost.sql`

2019-04-10 15:35 UTC, saurass commented
@williamdes I think this PR will work well while exporting SQL queries.

2019-04-10 16:34 UTC, saurass commented
This should also work well with JSON export now.

2019-04-10 17:15 UTC, saurass commented
@sudo-bot Deploy pr

2019-04-11 08:47 UTC, saurass commented
Export CSV now working. : )

2019-04-11 09:08 UTC, williamdes requested changes

2019-04-11 09:08 UTC, williamdes commented on libraries/classes/Export.php
> +     * @param $whatStrucOrData
please add parameter types :)
eg: `@param string $parameter`

2019-04-11 09:10 UTC, saurass commented on libraries/classes/Export.php
> +     * @param $whatStrucOrData
okay

2019-04-11 09:17 UTC, williamdes requested changes
The code looks okay, and works fine on deployed instance

2019-04-11 09:17 UTC, williamdes commented on libraries/classes/Plugins/Export/ExportJson.php
> +        return $this->exportData('','','', $err_url, $sql_query);
this line will never be reached

2019-04-11 09:17 UTC, williamdes commented on libraries/classes/Plugins/Export/ExportSql.php
> +        return $this->export->outputHandler($dump);
You can use `$sql_query` instead of `$dump`

2019-04-11 09:17 UTC, williamdes commented on libraries/classes/Plugins/Export/ExportSql.php
> +     *
missing parameter `$crlf`

2019-04-11 09:17 UTC, williamdes commented on tbl_export.php
> +if (isset($_REQUEST['raw_query'])) {
if possible use `_GET` or `_POST`

2019-04-11 09:24 UTC, saurass commented on libraries/classes/Plugins/Export/ExportJson.php
> +        return $this->exportData('','','', $err_url, $sql_query);
I forgot to remove the last line. It is not required. Removing : )

2019-04-11 09:25 UTC, saurass commented on libraries/classes/Plugins/Export/ExportSql.php
> +        return $this->export->outputHandler($dump);
Yeah cool.

2019-04-11 09:25 UTC, saurass commented on libraries/classes/Plugins/Export/ExportSql.php
> +     *
okay

2019-04-11 09:27 UTC, saurass commented on tbl_export.php
> +if (isset($_REQUEST['raw_query'])) {
$_POST can be used for sure, but not sure if it is used anywhere else in the code base.

2019-04-11 09:58 UTC, saurass commented
@sudo-bot Deploy pr

2019-04-11 12:19 UTC, williamdes approved these changes

2019-04-11 12:19 UTC, williamdes commented on export.php
> +if($export_type == 'raw') {
please add a space before `(`

2019-04-11 12:45 UTC, saurass commented on export.php
> +if($export_type == 'raw') {
Yeah sure

2019-04-12 12:36 UTC, saurass commented
I have updated few more plugins, they must work well.

I am working on that for `Codegen` `LaTeX` and `XML` . I may require help in these

2019-04-12 12:36 UTC, saurass commented
@sudo-bot Deploy pr

2019-04-15 23:44 UTC, MauricioFauth requested changes
Hi, @saurass. Thanks for your contribution.

You need to fix the phpstan error [1] and the phpcs errors [2].

- [1] https://travis-ci.org/phpmyadmin/phpmyadmin/jobs/519224641#L631
- [2] https://travis-ci.org/phpmyadmin/phpmyadmin/jobs/519224640#L641

2019-04-15 23:44 UTC, mauriciofauth commented on libraries/classes/Controllers/Server/SqlController.php
> +    public function index($query_to_show): string
We are using an array of request parameters in the actions of the controllers. Example:
https://github.com/phpmyadmin/phpmyadmin/blob/13ef404d1e0fddc4c8595992b0385d2cb830a9a3/libraries/classes/Controllers/BrowseForeignersController.php#L47-L51

2019-04-16 03:31 UTC, saurass commented on libraries/classes/Controllers/Server/SqlController.php
> +    public function index($query_to_show): string
Okay, I will pass it as an array. Thanks

2019-04-16 11:50 UTC, saurass commented
Travis-ci builds are failing any ideas why?

cc @williamdes @mauriciofauth

2019-04-16 17:12 UTC, saurass commented
@williamdes @mauriciofauth 
I have made changes to all the ExportPlugins except "CodeGen" of which I have no idea.
So, should we work with the codegen part , if yes please help me get that done.

Otherwise I think this PR should work well (is ready I guess). Please test this and lemme know any thing that bothers you or is not working well.

Thank You : )

2019-04-16 17:14 UTC, saurass commented
@sudo-bot /deploy

2019-04-16 17:47 UTC, saurass commented
@sudo-bot Deploy pr

2019-04-16 22:02 UTC, mauriciofauth commented
> Travis-ci isn't working any ideas why?

@saurass Can you rebase against `master` and squash your commits?

2019-04-17 06:44 UTC, saurass commented
> > Travis-ci isn't working any ideas why?
> 
> @saurass Can you rebase against `master` and squash your commits?

Thank you @mauriciofauth

2019-04-17 06:45 UTC, saurass commented
@sudo-bot Deploy pr

2019-04-17 20:01 UTC, MauricioFauth requested changes

2019-04-17 20:01 UTC, mauriciofauth commented on export.php
> +// TODO: It can be make dynamic, user may enter name of file.
Could you remove this TODO?

2019-04-18 05:10 UTC, saurass commented on tbl_export.php
> +if (isset($_REQUEST['raw_query'])) {
Okay, I will get this to POST

2019-04-18 05:12 UTC, saurass commented on export.php
> +// TODO: It can be make dynamic, user may enter name of file.
Ya sure, I will remove this.

2019-05-01 01:13 UTC, saurass commented
@mauriciofauth @williamdes please suggest further changes.

2019-06-30 20:27 UTC, williamdes commented
@saurass sorry for not reviewing, can you please fix the conflicts ?

2019-11-01 03:55 UTC, saurass commented
> @saurass sorry for not reviewing, can you please fix the conflicts ?

You mean the merge conflicts. Right?

2019-11-01 06:48 UTC, williamdes commented
> > @saurass sorry for not reviewing, can you please fix the conflicts ?
> 
> You mean the merge conflicts. Right?

Yes

2020-01-11 14:17 UTC, williamdes commented
@saurass I rebased and add types to your great work, thank your for your contribution !

2020-01-11 14:20 UTC, williamdes commented
@sudo-bot Deploy PR

2020-01-11 15:31 UTC, williamdes commented
@ibennetch and @mauriciofauth could I have your review on this old PR that should be merged a long time ago ?

2020-01-23 12:08 UTC, williamdes commented
CI should pass, testing in progress
Maybe I will add some test coverage before merging

2020-01-23 12:13 UTC, williamdes commented
Issues found:
- [ ] - Export as visible text, go back: could be better

2020-01-23 13:13 UTC, williamdes commented
@victorphoenix3 Could you help me review this PR please ?
cc @kartik1000

2020-01-24 16:29 UTC, williamdes commented
cc @boherm

2020-01-25 13:29 UTC, kartik1000 commented
Hey @williamdes, Is the code change made in  templates/display/export/option_header.twig done to inform the user that we are exporting a raw query. I didn't understand its use much. Can you explain?

2020-01-25 18:31 UTC, williamdes commented
> Hey @williamdes, Is the code change made in templates/display/export/option_header.twig done to inform the user that we are exporting a raw query. I didn't understand its use much. Can you explain?

Hey @kartik1000 
You are right, it is only to inform the user that we are exporting a raw query and not a db or a table.

2020-01-27 20:28 UTC, williamdes approved these changes

2020-01-27 20:28 UTC, merged

2020-01-27 20:30 UTC, williamdes commented
Thank you for your hard work and patience !
Merged :tada:

2020-01-28 04:06 UTC, saurass commented
> Thank you for your hard work and patience !
> Merged

Thanks a lot : )

2022-12-13 21:34 UTC, williamdes commented on libraries/classes/Plugins/Export/ExportSql.php
> +        return $this->export->outputHandler($sql_query);
This is a mistake, fixed by d258e4ed142ca69efd0f68e9018529cb11f9d2f9