Fixes #15136 Hex converter giving invalid result
phpmyadmin/phpmyadmin pull request #15147
Opened 2019-04-02 19:16 UTC by apoorvkhare07

Signed-off-by: apoorv <apoorvkhare007@gmail.com>

### Description
The HEX() function in mysql behaves differently for string and int input. 
Changing the value to int which is string currently fixes the issue.

Fixes #15136

Before submitting pull request, please review the following checklist:

- [x] Make sure you have read our [CONTRIBUTING.md](https://github.com/phpmyadmin/phpmyadmin/blob/master/CONTRIBUTING.md) document.
- [x] Make sure you are making a pull request against the correct branch. For example, for bug fixes in a released version use the corresponding QA branch and for new features use the _master_ branch. If you have a doubt, you can ask as a comment in the bug report or on the mailing list.
- [x] Every commit has proper `Signed-off-by` line as described in our [DCO](https://github.com/phpmyadmin/phpmyadmin/blob/master/DCO). This ensures that the work you're submitting is your own creation.
- [x] Every commit has a descriptive commit message.
- [x] Every commit is needed on its own, if you have just minor fixes to previous commits, you can squash them.
- [x] Any new functionality is covered by tests.

2019-04-02 19:35 UTC, kartik1000 commented
LGTM👍. What do you think @williamdes?

2019-04-02 21:18 UTC, AghaSaad04 commented
@kartik1000 , @apoorvkhare07  Actually, It does not work for some integers that are from 10 - 15, because these are Alphabets in Hex as the column is already in int, So you cannot save them in an int column and 0 will be stored for those numbers.

2019-04-02 23:32 UTC, apoorvkhare07 commented
@AghaSaad04 This works fine, the mysql query will now return the correct hex value for all values. The issue is we cannot store hex values in int field. 
I think which is not the purpose of this PR. 
@williamdes @kartik1000 what do you'll think ?

2019-04-03 08:46 UTC, AghaSaad04 commented
@apoorvkhare07 I am not saying your changes are wrong. They are actually perfect 👍. I am just saying that if we cannot save hex in int column. Then there's no need for that converter. Why don't we just remove that hex conversion for int? This is what I am thinking :)

2019-04-03 08:53 UTC, apoorvkhare07 commented
@AghaSaad04 No we need the converter to return correct values as we cannot save HEX values in int but we can save them in strings or other types.

2019-04-03 11:17 UTC, kartik1000 commented
@apoorvkhare07, Is it now working fine, for all the values or is it giving incorrect answers?

2020-01-12 11:00 UTC, williamdes requested changes
Thank you for contributing, unfortunately I can not merge the PR
Please have a look at the discussion on #15136

2020-01-12 11:00 UTC, closed without merging