refactored 2 files as of now
phpmyadmin/phpmyadmin pull request #15165
Opened 2019-04-08 17:56 UTC by Bournvita1998

### Description

#15163 
Refactored 2 JS files of Designer 

Fixes #

Before submitting pull request, please review the following checklist:

- [ ] Make sure you have read our [CONTRIBUTING.md](https://github.com/phpmyadmin/phpmyadmin/blob/master/CONTRIBUTING.md) document.
- [ ] Make sure you are making a pull request against the correct branch. For example, for bug fixes in a released version use the corresponding QA branch and for new features use the _master_ branch. If you have a doubt, you can ask as a comment in the bug report or on the mailing list.
- [ ] Every commit has proper `Signed-off-by` line as described in our [DCO](https://github.com/phpmyadmin/phpmyadmin/blob/master/DCO). This ensures that the work you're submitting is your own creation.
- [ ] Every commit has a descriptive commit message.
- [ ] Every commit is needed on its own, if you have just minor fixes to previous commits, you can squash them.
- [ ] Any new functionality is covered by tests.

2019-04-08 18:56 UTC, williamdes commented
@Bournvita1998 I see that you have made great improvements, can you fix https://travis-ci.org/phpmyadmin/phpmyadmin/jobs/517394475#L645 before I review the PR please ?

2019-04-08 20:31 UTC, MauricioFauth requested changes

2019-04-08 20:31 UTC, mauriciofauth commented on js/designer/database.js
> +    var designerDB = {}, datastore = null;
You should split `var` declarations into multiple statements.

2019-04-08 20:31 UTC, mauriciofauth commented on js/designer/history.js
> +        $("#eQuery").value = history_array[index].get_obj().getquery(); // get_obj(),get_query might be removed
Why replace `document.getElementById` with the jQuery ID selector?

2019-04-08 20:45 UTC, mauriciofauth commented
Hello. Thanks for your contribution!

We require a full name for legal compliance reasons. Could you use your full name in the signature tag?
For example: `Signed-off-by: Jane Developer <jane@example.org>`

See [Developer's Certificate of Origin](https://github.com/phpmyadmin/phpmyadmin/blob/master/DCO#L39)

2019-04-08 21:42 UTC, Bournvita1998 commented on js/designer/history.js
> +        $("#eQuery").value = history_array[index].get_obj().getquery(); // get_obj(),get_query might be removed
I was trying to convert some of the JS into jQuery while refactoring the code. Should I continue doing this in this PR itself or should I create a new one?

2019-04-08 21:43 UTC, Bournvita1998 commented on js/designer/database.js
> +    var designerDB = {}, datastore = null;
I remembered that we should not declare the variables in multiple lines as per good coding practices. But found that it wrong :(. Thus reverted the changes. Also due to the same reason its showing linting error (which I have removed rn, will be displayed in the new commit).

2019-04-08 21:50 UTC, mauriciofauth commented on js/designer/history.js
> +        $("#eQuery").value = history_array[index].get_obj().getquery(); // get_obj(),get_query might be removed
What I want to know is, for example in the `#eQuery` case, what are the advantages in using jQuery instead of using plain JavaScript?

2019-04-08 21:54 UTC, Bournvita1998 commented on js/designer/history.js
> +        $("#eQuery").value = history_array[index].get_obj().getquery(); // get_obj(),get_query might be removed
Ohh!!, So do you want to compare JS vs jQuery. Right?

2019-04-08 22:14 UTC, Bournvita1998 commented on js/designer/history.js
> +        $("#eQuery").value = history_array[index].get_obj().getquery(); // get_obj(),get_query might be removed
@mauriciofauth I would like to suggest that if you hadn't looked my proposal on "Refactoring and Improving Designer" till now, please have a look at that you will definitely find the answer for "what are the advantages in using jQuery instead of using plain JavaScript?"

2019-04-09 11:19 UTC, Bournvita1998 commented on js/designer/history.js
> +        $("#eQuery").value = history_array[index].get_obj().getquery(); // get_obj(),get_query might be removed
@williamdes Here is the link to the proposal :p 
https://docs.google.com/document/d/16rg0DImKFuW_dwxGXbgncJQ0NjZuglXVkRF2rUPzrwA/edit?usp=sharing

2019-04-10 18:20 UTC, Bournvita1998 commented
@williamdes If everything is fine, should I go ahead with other changes?

2019-04-11 09:04 UTC, williamdes commented
@Bournvita1998 I would say yes, @mauriciofauth do you agree ?

2019-04-13 03:54 UTC, Bournvita1998 commented
@williamdes I am done with all the changes, please review.

2019-05-16 07:18 UTC, Bournvita1998 commented
@williamdes @mauriciofauth I am thinking of closing this PR and create new PRs in a step by step manner as mentioned in my proposal. Its because I will be working on the designer project this summer. Should I go ahead?
Also, can you please review my proposal and suggest any changes if required?
https://docs.google.com/document/d/16rg0DImKFuW_dwxGXbgncJQ0NjZuglXVkRF2rUPzrwA/edit?usp=sharing

2019-05-16 08:09 UTC, williamdes commented
@Bournvita1998 I agree, good proposal !

2019-05-28 20:36 UTC, closed without merging