[REFACTOR] Removed unused variables and added file description comments
phpmyadmin/phpmyadmin pull request #15173
Opened 2019-04-10 21:04 UTC by imdhruvgupta

Signed-off-by : Dhruv Gupta gdhruv167@gmail.com

### Description
Enhancement #15168

Before submitting pull request, please review the following checklist:

- [x] Make sure you have read our [CONTRIBUTING.md](https://github.com/phpmyadmin/phpmyadmin/blob/master/CONTRIBUTING.md) document.
- [x] Make sure you are making a pull request against the correct branch. For example, for bug fixes in a released version use the corresponding QA branch and for new features use the _master_ branch. If you have a doubt, you can ask as a comment in the bug report or on the mailing list.
- [x] Every commit has proper `Signed-off-by` line as described in our [DCO](https://github.com/phpmyadmin/phpmyadmin/blob/master/DCO). This ensures that the work you're submitting is your own creation.
- [x] Every commit has a descriptive commit message.
- [x] Every commit is needed on its own, if you have just minor fixes to previous commits, you can squash them.
- [x] Any new functionality is covered by tests.

2019-04-12 18:22 UTC, williamdes approved these changes
LGTM

2019-04-16 22:30 UTC, MauricioFauth requested changes
Hi @imdhruvgupta. Thank you for your contribution.

Can you fix the lint errors?
See: https://travis-ci.org/phpmyadmin/phpmyadmin/jobs/518492286#L649

You can fix some errors by running:
```
yarn run js-lint --fix
```

2019-05-09 02:20 UTC, MauricioFauth approved these changes

2019-05-09 02:22 UTC, merged

2019-05-09 02:22 UTC, mauriciofauth commented
Merged, thanks for your contribution!