Fixes - #15205 - Useless backquotes, sql preview, delete index
phpmyadmin/phpmyadmin pull request #15207
Opened 2019-04-16 08:40 UTC by saurass

Signed-off-by: Saurabh Srivastava <saurabhsrivastava312@gmail.com>

### Description
Fixes #15205 

## Problem
* Pretty SQL not showing because we were using simple `PMA_confirm`
* The SQL query had backquotes because when sanitizing the query (line 754 `libraries/classes/Index.php`) we weren't passing `add_backquotes` to `false`.

## Solution
* Introduced a new function to `functions.js` --> `PMA_confirmPreviewSQL(....)`.
* Calling this function to show pretty SQL query in `indexes.js` line 602.
* Passing `add_backquotes` parameter as `false` (line 754 `libraries/classes/Index.php`) in function call - `Sanitize::jsFormat(....)`

This seems to fix our issue.

## Contribution Checklist
- [x] Make sure you have read our [CONTRIBUTING.md](https://github.com/phpmyadmin/phpmyadmin/blob/master/CONTRIBUTING.md) document.
- [x] Make sure you are making a pull request against the correct branch. For example, for bug fixes in a released version use the corresponding QA branch and for new features use the _master_ branch. If you have a doubt, you can ask as a comment in the bug report or on the mailing list.
- [x] Every commit has proper `Signed-off-by` line as described in our [DCO](https://github.com/phpmyadmin/phpmyadmin/blob/master/DCO). This ensures that the work you're submitting is your own creation.
- [x] Every commit has a descriptive commit message.
- [x] Every commit is needed on its own, if you have just minor fixes to previous commits, you can squash them.
- [x] Any new functionality is covered by tests.

2019-04-16 08:42 UTC, saurass commented
@sudo-bot Deploy pr

2019-04-25 22:26 UTC, williamdes approved these changes
LGTM

2019-04-25 22:26 UTC, williamdes commented on js/functions.js
> +    var button_options = {};
can you remove this line

2019-04-25 22:26 UTC, williamdes commented on js/functions.js
> +            'class': 'submitCancel',
why did you use quotes for this property ?

2019-04-26 10:39 UTC, saurass commented on js/functions.js
> +            'class': 'submitCancel',
Not exactly sure why I wrote it. May be just in a flow :sweat_smile:

I will remove this

2019-04-26 10:39 UTC, saurass commented on js/functions.js
> +    var button_options = {};
Remove all these 4 lines ?

2019-04-26 10:47 UTC, saurass commented on js/functions.js
> +    var button_options = {};
I don't think line 2423 should be removed. It is important to make sure that `button_options` variable is empty before use.

About the line above that (2420-2423), these are to generate the SQL preview div.

2019-04-28 12:08 UTC, williamdes commented on js/functions.js
> +    var button_options = {};
@saurass only `2423`  `var button_options = {};` is useless since `var button_options = [` declares another time the variable

2019-04-28 12:10 UTC, saurass commented on js/functions.js
> +    var button_options = {};
Yeah okay, sure it can be removed .

2019-04-28 12:11 UTC, williamdes requested changes
Works fine for delete primary key but not for and index
Can you please have a look @saurass ?
![Delete index screenshot](https://user-images.githubusercontent.com/7784660/56864159-6f63eb00-69bf-11e9-9876-4dc411b18c2f.png)
![Delete PK screenshot](https://user-images.githubusercontent.com/7784660/56864172-8b678c80-69bf-11e9-8951-7d2cb976b24f.png)

2019-04-28 12:12 UTC, saurass commented
> Works fine for delete primary key but not for and index
> Can you please have a look @saurass ?
 Yeah sure, I will try to fix this.

2019-04-28 12:21 UTC, saurass commented
@sudo-bot Deploy pr

2019-04-28 12:23 UTC, saurass commented
I missed removing backquotes in `libraries/classes/Index.php` for `INDEX` keys. 

Should work well now @williamdes

2019-04-28 18:13 UTC, williamdes approved these changes
Merged, great work on this issue @saurass !

2019-04-28 18:20 UTC, merged

2019-04-28 22:51 UTC, saurass commented
Thank you @williamdes