Remove exit from code
phpmyadmin/phpmyadmin pull request #15248
Opened 2019-05-05 12:57 UTC by williamdes

### Description

I have no idea is this is a good enhancement but i wanted to remove as much 'exit;' to be able to mock the response function in order to test code and be able to remove some if TESTSUITE from codebase

2019-05-05 12:58 UTC, williamdes commented
Hi @mauriciofauth I hope this is a good idea, can you please review ?

2019-05-08 15:29 UTC, MauricioFauth approved these changes

2019-05-08 15:32 UTC, mauriciofauth commented
I want to improve how we handle request and response in the future. Using a library that implements [PSR-7](https://www.php-fig.org/psr/psr-7/) or other HTTP library.

2019-05-09 22:42 UTC, mauriciofauth commented
There is a lot of errors on Browserstack.

2020-05-15 21:32 UTC, williamdes commented
A very much smaller change but if it passes and you approve @mauriciofauth that will be a small but good step to remove the 80+ exits in our code base

2020-05-19 21:06 UTC, MauricioFauth requested changes

2020-05-19 21:06 UTC, mauriciofauth commented on libraries/classes/Controllers/Database/StructureController.php
> +                        return;
You also have to add a return after the `$this->multiSubmitAction();` call in the `index` method.

2020-05-19 21:10 UTC, mauriciofauth commented on libraries/classes/Controllers/Database/StructureController.php
> +                        return;
This is not correct. :disappointed: 
Removing these exits will change the code flow. The best way to remove them is to extract each action into a dedicated route.

2020-05-19 21:15 UTC, williamdes commented on libraries/classes/Controllers/Database/StructureController.php
> +                        return;
I see, that will take me more time :)
I will have a try when possible

2020-05-19 22:04 UTC, mauriciofauth commented on libraries/classes/Controllers/Database/StructureController.php
> +                        return;
I've been extracting these `mult_submit` actions recently. They are confusing and difficult to read.

The other changes are good changes. :+1:

2020-07-21 21:49 UTC, merged