External dependency injection system
phpmyadmin/phpmyadmin pull request #15266
Opened 2019-05-11 21:23 UTC by Tithugues

### Description

What do you think about this kind of DI system please?

The current system seems to be restrictive: the definition of services should be done in PHP (which doesn't seem very readable for me), also the parameters can't be defined at the beginning (only when getting the object).

With this system, we defined the template class and it can be passed everywhere quite easily, and this may be done for other classes. Also in a second step, this would enforce the principle to use injection instead of building objects in other objects. (I would love to split the current `Response` class in `HtmlResponse` and `AjaxResponse` classes with a common `ResponseInterface`.)

Fixes #

Before submitting pull request, please review the following checklist:

- [x] Make sure you have read our [CONTRIBUTING.md](https://github.com/phpmyadmin/phpmyadmin/blob/master/CONTRIBUTING.md) document.
- [x] Make sure you are making a pull request against the correct branch. For example, for bug fixes in a released version use the corresponding QA branch and for new features use the _master_ branch. If you have a doubt, you can ask as a comment in the bug report or on the mailing list.
- [ ] Every commit has proper `Signed-off-by` line as described in our [DCO](https://github.com/phpmyadmin/phpmyadmin/blob/master/DCO). This ensures that the work you're submitting is your own creation.
- [ ] Every commit has a descriptive commit message.
- [ ] Every commit is needed on its own, if you have just minor fixes to previous commits, you can squash them.
- [ ] Any new functionality is covered by tests.

2019-05-11 21:50 UTC, MauricioFauth approved these changes

2019-05-11 21:56 UTC, mauriciofauth commented
> I would love to split the current `Response` class in `HtmlResponse` and `AjaxResponse` classes with a common `ResponseInterface`.

Great idea. As I said in https://github.com/phpmyadmin/phpmyadmin/pull/15248#issuecomment-490535168, I also want to improve how we handle request and response with a HTTP library.

2019-05-12 13:05 UTC, Tithugues commented
If you find any bug to fix or any code to improve, please tell me, I'll do my best to do it.

2019-05-12 19:49 UTC, Tithugues commented
Hi,
Do you please know how to get rid of the errors thrown in https://travis-ci.org/phpmyadmin/phpmyadmin/jobs/531442853 ?

`Undefined variable: $containerBuilder`

This variable is defined in `common.inc.php` which is called at the beginning of all files which have the error. :confused: 

Thank you.

2019-05-14 15:40 UTC, mauriciofauth commented
> This variable is defined in common.inc.php which is called at the beginning of all files which have the error. :confused:

The static analyzer doesn't know about variables defined in another files. We have been ignoring these errors.

https://github.com/phpmyadmin/phpmyadmin/blob/720e302de5c1ad5db1fb1cbcad3eaaec948ca465/phpstan.neon.dist#L18

2019-05-14 15:53 UTC, mauriciofauth commented
Some ways to solve this would be to get the variable some other way, or if it is a global variable, declare it in the file.

2019-05-14 18:37 UTC, Tithugues commented
> Some ways to solve this would be to get the variable some other way, or if it is a global variable, declare it in the file.

Yes, I know this is done for other variables. But doing this would encourage use of the container through the global variable in many places, whereas the idea would rather be to provide the data as an input.
So if this is OK for you, I would prefer to fill the `phpstan.neon.dist` file.

2019-05-14 18:40 UTC, mauriciofauth commented
> So if this is OK for you, I would prefer to fill the `phpstan.neon.dist` file.

No problem.

2019-05-14 20:21 UTC, Tithugues commented
Please don't merge it for now, I've an error after the creation of a table.

2019-05-14 20:34 UTC, Tithugues commented
> Please don't merge it for now, I've an error after the creation of a table.

Please ignore my previous message, it was on the other PR I'm working on.

2019-05-14 21:43 UTC, mauriciofauth commented on ajax.php
> +$controller = $containerBuilder->get('ajax_controller');
What do you think about using `AjaxController::class` instead of `'ajax_controller'`?

2019-05-17 20:14 UTC, Tithugues commented on ajax.php
> +$controller = $containerBuilder->get('ajax_controller');
This is OK for me. I'll rename the controller services with the class name of the controllers.

2019-05-18 09:56 UTC, williamdes requested changes
Good work!

2019-05-18 09:56 UTC, williamdes commented on db_events.php
> +$definition->setArguments(array_merge($definition->getArguments(), $dependency_definitions));
Is it possible to avoid having array merges?

2019-05-18 09:56 UTC, williamdes commented on db_multi_table_query.php
> +$definition = $containerBuilder->getDefinition('PhpMyAdmin\Controllers\Database\MultiTableQueryController');
Can you use ::class ?

2019-05-18 12:33 UTC, Tithugues commented on db_events.php
> +$definition->setArguments(array_merge($definition->getArguments(), $dependency_definitions));
2 things please:
1/ thank you because I wanted to replace it
2/ what would be your reason to avoid `array_merge` please?

2019-05-18 12:33 UTC, Tithugues commented on db_multi_table_query.php
> +$definition = $containerBuilder->getDefinition('PhpMyAdmin\Controllers\Database\MultiTableQueryController');
Oups… Missed this one…

2019-05-18 13:13 UTC, williamdes commented on db_events.php
> +$definition->setArguments(array_merge($definition->getArguments(), $dependency_definitions));
It feels strange, kind of broken
I would love to see a `->setArgument('name', $value);`
And also if you invert or do a mistake in the order of an array merge the output will not be what you expected.

2019-05-18 14:27 UTC, Tithugues commented on db_events.php
> +$definition->setArguments(array_merge($definition->getArguments(), $dependency_definitions));
OK, thanks for feedback. It should be OK now.

2019-05-18 14:30 UTC, williamdes commented on db_central_columns.php
> +$definition->setArguments(array_merge($definition->getArguments(), $dependency_definitions));
@Tithugues Can you remove `array_merge` and all the other occurrences ?

2019-05-18 14:31 UTC, Tithugues commented on db_central_columns.php
> +$definition->setArguments(array_merge($definition->getArguments(), $dependency_definitions));
Yes, I'm going to try.

2019-05-18 14:32 UTC, williamdes requested changes

2019-05-18 14:32 UTC, williamdes commented on db_central_columns.php
> +$definition = $containerBuilder->getDefinition('database_central_columns_controller');
missing `::class` :)

2019-05-18 14:32 UTC, williamdes commented on db_central_columns.php
> +$controller = $containerBuilder->get('database_central_columns_controller');
here also

2019-05-18 14:32 UTC, williamdes commented on server_databases.php
> +$response = $containerBuilder->get('response', ContainerInterface::NULL_ON_INVALID_REFERENCE) ?? Response::getInstance();
Can you use `::class` ?

2019-05-18 16:17 UTC, MauricioFauth approved these changes
Excellent work!

2019-05-18 16:19 UTC, mauriciofauth commented
@Tithugues Do you think it's now possible to remove our custom DIC (`PhpMyAdmin\Di\Container`)?

2019-05-18 19:09 UTC, Tithugues commented on server_databases.php
> +$response = $containerBuilder->get('response', ContainerInterface::NULL_ON_INVALID_REFERENCE) ?? Response::getInstance();
As I defined `response` as a service in the other PR, I would like to do it in the other one if this is OK for you.

2019-05-18 19:12 UTC, Tithugues commented on db_central_columns.php
> +$controller = $containerBuilder->get('database_central_columns_controller');
Done.

2019-05-18 19:12 UTC, Tithugues commented on db_central_columns.php
> +$definition = $containerBuilder->getDefinition('database_central_columns_controller');
Done.

2019-05-18 19:22 UTC, Tithugues commented
> @Tithugues Do you think it's now possible to remove our custom DIC (`PhpMyAdmin\Di\Container`)?

Not yet. But I should confess this is one on my aims…
I think we should go further before this. Your current `Container` has one advantage that I would like not to implement with the current one: `getInstance`. Thanks to this, you can retrieve every service everywhere. But if we achieve to inject dependencies instead of creating objects, we should be able to remove the current `container`, I think.
(This is a bit confusing because I think that I'm currently doing 2 things at the same time: defining the services externally thanks to the Symfony DI + injecting dependencies.)
The first things I'm currently trying to get rid of the current `container` are:
* registering every old services as a service with the new `container`;
* replacing as much as possible the `get` of services by a `get` through the new `container`.

When all the `get` will be replaced, it won't be fully finished, because there is also some magic in your `container` that loads the parameters regarding name and/or type (don't really remember, I had a quick look) of registered services.

2019-05-18 20:20 UTC, Tithugues commented on db_central_columns.php
> +$definition->setArguments(array_merge($definition->getArguments(), $dependency_definitions));
This is done!
As there is no `replaceArguments`, I had to do it for each parameter.

Later, I think that we'll have to find a way not to duplicate this closure.

2019-05-18 20:56 UTC, williamdes commented on db_central_columns.php
> +$definition->setArguments(array_merge($definition->getArguments(), $dependency_definitions));
@Tithugues Seems like you did not push on the right branch :)

2019-05-18 22:47 UTC, Tithugues commented on db_central_columns.php
> +$definition->setArguments(array_merge($definition->getArguments(), $dependency_definitions));
Seems you're right… :sob:

2019-05-18 22:59 UTC, williamdes commented on db_datadict.php
> +$definition->setArguments(array_merge($definition->getArguments(), $dependency_definitions));
You missed this one :)

2019-05-18 23:12 UTC, Tithugues commented on db_datadict.php
> +$definition->setArguments(array_merge($definition->getArguments(), $dependency_definitions));
Thanks. It should be OK this time…

2019-05-18 23:16 UTC, williamdes approved these changes
:100:

2019-05-18 23:25 UTC, Tithugues commented
Do you want me to squash the commits before merging the branch?

2019-05-18 23:45 UTC, mauriciofauth commented
You can do it, if you want.

2019-05-18 23:55 UTC, Tithugues commented
Done.

2019-05-18 23:58 UTC, MauricioFauth approved these changes

2019-05-19 03:59 UTC, mauriciofauth commented
There are a few Selenium errors. You can open the link in the log to see the video of the test. 

https://travis-ci.org/phpmyadmin/phpmyadmin/jobs/534311833#L494

2019-05-19 13:40 UTC, Tithugues commented
> There are a few Selenium errors. You can open the link in the log to see the video of the test.
> 
> https://travis-ci.org/phpmyadmin/phpmyadmin/jobs/534311833#L494

Thanks, I did some fixes. I'll wait for Selenium feedback.

2019-05-19 14:55 UTC, merged

2019-05-19 14:56 UTC, mauriciofauth commented
Excellent work! Thank you for your contribution.