Get rid of old container
phpmyadmin/phpmyadmin pull request #15279
Opened 2019-05-19 20:54 UTC by Tithugues

### Description

Try to get rid of PhpMyAdmin\DI and replace it by Symfony DI.
Some tasks are needed, like giving all needed objects to every scripts / classes (instead of getting instance of container) and use `db`, `table`, … as DI parameters instead of updating the definition.

Fixes #

Before submitting pull request, please review the following checklist:

- [ ] Make sure you have read our [CONTRIBUTING.md](https://github.com/phpmyadmin/phpmyadmin/blob/master/CONTRIBUTING.md) document.
- [ ] Make sure you are making a pull request against the correct branch. For example, for bug fixes in a released version use the corresponding QA branch and for new features use the _master_ branch. If you have a doubt, you can ask as a comment in the bug report or on the mailing list.
- [ ] Every commit has proper `Signed-off-by` line as described in our [DCO](https://github.com/phpmyadmin/phpmyadmin/blob/master/DCO). This ensures that the work you're submitting is your own creation.
- [ ] Every commit has a descriptive commit message.
- [ ] Every commit is needed on its own, if you have just minor fixes to previous commits, you can squash them.
- [ ] Any new functionality is covered by tests.

2019-05-19 20:56 UTC, Tithugues commented
@mauriciofauth , you asked if we'll be able to remove existing DI. "Winter is coming." I mean… "Removal is coming."
(There are a lot of commits here because there are also the commits of the other PR.)

2019-06-08 17:13 UTC, MauricioFauth requested changes

2019-06-08 17:13 UTC, mauriciofauth commented on libraries/classes/Di/Migration.php
> +     * @param        $value
You need to follow the format `@param type $name Description` here.

2019-06-08 17:13 UTC, mauriciofauth commented on libraries/classes/Di/Migration.php
> +    public static function getInstance(?ContainerBuilder $containerBuilder = null): self
You need to add the PHPDoc for this method.

2019-06-08 17:13 UTC, mauriciofauth commented on libraries/classes/Di/Migration.php
> +    public function __construct(ContainerBuilder $containerBuilder)
You need to add the PHPDoc for the constructor.

2019-06-08 17:13 UTC, mauriciofauth commented on db_central_columns.php
> -global $db;
Removing `global $db;` will cause PHPStan to fail.

2019-06-08 17:13 UTC, mauriciofauth commented on db_events.php
> -global $db, $table;
Removing `global $db, $table;` will cause PHPStan to fail.

2019-06-08 17:13 UTC, mauriciofauth commented on db_routines.php
> -global $db, $table;
Removing `global $db, $table;` will cause PHPStan to fail.

2019-06-08 17:13 UTC, mauriciofauth commented on db_triggers.php
> -global $db, $table;
Removing `global $db, $table;` will cause PHPStan to fail.

2019-06-08 17:13 UTC, mauriciofauth commented on tbl_addfield.php
> -global $cfg, $db, $table;
Removing `global $cfg, $db, $table;` will cause PHPStan to fail.

2019-06-08 17:13 UTC, mauriciofauth commented on tbl_create.php
> -global $cfg, $db, $table;
Removing `global $cfg, $db, $table;` will cause PHPStan to fail.

2019-06-08 17:13 UTC, mauriciofauth commented on tbl_find_replace.php
> -global $url_query;
Removing `global $url_query;` will cause PHPStan to fail.

2019-06-14 16:38 UTC, mauriciofauth commented on libraries/classes/Di/Migration.php
> +    public static function getInstance(?ContainerBuilder $containerBuilder = null): self
This will cause phpcs to fail.

2019-06-14 16:38 UTC, mauriciofauth commented on libraries/classes/Di/Migration.php
> +    public function __construct(ContainerBuilder $containerBuilder)
This will cause phpcs to fail.

2019-06-14 16:38 UTC, mauriciofauth commented on libraries/classes/Di/Migration.php
> +     * @param        $value
This will cause phpcs and phpstan to fail.

2019-06-14 16:44 UTC, mauriciofauth commented
Hi, @Tithugues, thank you for your work on this pull request.

How much do you think it takes before we can remove our custom container?
We are wanting to feature freeze the version 5.0 and we would like to include this pull request.

2019-06-15 19:36 UTC, Tithugues commented
@mauriciofauth ,
Good question… I don't really know how long it could be. Maybe 2-3 weeks. I hope not longer.
When do you expect to create the QA_5_0 branch please?

2019-06-15 22:52 UTC, MauricioFauth approved these changes

2019-06-15 22:58 UTC, merged

2019-06-15 23:04 UTC, mauriciofauth commented
Hi, @Tithugues,

I merged this pull request to include this changes in 5.0. We are planning to release 5.0.0-alpha soon, so the remaining changes may not be included.
You can open a new pull request with the remaining changes.

Thank you for your contribution.

2019-06-16 01:25 UTC, ibennetch commented
I think we are waiting on this to release 5.0.0-alpha. I’m willing to wait
about two weeks, so long as no one else objects. I think that is worth it
to get this in to 5.0.

2019-06-16 01:30 UTC, mauriciofauth commented
I open #15335 to help with the removal of the container.