first commit
phpmyadmin/phpmyadmin pull request #15298
Opened 2019-06-01 09:24 UTC by murex971

### Description
implementation of Bootstrap

2019-06-01 12:51 UTC, shucon commented
Please try to use better commit message and sign-off each commit.

2019-06-01 12:53 UTC, shucon requested changes

2019-06-01 12:53 UTC, shucon commented on templates/home/index.twig
> +</div></div></div>
Proper indentation of closing tags, and each tag in new line is required.

2019-06-01 12:53 UTC, shucon commented on templates/login/header.twig
> +<div class="col-12">
Closing tags for them are not present.

2019-06-01 17:53 UTC, MauricioFauth reviewed
Nice work!

You should try to keep the style of the themes (pmahomme, Metro and Original) as same as possible.
For example, the login page is looking different:
![Screenshot from 2019-06-01 14-50-38](https://user-images.githubusercontent.com/120970/58751955-e12acb00-847c-11e9-9b8a-eae24ac914ad.png)

2019-06-01 17:55 UTC, MauricioFauth requested changes
Also, don't forget to add your signature tag in the commit messages with `git commit -s`.

2019-06-02 06:09 UTC, murex971 commented
> Nice work!
> 
> You should try to keep the style of the themes (pmahomme, Metro and Original) as same as possible.
> For example, the login page is looking different:
> ![Screenshot from 2019-06-01 14-50-38](https://user-images.githubusercontent.com/120970/58751955-e12acb00-847c-11e9-9b8a-eae24ac914ad.png)

I will be working on forms particularly once I am done with the grids part.

2019-06-06 20:35 UTC, mauriciofauth commented
Closed in favor of #15302

2019-06-06 20:35 UTC, closed without merging