history.js - improving performance
phpmyadmin/phpmyadmin pull request #15300
Opened 2019-06-03 10:01 UTC by Bournvita1998

Signed-off-by: Bournvita1998 <mohit.kuri@research.iiit.ac.in>

### Description

Improved some performance factors present in history.js

Fixes #

Before submitting the pull request, please review the following checklist:

- [ ] Make sure you have read our [CONTRIBUTING.md](https://github.com/phpmyadmin/phpmyadmin/blob/master/CONTRIBUTING.md) document.
- [ ] Make sure you are making a pull request against the correct branch. For example, for bug fixes in a released version use the corresponding QA branch and for new features use the _master_ branch. If you have a doubt, you can ask as a comment in the bug report or on the mailing list.
- [ ] Every commit has proper `Signed-off-by` line as described in our [DCO](https://github.com/phpmyadmin/phpmyadmin/blob/master/DCO). This ensures that the work you're submitting is your own creation.
- [ ] Every commit has a descriptive commit message.
- [ ] Every commit is needed on its own, if you have just minor fixes to previous commits, you can squash them.
- [ ] Any new functionality is covered by tests.

2019-06-03 10:15 UTC, Bournvita1998 commented
@mauriciofauth @williamdes
Improved some performance factors in histroy.js, Should I commit further updates in history.js over here only or should I create a new PR?

cc- @ibennetch

2019-06-03 16:14 UTC, Bournvita1998 commented
@williamdes you can refer [this](https://github.com/phpmyadmin/phpmyadmin/issues/15163) for the previous discussion.

2019-06-03 16:29 UTC, MauricioFauth requested changes
You should resolve the conflicts before we can merge your changes.

2019-06-03 16:33 UTC, mauriciofauth commented
Can you change your signature tag to use your full name?
We require a full name for legal compliance reasons.

For example: `Signed-off-by: Jane Smith <jane.smith@example.org>`

See [Developer's Certificate of Origin](https://github.com/phpmyadmin/phpmyadmin/blob/master/DCO#L39)

2019-06-03 16:33 UTC, williamdes approved these changes
LGTM @Bournvita1998

2019-06-04 06:44 UTC, Bournvita1998 commented
> You should resolve the conflicts before we can merge your changes.

I couldn't figure out what's the exact conflict. Can you please help me here?

2019-06-05 03:17 UTC, MauricioFauth requested changes
You should fix the ESLint error.
See: https://travis-ci.org/phpmyadmin/phpmyadmin/jobs/541106844#L402

You can run ESLint with:
```
node_modules/.bin/eslint js/designer/history.js
```

2019-06-05 06:23 UTC, Bournvita1998 commented
@mauriciofauth fixed...

2019-06-05 12:30 UTC, Bournvita1998 commented
@mauriciofauth Can you please review this?
And if everything is good... should I go ahead and create a new PR "Refactoring in history.js" or should I commit those changes here in the same PR?

2019-06-06 12:17 UTC, shucon requested changes

2019-06-06 12:17 UTC, shucon commented on js/designer/history.js
> +    var history_array_length = history_array.length;
Use Camel Case instead of underscores to name variables.

2019-06-06 12:17 UTC, shucon commented on js/designer/history.js
> +        temp = history_array[i].get_tab(); // + '.' + history_array[i].get_obj_no(); for Self JOIN
Don't change the variable names of existing variables.

2019-06-06 12:18 UTC, shucon commented
@Bournvita1998 have you even tested this PR? This code won't even work.
@williamdes @mauriciofauth please don't merge the code yet.

2019-06-06 12:19 UTC, shucon commented on js/designer/history.js
> +    var history_array_length = history_array.length;
There's no variable named `history_array`

2019-06-07 07:57 UTC, MauricioFauth requested changes
There are still ESLint errors.

You can run ESLint with:
```
node_modules/.bin/eslint js
```
or
```
yarn run js-lint
```

2019-06-07 08:57 UTC, Bournvita1998 commented
@mauriciofauth @shucon I think while creating this PR I messed up at a lot of points(worked on different branch initially, while copying changes to the new branch got a lot of indentation issues, pulled the changes late, merge conflict, etc... ) which lead to soo many errors. I was thinking of creating a new PR, should I create one soon? I have already done work on that but now looking that how can I test that(posted the query in the mailing list regarding the same).

PS- I have considered your reviews while working this time.

2019-06-07 09:08 UTC, mauriciofauth commented
@Bournvita1998 The majority of issues is just name changes. For example, you are using `history_array` but that variable is now named `historyArray`.

2019-06-07 09:10 UTC, mauriciofauth commented
These conflicts were caused by some recent changes I made in the JavaScript files.

2019-06-07 09:12 UTC, Bournvita1998 commented
@mauriciofauth  ohh okay, So I guess it's okay if I resolve the issues to this PR only?

2019-06-07 09:13 UTC, mauriciofauth commented
You can keep working on this PR.

2019-06-07 11:10 UTC, Bournvita1998 commented
@mauriciofauth while resolving ESLint error, I got these 3 errors along with other 183 warnings. Should I rename the variables or leave them as it is?

![Selection_042](https://user-images.githubusercontent.com/26218090/59100172-e25b6c80-8942-11e9-9f32-90c5d6b0b2ab.png)

2019-06-07 19:15 UTC, MauricioFauth requested changes

2019-06-07 19:15 UTC, mauriciofauth commented on js/designer/history.js
> +function history_delete (index) {
You have to change the signature from:
```js
function history_delete (index) {
```
to:
```js
DesignerHistory.historyDelete = function (index) {
```

2019-06-07 19:15 UTC, mauriciofauth commented on js/designer/history.js
> +function found (arrayName, value) {
You have to change the signature from:
```js
function found (arrayName, value) {
```
to:
```js
DesignerHistory.found = function (arrayName, value) {
```

2019-06-07 19:15 UTC, mauriciofauth commented on js/designer/history.js
> +function add_array (add, arr) {
You have to change the signature from:
```js
function add_array (add, arr) {
```
to:
```js
DesignerHistory.addArray = function (add, arr) {
```

2019-06-07 19:15 UTC, mauriciofauth commented on js/designer/history.js
> +function remove_array (rem, arr) {
You have to change the signature from:
```js
function remove_array (rem, arr) {
```
to:
```js
DesignerHistory.removeArray = function (rem, arr) {
```

2019-06-07 19:29 UTC, Bournvita1998 commented
@mauriciofauth Resolved the changes suggested

2019-06-07 19:32 UTC, MauricioFauth approved these changes

2019-06-07 19:34 UTC, Bournvita1998 commented
@mauriciofauth Should I now move ahead to refactor history.js?

2019-06-07 19:35 UTC, mauriciofauth commented
> Should I now move ahead to refactor history.js?

@Bournvita1998 Yes, you can open a new pull request if you want.

2019-06-07 19:38 UTC, Bournvita1998 commented
@mauriciofauth Any suggestion on the query which I asked on the developer's list and also in our personal gitter conversation?

2019-06-07 23:33 UTC, merged