Refactoring designer
phpmyadmin/phpmyadmin pull request #15318
Opened 2019-06-09 20:09 UTC by Bournvita1998

Signed-off-by: Mohit Kuri <mohit.kuri@research.iiit.ac.in>

### Description

Removed vanilla js and added jQuery at several places

Fixes #

Before submitting pull request, please review the following checklist:

- [x] Make sure you have read our [CONTRIBUTING.md](https://github.com/phpmyadmin/phpmyadmin/blob/master/CONTRIBUTING.md) document.
- [x] Make sure you are making a pull request against the correct branch. For example, for bug fixes in a released version use the corresponding QA branch and for new features use the _master_ branch. If you have a doubt, you can ask as a comment in the bug report or on the mailing list.
- [x] Every commit has proper `Signed-off-by` line as described in our [DCO](https://github.com/phpmyadmin/phpmyadmin/blob/master/DCO). This ensures that the work you're submitting is your own creation.
- [x] Every commit has a descriptive commit message.
- [x] Every commit is needed on its own, if you have just minor fixes to previous commits, you can squash them.
- [x] Any new functionality is covered by tests.

2019-06-09 20:36 UTC, Bournvita1998 commented
@shucon the same Travis build issue is still there. I will resolve that soon

2019-06-09 20:57 UTC, williamdes approved these changes

2019-06-09 21:00 UTC, Bournvita1998 commented
I tried to resolve existing Travis build errors but now I am getting this error and I don't think I made any changes related to this is the file

![Selection_043](https://user-images.githubusercontent.com/26218090/59164211-aaf9e500-8b27-11e9-8f2b-096df4e6e891.png)

2019-06-10 08:22 UTC, williamdes commented on js/designer/history.js
> +/* global fromArray */ // js/designer/move.js
@Bournvita1998 here

2019-06-10 08:48 UTC, Bournvita1998 commented on js/designer/history.js
> +/* global fromArray */ // js/designer/move.js
@williamdes  Yes this was the error.. Thanks!!

2019-06-10 20:01 UTC, Bournvita1998 commented
@williamdes  @mauriciofauth @shucon @ibennetch

What else can we refactor here in history.js? Any suggestions?

2019-06-11 07:05 UTC, shucon commented
Fix failed tests :stuck_out_tongue:

2019-06-12 15:32 UTC, ibennetch reviewed
Overall I think you're making good progress here. I'm worried that some of the lines are starting to get a little long and in general I'm not that concerned about turning two shorter lines in to one line line (such as around #94).

I don't see a whole lot more to change in this file.

2019-06-12 15:32 UTC, ibennetch commented on js/designer/history.js
> +            str += historyArray[index].getObj().getOperator() + '( ' + historyArray[index].getColumnName() + ' )' + historyArray[index].getObj().getRelationOperator() + historyArray[index].getObj().g
I personally think this line is too long. We don't have a hard limit on line length, but I think this one got too long.

2019-06-12 15:32 UTC, ibennetch commented on js/designer/history.js
> +            str += '<div class="block"> <table width ="250">' + '<thead><tr><td>';
This probably was a separate line in order to keep the logical break (since the `div class` and `<thead><tr><td>` blocks serve different purposes, it logically makes sense broken across two lines. I think I'd have a slight preference to keeping it as two lines.

2019-06-12 15:32 UTC, ibennetch commented on js/designer/history.js
> +        str += '<h3 class="tiger"><a href="#">' + temp + '</a></h3>' + '<div class="toggle_container">\n';
Is there any particular reason you didn't just combine the
`'</a></h3>' + '<div class="toggle_container">\n';` into
`'</a></h3><div class="toggle_container">\n';`?

2019-06-12 15:32 UTC, ibennetch commented on js/designer/history.js
> +        $('#query_where').style.display = 'block';
This looks like a positive change.

2019-06-12 15:32 UTC, ibennetch commented on js/designer/history.js
> +    $('#ab').innerHTML = DesignerHistory.display(0, 0);
This is good, too.

2019-06-14 12:00 UTC, Bournvita1998 commented on js/designer/history.js
> +        str += '<h3 class="tiger"><a href="#">' + temp + '</a></h3>' + '<div class="toggle_container">\n';
I forgot this... will update it soon

2019-06-14 12:12 UTC, Bournvita1998 commented
@ibennetch there is no specific reasoning behind merging 2 lines in 1, it's just that it is considered a good coding practice. But yeah the logical break is more important here.

![Selection_044](https://user-images.githubusercontent.com/26218090/59508466-af2d5600-8ecb-11e9-9f96-7e944825c53c.png)

By this way, it will satisfy both the situations mentioned here.
Should I do this or the earlier one (the one with the 2 lines) is fine?

2019-06-14 21:02 UTC, Bournvita1998 commented
Any idea why CI is failing? (it's not failing for PHP7.1 but for all other versions it is)

2019-06-14 21:05 UTC, mauriciofauth commented
> Any idea why CI is failing? (it's not failing for PHP7.1 but for all other versions it is)

It is fixed in master by 9102b98ede9ec3308f0711fa7679565a44347720. You should rebase with master with want to fix these errors.

2019-06-14 21:07 UTC, Bournvita1998 commented
> > Any idea why CI is failing? (it's not failing for PHP7.1 but for all other versions it is)
> 
> It is fixed in master by [9102b98](https://github.com/phpmyadmin/phpmyadmin/commit/9102b98ede9ec3308f0711fa7679565a44347720). You should rebase with master with want to fix these errors.

Do we need to rebase this now itself or will we wait until the project gets completed?

2019-06-14 21:12 UTC, mauriciofauth commented
> Do we need to rebase this now itself or will we wait until the project gets completed?

I forgot that this pull request is against a branch different than master, sorry for that.
Just ignore these errors for now.

2019-06-14 21:13 UTC, Bournvita1998 commented
> > Do we need to rebase this now itself or will we wait until the project gets completed?
> 
> I forgot that this pull request is against a branch different than master, sorry for that.
> Just ignore these errors for now.

Okay, So should I make the changes as per reviews and proceed further to other file?

2019-07-07 14:25 UTC, devenbansod commented on js/designer/history.js
> +    $('#ab').innerHTML = DesignerHistory.display(0, 0);
@Bournvita1998 same here

2019-07-07 14:25 UTC, devenbansod requested changes
@Bournvita1998 please fix all these changes w.r.t to our discussion on  #15338

2019-07-07 14:25 UTC, devenbansod commented on js/designer/history.js
> +    $('#ab').innerHTML = DesignerHistory.display(0, 0);
@Bournvita1998 same here (ref: #15338)

2019-07-07 14:25 UTC, devenbansod commented on js/designer/history.js
> +        $('#eQuery').value = historyArray[index].get_obj().getquery();
@Bournvita1998 same here (ref: #15338)

2019-09-23 07:34 UTC, closed without merging