applied bootstrap grid structure on settings page.
phpmyadmin/phpmyadmin pull request #15320
Opened 2019-06-10 13:56 UTC by murex971

Signed-off-by: Nupur Agrawal <nupur202000@gmail.com>

2019-07-02 01:15 UTC, MauricioFauth requested changes

2019-07-02 01:15 UTC, mauriciofauth commented on libraries/classes/Config/FormDisplayTemplate.php
> +       // $htmlOutput .= '<br>';
You forgot a commented line here.

2019-07-02 23:54 UTC, MauricioFauth approved these changes

2019-07-07 16:02 UTC, MauricioFauth requested changes

2019-07-08 09:16 UTC, murex971 commented on templates/server/collations/index.twig
> +<div class="row">
"div_mysql_charset_collations" does not have any specific css attributes associated with it. That's why I removed it because it is of no use as of now.

2019-07-20 04:17 UTC, merged

2019-07-20 04:19 UTC, mauriciofauth commented
Merged, thanks for your contribution!