Quick filter for result table #14112
phpmyadmin/phpmyadmin pull request #15329
Opened 2019-06-13 17:57 UTC by UPF-PBOSS2019

Signed-off-by: UPF-PBOSS2019 <50959285+UPF-PBOSS2019@users.noreply.github.com>

### Description

Implemented: Quick filter for result table #14112

Fixes #

Before submitting pull request, please review the following checklist:

- [ ] Make sure you have read our [CONTRIBUTING.md](https://github.com/phpmyadmin/phpmyadmin/blob/master/CONTRIBUTING.md) document.
- [ ] Make sure you are making a pull request against the correct branch. For example, for bug fixes in a released version use the corresponding QA branch and for new features use the _master_ branch. If you have a doubt, you can ask as a comment in the bug report or on the mailing list.
- [ ] Every commit has proper `Signed-off-by` line as described in our [DCO](https://github.com/phpmyadmin/phpmyadmin/blob/master/DCO). This ensures that the work you're submitting is your own creation.
- [ ] Every commit has a descriptive commit message.
- [ ] Every commit is needed on its own, if you have just minor fixes to previous commits, you can squash them.
- [ ] Any new functionality is covered by tests.

2019-06-13 18:14 UTC, williamdes commented on js/sql.js
> +        $('.table_results.ajax thead tr th[data-column]').each((i, cell) => {           //Apply each Col_Filter
can you use function instead since the arrow syntax is not IE and some browsers compatible
See: https://caniuse.com/#feat=arrow-functions

Reported: https://travis-ci.org/phpmyadmin/phpmyadmin/jobs/545377585#L402

2019-06-13 18:16 UTC, williamdes commented
@UPF-PBOSS2019 Please use your real name (this option is an agreement to our [policy](https://github.com/phpmyadmin/phpmyadmin/blob/master/CONTRIBUTING.md#patches-submission))

2019-06-13 18:16 UTC, williamdes commented
@sudo-bot deploy PR

2019-06-13 18:17 UTC, UPF-PBOSS2019 commented on js/sql.js
> +        $('.table_results.ajax thead tr th[data-column]').each((i, cell) => {           //Apply each Col_Filter
Hi,
Thanks for reply

I'm currently working on it...

2019-06-13 18:18 UTC, UPF-PBOSS2019 commented
> @UPF-PBOSS2019 Please use your real name (this option is an agreement to our [policy](https://github.com/phpmyadmin/phpmyadmin/blob/master/CONTRIBUTING.md#patches-submission))

We are a group, not a single person.

2019-06-13 18:21 UTC, williamdes commented
@UPF-PBOSS2019 In my opinion you should add the signoff of every person :)
And use (just a cool option, use https://help.github.com/en/articles/creating-a-commit-with-multiple-authors#creating-co-authored-commits-on-the-command-line) if you want

cc @ibennetch

2019-06-13 18:30 UTC, williamdes requested changes
Works well !
https://phpmyadmin-pr-15329.wdes.eu.org/sql.php?db=sakila&table=customer&pos=0

2019-06-13 19:29 UTC, UPF-PBOSS2019 commented on js/sql.js
> +        $('.table_results.ajax thead tr th[data-column]').each((i, cell) => {           //Apply each Col_Filter
The last refactor #15329 is tested against IE 11

2019-06-14 13:11 UTC, ibennetch commented
I agree that the best way to handle this is to have each person add a signoff line to comply with the DCO; this is to protect the project and individual contributors legally. You could manually edit the commit message to add lines for each contributor or try the link that William has mentioned, but unfortunately we really are required to have it in place to accept a commit.

2019-06-16 20:54 UTC, UPF-PBOSS2019 commented
Hi,
@williamdes in the last commit, we added the signoff of every person as you requested.

A greeting.

2019-12-23 14:31 UTC, williamdes commented
@UPF-PBOSS2019 Sorry for not merging your work, I am reopening this one

2020-02-18 23:37 UTC, MauricioFauth reviewed
Thank you for your contribution.
It works really well, but I'm not sure about the filter boxes below the column names being always visible.

2020-04-26 01:07 UTC, closed without merging