Remove old DI container
phpmyadmin/phpmyadmin pull request #15335
Opened 2019-06-16 01:13 UTC by mauriciofauth

### Description

Removes old dependency injection container in some files.

Related to #15279

2019-06-16 01:14 UTC, mauriciofauth commented
@Tithugues Can you review this pull request?

I'm trying to help with the removal of the old DI container.

2019-06-16 09:40 UTC, Tithugues commented
@mauriciofauth , thank you! You did almost everything I did yesterday (but didn't push…) so I'm mostly OK with all you that you did. And you also updated the unit tests that wasn't yet up to date on my side!
I believe that I just have a few returns to do on some changes. I'll try to do them today!

2019-06-16 09:53 UTC, Tithugues requested changes

2019-06-16 09:53 UTC, Tithugues commented on db_sql.php
As this may be an imported file, we may need to add:
```php
global $containerBuilder;
```

2019-06-16 09:53 UTC, Tithugues commented on services.yml
> +  insert_edit:
Thank you for this one! I didn't do it yet on my side!

2019-06-16 09:53 UTC, Tithugues commented on sql.php
As this may be an imported file, we may need to add:
```php
global $containerBuilder;
```

2019-06-16 09:53 UTC, Tithugues commented on tbl_change.php
As this may be an imported file, we may need to add:
```php
global $containerBuilder;
```

2019-06-16 09:53 UTC, Tithugues commented on tbl_export.php
As this may be an imported file, we may need to add:
```php
global $containerBuilder;
```

2019-06-16 09:53 UTC, Tithugues commented on tbl_replace.php
As this may be an imported file, we may need to add:
```php
global $containerBuilder;
```

2019-06-16 09:53 UTC, Tithugues commented on tbl_select.php
>  require_once ROOT_PATH . 'libraries/common.inc.php';
As this may be an imported file, we may need to add:
```php
global $containerBuilder;
```

2019-06-16 09:53 UTC, Tithugues commented on tbl_sql.php
As this may be an imported file, we may need to add:
```php
global $containerBuilder;
```

2019-06-16 09:56 UTC, Tithugues commented
I think that there is one last think that we can remove… All the classes in `libraries\Di` (with associated tests), except the `Migration` class which is still needed for now.

2019-06-17 21:38 UTC, merged

2019-06-17 21:39 UTC, mauriciofauth commented
Thank you @Tithugues for your work and help with replacing the custom DI container.

2019-06-17 22:15 UTC, Tithugues commented
Thank you for your help and your reviews.
Feel free to contact me if you find any issues with the new DI. I'll try to help as much as possible.