Refactoring and Improving page.js of designer
phpmyadmin/phpmyadmin pull request #15339
Opened 2019-06-17 10:02 UTC by Bournvita1998

Signed-off-by: Bournvita1998 <mohit.kuri@research.iiit.ac.in>

### Description

Refactored and Improved page.js of the designer section.

Fixes #

Before submitting pull request, please review the following checklist:

- [x] Make sure you have read our [CONTRIBUTING.md](https://github.com/phpmyadmin/phpmyadmin/blob/master/CONTRIBUTING.md) document.
- [x] Make sure you are making a pull request against the correct branch. For example, for bug fixes in a released version use the corresponding QA branch and for new features use the _master_ branch. If you have a doubt, you can ask as a comment in the bug report or on the mailing list.
- [x] Every commit has proper `Signed-off-by` line as described in our [DCO](https://github.com/phpmyadmin/phpmyadmin/blob/master/DCO). This ensures that the work you're submitting is your own creation.
- [x] Every commit has a descriptive commit message.
- [x] Every commit is needed on its own, if you have just minor fixes to previous commits, you can squash them.
- [x] Any new functionality is covered by tests.

2019-06-17 10:23 UTC, williamdes approved these changes

2019-06-22 01:18 UTC, MauricioFauth approved these changes

2019-06-22 03:02 UTC, ibennetch commented
Could you please use your real name in the signoff message? You can modify this with `git commit --amend` and push back to your repository (it might require a force-push, which is okay).

2019-07-07 14:24 UTC, devenbansod requested changes
Please make sure you test your changes (ideally even before you commit, but definitely before you submit the PR)

2019-07-07 14:24 UTC, devenbansod commented on js/designer/page.js
> +            var element = $('#' + input.value);
@Bournvita1998 even this won't work, as we discussed in #15338

2019-07-07 14:24 UTC, devenbansod commented on js/designer/page.js
> +            var table = $('#' + tbId);
@Bournvita1998 same as above

2019-07-07 14:24 UTC, devenbansod commented on js/designer/page.js
> +            var checkbox = $('#check_vis_' + tbId);
@Bournvita1998 same as above

2019-09-17 07:13 UTC, closed without merging