Implemented password_hash function
phpmyadmin/phpmyadmin pull request #15344
Opened 2019-06-19 05:59 UTC by kartik1000

Signed-off-by: Kartik Kathuria <kathuriakartik0@gmail.com>

### Description

Password_hash function has been implemented through this PR by php. To use it you must go to Insert field of any column and then select 'PASSWORD_HASH' as a function in some column which supports text like when we use 'PASSWORD' function. Then Enter the desired password and click on 'Go' and you will see that the row has been inserted with password in the form of hash from password_hash function.
 
Fixes #14772 

Before submitting pull request, please review the following checklist:

- [ ] Make sure you have read our [CONTRIBUTING.md](https://github.com/phpmyadmin/phpmyadmin/blob/master/CONTRIBUTING.md) document.
- [ ] Make sure you are making a pull request against the correct branch. For example, for bug fixes in a released version use the corresponding QA branch and for new features use the _master_ branch. If you have a doubt, you can ask as a comment in the bug report or on the mailing list.
- [ ] Every commit has proper `Signed-off-by` line as described in our [DCO](https://github.com/phpmyadmin/phpmyadmin/blob/master/DCO). This ensures that the work you're submitting is your own creation.
- [ ] Every commit has a descriptive commit message.
- [ ] Every commit is needed on its own, if you have just minor fixes to previous commits, you can squash them.
- [ ] Any new functionality is covered by tests.

2019-06-19 06:05 UTC, williamdes approved these changes
:100:

2019-06-19 06:06 UTC, williamdes commented
Looks good to me, good enhancement! 

@sudo-bot Deploy pr

2019-06-21 14:21 UTC, ibennetch commented
This looks great. I have two thoughts and I'm not certain about either of them:

1) Since PHP can take arguments for this function, should we prompt for them like we do for `AES_ENCRYPT`? If we do this, it probably will require two extra fields (one for the algorithm, one for the options), but I'm not certain whether we should add this.

2) I wonder if we should indicate in some way that this is the PHP function, rather than a MySQL built-in. I'm thinking an informational icon with hover text like "This is a PHP function" or some such.

2019-06-22 05:06 UTC, kartik1000 commented
@ibennetch, I am not certain about the first one as well, because generally  i have used it for single field only, which is input password and create its hash using the function. Second one I think should be done, because some user might try to use the function in SQL Query after seeing it in list, so it will be good to inform them earlier that they cannot use it using SQL Query. Should I start working for Second one? What do you think @williamdes and @ibennetch ?

2019-06-22 11:05 UTC, kartik1000 commented
@williamdes, @ibennetch I have added an alert related to it. Please look if it the position looks ok to you :)

2020-01-20 08:23 UTC, kartik1000 commented
@williamdes can we think on adding this enhancement?

2020-01-20 08:28 UTC, williamdes commented
@kartik1000 If you can rebase onto latest master version ?

I want to implement this feature but you need to do something about https://github.com/phpmyadmin/phpmyadmin/pull/15344#issuecomment-504443907

Maybe you can add subcategory for php functions ?
https://www.w3schools.com/tags/tag_optgroup.asp

2020-01-20 08:33 UTC, kartik1000 commented
@williamdes I have already added an alert message which @ibennetch suggested in 2nd option

2020-01-20 08:34 UTC, kartik1000 commented
I will first rebase so you can deploy and see it.

2020-01-20 10:15 UTC, kartik1000 commented
@williamdes  I have rebased with latest master. Please review. In case you don't see the alert-box to be fit then we can discuss some other option maybe subcategory for php functions.

2020-01-20 12:35 UTC, williamdes commented on js/table/change.js
> +        ' id=salt_' + target.id + ' placeholder=\'' + PMA_messages.strEncryptionKey + '\'+ style="background-color:#FEF3CD;color:#8E6F29;padding:20px;">' + 'ALERT: PASSWORD_HASH is a PHP function and
I would like that another solution is found:
- The place holder is strange `'strEncryptionKey' => __('Encryption key'),`
- The string is not translated
- CSS is inlined
- HTML is injected

@kartik1000 can you please improve this ?

2020-01-20 12:36 UTC, williamdes commented on libraries/classes/InsertEdit.php
> +            elseif ($multi_edit_funcs[$key] == "PASSWORD_HASH") {
```suggestion
            elseif ($multi_edit_funcs[$key] === "PASSWORD_HASH") {
```

2020-01-20 12:36 UTC, williamdes commented on libraries/classes/InsertEdit.php
> +                $current_value = password_hash($current_value,PASSWORD_DEFAULT);
```suggestion
                $current_value = password_hash($current_value, PASSWORD_DEFAULT);
```

2020-01-20 12:37 UTC, williamdes requested changes
I added some comments, thank you for the rebase

2020-01-20 12:49 UTC, kartik1000 commented on js/table/change.js
> +        ' id=salt_' + target.id + ' placeholder=\'' + PMA_messages.strEncryptionKey + '\'+ style="background-color:#FEF3CD;color:#8E6F29;padding:20px;">' + 'ALERT: PASSWORD_HASH is a PHP function and
Yes, sure It was just a proposal so that you could know how I am thinking of the alert box. Do I need to modify this alert box or are we planning something different? @williamdes

2020-05-11 19:04 UTC, closed without merging

2020-05-11 19:19 UTC, mauriciofauth commented
Thanks for your contribution @kartik1000.