Improving move.js of Designer
phpmyadmin/phpmyadmin pull request #15345
Opened 2019-06-20 20:14 UTC by Bournvita1998

Signed-off-by: Bournvita1998 <mohit.kuri@research.iiit.ac.in>

### Description

Improved the performance of move.js in the designer section

Fixes #

Before submitting pull request, please review the following checklist:

- [x] Make sure you have read our [CONTRIBUTING.md](https://github.com/phpmyadmin/phpmyadmin/blob/master/CONTRIBUTING.md) document.
- [x] Make sure you are making a pull request against the correct branch. For example, for bug fixes in a released version use the corresponding QA branch and for new features use the _master_ branch. If you have a doubt, you can ask as a comment in the bug report or on the mailing list.
- [x] Every commit has proper `Signed-off-by` line as described in our [DCO](https://github.com/phpmyadmin/phpmyadmin/blob/master/DCO). This ensures that the work you're submitting is your own creation.
- [x] Every commit has a descriptive commit message.
- [x] Every commit is needed on its own, if you have just minor fixes to previous commits, you can squash them.
- [x] Any new functionality is covered by tests.

2019-06-20 20:53 UTC, williamdes approved these changes

2019-06-20 20:54 UTC, williamdes requested changes
@Bournvita1998 please fix the DCO signature :)

2019-06-21 01:20 UTC, MauricioFauth approved these changes

2019-07-20 10:27 UTC, devenbansod approved these changes
LGTM

2019-09-11 22:33 UTC, merged

2019-09-11 22:33 UTC, mauriciofauth commented
Merged, thanks for your contribution!