Change MIME type references to Media (MIME) type
phpmyadmin/phpmyadmin pull request #15354
Opened 2019-06-24 18:05 UTC by mauriciofauth

### Description

Change _MIME type_ references to _Media (MIME) type_ and _MIME_ references to _Media type (MIME)_.

Related to #15350

2019-06-24 18:10 UTC, williamdes approved these changes

2019-06-25 03:16 UTC, ibennetch requested changes
Nice work. I left a few comments in line.

2019-06-25 03:16 UTC, ibennetch commented on doc/glossary.rst
> +
👍

2019-06-25 03:16 UTC, ibennetch commented on libraries/classes/Plugins/Export/ExportHtmlword.php
> +                . __('Media type (MIME)')
The original use of `htmlspecialchars()` is odd to me here, but this seems like a good change.

2019-06-25 03:16 UTC, ibennetch commented on libraries/classes/Plugins/Export/Helpers/Pdf.php
> +            $this->colTitles[$columns_cnt] = __('Media type (MIME)');
In several places, you flip back and forth between "Media type (MIME)" and "Media (MIME) type". We should pick one and I think the second way sounds more natural. Therefore, I'd change this one.

2019-06-25 03:16 UTC, ibennetch commented on templates/database/data_dictionary/index.twig
> +            <th>{% trans 'Media type (MIME)' %}</th>
And the order here as well.

2019-06-25 06:39 UTC, mauriciofauth commented
@ibennetch Done! I fixed the inconsistencies.

2019-07-11 02:37 UTC, merged