Favortie database feature implemented
phpmyadmin/phpmyadmin pull request #15353
Opened 2019-06-24 11:19 UTC by apoorvkhare07

Signed-off-by: Apoorv Khare <apoorvkhare007@gmail.com>

### Description
Add Feature for selecting favourite databases similar to favourite table feature.

Before submitting pull request, please review the following checklist:

- [x] Make sure you have read our [CONTRIBUTING.md](https://github.com/phpmyadmin/phpmyadmin/blob/master/CONTRIBUTING.md) document.
- [x] Make sure you are making a pull request against the correct branch. For example, for bug fixes in a released version use the corresponding QA branch and for new features use the _master_ branch. If you have a doubt, you can ask as a comment in the bug report or on the mailing list.
- [x] Every commit has proper `Signed-off-by` line as described in our [DCO](https://github.com/phpmyadmin/phpmyadmin/blob/master/DCO). This ensures that the work you're submitting is your own creation.
- [x] Every commit has a descriptive commit message.
- [x] Every commit is needed on its own, if you have just minor fixes to previous commits, you can squash them.
- [x] Any new functionality is covered by tests.

2019-06-24 12:48 UTC, shucon commented
There are failed CI tests

2019-06-24 12:51 UTC, shucon commented
You can use `https://editorconfig.org/#download` to fix trailing whitespace automatically.

2019-06-24 12:54 UTC, williamdes requested changes

2019-06-24 12:54 UTC, williamdes commented on libraries/classes/Controllers/Server/DatabasesController.php
> +        $user = sha1($cfg['Server']['user']);
can you use `hash('sha1'` ?

2019-06-24 12:54 UTC, williamdes commented on libraries/classes/Controllers/Server/DatabasesController.php
> +                'msg' => __("Favorite List is full!"),
List does not need a capital `L` ?

2019-06-24 12:54 UTC, williamdes commented on libraries/classes/Controllers/Server/DatabasesController.php
> +                'name_hash' => md5($database['SCHEMA_NAME']),
Can you use sha1 and hash method ?

2019-06-24 12:54 UTC, williamdes commented on libraries/classes/FavoriteDatabase.php
> +class FavoriteDatabase
That would be cool to use twig for all HTML in the class

2019-06-24 12:54 UTC, williamdes commented on libraries/classes/FavoriteDatabase.php
> +            = " REPLACE INTO " . $this->_getPmaTable() . " (`username`, `tables`)" .
I think you could use `INSERT OR IGNORE INTO` ?
I think there is compatibility issues with `REPLACE INTO` ?

2019-06-24 12:54 UTC, williamdes commented on libraries/classes/FavoriteDatabase.php
> +     * @return string pma table name
string|null

2019-06-24 12:54 UTC, williamdes commented on libraries/classes/FavoriteDatabase.php
> +    private function _getPmaTable()
(): ?string

2019-06-24 12:54 UTC, williamdes commented on server_databases.php
> +if ( ! empty($_REQUEST['favorite_db'])) {
Please use `$_GET` or `$_POST`

2019-06-24 13:02 UTC, shucon commented on libraries/classes/Controllers/HomeController.php
> +        // $syncFavoriteTables = RecentFavoriteDb::getInstance('favorite_db')
Remove comments

2019-06-24 13:04 UTC, shucon commented on libraries/classes/RecentFavoriteTable.php
> +    //         return '';
Remove unnecessary comments.

2019-06-25 21:18 UTC, williamdes commented on libraries/classes/Controllers/Server/DatabasesController.php
> +                'name_hash' => hash(sha1($database['SCHEMA_NAME'])),
```suggestion
                'name_hash' => hash('sha1', $database['SCHEMA_NAME']),
```

2019-06-25 21:19 UTC, williamdes requested changes
I think you can extract the HTML to twig

2019-06-26 09:02 UTC, shucon commented
Fix failed tests. 
Refer:
https://travis-ci.org/phpmyadmin/phpmyadmin/jobs/550498083
https://travis-ci.org/phpmyadmin/phpmyadmin/jobs/550498084

2019-06-26 09:04 UTC, shucon commented on libraries/classes/Controllers/Server/DatabasesController.php
> +            print('hello');
This is not required.

2019-06-26 09:09 UTC, shucon requested changes

2019-06-26 09:09 UTC, shucon commented on libraries/classes/Controllers/Server/DatabasesController.php
> +}
```suggestion
}

```

2019-06-26 09:09 UTC, shucon commented on libraries/classes/FavoriteDatabase.php
> +}
```suggestion
}

```

2019-06-26 09:09 UTC, shucon commented on libraries/classes/Navigation/NavigationTree.php
> +}
```suggestion
}

```

2019-06-26 09:09 UTC, shucon commented on server_databases.php
> +}
```suggestion
}

```

2019-06-26 09:09 UTC, shucon commented on templates/server/databases/favorite_anchor.twig
> +</a>
```suggestion
</a>

```

2019-06-26 09:09 UTC, shucon commented on templates/server/databases/index.twig
> +{% endif %}
```suggestion
{% endif %}

```

2019-06-26 09:09 UTC, shucon commented on libraries/classes/Controllers/HomeController.php
> +}
```suggestion
}

```

2019-06-26 09:10 UTC, shucon commented
@sudo-bot Deploy PR

2019-06-27 15:09 UTC, shucon commented
![Screenshot from 2019-06-27 20-37-13](https://user-images.githubusercontent.com/22860775/60277542-6b9b0900-991b-11e9-9d26-b37317e64e03.png)
It's showing an error when going to `server_databases.php`.
Also change the name of `Databases` to `Favourite Databases`.

2019-06-27 17:04 UTC, williamdes commented
@shucon https://github.com/phpmyadmin/phpmyadmin/pull/15353#discussion_r297398225

2019-07-20 04:12 UTC, apoorvkhare07 commented on libraries/classes/FavoriteDatabase.php
> +class FavoriteDatabase
@williamdes The whole side nav is currently rendered through PHP only not twig. In order to change this to twig I will have to write twig templates for the whole side nav bar.
I have written Favorite Database similar to Favorite Table already written.

2019-07-22 14:02 UTC, shucon commented
@sudo-bot Deploy PR

2019-07-22 14:03 UTC, shucon commented
Please fix the merge-conflicts.

2019-09-27 14:53 UTC, closed without merging