Button on Export Page to show SQL Query
phpmyadmin/phpmyadmin pull request #15365
Opened 2019-06-29 04:28 UTC by kartik1000

Signed-off-by: Kartik Kathuria <kathuriakartik0@gmail.com>

### Description
Please describe your pull request.
The following PR adds Show SQL Query button on Export page, to show the SQL Query used for exporting. In case, one does not go to the export page after executing some SQL Query the button is not shown. 
Fixes #14340 

Before submitting pull request, please review the following checklist:

- [ ] Make sure you have read our [CONTRIBUTING.md](https://github.com/phpmyadmin/phpmyadmin/blob/master/CONTRIBUTING.md) document.
- [ ] Make sure you are making a pull request against the correct branch. For example, for bug fixes in a released version use the corresponding QA branch and for new features use the _master_ branch. If you have a doubt, you can ask as a comment in the bug report or on the mailing list.
- [ ] Every commit has proper `Signed-off-by` line as described in our [DCO](https://github.com/phpmyadmin/phpmyadmin/blob/master/DCO). This ensures that the work you're submitting is your own creation.
- [ ] Every commit has a descriptive commit message.
- [ ] Every commit is needed on its own, if you have just minor fixes to previous commits, you can squash them.
- [ ] Any new functionality is covered by tests.

2019-07-01 08:01 UTC, kartik1000 commented
@williamdes please review :)

2019-07-01 08:05 UTC, williamdes commented
@sudo-bot /deploy

2019-07-01 08:09 UTC, williamdes commented on js/export.js
> +    var sqlquery = sessionStorage.getItem("sqlquery");
You should use `if (isStorageSupported('sessionStorage')) {`

2019-07-01 08:10 UTC, williamdes commented on js/export.js
> +        title: 'Sql query',
Could you make this translatable ?

2019-07-04 06:53 UTC, williamdes requested changes

2019-07-04 06:53 UTC, williamdes commented on templates/display/export/template_loading.twig
> +            <h4>Show Sql Query:</h4>
```suggestion
            <h4>{% trans 'Show Sql Query:' %}</h4>
```

2019-07-04 06:53 UTC, williamdes commented on templates/display/export/template_loading.twig
> +                value="Show the SQL Query">
```suggestion
                value="{% trans 'Show the SQL Query' %}">
```

2019-07-04 06:53 UTC, williamdes commented on js/export.js
> +            title: 'Sql query',
Please make the string translatable like `PMA_messages.strClose`

`PMA_messages` to `Messages` was renamed by @mauriciofauth (ea2d5a0d87a706814df929e9c5cedee5f84e9fcc)

2019-09-15 11:05 UTC, kartik1000 commented
@williamdes  I made the change. Please review :)

2019-09-15 19:51 UTC, williamdes commented on js/export.js
> +            closingoptions[PMA_messages.strClose] = function () {
`PMA_messages` was renamed to `Messages`

2019-09-15 19:51 UTC, williamdes commented on js/export.js
> +                PMA_highlightSQL($(this));
the function was renamed

2019-10-06 17:00 UTC, kartik1000 commented
@williamdes, renamed the functions.  Please review :)

2019-10-07 05:51 UTC, williamdes approved these changes

2020-01-11 18:34 UTC, williamdes approved these changes

2020-01-11 18:34 UTC, williamdes commented
@sudo-bot Deploy PR

2020-01-12 19:31 UTC, williamdes commented
I changed the ui part of your contribution
![image](https://user-images.githubusercontent.com/7784660/72224382-51084480-357a-11ea-8e47-77608ee0cdb7.png)
But I am still not sure about the placement of this button and you are not creating a workaround for #14340 

Maybe fixing the return button is a better idea :thinking: ?

2020-01-12 21:20 UTC, kartik1000 commented
@williamdes, I felt that the export page was designed such that it cannot return to the query page and that was not a bug. 
The ui is good and and a new heading was required :)
I feel that we can use maybe both. It can probably be used as shortcut rather than returning back and if not, and if this is no urgent then I can look for fix to return button and keep this PR open as well and change suggested change in the issue description 😄

2020-01-12 21:23 UTC, williamdes commented
> I can look for fix to return button

That would be a great idea, seems like users are mad about that stupid return issue

2020-05-02 11:26 UTC, williamdes commented
@kartik1000 Would it be possible to rebase onto latest master version and do not rely on local storage ?

2020-07-02 21:18 UTC, williamdes commented
![image](https://user-images.githubusercontent.com/7784660/86409978-41142680-bcba-11ea-98e4-c93d40208920.png)

2020-07-02 21:19 UTC, williamdes commented
@kartik1000 I worked on your code and simplified it, would you agree to review it ?

2020-07-02 21:49 UTC, kartik1000 commented
@williamdes, Yes sure! I will do it by tomorrow👍. On first look it looks good to me :)

2020-07-22 15:41 UTC, merged

2020-07-22 15:41 UTC, williamdes commented
Merged !
Thank you !