card classes added to home page
phpmyadmin/phpmyadmin pull request #15369
Opened 2019-07-02 07:51 UTC by murex971

Signed-off-by: Nupur Agrawal <nupur202000@gmail.com>

Before submitting pull request, please review the following checklist:

- [ ] Make sure you have read our [CONTRIBUTING.md](https://github.com/phpmyadmin/phpmyadmin/blob/master/CONTRIBUTING.md) document.
- [ ] Make sure you are making a pull request against the correct branch. For example, for bug fixes in a released version use the corresponding QA branch and for new features use the _master_ branch. If you have a doubt, you can ask as a comment in the bug report or on the mailing list.
- [ ] Every commit has proper `Signed-off-by` line as described in our [DCO](https://github.com/phpmyadmin/phpmyadmin/blob/master/DCO). This ensures that the work you're submitting is your own creation.
- [ ] Every commit has a descriptive commit message.
- [ ] Every commit is needed on its own, if you have just minor fixes to previous commits, you can squash them.
- [ ] Any new functionality is covered by tests.

2019-07-02 08:55 UTC, williamdes approved these changes
LGTM

2019-07-02 23:48 UTC, mauriciofauth commented
@sudo-bot Deploy pull request

2019-07-20 05:04 UTC, MauricioFauth requested changes
Can you rebase with _master_ branch and fix the conflicts?

2019-08-30 15:58 UTC, MauricioFauth requested changes

2019-08-30 15:58 UTC, mauriciofauth commented on templates/home/index.twig
> +                  <a href="changelog.php{{ get_common() }}" target="_blank">
```suggestion
                  <a href="{{ url('/changelog') }}" target="_blank">
```

2019-08-30 15:58 UTC, mauriciofauth commented on templates/home/index.twig
> +                  <a href="license.php{{ get_common() }}" target="_blank">
```suggestion
                  <a href="{{ url('/license') }}" target="_blank">
```

2019-08-30 15:58 UTC, mauriciofauth commented on templates/preferences/manage/main.twig
> -                            {{ 'You have no saved settings!'|trans|notice }}
You removed the `localStorage-empty` `div`.

2019-08-30 15:58 UTC, mauriciofauth commented on templates/preferences/manage/main.twig
> +                      action="prefs_manage.php" method="post">
```suggestion
                      action="{{ url('/preferences/manage') }}" method="post">
```

2019-08-30 15:58 UTC, mauriciofauth commented on templates/preferences/two_factor/main.twig
> +        <form method="post" action="prefs_twofactor.php">
```suggestion
        <form method="post" action="{{ url('/preferences/twofactor') }}">
```

2019-08-30 15:58 UTC, mauriciofauth commented on templates/preferences/two_factor/main.twig
> +        <form method="post" action="prefs_twofactor.php">
```suggestion
        <form method="post" action="{{ url('/preferences/twofactor') }}">
```

2019-08-30 15:58 UTC, mauriciofauth commented on themes/pmahomme/scss/_common.scss
>  }
You should remove the empty block.
See: https://travis-ci.org/phpmyadmin/phpmyadmin/jobs/575149921#L415

2019-11-07 07:20 UTC, closed without merging