Refactoring move.js of Designer
phpmyadmin/phpmyadmin pull request #15378
Opened 2019-07-08 01:19 UTC by Bournvita1998

Signed-off-by: Mohit Kuri <mohit.kuri@research.iiit.ac.in>

### Description

Refactored move.js of the designer but not completely yet.

Fixes #

Before submitting pull request, please review the following checklist:

- [x] Make sure you have read our [CONTRIBUTING.md](https://github.com/phpmyadmin/phpmyadmin/blob/master/CONTRIBUTING.md) document.
- [x] Make sure you are making a pull request against the correct branch. For example, for bug fixes in a released version use the corresponding QA branch and for new features use the _master_ branch. If you have a doubt, you can ask as a comment in the bug report or on the mailing list.
- [x] Every commit has proper `Signed-off-by` line as described in our [DCO](https://github.com/phpmyadmin/phpmyadmin/blob/master/DCO). This ensures that the work you're submitting is your own creation.
- [x] Every commit has a descriptive commit message.
- [x] Every commit is needed on its own, if you have just minor fixes to previous commits, you can squash them.
- [x] Any new functionality is covered by tests.

2019-07-08 01:31 UTC, Bournvita1998 commented
For testing, I have tested this whole thing in general. Here is an example of the same:

Using - document.getElementById('selector')

![YO](https://user-images.githubusercontent.com/26218090/60777029-bf90c380-a14d-11e9-99ce-fb1d83f3cc62.jpg)

Using - $('#selector')[0]

![YO2](https://user-images.githubusercontent.com/26218090/60777036-c6b7d180-a14d-11e9-9aa7-4fc8872439e0.jpg)

Since this worked, I replicated the same here.

@devenbansod Please review and provide feedback for the same. Will proceed further once the work till here is approved and we are good to go ahead.

2019-07-08 04:13 UTC, devenbansod requested changes
@Bournvita1998 I've left a comment. It applies to all the changes.

2019-07-08 04:13 UTC, devenbansod commented on js/designer/move.js
> +        $('#canvas')[0].style.display = 'none';
@Bournvita1998 this would work for the elements selected with IDs only. I'd ideally use `.css()` method to set the styles instead of manually selecting the first element and setting the native properties. IMO (even though it works) this current approach sort of doesn't use JQuery's power at all.

Using `.css()` would auto-loop over all the selected elements, so would be easier to read when we're selecting based on input types, classes etc.

2019-07-08 10:12 UTC, shucon commented on js/designer/move.js
> +        $('#canvas')[0].style.display = 'none';
I agree with @devenbansod . Don't try to hard-code things. As you're trying to refactor the code, try to do it in such a way that would let other developers work on the code without much changes to your code. It gets extremely difficult to manage such things on such a large scale.

2019-07-08 12:10 UTC, Bournvita1998 commented on js/designer/move.js
> +        $('#canvas')[0].style.display = 'none';
Okay, I will make these changes asap. Thanks @devenbansod, @shucon

2019-07-09 18:30 UTC, Bournvita1998 commented
@devenbansod @shucon Please have a look now

2019-07-15 14:55 UTC, Bournvita1998 commented
I am done refactoring move.js once. Please share your reviews so that I can make the possible changes

2019-09-21 06:27 UTC, closed without merging