Fix/minor improvements
phpmyadmin/phpmyadmin pull request #15376
Opened 2019-07-06 21:52 UTC by Tithugues

### Description

This MR includes many improvements on many topics:
* merge isset / unset
* use constants in some places
* use relevant static calls when needed

2019-07-07 07:34 UTC, williamdes commented on libraries/classes/Config.php
> +            $git_folder .= trim($common_dir_contents) . DIRECTORY_SEPARATOR;
You inverted the operation

2019-07-07 07:37 UTC, williamdes commented on libraries/classes/Export.php
> +            $tmp_select = implode('|', $db_select);
Good catch!

2019-07-07 07:54 UTC, williamdes requested changes
LGTM
I left one comment

2019-07-07 11:50 UTC, Tithugues commented on libraries/classes/Config.php
> +            $git_folder .= trim($common_dir_contents) . DIRECTORY_SEPARATOR;
You're right, sorry for that.
This should be fixed now.

2019-07-07 14:01 UTC, MauricioFauth approved these changes

2019-07-07 14:04 UTC, mauriciofauth commented on libraries/classes/Util.php
> +        $geom_type = mb_strtolower(trim((string)$geom_type));
The coding standard requires 1 space after the cast statement.

```suggestion
        $geom_type = mb_strtolower(trim((string) $geom_type));
```

2019-07-07 15:22 UTC, williamdes approved these changes

2019-07-07 16:52 UTC, Tithugues commented on libraries/classes/Util.php
> +        $geom_type = mb_strtolower(trim((string)$geom_type));
Sorry. Fixed.

2019-07-17 02:23 UTC, mauriciofauth commented
Merged in ffdc2cf7bf66b1e7f1090b9d05794483bc3f4df0. Thanks for your contribution.

2019-07-17 02:23 UTC, closed without merging