removed hard-coded things
phpmyadmin/phpmyadmin pull request #15382
Opened 2019-07-10 01:04 UTC by Bournvita1998

Signed-off-by: Mohit Kuri <mohit.kuri@research.iiit.ac.in>

### Description

Resolves issues exiting in https://github.com/phpmyadmin/phpmyadmin/pull/15338

Fixes #

Before submitting pull request, please review the following checklist:

- [x] Make sure you have read our [CONTRIBUTING.md](https://github.com/phpmyadmin/phpmyadmin/blob/master/CONTRIBUTING.md) document.
- [x] Make sure you are making a pull request against the correct branch. For example, for bug fixes in a released version use the corresponding QA branch and for new features use the _master_ branch. If you have a doubt, you can ask as a comment in the bug report or on the mailing list.
- [x] Every commit has proper `Signed-off-by` line as described in our [DCO](https://github.com/phpmyadmin/phpmyadmin/blob/master/DCO). This ensures that the work you're submitting is your own creation.
- [x] Every commit has a descriptive commit message.
- [x] Every commit is needed on its own, if you have just minor fixes to previous commits, you can squash them.
- [x] Any new functionality is covered by tests.

2019-07-10 04:57 UTC, williamdes approved these changes

2019-07-20 10:31 UTC, devenbansod approved these changes

2019-09-11 22:40 UTC, MauricioFauth requested changes

2019-09-11 22:40 UTC, mauriciofauth commented on js/designer/init.js
> +        $('#query_Aggregate').css("display", 'none');
```suggestion
        $('#query_Aggregate').css('display', 'none');
```

2019-09-11 22:40 UTC, mauriciofauth commented on js/designer/init.js
> +        $('#query_having').css("display", 'none');
```suggestion
        $('#query_having').css('display', 'none');
```

2019-09-11 22:40 UTC, mauriciofauth commented on js/designer/init.js
> +        $('#query_rename_to').css("display", 'none');
```suggestion
        $('#query_rename_to').css('display', 'none');
```

2019-09-11 22:40 UTC, mauriciofauth commented on js/designer/init.js
> +        $('#query_where').css("display", 'none');
```suggestion
        $('#query_where').css('display', 'none');
```

2019-11-17 23:17 UTC, closed without merging