bootstrap table classes added to all classes
phpmyadmin/phpmyadmin pull request #15392
Opened 2019-07-18 18:46 UTC by murex971

Signed-off-by: Nupur Agrawal <nupur202000@gmail.com>

### Description

Applies bootsrap table classes to all the tables and provide an overall consistency across tables.

Before submitting pull request, please review the following checklist:

- [ ] Make sure you have read our [CONTRIBUTING.md](https://github.com/phpmyadmin/phpmyadmin/blob/master/CONTRIBUTING.md) document.
- [ ] Make sure you are making a pull request against the correct branch. For example, for bug fixes in a released version use the corresponding QA branch and for new features use the _master_ branch. If you have a doubt, you can ask as a comment in the bug report or on the mailing list.
- [ ] Every commit has proper `Signed-off-by` line as described in our [DCO](https://github.com/phpmyadmin/phpmyadmin/blob/master/DCO). This ensures that the work you're submitting is your own creation.
- [ ] Every commit has a descriptive commit message.
- [ ] Every commit is needed on its own, if you have just minor fixes to previous commits, you can squash them.
- [ ] Any new functionality is covered by tests.

2019-07-20 05:07 UTC, mauriciofauth commented
@sudo-bot Deploy PR

2019-07-20 19:01 UTC, mauriciofauth commented
> Applies bootsrap table classes to all the tables and provide an overall consistency across tables.

You commented that you added the Bootstrap classes in **all** the tables, but only the tables of the server pages received the classes, the database pages and the table pages are still missing. Is this pull request a work in progress?

2019-07-22 10:10 UTC, murex971 commented
> > Applies bootsrap table classes to all the tables and provide an overall consistency across tables.
> 
> @murex971 You commented that you added the Bootstrap classes in **all** the tables, but only the tables of the server pages received the classes, the database pages and the table pages are still missing. Is this pull request a work in progress?

yeah, it is still in progress.

2019-08-21 20:42 UTC, MauricioFauth requested changes

2019-08-21 20:42 UTC, mauriciofauth commented on templates/server/plugins/index.twig
> +      {% for plugin_type in plugins|keys %}
```suggestion
      {% for type in plugins|keys %}
```

2019-08-21 20:42 UTC, mauriciofauth commented on templates/server/plugins/index.twig
> +        <a class="btn btn-primary" href="#plugins-{{- plugins_type_clean[plugin_type] }}">
```suggestion
        <a class="btn btn-primary" href="#plugins-{{ clean_types[type] }}">
```

2019-08-21 20:42 UTC, mauriciofauth commented on templates/server/plugins/index.twig
> +            {{ plugin_type }}
```suggestion
            {{ type }}
```

2019-08-21 20:42 UTC, mauriciofauth commented on templates/server/plugins/index.twig
> +            {{ plugin_type }}
```suggestion
            {{ type }}
```

2019-08-21 20:42 UTC, mauriciofauth commented on templates/server/plugins/index.twig
> +            {% for plugin in plugin_list %}
```suggestion
            {% for plugin in list %}
```

2019-08-21 20:42 UTC, mauriciofauth commented on templates/server/plugins/index.twig
> +                      {% trans 'disabled' %}
```suggestion
                      {% if plugin.status == 'INACTIVE' %}
                        {% trans 'inactive' %}
                      {% elseif plugin.status == 'DISABLED' %}
                        {% trans 'disabled' %}
                      {% elseif plugin.status == 'DELETING' %}
                        {% trans 'deleting' %}
                      {% elseif plugin.status == 'DELETED' %}
                        {% trans 'deleted' %}
                      {% endif %}
```

2019-08-21 20:42 UTC, mauriciofauth commented on templates/server/plugins/index.twig
> +                <td>{{ plugin.plugin_license }}</td>
```suggestion
                <td>{{ plugin.license }}</td>
```

2019-08-21 20:42 UTC, mauriciofauth commented on templates/server/plugins/index.twig
> +                <td>{{ plugin.plugin_author }}</td>
```suggestion
                <td>{{ plugin.author }}</td>
```

2019-08-21 20:42 UTC, mauriciofauth commented on templates/server/plugins/index.twig
> +                <td>{{ plugin.plugin_type_version }}</td>
```suggestion
                <td>{{ plugin.version }}</td>
```

2019-08-21 20:42 UTC, mauriciofauth commented on templates/server/plugins/index.twig
> +                <td>{{ plugin.plugin_description }}</td>
```suggestion
                <td>{{ plugin.description }}</td>
```

2019-10-28 20:04 UTC, closed without merging