Export view option added in Export
phpmyadmin/phpmyadmin pull request #15416
Opened 2019-08-05 09:52 UTC by kartik1000

Signed-off-by: Kartik Kathuria <kathuriakartik0@gmail.com>

### Description
The PR adds export view option in export under data creation options and replaces `CREATE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW...` with `CREATE VIEW...` as suggested. 
Fixes #14815 

Before submitting pull request, please review the following checklist:

- [ ] Make sure you have read our [CONTRIBUTING.md](https://github.com/phpmyadmin/phpmyadmin/blob/master/CONTRIBUTING.md) document.
- [ ] Make sure you are making a pull request against the correct branch. For example, for bug fixes in a released version use the corresponding QA branch and for new features use the _master_ branch. If you have a doubt, you can ask as a comment in the bug report or on the mailing list.
- [ ] Every commit has proper `Signed-off-by` line as described in our [DCO](https://github.com/phpmyadmin/phpmyadmin/blob/master/DCO). This ensures that the work you're submitting is your own creation.
- [ ] Every commit has a descriptive commit message.
- [ ] Every commit is needed on its own, if you have just minor fixes to previous commits, you can squash them.
- [ ] Any new functionality is covered by tests.

2019-08-20 11:39 UTC, williamdes requested changes

2019-08-20 11:39 UTC, williamdes commented on libraries/classes/Plugins/Export/ExportSql.php
> +
You should add this options to `$subgroup_create_view` at L326
```php
                $leaf = new BoolPropertyItem(
                    "simple_export",
                    _pgettext('Allow simplifying exported view syntax to only "CREATE VIEW"', 'Use simple view export')
                );
                $subgroup_create_view->addProperty($leaf);
```

2019-08-20 11:39 UTC, williamdes commented on view_create.php
> +        if(!isset($_POST['sql_simple_export'])) {
space missing 
```suggestion
        if(! isset($_POST['sql_simple_export'])) {
```

2019-08-20 11:39 UTC, williamdes commented on view_create.php
> +            }
you are maybe missing a `}`

2019-08-20 11:44 UTC, kartik1000 commented
Ok @williamdes, I'll make the required changes by night :)

2019-08-22 14:03 UTC, kartik1000 commented on libraries/classes/Plugins/Export/ExportSql.php
> +
@williamdes, there is no subgroup as as subgroup_create_view, did you mean to add it simply in object creation system under $subgroup?

2019-08-23 07:23 UTC, williamdes commented on libraries/classes/Plugins/Export/ExportSql.php
> +
@kartik1000 yeah, sorry
You should maybe create one after :+1: 

```php
// Add view option
                $leaf = new BoolPropertyItem(
                    'create_view',
                    sprintf(__('Add %s statement'), '<code>CREATE VIEW</code>')
                );
                $subgroup->addProperty($leaf);
```

`subgroup_create_view` must exist on another branch :confused:

2019-08-23 18:59 UTC, kartik1000 commented on libraries/classes/Plugins/Export/ExportSql.php
> +
Sorry, but subgroup_create_view exists on this branch too, but earlier i was accessing the files through xampp, so couldn't find it. Now I have done the required change :)

2019-08-25 12:52 UTC, williamdes approved these changes

2020-01-12 21:56 UTC, kartik1000 commented
@williamdes, I have rebased it to QA_5_0. cherry-pick was not working because exportcontrollers.php existed in master but its required code was replaced in export.php in QA_5_0 and this was leading to conflicts. So some part of it had to be done manually.

2020-01-12 22:00 UTC, williamdes commented
Thank you @kartik1000 
Is the feature working now ?

2020-03-20 22:00 UTC, williamdes commented
@kartik1000 I found a solution for you and force pushed the pull-request
Could you test it ?

2020-04-30 14:10 UTC, kartik1000 commented
@williamdes,  Yup it works as expected now. Replaces the SQL Keywords successfully. You can test and merge :)

2020-05-01 23:22 UTC, merged

2020-05-01 23:22 UTC, williamdes commented
Thank you @kartik1000 !

2021-07-14 05:50 UTC, smalos commented
Is this "export view option" already included in phpMyAdmin?

2021-07-14 10:51 UTC, williamdes commented
> Is this "export view option" already included in phpMyAdmin?

Hi @smalos 
As the milestone assigned to this PR says, it is part of 5.1.0 and newer