Password String escaped correctly Fix#15202
phpmyadmin/phpmyadmin pull request #15428
Opened 2019-08-11 18:21 UTC by kartik1000

Signed-off-by: Kartik Kathuria <kathuriakartik0@gmail.com>

### Description

The commit ensures that password string is escaped correctly while creating a new user account and adding password. It uses PHP addslashes() function to correctly escape string. 

Fixes #15202 

Before submitting pull request, please review the following checklist:

- [ ] Make sure you have read our [CONTRIBUTING.md](https://github.com/phpmyadmin/phpmyadmin/blob/master/CONTRIBUTING.md) document.
- [ ] Make sure you are making a pull request against the correct branch. For example, for bug fixes in a released version use the corresponding QA branch and for new features use the _master_ branch. If you have a doubt, you can ask as a comment in the bug report or on the mailing list.
- [ ] Every commit has proper `Signed-off-by` line as described in our [DCO](https://github.com/phpmyadmin/phpmyadmin/blob/master/DCO). This ensures that the work you're submitting is your own creation.
- [ ] Every commit has a descriptive commit message.
- [ ] Every commit is needed on its own, if you have just minor fixes to previous commits, you can squash them.
- [ ] Any new functionality is covered by tests.

2019-08-11 19:10 UTC, williamdes commented on libraries/classes/Server/Privileges.php
> +            "SELECT PASSWORD('" . addslashes($password) . "') AS `password`;"
You could use `addcslashes($password, '"');` ? (I did not try it but seems more appropriate since only `"` must be escaped

https://www.php.net/manual/en/function.addcslashes.php

```suggestion
            "SELECT PASSWORD('" . addcslashes($password, '"') . "') AS `password`;"
```

2019-08-11 19:56 UTC, kartik1000 commented on libraries/classes/Server/Privileges.php
> +            "SELECT PASSWORD('" . addslashes($password) . "') AS `password`;"
@williamdes, I checked by making the change, but it is not working as the issue is not being resolved and it shows Password as No in User Accounts

2019-08-11 20:22 UTC, williamdes commented on libraries/classes/Server/Privileges.php
> +            "SELECT PASSWORD('" . addslashes($password) . "') AS `password`;"
@kartik1000 okay, I removed my suggestion
```sql
SELECT PASSWORD(''),PASSWORD('"'),PASSWORD('\''),PASSWORD("'"),PASSWORD("\"")
```

2019-08-11 20:23 UTC, williamdes commented on libraries/classes/Server/Privileges.php
>      {
```suggestion
     {
     $password = $this->dbi->escapeString($password);
```

2019-08-11 20:24 UTC, williamdes requested changes

2019-08-11 20:24 UTC, williamdes commented on libraries/classes/Server/Privileges.php
> +            "SELECT PASSWORD('" . addslashes($password) . "') AS `password`;"
@kartik1000 here is a better one: https://github.com/phpmyadmin/phpmyadmin/pull/15428/files#r312753043

2019-08-12 06:16 UTC, kartik1000 commented on libraries/classes/Server/Privileges.php
> +            "SELECT PASSWORD('" . addslashes($password) . "') AS `password`;"
![image](https://user-images.githubusercontent.com/43112279/62847948-ac49b880-bcf6-11e9-83d2-934464c88478.png)
The error I am getting after making the change.

2019-08-12 06:31 UTC, williamdes commented on libraries/classes/Server/Privileges.php
> +            "SELECT PASSWORD('" . addslashes($password) . "') AS `password`;"
Use `$GLOBALS['dbi']->` instead :)

2019-08-12 06:41 UTC, kartik1000 commented on libraries/classes/Server/Privileges.php
> +            "SELECT PASSWORD('" . addslashes($password) . "') AS `password`;"
This one is working @williamdes :) Shall I make the change then?

2019-08-12 06:49 UTC, williamdes commented on libraries/classes/Server/Privileges.php
> +            "SELECT PASSWORD('" . addslashes($password) . "') AS `password`;"
Yes, absolutely :)

2019-08-12 15:53 UTC, williamdes approved these changes

2019-08-15 18:32 UTC, williamdes approved these changes
Thanks Kartik, merged !

2019-08-15 18:51 UTC, merged