Made required changes to add online transaction option
phpmyadmin/phpmyadmin pull request #15420
Opened 2019-08-06 19:33 UTC by kartik1000

Signed-off-by: Kartik Kathuria <kathuriakartik0@gmail.com>

### Description

Please describe your pull request.

Fixes #

Before submitting pull request, please review the following checklist:

- [ ] Make sure you have read our [CONTRIBUTING.md](https://github.com/phpmyadmin/phpmyadmin/blob/master/CONTRIBUTING.md) document.
- [ ] Make sure you are making a pull request against the correct branch. For example, for bug fixes in a released version use the corresponding QA branch and for new features use the _master_ branch. If you have a doubt, you can ask as a comment in the bug report or on the mailing list.
- [ ] Every commit has proper `Signed-off-by` line as described in our [DCO](https://github.com/phpmyadmin/phpmyadmin/blob/master/DCO). This ensures that the work you're submitting is your own creation.
- [ ] Every commit has a descriptive commit message.
- [ ] Every commit is needed on its own, if you have just minor fixes to previous commits, you can squash them.
- [ ] Any new functionality is covered by tests.

2019-08-07 21:03 UTC, shucon approved these changes

2019-08-07 21:06 UTC, shucon requested changes
Please fix the failed Travis tests.

2019-08-20 12:08 UTC, williamdes commented
@kartik1000 how can I test your PR ?
can you please fix the `Fixes #15420` link in the description ?

2019-08-20 12:14 UTC, kartik1000 commented
I fixed the description, sorry for the problem.

2019-08-20 12:21 UTC, williamdes requested changes
@kartik1000 did you forget to commit the front-end part ?

2019-08-20 12:23 UTC, kartik1000 commented
Oh shit, yes you are right. I'll fix that by night. I am really sorry for it

2019-08-22 23:01 UTC, williamdes requested changes

2019-08-22 23:01 UTC, williamdes commented on templates/columns_definitions/column_definitions_form.twig
> +        <input type="checkbox" name="online_transaction" value="Online_Transaction" id="transaction"><label for="transaction" style="font-weight:bold;">Online Transaction</label>
```
<input type="checkbox" name="online_transaction" value="Online_Transaction" id="transaction"><label for="transaction" style="font-weight:bold;">{% trans 'Online Transaction' %}</label>
```

Please make it translatable and try to remove inline styles ;)

2019-09-14 10:15 UTC, kartik1000 commented
@williamdes Made the change, please review :)

2019-09-14 10:52 UTC, williamdes approved these changes
@mauriciofauth can you please review this PR?

I wonder if value= should bee translated or have another value?

2019-09-15 05:27 UTC, kartik1000 commented
@williamdes I think I will translate value anyway in case someone else uses it in future. :)

2019-11-02 08:57 UTC, nunoperalta commented
Hey! Thanks very much for developing this. Anything stopping this, or can this get live soon?
Thanks - have a great day!

2020-01-01 12:01 UTC, williamdes approved these changes
LGTM

2020-01-01 12:04 UTC, williamdes commented
Thank you for your work @kartik1000 !
I fixed an bug and rebased onto `QA_5_0`

2020-01-16 20:49 UTC, williamdes commented
@kartik1000 I now rebased on master branch :sweat_smile: in order to merge it ASAP
See comments on the issue, I was ready to merge before the comment
Maybe the PR needs a server and version check

2020-01-16 20:56 UTC, kartik1000 commented
Yes @williamdes. I will add server and version check. I shall then add for MySQL as well. Right?

2020-01-16 21:10 UTC, williamdes commented
> I shall then add for MySQL as well. Right?

Yes, right

Also please be sure to hard reset your local copy to c0a378b822631541bb85b0ac95546a11f9285817

2020-01-17 08:08 UTC, kartik1000 commented
@williamdes I have made the changes. Please Review

2020-01-17 09:33 UTC, nunoperalta commented
Looks good to me.
Thank you very much!

2020-01-17 13:11 UTC, merged

2020-01-17 13:11 UTC, williamdes commented
Thank you so much for your work and patience !

2020-01-17 13:34 UTC, nunoperalta commented
I was reading further, and it appears that ALTER ONLINE is actually equivalent to LOCK=NONE:

https://mariadb.com/kb/en/alter-table/#alter-online-table


It doesn't mean it's wrong to do ALGORITHM=INPLACE, but maybe the most correct way to do it, which also works with MySQL is:

ALGORITHM=INPLACE, LOCK=NONE

That's the best way to do it, from what I'm reading.

Is it easy to create a new PR to add this small thing?

Sorry for the several changes! :)

2020-01-17 13:37 UTC, kartik1000 commented
Yes sure @nunoperalta. @williamdes Shall I make a new PR to add LOCK = NONE? My fault as well I should have added that initially only 😞 .

2020-01-17 13:54 UTC, williamdes commented
Yes, please open a PR so we can discuss it

2020-01-17 14:26 UTC, nunoperalta commented
No one's fault! We learn as we go. I appreciate your patience.