Display an error when trying to import in designer a table that's already imported
phpmyadmin/phpmyadmin pull request #15452
Opened 2019-08-21 21:07 UTC by Tithugues

It's currently possible to add many times the same table in the designer. This should not be allowed.

I used an existing message… Please tell me if a new one should be used and how to do it.

Thank you.

2019-08-21 21:35 UTC, williamdes approved these changes
LGTM :100:

2019-08-22 07:47 UTC, williamdes commented on js/messages.php
> +$js_messages['strTableAlreadyExists'] = __('Table %s already exists!');
```suggestion
$js_messages['strTableAlreadyExists'] = _pgettext('The table already exists in the designer and can not be added once more.', 'Table %s already exists!');
```

2019-08-22 07:48 UTC, williamdes requested changes
I added a suggestion to add context for translators, do you agree ?

2019-08-22 08:04 UTC, Tithugues commented on js/messages.php
> +$js_messages['strTableAlreadyExists'] = __('Table %s already exists!');
Honnestly, I don't really know the impact of this change. I looked at the `_pgettext` function, but don't really this the need for the context.
So I'll rely on you and commit your suggestion.

2019-08-22 11:57 UTC, williamdes commented on js/messages.php
> +$js_messages['strTableAlreadyExists'] = __('Table %s already exists!');
The impact is that the translators know what they are translating
https://github.com/phpmyadmin/phpmyadmin/blob/a2308ee965b70d77d74f3570f60cc6fba9580637/po/phpmyadmin.pot#L912
![image](https://user-images.githubusercontent.com/7784660/63512654-a61cbe80-c4e4-11e9-979a-0af94a46ec98.png)
https://hosted.weblate.org/translate/phpmyadmin/4-9/fr/?checksum=&offset=1&q=Table&search=exact&type=translated&ignored=&date=&only_user=&exclude_user=

2019-08-22 22:58 UTC, merged