FIX: [UI] Text area overflows its parent element #15161
phpmyadmin/phpmyadmin pull request #15478
Opened 2019-09-27 15:48 UTC by ecordoba24

FIX: [UI] Text area overflows its parent element #15161

2019-09-28 00:39 UTC, MauricioFauth requested changes

2019-09-28 00:39 UTC, mauriciofauth commented on libraries/classes/Database/Qbe.php
> +        $html_output .= '<textarea style="width: 98%;" cols="80" name="sql_query" id="textSqlquery"'
Could you move this to a CSS file instead of using inline styles?

2019-10-17 22:05 UTC, williamdes commented
Sorry but I merged #15342 since this PR does not have a valid Signed-Off-By line and has debug code.

2019-10-17 22:05 UTC, closed without merging

2019-10-17 22:06 UTC, williamdes commented
Maybe you can try to solve another issue :)