Fix composer usage in setup docs and fix some English rules and typos
phpmyadmin/phpmyadmin pull request #15518
Opened 2019-10-21 18:29 UTC by seyfer

### Description

Fix composer usage in setup docs and fix some English rules and typos

Composer installation must be done with `composer install`, not `composer update`. 
Because `update` updates `composer.lock` file, which should be updated only in case of dependency change (add, remove, version).
`composer install` just installs versions preserved in  `composer.lock`.

2019-10-21 22:50 UTC, ibennetch requested changes
Hi, thanks for your contributions. I appreciate your input on these items.

I have a few comments in-line but overall think you made some great impovements.

I'd like to keep the Composer change as a separate commit so we can see in the commit history that it's a distinct change from the grammar improvements.

2019-10-21 22:50 UTC, ibennetch commented on CONTRIBUTING.md
> +You can triage issues that may include reproducing bug reports or asking for vital information, such as version numbers or reproduction instructions. If you would like to start triaging issues, one e
I don't love this change, but think it needs a comma before "which"

2019-10-21 22:50 UTC, ibennetch commented on doc/setup.rst
> +Gentoo ships the phpMyAdmin package, both in a near-stock configuration as well
👍

2019-10-21 22:50 UTC, ibennetch commented on doc/setup.rst
> +    It allows you to enter a database server hostname on login form.
I'd prefer to leave this as it is; in a short list such as these variables are I think there's no benefit to adding "It" here other than making the sentence a bit longer.

2019-10-21 22:50 UTC, ibennetch commented on doc/setup.rst
>  ------------------
Could you extend the dashes `----` to match the new line length?

2019-10-21 22:50 UTC, ibennetch commented on doc/setup.rst
> +Debian and Ubuntu have changed the way how the setup is enabled and disabled, in a way
I think this could be improved a bit further with "...have changed the way in which the setup script is enabled..."

2019-10-21 22:50 UTC, ibennetch commented on doc/setup.rst
> +The Handbook covers this topic in the chapter `Validating other keys on your public
I think something went wrong here, but I think it originally made sense. Now it seems to say "The GNU Privacy The Handbook" which doesn't sound right.

2019-10-21 22:50 UTC, ibennetch commented on doc/setup.rst
> +    This way you will not leave any old no longer working code in the directory,
I think this can also be improved, what about "This way, you will not leave any old or outdated files in the directory," ?

2019-10-21 22:51 UTC, ibennetch commented
About the Composer change, we had some previous discussion about it at #14338 but it seems this is the better way to handle the matter.

2019-10-21 22:57 UTC, ibennetch commented
Also, these changes should probably target QA_4_9 if possible.

2019-10-22 06:11 UTC, seyfer commented on doc/setup.rst
>  ------------------
@ibennetch sure

2019-10-22 06:34 UTC, seyfer commented
@ibennetch thank you for review.

I have left a comment in #14338 with an explanation of why I agree on this change. I will remove it here.

One question, how can I know that `QA_4_9` branch designated for docs changes? Is there a description somewhere for each QA branch? :)

2019-10-22 06:47 UTC, seyfer commented
@ibennetch I have checked `QA_4_9`, it seems outdated. For example, in `CONTRIBUTING` the whole section `Triage issues` is missing.

2019-10-26 14:59 UTC, MauricioFauth approved these changes

2019-10-26 16:10 UTC, williamdes approved these changes

2019-11-01 22:07 UTC, ibennetch approved these changes
Thanks! Nice work.

I'm pleased with this work, but our history makes rebasing this in to QA_4_9 somewhat time-consuming, as QA_4_9 and master have diverged in several ways.

We (or you) should squash this to one commit before merging, perhaps also fixing up the commit message which now no longer should reference composer.

Since we're approaching the release of 5.0, I'm considering merging this only in to master, rather than the QA branch. @williamdes what do you think?

2019-11-01 22:19 UTC, ibennetch commented
@seyfer We do explain which branch a pull request should target in the developer documentation here, https://github.com/phpmyadmin/phpmyadmin/wiki/Developer_guidelines#branches-in-git — but I'll be the first to admit this isn't the first place people look. If you have any suggestion about how to make this more clear for new developers, please let us know.

In general, QA_4_9 is where we put bug fixes (this then merges in to QA_5_0. QA_5_0 in turn merges in to master). New features go in to master. This way we can generate releases 4.9.x from QA_4_9, 5.0.x from QA_5_0, and 5.1 development occurs in master. Once we reach the end of life for 4.9, this will improve a bit and we'll only have to worry about QA_5_0 and master.

2019-11-01 23:10 UTC, williamdes commented
> Since we're approaching the release of 5.0, I'm considering merging this only in to master, rather than the QA branch. @williamdes what do you think?

I think all QA branches should benefit from clean documentation, I can handle the merge to QA branches

2019-11-03 14:10 UTC, seyfer commented
Thank you for the explanation. 
I did the commits squash and fixed the commit message.

If it is hard to change the base branch for this PR, I see another option.
Maybe it will be easier for you to close this PR and apply changes manually or create a new one in a proper branch? I'm totally fine with it. :)

2019-11-03 14:21 UTC, williamdes commented
@seyfer I agree that you rebase on `QA_4_9` and add the triage section, your version wins the conflicts.

If you prefer tell me and I will do it ;)

2019-11-03 14:22 UTC, williamdes commented
A simple way would be to do:
```bash
git reset --hard 2dbaa6f3d984c8f467b462ea2f9e157794813a86
git cherry-pick 3c924e5a162d3b0e5a0e6bb740198e3e23939619
# Fix conflicts
git push -f 
```

2019-11-03 15:37 UTC, ibennetch commented
The problem here is that there were to changes to CONTRIBUTING.md that applied to master but not QA_4_9. One adding the Code Triage section and the other adding a semicolon to an SQL statement. Those changes prevent a clean cherry pick of this whole change set.

I was working on cherry picking those changes back to QA, squashing all these commits, and applying these to QA but didn’t finish yet because it was a rather lengthy process consisting of multiple steps of manual work.

2019-11-09 15:52 UTC, williamdes approved these changes

2019-11-09 15:54 UTC, merged

2019-11-09 15:58 UTC, williamdes commented
Thanks for your contribution @seyfer !
Merged as 4570e2f906ef051ebbca961d0d6c4d50a888e077 in `QA_4_9` and 685eeaf9a5e5252b5b94a3283e63cfa91dd17544 in `QA_5_0`

Also 580fca0d26ad648755d7ba9fa5b2b18f87859234 on master