extract twig for TextImageLinkTransformationsPlugin method and fix test #14801
phpmyadmin/phpmyadmin pull request #15533
Opened 2019-10-27 13:55 UTC by seyfer

Signed-off-by: Oleg Abrazhaev <seyferseed@gmail.com>

### Description

* extract twig for TextImageLinkTransformationsPlugin method and fix test

Please describe your pull request.

Fixes #

Before submitting pull request, please review the following checklist:

- [x] Make sure you have read our [CONTRIBUTING.md](https://github.com/phpmyadmin/phpmyadmin/blob/master/CONTRIBUTING.md) document.
- [x] Make sure you are making a pull request against the correct branch. For example, for bug fixes in a released version use the corresponding QA branch and for new features use the _master_ branch. If you have a doubt, you can ask as a comment in the bug report or on the mailing list.
- [x] Every commit has proper `Signed-off-by` line as described in our [DCO](https://github.com/phpmyadmin/phpmyadmin/blob/master/DCO). This ensures that the work you're submitting is your own creation.
- [x] Every commit has a descriptive commit message.
- [x] Every commit is needed on its own, if you have just minor fixes to previous commits, you can squash them.
- [x] Any new functionality is covered by tests.

2019-10-27 13:56 UTC, williamdes approved these changes

2019-10-28 12:34 UTC, MauricioFauth requested changes

2019-10-28 12:34 UTC, mauriciofauth commented on libraries/classes/Plugins/Transformations/Abs/TextImageLinkTransformationsPlugin.php
> +            'buffer' => htmlspecialchars($buffer),
You don't need to pre-escape the variables here.

2019-10-30 01:47 UTC, MauricioFauth approved these changes

2019-10-30 01:47 UTC, merged

2019-10-30 01:47 UTC, mauriciofauth commented
Merged, thanks for your contribution!