use twig in Structure and Variables controller and add missing tests #14801
phpmyadmin/phpmyadmin pull request #15534
Opened 2019-10-27 17:03 UTC by seyfer

Signed-off-by: Oleg Abrazhaev <seyferseed@gmail.com>

### Description

* use twig templates in two controllers
* add missing tests
* minor fixes btw

Before submitting pull request, please review the following checklist:

- [x] Make sure you have read our [CONTRIBUTING.md](https://github.com/phpmyadmin/phpmyadmin/blob/master/CONTRIBUTING.md) document.
- [x] Make sure you are making a pull request against the correct branch. For example, for bug fixes in a released version use the corresponding QA branch and for new features use the _master_ branch. If you have a doubt, you can ask as a comment in the bug report or on the mailing list.
- [x] Every commit has proper `Signed-off-by` line as described in our [DCO](https://github.com/phpmyadmin/phpmyadmin/blob/master/DCO). This ensures that the work you're submitting is your own creation.
- [x] Every commit has a descriptive commit message.
- [x] Every commit is needed on its own, if you have just minor fixes to previous commits, you can squash them.
- [x] Any new functionality is covered by tests.

2019-10-28 06:56 UTC, williamdes approved these changes

2019-10-28 14:18 UTC, ibennetch approved these changes
Looks great to me, thank you.

Requested additional review from Maurício, our Twig expert.

2019-10-28 14:47 UTC, MauricioFauth requested changes

2019-10-28 14:47 UTC, mauriciofauth commented on templates/database/structure/overhead.twig
> +<a href="{{ url }}" id="overhead">
I think it's better to call the function inside the template:
```suggestion
<a href="{{ url('/table/structure', table_url_params) }}#showusage" id="overhead">
```

2019-10-28 14:47 UTC, mauriciofauth commented on libraries/classes/Controllers/Database/StructureController.php
> +                        'url' => Url::getFromRoute('/table/structure', $tableUrlParams) . '#showusage',
I think it's better to call the function inside the template:
```suggestion
                        'table_url_params' => $tableUrlParams,
```

2019-10-28 14:47 UTC, mauriciofauth commented on libraries/classes/Controllers/Server/VariablesController.php
> +                                ),
You don't need to escape the variables with `htmlspecialchars` here.

2019-10-28 17:56 UTC, seyfer commented on libraries/classes/Controllers/Server/VariablesController.php
> +                                ),
@mauriciofauth it was in the code before, so I kept it. Shall I remove it?

2019-10-28 17:58 UTC, seyfer commented on libraries/classes/Controllers/Server/VariablesController.php
> +                                ),
ah true, Twig does it :+1:

2019-10-30 01:48 UTC, MauricioFauth approved these changes

2019-10-30 01:48 UTC, merged

2019-10-30 01:48 UTC, mauriciofauth commented
Merged, thanks for your contribution!