Fix a lot of bug and assertions in and around the Designer feature
phpmyadmin/phpmyadmin pull request #15586
Opened 2019-11-24 00:01 UTC by williamdes

### Description

Stupid assertions I remove:
- A table name never contains a dot
- A database name never contains a dot
- A table name never contains a coma
- A database name never contains a coma
- A table name never contains very special chars
- A database name never contains very special chars
- That only one database is displayed in the designer

To fix all that and more I had to:
- use URL/HTML safe identifiers
- remove very old (10+ years) that became over the year very bad code
- Change the structure of the `contr` object in designer
- Add classes
- Improve translation support
- Improve the twig template
- Remove globals
- Fix designer offline feature

2019-11-24 00:02 UTC, williamdes commented
A lot of work is needed to fix all the left bugs and stupid assertions, but still a review can be useful :)

2019-11-24 00:19 UTC, mauriciofauth commented on libraries/classes/Database/Designer/Common.php
> +        $scriptContr = [];
What _contr_ means?

2019-11-24 00:19 UTC, williamdes commented on libraries/classes/Database/Designer/Common.php
> +        $scriptContr = [];
Contraints

2019-11-24 00:23 UTC, mauriciofauth commented on libraries/classes/Database/Designer/Common.php
> +        $scriptContr = [];
Thanks. Since you are adding a new variable here, could you use the full word?

2019-11-24 00:31 UTC, williamdes commented on libraries/classes/Database/Designer/Common.php
> +        $scriptContr = [];
Yes, good idea!

2019-12-07 21:46 UTC, williamdes commented
List of manual tests to be done:
- [ ] on one table
   - [ ] close, expand, close, expand
   - [ ] click on browse structure
   - [ ] move it around
   - [ ] try to do monkey clicking and moving around
   - [ ] click on columns names like a monkey

- [ ] designer
   - [ ] click at random empty places
- [ ] Features
   - [ ] Anchor, de anchor test menu
   - [ ] Move menu from left to right
   - [ ] Close all tables and check that the links are correctly placed, repeat the process 2+ times
   - [ ] Enable angular links, look at the result, repeat the process 2+ times
   - [ ] Enable grid mode, move a table and feel the grid effect, disable feel the non grid effect, repeat the process 2+ times
   - [ ] Click help, get help in another tab and close it
   - [ ] Monkey click on reload and have a look at the result
   - [ ] Having display features disabled, change "shown" column, see the error message and the pink field changing places, <kbd>F5</kbd> and see that the pink field did not change places
   - [ ]  Having display features disabled, change "shown" column on a already pink column, see the error message and the pink field that disapears, <kbd>F5</kbd> and see that the pink field did not change places
   - [ ]  Click new table and be redirected to a new table, go back to designer
   - [ ]  Enter and quit full screen mode, repeat the process 1+ times
   - [ ]  Enter and quit full screen mode, observe the icon changing, repeat the process 1+ times
   - [ ]  Click on "show/hide" tables button, be sure it is shown, hide it, repeat the process 1+ times
   - [ ]  Click on "show/hide" tables button, observe icon changing, hide it, observe icon changing to original state, repeat the process 1+ times
   - [ ]  Save page, title must have changed to page name
   - [ ]  Delete page from previously saved page name in the list, have a success message, try another time, no more page of the name in list
   - [ ]  :warning: Bug to fix: page name is still as if it was saved
   - [ ]  Save page as with a new name without selecting "create a new page", ...
   - [ ] :rotating_light: Save page as with a new name without selecting "create a new page", CRASH
   - [ ]   Save page as with a new name with selecting "create a new page"
   - [ ]  :warning: Bug to fix: page name is not changed
   - [ ]  :rotating_light: Bug to fix: contents are empty, all tables are gone
   - [ ]  Add new tables from another DB, title is now unsaved, save
   - [ ]  Add new tables from another DB, title is now unsaved, try adding the same tables from the same DB, a message is shown
   - [ ]  :warning: Bug to fix: no message
   - [ ]  Click on the ball at the end of a relation line, line is colored in red, "cancel", line is in original color
   - [ ] New page, modal shows, accept not saving, the designer is like "reloaded"
   - [ ] New page, modal shows, accept saving, fill the name, the designer is like "reloaded", try to delete saved page
  - [ ] New page, modal shows, choose cancel, nothing more is done
  - [ ] Show table list, click on  hide all, show all, repeat the process 1+ times
  - [ ] Show table list, click on hide all, all checkbox unchecked, show all, , all checkbox checked, repeat the process 1+ times
  - [ ] Show table list, click on hide all, icon changes, show all, icon changes, repeat the process 1+ 
times
  - [ ] Show table list, click on hide tables without relations, all tables without relations hidden, show them back, repeat the process 1+ times
  - [ ] Show table list, click on hide tables without relations, icon changes, show them back, icon changes
  - [ ] On table list, uncheck a table, table and relations are hidden, check the box, all is back
  - [ ] On table list, click on structure bolt icon, you are redirected, go back to designer
  - [ ] On table list, hide all, check on table of a relation, no relation shown but only the table, check the other table, you now have 2 tables and a relation
  - [ ]  :warning: Minor bug: On table list, hide all, check all back by hand, icon did not change (this is a UI bug)
  - [ ] Table list is open, add a new table from the list, new table is listed and checked
  - [ ] Table list is open, add a new table from the list, total tables increments by one
  - [ ] Try hiding the new table and browsing the structure

_I will update this message, but the main features are listed here_

2021-03-12 16:59 UTC, williamdes commented
@sudo-robot deploy

2021-03-12 17:13 UTC, williamdes commented
@sudo-robot deploy

2021-03-19 16:51 UTC, mauriciofauth approved these changes

2021-03-19 16:51 UTC, mauriciofauth commented on libraries/classes/Database/Designer/Common.php
> +            while ($row = $GLOBALS['dbi']->fetchAssoc($fieldsRs)) {
Is there a reason to replace `$this->dbi` with `$GLOBALS['dbi']`?

2021-03-20 01:48 UTC, williamdes commented on libraries/classes/Database/Designer/Common.php
> +            while ($row = $GLOBALS['dbi']->fetchAssoc($fieldsRs)) {
Probably not, seems like a rebase mistake

2021-06-11 22:32 UTC, williamdes commented
DO NOT MERGE THIS.

I will take my work and push it to main branch little by little after checking it does not break anything

2021-06-15 19:31 UTC, williamdes commented on js/src/designer/page.js
> +                    if (typeof callback !== 'undefined') {
unclear why this change is there

2021-07-14 18:19 UTC, mauriciofauth requested changes

2021-07-14 18:19 UTC, mauriciofauth commented on libraries/classes/Database/Designer/Common.php
> +        $alltab_rs = $GLOBALS['dbi']->query(
```suggestion
        $alltab_rs = $this->dbi->query(
```

2021-07-14 18:19 UTC, mauriciofauth commented on libraries/classes/Database/Designer/Common.php
> +        while ($val = @$GLOBALS['dbi']->fetchRow($alltab_rs)) {
```suggestion
        while ($val = @$this->dbi->fetchRow($alltab_rs)) {
```

2021-07-14 18:19 UTC, mauriciofauth commented on libraries/classes/Database/Designer/Common.php
> +        $tabPositions = (array) $GLOBALS['dbi']->fetchResult(
```suggestion
        $tabPositions = (array) $this->dbi->fetchResult(
```

2021-07-14 18:19 UTC, mauriciofauth commented on libraries/classes/Database/Designer/DesignerColumn.php
> + */
This can be removed.

2021-07-14 18:19 UTC, mauriciofauth commented on libraries/classes/Database/Designer/DesignerColumn.php
> + */
This can be removed.

2021-07-14 18:19 UTC, mauriciofauth commented on libraries/classes/Database/Designer/DesignerColumn.php
> +    public function jsonSerialize()
```suggestion
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
```

2021-07-14 18:19 UTC, mauriciofauth commented on libraries/classes/Database/Designer/DesignerForeignKey.php
> +    public function jsonSerialize()
```suggestion
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
```

2021-07-14 18:19 UTC, mauriciofauth commented on libraries/classes/Database/Designer/DesignerTable.php
> +    public function jsonSerialize()
```suggestion
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
```

2021-07-14 18:19 UTC, mauriciofauth commented on templates/database/designer/database_tables.twig
> +        table_name_base64="{{ table_name_base64 }}"
Is not better to use the `data-*` attributes format?

2025-12-31 10:26 UTC, williamdes commented
Time to get rid of this one, bye 👋🏻

2025-12-31 10:26 UTC, closed without merging

2025-12-31 11:50 UTC, kamil-tekiela commented
Has anything from this PR ever been merged? Should I look into this?

2025-12-31 11:51 UTC, williamdes commented
> Has anything from this PR ever been merged? Should I look into this?

For sure, please look into the diff of this PR

I ported out https://github.com/phpmyadmin/phpmyadmin/pull/18839

But never found the courage to do all the left over diff over again.
Now we have nice readonly stuff etc..
The designer needs to be re-done and not depend on index arrays or horrible stuff I tried to remove