Invalid extension alert and clear input
phpmyadmin/phpmyadmin pull request #15595
Opened 2019-11-25 19:58 UTC by shifatbuet

Signed-off-by: Md Shifaul Islam <shifat.it@gmail.com>

### Description

Invalid extension alert and clear input to upload valid files again. 

Fixes #

Before submitting pull request, please review the following checklist:

- [ ] Make sure you have read our [CONTRIBUTING.md](https://github.com/phpmyadmin/phpmyadmin/blob/master/CONTRIBUTING.md) document.
- [ ] Make sure you are making a pull request against the correct branch. For example, for bug fixes in a released version use the corresponding QA branch and for new features use the _master_ branch. If you have a doubt, you can ask as a comment in the bug report or on the mailing list.
- [ ] Every commit has proper `Signed-off-by` line as described in our [DCO](https://github.com/phpmyadmin/phpmyadmin/blob/master/DCO). This ensures that the work you're submitting is your own creation.
- [ ] Every commit has a descriptive commit message.
- [ ] Every commit is needed on its own, if you have just minor fixes to previous commits, you can squash them.
- [ ] Any new functionality is covered by tests.

2019-11-25 19:59 UTC, shifatbuet commented
Please proceed . Existing flow is ok . Just an alert given for invalid extension. 
Hope this will help.

2019-11-25 20:00 UTC, williamdes commented on js/import.js
> +                'Invalid file format . Valid file format (\'csv\',\'sql\',\'xml\',\'txt\',\'ods\',\'atx\',\'ain\',\'aih\',\'dbf\',\'gz\',\'zip\',\'bz2\')\n');
This fix is only a front-end one, using an extension like [TamperMonkey](https://chrome.google.com/webstore/detail/tampermonkey/dhdgffkkebhmkfjojejmpbldmpobfkfo) I can easily remove this check.

So IMHO you need to do a back-end fix using php code

2019-11-25 20:01 UTC, williamdes requested changes
Please do a php server side check

But this check is restricting users as @ibennetch said

2019-11-25 20:06 UTC, shifatbuet commented on js/import.js
> +                'Invalid file format . Valid file format (\'csv\',\'sql\',\'xml\',\'txt\',\'ods\',\'atx\',\'ain\',\'aih\',\'dbf\',\'gz\',\'zip\',\'bz2\')\n');
Okay.

2019-11-25 20:06 UTC, shifatbuet commented on js/import.js
> +                'Invalid file format . Valid file format (\'csv\',\'sql\',\'xml\',\'txt\',\'ods\',\'atx\',\'ain\',\'aih\',\'dbf\',\'gz\',\'zip\',\'bz2\')\n');
I am working on it. @williamdes

2019-11-25 20:22 UTC, williamdes commented on js/import.js
> +                'Invalid file format . Valid file format (\'csv\',\'sql\',\'xml\',\'txt\',\'ods\',\'atx\',\'ain\',\'aih\',\'dbf\',\'gz\',\'zip\',\'bz2\')\n');
Thank you @shifatbuet

2019-11-25 20:45 UTC, williamdes reviewed
Thank you for the server side fix !

2019-11-25 20:50 UTC, ibennetch commented on js/import.js
> +                'Invalid file format . Valid file format (\'csv\',\'sql\',\'xml\',\'txt\',\'ods\',\'atx\',\'ain\',\'aih\',\'dbf\',\'gz\',\'zip\',\'bz2\')\n');
On the other hand, IMHO, this is really meant to protect a user from an accidental click; there's no real attack vector here that I can see. So doing this on client side would make more sense, so as to save the upload time to the server.

2019-11-25 20:54 UTC, shifatbuet commented on js/import.js
> +                'Invalid file format . Valid file format (\'csv\',\'sql\',\'xml\',\'txt\',\'ods\',\'atx\',\'ain\',\'aih\',\'dbf\',\'gz\',\'zip\',\'bz2\')\n');
Both client side and server side check is done. Please proceed.

2020-01-16 12:52 UTC, williamdes commented
Sorry but I will not merge this PR
IMO users do what they want and if they upload bad files no problem if it does not introduce a security issue.

2020-01-16 12:52 UTC, closed without merging