Extracts HTML from UserPassword.php to twig template #14801
phpmyadmin/phpmyadmin pull request #15610
Opened 2019-12-03 10:43 UTC by victorphoenix3

Signed-off-by: Jayati Shrivastava <gaurijove@gmail.com>

This PR is for extracting HTML from the UserPassword.php to a twig template and continues the work on #14801 .

Before submitting pull request, please review the following checklist:

- [x] Make sure you have read our [CONTRIBUTING.md](https://github.com/phpmyadmin/phpmyadmin/blob/master/CONTRIBUTING.md) document.
- [x] Make sure you are making a pull request against the correct branch. For example, for bug fixes in a released version use the corresponding QA branch and for new features use the _master_ branch. If you have a doubt, you can ask as a comment in the bug report or on the mailing list.
- [x] Every commit has proper `Signed-off-by` line as described in our [DCO](https://github.com/phpmyadmin/phpmyadmin/blob/master/DCO). This ensures that the work you're submitting is your own creation.
- [x] Every commit has a descriptive commit message.
- [x] Every commit is needed on its own, if you have just minor fixes to previous commits, you can squash them.
- [x] Any new functionality is covered by tests.

2019-12-03 12:51 UTC, victorphoenix3 commented
@williamdes This is my first PR. I do not understand why its failing the tests.

2019-12-03 15:59 UTC, MauricioFauth requested changes
Hi. Thanks for your contribution.

2019-12-03 15:59 UTC, mauriciofauth commented on templates/UserPassword.twig
> +<a href="{{ url }} " target="_parent">
You can use the `url` function here instead of using a variable.
```suggestion
<a href="{{ url('/') }}" target="_parent">
```

2019-12-03 16:00 UTC, mauriciofauth commented on libraries/classes/UserPassword.php
> +
You should remove the trailing whitespace here.
```suggestion

```

2019-12-03 16:03 UTC, mauriciofauth commented on libraries/classes/UserPassword.php
> +        echo $template->render('UserPassword', [
We use snake case for template file names.
```suggestion
        echo $template->render('user_password', [
```

2019-12-03 18:18 UTC, williamdes commented
> @williamdes This is my first PR. I do not understand why its failing the tests.

For now the selenium tests can fail for strange reasons (#15154), just do as if they where not failing ;)

2019-12-03 19:53 UTC, williamdes approved these changes

2019-12-03 19:59 UTC, victorphoenix3 commented on libraries/classes/UserPassword.php
> +        echo $template->render('UserPassword', [
fixed the Pr;excuse the silly mistakes...Is there any other change required?

2019-12-04 15:50 UTC, victorphoenix3 commented
@mauriciofauth I have made the required changes.

2019-12-06 15:50 UTC, MauricioFauth approved these changes

2019-12-06 15:50 UTC, merged

2019-12-06 15:51 UTC, mauriciofauth commented
Merged, thanks for your contribution!