Pass
phpmyadmin/phpmyadmin pull request #15616
Opened 2019-12-04 16:44 UTC by victorphoenix3

This PR continues work on #14801 .
HTML from ChangePassword.php has been shifted to twig templates.

- [x] Make sure you have read our [CONTRIBUTING.md](https://github.com/phpmyadmin/phpmyadmin/blob/master/CONTRIBUTING.md) document.
- [x] Make sure you are making a pull request against the correct branch. For example, for bug fixes in a released version use the corresponding QA branch and for new features use the _master_ branch. If you have a doubt, you can ask as a comment in the bug report or on the mailing list.
- [x] Every commit has proper `Signed-off-by` line as described in our [DCO](https://github.com/phpmyadmin/phpmyadmin/blob/master/DCO). This ensures that the work you're submitting is your own creation.
- [x] Every commit has a descriptive commit message.
- [x] Every commit is needed on its own, if you have just minor fixes to previous commits, you can squash them.
- [x] Any new functionality is covered by tests.

2019-12-04 17:00 UTC, victorphoenix3 commented
@williamdes @mauriciofauth This is ready for review.

2019-12-04 18:49 UTC, victorphoenix3 commented on templates/display/change_password/file_a.twig
> +action="{{ action }}" name="chgPassword" class="({{ is_privileges }} ? 'submenu-item' : '')">
@williamdes  @mauriciofauth 
the 'action' variable here is being passed "index.php?route=/server/privileges&amp;amp;lang=en" instead of
 "index.php?route=/server/privileges&amp;lang=en" ;
due to which the assert tests are failing.
How do I fix this?

2019-12-04 18:57 UTC, victorphoenix3 commented on templates/display/change_password/file_a.twig
> +action="{{ action }}" name="chgPassword" class="({{ is_privileges }} ? 'submenu-item' : '')">
@williamdes  @mauriciofauth 
The 'action' variable here is being passed "index.php?route=/server/privileges&amp;amp;lang=en" instead of
"index.php?route=/server/privileges&amp;lang=en" ;
due to which the assert tests are failing.
How do I fix this?

2019-12-04 19:05 UTC, victorphoenix3 commented on templates/display/change_password/file_a.twig
> +action="{{ action }}" name="chgPassword" class="({{ is_privileges }} ? 'submenu-item' : '')">
@williamdes  @mauriciofauth 
The 'action' variable here is being passed "index.php?route=/server/privileges&amp;amp;lang=en" instead of
"index.php?route=/server/privileges&amp;lang=en" ;
due to which the assert tests are failing.
How do I fix this?

2019-12-04 19:49 UTC, victorphoenix3 commented on templates/display/change_password/file_a.twig
> +action="{{ action }}" name="chgPassword" class="({{ is_privileges }} ? 'submenu-item' : '')">
ok fixed

2019-12-06 18:07 UTC, victorphoenix3 commented
@mauriciofauth please do review.

2019-12-11 11:09 UTC, victorphoenix3 commented
@williamdes @mauriciofauth The PR is complete and ready for review.

2019-12-11 12:39 UTC, williamdes approved these changes

2019-12-14 12:59 UTC, MauricioFauth requested changes

2019-12-14 12:59 UTC, mauriciofauth commented on libraries/classes/Display/ChangePassword.php
> +        $template = new Template();
You don't have to create a new Template every time, you can create only one time at the start of the method.

2019-12-14 12:59 UTC, mauriciofauth commented on libraries/classes/Display/ChangePassword.php
> +            'hidden_inputs' => Url::getHiddenInputs(),
You can use the `get_hidden_inputs()` Twig function.

2019-12-14 12:59 UTC, mauriciofauth commented on libraries/classes/Display/ChangePassword.php
> +            'hostname' => htmlspecialchars($hostname),
Twig automatically escapes the variables, so you don't need to use `htmlspecialchars`, otherwise it will be escaped two times.

2019-12-14 12:59 UTC, mauriciofauth commented on libraries/classes/Display/ChangePassword.php
> +                                )->getDisplay(),
For the `Message::notice` you can use the `notice` Twig filter and for `MySQLDocumentation::show` you can use the `show_mysql_docu` Twig function.

2019-12-14 12:59 UTC, mauriciofauth commented on templates/display/change_password/file_a.twig
> +action="({{ is_privileges  }} ? {{url('/server/privileges')}} : {{url('/user_password')}})" name="chgPassword" class="({{ is_privileges }} ? 'submenu-item' : '')">
You have to use the ternary operator inside the curly braces, otherwise you'll just print them. See: https://twig.symfony.com/doc/2.x/templates.html#other-operators

```suggestion
action="{{ is_privileges ? url('/server/privileges') : url('/user_password') }}" name="chgPassword" class="{{ is_privileges ? 'submenu-item' }}">
```

2019-12-14 20:31 UTC, victorphoenix3 commented
@mauriciofauth thanks for reviewing. I have update the PR with the corrections.

2019-12-14 20:33 UTC, victorphoenix3 commented
@mauriciofauth thanks for reviewing. I have updated the PR with the corrections

2019-12-16 13:36 UTC, williamdes approved these changes

2019-12-16 20:32 UTC, MauricioFauth requested changes
A few more small fixes.

2019-12-16 20:32 UTC, mauriciofauth commented on templates/display/change_password/file_a.twig
> +action="({{ is_privileges ? url('/server/privileges') : url('/user_password')}})" name="chgPassword" class="({{ is_privileges ? 'submenu-item' }})">
```suggestion
action="{{ is_privileges ? url('/server/privileges') : url('/user_password') }}" name="chgPassword" class="{{ is_privileges ? 'submenu-item' }}">
```

2019-12-16 20:32 UTC, mauriciofauth commented on templates/display/change_password/file_a.twig
> +    <legend ({{ is_privileges ? ' data-submenu-label="Change password"' }})>{%trans 'Change password' %}</legend>
```suggestion
    <legend{{ is_privileges ? ' data-submenu-label="Change password"' }}>{% trans 'Change password' %}</legend>
```

2019-12-16 20:32 UTC, mauriciofauth commented on templates/display/change_password/file_a.twig
> +{{ get_hidden_inputs()|raw }}
```suggestion
{{ get_hidden_inputs() }}
```

2019-12-16 20:32 UTC, mauriciofauth commented on templates/display/change_password/file_a.twig
> +                 <label for="nopass_1">{%trans 'No Password' %}</label>
```suggestion
                 <label for="nopass_1">{% trans 'No Password' %}</label>
```

2019-12-16 20:32 UTC, mauriciofauth commented on templates/display/change_password/file_a.twig
> +                <label for="nopass_0">{%trans 'Password:' %} &nbsp; </label>
```suggestion
                <label for="nopass_0">{% trans 'Password:' %}&nbsp;</label>
```

2019-12-16 20:32 UTC, mauriciofauth commented on templates/display/change_password/file_a.twig
> +                {%trans 'Enter:'%}&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
```suggestion
                {% trans 'Enter:' %}&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
```

2019-12-16 20:32 UTC, mauriciofauth commented on templates/display/change_password/file_a.twig
> +                {%trans 'Re-type:' %} &nbsp;
```suggestion
                {% trans 'Re-type:' %}&nbsp;
```

2019-12-16 20:32 UTC, mauriciofauth commented on templates/display/change_password/file_b.twig
> +  <td>{%trans 'Password Hashing:' %}</td>
```suggestion
  <td>{% trans 'Password Hashing:' %}</td>
```

2019-12-16 20:32 UTC, mauriciofauth commented on templates/display/change_password/file_b.twig
> +<div ({{ orig_auth_plugin  != 'sha256_password' ? ' class="hide"' }}) id="ssl_reqd_warning_cp">
```suggestion
<div{{ orig_auth_plugin != 'sha256_password' ? ' class="hide"' }} id="ssl_reqd_warning_cp">
```

2019-12-16 20:32 UTC, mauriciofauth commented on templates/display/change_password/file_d.twig
> +    <td>{%trans 'Password Hashing:' %}</td>
```suggestion
    <td>{% trans 'Password Hashing:' %}</td>
```

2019-12-16 20:32 UTC, mauriciofauth commented on templates/display/change_password/file_e.twig
> +<input class="btn btn-primary" type="submit" value="{%trans 'Go' %}">
```suggestion
<input class="btn btn-primary" type="submit" value="{% trans 'Go' %}">
```

2019-12-16 22:20 UTC, victorphoenix3 commented
@mauriciofauth I have updated the PR.

2019-12-16 22:34 UTC, MauricioFauth approved these changes

2019-12-16 22:36 UTC, merged

2019-12-16 22:36 UTC, mauriciofauth commented
Merged, thanks for your contribution!