Double tap to edit on mobile bug solved
phpmyadmin/phpmyadmin pull request #15617
Opened 2019-12-04 17:57 UTC by harsh-kukreja

Signed-off-by: Harsh Kukreja <harshkukreja99@gmail.com>

### Description
Edited the css file and the control flow to solve the double tap zoom in problem on mobile 

Fixes #14411 

Before submitting pull request, please review the following checklist:

- [x] Make sure you have read our [CONTRIBUTING.md](https://github.com/phpmyadmin/phpmyadmin/blob/master/CONTRIBUTING.md) document.
- [x] Make sure you are making a pull request against the correct branch. For example, for bug fixes in a released version use the corresponding QA branch and for new features use the _master_ branch. If you have a doubt, you can ask as a comment in the bug report or on the mailing list.
- [x] Every commit has proper `Signed-off-by` line as described in our [DCO](https://github.com/phpmyadmin/phpmyadmin/blob/master/DCO). This ensures that the work you're submitting is your own creation.
- [x] Every commit has a descriptive commit message.
- [x] Every commit is needed on its own, if you have just minor fixes to previous commits, you can squash them.
- [x] Any new functionality is covered by tests.

2019-12-04 18:14 UTC, williamdes requested changes

2019-12-04 18:14 UTC, williamdes commented on themes/pmahomme/css/common.css.php
> +    touch-action: manipulation;
for the record: https://caniuse.com/#search=touch-action

2019-12-04 18:14 UTC, williamdes commented on package-lock.json
> +{
can you delete the file ?
if you need help I can send you he commands to do ;)

2019-12-04 18:16 UTC, harsh-kukreja commented on package-lock.json
> +{
Yaa that will be helpful

2019-12-04 18:49 UTC, williamdes commented on package-lock.json
> +{
So:
git reset soft before your work, remove the file to avoid future mistakes, commit and force push
```
git reset --soft d8444c18a98f8e37d1f078a9fc95cbd921f0ceca
rm package-lock.json
git commit --signoff ....
git push --force
```

2019-12-04 19:09 UTC, williamdes commented on package-lock.json
> +{
Nope, you seem to have not removed the package-lock when committing or before

2019-12-04 19:13 UTC, harsh-kukreja commented
Please check @williamdes

2019-12-04 19:50 UTC, williamdes commented
@harsh-kukreja you are near to succeed, if you can revert the change you made to package.json ?

2019-12-05 14:45 UTC, harsh-kukreja commented
Hey @williamdes  sorry for the delay please check

2019-12-07 21:36 UTC, harsh-kukreja commented
Hey @williamdes any updates??

2019-12-07 21:50 UTC, williamdes commented
hey @harsh-kukreja sorry for not replying in time to the message, I need to do some more testing when I can take some time
I will keep you updated ASAP

2019-12-07 21:50 UTC, williamdes approved these changes

2019-12-08 13:51 UTC, harsh-kukreja commented
Okay @williamdes

2019-12-18 09:08 UTC, harsh-kukreja commented
Hey @williamdes can you give me the slack workspace link?

2019-12-18 12:56 UTC, williamdes commented
[Slack](https://join.slack.com/t/phpmyadmin/shared_invite/enQtNTQ3ODU0NzExNTExLTVjYTNhOGVjMDdlMzFiZTRkMjBjYjViY2YxNTlkZDE3OTNlNmViMjE2YTg3MTQ2MzQwNTk2ZjI3MzhkNzIzMDY)
[Gitter](https://gitter.im/phpmyadmin/Lobby)

2020-04-25 09:42 UTC, williamdes approved these changes

2020-04-25 09:43 UTC, williamdes commented
@sudo-bot Deploy PR

2020-04-25 09:55 UTC, williamdes commented
@harsh-kukreja I changed your code because it broke the edit a link feature, a minor change

2020-04-25 09:55 UTC, williamdes commented
@sudo-bot deploy PR

2020-04-25 11:26 UTC, merged

2020-04-25 11:31 UTC, williamdes commented
Thank you @harsh-kukreja !