Hotfix/text size too large  #15598
phpmyadmin/phpmyadmin pull request #15611
Opened 2019-12-03 19:18 UTC by shifatbuet

### Description

Text size was too large. Edited css of legend to 13px

Fixes #

Before submitting pull request, please review the following checklist:

- [ ] Make sure you have read our [CONTRIBUTING.md](https://github.com/phpmyadmin/phpmyadmin/blob/master/CONTRIBUTING.md) document.
- [ ] Make sure you are making a pull request against the correct branch. For example, for bug fixes in a released version use the corresponding QA branch and for new features use the _master_ branch. If you have a doubt, you can ask as a comment in the bug report or on the mailing list.
- [ ] Every commit has proper `Signed-off-by` line as described in our [DCO](https://github.com/phpmyadmin/phpmyadmin/blob/master/DCO). This ensures that the work you're submitting is your own creation.
- [ ] Every commit has a descriptive commit message.
- [ ] Every commit is needed on its own, if you have just minor fixes to previous commits, you can squash them.
- [ ] Any new functionality is covered by tests.

2019-12-03 19:19 UTC, shifatbuet commented
please proceed . minor change.

2019-12-03 19:51 UTC, williamdes commented
@shifatbuet I think you can do the following commands
```
git checkout hotfix/text_size_15598
git reset --hard 12db01bfc355915eabe1a23b96e068cfc43d37d4
git cherry-pick 38ad60a6070ad56dfa6d70713e4e307d6585bb8e
git push --force
```

2019-12-03 20:04 UTC, williamdes approved these changes

2019-12-03 20:04 UTC, shifatbuet commented
> 
> 
> @shifatbuet I think you can do the following commands
> 
> ```
> git checkout hotfix/text_size_15598
> git reset --hard 12db01bfc355915eabe1a23b96e068cfc43d37d4
> git cherry-pick 38ad60a6070ad56dfa6d70713e4e307d6585bb8e
> git push --force
> ```



> 
> 
> @shifatbuet I think you can do the following commands
> 
> ```
> git checkout hotfix/text_size_15598
> git reset --hard 12db01bfc355915eabe1a23b96e068cfc43d37d4
> git cherry-pick 38ad60a6070ad56dfa6d70713e4e307d6585bb8e
> git push --force
> ```

done as per your instruction .

2019-12-03 20:04 UTC, williamdes commented
@sudo-bot Deploy pull-request

2019-12-03 20:10 UTC, williamdes commented
![image](https://user-images.githubusercontent.com/7784660/70085839-57b5aa80-1611-11ea-8750-f7d551f0906b.png)

2019-12-03 20:11 UTC, williamdes approved these changes
Solved, thank you @shifatbuet for your contribution !

2019-12-03 20:17 UTC, williamdes commented
@mauriciofauth If you approve the change you can merge :)

2019-12-14 03:22 UTC, rahgurung requested changes
This solves the problem but doesn't solve the reason why the problem was there in first place. Actually in old fixed version font-size was already `1rem`. The problem here is we have to set 
```  
html {
    font-size: 82%;
}
```
so that rem can get the correct size from the root element. This fix (the one I'm suggesting) further creates few more UI bugs which can be easily fixed by changing the respective element's font-size to 1 rem or whatever was there in old fixed version. `rem` should be preferred for global styling.

2019-12-15 14:32 UTC, MauricioFauth requested changes

2019-12-15 14:32 UTC, mauriciofauth commented on themes/pmahomme/scss/_common.scss
> +    font-size: 13px;
We don't want to use the `px` unit here.

2020-01-10 12:40 UTC, williamdes commented
@gurrrung can you fix your work ?

2020-03-11 04:27 UTC, gurrrung commented
This is fixed already, #15816. Thanks for your contribution.

2020-03-11 06:32 UTC, closed without merging