Fix #15619 - Text alignment issue
phpmyadmin/phpmyadmin pull request #15625
Opened 2019-12-06 20:44 UTC by NikhilNagdev

Signed-off-by: Nikhil Nagdev <nnagdev58@gmail.com>

### Description

Created a CSS class `label-structure` for the label tag inside "th" tag in the table(the table which describes structure of the database table). Assigned that class to the label tag.

Fixes #15619

Before submitting pull request, please review the following checklist:

- [x] Make sure you have read our [CONTRIBUTING.md](https://github.com/phpmyadmin/phpmyadmin/blob/master/CONTRIBUTING.md) document.
- [x] Make sure you are making a pull request against the correct branch. For example, for bug fixes in a released version use the corresponding QA branch and for new features use the _master_ branch. If you have a doubt, you can ask as a comment in the bug report or on the mailing list.
- [x] Every commit has proper `Signed-off-by` line as described in our [DCO](https://github.com/phpmyadmin/phpmyadmin/blob/master/DCO). This ensures that the work you're submitting is your own creation.
- [x] Every commit has a descriptive commit message.
- [x] Every commit is needed on its own, if you have just minor fixes to previous commits, you can squash them.
- [x] Any new functionality is covered by tests.

2019-12-06 20:51 UTC, williamdes requested changes

2019-12-06 20:51 UTC, williamdes commented on package-lock.json
> +{
please remove the lock file from your commit, If you need help I can send you commands

2019-12-06 20:51 UTC, williamdes commented on themes/pmahomme/scss/_reboot.scss
> +}
please add a new line at the end of the file

2019-12-06 21:01 UTC, NikhilNagdev commented on package-lock.json
> +{
Yes please it will be helpful

2019-12-06 21:07 UTC, williamdes commented on package-lock.json
> +{
```
# Reset on the previous commit
git reset --soft df127684d47ef9ede3cce5686b654c9ff0a3b30d
# Remove useless lock file
rm package-lock.json
# Do the commit 
git commit --signoff ...
# Force push
git push --force
```

2019-12-06 21:22 UTC, NikhilNagdev commented on themes/pmahomme/scss/_reboot.scss
> +}
Added a new line

2019-12-06 21:26 UTC, williamdes commented on package-lock.json
> +{
You seem to have pushed an empty file named git

2019-12-06 21:36 UTC, NikhilNagdev commented on package-lock.json
> +{
So should i repeat the above steps ?

2019-12-06 21:43 UTC, williamdes commented on package-lock.json
> +{
Yes, please

2019-12-06 21:43 UTC, williamdes commented on package-lock.json
> +{
But `rm git`

2019-12-06 21:58 UTC, williamdes approved these changes

2019-12-06 22:01 UTC, NikhilNagdev commented on package-lock.json
> +{
Thanks :)

2019-12-07 11:01 UTC, williamdes commented on themes/pmahomme/scss/_reboot.scss
> +}
Thank you

2020-01-28 19:24 UTC, williamdes approved these changes

2020-01-28 19:25 UTC, williamdes commented on themes/bootstrap/scss/_common.scss
> +  margin: 0.3rem 0 !important;
@mauriciofauth what do you think about using `!important` in this case ?

2020-02-23 11:15 UTC, mauriciofauth commented on themes/bootstrap/scss/_common.scss
> +  margin: 0.3rem 0 !important;
It is always better to find a solution that don't use it.

2020-02-23 11:16 UTC, mauriciofauth commented on themes/bootstrap/scss/_common.scss
> +  margin: 0.3rem 0 !important;
I think it's possible to find a solution for this case.

2020-02-23 11:24 UTC, mauriciofauth commented on themes/bootstrap/scss/_common.scss
> +  margin: 0.3rem 0 !important;
I don't know if `margin` is the best solution. Looks like a vertical alignment issue.

2020-02-23 12:41 UTC, NikhilNagdev commented on themes/bootstrap/scss/_common.scss
> +  margin: 0.3rem 0 !important;
Can u explain me the issue for using `!important` @mauriciofauth

2020-02-24 14:25 UTC, mauriciofauth commented on themes/bootstrap/scss/_common.scss
> +  margin: 0.3rem 0 !important;
If it only works when you add `!important`, it's because the property is getting overwritten elsewhere. So you need to find where this is happening. The `!important` is only needed for utility classes, which is not this case.

2020-02-24 14:30 UTC, mauriciofauth commented on themes/bootstrap/scss/_common.scss
> +  margin: 0.3rem 0 !important;
Your browser developer tools will help you find where the property is getting overwritten.

2020-04-25 09:20 UTC, williamdes approved these changes
Thank you for your contribution @NikhilNagdev !
I removed the use of a new class and `!important`

2020-04-25 09:24 UTC, merged