Added alert message for extensions required
phpmyadmin/phpmyadmin pull request #15643
Opened 2019-12-11 14:30 UTC by kartik1000

Signed-off-by: Kartik Kathuria <kathuriakartik0@gmail.com>

### Description
.
This will add an alert message if the user is trying to import a file with zip extension or bzip2 extension that the required extensions must be present or enabled to import a zip or bzip2 file. 

Fixes #15328 and #14326 

Before submitting pull request, please review the following checklist:

- [ ] Make sure you have read our [CONTRIBUTING.md](https://github.com/phpmyadmin/phpmyadmin/blob/master/CONTRIBUTING.md) document.
- [ ] Make sure you are making a pull request against the correct branch. For example, for bug fixes in a released version use the corresponding QA branch and for new features use the _master_ branch. If you have a doubt, you can ask as a comment in the bug report or on the mailing list.
- [ ] Every commit has proper `Signed-off-by` line as described in our [DCO](https://github.com/phpmyadmin/phpmyadmin/blob/master/DCO). This ensures that the work you're submitting is your own creation.
- [ ] Every commit has a descriptive commit message.
- [ ] Every commit is needed on its own, if you have just minor fixes to previous commits, you can squash them.
- [ ] Any new functionality is covered by tests.

2019-12-16 20:54 UTC, williamdes commented on js/import.js
> +            $("#alert_message_for_zip").html("<h4>Note: php-zip extension must be enabled to import a zip file else it will result in a blank screen</h4>");
Can you use PMA_Messages ?

2019-12-16 20:55 UTC, williamdes commented on templates/display/import/import.twig
> +            <div class="formelementrow" id="alert_message_for_zip">
you should add a flag or do the warning on the server side

2019-12-24 08:12 UTC, kartik1000 commented on js/import.js
> +            $("#alert_message_for_zip").html("<h4>Note: php-zip extension must be enabled to import a zip file else it will result in a blank screen</h4>");
Definitely. I will switch to that

2019-12-24 08:13 UTC, kartik1000 commented on templates/display/import/import.twig
> +            <div class="formelementrow" id="alert_message_for_zip">
Add a flag where? I don't think I clearly understood you

2019-12-24 10:01 UTC, williamdes commented on templates/display/import/import.twig
> +            <div class="formelementrow" id="alert_message_for_zip">
What I wanted to say is that you could add a hidden input with the value that the user has zip extension enabled
And dl the same for bz2

Then use the input in the js code to show the warning

2020-01-10 06:48 UTC, kartik1000 commented on templates/display/import/import.twig
> +            <div class="formelementrow" id="alert_message_for_zip">
@williamdes  I was wondering if you mean that I should First detect that if the user has zip extension enabled or not and the pass that as a hidden input for alert message. If you mean so, how can I detect wether the user has enabled zip extension or not? What I did was to see if user is importing a zip file then alert him at first that php zip extension needs to be enabled and same for bz2 extension.

2020-01-10 07:00 UTC, williamdes commented on templates/display/import/import.twig
> +            <div class="formelementrow" id="alert_message_for_zip">
php offers the extension_loaded https://www.php.net/manual/en/function.extension-loaded.php function can help you

2020-01-10 07:01 UTC, williamdes commented on templates/display/import/import.twig
> +            <div class="formelementrow" id="alert_message_for_zip">
Let me know if this is enough so you can fix your work @kartik1000

2020-01-10 07:01 UTC, yashrajbothra commented on templates/display/import/import.twig
> +            <div class="formelementrow" id="alert_message_for_zip">
hey @kartik1000 i guess u could use `extension_loaded('zip')` to check extension.

2020-01-10 07:02 UTC, kartik1000 commented on templates/display/import/import.twig
> +            <div class="formelementrow" id="alert_message_for_zip">
Thanks! This will be very helpful! I will implement it in this way then.

2020-01-10 07:18 UTC, kartik1000 commented on templates/display/import/import.twig
> +            <div class="formelementrow" id="alert_message_for_zip">
@williamdes I think this should be enough. in case there is some issue I will let you know. Thanks!

2020-01-11 18:01 UTC, kartik1000 commented
@williamdes, I have made the changes. Please review.

2020-01-11 18:06 UTC, williamdes requested changes
Quite good, added some minor changes

2020-01-11 18:06 UTC, williamdes commented on libraries/classes/Display/Import.php
> +            'extension_not_zip' => $extension_not_zip,
```suggestion
            'extension_not_zip' => extension_loaded('zip'),
```

2020-01-11 18:06 UTC, williamdes commented on libraries/classes/Display/Import.php
> +            'extension_not_bz2' => $extension_not_bz2,
```suggestion
            'extension_not_bz2' => extension_loaded('bz2'),
```

2020-01-11 18:06 UTC, williamdes commented on templates/display/import/import.twig
> +                    {% trans '<strong> Please enable the php zip extension to import a php zip file else it will result in a blank screen </strong>' %}
```suggestion
                   <strong>{% trans 'Please enable the php zip extension to import a php zip file else it will result in a blank screen' %}</strong>
```

2020-01-11 18:06 UTC, williamdes commented on templates/display/import/import.twig
> +                    {% trans '<strong> Please enable the php bz2 extension to import a php bz2 file else it will result in a blank screen </strong>' %}
same here

2020-01-12 07:13 UTC, kartik1000 commented
@williamdes I have made the changes. Please review.

2020-01-12 09:38 UTC, williamdes approved these changes
:100:

2020-01-12 17:13 UTC, williamdes commented
@kartik1000 You mentioned #14326 but I see no implementation for the export page

2020-01-12 17:15 UTC, kartik1000 commented
Oh, I didn't read it was the same as one of the issues was even mentioned in the other. No , the alert is only for import.

2020-01-12 17:17 UTC, williamdes commented
Okay
@mauriciofauth can I please have a review ?

2020-02-18 20:29 UTC, kartik1000 commented
@williamdes @mauriciofauth Can we do a review so that we can look to merge this as this was listed as a high priority issue?

2020-02-18 20:35 UTC, williamdes commented
@kartik1000 Can you add a bit of JS code to show the error only when compression is selected ?
And also add a back-end check ?

2020-02-18 20:41 UTC, kartik1000 commented
@williamdes Ok I will add those checks :)

2020-02-20 19:42 UTC, williamdes approved these changes
:+1:
Maybe you need `yarn run js-lint --fix`

2020-02-24 14:39 UTC, MauricioFauth requested changes

2020-02-24 14:39 UTC, mauriciofauth commented on templates/display/import/import.twig
> +                    <strong>{% trans 'Please enable the php bz2 extension to import a php bz2 file else it will result in a blank screen' %}</strong>
I don't like this message. I prefer to fix the blank page instead of showing this.

2020-02-24 21:17 UTC, williamdes commented on templates/display/import/import.twig
> +                    <strong>{% trans 'Please enable the php bz2 extension to import a php bz2 file else it will result in a blank screen' %}</strong>
I agree, a back-end check + message is required

2020-08-16 23:16 UTC, closed without merging

2020-08-16 23:18 UTC, mauriciofauth commented
Closed by 51b04c9b5c6cb4b88befde2f70c6b25bbe2b8d86. Thanks for your contribution.