[WIP]  prevent resetting of enum fields
phpmyadmin/phpmyadmin pull request #15657
Opened 2019-12-16 11:03 UTC by victorphoenix3

fixes #13864

Signed-off-by: Jayati Shrivastava <gaurijove@gmail.com>

### Description

Please describe your pull request.

Fixes #

Before submitting pull request, please review the following checklist:

- [x] Make sure you have read our [CONTRIBUTING.md](https://github.com/phpmyadmin/phpmyadmin/blob/master/CONTRIBUTING.md) document.
- [x] Make sure you are making a pull request against the correct branch. For example, for bug fixes in a released version use the corresponding QA branch and for new features use the _master_ branch. If you have a doubt, you can ask as a comment in the bug report or on the mailing list.
- [x] Every commit has proper `Signed-off-by` line as described in our [DCO](https://github.com/phpmyadmin/phpmyadmin/blob/master/DCO). This ensures that the work you're submitting is your own creation.
- [x] Every commit has a descriptive commit message.
- [x] Every commit is needed on its own, if you have just minor fixes to previous commits, you can squash them.
- [x] Any new functionality is covered by tests.

2019-12-16 21:22 UTC, williamdes approved these changes

2019-12-16 22:24 UTC, victorphoenix3 commented
@williamdes @mauriciofauth The PR is ready for review.

2019-12-16 22:45 UTC, MauricioFauth requested changes

2019-12-16 22:45 UTC, mauriciofauth commented on js/table/change.js
> +                    if ($(this).val() === $checkedValue) {
ESLint found 1 error:
https://travis-ci.org/phpmyadmin/phpmyadmin/jobs/625894283#L404
```
Function declared in a loop contains unsafe references to variable(s) '$checkedValue'  no-loop-func
```
You can run ESLint yourself with the command:
```
yarn run js-lint
```

2019-12-16 22:55 UTC, victorphoenix3 commented on js/table/change.js
> +                    if ($(this).val() === $checkedValue) {
How do i sidestep this? I had to declare a new variable to $checkedValue to store the value of the enum field of the last row since it is lost during cloning.

2019-12-16 22:56 UTC, victorphoenix3 commented on js/table/change.js
> +                    if ($(this).val() === $checkedValue) {
@mauriciofauth

2019-12-17 09:51 UTC, victorphoenix3 commented
@williamdes  @mauriciofauth that js-lint error got fixed by defining the function outside the loop. Its ready for review.

2019-12-17 22:46 UTC, williamdes approved these changes
LGTM

I loved the GIFs that you made to show the change :100:

2020-01-13 16:33 UTC, victorphoenix3 commented
@williamdes  is this ready for merge?

2020-01-19 14:34 UTC, merged

2020-01-19 14:36 UTC, williamdes commented
Thank you @victorphoenix3 for your patience and contribution !
Works fine now :tada: