SSL message removed when server is local. (#15584)
phpmyadmin/phpmyadmin pull request #15673
Opened 2019-12-19 06:32 UTC by Jaideep-97

Signed-off-by: JAIDEEP DATTA <34120588+Jaideep-97@users.noreply.github.com>

### Description

SSL message removed when server is local.

Fixes #

15584

2019-12-19 16:07 UTC, ibennetch requested changes
Overall I think this is a good idea.

Your pull request has a lot of extra files that aren't needed as part of this submission, can you remove the files composer-setup.php, composer.phar, and yarn-error.log?

2019-12-19 16:07 UTC, ibennetch commented on templates/home/index.twig
> +          {%  if(database_server.host !="Localhost via UNIX socket") %}
I think this indentation looks to be not ideal; I think you should line up the `{%` in line with the `</li`> above it, then one space before `if` (the newline is fine, though).

@mauriciofauth what do you think?

2019-12-19 16:07 UTC, ibennetch commented on templates/home/index.twig
> +          {%  if(database_server.host !="Localhost via UNIX socket") %}
I don't think this test will work due to translations. For example, in German this message is shown as "Server-Verbindung: SSL wird nicht verwendet"

2019-12-19 16:07 UTC, ibennetch commented on templates/home/index.twig
> +          {%  if(database_server.host !="Localhost via UNIX socket") %}
I wonder what would happen with Windows using a named pipe. I don't have a Windows MySQL installation to check what message is shown, but we could hide the message in the case of a named pipe as well as UNIX socket.

2019-12-19 16:07 UTC, ibennetch commented on templates/sql/query.twig
> +        <legend style="font-size:0.7em;">{{ legend|raw }}</legend>
Looks like you've made a few unrelated changes to this file as well, please revert those.

2019-12-26 22:26 UTC, williamdes commented
The submitter of the issue now agrees that the text should be black https://github.com/phpmyadmin/phpmyadmin/issues/15584#issuecomment-569140761

Thank you for the contribution.

2019-12-26 22:26 UTC, closed without merging