Fixed UI Header bug
phpmyadmin/phpmyadmin pull request #15680
Opened 2019-12-21 15:31 UTC by Gaurav-Punjabi

Fixed UI Header bug by checking the type of query while adding draggable class to the header columns

Signed-off-by: Gaurav Punjabi <gaurav.bpunjabi@gmail.com>

### Description

Please describe your pull request.

Fixes #15656 

Before submitting pull request, please review the following checklist:

- [ ] Make sure you have read our [CONTRIBUTING.md](https://github.com/phpmyadmin/phpmyadmin/blob/master/CONTRIBUTING.md) document.
- [ ] Make sure you are making a pull request against the correct branch. For example, for bug fixes in a released version use the corresponding QA branch and for new features use the _master_ branch. If you have a doubt, you can ask as a comment in the bug report or on the mailing list.
- [ ] Every commit has proper `Signed-off-by` line as described in our [DCO](https://github.com/phpmyadmin/phpmyadmin/blob/master/DCO). This ensures that the work you're submitting is your own creation.
- [ ] Every commit has a descriptive commit message.
- [ ] Every commit is needed on its own, if you have just minor fixes to previous commits, you can squash them.
- [ ] Any new functionality is covered by tests.

2019-12-21 15:31 UTC, williamdes approved these changes

2020-01-10 12:46 UTC, williamdes approved these changes

2020-01-10 12:46 UTC, williamdes commented on libraries/classes/Display/Results.php
> +        if (!$this->__get('is_show')) {
I am unsure if this should be used as a condition, can you let me know how you did determine it was the right one ?

2020-01-12 19:45 UTC, Gaurav-Punjabi commented on libraries/classes/Display/Results.php
> +        if (!$this->__get('is_show')) {
@williamdes  Well, I tried did some debugging and came to know that 'is_show' indicates that the current query that is getting displayed is a show query. Hence we'll add class 'draggable' to only those queries that are other than show.

2020-01-12 19:55 UTC, williamdes commented
@Gaurav-Punjabi can you please fetch and `git reset --hard ca45710430e5a0e0cca294b6eec60b720c71108b` on this branch
While wanting to merge your fix it did not work using `SHOW PROCESSLIST`

2020-01-12 19:56 UTC, williamdes commented on libraries/classes/Display/Results.php
> +        if (!$this->__get('is_show')) {
Okay :)

2020-01-12 19:59 UTC, Gaurav-Punjabi commented
> @Gaurav-Punjabi can you please fetch and `git reset --hard ca45710430e5a0e0cca294b6eec60b720c71108b` on this branch
> While wanting to merge your fix it did not work using `SHOW PROCESSLIST`
Done I hard reset to the given has. What should I do next ?

2020-01-12 20:05 UTC, williamdes commented
> Done I hard reset to the given has. What should I do next ?

You you check your fix ?

See this screenshot:
![image](https://user-images.githubusercontent.com/7784660/72224857-397f8a80-357f-11ea-9ae3-67e42b0b41bc.png)

2020-01-15 17:01 UTC, Gaurav-Punjabi commented
> > Done I hard reset to the given has. What should I do next ?
> 
> You you check your fix ?
> 
> See this screenshot:
> ![image](https://user-images.githubusercontent.com/7784660/72224857-397f8a80-357f-11ea-9ae3-67e42b0b41bc.png)

Done 👍

2020-01-16 21:32 UTC, williamdes requested changes

2020-01-16 21:32 UTC, williamdes commented on libraries/classes/Display/Results.php
> +        $displayParts['sort_lnk']  = (string) '1';
@Gaurav-Punjabi can you explain this change ?

2020-01-16 21:39 UTC, williamdes commented on libraries/classes/Display/Results.php
> +        $displayParts['sort_lnk']  = (string) '1';
![image](https://user-images.githubusercontent.com/7784660/72564921-191e3b80-38b1-11ea-93dd-5bc1bd6f1fd7.png)

2020-02-13 22:20 UTC, williamdes commented
@Gaurav-Punjabi can you please fix this PR ?

2020-02-14 20:12 UTC, Gaurav-Punjabi commented
@williamdes Sure I'll work on this and fix it asap 👍.

2020-04-22 13:35 UTC, closed without merging

2020-04-22 17:06 UTC, williamdes commented
@Gaurav-Punjabi did you delete your PRs because of our very bad review delay ?