Issue 15720
phpmyadmin/phpmyadmin pull request #15727
Opened 2019-12-31 11:48 UTC by yashrajbothra

### Description

1. made a call to markUnsaved function to set asterisk.
2. set value of checkbox only when table is displayed.
3. change tooltip message when clicked

Fixes #15720 

Before submitting pull request, please review the following checklist:

- [ ] Make sure you have read our [CONTRIBUTING.md](https://github.com/phpmyadmin/phpmyadmin/blob/master/CONTRIBUTING.md) document.
- [ ] Make sure you are making a pull request against the correct branch. For example, for bug fixes in a released version use the corresponding QA branch and for new features use the _master_ branch. If you have a doubt, you can ask as a comment in the bug report or on the mailing list.
- [ ] Every commit has proper `Signed-off-by` line as described in our [DCO](https://github.com/phpmyadmin/phpmyadmin/blob/master/DCO). This ensures that the work you're submitting is your own creation.
- [ ] Every commit has a descriptive commit message.
- [ ] Every commit is needed on its own, if you have just minor fixes to previous commits, you can squash them.
- [ ] Any new functionality is covered by tests.

2019-12-31 11:51 UTC, yashrajbothra commented
Hey @williamdes  kindly review the PR

2019-12-31 12:18 UTC, williamdes requested changes

2019-12-31 12:18 UTC, williamdes commented on js/designer/move.js
> +        $(this).attr('title',(i,currentvalue) => { return currentvalue == 'Show' ? 'Hide' : 'Show' });
That will not work using another language than English

2020-01-01 20:33 UTC, yashrajbothra commented on js/designer/move.js
> +        $(this).attr('title',(i,currentvalue) => { return currentvalue == 'Show' ? 'Hide' : 'Show' });
Changed messages to msg variables. Kindly review the PR

2020-01-01 20:52 UTC, williamdes approved these changes

2020-01-01 20:52 UTC, williamdes commented on js/designer/move.js
> +        $(this).attr('title',(i,currentvalue) => { return currentvalue == Messages.strHide ? Messages.strShow : Messages.strHide });
Oh, 2 tings

`=>` https://caniuse.com/#feat=arrow-functions please use a normal function

`==` => `===` can be replaced my a strict equals

2020-01-01 20:53 UTC, williamdes commented on js/designer/move.js
> +    var tableIsChecked = $(tableDom).css('display') == "block" ? "checked" : "";
a strict equals can be used here also

2020-01-01 21:03 UTC, yashrajbothra commented on js/designer/move.js
> +        $(this).attr('title',(i,currentvalue) => { return currentvalue == Messages.strHide ? Messages.strShow : Messages.strHide });
Thanks,I will keep these things in mind.

2020-01-01 21:03 UTC, yashrajbothra commented on js/designer/move.js
> +    var tableIsChecked = $(tableDom).css('display') == "block" ? "checked" : "";
yea sure

2020-01-01 21:04 UTC, yashrajbothra commented on js/designer/move.js
> +    var tableIsChecked = $(tableDom).css('display') == "block" ? "checked" : "";
Do i have to commit and push these changes?

2020-01-01 21:04 UTC, williamdes commented on js/designer/move.js
> +    var tableIsChecked = $(tableDom).css('display') == "block" ? "checked" : "";
Yes

2020-01-01 21:09 UTC, yashrajbothra commented on js/designer/move.js
> +    var tableIsChecked = $(tableDom).css('display') == "block" ? "checked" : "";
Done!

2020-01-01 21:12 UTC, williamdes approved these changes

2020-01-01 21:12 UTC, williamdes commented on js/designer/move.js
> +    var tableIsChecked = $(tableDom).css('display') == "block" ? "checked" : "";
Thank you

2020-01-01 21:19 UTC, williamdes commented
Waiting for the CI and will test your work manually

2020-01-01 21:27 UTC, NKarasek commented
@yashrajbothra @williamdes 
Good job folks and thank you for being so responsive.  I was just about to note that the checkboxes were not being updated with their new title when clicked - but @williamdes did that one line change as I looked at the list of comments.  Again - thanks much - and Happy New Year to you both!!

2020-01-02 05:55 UTC, yashrajbothra commented
Thanks @NKarasek @williamdes and a very Happy New year.

2020-01-15 13:05 UTC, williamdes commented
@Tithugues can you please review this PR ?
You introduced this in #15448 de57539fb71beacba54b18283893ca3cba6f01cf

@yashrajbothra can you check it does not revert #15446 ?

2020-01-15 13:12 UTC, Tithugues commented
It sounds good to me.

2020-01-15 13:53 UTC, yashrajbothra commented
> @yashrajbothra can you check it does not revert #15446 ?

I checked #15446 and as I have only added some changes it will not revert the PR.

2020-01-16 20:41 UTC, merged

2020-01-16 21:08 UTC, williamdes commented
Thank you @yashrajbothra for your contribution !