Update Session.php
phpmyadmin/phpmyadmin pull request #15737
Opened 2020-01-02 22:08 UTC by TechTank

Verify that the session_save_path is writable, may be unwritable due to open_basedir restrictions or directory permissions. An unwritable session directory will cause phpMyAdmin to produce an unrelated error during ajax and page requests that will be hard to diagnose and prevent the normal operation of phpMyAdmin.

---signoff

### Description

Please describe your pull request.

Fixes #

Before submitting pull request, please review the following checklist:

- [ ] Make sure you have read our [CONTRIBUTING.md](https://github.com/phpmyadmin/phpmyadmin/blob/master/CONTRIBUTING.md) document.
- [ ] Make sure you are making a pull request against the correct branch. For example, for bug fixes in a released version use the corresponding QA branch and for new features use the _master_ branch. If you have a doubt, you can ask as a comment in the bug report or on the mailing list.
- [ ] Every commit has proper `Signed-off-by` line as described in our [DCO](https://github.com/phpmyadmin/phpmyadmin/blob/master/DCO). This ensures that the work you're submitting is your own creation.
- [ ] Every commit has a descriptive commit message.
- [ ] Every commit is needed on its own, if you have just minor fixes to previous commits, you can squash them.
- [ ] Any new functionality is covered by tests.

2020-01-02 22:14 UTC, williamdes reviewed
Good idea, but maybe you should use sprintf function to allow translators to use the path

2020-01-02 22:14 UTC, williamdes commented on libraries/classes/Session.php
> +                'Session path "'
```suggestion
                __('Session path "'
```

2020-01-02 22:14 UTC, williamdes commented on libraries/classes/Session.php
> +				. '" is not writable.'
```suggestion
				. '" is not writable.')
```

2020-01-02 22:28 UTC, TechTank commented
Thanks Williamdes. This is my first time using Git, I'm still learning how to use it.

2020-01-02 22:29 UTC, williamdes commented
@TechTank I understand, contributions are very welcome
I will add your signoff and clean the commit for you

2020-01-06 22:30 UTC, williamdes requested changes

2020-01-06 22:30 UTC, williamdes commented on libraries/classes/Session.php
> +        if (! is_writable(session_save_path())) {
https://www.php.net/manual/en/session.configuration.php#ini.session.save-handler

Seems to be empty by default

This pr must also support redis or memcache session handlers

2020-01-27 21:09 UTC, williamdes commented
I will not merge this PR unfortunately, It will break more things as it is.
If you want you can ask me to re-open it so you can do improvements :)

Thank you for contributing

2020-01-27 21:09 UTC, closed without merging