fix #14875 - fix shp filename sanitization and update test
phpmyadmin/phpmyadmin pull request #15753
Opened 2020-01-06 10:56 UTC by bepsvpt

Signed-off-by: bepsvpt <og7lsrszah6y3lz@infinitefa.email>

### Description

Origin sanitization will remove the filename extension and it will result in file not found when loading the content([referece](https://travis-ci.org/phpmyadmin/phpmyadmin/jobs/633026890#L569-L581)).

This pull request fixes shp filename sanitization bug. 

Fixes #14875

Before submitting pull request, please review the following checklist:

- [x] Make sure you have read our [CONTRIBUTING.md](https://github.com/phpmyadmin/phpmyadmin/blob/master/CONTRIBUTING.md) document.
- [x] Make sure you are making a pull request against the correct branch. For example, for bug fixes in a released version use the corresponding QA branch and for new features use the _master_ branch. If you have a doubt, you can ask as a comment in the bug report or on the mailing list.
- [x] Every commit has proper `Signed-off-by` line as described in our [DCO](https://github.com/phpmyadmin/phpmyadmin/blob/master/DCO). This ensures that the work you're submitting is your own creation.
- [x] Every commit has a descriptive commit message.
- [x] Every commit is needed on its own, if you have just minor fixes to previous commits, you can squash them.
- [x] Any new functionality is covered by tests.

2020-01-06 12:08 UTC, williamdes requested changes
Thank you for the fix !
I added a last comment to improve the code

2020-01-06 12:08 UTC, williamdes commented on libraries/classes/Plugins/Import/ImportShp.php
> +                        $dbf_file_name = substr($dbf_file_name, 0, -4);
I would suggest using https://www.php.net/manual/en/function.pathinfo.php

2020-01-06 12:09 UTC, williamdes commented on libraries/classes/Plugins/Import/ImportShp.php
> +                        $cell = trim(strval($record->DBFData[$c[0]]));
```suggestion
                        $cell = trim((string) $record->DBFData[$c[0]]);
```

2020-01-06 13:09 UTC, williamdes approved these changes

2020-01-06 13:09 UTC, williamdes commented
@bepsvpt Do you want to signoff or that I use your changes using my signoff line ?

2020-01-06 13:26 UTC, bepsvpt commented
Hi @williamdes,

You can use your signoff line.

I'm curious about if the repository owner(organization) can not verify the contributer's signed-off. Is there any different between using real name or nickname(fake name)?

2020-01-06 22:48 UTC, closed without merging

2020-01-06 22:52 UTC, williamdes commented
Hi @bepsvpt 

Thank you for your contributions !

I forwarded your question to the team

2020-01-07 01:10 UTC, bepsvpt commented
Thanks a lot. :)