Informing the user about the HEX conversion scheme of Integers
phpmyadmin/phpmyadmin pull request #15779
Opened 2020-01-12 18:03 UTC by thesmallstar

Signed-off-by: Manthan Surkar <manthan.surkar@gmail.com>

### Description

Please describe your pull request.
A note is shown to the user when he tries to apply HEX function on integer.
Cases, like adding multiple integer notes and removing them, is also taken care of. 

![image](https://user-images.githubusercontent.com/42006277/72223328-92f1b480-3593-11ea-9729-9b74a232c7c5.png)

Fixes #15136

Before submitting pull request, please review the following checklist:

- [ ] Make sure you have read our [CONTRIBUTING.md](https://github.com/phpmyadmin/phpmyadmin/blob/master/CONTRIBUTING.md) document.
- [ ] Make sure you are making a pull request against the correct branch. For example, for bug fixes in a released version use the corresponding QA branch and for new features use the _master_ branch. If you have a doubt, you can ask as a comment in the bug report or on the mailing list.
- [ ] Every commit has proper `Signed-off-by` line as described in our [DCO](https://github.com/phpmyadmin/phpmyadmin/blob/master/DCO). This ensures that the work you're submitting is your own creation.
- [ ] Every commit has a descriptive commit message.
- [ ] Every commit is needed on its own, if you have just minor fixes to previous commits, you can squash them.
- [ ] Any new functionality is covered by tests.

2020-01-12 18:06 UTC, williamdes requested changes
I am not sure if adding html that way is the best way to do, but I also do not have a better solution today

2020-01-12 18:06 UTC, williamdes commented on js/table/change.js
> +      "</p>";
Can you add the string to `js/messages.php` and use it here using `Messages.`

2020-01-12 18:23 UTC, thesmallstar commented
@williamdes, Since this is not an error we cannot put this string/note in any error code section.
The following way is referred from the same file, selecting AES_ENCRYPT adds HTML to provide similar functionality. 

I also couldn't find a better way :P, Hope this works.

2020-01-12 18:24 UTC, williamdes requested changes
> I also couldn't find a better way :P, Hope this works.
> The following way is referred from the same file

Okay then :p

You are on the right path ;)
Be sure to run `yarn run js-lint`/`yarn run js-lint --fix`

2020-01-12 18:24 UTC, williamdes commented on js/table/change.js
> +    var newHexInfo =
can you make it oneline

2020-01-12 18:24 UTC, williamdes commented on js/messages.php
> +$js_messages['HexConversionInfo'] = __('HEX function will treat the integer as String while calculating hexadecimal value');
`String` should not have a capital letter ?
```suggestion
/* l10n: Please explain here to translators what they are translating 
$js_messages['HexConversionInfo'] = __('HEX function will treat the integer as string while calculating hexadecimal value');
```

2020-01-12 18:27 UTC, thesmallstar commented
@williamdes Thank you so much for the suggestions, helps us improve :)

2020-01-12 19:00 UTC, williamdes approved these changes

2020-01-12 19:00 UTC, williamdes commented on js/messages.php
> +/*Tip for HEX conversion of Integers*/
```suggestion
/* l10n: Tip for HEX conversion of Integers*/
```

2020-01-12 19:00 UTC, williamdes commented on js/messages.php
> +/*Tip for HEX conversion of Integers*/
@thesmallstar If you remove the comment prefix `gettext` will not extract it

2020-01-12 19:01 UTC, thesmallstar commented on js/messages.php
> +/*Tip for HEX conversion of Integers*/
on it :D

2020-01-12 19:08 UTC, williamdes commented
Looks nice, I would like a team review or point of view before merging

2020-01-13 11:46 UTC, kartik1000 commented
@thesmallstar You can add the notice in <strong> tags to highlight it. Also can't we add a notice only once when the function is selected in more than one columns. Don't makes much sense to keep repeating it again and again. What do you feel @williamdes? Rest everything looks good 😃

2020-01-13 14:11 UTC, williamdes commented
What about adding a validator the adds the message if the input is not considered correct or risky ?

Like the error message when typing text in an int

2020-01-13 14:21 UTC, kartik1000 commented
Yess @williamdes that would not confuse a new user in case the output is correct and we are still giving some notice.  That would be the best.

2020-01-13 15:43 UTC, williamdes commented
I think you will need to use master branch because it seems more like an enhancement to me

2020-01-14 07:44 UTC, thesmallstar commented
@willamdes okay, I am still trying to find the best way to inform the user, I will let you know. @kartik1000 do you have more suggestions?

2020-01-14 08:40 UTC, kartik1000 commented
@thesmallstar I think if you can make the change @williamdes has mentioned that would be the best and it won't require any more changes

2020-05-14 01:01 UTC, MauricioFauth approved these changes
Thanks for your contribution @thesmallstar.

LGTM.
I think this notice should be added in the _master_ branch.

2020-05-14 11:59 UTC, merged

2020-05-14 12:00 UTC, williamdes commented
Thank you @thesmallstar !

2020-05-14 12:00 UTC, williamdes commented
You will need to force push QA_5_0 to the right commit using #15942