Usergroup twig work2
phpmyadmin/phpmyadmin pull request #15796
Opened 2020-01-15 11:41 UTC by tabraiz961

UserGroups.php file extracted HTML to twig templates 

4 twig templates updated in templates/server/user_groups/*.twig

2020-01-15 11:47 UTC, williamdes requested changes
Good work, some minor changes are required

2020-01-15 11:47 UTC, williamdes commented on libraries/classes/Server/UserGroups.php
> +            'user_group_msg' => $userGroupMsg,
you can use `{{ 'Users of \'%s\' user group'|trans|format(userGroup) }}` in twig ;)

2020-01-15 11:47 UTC, williamdes commented on libraries/classes/Server/UserGroups.php
> +            'hidden_inputs' => isset($hidden_inputs)?$hidden_inputs:'',
```suggestion
            'hidden_inputs' => isset($hidden_inputs) ? $hidden_inputs : '',
```

Do not forget to run `composer run phpcbf` before committing

2020-01-15 11:47 UTC, williamdes commented on libraries/classes/Server/UserGroups.php
> +            $editUserGroup = sprintf(__('Edit user group: \'%s\''), htmlspecialchars($userGroup));
same here for twig

2020-01-15 11:47 UTC, williamdes commented on libraries/classes/Server/UserGroups.php
> +//            'user_group' => $userGroup,
```suggestion
```

2020-01-15 11:48 UTC, williamdes commented
Can you mention the twig issue here so it links ?

2020-01-15 12:44 UTC, williamdes approved these changes
LGTM

2020-01-15 12:44 UTC, williamdes commented on libraries/classes/Server/UserGroups.php
> +            $tabDetails[] =$tabDetail;
```suggestion
            $tabDetails[] = $tabDetail;
```

2020-01-15 12:44 UTC, williamdes commented on templates/server/user_groups/user_listings.twig
> +<h2>{{ 'Users of \'%s\' user group'| trans | format(user_group_special_chars) }}</h2>
```suggestion
<h2>{{ 'Users of \'%s\' user group'|trans|format(user_group_special_chars) }}</h2>
```

2020-01-15 12:44 UTC, tabraiz961 commented on libraries/classes/Server/UserGroups.php
> +            'hidden_inputs' => isset($hidden_inputs)?$hidden_inputs:'',
phpcbf gave me tons of fixed files however i pushed only the ones i am working on

2020-01-15 12:45 UTC, tabraiz961 commented on libraries/classes/Server/UserGroups.php
> +            $editUserGroup = sprintf(__('Edit user group: \'%s\''), htmlspecialchars($userGroup));
done

2020-01-15 12:53 UTC, tabraiz961 commented
@williamdes  i dont understand the designer quotes issue given by Travis CI, i fixed it and was reviewed and pushed to QA_5_0 and these changes were not merged in phpmyadmin/master. My pull request should not have conflicted. Correct me please.

2020-01-15 12:55 UTC, williamdes commented on libraries/classes/Server/UserGroups.php
> +            'hidden_inputs' => isset($hidden_inputs)?$hidden_inputs:'',
quite strange
did you `composer update` before ?

2020-01-15 13:16 UTC, williamdes commented
@tabraiz961 can you check the box to allow me to edit your changes please ?

BTW your history does not make sense to me 
![image](https://user-images.githubusercontent.com/7784660/72436713-657a5600-37a1-11ea-9363-f4c2aa1acc86.png)

So I squashed and rebased the changes:
![image](https://user-images.githubusercontent.com/7784660/72436755-7f1b9d80-37a1-11ea-9765-2d6b67a2cd30.png)


If you allow me to push the change I will help you with travis :)

2020-01-15 14:39 UTC, tabraiz961 commented on libraries/classes/Server/UserGroups.php
> +            'hidden_inputs' => isset($hidden_inputs)?$hidden_inputs:'',
> quite strange
> did you `composer update` before ?

no

2020-01-15 18:38 UTC, williamdes commented
@tabraiz961 please run 
```
git fetch --all -p
git checkout usergroup_twig_work2
git reset --hard b427cfae84a7b29c7d20843ed6726bf0fd659316
```
You have one test to fix but it is very easy
https://travis-ci.org/phpmyadmin/phpmyadmin/jobs/637575583#L700

2020-01-16 11:11 UTC, tabraiz961 commented
> @tabraiz961 please run
> 
> ```
> git fetch --all -p
> git checkout usergroup_twig_work2
> git reset --hard b427cfae84a7b29c7d20843ed6726bf0fd659316
> ```
i have run the commands on local. I hope they meant to pull all working remote changes and reset head to a previous commit which is already in sync with remote.

> You have one test to fix but it is very easy
> https://travis-ci.org/phpmyadmin/phpmyadmin/jobs/637575583#L700

This seems to be an issue although i dont fully understand this section but it seems that 
`$dbi->expects($this->exactly(2))
            ->method('fetchAssoc')
            ->willReturnOnConsecutiveCalls(
                [
                    'usergroup' => 'ug',
                    'tab' => 'server_sql',
                    'allowed' => 'Y',
                ],
                false
            );`
in the UserGroupsTest.php, A usergroup(ug) is created with server_sql checkbox checked. So html should also be rendered with the checked="checked" attribute causing the issue. Am i going in the right direction ?

2020-01-16 11:35 UTC, williamdes commented
> i have run the commands on local. I hope they meant to pull all working remote changes and reset head to a previous commit which is already in sync with remote.

It has set your local copy to the remote one, discarding all changes that where made locally before the command

> This seems to be an issue although i dont fully understand this section but it seems that
$dbi->expects($this->exactly(2)) ->method('fetchAssoc') ->willReturnOnConsecutiveCalls( [ 'usergroup' => 'ug', 'tab' => 'server_sql', 'allowed' => 'Y', ], false );
in the UserGroupsTest.php, A usergroup(ug) is created with server_sql checkbox checked. So html should also be rendered with the checked="checked" attribute causing the issue. Am i going in the right direction ?

You seem to have a space problem

First line is what the test wants, second is what you generate, maye consider adjusting the twig template
```diff
+ <input type="checkbox" class="checkall" checked="checked" name="server_sql" value="Y">
- <input type="checkbox" class="checkall"  checked="checked" name="server_sql"  value="Y">
```

2020-01-16 11:39 UTC, tabraiz961 commented
One last thing since the changes are already approved do i need to push the changes for the space problem?

2020-01-16 11:48 UTC, williamdes commented
Yes, please fix this so the tests pass

2020-01-16 12:53 UTC, williamdes approved these changes
Tests pass :heavy_check_mark:

2020-01-16 13:04 UTC, boherm commented on templates/server/user_groups/user_listings.twig
> +<h2>{{ 'Users of \'%s\' user group'| trans | format(user_group_special_chars) }}</h2>
```suggestion
<h2>{{ 'Users of \'%s\' user group' | trans | format(user_group_special_chars) }}</h2>
```

2020-01-16 13:04 UTC, boherm approved these changes

2020-01-16 13:11 UTC, merged

2020-01-16 13:12 UTC, williamdes commented
Thank you @tabraiz961 for your contribution !
Merged as 66b446a13ea76686c03ea7dc5812cc1287e5688a