FormDisplayTemplate function displayInput upgrading with twig templates
phpmyadmin/phpmyadmin pull request #15809
Opened 2020-01-17 17:07 UTC by tabraiz961

### Description

Please describe your pull request.

Fixes #

Before submitting pull request, please review the following checklist:

- [ ] Make sure you have read our [CONTRIBUTING.md](https://github.com/phpmyadmin/phpmyadmin/blob/master/CONTRIBUTING.md) document.
- [ ] Make sure you are making a pull request against the correct branch. For example, for bug fixes in a released version use the corresponding QA branch and for new features use the _master_ branch. If you have a doubt, you can ask as a comment in the bug report or on the mailing list.
- [ ] Every commit has proper `Signed-off-by` line as described in our [DCO](https://github.com/phpmyadmin/phpmyadmin/blob/master/DCO). This ensures that the work you're submitting is your own creation.
- [ ] Every commit has a descriptive commit message.
- [ ] Every commit is needed on its own, if you have just minor fixes to previous commits, you can squash them.
- [ ] Any new functionality is covered by tests.

2020-01-17 17:11 UTC, tabraiz961 commented
signoff remains will push with the next commit.

2020-01-17 19:43 UTC, MauricioFauth requested changes

2020-01-17 19:43 UTC, mauriciofauth commented on libraries/classes/Config/FormDisplayTemplate.php
> +        $pathSpecialChars = htmlspecialchars($path);
Twig automatically escapes special chars, so you don't need to escape `$path` here.

2020-01-21 23:14 UTC, williamdes commented
@tabraiz961 you seem to have to many or strange spaces in your signoff line :)

2020-01-22 01:29 UTC, tabraiz961 commented
> @tabraiz961 you seem to have to many or strange spaces in your signoff line :)

All i had to do was increase the width of sidebar in GitKraken

2020-01-22 09:38 UTC, tabraiz961 commented
Hi @williamdes 
random order test failed. Is this something that i should be worry about.

2020-01-22 09:58 UTC, williamdes commented
> Hi @williamdes
random order test failed. Is this something that i should be worry about.

Hi @tabraiz961 
No, they are failing on master branch before your PR. You can see that they are allowed to fail in `travis-ci.yml`

2020-01-24 21:28 UTC, williamdes approved these changes
Except the htmlspecialchars LGTM

2020-02-13 21:52 UTC, williamdes requested changes

2020-02-13 21:52 UTC, williamdes commented on libraries/classes/Config/FormDisplayTemplate.php
> +        $nameSpecialCharsDecode = htmlspecialchars_decode($name);
Please remove this one :)

2020-02-13 21:56 UTC, williamdes requested changes

2020-02-13 21:56 UTC, williamdes commented on libraries/classes/Config/FormDisplayTemplate.php
> +            'name_special_chars_decode' => $name,
```suggestion
            'name' => $name,
```

2020-02-13 22:11 UTC, williamdes commented on libraries/classes/Config/FormDisplayTemplate.php
> +        $nameId = 'name="' . $path . '" id="'
this change might introduce a security issue, please revert it

2020-02-13 22:11 UTC, williamdes requested changes
LGTM except the function removal :)

2020-02-13 22:18 UTC, williamdes approved these changes

2020-02-14 20:02 UTC, MauricioFauth requested changes

2020-02-14 20:02 UTC, mauriciofauth commented on templates/config/form_display/inputs.twig
> +            <input type="checkbox" name="{{ path }}-userprefs-allow" {{ check|raw }}
```suggestion
            <input type="checkbox" name="{{ path }}-userprefs-allow"{{ opts.userprefs_allow ? ' checked' }}>
```

2020-02-18 15:16 UTC, tabraiz961 commented
Hi @williamdes  i have moved this task to a seperate branch. According to GIT guide.
Is there a way where you can either duplicate or drop these commits? Thanks

2020-02-18 20:42 UTC, williamdes commented
> Hi @williamdes i have moved this task to a seperate branch. According to GIT guide.
> Is there a way where you can either duplicate or drop these commits? Thanks

Hi @tabraiz961 
Can you post a link to the other PR and close this one ?

2020-02-19 14:16 UTC, closed without merging