fixed font sizing
phpmyadmin/phpmyadmin pull request #15816
Opened 2020-01-19 08:22 UTC by gurrrung

Closes #15598 

Used a global styling 1em unit and set font-size to 82% for HTML (it was so in earlier versions)

Signed-off-by: Rahul Gurung <gurungrahul2@gmail.com>

2020-01-19 08:46 UTC, williamdes approved these changes
LGTM

2020-01-19 13:50 UTC, gurrrung commented
The latest commit is for fixing font-size in the login panel where we enter root as the username.

2020-01-19 14:25 UTC, MauricioFauth requested changes

2020-01-19 14:25 UTC, mauriciofauth commented on themes/pmahomme/scss/_common.scss
> +}
This is redundant. This value is already defined in `_variables.scss`.
https://github.com/phpmyadmin/phpmyadmin/blob/d292855d697f4fe52ad0d180b62bfafa05e90cc8/themes/pmahomme/scss/_variables.scss#L63

2020-01-20 08:16 UTC, gurrrung commented on themes/pmahomme/scss/_common.scss
> +}
If I'm not wrong, `rem` values are relative to the root html element and that root HTML element size was missing here. Thus I added this.

2020-01-22 14:49 UTC, gurrrung commented on themes/pmahomme/scss/_common.scss
> +}
Ping !

2020-01-22 17:24 UTC, mauriciofauth commented on themes/pmahomme/scss/_common.scss
> +}
_0.82rem_ is the same as _82%_ and the `$font-size-base` is used in the `body` tag.
https://github.com/twbs/bootstrap/blob/v4.4.1/scss/_reboot.scss#L46-L49

2020-01-25 16:24 UTC, gurrrung commented on themes/pmahomme/scss/_common.scss
> +}
Thanks, I got it. Reverted the changes.

2020-01-26 10:46 UTC, MauricioFauth approved these changes

2020-01-26 11:04 UTC, merged

2020-01-26 11:04 UTC, williamdes commented
Thank your for your contribution @gurrrung !

2020-01-26 11:07 UTC, williamdes commented
I added ece12c5fb311cf78410cb30ab72ee86be2ca513d