Disabled checkbox of pmadb
phpmyadmin/phpmyadmin pull request #15847
Opened 2020-01-24 22:52 UTC by yashrajbothra

Signed-off-by: Yash Bothra <yashrajbothra786@gmail.com>

### Description

added `is_pmadb` to check the db is pmadb and disable checkbox for the same. 

Fixes #15447

2020-01-24 22:56 UTC, williamdes approved these changes

2020-03-06 16:54 UTC, MauricioFauth requested changes

2020-03-06 16:54 UTC, mauriciofauth commented on libraries/classes/Controllers/Server/DatabasesController.php
> +                'is_pmadb' => $database['SCHEMA_NAME'] === $GLOBALS['cfg']['Server']['pmadb'],
```suggestion
                'is_pmadb' => $database['SCHEMA_NAME'] === $cfg['Server']['pmadb'],
```

2020-03-06 20:32 UTC, MauricioFauth approved these changes

2020-03-06 22:37 UTC, merged