Fixes #15854: Designer Fullscreen Issues.
phpmyadmin/phpmyadmin pull request #15857
Opened 2020-01-26 16:32 UTC by rabeehrz

### Description

Fixes issue #15854 

Fixes #

- Removes black border on fullscreen canvas by setting the width and height to 100 viewports.
- Add the functionality to change menu icon on exiting full screen mode by pressing ESC.

Before submitting pull request, please review the following checklist:

- [x] Make sure you have read our [CONTRIBUTING.md](https://github.com/phpmyadmin/phpmyadmin/blob/master/CONTRIBUTING.md) document.
- [x] Make sure you are making a pull request against the correct branch. For example, for bug fixes in a released version use the corresponding QA branch and for new features use the _master_ branch. If you have a doubt, you can ask as a comment in the bug report or on the mailing list.
- [x] Every commit has proper `Signed-off-by` line as described in our [DCO](https://github.com/phpmyadmin/phpmyadmin/blob/master/DCO). This ensures that the work you're submitting is your own creation.
- [x] Every commit has a descriptive commit message.
- [x] Every commit is needed on its own, if you have just minor fixes to previous commits, you can squash them.
- [x] Any new functionality is covered by tests.

2020-01-26 17:13 UTC, williamdes commented on js/designer/move.js
> +    ctx.fillRect(x1, y1, w, h)
can you revert this change ?
and the line added below ?

2020-01-26 17:28 UTC, williamdes approved these changes

2020-01-26 17:29 UTC, williamdes commented
Code looks good, can you please squash the commits into one ?

2020-01-26 17:32 UTC, rabeehrz commented
@williamdes Commits squashed.

2020-01-28 18:37 UTC, williamdes commented on js/designer/move.js
> +            DesignerMove.saveValueInConfig('full_screen', valueSent);
why did you add this line :thinking:

2020-01-28 18:52 UTC, rabeehrz commented on js/designer/move.js
> +            DesignerMove.saveValueInConfig('full_screen', valueSent);
When the designer full screen is exited via by hitting the Exit full screen button, the value is saved in config. So when the full screen exists via ESC button, I thought the same thing should be done. Do I need to remove this? 😅

2020-01-28 18:56 UTC, williamdes commented on js/designer/move.js
> +            DesignerMove.saveValueInConfig('full_screen', valueSent);
Oh, no you can leave it, maybe add a comment to explain the issue ?

2020-01-28 19:38 UTC, williamdes commented on js/designer/move.js
> +        $('#osn_tab').css({ 'width': '100vw', 'height': '100vh' });
https://caniuse.com/#feat=mdn-api_css_vw
https://caniuse.com/#feat=mdn-api_css_vh

Can you find another way to do ?
And squash the commits ?

I would have loved to merge but the support is terrible for those units

2020-01-28 20:24 UTC, rabeehrz commented
@williamdes I've switched from viewports to JS screen dimensions. Please review. :)

2020-01-28 20:35 UTC, williamdes requested changes

2020-01-28 20:35 UTC, williamdes commented on js/designer/move.js
> +        console.log(screen.width);
Needs to be removed ;)

2020-01-28 20:57 UTC, williamdes approved these changes
tested it and it works fine.

2020-01-28 21:01 UTC, williamdes commented on js/designer/move.js
> +            $content.removeClass('content_fullscreen')
@rabeehrz can hard reset to my commit 3dd8a075e91423e13bd75bd1b8b382c4208a962b and add a OR case so it reduces the code duplication ?

2020-01-28 21:16 UTC, rabeehrz commented on js/designer/move.js
> +            $content.removeClass('content_fullscreen')
@williamdes Done! :)

2020-01-28 21:43 UTC, merged

2020-01-28 21:48 UTC, williamdes commented
Merged, thank your for your contributions !
I added f887621ad999e8239cd8dcc1718317779003ccc2 that I forgot to add to the commit