added continue session message
phpmyadmin/phpmyadmin pull request #15872
Opened 2020-01-28 19:58 UTC by yashrajbothra

Signed-off-by: Yash Bothra <yashrajbothra786@gmail.com>

Fixes #14149

2020-01-28 19:59 UTC, yashrajbothra commented
![image](https://user-images.githubusercontent.com/47683556/73300232-add05400-4236-11ea-81fe-8a312a42fa04.png)


Looks Good??

2020-01-28 20:10 UTC, williamdes commented on libraries/classes/Plugins/AuthenticationPlugin.php
> +                __('SESSION TIMEOUT: No activity within %s seconds.'
can you use non full caps letters ?
Also can you look in the codebase if we have another way of adding new lines into translations, I would like to avoid having the br tag in he translation source

2020-01-28 20:30 UTC, yashrajbothra commented on libraries/classes/Plugins/AuthenticationPlugin.php
> +                __('SESSION TIMEOUT: No activity within %s seconds.'
I was unable to find another way but `<br>` is passed number of times to translator

![image](https://user-images.githubusercontent.com/47683556/73302632-eeca6780-423a-11ea-8391-1726a080c8de.png)

2020-01-28 20:39 UTC, williamdes commented on libraries/classes/Plugins/AuthenticationPlugin.php
> +                __('SESSION TIMEOUT: No activity within %s seconds.'
Okay then :)

2020-01-28 20:47 UTC, williamdes approved these changes
LGTM
I would need another team member to review or approve

2020-01-28 22:10 UTC, MauricioFauth requested changes

2020-01-28 22:10 UTC, mauriciofauth commented on libraries/classes/Plugins/AuthenticationPlugin.php
> +                .'<br>'
Could you remove the `<br>` tag? You can concatenate it after the `sprintf` function.

2020-01-29 10:49 UTC, MauricioFauth requested changes

2020-01-29 10:49 UTC, mauriciofauth commented on libraries/classes/Plugins/AuthenticationPlugin.php
> +            .__('Please log in to continue session.');
You should run `composer test` to see other issues to fix.

2020-01-29 10:52 UTC, mauriciofauth commented
What about the message Isaac suggested in https://github.com/phpmyadmin/phpmyadmin/issues/14149#issuecomment-578724663 ?

2020-01-29 10:57 UTC, yashrajbothra commented
> What about the message Isaac suggested in [#14149 (comment)](https://github.com/phpmyadmin/phpmyadmin/issues/14149#issuecomment-578724663) ?

So i should change whole message with ***You have been automatically logged out due to
inactivity of {n} seconds. Once you log in again, you should be able to resume working
where you left off.***

2020-01-30 09:17 UTC, williamdes commented on libraries/classes/Plugins/AuthenticationPlugin.php
> +                inactivity of %s seconds. Once you log in again, you should be able to resume working
```suggestion
                inactivity of %s seconds. Once you log in again, you should be able to resume the work
```
?

2020-01-30 12:27 UTC, MauricioFauth requested changes

2020-01-30 12:27 UTC, mauriciofauth commented on libraries/classes/Plugins/AuthenticationPlugin.php
> +                where you left off.'),
Use concatenation to break the lines and remove the space at the start of the first line.

2020-01-31 10:20 UTC, MauricioFauth requested changes

2020-01-31 10:20 UTC, mauriciofauth commented on libraries/classes/Plugins/AuthenticationPlugin.php
> +                .'Once you log in again, you should be able to resume the work where you left off.'),
You should add a space between the words `seconds.Once`.

Don't forget to run `composer test` as well.

2020-01-31 13:25 UTC, yashrajbothra commented on libraries/classes/Plugins/AuthenticationPlugin.php
> +                .'Once you log in again, you should be able to resume the work where you left off.'),
`composer test` is showing me hundreds of error is it normal. Should i only fix the error in the file i have changed?

2020-01-31 19:59 UTC, williamdes commented on libraries/classes/Plugins/AuthenticationPlugin.php
> +                .'Once you log in again, you should be able to resume the work where you left off.'),
Dis you `composer update`?

2020-01-31 21:11 UTC, yashrajbothra commented on libraries/classes/Plugins/AuthenticationPlugin.php
> +                .'Once you log in again, you should be able to resume the work where you left off.'),
Pulled master -> run `composer update` -> run `composer test`
![image](https://user-images.githubusercontent.com/47683556/73574675-5501f500-449c-11ea-86c6-d5d0c9907675.png)

Unfortunately i can see lots of errors. Am i missing something?

2020-01-31 21:13 UTC, yashrajbothra commented on libraries/classes/Plugins/AuthenticationPlugin.php
> +                .'Once you log in again, you should be able to resume the work where you left off.'),
I guess its a OS [issue](https://stackoverflow.com/questions/35323321/php-validation-issue-end-of-line-character-is-invalid-expected-n-but-found)

2020-02-01 01:02 UTC, williamdes commented on libraries/classes/Plugins/AuthenticationPlugin.php
> +                .'Once you log in again, you should be able to resume the work where you left off.'),
Thank you!
Maybe you should open an issue on the phpcs repo?
I will check that because it now explains why another contributor said there was a lot of errors, but it was an OS issue

2020-02-01 01:03 UTC, williamdes commented on libraries/classes/Plugins/AuthenticationPlugin.php
> +                .'Once you log in again, you should be able to resume the work where you left off.'),
Also it could be related to a git setting that converts line breaks

2020-02-01 09:41 UTC, yashrajbothra commented on libraries/classes/Plugins/AuthenticationPlugin.php
> +                .'Once you log in again, you should be able to resume the work where you left off.'),
Issue is Closed on there Repo -> [Issue](https://github.com/squizlabs/PHP_CodeSniffer/issues/313)

i think we have to change something in ruleset?

2020-02-01 10:21 UTC, williamdes commented
@yashrajbothra why did you need to close it?

2020-02-01 10:32 UTC, yashrajbothra commented
So Sorry, I accidently Pushed without commit so it got closed automatically 😞

2020-02-01 10:40 UTC, williamdes commented
Okay, good to know :)

2020-02-03 14:18 UTC, MauricioFauth approved these changes

2020-02-22 22:52 UTC, williamdes approved these changes

2020-05-02 11:19 UTC, merged

2020-05-02 11:20 UTC, williamdes commented
Thank you @yashrajbothra !