fixed bad UI: buttons showing instead of text (bootstrap theme) #15882
phpmyadmin/phpmyadmin pull request #15891
Opened 2020-02-01 13:12 UTC by anirudhsingh20

### Description

Fixed Bad UI: buttons showing instead of text (bootstrap theme) #15882 
removed kbd text as it is responsible for padding and color around main and new text in navigation-settings -> navigation panel -> logo link target (description text) [ main and new ] 

updated Description.php file 

Fixes #
![issuew](https://user-images.githubusercontent.com/49402380/73592639-67bf0d00-4522-11ea-9609-2bf1896626ac.png)
to 
![issue@1](https://user-images.githubusercontent.com/49402380/73592644-6db4ee00-4522-11ea-85ee-1ef29eb3bdbb.png)

2020-02-11 21:12 UTC, MauricioFauth requested changes

2020-02-11 21:12 UTC, mauriciofauth commented on libraries/classes/Config/Descriptions.php
> +                . '( new ).'
I think you should replace with `[code]` and `[/code]` instead of removing the tag.

2020-02-12 10:42 UTC, anirudhsingh20 commented
Okay sure 👍

On Wed, Feb 12, 2020, 02:42 Maurício Meneghini Fauth <
notifications@github.com> wrote:

> *@mauriciofauth* requested changes on this pull request.
> ------------------------------
>
> In libraries/classes/Config/Descriptions.php
> <https://github.com/phpmyadmin/phpmyadmin/pull/15891#discussion_r377901216>
> :
>
> > -                'Open the linked page in the main window ([kbd]main[/kbd]) or in a new one '
> -                . '([kbd]new[/kbd]).'
> +                'Open the linked page in the main window ( main ) or in a new one '
> +                . '( new ).'
>
> I think you should replace with [code] and [/code] instead of removing
> the tag.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/phpmyadmin/phpmyadmin/pull/15891?email_source=notifications&email_token=ALY5EDG4EB7YJGSLHGADER3RCMIFFA5CNFSM4KOTCOIKYY3PNVWWK3TUL52HS4DFWFIHK3DMKJSXC5LFON2FEZLWNFSXPKTDN5WW2ZLOORPWSZGOCVDVXTI#pullrequestreview-356998093>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ALY5EDAA42GVJULUJ6ZYA5DRCMIFFANCNFSM4KOTCOIA>
> .
>

2020-02-13 22:08 UTC, closed without merging

2020-02-13 22:09 UTC, williamdes commented
Thank your for this PR, unfortunately #15949 was ready and had the same change.
I would suggest that you try another issue :muscle: