Fix #15895: add phpmyadmin logo and make navigation icons in a correct position
phpmyadmin/phpmyadmin pull request #15902
Opened 2020-02-03 13:05 UTC by MouadBH

Signed-off-by: Mouad Boulahdoud <mouad123b@gmail.com>

### Description

fix #15895

### Fixes
Before Fix:
![image](https://user-images.githubusercontent.com/28781942/73655134-99a0b280-468d-11ea-8741-b3ef06ea5df4.png)
After Fix:
![image](https://user-images.githubusercontent.com/28781942/73655240-cc4aab00-468d-11ea-904a-8b752d9db0bb.png)

2020-02-03 13:05 UTC, MouadBH commented
@williamdes  Please review and let me know if any changes are required. :)

2020-02-03 13:53 UTC, williamdes requested changes
I added some comments, I think you can remove the new logo file and the gitignore change and then amend your commit
Also you maybe need to change your git settings for your name or just change the signoff line before next push (--force) :)

2020-02-03 13:53 UTC, williamdes commented on .gitignore
> +.yarn
This change could be removed

2020-02-03 13:53 UTC, williamdes commented on themes/metro/scss/_navigation.scss
> +      display: none;
I am not sure this is okay

2020-02-03 16:27 UTC, MouadBH commented on themes/metro/scss/_navigation.scss
> +      display: none;
so we can delete the old logo

2020-02-03 18:05 UTC, williamdes commented on themes/metro/scss/_navigation.scss
> +      display: none;
I will need to test it at the end of the week :)

2020-02-10 09:00 UTC, MouadBH commented on .gitignore
> +.yarn
@williamdes I push a new commit to fix what you tell me.

2020-02-23 19:05 UTC, AbdullahiAbdulkabir commented
I found out that the navigation bar was okay in the cloned project and that the ::after is affecting the logo from displaying and also the display of the image was set to none. 
After making the image to be visible there was still a bit of CSS adjustment that I made.

2020-02-24 23:54 UTC, MauricioFauth requested changes
LGTM

2020-02-24 23:54 UTC, mauriciofauth commented on .gitignore
> +phpstan.neon
Please revert this change.

2020-04-25 08:59 UTC, williamdes approved these changes

2020-04-25 09:01 UTC, merged

2020-04-25 09:01 UTC, williamdes commented
I made the requested change for you.
Thank you for your contribution