Added Rename Button to use RENAME INDEX syntax of MySQL
phpmyadmin/phpmyadmin pull request #15912
Opened 2020-02-04 12:23 UTC by kartik1000

Signed-off-by: Kartik Kathuria <kathuriakartik0@gmail.com>

### Description

The PR adds Rename button in options of index in case the user only wants to Rename Index and not change any other properties of Index. Through this button we can use the RENAME INDEX syntax of MySQL but for MariaDB since this syntax is not applicable it will use the OLD ADD/DROP Method. For MySQL it will save a lot of time for large tables.

Fixes #14953 

Before submitting pull request, please review the following checklist:

- [ ] Make sure you have read our [CONTRIBUTING.md](https://github.com/phpmyadmin/phpmyadmin/blob/master/CONTRIBUTING.md) document.
- [ ] Make sure you are making a pull request against the correct branch. For example, for bug fixes in a released version use the corresponding QA branch and for new features use the _master_ branch. If you have a doubt, you can ask as a comment in the bug report or on the mailing list.
- [ ] Every commit has proper `Signed-off-by` line as described in our [DCO](https://github.com/phpmyadmin/phpmyadmin/blob/master/DCO). This ensures that the work you're submitting is your own creation.
- [ ] Every commit has a descriptive commit message.
- [ ] Every commit is needed on its own, if you have just minor fixes to previous commits, you can squash them.
- [ ] Any new functionality is covered by tests.

2020-02-04 12:25 UTC, kartik1000 commented
@williamdes  I am still left to add image for Rename button. When I am adding it in the img folder, it is not being added as commit . How can I add it?

2020-02-04 12:28 UTC, saurass commented
> @williamdes I am still left to add image for Rename button. When I am adding it in the img folder, it is not being added as commit . How can I add it?

Git can never commit an empty directory, though people using git have made a convention to keep a file named `.gitkeep` in the empty directory before commiting it.
Maybe you could use that : )

2020-02-04 12:33 UTC, kartik1000 commented
Thanks @saurass I will try to do that :)

2020-02-05 15:45 UTC, kartik1000 commented
@williamdes Please Review :)

2020-02-05 17:13 UTC, williamdes commented on js/functions.js
> +    if($('#check_rename').val() == 1){
=== 1 or "1"
Also be sure tu run `yarn run js-lint --fix`

2020-02-05 17:13 UTC, williamdes commented on libraries/classes/Controllers/Table/IndexesController.php
> +        if($_POST['rename_only'] == 1 and Util::getServerType() == 'MySQL'){
Same here, can you use strict equals?

2020-02-05 17:16 UTC, williamdes commented on libraries/classes/Table.php
> +    public function getSqlQueryForIndexRename($index, &$error){
```suggestion
    public function getSqlQueryForIndexRename(PleaseFindRightClass $index, ?Message &$error): string {
```

Can you add a phpdoc block and be sure to run `composer run phpcs`/`phpcbf`

2020-02-05 17:17 UTC, williamdes commented on tbl_indexes.php
> +if(isset($_POST['rename_only']) and $_POST['rename_only'] == 1){
Try to use strict equals everywhere :)

2020-02-05 17:18 UTC, williamdes requested changes
Where does the icon come from?
Do we have full rights on it?

2020-02-06 17:28 UTC, kartik1000 commented
@williamdes I will make all the requested changes and mention you here. I took the icon from https://icons8.com/icons/set/rename. The say its free for download for everybody. As per their licensing https://icons8.com/pricing It looks to me that all icons are free downloadable for everybody and they will have full rights on its. You can also confirm, the same.

2020-02-06 17:57 UTC, williamdes commented on js/functions.js
> +        title = 'Rename Index';
Oops you forgot to make the title translatable

2020-02-06 17:57 UTC, williamdes commented on libraries/classes/Index.php
> +                $r .= 'ajax' . ' edit';
```suggestion
                $r .= 'ajax edit';
```

2020-02-06 17:58 UTC, williamdes commented on libraries/classes/Index.php
> +        $r .= '<form action="tbl_indexes.php" method="post">'. '<input type="hidden" id="check_rename" value="0" />'. '</form>';
I think concats can be avoided

2020-02-06 17:59 UTC, williamdes commented on libraries/classes/Index.php
> +                $r .= ' ajax' . ' rename';
Same here

2020-02-06 18:02 UTC, williamdes commented
> @williamdes I will make all the requested changes and mention you here. I took the icon from https://icons8.com/icons/set/rename. The say its free for download for everybody. As per their licensing https://icons8.com/pricing It looks to me that all icons are free downloadable for everybody and they will have full rights on its. You can also confirm, the same.

@ibennetch do you agree about the icon and its licence?

2020-02-07 09:28 UTC, kartik1000 commented on libraries/classes/Table.php
> +    public function getSqlQueryForIndexRename($index, &$error){
@williamdes, By phpdoc block you mean information regarding the function and its working just above the function right?

2020-02-07 09:41 UTC, williamdes commented on libraries/classes/Table.php
> +    public function getSqlQueryForIndexRename($index, &$error){
Yes the
```
/**
  *
  */
```
Block

2020-02-08 08:59 UTC, williamdes commented on libraries/classes/Controllers/Table/IndexesController.php
> +        if($_POST['rename_only'] === "1" and Util::getServerType() === 'MySQL'){
```suggestion
        if($_POST['rename_only'] === "1" && Util::getServerType() === 'MySQL'){
```

2020-02-08 09:00 UTC, williamdes commented on libraries/classes/Controllers/Table/IndexesController.php
> +        else{
Can you make it on line above `} else {`
`composer run phpcbf`

2020-02-08 09:01 UTC, williamdes approved these changes
The code looks good

2020-02-08 09:09 UTC, kartik1000 commented
@williamdes  I made the above requested changes. somehow phpcbf package was not present on my system so just did it manually for now. @ibennetch What do you think about the icons and its license?

2020-02-08 09:26 UTC, williamdes commented
> @williamdes I made the above requested changes. somehow phpcbf package was not present on my system so just did it manually for now. @ibennetch What do you think about the icons and its license?

Maybe you need a `composer update`
I would need another point of view from a team member

2020-02-10 14:07 UTC, mauriciofauth commented
Why targeting QA instead of master branch?

2020-02-10 16:56 UTC, kartik1000 commented
@mauriciofauth When I made the changes locally some of the changes were required in tbl_indexes.php which I couldn't find in master. So had to make the changes considering QA_5_0 as base branch

2020-02-14 07:16 UTC, williamdes approved these changes

2020-02-14 07:16 UTC, williamdes commented on libraries/classes/Table.php
> +    public function getSqlQueryForIndexRename(Index $index, &$error): string
```suggestion
    public function getSqlQueryForIndexRename(Index $index, bool &$error): string
```

2020-02-16 09:08 UTC, kartik1000 commented
@williamdes  I made the change. Is it ready to be merged or do I need to rebase?

2020-02-16 09:21 UTC, williamdes commented
@kartik1000 the icon can not be used for multiple users

The icon is blocking the merge of your work

2020-02-16 10:11 UTC, kartik1000 commented
@williamdes How can we fix this problem? I am not sure I am understanding what is the issue.

2020-02-16 15:16 UTC, williamdes commented
> @williamdes How can we fix this problem? I am not sure I am understanding what is the issue.

The issue is that we can not use licenced work in phpMyAdmin that does not explicitly state it is free to use by a lot of users

The icon must be compatible with GPL-2.0

@mauriciofauth @ibennetch could you help me explain what is the policy?

Maybe a comment should be added in a documentation or in #15942?

2020-02-16 18:55 UTC, mauriciofauth commented
> When I made the changes locally some of the changes were required in tbl_indexes.php which I couldn't find in master. So had to make the changes considering QA_5_0 as base branch

New features should go to the master branch, the QA branches are for bug fixes only.

You can find the `tbl_indexes.php` content in the `PhpMyAdmin\Controllers\Table\IndexesController::index` method. However, it looks like you using `tbl_indexes.php` to create a new action, but it should be added as a new route in the `libraries/routes.php` file.

The license of the icon you are using is not compatible with the GPLv2 license. You can find another icon with a [compatible license](https://www.gnu.org/licenses/license-list.html) or you can use the icon provided in the [data repository](https://github.com/phpmyadmin/data/blob/master/resources/svg/icons/rename.svg).

2020-02-16 19:18 UTC, williamdes commented
> you can use the icon provided in the data repository.

I would definitely prefer this option

2020-02-16 19:23 UTC, kartik1000 commented
Ok @williamdes I will make the changes by tomorrow

2020-02-18 23:19 UTC, MauricioFauth requested changes
You have to switch from `QA_5_0` branch to `master` branch. Also don't forget to add tests that covers your changes.

2020-02-20 07:52 UTC, williamdes approved these changes

2020-02-20 07:53 UTC, williamdes commented
@mauriciofauth should we add a png render so other browsers have the icon?

2020-02-27 01:33 UTC, mauriciofauth commented
> @mauriciofauth should we add a png render so other browsers have the icon?

I don't know if it's necessary. Which browsers don't support SVG?

2020-02-27 01:44 UTC, MauricioFauth requested changes

2020-02-27 01:44 UTC, mauriciofauth commented on libraries/classes/Index.php
> +                $r .= '" href="' . Url::getFromRoute('/table/indexes') . '"  data-post="' . Url::getCommon($this_params, '')
I think you should create a new route for rename (like `/table/indexes/rename`) instead of using a POST parameter like `$_POST['rename_only']` to define the action.

2020-02-27 07:16 UTC, williamdes commented
https://caniuse.com/#feat=svg-img
It seems like we could switch full svg on phpMyAdmin

2020-03-11 20:04 UTC, williamdes commented
@kartik1000 do you need some help to make the changes ?

2020-04-14 22:23 UTC, williamdes commented
I rebase the work, and did some minor changes
Some more work is required before merging ;)

2020-11-05 11:31 UTC, williamdes commented
Near to be finished

2020-11-05 13:00 UTC, williamdes commented
![rename index feature](https://user-images.githubusercontent.com/7784660/98244112-31119980-1f6f-11eb-8460-4669a18817e4.png)

2020-11-05 14:24 UTC, williamdes commented
Hi @mauriciofauth @ibennetch 
This is a good feature, I tested and improved/finished it.
I think we should merge it into 5.1.

Tips:
- for merge: Update PO files
- for testing: run yarn to compile css and JS files

2020-11-13 21:58 UTC, mauriciofauth approved these changes
LGTM

2020-11-13 22:53 UTC, merged

2023-09-26 18:28 UTC, nunoperalta commented
Aaahhhhh.... I was now going to raise an issue saying that if we're just changing the name of an index, while the columns to be indexed don't change, it should generate a `RENAME INDEX` SQL instead of `DROP/ADD`.

Then I realized, from this PR (and #14953) that there's a Rename button!!! 😁👍🏼
(I hide the labels, and just show icons, so I didn't notice the Rename button)

Very good!! Thanks for that!!

Just one suggestion -- it's probably a good idea to add `, ALGORITHM=INPLACE, LOCK=NONE` to the SQL generated, just in case! (or add "Online Transaction" checkbox, to both Edit and Rename popups)