[WIP] Documentation URL
phpmyadmin/phpmyadmin pull request #15916
Opened 2020-02-04 14:17 UTC by victorphoenix3

Fixes #14947 , #15790

2020-02-04 14:22 UTC, williamdes approved these changes

2020-02-04 15:13 UTC, victorphoenix3 commented
@williamdes  is this fine or should I move the code to  https://github.com/williamdes/mariadb-mysql-kbs ?

2020-02-04 16:10 UTC, williamdes commented on libraries/classes/Util.php
> +    public static function getDocuURL(bool $isMariaDB = false)
```suggestion
    public static function getDocuURL(bool $isMariaDB = false): string
```

2020-02-04 16:11 UTC, williamdes approved these changes
For me it is okay, no need for now to move the links but maybe in a near future so they can receive updates and version handling

2020-02-04 16:41 UTC, victorphoenix3 commented on libraries/classes/Util.php
> +    public static function getDocuURL(bool $isMariaDB = false)
updated

2020-02-04 16:44 UTC, williamdes commented on libraries/classes/Util.php
> +            $this->getMySQLDocuURL('');
Is it missing a return?

2020-02-04 17:10 UTC, victorphoenix3 commented on libraries/classes/Util.php
> +            $this->getMySQLDocuURL('');
corrected it.

2020-02-04 17:15 UTC, williamdes commented on libraries/classes/Util.php
> +            $url = $this->getMySQLDocuURL('');
I would prefer to have 2 return statements
Also please check Travis CI you will see that phpstan pointed out that you can not use $this in a static method

:)

2020-02-04 18:07 UTC, victorphoenix3 commented on libraries/classes/Util.php
> +            $url = $this->getMySQLDocuURL('');
fixed :)

2020-02-04 18:15 UTC, williamdes commented on libraries/classes/Util.php
> +            return $url;
Why can you not return the function directly?

2020-02-04 18:20 UTC, williamdes commented on libraries/classes/Util.php
> +            return $url;
Just that it would be more readable :)

2020-02-04 18:23 UTC, williamdes approved these changes

2020-02-04 18:24 UTC, victorphoenix3 commented on libraries/classes/Util.php
> +            return $url;
done

2020-02-05 00:25 UTC, MauricioFauth requested changes

2020-02-05 00:25 UTC, mauriciofauth commented on libraries/classes/Util.php
> +        }
The `else` statement is useless here. You can remove it.

2020-02-05 05:01 UTC, MauricioFauth approved these changes

2020-02-09 17:35 UTC, merged

2020-02-09 17:36 UTC, williamdes commented
Thank you @victorphoenix3 for this enhancement !