Fix bug: PhpMyAdmin\Core::getRealSize / #15926
phpmyadmin/phpmyadmin pull request #15928
Opened 2020-02-06 21:57 UTC by BaseMax

Signed-off-by: Max Base <Max@Asrez.com>

### Description

> PhpMyAdmin\Core::getRealSize('8000M') returns a float instead of an int

it seems that PHPMyAdmin is not yet compatible with PHP 7.4.2.
My Pull request is for **phpMyAdmin v5.1.0-dev**, Not old versions.

Reffer to: https://github.com/phpmyadmin/phpmyadmin/pull/15927

Fixes #

Before submitting pull request, please review the following checklist:

- [x] Make sure you have read our [CONTRIBUTING.md](https://github.com/phpmyadmin/phpmyadmin/blob/master/CONTRIBUTING.md) document.
- [x] Make sure you are making a pull request against the correct branch. For example, for bug fixes in a released version use the corresponding QA branch and for new features use the _master_ branch. If you have a doubt, you can ask as a comment in the bug report or on the mailing list.
- [x] Every commit has proper `Signed-off-by` line as described in our [DCO](https://github.com/phpmyadmin/phpmyadmin/blob/master/DCO). This ensures that the work you're submitting is your own creation.
- [x] Every commit has a descriptive commit message.
- [x] Every commit is needed on its own, if you have just minor fixes to previous commits, you can squash them.
- [x] Any new functionality is covered by tests.

2020-02-06 21:58 UTC, BaseMax commented
Wow, **DCO** did accept my PR now.

2020-02-07 01:50 UTC, williamdes approved these changes

2020-02-07 02:07 UTC, williamdes commented
@BaseMax can you add a test case to https://github.com/phpmyadmin/phpmyadmin/blob/27fbfc70d84b7b3e0dc5f4cc21ad176d738df188/test/classes/CoreTest.php#L543?

This PR is okay, thank you for fixing the signoff line

2020-02-07 02:17 UTC, williamdes commented
If your real name "Seyyed Ali Mohammadiye" https://github.com/Asrez/Website/blob/9a643bc721e01f2c5734eb81f9c3dde6a1b84116/index.html#L7 ?
No insult, I am just afraid you are using a pseudonym

2020-02-07 02:19 UTC, williamdes requested changes
https://scholar.google.com/citations?user=0W-jUF0AAAAJ&hl=en

2020-02-08 18:47 UTC, williamdes commented on test/classes/CoreTest.php
> +                8388608000
```suggestion
                8388608000,
```

2020-02-08 18:47 UTC, williamdes commented on test/classes/CoreTest.php
> +                8589934592
```suggestion
                8589934592,
```

2020-02-08 18:48 UTC, williamdes commented
@BaseMax can you squash the commits and apply my suggestions ?
I am ready to merge

2020-02-08 20:57 UTC, williamdes commented
Also why 8G != 8000M in your test data ?

2020-02-08 21:49 UTC, BaseMax commented
> Also why 8G != 8000M in your test data ? @williamdes 

I did see both error in PHPmyAdmin.
So i did add both in unit tests. It's bad? I think we not have limitation in unit tests. They are not same.
If you want i will keep one.

2020-02-08 21:59 UTC, BaseMax commented on test/classes/CoreTest.php
> +                8589934592
Added.

2020-02-08 22:00 UTC, BaseMax commented on test/classes/CoreTest.php
> +                8388608000
Added.

2020-02-09 08:10 UTC, williamdes commented
> > Also why 8G != 8000M in your test data ? @williamdes
> 
> Thanks you, I did see both error in PHPmyAdmin.
> So i did add both in unit tests. It's bad? I think we not have limitation in unit tests. They are not same.
> If you want i will keep one.
> 
> Cheers,

Oh sorry, you can add as much test cases as you want
I was just surprised that the result of 8G was different than 8000M
Or is it because it was storage units by 1024 and not 1000?

2020-02-09 08:11 UTC, williamdes commented
Please squash your commits or give me access to your forked repo so I can fix it :)

2020-02-09 14:23 UTC, williamdes commented
https://github.com/phpmyadmin/phpmyadmin/issues/15936#issuecomment-583844660

2020-02-09 18:10 UTC, BaseMax commented
I did invite you, Also i did merge it. @williamdes

2020-02-10 07:19 UTC, williamdes approved these changes

2020-02-10 07:42 UTC, merged

2020-02-10 07:49 UTC, williamdes commented
Thank you @BaseMax !
Sorry for the ping pongs to fix minor things, but it was worth it ;)