[WIP] Make logo clickable
phpmyadmin/phpmyadmin pull request #15948
Opened 2020-02-11 18:13 UTC by victorphoenix3

Fixes #15946

2020-02-11 18:23 UTC, victorphoenix3 commented
@williamdes  do test.

2020-02-18 23:25 UTC, MauricioFauth requested changes

2020-02-18 23:25 UTC, mauriciofauth commented on templates/navigation/main.twig
> +              {% if theme == 'metro' %}
I think it's better to find a solution that work for all themes without adding an exception for the Metro theme.

2020-02-19 03:24 UTC, victorphoenix3 commented on templates/navigation/main.twig
> +              {% if theme == 'metro' %}
But its only for the "metro" theme thay we aren't using the official logo and hence the issue.

2020-04-26 05:28 UTC, closed without merging