Add css for kbd tag (Bootstrap theme)
phpmyadmin/phpmyadmin pull request #15949
Opened 2020-02-11 20:35 UTC by victorphoenix3

Fixes #15882

2020-02-11 20:44 UTC, victorphoenix3 commented
@williamdes  ready for review

2020-02-11 21:17 UTC, MauricioFauth reviewed
I don't agree with this change. The Bootstrap theme already have style for the `kbd` tag. I think it is better to change the tag instead of changing the default style of this tag.

2020-02-11 21:22 UTC, williamdes requested changes
I agree with @mauriciofauth 
Please change the tag

2020-02-11 21:33 UTC, victorphoenix3 commented
@williamdes  @mauriciofauth  I didn't find any properties for kbd defined in the _common.scss file for the bootstrap theme. The properties are being inherited from the _code.scss bootstrap module.

In the scss files for all the other themes these are being overridden by defining kbd properties again.

Am I missing something here? Do please take a closer look.

2020-02-11 21:39 UTC, mauriciofauth commented
> Am I missing something here? Do please take a closer look.

The idea of the Bootstrap theme is to use the default Bootstrap style. The [`kbd` tag](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/kbd) is used for keyboard inputs and that's why, for this case, I think the `code` tag makes more sense.

2020-02-11 21:58 UTC, victorphoenix3 commented
I understand it now :)
Have changed the `kbd` to `code`

2020-02-11 22:18 UTC, williamdes approved these changes

2020-02-13 22:08 UTC, merged

2020-02-13 22:10 UTC, williamdes commented
Thank you @victorphoenix3 !