WIP: GIT guide
phpmyadmin/phpmyadmin pull request #15942
Opened 2020-02-09 20:04 UTC by williamdes

Please comment and try to help make it simple. 
I can get to much technical sometimes.

I am writing it on mobile so I will add more content from my pc soon and change base

2020-02-09 20:43 UTC, williamdes commented
@yashrajbothra @kartik1000 if you could give me some comments on this alpha version of the file?

2020-02-10 05:11 UTC, yashrajbothra requested changes

2020-02-10 05:11 UTC, yashrajbothra commented on .github/GIT_GUIDE.md
> +## signoff explainations and instructions
I think this should be above add missing signoff line 😕

2020-02-10 12:17 UTC, kartik1000 commented
@williamdes For signoff line you can add git commit --amend --signoff  command.

2020-02-10 12:19 UTC, kartik1000 commented
@williamdes Also we can add how to cherry pick the commits as it is often required when rebasing.

2020-02-10 12:27 UTC, williamdes commented
> @williamdes For signoff line you can add git commit --amend --signoff command.

Done

> @williamdes Also we can add how to cherry pick the commits as it is often required when rebasing.

Sure, I will add as much details as possible

2020-02-10 12:29 UTC, williamdes commented on .github/GIT_GUIDE.md
> +# git guide
done

2020-02-10 12:29 UTC, williamdes commented on .github/GIT_GUIDE.md
> +## signoff explainations and instructions
I agree, done

2020-02-10 12:53 UTC, yashrajbothra commented
https://github.com/phpmyadmin/phpmyadmin/wiki/Git  @williamdes  aren't these similar?

2020-02-10 12:56 UTC, williamdes commented
> https://github.com/phpmyadmin/phpmyadmin/wiki/Git @williamdes aren't these similar?

Yes, maybe I should merge or create a new wiki page

2020-02-10 13:00 UTC, kartik1000 commented
@williamdes  What you are creating now is quite in brief and I think this is what is required rather than too long documentations. I think most of the people know the basics but what is specific to pMA and what they require is what they need to learn.

2020-02-10 13:25 UTC, yashrajbothra commented
If the Aim is to keep things short ,simple and point to point then its great. 
But if our aim is to give breif explaination then making that old guide better is good idea IMO as its already in breif.

2020-02-11 05:28 UTC, victorphoenix3 commented
@williamdes we should have a similar guide on how to set the Phpmyadmin system for development. It could include initial setup steps like cloning the repo in the var/www folder, setting `allownopassword` to `true`,  running `yarn install` for recompiling scss, running `phpstan`,  `phpcbf` , .tests/ci-phplint tests locally before submitting the PR.
It would make setup a lot easier for new contributers.

2020-02-11 20:46 UTC, rabeehrz commented
I think a section should be alloted for linting and compiling. 

Running CSSLint and JSLint.

Also something for compiling SCSS to CSS.

2020-02-11 22:50 UTC, williamdes commented
Thank you for all your comments ! :+1: 

NOTE: Inform contributors how much it is a bad idea of using main branches for PRs

2020-02-13 23:01 UTC, williamdes commented
Hi everybody
Please have a look https://github.com/phpmyadmin/phpmyadmin/pull/15942/files?short_path=b74d2c6#diff-b74d2c6a6e35fef3746c7fe1ef55f386

I added some requested details

2020-02-13 23:05 UTC, williamdes commented
@tabraiz961

2020-02-14 19:13 UTC, victorphoenix3 commented on .github/GIT_GUIDE.md
> +- because you can only create on PR per branch
"one" PR per branch

2020-02-14 19:20 UTC, victorphoenix3 commented on .github/GIT_GUIDE.md
> +- because it will be hard for maintainers to do git operations is needed to merge the PR
because it will be hard for maintainers to do git operations ~is~ needed to merge the PR (remove "is")

2020-02-14 19:22 UTC, williamdes commented on .github/GIT_GUIDE.md
> +- because you can only create on PR per branch
Fixed in 526c0cc05ef84d18e94d688ab77c97b228165e44 version

2020-02-14 19:22 UTC, williamdes commented on .github/GIT_GUIDE.md
> +- because it will be hard for maintainers to do git operations is needed to merge the PR
Fixed in 526c0cc05ef84d18e94d688ab77c97b228165e44 version

thank you for the reviews :)

2020-03-02 18:05 UTC, mauriciofauth commented
Related to #14746

2020-03-02 18:18 UTC, MauricioFauth reviewed
Some of this content can go to the `CONTRIBUTING.md` file and the rest can go to the [Git](https://github.com/phpmyadmin/phpmyadmin/wiki/Git) wiki page.
Also I think we should keep the git commands as simple as possible and add a reference to the GitHub/Git documentation if the person wants to learn more about that command.

2020-05-01 18:43 UTC, williamdes commented
Can someone help me split my PR ?

2020-05-01 19:42 UTC, ibennetch commented
I can help you with this, but probably not today.

2020-05-01 20:01 UTC, williamdes commented
> I can help you with this, but probably not today.

Thank you !
I will wait, no worries.

2020-09-15 13:15 UTC, closed without merging

2020-09-15 13:17 UTC, williamdes commented
Imported as https://github.com/phpmyadmin/phpmyadmin/wiki/GIT_MANUAL/a7441952b5c1264ebea5f04153124ad858da55a0 into https://github.com/phpmyadmin/phpmyadmin/wiki/GIT_MANUAL