fix #15950: updated datetime picker UI
phpmyadmin/phpmyadmin pull request #15951
Opened 2020-02-12 11:10 UTC by anirudhsingh20

### Description
signoff-by: Anirudh Singh <anirudhsingh20.as@gmail.com>

Updated DateTime picker UI in all the theme using CSS

fixes #15950 

Fixes #

Before fix:
no margin or space before sliders to select sec, min, millisec
![datetime](https://user-images.githubusercontent.com/49402380/74323352-65bf3e80-4dab-11ea-9e38-c1599a895c4d.PNG)

###After fix: 
In Bootstrap theme:
![datetimefixedbootstrap](https://user-images.githubusercontent.com/49402380/74329588-1af6f400-4db6-11ea-8fdc-d208eb2fa865.PNG)
![datetimefixed1](https://user-images.githubusercontent.com/49402380/74329607-23e7c580-4db6-11ea-8965-56d291c7ebff.PNG)

In pmahomme theme:
![datetimefixedmetro](https://user-images.githubusercontent.com/49402380/74329124-39102480-4db5-11ea-9d98-c3b924360a4d.PNG)

In original theme:
![datetimefixedoriginal](https://user-images.githubusercontent.com/49402380/74329160-44635000-4db5-11ea-9ddd-565706f38ec6.PNG)

In metro theme: 
![datetimefixedmetro](https://user-images.githubusercontent.com/49402380/74329581-1599a980-4db6-11ea-9643-b4bf57a4813d.PNG)

2020-02-16 22:01 UTC, MauricioFauth requested changes
Don't forget to run `yarn run css-lint`.

2020-02-17 03:11 UTC, anirudhsingh20 commented
Okay sure 👍

On Mon, Feb 17, 2020, 03:31 Maurício Meneghini Fauth <
notifications@github.com> wrote:

> *@mauriciofauth* requested changes on this pull request.
>
> Don't forget to run yarn run css-lint.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/phpmyadmin/phpmyadmin/pull/15951?email_source=notifications&email_token=ALY5EDDBFWRS4FMUS25OJ4TRDGZSHA5CNFSM4KTXVQ3KYY3PNVWWK3TUL52HS4DFWFIHK3DMKJSXC5LFON2FEZLWNFSXPKTDN5WW2ZLOORPWSZGOCVWIAGY#pullrequestreview-359432219>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ALY5EDDJ4FRXUMJZVZOVZ4TRDGZSHANCNFSM4KTXVQ3A>
> .
>

2020-02-17 03:13 UTC, anirudhsingh20 commented
What this command do ?

On Mon, Feb 17, 2020, 08:41 Anirudh singh <anirudhsingh20.as@gmail.com>
wrote:

> Okay sure 👍
>
> On Mon, Feb 17, 2020, 03:31 Maurício Meneghini Fauth <
> notifications@github.com> wrote:
>
>> *@mauriciofauth* requested changes on this pull request.
>>
>> Don't forget to run yarn run css-lint.
>>
>> —
>> You are receiving this because you authored the thread.
>> Reply to this email directly, view it on GitHub
>> <https://github.com/phpmyadmin/phpmyadmin/pull/15951?email_source=notifications&email_token=ALY5EDDBFWRS4FMUS25OJ4TRDGZSHA5CNFSM4KTXVQ3KYY3PNVWWK3TUL52HS4DFWFIHK3DMKJSXC5LFON2FEZLWNFSXPKTDN5WW2ZLOORPWSZGOCVWIAGY#pullrequestreview-359432219>,
>> or unsubscribe
>> <https://github.com/notifications/unsubscribe-auth/ALY5EDDJ4FRXUMJZVZOVZ4TRDGZSHANCNFSM4KTXVQ3A>
>> .
>>
>

2020-02-17 03:17 UTC, rabeehrz commented
> What this command do ?

There are some guidelines on how certain code should be written. That script will check your scss files for any violation and tell you. You can run `yarn run css-lint —-fix` to fix those issues.

2020-02-17 03:20 UTC, anirudhsingh20 commented
Okay thanks

On Mon, Feb 17, 2020, 08:47 Mohammed Rabeeh <notifications@github.com>
wrote:

> What this command do ?
>
> There are some guidelines on how certain code should be written. That
> script will check your scss files for any violation and tell you. You can
> run yarn run css-lint —-fix to fix those issues.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/phpmyadmin/phpmyadmin/pull/15951?email_source=notifications&email_token=ALY5EDH4SNSSU5E24GXC4LTRDH6VVA5CNFSM4KTXVQ3KYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEL453EQ#issuecomment-586800530>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ALY5EDAAMFBFMIJUOOMMMY3RDH6VVANCNFSM4KTXVQ3A>
> .
>

2020-02-17 14:52 UTC, anirudhsingh20 commented
updated requested changes @mauriciofauth

2020-05-18 17:59 UTC, MauricioFauth approved these changes

2020-05-18 21:24 UTC, merged

2020-05-18 21:25 UTC, williamdes commented
Thank you @anirudhsingh20 for your contribution !