Improved Search Results Page UI and refactored code
phpmyadmin/phpmyadmin pull request #15963
Opened 2020-02-15 10:37 UTC by thesmallstar

Signed-off-by: Manthan Surkar <manthan.surkar@gmail.com>
Initially, Two divs were used, which was unnecessary. I have made the required changes for code and UI.

New UI:
![image](https://user-images.githubusercontent.com/42006277/74586417-2859eb80-500d-11ea-894f-add8efb6ca5c.png)

![image](https://user-images.githubusercontent.com/42006277/74586422-2f80f980-500d-11ea-8dcd-d875dc47ca56.png)

2020-02-15 14:00 UTC, thesmallstar commented
![image](https://user-images.githubusercontent.com/42006277/74589249-a926e080-5029-11ea-8ea7-b996a35d6f58.png)

2020-02-25 11:34 UTC, MauricioFauth requested changes

2020-02-25 11:34 UTC, mauriciofauth commented on templates/database/search/main.twig
> +    <br>
Only use `<br>` for paragraph breaks. Please remove it.

2020-02-25 11:34 UTC, mauriciofauth commented on templates/database/search/main.twig
> +    <button class="btn btn-primary" id="togglesearchformlink"></a>
```suggestion
    <button class="btn btn-primary" id="togglesearchformlink"></button>
```

2020-04-05 19:55 UTC, williamdes commented
@thesmallstar could you fix this PR please ?

2020-06-12 07:37 UTC, closed without merging