FormDisplayTemplate upgrading with twig templates
phpmyadmin/phpmyadmin pull request #15977
Opened 2020-02-18 15:29 UTC by tabraiz961

Upgrading with twig templates and removed some extra condition.

2020-02-18 20:39 UTC, williamdes commented
@tabraiz961 did you already do a PR for this changes ?
Also If I did push the wrong changes please force push yours

2020-02-19 14:07 UTC, tabraiz961 commented
> @tabraiz961 did you already do a PR for this changes ?
> Also If I did push the wrong changes please force push yours
Yes a PR already exists for this but that PR had many issues so i created another branch and i,ll be force pushing soon against your changes

2020-02-20 00:31 UTC, tabraiz961 commented
Hi @williamdes can you check the error generated by Travis CI.

2020-02-20 07:56 UTC, williamdes requested changes
Can you edit the phpunit test that checks the html output of this part
See: Travis ci error

2020-02-20 10:22 UTC, tabraiz961 commented
> Can you edit the phpunit test that checks the html output of this part
> See: Travis ci error

Yes i can but i cant run test locally it gives me templates directory not found error.
![image](https://user-images.githubusercontent.com/5255703/74924695-b14d9a00-53f4-11ea-86e8-0d9a24a16f96.png)

2020-02-22 18:45 UTC, MauricioFauth requested changes

2020-02-22 18:45 UTC, mauriciofauth commented on libraries/classes/Config/FormDisplayTemplate.php
> +            . $pathSpecialChars . '"';
Please use the function directly instead of using the variable.

2020-02-22 18:45 UTC, mauriciofauth commented on templates/config/form_display/inputs.twig
> +      <a class="set-value hide" href="#{{ path ~ '={' ~ opts.setvalue ~ '}' }}" title="{{ 'Set value: %s'|trans|format(opts.setvalue) }}">{{ icons.edit|raw }}</a>
What is the reason to add `{}`around the `opts.setvalue`?

2020-02-22 18:45 UTC, mauriciofauth commented on templates/config/form_display/inputs.twig
> +    {% if opts.setvalue %}
```suggestion
    {% if opts.setvalue is not empty %}
```

2020-02-22 18:45 UTC, mauriciofauth commented on templates/config/form_display/inputs.twig
> +    {% if opts.show_restore_default %}
```suggestion
    {% if opts.show_restore_default is not empty %}
```

2020-02-26 00:00 UTC, tabraiz961 commented on templates/config/form_display/inputs.twig
> +    {% if opts.show_restore_default %}
I reviewed the twig docs if opts.show_restore_default is already empty we might not need to use "is not empty " here. Or is it a good practice ?

2020-02-26 00:01 UTC, tabraiz961 commented on templates/config/form_display/inputs.twig
> +      <a class="set-value hide" href="#{{ path ~ '={' ~ opts.setvalue ~ '}' }}" title="{{ 'Set value: %s'|trans|format(opts.setvalue) }}">{{ icons.edit|raw }}</a>
concating strings.

2020-05-03 00:59 UTC, closed without merging