Fixed Action buttons on join query
phpmyadmin/phpmyadmin pull request #15971
Opened 2020-02-17 06:44 UTC by yashrajbothra

Signed-off-by: Yash Bothra <yashrajbothra786@gmail.com>

### Description

Replaced `||` with `&&` so `just_one_table` is only false when there is more than one table

Fixes #13488

2020-02-17 06:49 UTC, williamdes approved these changes

2020-02-22 20:31 UTC, williamdes requested changes
`SELECT message.* FROM message JOIN user ON message.user_id = user.id WHERE user.username != ''` https://github.com/phpmyadmin/phpmyadmin/issues/12625#issue-181894158

The fix you made would revert 6b256e89dd4d405b5c74cacdaa1bf11aa53ee6e1 and 8c357fab12b041b1dd67ce8505e7767c4a7a413e for #12625

2020-08-05 08:23 UTC, williamdes commented
For reference:

https://github.com/phpmyadmin/phpmyadmin/blob/7fdde9e1cd80de19eb0a2f9da32306bbd5483b88/libraries/classes/Sql.php#L1860-L1864

@mauriciofauth @ibennetch do you think this PR is right or wrong (see above posted comments) ?

2021-02-09 13:12 UTC, williamdes commented
> `SELECT message.* FROM message JOIN user ON message.user_id = user.id WHERE user.username != ''` [#12625 (comment)](https://github.com/phpmyadmin/phpmyadmin/issues/12625#issue-181894158)
> 
> The fix you made would revert [6b256e8](https://github.com/phpmyadmin/phpmyadmin/commit/6b256e89dd4d405b5c74cacdaa1bf11aa53ee6e1) and [8c357fa](https://github.com/phpmyadmin/phpmyadmin/commit/8c357fab12b041b1dd67ce8505e7767c4a7a413e) for #12625

Hi @devenbansod 
Could you give me some advice on this old commit you had done ?

2021-04-20 16:42 UTC, williamdes commented
cc @ibennetch @mauriciofauth would anyone like to help me unblock this PR ?

2021-04-21 16:05 UTC, mauriciofauth commented
As William mentioned earlier, this pull request will cause a regression of the bug #12625.

2021-04-21 16:05 UTC, closed without merging