autocomplete attributes added
phpmyadmin/phpmyadmin pull request #16011
Opened 2020-03-04 17:04 UTC by Pankaj-Wadhwani

Signed-off-by: Pankaj Wadhwani <pankajwadhwani100@gmail.com>

### Description

Added `autocomplete : on` in form tag,username field and password field.

Fixes #

Before submitting pull request, please review the following checklist:

- [x] Make sure you have read our [CONTRIBUTING.md](https://github.com/phpmyadmin/phpmyadmin/blob/master/CONTRIBUTING.md) document.
- [x] Make sure you are making a pull request against the correct branch. For example, for bug fixes in a released version use the corresponding QA branch and for new features use the _master_ branch. If you have a doubt, you can ask as a comment in the bug report or on the mailing list.
- [x] Every commit has proper `Signed-off-by` line as described in our [DCO](https://github.com/phpmyadmin/phpmyadmin/blob/master/DCO). This ensures that the work you're submitting is your own creation.
- [x] Every commit has a descriptive commit message.
- [x] Every commit is needed on its own, if you have just minor fixes to previous commits, you can squash them.
- [x] Any new functionality is covered by tests.

2020-03-04 20:21 UTC, MauricioFauth reviewed
Is there a reason to add autocomplete for username and password fields?

2020-03-04 20:42 UTC, mauriciofauth commented
Okay. It's related to #16001.

2020-03-04 22:20 UTC, williamdes commented
From what I linked in #16001 https://www.chromium.org/developers/design-documents/form-styles-that-chromium-understands the value could be more precise then `on`

2020-03-05 13:31 UTC, Pankaj-Wadhwani commented
what if i do like this,
form tag has autocomplete="off"
username has autocomplete="pma_username"
password has autocomplete="pma_password"

2020-03-06 07:42 UTC, williamdes commented
> what if i do like this,
> form tag has autocomplete="off"
> username has autocomplete="pma_username"
> password has autocomplete="pma_password"
> @williamdes

I am not sure this is standard, could you do some research ?

2020-03-06 13:20 UTC, Pankaj-Wadhwani commented
> 
> I am not sure this is standard, could you do some research ?

yes

2020-03-07 12:35 UTC, Pankaj-Wadhwani commented
I changed the commit in pull request,please review it. @williamdes

2020-03-07 17:51 UTC, MauricioFauth requested changes

2020-03-07 17:51 UTC, mauriciofauth commented on templates/login/form.twig
> +        <input type="text" name="pma_username" id="input_username" value="{{ default_user }}" size="24" class="textfield form-control" autocomplete="pma_username">
https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/autocomplete

```suggestion
        <input type="text" name="pma_username" id="input_username" value="{{ default_user }}" size="24" class="textfield form-control" autocomplete="username">
```

2020-03-07 17:51 UTC, mauriciofauth commented on templates/login/form.twig
> +        <input type="password" name="pma_password" id="input_password" value="" size="24" class="textfield form-control" autocomplete="pma_password">
https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/autocomplete

```suggestion
        <input type="password" name="pma_password" id="input_password" value="" size="24" class="textfield form-control" autocomplete="current-password">
```

2020-03-08 22:55 UTC, Pankaj-Wadhwani commented
Review my commit @mauriciofauth

2020-03-10 17:04 UTC, MauricioFauth approved these changes

2020-03-10 20:35 UTC, merged

2020-03-10 20:37 UTC, williamdes commented
Thank you @Pankaj-Wadhwani for your contribution!

2020-03-11 13:54 UTC, Pankaj-Wadhwani commented
> Thank you @Pankaj-Wadhwani for your contribution!

My pleasure.
Would love to contribute more.