Use caching to speed up route parsing
phpmyadmin/phpmyadmin pull request #16028
Opened 2020-03-14 11:38 UTC by williamdes

Use caching for routing parsing.

I reduces the amounts of php function calls from ~1200 to ~3

Ref: #16005

2020-03-14 11:39 UTC, williamdes commented
Yes, I added more code safe-guards than necessary so nobody reports blank pages

2020-03-14 11:47 UTC, williamdes commented
Before: [trace.1584184315.25.xt.txt](https://github.com/phpmyadmin/phpmyadmin/files/4332664/trace.1584184315.25.xt.txt)
After: [trace.1584186349.56.xt.txt](https://github.com/phpmyadmin/phpmyadmin/files/4332666/trace.1584186349.56.xt.txt)

2020-03-15 00:17 UTC, MauricioFauth reviewed
:100:

2020-03-15 00:17 UTC, mauriciofauth commented on index.php
> +    'cacheFile' => $config !== null ? $config->getTempDir('routing') . '/routes.cache' : null,
I don't think we should use the temp dir. I think a `cache` dir should be created somewhere, and warm up the cache for the release. We can use the same cache dir later for the Twig cache (#14604).

2020-03-15 00:19 UTC, mauriciofauth commented on index.php
> +    'cacheFile' => $config !== null ? $config->getTempDir('routing') . '/routes.cache' : null,
What do you think of `libraries/cache/`?

2020-03-15 00:21 UTC, williamdes commented on index.php
> +    'cacheFile' => $config !== null ? $config->getTempDir('routing') . '/routes.cache' : null,
Good idea, I need to do more testing to know how changes are handled
We could add the cache file to GIT ? (not twig templates cache ^^)

2020-03-15 00:27 UTC, williamdes commented on index.php
> +    'cacheFile' => $config !== null ? $config->getTempDir('routing') . '/routes.cache' : null,
> What do you think of `libraries/cache/`?

Why not but it seems a strange place for twig templates cache

2020-03-15 00:32 UTC, mauriciofauth commented on index.php
> +    'cacheFile' => $config !== null ? $config->getTempDir('routing') . '/routes.cache' : null,
> We could add the cache file to GIT ?

I don't think so. We should create the file using the create release script.

> Why not but it seems a strange place for twig templates cache

I know, but since the root directory is public, I think is easier to use an existing dir.

2020-03-15 00:42 UTC, williamdes commented on index.php
> +    'cacheFile' => $config !== null ? $config->getTempDir('routing') . '/routes.cache' : null,
> I don't think so. We should create the file using the create release script.

Okay

> I know, but since the root directory is public, I think is easier to use an existing dir.

I agree

I will do the changes tomorrow

2020-03-18 11:02 UTC, williamdes commented on index.php
> +    'cacheFile' => $config !== null ? $config->getTempDir('routing') . '/routes.cache' : null,
d32807862b20017beba0ba080a5f3626143877a9
Done

2020-03-18 11:03 UTC, williamdes commented
@ibennetch I made some changes to the release script, are you okay with them ?

2020-03-18 15:36 UTC, ibennetch reviewed
Looks good to me. I've added a few comments but think this is a good development.

2020-03-18 15:36 UTC, ibennetch commented on libraries/cache/.gitignore
> +!/.gitignore
I suggest adding `/libraries/cache` to `/.gitignore`, rather than adding this file here.

We could add the empty cache directory to git but use gitignore to leave it empty in the repository, right?

2020-03-18 15:36 UTC, ibennetch commented on scripts/create-release.sh
> +                branch=`echo $1 | tr -d -c '/0-9A-Za-z_-'`
Is this change related to other changes you're making?

2020-03-18 15:36 UTC, ibennetch commented on libraries/cache/.gitignore
> +!/.gitignore
By the way, the `libraries/cache` folder is fine for me. We should consider adding the path to the `/libraries/vendor_config.php` file, though, so distributions can move it as they see fit.

2020-03-18 15:36 UTC, ibennetch commented
> I made some changes to the release script, are you okay with them ?

Sure, they look good to me.

2020-03-18 16:30 UTC, williamdes commented on scripts/create-release.sh
> +                branch=`echo $1 | tr -d -c '/0-9A-Za-z_-'`
I could not run the release script with my branch name `perf/cachedRouting`
Can I keep this change ?

2020-03-18 16:31 UTC, williamdes commented on libraries/cache/.gitignore
> +!/.gitignore
Good idea I will do that

2020-03-18 16:48 UTC, williamdes commented on libraries/cache/.gitignore
> +!/.gitignore
> We could add the empty cache directory to git but use gitignore to leave it empty in the repository, right?

This is what I did, adding it to the global ignore will not allow me to add the folder to git unfortunately

Is it okay then ?

2020-03-18 17:15 UTC, MauricioFauth requested changes

2020-03-18 17:15 UTC, mauriciofauth commented on libraries/classes/Command/RoutingCacheWarmupCommand.php
> +    protected static $defaultName = 'routing:cache:warmup';
What about `cache:routing-warmup`? Or maybe use `cache:warmup` for both warmups (twig and routing) and add cli options to run specific warmups.

2020-03-18 17:15 UTC, mauriciofauth commented on scripts/create-release.sh
> +    composer update --no-dev --optimize-autoloader
Will this work with customs plugins?

2020-03-18 17:32 UTC, williamdes commented on scripts/create-release.sh
> +    composer update --no-dev --optimize-autoloader
Good catch, I will try to be sure of that

2020-03-18 20:04 UTC, williamdes commented on libraries/classes/Command/RoutingCacheWarmupCommand.php
> +    protected static $defaultName = 'routing:cache:warmup';
I merged the commands, good suggestion :)

2020-03-18 20:05 UTC, williamdes commented on libraries/cache/.gitignore
> +!/.gitignore
Done in 4d2800daa49819b85aceba9089f6bec3da254608

2020-03-18 21:13 UTC, MauricioFauth approved these changes
Good job. :100:

2020-03-18 21:13 UTC, mauriciofauth commented on libraries/vendor_config.php
> +define('ROUTING_CACHE_DIR', ROOT_PATH . 'libraries/cache/');
I think just `CACHE_DIR` is better, because we can use this for other types of cache later.

2020-03-18 21:13 UTC, mauriciofauth commented on libraries/classes/Command/CacheWarmupCommand.php
> +            $output->writeln('Please specify --twig or --routing');
I think it could be less strict here and allow both options or none, and in both cases run both warmups.

2020-03-18 21:19 UTC, mauriciofauth commented on libraries/classes/Command/CacheWarmupCommand.php
> +    public function warmUpRoutingCache(OutputInterface $output): int
This should be private, shouldn't it?

2020-03-18 21:28 UTC, williamdes commented on libraries/vendor_config.php
> +define('ROUTING_CACHE_DIR', ROOT_PATH . 'libraries/cache/');
Done 39b3f3f5e8a9f8149b15726b440d290d328803de
I agree with you

2020-03-18 21:28 UTC, williamdes commented on libraries/classes/Command/CacheWarmupCommand.php
> +            $output->writeln('Please specify --twig or --routing');
f79c26f986b9b915e3ad70fadc6296236a302194

2020-03-18 21:29 UTC, williamdes commented on libraries/classes/Command/CacheWarmupCommand.php
> +    public function warmUpRoutingCache(OutputInterface $output): int
I would prefer not to make it private to allow some testing to be done some day
Do you agree ?

2020-03-18 21:45 UTC, williamdes commented on libraries/common.inc.php
> +$route = Routing::getCurrentRoute();
@mauriciofauth the alternative was fd912545cc27e23d97c156316cf4cd0606046c72
Still okay ?

2020-03-28 10:32 UTC, williamdes commented on scripts/create-release.sh
> +    composer update --no-dev --optimize-autoloader
Custom plugins load as expected:
- tested a custom auth plugin
- tested a custom export plugin

2020-03-28 10:33 UTC, williamdes commented on libraries/classes/Command/CacheWarmupCommand.php
> +    public function warmUpRoutingCache(OutputInterface $output): int
c3b99d7baa2a3f91fa9828c30f06bc72fa408857

2020-03-28 10:53 UTC, merged