Fix IN(...) clause doesnt permit multiple values
phpmyadmin/phpmyadmin pull request #16077
Opened 2020-04-14 07:51 UTC by asprazz

### Description

Please describe your pull request.
Fixes #16041 
Added regex validation for Multiple Clauses Like
IN(...) NOT IN(...) BETWEEN 

Before submitting pull request, please review the following checklist:

- [x] Make sure you have read our [CONTRIBUTING.md](https://github.com/phpmyadmin/phpmyadmin/blob/master/CONTRIBUTING.md) document.
- [x] Make sure you are making a pull request against the correct branch. For example, for bug fixes in a released version use the corresponding QA branch and for new features use the _master_ branch. If you have a doubt, you can ask as a comment in the bug report or on the mailing list.
- [x] Every commit has proper `Signed-off-by` line as described in our [DCO](https://github.com/phpmyadmin/phpmyadmin/blob/master/DCO). This ensures that the work you're submitting is your own creation.
- [x] Every commit has a descriptive commit message.
- [x] Every commit is needed on its own, if you have just minor fixes to previous commits, you can squash them.
- [ ] Any new functionality is covered by tests.

2020-04-14 07:53 UTC, williamdes commented on js/table/change.js
> +            'Please enter a valid numbers.'
You should use https://github.com/phpmyadmin/phpmyadmin/blob/09c1d1070a8027c6572a6eb77e39f91bdd9b2b75/js/messages.php#L123

2020-04-14 08:19 UTC, asprazz commented on js/table/change.js
> +            'Please enter a valid numbers.'
Done..

2020-04-14 08:24 UTC, williamdes requested changes
95%okay for me
Good work
I need to test it after your changes

2020-04-14 08:24 UTC, williamdes commented on js/table/change.js
>      if ($thisInput.data('type') === 'INT') {
Consider moving hasMultiple into this if condition to narrow the use cases of this variable :)

2020-04-14 08:24 UTC, williamdes commented on js/table/change.js
> +        var mini = $('#fieldID_' + searchIndex).attr('min');
Could all this operations be done in the PHP code ?

2020-04-14 08:25 UTC, asprazz commented on js/table/change.js
>      if ($thisInput.data('type') === 'INT') {
Oke Got It!

2020-04-14 08:26 UTC, asprazz commented on js/table/change.js
> +        var mini = $('#fieldID_' + searchIndex).attr('min');
I will try ...

2020-04-14 08:35 UTC, williamdes commented on js/table/change.js
> +        var mini = $('#fieldID_' + searchIndex).attr('min');
:muscle:

2020-04-14 08:40 UTC, asprazz commented on js/table/change.js
> +        var mini = $('#fieldID_' + searchIndex).attr('min');
I have changed the attributes to data-min and data-max in the backend so IN(...) , NOT IN(....) clauses won't have that problem of min max I hope it works for us! :)

2020-04-14 08:41 UTC, asprazz commented on js/table/change.js
> -        $('#fieldID_' + searchIndex).prop('multiple', false);
Should i revert this to `prop` also ?

2020-04-14 08:43 UTC, asprazz commented on js/table/change.js
> -        $('#fieldID_' + searchIndex).prop('multiple', false);
I reverted... it back to `prop`

2020-04-14 08:58 UTC, williamdes approved these changes
:100:

2020-04-14 08:58 UTC, williamdes commented on js/table/change.js
> +        var mini = $('#fieldID_' + searchIndex).attr('min');
Very nice, thank you

2020-04-14 08:59 UTC, williamdes commented on libraries/classes/Controllers/Table/SearchController.php
> +            $html_attributes = 'data-min="' . $min_max_values[0] . '" '
FTR: Line added by e92e51d42d38b9516153c011781bc90f94c144d5

2020-04-14 09:03 UTC, asprazz commented on libraries/classes/Controllers/Table/SearchController.php
> +            $html_attributes = 'data-min="' . $min_max_values[0] . '" '
Yeas!

2020-04-17 23:09 UTC, williamdes commented
@asprazz I tested your work and a minor issue was introduced.
When you will the field and the validation does pass, then you empty the input and it stays invalid as it is empty.
As a user I would like to ba able to empty the input and the validation resets.

Could you please fix this behavior ?

2020-04-18 01:30 UTC, asprazz commented
Hi @williamdes I will look into it asap.

2020-04-18 10:06 UTC, williamdes approved these changes

2020-04-18 10:27 UTC, merged

2020-04-18 10:46 UTC, williamdes commented
Thank you @asprazz for fixing this issue !

2020-04-18 10:55 UTC, asprazz commented
> Thank you @asprazz for fixing this issue !

I’m glad I could help. :man_technologist: