Glossary reworked
phpmyadmin/phpmyadmin pull request #16087
Opened 2020-04-19 15:09 UTC by comradekingu

All terms and corresponding URLs checked and updated

2020-04-19 15:21 UTC, williamdes approved these changes

2020-04-19 15:21 UTC, williamdes commented on doc/glossary.rst
> +      a libre software data compression algorithm and program developed by Julian Seward.
This change feels strange

2020-04-19 15:27 UTC, comradekingu commented on doc/glossary.rst
> +      a libre software data compression algorithm and program developed by Julian Seward.
See https://en.wikipedia.org/wiki/Free_software

2020-04-19 23:01 UTC, ibennetch commented
Thanks for your pull request. The bot is complaining because your commit is missing a "[signed off by](https://stackoverflow.com/questions/1962094/what-is-the-sign-off-feature-in-git-for)" line indicating that you agree to our [Developer Certificate of Origin](https://github.com/phpmyadmin/phpmyadmin/blob/master/DCO) document, which ensures that the work you've done is your own.

The best way to fix it is to amend your commit using the --signoff flag (such as `git commit --amend --signoff`) and push the changes back to your branch (you'll need to force the push with -f or --force).

2020-04-19 23:33 UTC, comradekingu commented
If you want to sign off on it, go right ahead. It is all trivial.

2020-04-19 23:53 UTC, ibennetch requested changes
These are mostly good fixes, thanks for doing the work. I have some notes about a few things I'm not so sure about.

2020-04-19 23:53 UTC, ibennetch commented on doc/glossary.rst
> +      a libre software data compression algorithm and program developed by Julian Seward.
While the term "libre" is common in  the free software community, those people are also more likely to already know what bzip2 is. Because this glossary is meant as a quick introduction to a topic for new users, I think the original definition carries the meaning more clearly. Of particular note from the Wikipedia page you linked are that they introduce both terms as synonyms and reference the FSF's recommendation to use the term "free software."

I think the term libre is unnecessarily nuanced for this purpose.

2020-04-19 23:53 UTC, ibennetch commented on doc/glossary.rst
> +    Database
Good. We have quite a few styles of terms here, and I like the capital leading letter. Good improvement.

2020-04-19 23:53 UTC, ibennetch commented on doc/glossary.rst
> +      GZip is short for GNU zip, a GNU libre software file compression program.
I'd have the same comment about not wanting to use "libre" here as I did for bzip2, although we might want to add that it's open source.

2020-04-19 23:53 UTC, ibennetch commented on doc/glossary.rst
> +      Hypertext Transfer Protocol is the primary method used to transfer or
This makes no sense, but that's not your fault. I didn't write this entry, but also thought it was "HyperText" because that's where the first "T" of http comes from. Turns out the RFCs always us "Hypertext" like you have here. So you've taught me something today.

2020-04-19 23:53 UTC, ibennetch commented on doc/glossary.rst
> +      .. seealso:: <https://en.wikipedia.org/wiki/Database_index>
Good catch

2020-04-19 23:53 UTC, ibennetch commented on doc/glossary.rst
> -      .. seealso:: <https://pear.php.net/>
We can keep the link to the official page while adding Wikipedia:

`seealso:: <https://en.wikipedia.org/wiki/PEAR>, <https://pear.php.net/>`

2020-04-19 23:53 UTC, ibennetch commented on doc/glossary.rst
> +      .. seealso:: <https://en.wikipedia.org/wiki/Perl_Compatible_Regular_Expressions>
Same here as for PEAR, we can link to both.

2020-04-19 23:53 UTC, ibennetch commented on doc/glossary.rst
> +      short for "PHP: Hypertext Preprocessor", is a libre software, reflective
Same thing about the use of libre.

2020-04-19 23:53 UTC, ibennetch commented on doc/glossary.rst
> -      .. seealso:: <https://dev.mysql.com/doc/refman/5.7/en/storage-engines.html>
I'd keep both links here, as well.

2020-04-19 23:53 UTC, ibennetch commented on doc/glossary.rst
> +      a type of archive file format, from "Tape Archive".
Good, this reads much better.

2020-04-19 23:53 UTC, ibennetch commented on doc/glossary.rst
> +      standardised format, that is used for referring to resources, such as
We tend to use the American English spelling of words, so I believe "standardized" is preferred here.

2020-06-25 02:15 UTC, comradekingu commented on doc/glossary.rst
> +      a libre software data compression algorithm and program developed by Julian Seward.
I don't think so. "Libre" is unencumbered by the FSF. Also, "Free software" is a lost cause now that "freeware" isn't being used". From what I have seen "free software" introduces errors in translation. Now it is consistent wrt. the below occurrence.

2020-08-10 19:51 UTC, williamdes commented
Draft until everyone agrees on everything :)

2020-08-10 20:09 UTC, comradekingu commented on doc/glossary.rst
> +      .. seealso:: <https://en.wikipedia.org/wiki/PEAR>
```suggestion
      .. seealso:: <https://en.wikipedia.org/wiki/PEAR>,
      <https://pear.php.net/>
```

2020-08-10 20:12 UTC, comradekingu commented on doc/glossary.rst
> +      .. seealso:: <https://en.wikipedia.org/wiki/Perl_Compatible_Regular_Expressions>
```suggestion
      .. seealso:: <https://en.wikipedia.org/wiki/Perl_Compatible_Regular_Expressions>,
      <https://www.php.net/pcre>
```

2020-08-10 20:15 UTC, comradekingu commented on doc/glossary.rst
> +      .. seealso:: <https://en.wikipedia.org/wiki/Database_engine>
```suggestion
      .. seealso:: <https://en.wikipedia.org/wiki/Database_engine>,
      <https://dev.mysql.com/doc/refman/5.7/en/storage-engines.html>
```

2020-08-10 20:16 UTC, comradekingu commented on doc/glossary.rst
> +      standardised format, that is used for referring to resources, such as
```suggestion
      standardized format, that is used for referring to resources, such as
```

2020-08-10 20:26 UTC, comradekingu commented on doc/glossary.rst
> +      Hypertext Transfer Protocol is the primary method used to transfer or
There is also the second "/" in HTTP-addresses to contemplate in quiet moments.

2020-08-10 21:05 UTC, comradekingu commented on doc/glossary.rst
> +      GZip is short for GNU zip, a GNU libre software file compression program.
That is a disservice to GNU.

2020-08-10 21:13 UTC, comradekingu commented on doc/glossary.rst
> +      short for "PHP: Hypertext Preprocessor", is a libre software, reflective
How did it get to be so imperative to avoid being consistent?
If it isn't "open-source" and "open source", plus the combination of it must now be anything but for GNU stuff, and as follows "open source" for anything else.

2020-08-10 21:48 UTC, comradekingu commented on doc/glossary.rst
> +      a libre software data compression algorithm and program developed by Julian Seward.
@ibennetch The concoction "free software/open-source" is confused on many levels. It really snoggles the boggles.
First of all they aren't synonymous. However much "free software" happens to be synonymous with "gratis software", it doesn't then qualify "open-source" as such. That is just one of the pitfalls to avoid, before translation. Further, that isn't even the way to write it in English, which even https://www.sourceware.org/bzip2/ manages to get wrong. How this carries more meaning is beyond me. It robs the English language of a word to say "software with publicly accessible/opened source code", for a basic (as in primitive) idea to purposely rob unsuspecting users of the notion that free software actually is to do with freedom. That is _less_ meaning _by design_. The derived "FOSS" epitomizes how much nothing can come out of something. Not only is it as often "Free and open source software" as "Free open source software", it at best implies meaning from being devoid of an Oxford comma. Recommendations by way of the modern FSF now hold the same ambiguous quality as the term "free software". It just didn't pan out after 37 years. Stop the beating of a dead horse, especially when it is beating itself.

"Unnecessarily nuanced" scores you no points for what is "concisely clear". Libre.

2020-10-12 04:29 UTC, comradekingu commented
Not sure why the travis build fails here.

2020-10-12 13:46 UTC, williamdes commented
> Not sure why the travis build fails here.

Could you rebase onto latest master ?

2020-11-05 17:27 UTC, Guileas commented on doc/glossary.rst
> +      .. seealso:: <https://en.wikipedia.org/wiki/MySQLi>
```suggestion
      .. seealso:: `PHP Manual for MySQL Improved Extension <https://www.php.net/manual/en/book.mysqli.php>`_
       .. seealso:: <https://en.wikipedia.org/wiki/MySQLi>
```

2020-11-05 17:32 UTC, Guileas commented on doc/glossary.rst
>        .. seealso:: <https://en.wikipedia.org/wiki/OS_X>
```suggestion
      .. seealso:: <https://en.wikipedia.org/wiki/MacOS>
```

2020-11-05 17:38 UTC, Guileas commented on doc/glossary.rst
> +      .. seealso:: <https://en.wikipedia.org/wiki/PEAR>,
```suggestion
      .. seealso:: `PEAR Website<https://pear.php.net/>`_
      .. seealso:: `Wikipedia page for PEAR <https://en.wikipedia.org/wiki/PEAR/>`_
```

2020-11-05 17:39 UTC, Guileas commented on doc/glossary.rst
> +      Perl Compatible Regular Expressions is the Perl-compatible regular
```suggestion
      Perl-Compatible Regular Expressions is the Perl-compatible regular
```

2020-11-05 17:42 UTC, Guileas commented on doc/glossary.rst
> +      .. seealso:: <https://en.wikipedia.org/wiki/Perl_Compatible_Regular_Expressions>,
```suggestion
      .. seealso:: `PHP manual for Perl-Compatible Regular Expressions<https://www.php.net/pcre>`_
      .. seealso:: <https://en.wikipedia.org/wiki/Perl_Compatible_Regular_Expressions>,
```

2020-11-05 17:50 UTC, Guileas commented on doc/glossary.rst
> +      .. seealso:: <https://en.wikipedia.org/wiki/Database_engine>,
```suggestion
      .. seealso:: `MySQL chapter about Alternative Storage Engines
 <https://dev.mysql.com/doc/refman/5.7/en/storage-engines.html>`_
      .. seealso:: <https://en.wikipedia.org/wiki/Database_engine>,
```

2020-11-06 17:21 UTC, williamdes commented on doc/glossary.rst
> +      .. seealso:: >https://en.wikipedia.org/wiki/International_Organization_for_Standardization>
```suggestion
      .. seealso:: <https://en.wikipedia.org/wiki/International_Organization_for_Standardization>
```

2020-11-06 17:37 UTC, williamdes commented
I rebased and improved your work, would you mind if I revert all the "free" stuff so I can merge this one ?

> If you want to sign off on it, go right ahead. It is all trivial.

Done

2020-11-06 17:40 UTC, williamdes commented on doc/glossary.rst
> -      .. seealso:: <https://pear.php.net/>
It turns out this is a kind of broken syntax so I will keep multiple lines ;)
The website link is back

2020-11-06 17:55 UTC, comradekingu commented
@williamdes Sure, if you just don't want to be right. I can't force your hand.
I'll be here in decades to come when you are ready to come around on it ;)

2020-11-06 18:35 UTC, williamdes commented
> @williamdes Sure, if you just don't want to be right. I can't force your hand.
> I'll be here in decades to come when you are ready to come around on it ;)

Sure, there is just too much debate around the change. I did push the revert bc4b60d3b9b4b3d3c88acb904de5683218eca94d that you can revert and make a pull-request for.

2020-11-06 18:45 UTC, merged