Converting getExecuteForm to TWIG template
phpmyadmin/phpmyadmin pull request #16202
Opened 2020-06-17 19:09 UTC by britbarn

### Description

The function getExecuteForm in /libraries/classes/Database/Routines.php has been converted to a TWIG template in /templates/execute_form.twig

Fixes #

Before submitting pull request, please review the following checklist:

- [ ] Make sure you have read our [CONTRIBUTING.md](https://github.com/phpmyadmin/phpmyadmin/blob/master/CONTRIBUTING.md) document.
- [ ] Make sure you are making a pull request against the correct branch. For example, for bug fixes in a released version use the corresponding QA branch and for new features use the _master_ branch. If you have a doubt, you can ask as a comment in the bug report or on the mailing list.
- [ ] Every commit has proper `Signed-off-by` line as described in our [DCO](https://github.com/phpmyadmin/phpmyadmin/blob/master/DCO). This ensures that the work you're submitting is your own creation.
- [ ] Every commit has a descriptive commit message.
- [ ] Every commit is needed on its own, if you have just minor fixes to previous commits, you can squash them.
- [ ] Any new functionality is covered by tests.

2020-06-17 19:38 UTC, MauricioFauth requested changes
Hi, @britbarn. Thank you for your contribution.

Our test suite [found some issues](https://travis-ci.org/github/phpmyadmin/phpmyadmin/jobs/699435386#L415) in your pull request that should be fixed before we can merge it.

You can run the tests locally with the following command:
```
composer test
```

2020-06-17 20:01 UTC, MauricioFauth requested changes

2020-06-17 20:01 UTC, mauriciofauth commented on libraries/classes/Database/Routines.php
> +        echo $this->template->render('execute_form', [
```suggestion
        return $this->template->render('database/routines/execute_form', [
```

2020-10-05 08:27 UTC, williamdes commented
@mauriciofauth do you think it can be finished quickly or do I close this one ?

2020-10-15 15:05 UTC, closed without merging