remove underscore prefix from property names
phpmyadmin/phpmyadmin pull request #16279
Opened 2020-07-25 16:25 UTC by morrme

Signed-off-by: morrme <morrme@users.noreply.github.com>

### Description

Removes underscore from property names
See #16278 

Before submitting pull request, please review the following checklist:

- [x] Make sure you have read our [CONTRIBUTING.md](https://github.com/phpmyadmin/phpmyadmin/blob/master/CONTRIBUTING.md) document.
- [x] Make sure you are making a pull request against the correct branch. For example, for bug fixes in a released version use the corresponding QA branch and for new features use the _master_ branch. If you have a doubt, you can ask as a comment in the bug report or on the mailing list.
- [x] Every commit has proper `Signed-off-by` line as described in our [DCO](https://github.com/phpmyadmin/phpmyadmin/blob/master/DCO). This ensures that the work you're submitting is your own creation.
- [x] Every commit has a descriptive commit message.
- [x] Every commit is needed on its own, if you have just minor fixes to previous commits, you can squash them.
- [x] Any new functionality is covered by tests.

2020-07-28 22:05 UTC, MauricioFauth requested changes

2020-07-28 22:05 UTC, mauriciofauth commented on libraries/classes/Bookmark.php
> +    private $user;
The property `$user` already exists.
https://github.com/phpmyadmin/phpmyadmin/blob/bcf21c4081232df1bb77a076a3ff551ee7d7b40c/libraries/classes/Bookmark.php#L57-L62

2020-07-28 22:08 UTC, mauriciofauth commented
Hello. Thanks for your contribution!

We require a full real name for legal compliance reasons. Could you use your full name in the signature tag?
For example: `Signed-off-by: Jane Developer <jane@example.org>`

See [Developer's Certificate of Origin](https://github.com/phpmyadmin/phpmyadmin/blob/master/DCO#L39)

2020-07-29 17:03 UTC, morrme commented
@mauriciofauth Please see the note I wrote you aout $user and let me know your decision

2020-07-30 21:42 UTC, mauriciofauth commented
> @mauriciofauth Please see the note I wrote you aout $user and let me know your decision

Sorry, but I don't see where your note is.

2020-08-01 15:36 UTC, morrme commented
Please see the review line above your comment. What would you like to change $user to?

2020-08-05 03:50 UTC, morrme commented
@mauriciofauth  Any update here? Is there a variable name you'd like to change $_user to so that it does not conflict with $user?

2020-08-05 03:51 UTC, morrme commented
![bk](https://user-images.githubusercontent.com/26514778/89369919-0af50880-d6a5-11ea-8432-dcbd9189a535.JPG)
@mauriciofauth here is my original comment

2020-08-05 04:29 UTC, closed without merging

2020-08-05 04:58 UTC, mauriciofauth commented on libraries/classes/Bookmark.php
> +    private $user;
You can use `$bookmarkUser` here.

2020-08-05 05:02 UTC, mauriciofauth commented
@morrme I didn't saw your comment because it was still with the _Pending_ status. I can use `$bookmarkUser` instead of `$_user`.