Support ReCaptcha v2 checkbox
phpmyadmin/phpmyadmin pull request #16299
Opened 2020-08-07 14:10 UTC by williamdes

### Description

Support ReCaptcha v2 checkbox

Fixes #16269

```php
<?php
$cfg['CaptchaMethod'] = 'checkbox';
```

2020-08-07 15:48 UTC, MauricioFauth requested changes
You have to add the config directive to the `libraries/config.default.php` file as well.

2020-08-07 15:52 UTC, williamdes commented
> You have to add the config directive to the `libraries/config.default.php` file as well.

Done :)

2020-08-07 15:54 UTC, MauricioFauth approved these changes

2020-08-07 21:57 UTC, merged

2020-08-08 21:35 UTC, ibennetch commented
Nice work!