Remove inline js
phpmyadmin/phpmyadmin pull request #16308
Opened 2020-08-18 13:46 UTC by nikkolai14

#13270

2020-08-18 14:36 UTC, williamdes commented
Hi @nikkolai14  
Thank you for contributing!
I would recommend you to use some git visualisation tool like GitKraken in order to avoid doing merges of merges but instead one commit or more on your pull-requests :)

2020-08-18 14:52 UTC, nikkolai14 commented
@williamdes Okay, I will try to learn the GitKraken tool, sorry about that.

2020-08-18 18:07 UTC, MauricioFauth requested changes

2020-08-18 18:07 UTC, mauriciofauth commented on templates/export.twig
> +      {%- if exec_time_limit > 0 %} data-exec-time-limit="{{ exec_time_limit }}" {% endif %}>
I think you could move that if to the js file as well.

2020-08-18 18:07 UTC, mauriciofauth commented on js/export.js
> +        Export.checkTimeOut(timeLimit);
```suggestion
        if (timeLimit > 0) {
            Export.checkTimeOut(timeLimit);
        }
```

2020-08-18 18:12 UTC, mauriciofauth commented
> @williamdes Okay, I will try to learn the GitKraken tool, sorry about that.

You don't have to sorry about that. It is a recommendation to help you improve as a developer. Having a lot of commits in the pull request doesn't matter to us that much, since we can squash them before merging.

2020-08-18 19:13 UTC, williamdes commented
> > @williamdes Okay, I will try to learn the GitKraken tool, sorry about that.
> 
> You don't have to sorry about that. It is a recommendation to help you improve as a developer. Having a lot of commits in the pull request doesn't matter to us that much, since we can squash them before merging.

I agree but I would add that it adds some overhead for me to do squashes before a merge :)
Do as you want with a good balance between not wasting your time and not adding to much overhead to the developer merging your work. Examples: good pull-request descriptions, fixes number, clean git history, etc..

Anyway, enjoy your coding time and thank you for your contributions! ;)

2020-08-19 15:51 UTC, MauricioFauth approved these changes

2020-08-19 15:52 UTC, merged

2020-08-19 15:52 UTC, mauriciofauth commented
Merged, thanks for your contribution!