Fix Incomplete JSON Blob Export
phpmyadmin/phpmyadmin pull request #16346
Opened 2020-09-13 14:01 UTC by realcc

Apply base64_encode when exporting table that contains blob column

Signed-off-by: Andreas Kurniawan <andreas@kurniawan.ceo>

2020-09-13 14:16 UTC, realcc reviewed
Apply base64_encode when exporting table that contains blob column

Signed-off-by: Andreas Kurniawan <andreas@kurniawan.ceo>

2020-10-07 15:14 UTC, williamdes commented
Could you provide a use case, I looked to your fix for the second time and am not sure to well understand ?

2020-10-07 17:57 UTC, realcc commented
> Could you provide a use case, I looked to your fix for the second time and am not sure to well understand ?

Try to create a table that contains a blob column, and then populate with some records. After that, try to export that table into a JSON file, and it does not work properly.

2020-11-05 09:23 UTC, williamdes commented
Hi @realcc 

I tested your work and this is the final diff, could you give me access to the repository so I can push the final change ?

```patch
commit 2ba35d78d3890d0b8779e92f8c44dc903a6d5f36 (json-export-blob)
Author: realcc <andreas@kurniawan.ceo>
Date:   Sun Sep 13 20:50:01 2020 +0700

    Fix Incomplete JSON Blob Export
    
    Apply base64_encode when exporting table that contains blob column
    
    Signed-off-by: Andreas Kurniawan <andreas@kurniawan.ceo>

diff --git a/libraries/classes/Plugins/Export/ExportJson.php b/libraries/classes/Plugins/Export/ExportJson.php
index a89918f77f..6fecee0f6c 100644
--- a/libraries/classes/Plugins/Export/ExportJson.php
+++ b/libraries/classes/Plugins/Export/ExportJson.php
@@ -16,10 +16,12 @@ use PhpMyAdmin\Properties\Options\Items\HiddenPropertyItem;
 use PhpMyAdmin\Properties\Plugins\ExportPluginProperties;
 use const JSON_PRETTY_PRINT;
 use const JSON_UNESCAPED_UNICODE;
+use function base64_encode;
 use function bin2hex;
 use function explode;
 use function json_encode;
 use function stripslashes;
+use function strpos;
 
 /**
  * Handles the export for the JSON format
@@ -271,6 +273,8 @@ class ExportJson extends ExportPlugin
                 if ($fieldsMeta[$i]->type === 'geometry') {
                     // export GIS types as hex
                     $record[$i] = '0x' . bin2hex($record[$i]);
+                } elseif (strpos($fieldsMeta[$i]->type, 'blob') !== false) {
+                    $record[$i] = base64_encode($record[$i]);
                 }
                 $data[$columns[$i]] = $record[$i];
             }

```

@ibennetch Should we warn our users about using base64 instead of plain broken binary in the JSON export ?

2020-11-06 16:33 UTC, realcc commented
Hi @williamdes

Access granted to the repository.

Many thanks.

2020-11-06 16:48 UTC, williamdes approved these changes

2020-11-06 16:48 UTC, williamdes commented
> Hi @williamdes
> 
> Access granted to the repository.
> 
> Many thanks.

Thank you, I did push the changes

2020-11-11 16:21 UTC, mauriciofauth requested changes

2020-11-11 16:21 UTC, mauriciofauth commented on libraries/classes/Plugins/Export/ExportJson.php
> +                    $record[$i] = base64_encode($record[$i]);
```suggestion
                    $record[$i] = base64_encode($record[$i] ?? '');
```

2020-11-11 16:21 UTC, mauriciofauth commented on libraries/classes/Plugins/Export/ExportJson.php
> +                    $record[$i] = base64_encode($record[$i]);
Why not use `bin2hex` as well?

2020-11-11 17:09 UTC, realcc commented on libraries/classes/Plugins/Export/ExportJson.php
> +                    $record[$i] = base64_encode($record[$i]);
base64_encode would be more useful when the user want to show the image stored in blob, such as using 'data:image/jpeg;base64,'

2020-11-11 20:04 UTC, mauriciofauth commented on libraries/classes/Plugins/Export/ExportJson.php
> +                    $record[$i] = base64_encode($record[$i]);
For general use, I think `bin2hex` makes more sense. What do you think @williamdes?

2020-11-11 22:47 UTC, williamdes commented on libraries/classes/Plugins/Export/ExportJson.php
> +                    $record[$i] = base64_encode($record[$i]);
Yes, I agree. In fact I hesitated when rebasing to change to hex.

2020-11-11 23:43 UTC, mauriciofauth commented on libraries/classes/Plugins/Export/ExportJson.php
> +                    $record[$i] = base64_encode($record[$i]);
@realcc Could you change to the bin2hex function?

2020-11-12 09:03 UTC, williamdes approved these changes

2020-11-12 09:03 UTC, williamdes commented on libraries/classes/Plugins/Export/ExportJson.php
> +                    $record[$i] = base64_encode($record[$i]);
Done

2020-11-12 21:19 UTC, merged

2020-11-12 21:19 UTC, williamdes commented
Now blobs will be exported as hex, thank you for the pull-request @realcc !