Added checks for Routine Specific privileges
phpmyadmin/phpmyadmin pull request #16371
Opened 2020-09-23 16:39 UTC by rajat315315

Signed-off-by: Rajat Jain <rajatjain.ix@gmail.com>

### Description

Added a function which checks Routine specific privileges.

Fixes #14430 

Before submitting pull request, please review the following checklist:

- [x] Make sure you have read our [CONTRIBUTING.md](https://github.com/phpmyadmin/phpmyadmin/blob/master/CONTRIBUTING.md) document.
- [x] Make sure you are making a pull request against the correct branch. For example, for bug fixes in a released version use the corresponding QA branch and for new features use the _master_ branch. If you have a doubt, you can ask as a comment in the bug report or on the mailing list.
- [x] Every commit has proper `Signed-off-by` line as described in our [DCO](https://github.com/phpmyadmin/phpmyadmin/blob/master/DCO). This ensures that the work you're submitting is your own creation.
- [x] Every commit has a descriptive commit message.
- [x] Every commit is needed on its own, if you have just minor fixes to previous commits, you can squash them.
- [ ] Any new functionality is covered by tests.

2020-09-24 08:00 UTC, williamdes commented on libraries/classes/Util.php
> +     * @param mixed  $db      db name to which routine belongs
```suggestion
     * @param string  $db      db name to which routine belongs
```

2020-09-24 08:01 UTC, williamdes commented
Related to https://github.com/phpmyadmin/phpmyadmin/issues/15883
Would close PR https://github.com/phpmyadmin/phpmyadmin/pull/15840

2020-09-24 08:46 UTC, williamdes commented on libraries/classes/Util.php
> +                $priv
I think all the arguments should use `escapeString` to avoid query injections 
https://github.com/phpmyadmin/phpmyadmin/blob/bed85fb01c1e5c0206ae95add75b9320f3dd75a4/libraries/classes/DatabaseInterface.php#L2991

2020-09-24 08:49 UTC, williamdes commented on libraries/classes/Util.php
> +    public static function currentUserHasSpecificProcPrivilege(string $priv, array $routine, $db): bool
```suggestion
    /**
     * Checks if the current user has a specific procedure privilege and returns true if the
     * user indeed has that privilege or false if they don't.
     *
     * @example currentUserHasSpecificProcPrivilege(
     *                             'EXECUTE', ['name' => 'MyProcedure', 'type' => 'PROCEDURE']
     *                   );
     *  Checks if the currently logged in user has the
     *  'EXECUTE' privilege on 'MyProcedure'
     *
     * @param string $priv    The privilege to check
     * @param array  $routine an array containing Routine information. It must have two keys
     *                        name and type. For example: ['name' => 'MyProcedure',
     *                        'type' => 'PROCEDURE']
     * @param string  $db     db name to which routine belongs
     *
     * @return bool
     */
    public static function currentUserHasSpecificProcPrivilege(string $priv, array $routine, string $db): bool
```

2020-09-24 08:49 UTC, williamdes commented on libraries/classes/Util.php
> +        }
```suggestion
        return (bool) $user_privileges;
```

2020-09-24 08:50 UTC, williamdes commented
I added some code improvements before testing your work, feel free to apply them and do one commit for all changes :)

2020-10-02 16:25 UTC, rajat315315 commented on libraries/classes/Util.php
> +                $priv
There are other places in the file, where same `sprintf` is used, but none uses `escapeString`..

2020-10-03 15:09 UTC, mauriciofauth requested changes

2020-10-03 15:09 UTC, mauriciofauth commented on libraries/classes/Util.php
> +     * @param string  $db     db name to which routine belongs
```suggestion
     * @param string $db      db name to which routine belongs
```

2020-10-03 15:09 UTC, mauriciofauth commented on libraries/classes/Util.php
> +        $user_privileges = $GLOBALS['dbi']->fetchValue(
```suggestion
        $userPrivileges = $GLOBALS['dbi']->fetchValue(
```

2020-10-03 15:09 UTC, mauriciofauth commented on libraries/classes/Util.php
> +        return (bool) $user_privileges;
```suggestion
        return (bool) $userPrivileges;
```

2020-10-03 19:54 UTC, mauriciofauth approved these changes

2020-11-02 10:20 UTC, williamdes commented
The code really looks nice but I could not validate the fix using the data from #14430

2020-11-03 10:49 UTC, rajat315315 commented
Should work. Can you try once more please?

2020-11-05 00:01 UTC, williamdes commented
> Should work. Can you try once more please?

I tried on MySQL and MariaDB and the user can not find the procedure definition.
Your code is maybe working but I can not test it with the user I create and grant like #14430 defines the steps to do.

here is some enhancements:
```patch
diff --git a/libraries/classes/Util.php b/libraries/classes/Util.php
index 649ad4b70c..233058c45a 100644
--- a/libraries/classes/Util.php
+++ b/libraries/classes/Util.php
@@ -2225,13 +2225,13 @@ class Util
         }
 
         // Prepare the query
-        $query = 'SELECT Proc_priv FROM `mysql`.`procs_priv`'
+        $query = 'SELECT 1 FROM `mysql`.`procs_priv`'
                . " WHERE Host= '%s'"
                . " AND Db='%s'"
                . " AND User='%s'"
                . " AND Routine_name='%s'"
                . " AND Routine_type='%s'"
-               . " AND Proc_priv='%s'";
+               . " AND Proc_priv LIKE '%s'";
 
         // Check specific routine privileges.
         $userPrivileges = $dbi->fetchValue(
@@ -2241,12 +2241,12 @@ class Util
                 $db,
                 $user,
                 $routine['name'],
-                $routine['type'],
-                $priv
+                 $routine['type'],
+                '%' . $priv . '%'// Contain the privilege
             )
         );
 
-        return (bool) $userPrivileges;
+        return $userPrivileges === '1';
     }
 
     /**
```

2020-11-05 17:01 UTC, rajat315315 commented
Give me few days, I will find a fix for sure. Currently I am very very busy. 😬

2020-11-05 17:07 UTC, williamdes commented
> Give me few days, I will find a fix for sure. Currently I am very very busy.

Okay, no worries I understand ;)

2020-11-06 09:59 UTC, rajat315315 commented
Execute button requires procedure's signature in order to open the input parameters dialog for execution.
Function definition/signature is retrieved by SHOW CREATE PROCEDURE statement which requires atleast SELECT PRIVILEGE for the user `hwreport`.
Source: https://dev.mysql.com/doc/refman/5.7/en/show-create-procedure.html 
![Screenshot from 2020-11-06 15-24-21](https://user-images.githubusercontent.com/15379278/98352906-a0a58880-2044-11eb-8403-345edb1d7b25.png)

2020-11-16 12:35 UTC, williamdes commented
Hi @rajat315315 
I tried with MySQL 5.7.17 and my user had no more permissions than his database.
The buttons did not work, he could not access the procedure definition.
I granted the user access to the mysql database in select mode and that showed the buttons.
But the fix does not show more buttons than before in this scenario..

Could you help me ?

2021-02-09 14:06 UTC, williamdes commented
Tried another time and could not verify the fix

2021-03-22 23:44 UTC, williamdes commented
I still can not validate your work.
Thank you for your contribution

2021-03-22 23:44 UTC, closed without merging