Use of SameSite=Strict
phpmyadmin/phpmyadmin pull request #16386
Opened 2020-10-06 10:03 UTC by rajat315315

Signed-off-by: Rajat Jain <rajatjain.ix@gmail.com>

### Description

Added new cookie parameter SameSite=Strict.

Fixes #16316 

Before submitting pull request, please review the following checklist:

- [x] Make sure you have read our [CONTRIBUTING.md](https://github.com/phpmyadmin/phpmyadmin/blob/master/CONTRIBUTING.md) document.
- [x] Make sure you are making a pull request against the correct branch. For example, for bug fixes in a released version use the corresponding QA branch and for new features use the _master_ branch. If you have a doubt, you can ask as a comment in the bug report or on the mailing list.
- [x] Every commit has proper `Signed-off-by` line as described in our [DCO](https://github.com/phpmyadmin/phpmyadmin/blob/master/DCO). This ensures that the work you're submitting is your own creation.
- [x] Every commit has a descriptive commit message.
- [x] Every commit is needed on its own, if you have just minor fixes to previous commits, you can squash them.
- [x] Any new functionality is covered by tests.

2020-10-06 13:33 UTC, williamdes approved these changes
LGTM

2020-10-08 18:48 UTC, mauriciofauth requested changes

2020-10-08 18:48 UTC, mauriciofauth commented on libraries/classes/Config.php
> +                $optional_params
This alternative signature requires PHP 7.3+.

2020-10-08 18:48 UTC, mauriciofauth commented on libraries/classes/Config.php
> +            $optional_params = [
```suggestion
            $optionalParams = [
```

2020-10-08 19:31 UTC, rajat315315 reviewed
@mauriciofauth is it better now?

2020-10-08 19:31 UTC, rajat315315 commented on libraries/classes/Config.php
> +                $optional_params
Nice Observation.. I never saw it.
Should I use polyfill?

2020-10-08 22:51 UTC, mauriciofauth commented on libraries/classes/Config.php
> +                $optional_params
You could check if PHP >= 7.3 then use the new signature, otherwise use the signature without the options param.

2020-10-09 06:03 UTC, rajat315315 commented
@mauriciofauth is it better?

2020-10-09 11:08 UTC, mauriciofauth requested changes

2020-10-09 11:08 UTC, mauriciofauth commented on libraries/classes/Config.php
> +            if (version_compare(phpversion(), '7.3', '<')) {
```suggestion
            if (PHP_VERSION_ID < 70300) {
```

2020-10-09 11:10 UTC, rajat315315 commented
Just a request..
Can we add `hacktoberfest-accepted` label to PR if it gets merged?

2020-10-09 12:32 UTC, mauriciofauth commented on libraries/classes/Config.php
> +                'samesite' => 'Strict',
I'm not really sure if it's a good idea to hard-code the Strict value. Maybe we could use a configuration directive and use Strict by default. What do you think @williamdes?

2020-10-09 12:41 UTC, mauriciofauth commented
> Can we add `hacktoberfest-accepted` label to PR if it gets merged?

All pull requests for this repository are valid for Hacktoberfest. Don't need to add the `hacktoberfest-accepted` label. :wink:

2020-10-09 12:41 UTC, mauriciofauth approved these changes

2020-10-09 12:42 UTC, mauriciofauth commented
@rajat315315 Could you please fix the errors found by phpcs?
https://travis-ci.org/github/phpmyadmin/phpmyadmin/jobs/734257860#L434

2020-10-10 13:54 UTC, rajat315315 commented
Done.

2020-10-13 14:44 UTC, williamdes commented on libraries/classes/Config.php
> +                'samesite' => 'Strict',
I agree, this is a better idea.

2020-10-13 15:21 UTC, mauriciofauth commented on libraries/classes/Config.php
> +                'samesite' => 'Strict',
@rajat315315 Could you do this change?

2020-10-13 16:45 UTC, rajat315315 commented on libraries/classes/Config.php
> +                'samesite' => 'Strict',
Sure

2020-10-14 06:44 UTC, rajat315315 commented
So, I have made `samesite` as a configuration directive and force-pushed.

2020-10-14 07:08 UTC, williamdes commented
Hi @rajat315315  
I appreciate your contribution :)
Could you look at #16406 to add a configuration option?

2020-10-14 07:11 UTC, rajat315315 commented
Oh, ok.. got it!
Sorry, I mis-understood a bit.

2020-10-14 07:19 UTC, rajat315315 commented
Is it better?

2020-10-14 07:24 UTC, mauriciofauth requested changes
You should add this configuration to the documentation as well.

2020-10-14 07:24 UTC, mauriciofauth commented on libraries/config.default.php
> + $cfg['sameSite'] = 'Strict';
```suggestion
$cfg['CookieSameSite'] = 'Strict';
```

2020-10-14 07:31 UTC, williamdes commented on libraries/classes/Config.php
> +            if (PHP_VERSION_ID < 70300) {
```suggestion
            if (version_compare(PHP_VERSION, '7.3.0', '<=')) {
```
This would be more readable and consistent with the code base ?

2020-10-14 07:45 UTC, mauriciofauth commented on libraries/classes/Config.php
> +            if (PHP_VERSION_ID < 70300) {
I suggested to use `PHP_VERSION_ID`. This constant requires PHP 5.2.7+, probably the other parts of the code base were added before that.

2020-10-14 07:50 UTC, williamdes commented on libraries/classes/Config.php
> +            if (PHP_VERSION_ID < 70300) {
Oh okay, good to know

2020-10-14 08:28 UTC, williamdes approved these changes
LGTM for now, missing some documentation :)

2020-10-14 09:20 UTC, rajat315315 commented
Do I need to make changes to `doc/config.rst` ?

2020-10-14 09:52 UTC, williamdes commented
> Do I need to make changes to `doc/config.rst` ?

Yes, please

this will solve

> You should add this configuration to the documentation as well.

2020-10-14 17:57 UTC, rajat315315 commented
Done.

2020-10-14 20:35 UTC, williamdes commented on doc/config.rst
> +
You did mention an RFC, maybe add it as well here as a link ?

2020-10-14 20:35 UTC, williamdes commented on doc/config.rst
> +
```suggestion
    :default: ``'Strict'``

    .. versionadded:: 5.1.0

```

2020-10-15 06:22 UTC, rajat315315 commented on doc/config.rst
> +
Done

2020-10-15 06:22 UTC, rajat315315 commented on doc/config.rst
> +
Done

2020-10-15 06:59 UTC, williamdes approved these changes

2020-10-15 07:01 UTC, williamdes commented on doc/config.rst
> +    https://tools.ietf.org/id/draft-ietf-httpbis-rfc6265bis-03.html#rfc.section.5.3.7
You could take example on 0d9882961f7d55a643ee63c6fb370d0b82d58aab to see how to add a specific rfc and how to add links

2020-10-16 09:29 UTC, rajat315315 commented on doc/config.rst
> +    https://tools.ietf.org/id/draft-ietf-httpbis-rfc6265bis-03.html#rfc.section.5.3.7
Do you mean like this:
.. seealso:: :rfc:`6265`

Actualy, this RDC is under draft. It's URL is:
https://tools.ietf.org/id/draft-ietf-httpbis-rfc6265bis-03.html#rfc.section.5.3.7

2020-10-16 09:32 UTC, williamdes commented on doc/config.rst
> +    https://tools.ietf.org/id/draft-ietf-httpbis-rfc6265bis-03.html#rfc.section.5.3.7
Indeed, you can use ``` `rfc6265 bis <https://tools.ietf.org/id/draft-ietf-httpbis-rfc6265bis-03.html#rfc.section.5.3.7>`_``` and that will make a link

2020-10-17 11:05 UTC, rajat315315 commented on doc/config.rst
> +    https://tools.ietf.org/id/draft-ietf-httpbis-rfc6265bis-03.html#rfc.section.5.3.7
Done!!

2020-10-17 11:33 UTC, williamdes approved these changes
💯

2020-11-01 21:51 UTC, merged

2020-11-01 21:51 UTC, williamdes commented
I improved the documentation with ce6bd5b3bd53772bb7648a0019ec1ff66e75fb6e
![image](https://user-images.githubusercontent.com/7784660/97815718-6c227d00-1c90-11eb-9263-9771f4aa0230.png)