Fix Latitude and Longitudes swap
phpmyadmin/phpmyadmin pull request #16391
Opened 2020-10-08 19:18 UTC by shucon

Fixes: https://github.com/phpmyadmin/phpmyadmin/issues/16326

### Description

Please describe your pull request.

Fixes #

Before submitting pull request, please review the following checklist:

- [ ] Make sure you have read our [CONTRIBUTING.md](https://github.com/phpmyadmin/phpmyadmin/blob/master/CONTRIBUTING.md) document.
- [ ] Make sure you are making a pull request against the correct branch. For example, for bug fixes in a released version use the corresponding QA branch and for new features use the _master_ branch. If you have a doubt, you can ask as a comment in the bug report or on the mailing list.
- [ ] Every commit has proper `Signed-off-by` line as described in our [DCO](https://github.com/phpmyadmin/phpmyadmin/blob/master/DCO). This ensures that the work you're submitting is your own creation.
- [ ] Every commit has a descriptive commit message.
- [ ] Every commit is needed on its own, if you have just minor fixes to previous commits, you can squash them.
- [ ] Any new functionality is covered by tests.

2020-10-10 21:12 UTC, williamdes requested changes
This needs to be downbased for 5.0

2020-10-10 21:12 UTC, williamdes commented on libraries/classes/Util.php
> +        $wktsql     = 'SELECT ' . $spatialAsText . "(x'" . $hex . "', 'axis-order=long-lat')";
Please refer to the other example in the code base to make this conditional :)

2020-10-12 06:55 UTC, shucon commented
Helpful for changing base branch : https://stackoverflow.com/questions/10853935/change-branch-base

2020-10-12 09:49 UTC, williamdes approved these changes
LGTM

Could you rebase (and squash) and add a test case to the test I added in 0f0dc09dee315a7ac494126dd89e89640ffd2eb5 please ?

2020-10-12 13:45 UTC, williamdes commented
Let me know so I can merge this one today if you intend to add a test case :)

2020-10-12 21:05 UTC, williamdes approved these changes
LGTM
Good catch on the phpdoc

2020-10-13 11:42 UTC, williamdes approved these changes

2020-10-13 11:47 UTC, merged