Open the Modify Row and Copy button to a new tab
phpmyadmin/phpmyadmin pull request #16444
Opened 2020-10-29 16:50 UTC by shucon

### Description

Please describe your pull request.

Fixes # https://github.com/phpmyadmin/phpmyadmin/issues/15413

Before submitting pull request, please review the following checklist:

- [ ] Make sure you have read our [CONTRIBUTING.md](https://github.com/phpmyadmin/phpmyadmin/blob/master/CONTRIBUTING.md) document.
- [ ] Make sure you are making a pull request against the correct branch. For example, for bug fixes in a released version use the corresponding QA branch and for new features use the _master_ branch. If you have a doubt, you can ask as a comment in the bug report or on the mailing list.
- [ ] Every commit has proper `Signed-off-by` line as described in our [DCO](https://github.com/phpmyadmin/phpmyadmin/blob/master/DCO). This ensures that the work you're submitting is your own creation.
- [ ] Every commit has a descriptive commit message.
- [ ] Every commit is needed on its own, if you have just minor fixes to previous commits, you can squash them.
- [ ] Any new functionality is covered by tests.

2020-11-01 22:42 UTC, williamdes commented on libraries/classes/InsertEdit.php
> +        } else if (isset($_GET['sql_query'])) {
You need to use the `sql_signature` method that is used in some parts of the code base to make this method secure

2020-11-02 10:21 UTC, williamdes commented on libraries/classes/Util.php
> +
```suggestion
```

2021-01-23 18:09 UTC, mauriciofauth reviewed
I'm not sure if I agree with this change. We are moving away from having SQLs in the URL, so I'm not comfortable with this.

2021-01-24 00:11 UTC, williamdes requested changes
I also am not too much a fan of this, some users have reported privacy concerns about private data in URLs

2021-04-23 23:26 UTC, closed without merging