Increase password characters limit during login
phpmyadmin/phpmyadmin pull request #16452
Opened 2020-11-02 20:23 UTC by kamilhristov

### Description

- allow logging in with longer passwords, for example tokens generated by AWS RDS IAM authentication

- show error message when the limit is reached instead of silently trimming the password to avoid confusion

Fixes https://github.com/phpmyadmin/phpmyadmin/issues/16451

Before submitting pull request, please review the following checklist:

- [ ] Make sure you have read our [CONTRIBUTING.md](https://github.com/phpmyadmin/phpmyadmin/blob/master/CONTRIBUTING.md) document.
- [ ] Make sure you are making a pull request against the correct branch. For example, for bug fixes in a released version use the corresponding QA branch and for new features use the _master_ branch. If you have a doubt, you can ask as a comment in the bug report or on the mailing list.
- [ ] Every commit has proper `Signed-off-by` line as described in our [DCO](https://github.com/phpmyadmin/phpmyadmin/blob/master/DCO). This ensures that the work you're submitting is your own creation.
- [ ] Every commit has a descriptive commit message.
- [ ] Every commit is needed on its own, if you have just minor fixes to previous commits, you can squash them.
- [ ] Any new functionality is covered by tests.

2020-11-02 23:30 UTC, williamdes approved these changes

2020-11-03 04:27 UTC, ibennetch requested changes
Nice work on this.

2020-11-03 07:36 UTC, williamdes approved these changes
Perfect

2020-11-04 03:03 UTC, ibennetch approved these changes

2020-11-04 09:10 UTC, williamdes commented
`less than 1000` I changed the operation from `>` to `>=`

2020-11-04 09:30 UTC, williamdes commented
I added an unit test in 16856d11251a88d7fd49af02bc747ef2dd44e21d

2020-11-04 09:31 UTC, merged