Get auto-saved query UX enhancement
phpmyadmin/phpmyadmin pull request #16456
Opened 2020-11-04 14:45 UTC by shucon

### Description

Please describe your pull request.

Fixes # https://github.com/phpmyadmin/phpmyadmin/issues/16046

Before submitting pull request, please review the following checklist:

- [ ] Make sure you have read our [CONTRIBUTING.md](https://github.com/phpmyadmin/phpmyadmin/blob/master/CONTRIBUTING.md) document.
- [ ] Make sure you are making a pull request against the correct branch. For example, for bug fixes in a released version use the corresponding QA branch and for new features use the _master_ branch. If you have a doubt, you can ask as a comment in the bug report or on the mailing list.
- [ ] Every commit has proper `Signed-off-by` line as described in our [DCO](https://github.com/phpmyadmin/phpmyadmin/blob/master/DCO). This ensures that the work you're submitting is your own creation.
- [ ] Every commit has a descriptive commit message.
- [ ] Every commit is needed on its own, if you have just minor fixes to previous commits, you can squash them.
- [ ] Any new functionality is covered by tests.

2020-11-11 22:18 UTC, mauriciofauth approved these changes

2020-11-15 19:30 UTC, williamdes approved these changes
So I have read the code once more and it seems like it is per table and not globally anymore.
The user is aware of that?

2020-11-15 20:03 UTC, shucon commented
> So I have read the code once more and it seems like it is per table and not globally anymore.
> The user is aware of that?

No, they don't. But the query gets erased once the user moves to another table before the patch, so I think it's nothing to be concerned about. What do you think?

2020-11-15 20:05 UTC, shucon commented
The Lint tests failed unexpectedly, give me a minute.

2020-11-15 20:22 UTC, williamdes commented
> > So I have read the code once more and it seems like it is per table and not globally anymore.
> > The user is aware of that?
> 
> No, they don't. But the query gets erased once the user moves to another table (before the patch), so I think it's nothing to be concerned about. What do you think?

Oh okay, then add some clue that is is per db or per db and table in the "get an autosaved" query no match found error.
What do you thing about that ?

2020-11-15 20:26 UTC, shucon commented
> > > So I have read the code once more and it seems like it is per table and not globally anymore.
> > > The user is aware of that?
> > 
> > 
> > No, they don't. But the query gets erased once the user moves to another table (before the patch), so I think it's nothing to be concerned about. What do you think?
> 
> Oh okay, then add some clue that is is per db or per db and table in the "get an autosaved" query no match found error.
> What do you thing about that ?

Yeah, we could do that. But we decided to remove that error altogether and only show the `Get auto-saved query` button incase a saved query is available.
Instead, we could change the button text to `Get auto-saved table query`?

2020-11-15 20:32 UTC, williamdes commented
> Yeah, we could do that. But we decided to remove that error altogether and only show the Get auto-saved query button incase a saved query is available.
Instead, we could change the button text to Get auto-saved table query?

Seems like I missed part of the diff on my mobile ..

`Get table auto-saved query` and `Get db auto-saved query` seem like a good option.
That said I think that an auto saved query can exist for the db and if one exists for the table the user needs to go to the db to get it.If this is right it is not very easy to use is case of db + table > db only. Maybe 2 buttons ?

cc @ibennetch

2020-11-15 20:42 UTC, shucon commented
> 
> `Get table auto-saved query` and `Get db auto-saved query` seem like a good option.
> That said I think that an auto saved query can exist for the db and if one exists for the table the user needs to go to the db to get it.If this is right it is not very easy to use is case of db + table > db only. Maybe 2 buttons ?
> 
> cc @ibennetch

Yes, two buttons would be a nice enhancement. Should we open an issue and discuss there?

2020-11-15 21:58 UTC, williamdes commented
> Yes, two buttons would be a nice enhancement. Should we open an issue and discuss there?

Here seems fine it is only a simple change, right ?

2021-06-21 16:45 UTC, mauriciofauth requested changes
This PR should target the `master` branch instead of `QA_5_1`.

2021-06-21 16:45 UTC, mauriciofauth commented on js/src/sql.js
> +    } else if (typeof Cookies.get(key) === 'string') {
This `else if` can be merged with previous `if`.

2021-06-21 16:45 UTC, mauriciofauth commented on js/src/sql.js
> +    $('#saved').hide();
Add the `d-none` CSS class instead of using the `.hide()` function.

2021-06-26 16:38 UTC, williamdes requested changes
Code looks okay, but I am not in favor of this because it hides a feature for the user.

2021-06-26 16:41 UTC, williamdes commented on js/src/sql.js
> +    $('#saved').addClass('d-none');
it removes the button, right ?
if yes, can it disable it ?

2021-06-26 16:51 UTC, shucon commented on js/src/sql.js
> +    $('#saved').addClass('d-none');
Showing the button but disabling it might cause some confusion.

2021-06-26 16:58 UTC, williamdes commented on js/src/sql.js
> +    $('#saved').addClass('d-none');
Removing the button may also cause confusion :/

2025-01-11 14:21 UTC, williamdes commented
Replaced by #19408

2025-01-11 14:21 UTC, closed without merging