README reworked
phpmyadmin/phpmyadmin pull request #16460
Opened 2020-11-06 18:02 UTC by comradekingu

### Description

Please describe your pull request.

Fixes #

Before submitting pull request, please review the following checklist:

- [ ] Make sure you have read our [CONTRIBUTING.md](https://github.com/phpmyadmin/phpmyadmin/blob/master/CONTRIBUTING.md) document.
- [ ] Make sure you are making a pull request against the correct branch. For example, for bug fixes in a released version use the corresponding QA branch and for new features use the _master_ branch. If you have a doubt, you can ask as a comment in the bug report or on the mailing list.
- [ ] Every commit has proper `Signed-off-by` line as described in our [DCO](https://github.com/phpmyadmin/phpmyadmin/blob/master/DCO). This ensures that the work you're submitting is your own creation.
- [ ] Every commit has a descriptive commit message.
- [ ] Every commit is needed on its own, if you have just minor fixes to previous commits, you can squash them.
- [ ] Any new functionality is covered by tests.

2020-11-06 19:58 UTC, Guileas requested changes

2020-11-06 19:58 UTC, Guileas commented on README.rst
> +https://www.phpmyadmin.net/ always has the newest release.
```suggestion
You can get the newest release at https://www.phpmyadmin.net/.
```

2020-11-06 19:58 UTC, Guileas commented on README.rst
> +More Info
```suggestion
More Information
```

2020-11-06 22:18 UTC, comradekingu commented on README.rst
> +https://www.phpmyadmin.net/ always has the newest release.
Harder to copy the link.

2020-11-06 22:18 UTC, comradekingu commented on README.rst
> +More Info
This is just longer for no good reason.

2020-11-06 23:49 UTC, ibennetch requested changes
Thanks for your submission, I have a few suggestions.

2021-01-24 14:30 UTC, Guileas commented on README.rst
> +For `support <https://www.phpmyadmin.net/support/>`_ or information on contributing code or `translating phpMyAdmin to your language <https://hosted.weblate.org/projects/phpmyadmin/>`_,
```suggestion
For `support <https://www.phpmyadmin.net/support/>`_ or information concerning code contribution or `translating phpMyAdmin to your language <https://hosted.weblate.org/projects/phpmyadmin/>`_,
```

2021-01-24 14:36 UTC, comradekingu commented on README.rst
> +For `support <https://www.phpmyadmin.net/support/>`_ or information on contributing code or `translating phpMyAdmin to your language <https://hosted.weblate.org/projects/phpmyadmin/>`_,
The two latter ones are more of the same type of thing, whereas the change makes it more three distinct things (?)

2021-02-09 11:05 UTC, shucon commented on README.rst
> +If you are into code you can read the `code contribution file <CONTRIBUTING.md>`_ or browse our website `contributing page <https://www.phpmyadmin.net/contribute/>`_.
If you would like to contribute to the phpMyAdmin's codebase, you can read the `code contribution file <CONTRIBUTING.md>`_ or browse our website's contributing page <https://www.phpmyadmin.net/contribute/>`_.

Looks better.

2021-02-09 11:08 UTC, williamdes commented on README.rst
> +If you are into code you can read the `code contribution file <CONTRIBUTING.md>`_ or browse our website `contributing page <https://www.phpmyadmin.net/contribute/>`_.
Awesome !

2021-02-09 11:11 UTC, shucon commented
LGTM

2021-02-09 11:13 UTC, shucon approved these changes

2021-02-09 11:14 UTC, Guileas approved these changes

2021-02-09 11:14 UTC, williamdes approved these changes

2021-02-09 11:23 UTC, merged