Fix Theme Generator
phpmyadmin/phpmyadmin pull request #16474
Opened 2020-11-10 15:10 UTC by shucon

Signed-off-by: Saksham Gupta <shucon01@gmail.com>

### Description

Please describe your pull request.

Fixes # https://github.com/phpmyadmin/phpmyadmin/issues/14933

Before submitting pull request, please review the following checklist:

- [ ] Make sure you have read our [CONTRIBUTING.md](https://github.com/phpmyadmin/phpmyadmin/blob/master/CONTRIBUTING.md) document.
- [ ] Make sure you are making a pull request against the correct branch. For example, for bug fixes in a released version use the corresponding QA branch and for new features use the _master_ branch. If you have a doubt, you can ask as a comment in the bug report or on the mailing list.
- [ ] Every commit has proper `Signed-off-by` line as described in our [DCO](https://github.com/phpmyadmin/phpmyadmin/blob/master/DCO). This ensures that the work you're submitting is your own creation.
- [ ] Every commit has a descriptive commit message.
- [ ] Every commit is needed on its own, if you have just minor fixes to previous commits, you can squash them.
- [ ] Any new functionality is covered by tests.

2020-11-10 15:28 UTC, williamdes commented on config.sample.inc.php
> +//$cfg['ThemeGenerator'] = 'false';
```suggestion
  * default = false
  */
$cfg['ThemeGenerator'] = false;
```

2020-11-10 15:30 UTC, williamdes commented on doc/config.rst
> +
```suggestion
.. config:option:: $cfg['ThemeGenerator']
    :type: boolean
    :default: false
    .. versionadded:: 5.1.0
    Whether to enable the theme generator.

```

b2c885908d69cc604a0de7ec7e080b9b53ca6630 can help you

Also do try your changes by `cd doc/ && make html` and then just browse the path on your favorite browser

2020-11-10 15:30 UTC, williamdes commented on libraries/classes/Controllers/HomeController.php
> +        $themeGenerator = '';
```suggestion
```

2020-11-10 15:32 UTC, williamdes commented
Let me know if you prefer to copy changes from https://github.com/phpmyadmin/phpmyadmin/tree/gsoc-theme-generator, merge or whatever.
I would like the changes to be merged and delete the branch ;)

2020-11-10 15:37 UTC, williamdes commented
Also be sure to be compatible with https://github.com/phpmyadmin/phpmyadmin/issues/16418 
I would understand users hating the fact that they have a theme generator in production not being able to delete the source files for it.

2020-11-10 16:23 UTC, shucon commented
> Let me know if you prefer to copy changes from https://github.com/phpmyadmin/phpmyadmin/tree/gsoc-theme-generator, merge or whatever.
> I would like the changes to be merged and delete the branch ;)

I'll copy stuff from `gsoc-theme-generator` branch manually. There's been a lot of changes and it's been a long time since I wrote that code, so I might need to make comparisions several times.

2020-11-11 22:48 UTC, williamdes commented on js/src/theme_generator/preview.js
> +/* vim: set expandtab sw=4 ts=4 sts=4: */
```suggestion
```

2020-11-11 23:00 UTC, williamdes commented on templates/theme_generator/form.twig
> +  &nbsp; Font :<br>
missing translation

2020-11-11 23:01 UTC, williamdes commented on templates/theme_generator/group_preview.twig
> +  <h2>Preview Panel</h2>
missing translation

2020-11-11 23:01 UTC, williamdes commented on templates/theme_generator/group_preview.twig
> +        <option value="">Collation</option>
same ?

2020-11-11 23:01 UTC, williamdes commented on templates/theme_generator/group_preview.twig
> +        <img src="themes/dot.gif" title="" alt="" class="icon ic_s_passwd">&nbsp;Change password
here also :)

2020-11-11 23:01 UTC, williamdes commented on js/src/theme_generator/color_picker.js
> +/* vim: set expandtab sw=4 ts=4 sts=4: */
```suggestion
```

2020-11-12 14:21 UTC, williamdes commented on libraries/classes/ThemeGenerator.php
> +/* vim: set expandtab sw=4 ts=4 sts=4: */
```suggestion
```

2020-11-12 14:21 UTC, williamdes commented on libraries/classes/ThemeGenerator/Common.php
> +        $file = fopen('themes/' . $name . '/scss/_common.scss', 'w');
You can use file_get_contents and file_put_contents

2020-11-12 14:22 UTC, williamdes commented on templates/theme_generator/form.twig
> +  &nbsp; {% trans 'URL' %} :<br>
```suggestion
  &nbsp; {% trans 'URL :' %}<br>
```
Same for all lines above :)

2020-11-12 14:22 UTC, williamdes commented on templates/theme_generator/form.twig
> +<form action="theme_generator.php" method="post" id="save">
You should use the router

2020-11-15 10:24 UTC, williamdes commented on libraries/classes/Controllers/ThemeGeneratorController.php
> +require_once 'libraries/common.inc.php';
Is this needed @mauriciofauth?

2020-11-15 10:26 UTC, williamdes commented on libraries/classes/ThemeGenerator.php
> +        $file = fopen("themes/" . $name . "/theme.json", "w");
This looks like a security risk
Maybe you should check that it is a file before `file_get_contents`.
And then you can use an array and `json_encode`

2020-11-15 13:32 UTC, williamdes commented on libraries/classes/ThemeGenerator.php
> +            @mkdir("themes/" . $name . "/css");
I think this is dangerous is we do not check the theme name

2020-11-28 11:09 UTC, williamdes commented on templates/theme_generator/color_picker.twig
> +          <div class="card-header">Colour Palette </div>
Some translations are missing in this file

2020-12-15 14:59 UTC, williamdes commented on libraries/classes/ThemeGenerator/Variables.php
> +            fwrite($file, $txt);
You should use file_put_contents

2020-12-18 14:50 UTC, shucon commented on libraries/classes/ThemeGenerator.php
> +        $name = $post['theme_name'];
The security risks are being handled here.

2020-12-18 22:32 UTC, williamdes commented on libraries/classes/ThemeGenerator.php
> +        $name = $post['theme_name'];
```suggestion
        $name = Sanitize::sanitizeFilename($post['theme_name'], true);
        unset($post['theme_name']);
```

2020-12-20 16:21 UTC, shucon commented
Hey @williamdes , it's working now. Needs a few tweaks but you can play around in the meantime.

2020-12-21 15:32 UTC, shucon commented
Screenshot preview of the theme generator : 
![Screenshot from 2020-12-21 21-01-59](https://user-images.githubusercontent.com/22860775/102793411-dffb1f00-43cf-11eb-8764-1e42f9667f8b.png)

2020-12-21 19:43 UTC, williamdes commented on libraries/classes/ThemeGenerator.php
> +    public function tablePreview()
```suggestion
     */
    public function tablePreview(): string
```

2020-12-21 19:43 UTC, williamdes commented on libraries/classes/ThemeGenerator.php
> +    public function recurse_copy($src,$dst) {
```suggestion
     * @param string $dst Destination path of the directory
     *
     */
    public function recurse_copy(string $src, string $dst): void {
```

2020-12-21 19:44 UTC, williamdes commented on libraries/classes/ThemeGenerator.php
> +                    copy($src . '/' . $file,$dst . '/' . $file);
```suggestion
                if ( is_dir($src . DIRECTORY_SEPARATOR . $file) ) {
                    $this->recurse_copy($src . DIRECTORY_SEPARATOR . $file, $dst . DIRECTORY_SEPARATOR . $file);
                }
                else {
                    copy($src . DIRECTORY_SEPARATOR . $file, $dst . DIRECTORY_SEPARATOR . $file);
```

2020-12-21 19:45 UTC, williamdes commented on libraries/classes/ThemeGenerator.php
> +        $out = array();
```suggestion
     * @return array<string,string> SCSS file data
     */
    public function getScssFile(): array {
        $out = [];
```

2020-12-22 09:29 UTC, williamdes requested changes
All the new functions must use php typehints :)

2020-12-22 10:52 UTC, shucon commented on libraries/classes/Controllers/ThemeGeneratorController.php
> +                                '</a>'
@williamdes I don't know why this message is not being displayed. Any ideas?

2020-12-22 11:21 UTC, williamdes commented on libraries/classes/ThemeGenerator.php
> +        $txt = '{';
You must use json_encode :)

2020-12-22 11:22 UTC, williamdes commented on templates/theme_generator/table_preview.twig
> +          <td class="center print_ignore"><span class="nowrap"><a href="#" ><span class="nowrap"><img src="themes/dot.gif" title="Copy" alt="Copy" class="icon ic_b_insrow">{% trans 'Copy' %}</span></
title and alt must also use trans

2020-12-22 11:23 UTC, williamdes commented on libraries/classes/ThemeGenerator.php
> +        @mkdir($dst);
All the ignore errors and warnings are not the best practice, if you can avoid them please do so

2020-12-22 11:24 UTC, williamdes commented on libraries/classes/Controllers/ThemeGeneratorController.php
> +                $file = file_put_contents('themes/' . $name . '/css/' . $generateFiles[$_POST['count']], $_POST['CSS_file'], LOCK_EX);
I think this can lead to overriting system files

2020-12-22 11:28 UTC, williamdes commented on libraries/classes/Controllers/ThemeGeneratorController.php
> +                                '</a>'
I think you need some logic in the front end to handle the error response
Maybe you are missing a set call on the php code to set the response as failed

2020-12-22 11:30 UTC, williamdes commented on libraries/classes/ThemeGenerator.php
> +        if (! is_writable('themes')) {
Alll the file logic should not use a relative path
Please use a vendor constant to be sure you use static paths

2020-12-22 12:28 UTC, shucon commented on libraries/classes/ThemeGenerator.php
> +        $txt = '{';
Nice catch! Thanks :D

2020-12-22 12:47 UTC, shucon commented on libraries/classes/ThemeGenerator.php
> +        if (! is_writable('themes')) {
I'm not entirely sure what this means and what's a vendor constant?

2020-12-22 16:06 UTC, williamdes commented on libraries/classes/ThemeGenerator.php
> +        if (! is_writable('themes')) {
You can see that some are defined here: https://github.com/phpmyadmin/phpmyadmin/blob/master/libraries/vendor_config.php

But you should use the `ROOT_PATH` for your scripts (IMO)

2020-12-24 14:16 UTC, shucon commented on libraries/classes/Controllers/ThemeGeneratorController.php
> +                                '</a>'
I can think of two ways, either refresh the page and show the messages and warnings (how it is generally done now) or make changes to the `Message:success` functions to support id's in HTML tags of messages so that it can be handled using Javascript (better IMO because of no reloads but a bit more ambitious, but might help in the future).

2020-12-24 14:16 UTC, shucon commented on libraries/classes/Controllers/ThemeGeneratorController.php
> +                                '</a>'
What do you think?

2021-01-01 14:46 UTC, williamdes commented on libraries/classes/Controllers/ThemeGeneratorController.php
> +                                '</a>'
why cant you handle the errors/messages on the js responses ?

2021-01-01 14:46 UTC, williamdes commented on libraries/classes/ThemeGenerator.php
> +     */
```suggestion
```

2021-01-01 14:47 UTC, williamdes commented on libraries/classes/ThemeGenerator.php
> +        $data['version'] = "5.0";
This hard coded string does not feel right, please change that

2021-01-01 14:48 UTC, williamdes commented on templates/theme_generator/table_preview.twig
> +      <table  width="100%" class="table_results ajax pma_table" data-uniqueid="510480552">
I think pma_table does not exist anymore like that
And `data-uniqueid` is useless

2021-01-01 14:48 UTC, williamdes commented on templates/theme_generator/table_preview.twig
> +                <img class="fulltext" src="./themes/pmahomme/img/s_fulltext.png" alt="{% trans 'Full Texts' %}" title="{% trans 'Full Texts' %}">
dont we have functions to build icons ?

2021-01-01 14:50 UTC, williamdes requested changes
Could you please let us know where you did find each icon in  `themes/pmahomme/img/theme_generator/*` the license and a link to verify that

2021-01-03 12:29 UTC, shucon commented
> Could you please let us know where you did find each icon in `themes/pmahomme/img/theme_generator/*` the license and a link to verify that

I took the images and color picker from here: https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Colors/Color_picker_tool#ColorPicker_tool

2021-01-03 13:08 UTC, williamdes commented
> > Could you please let us know where you did find each icon in `themes/pmahomme/img/theme_generator/*` the license and a link to verify that
> 
> I took the images and color picker from here: https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Colors/Color_picker_tool#ColorPicker_tool

https://github.com/mdn/content/blob/main/LICENSE.md

Could you make me a list of each file (URL) you copied from the tool in https://github.com/mdn/content please ?

2021-01-04 12:40 UTC, shucon commented
https://docs.google.com/document/d/1K4Lok7LjT5biMWKdtTNVN7xefX7076VxEHNyoXPqPn0/edit

2021-01-04 14:34 UTC, shucon commented on libraries/classes/ThemeGenerator.php
> +        $data['version'] = "5.0";
What do you suggest?

2021-01-04 20:13 UTC, williamdes commented on libraries/classes/Controllers/ThemeGeneratorController.php
> +require_once 'libraries/common.inc.php';
@shucon

2021-01-05 08:33 UTC, shucon commented on libraries/classes/Controllers/ThemeGeneratorController.php
> +require_once 'libraries/common.inc.php';
I think it isn't required. I have removed it.

2021-01-05 08:52 UTC, shucon commented on templates/theme_generator/table_preview.twig
> +                <img class="fulltext" src="./themes/pmahomme/img/s_fulltext.png" alt="{% trans 'Full Texts' %}" title="{% trans 'Full Texts' %}">
We do have functions, but they are not ideal to be used here as this is a preview table.

2021-01-10 11:20 UTC, shucon commented on libraries/classes/Controllers/ThemeGeneratorController.php
> +                    $response->addHTML('<script>document.getElementById("success_theme_saved").style.display = "block"</script>');
I'm unable to trigger Success notification once I'm done generating all the theme files. I tried adding acript to trigger display, using `addjson`, and sending POST requesrs but nothing seems to work. Can someone please help me with this?
cc- @mauriciofauth @ibennetch

2022-04-21 18:15 UTC, mauriciofauth commented
Closing this in favor of https://github.com/phpmyadmin/phpmyadmin/issues/17487.

2022-04-21 18:15 UTC, closed without merging