Remove depricated FOUND_ROWS()
phpmyadmin/phpmyadmin pull request #16470
Opened 2020-11-08 19:20 UTC by shucon

Signed-off-by: Saksham Gupta <shucon01@gmail.com>

### Description

Please describe your pull request.

Fixes: https://github.com/phpmyadmin/phpmyadmin/issues/15652

Before submitting pull request, please review the following checklist:

- [ ] Make sure you have read our [CONTRIBUTING.md](https://github.com/phpmyadmin/phpmyadmin/blob/master/CONTRIBUTING.md) document.
- [ ] Make sure you are making a pull request against the correct branch. For example, for bug fixes in a released version use the corresponding QA branch and for new features use the _master_ branch. If you have a doubt, you can ask as a comment in the bug report or on the mailing list.
- [ ] Every commit has proper `Signed-off-by` line as described in our [DCO](https://github.com/phpmyadmin/phpmyadmin/blob/master/DCO). This ensures that the work you're submitting is your own creation.
- [ ] Every commit has a descriptive commit message.
- [ ] Every commit is needed on its own, if you have just minor fixes to previous commits, you can squash them.
- [ ] Any new functionality is covered by tests.

2020-11-08 21:34 UTC, williamdes commented on libraries/classes/Sql.php
> +                $count_query .= Query::getClause($statement, $token_list, $clause, 'ORDER BY', false);
Could you move this to `Query\Generator` and write unit tests for this ?
Because just reading the code I do not understand what it does :/

2020-11-09 13:40 UTC, williamdes reviewed
This is a way more clean fix, thank you !
I hope another team member can review this one

2020-11-11 14:24 UTC, mauriciofauth requested changes

2020-11-11 14:24 UTC, mauriciofauth commented on libraries/classes/Sql.php
> +                $unlim_num_rows = mysqli_num_rows($this->dbi->tryQuery($count_query));
You should not use mysqli functions directly. You can use `$this->dbi->numRows($this->dbi->tryQuery($count_query))` instead.

2020-11-11 16:30 UTC, mauriciofauth requested changes

2020-11-11 16:30 UTC, mauriciofauth commented on libraries/classes/Sql.php
> +use function mysqli_num_rows;
```suggestion
```

2020-11-11 17:34 UTC, shucon commented on libraries/classes/Sql.php
> +use function mysqli_num_rows;
Ahh, sorry. Generally, my IDE takes care of it so I didn't pay attention to it.

2020-11-11 20:50 UTC, mauriciofauth approved these changes

2020-11-12 09:09 UTC, williamdes commented on libraries/classes/Sql.php
> +                    // Removes LIMIT clause that might have been added
@shucon I am unsure why you remove the LIMIT every time, do you know ?

The previous code was adding one for one use case
```php
                // Another LIMIT clause is added to avoid long delays.
                // A complete result will be returned anyway, but the LIMIT would
                // stop the query as soon as the result that is required has been
                // computed.

                if (empty($analyzed_sql_results['union'])) {
                    $count_query .= ' LIMIT 1';
                }

```

If this is resolved, LGTM for the diff

2020-11-12 11:40 UTC, shucon commented on libraries/classes/Sql.php
> +                    // Removes LIMIT clause that might have been added
The LIMIT clause is removed because it was mentioned in the comments of the function description: `Function to count the total number of rows for the same 'SELECT' query without the 'LIMIT' clause that may have been programatically added` .

I think it was added to `SQL_CALC_FOUND_ROWS` for some performance enhancement as mentioned in the comment above it. Or it might be some MySQL issue with `SQL_CALC_FOUND_ROWS` as mentioned in https://stackoverflow.com/questions/47407046/sql-calc-found-rows-with-found-rows-always-returns-1 .

2020-11-12 11:42 UTC, williamdes commented on libraries/classes/Sql.php
> +                    // Removes LIMIT clause that might have been added
Thank you :)

2020-11-12 11:42 UTC, williamdes approved these changes

2020-11-12 11:57 UTC, merged

2021-07-22 11:34 UTC, fliespl commented
This solution is not a direct replacement of found_rows() as one would expect. It generated random results even on such queries:

 Showing rows 0 - 49 (164056 total, 0 in query, Query took 0.1498 seconds.)
```select * from game_auth_logs l join ( select al.user_id, max(al.id) as id from game_auth_logs al where al.successfull = 1 group by al.user_id ) last_log on last_log.id = l.id;```

Showing rows 0 - 24 (267 total, Query took 0.1533 seconds.)
```select l.* from game_auth_logs l join ( select al.user_id, max(al.id) as id from game_auth_logs al where al.successfull = 1 group by al.user_id ) last_log on last_log.id = l.id;```

Notice that only change was start or alias select.



I think it should be configurable to allow how total rows is count.

Mysql as a replacement proposes running two queries:

```
The SQL_CALC_FOUND_ROWS query modifier and accompanying FOUND_ROWS() function are deprecated as of MySQL 8.0.17; expect them to be removed in a future version of MySQL. As a replacement, considering executing your query with LIMIT, and then a second query with COUNT(*) and without LIMIT to determine whether there are additional rows. For example, instead of these queries:
```

2021-07-22 12:23 UTC, williamdes commented
> This solution is not a direct replacement of found_rows() as one would expect. It generated random results even on such queries:
> 
> Showing rows 0 - 49 (164056 total, 0 in query, Query took 0.1498 seconds.)
> `select * from game_auth_logs l join ( select al.user_id, max(al.id) as id from game_auth_logs al where al.successfull = 1 group by al.user_id ) last_log on last_log.id = l.id;`
> 
> Showing rows 0 - 24 (267 total, Query took 0.1533 seconds.)
> `select l.* from game_auth_logs l join ( select al.user_id, max(al.id) as id from game_auth_logs al where al.successfull = 1 group by al.user_id ) last_log on last_log.id = l.id;`
> 
> Notice that only change was star or alias select.
> 
> I think it should be configurable to allow end user to decide how total rows is count.
> 
> Mysql as a replacement proposes running two queries:
> 
> ```
> The SQL_CALC_FOUND_ROWS query modifier and accompanying FOUND_ROWS() function are deprecated as of MySQL 8.0.17; expect them to be removed in a future version of MySQL. As a replacement, considering executing your query with LIMIT, and then a second query with COUNT(*) and without LIMIT to determine whether there are additional rows. For example, instead of these queries:
> ```

What version of phpMyAdmin are you running ?

2021-07-22 12:59 UTC, fliespl commented
5.1.1