Replace style image with Linear-gradient
phpmyadmin/phpmyadmin pull request #16513
Opened 2020-12-03 18:09 UTC by shucon

### Description

Replace style image with Linear-gradient

Before submitting pull request, please review the following checklist:

- [ ] Make sure you have read our [CONTRIBUTING.md](https://github.com/phpmyadmin/phpmyadmin/blob/master/CONTRIBUTING.md) document.
- [ ] Make sure you are making a pull request against the correct branch. For example, for bug fixes in a released version use the corresponding QA branch and for new features use the _master_ branch. If you have a doubt, you can ask as a comment in the bug report or on the mailing list.
- [ ] Every commit has proper `Signed-off-by` line as described in our [DCO](https://github.com/phpmyadmin/phpmyadmin/blob/master/DCO). This ensures that the work you're submitting is your own creation.
- [ ] Every commit has a descriptive commit message.
- [ ] Every commit is needed on its own, if you have just minor fixes to previous commits, you can squash them.
- [ ] Any new functionality is covered by tests.

2020-12-03 18:43 UTC, williamdes approved these changes

2020-12-07 00:09 UTC, williamdes approved these changes
I made the changes on all themes, but another review can be necessary to avoid mistakes

2020-12-08 01:02 UTC, mauriciofauth requested changes

2020-12-08 08:54 UTC, shucon commented on setup/styles.css
> +  background: linear-gradient(to right, #f3f3f3, #dadcde);
Hey @mauriciofauth , I'm not entirely sure where this particular style is being used. Can you please tell me where can I find it so that I can verify my changes?

2020-12-08 09:04 UTC, williamdes commented on setup/styles.css
> +  background: linear-gradient(to right, #f3f3f3, #dadcde);
You know what it is maybe not correct from a syntax point (and that would need a fix) but it works (if I disable you can see a change).
@shucon You can sompare https://demo.phpmyadmin.net/master/setup/ and my screenshot to see what to fix.
On any phpMyAdmin instance you can find it a /setup/
I recommend you to use `$cfg['DBG']['demo'] = true;` to have an easy access
![setup body](https://user-images.githubusercontent.com/7784660/101462365-71808080-393c-11eb-931f-e6128cce5f46.png)

2020-12-08 12:43 UTC, mauriciofauth commented on setup/styles.css
> +  background: linear-gradient(to right, #f3f3f3, #dadcde);
I didn't test it, but you will probably have to use the `background-size` property.

2020-12-08 12:46 UTC, mauriciofauth commented on setup/styles.css
> +  background: linear-gradient(to right, #f3f3f3, #dadcde);
I didn't test it, but you will probably have to use the `background-size` property here.

2020-12-09 10:20 UTC, shucon commented on setup/styles.css
> +  background: linear-gradient(to right, #f3f3f3, #dadcde);
Hey, after these changes it looks almost similar to me. What do you think?

2020-12-30 17:26 UTC, mauriciofauth approved these changes

2020-12-30 18:16 UTC, merged