fixes White on gray text on check table status results
phpmyadmin/phpmyadmin pull request #16561
Opened 2021-01-10 15:52 UTC by ujjwal-batra

Signed-off-by: ujjwal <ujjwal24batra@gmail.com>

### Description

Fixes grey checkboxes when checked.

Fixes #16552 

Before submitting pull request, please review the following checklist:

- [x] Make sure you have read our [CONTRIBUTING.md](https://github.com/phpmyadmin/phpmyadmin/blob/master/CONTRIBUTING.md) document.
- [x] Make sure you are making a pull request against the correct branch. For example, for bug fixes in a released version use the corresponding QA branch and for new features use the _master_ branch. If you have a doubt, you can ask as a comment in the bug report or on the mailing list.
- [x] Every commit has proper `Signed-off-by` line as described in our [DCO](https://github.com/phpmyadmin/phpmyadmin/blob/master/DCO). This ensures that the work you're submitting is your own creation.
- [x] Every commit has a descriptive commit message.
- [x] Every commit is needed on its own, if you have just minor fixes to previous commits, you can squash them.
- [ ] Any new functionality is covered by tests.

2021-02-21 01:13 UTC, williamdes commented on themes/pmahomme/scss/_common.scss
> +  &:checked[type=checkbox]{
Sorry for the review delay, the other themes did not need this fix ?

2021-02-21 05:37 UTC, ujjwal-batra commented on themes/pmahomme/scss/_common.scss
> +  &:checked[type=checkbox]{
@williamdes yeah i Checked for other themes they dknt need this fix.

2021-02-25 18:45 UTC, ujjwal-batra commented
@williamdes is there any change required further ?

2021-02-25 18:49 UTC, williamdes commented
> @williamdes is there any change required further ?

Nope, I am testing your fix ^^
I will push a rebase and squash commit before merging

2021-02-25 19:05 UTC, williamdes requested changes
I am not sure this is the right fix, it seems like `form-check-input` classes are the problem here

2021-02-25 19:16 UTC, ujjwal-batra commented
@williamdes okay i will look into it

2021-02-26 12:43 UTC, closed without merging