Improve the version handling
phpmyadmin/phpmyadmin pull request #16584
Opened 2021-01-20 21:51 UTC by williamdes

This PR is to improve the Version handling and what goes with it.

2021-01-22 16:37 UTC, mauriciofauth commented on scripts/create-release.sh
> +    php -r "require_once('libraries/classes/Version.php'); echo \PhpMyAdmin\Version::phpMyAdminVersion();"
I think `VERSION_SUFFIX` will never be defined here.

2021-01-22 16:37 UTC, mauriciofauth commented on libraries/classes/Version.php
> +            return $versionRaw . '-' . self::PRE_RELEASE_NAME . self::PRE_RELEASE_NUMBER;
I think we could remove `IS_DEV` and `IS_PRE_RELEASE`, then add `dev` to `PRE_RELEASE_NAME` and only concatenate `PRE_RELEASE_NUMBER` if it is different than 0. Or drop `PRE_RELEASE_NUMBER` completely and add the number to  `PRE_RELEASE_NAME`. I think this will simplify the script.

2021-01-22 17:36 UTC, williamdes commented on scripts/create-release.sh
> +    php -r "require_once('libraries/classes/Version.php'); echo \PhpMyAdmin\Version::phpMyAdminVersion();"
Indeed, It is only for packaging people to not do this https://salsa.debian.org/phpmyadmin-team/phpmyadmin/-/blob/debian/latest/debian/rules#L47 but change the vendor constant

2021-02-05 22:07 UTC, mauriciofauth commented on libraries/classes/Version.php
> +    public const IS_PRE_RELEASE = false;
I started to think that `IS_DEV` and `IS_PRE_RELEASE` will only add unnecessary steps to the Release Manager (as we can see in the `create-release.sh` script). If we need those boolean values, we can determine they based on `PRE_RELEASE_NAME` value.

2021-02-05 22:07 UTC, mauriciofauth commented on libraries/classes/Version.php
> +            return $versionRaw . VERSION_SUFFIX;
Is intended to only add `VERSION_SUFFIX` on released versions?

2021-02-05 22:10 UTC, mauriciofauth commented on libraries/classes/Version.php
> +    public const PRE_RELEASE_NAME = '';
```suggestion
    public const PRE_RELEASE_NAME = 'rc1';
```

https://github.com/phpmyadmin/phpmyadmin/blob/ffbebaa8a27e646e90d658515e703da9fbb2596b/libraries/classes/Config.php#L139

2021-02-05 22:11 UTC, williamdes commented on libraries/classes/Version.php
> +            return $versionRaw . VERSION_SUFFIX;
Yes, it is only for people packaging the final version ;)

2021-02-05 22:13 UTC, williamdes commented on libraries/classes/Version.php
> +    public const IS_PRE_RELEASE = false;
I agree to in another hand this will make any simple code detection harder.
Let me know if you want me to proceed removing `IS_PRE_RELEASE` ?

But for `IS_DEV` it is too important to be removed (in a tools detection perspective)

My point is: people will build bad script parsing a version management they do not know, booleans are explicit ;p

2021-02-05 22:15 UTC, williamdes commented on libraries/classes/Routing.php
> +            'cacheDisabled' => ($cfg['environment'] ?? '') === 'development' || Version::isDev(),
Yes, devs, contributors, testers are not setting `environment` and fall into caching issues we have to handle afterwards on the GitHub issues.
It want to short circuit the problem: if DEV = routes can change = no cache

2021-02-05 22:22 UTC, mauriciofauth commented on libraries/classes/Routing.php
> +            'cacheDisabled' => ($cfg['environment'] ?? '') === 'development' || Version::isDev(),
We should improve the cache cleanup and warmup instead of disabling the cache for everyone. This way we can not enable cache in development environments.

2021-02-05 22:24 UTC, williamdes commented on libraries/classes/Routing.php
> +            'cacheDisabled' => ($cfg['environment'] ?? '') === 'development' || Version::isDev(),
For sure !
See https://github.com/nikic/FastRoute/issues/224 upstream

2021-02-05 23:09 UTC, ibennetch commented on libraries/classes/Version.php
> +    public const IS_PRE_RELEASE = false;
I would tend to agree with @mauriciofauth about this, but @williamdes has a valid point, too. I would leave IS_DEV in, but remove IS_PRE_RELEASE and refactor that check to see whether `PRE_RELEASE_NAME` is empty instead of also having the IS_PRE_RELEASE boolean. It's pretty minor in the scheme of things, so I won't insist on changing it.

2021-02-05 23:10 UTC, ibennetch commented
🤷‍♂️

I like the refactoring in general, but this seems to me to be a little complex. Still, it's an improvement, and I don't have any better idea, so go for it!

2021-02-05 23:20 UTC, williamdes commented on libraries/classes/Version.php
> +    public const PRE_RELEASE_NAME = '';
This will have to be filled in when releasing, for now it should be empty

2021-02-05 23:21 UTC, williamdes commented
> I like the refactoring in general, but this seems to me to be a little complex. Still, it's an improvement, and I don't have any better idea, so go for it!

Thank you for the review !, I simplified slightly the code as you 2 suggested


@mauriciofauth do you agree that I merge this PR or do you have some more comments to do on it ?

2021-02-06 00:01 UTC, mauriciofauth commented
> do you agree that I merge this PR or do you have some more comments to do on it ?

@williamdes I just thought that we can have all those constants, but instead of manually update them, we can create a `scripts/console` command to auto-generate this class. This way we can have the version strings as constants as well.

2021-02-06 00:04 UTC, ibennetch commented
I was going to rework scripts/set-versions.sh to make this a bit less of a
manual process, but you’re welcome to jump on it too.

2021-02-06 00:06 UTC, williamdes commented
That seems like a good idea, not sure how I will do the automation but that will help for sure
Will work on that in some days more or less

2021-02-06 00:11 UTC, mauriciofauth commented on libraries/classes/Routing.php
> +            'cacheDisabled' => ($cfg['environment'] ?? '') === 'development' || Version::isDev(),
I really don't like this change and the Template class as well. Having both sides of the Or operator doesn't make sense to me, because you should not set `$cfg['environment']` to `'development'` if you are not in a development version.

We should improve the documentation about the `$cfg['environment']` setting and improve the cache cleanup and warmup as I said before.

2021-02-06 00:14 UTC, williamdes commented on libraries/classes/Routing.php
> +            'cacheDisabled' => ($cfg['environment'] ?? '') === 'development' || Version::isDev(),
I understand and will revert the two changes
I agree we should try to fix this warm-up issue in another better way

2021-02-06 00:22 UTC, mauriciofauth commented
> I was going to rework scripts/set-versions.sh to make this a bit less of a manual process, but you’re welcome to jump on it too.

We could migrate this script to that new command as well.

> Will work on that in some days more or less

I can help you with that if you want.

2021-02-06 00:29 UTC, williamdes commented
> I can help you with that if you want.

Sure, you can push commits there or create a new PR

After a night of sleep I will have a day of driving so meanwhile you can do what seems best to you :) 

Just asking myself how we will manage the input of giving the version to the script to be parsed and re-built into constants

2021-02-06 14:37 UTC, ibennetch commented
> We could migrate this script to that new command as well.

I'm rather ignorant about the advantages of using scripts/console over the
shell script; is there something that makes that a better choice than a
shell script?

2021-02-06 17:59 UTC, mauriciofauth commented
> I'm rather ignorant about the advantages of using scripts/console over the shell script; is there something that makes that a better choice than a shell script?

Actually, we can add the `./scripts/console set-version 5.1.0-dev` line to the `set-version.sh` script and avoid having to migrate a shell script to PHP.

2021-02-06 18:15 UTC, mauriciofauth commented
I pushed the commit that adds the class generator. I renamed some constants to remove the redundant version word and I added the ID constant as well but I don't know if we'll going to use it or not.

2021-02-06 21:16 UTC, williamdes commented on libraries/classes/Command/SetVersionCommand.php
> +
why not using file_put_contents ?

2021-02-06 21:22 UTC, williamdes commented
I like the changes you made
We need to:
- Have a lot of tests on the generation
- Correctness of the file, `php -l`
- Be sure to run the test suite **after** the version file has been generated

> I renamed some constants to remove the redundant version word and I added the ID constant as well but I don't know if we'll going to use it or not.

I think an important point is not if we will use it but if someone else will use it ;)

> I'm rather ignorant about the advantages of using scripts/console over the
shell script; is there something that makes that a better choice than a
shell script?

Nothing is better than a shell script and my point for that are:
- It never dies
- Is never deprecated
- Does not require any language to be setup
- Nobody does breaking changes to it (as far as I know)
- Does not require anybody to know a higher level of programming language and its specifics behaviors

2021-02-08 17:58 UTC, mauriciofauth commented on libraries/classes/Command/SetVersionCommand.php
> +
Good idea. For this case is a better idea to use it.

2021-02-08 18:02 UTC, mauriciofauth requested changes

2021-02-08 18:02 UTC, mauriciofauth commented on scripts/create-release.sh
> +    php -r "require_once('libraries/classes/Version.php'); echo \PhpMyAdmin\Version::phpMyAdminVersion();"
```suggestion
    php -r "require_once('libraries/classes/Version.php'); echo \PhpMyAdmin\Version::VERSION;"
```

2021-02-08 18:02 UTC, mauriciofauth commented on scripts/create-release.sh
> +                - change PRE_RELEASE_NAME to "rc1"
This should be updated.

2021-02-08 18:02 UTC, mauriciofauth commented on scripts/create-release.sh
> +            - change PRE_RELEASE_NAME to "rc1"
This should be updated.

2021-02-13 20:18 UTC, williamdes commented on scripts/create-release.sh
> +            - change PRE_RELEASE_NAME to "rc1"
Done

2021-02-14 00:23 UTC, mauriciofauth approved these changes

2021-02-14 00:31 UTC, williamdes commented
@ibennetch The work for the version handling is ready for a last review since you are the one that uses release scripts more
Will merge this as soon as you feel all this is okay :)

2021-02-17 00:59 UTC, williamdes commented
@ibennetch can I merge this one ?

2021-02-23 14:41 UTC, mauriciofauth approved these changes

2021-02-23 14:41 UTC, mauriciofauth commented on libraries/classes/Command/SetVersionCommand.php
> +            return 1;
```suggestion
            return Command::FAILURE;
```

2021-02-23 14:41 UTC, mauriciofauth commented on libraries/classes/Command/SetVersionCommand.php
> +        return 0;
```suggestion
        return Command::SUCCESS;
```

2021-02-23 14:44 UTC, mauriciofauth commented on libraries/classes/Command/SetVersionCommand.php
> +            return 1;
Forget about that, it will only work on `master`.

2021-02-23 14:44 UTC, mauriciofauth commented on libraries/classes/Command/SetVersionCommand.php
> +        return 0;
Forget about that, it will only work on `master`.

2021-02-23 14:54 UTC, merged

2021-02-23 14:56 UTC, williamdes commented on libraries/classes/Command/SetVersionCommand.php
> +        return 0;
Good idea, I will add them on master
See: https://github.com/symfony/console/commit/27327a59875896d8b8e577ccddc35d92d7654664
it was added in console 5.1

2021-02-23 15:21 UTC, williamdes commented on libraries/classes/Command/SetVersionCommand.php
> +        return 0;
66255ffbf91b1542eca8d64fa7b3cb5154bfd878