Fix: #16612 - Empty relation view table dropdown
phpmyadmin/phpmyadmin pull request #16615
Opened 2021-02-03 17:53 UTC by shucon

Signed-off-by: Saksham Gupta <shucon01@gmail.com>

### Description

Fixes Empty relation view table dropdown.

Fixes #16612

Before submitting pull request, please review the following checklist:

- [ ] Make sure you have read our [CONTRIBUTING.md](https://github.com/phpmyadmin/phpmyadmin/blob/master/CONTRIBUTING.md) document.
- [ ] Make sure you are making a pull request against the correct branch. For example, for bug fixes in a released version use the corresponding QA branch and for new features use the _master_ branch. If you have a doubt, you can ask as a comment in the bug report or on the mailing list.
- [ ] Every commit has proper `Signed-off-by` line as described in our [DCO](https://github.com/phpmyadmin/phpmyadmin/blob/master/DCO). This ensures that the work you're submitting is your own creation.
- [ ] Every commit has a descriptive commit message.
- [ ] Every commit is needed on its own, if you have just minor fixes to previous commits, you can squash them.
- [ ] Any new functionality is covered by tests.

2021-02-05 00:32 UTC, williamdes requested changes
I tested your fix it does "work" but creates a bug by emptying the table list of any already existing releatin

I would prefer a solution that would fetch the tables in the twig template

2021-02-05 11:27 UTC, shucon commented
> I tested your fix it does "work" but creates a bug by emptying the table list of any already existing releatin
> 
> I would prefer a solution that would fetch the tables in the twig template

Thanks for picking up the bug! I've fixed it in twig instead as you suggested.

2021-02-05 15:39 UTC, williamdes commented on templates/table/relation/foreign_key_row.twig
> +        {% set tables = get_tables(db, tbl_storage_engine) %}
db is always defined in this scenario ?

2021-02-05 15:39 UTC, williamdes commented on templates/table/relation/relational_dropdown.twig
> +    {% if foreign is not same as(false) and foreign != "" and not seen_key %}
could you explain this diff ?

2021-02-05 15:59 UTC, shucon commented on templates/table/relation/foreign_key_row.twig
> +        {% set tables = get_tables(db, tbl_storage_engine) %}
Yes!

2021-02-05 15:59 UTC, shucon commented on templates/table/relation/relational_dropdown.twig
> +    {% if foreign is not same as(false) and foreign != "" and not seen_key %}
If it's not in place, there is an extra empty row that is not required.

2021-02-09 14:34 UTC, williamdes commented on templates/table/relation/relational_dropdown.twig
> +    {% if foreign is not same as(false) and foreign != "" and not seen_key %}
For the record, it will prevent this extra line to exist
![image](https://user-images.githubusercontent.com/7784660/107378450-49ec9680-6aec-11eb-91b9-efda0860d7ed.png)

2021-02-09 14:35 UTC, williamdes approved these changes
It works great !
:100:

2021-02-09 14:49 UTC, merged