Fix 16506 Hide_db and Only_db does not work
phpmyadmin/phpmyadmin pull request #16626
Opened 2021-02-08 14:34 UTC by shucon

Signed-off-by: Saksham Gupta <shucon01@gmail.com>

### Description

Fixes #16506

Before submitting pull request, please review the following checklist:

- [ ] Make sure you have read our [CONTRIBUTING.md](https://github.com/phpmyadmin/phpmyadmin/blob/master/CONTRIBUTING.md) document.
- [ ] Make sure you are making a pull request against the correct branch. For example, for bug fixes in a released version use the corresponding QA branch and for new features use the _master_ branch. If you have a doubt, you can ask as a comment in the bug report or on the mailing list.
- [ ] Every commit has proper `Signed-off-by` line as described in our [DCO](https://github.com/phpmyadmin/phpmyadmin/blob/master/DCO). This ensures that the work you're submitting is your own creation.
- [ ] Every commit has a descriptive commit message.
- [ ] Every commit is needed on its own, if you have just minor fixes to previous commits, you can squash them.
- [ ] Any new functionality is covered by tests.

2021-02-08 14:35 UTC, shucon commented on libraries/classes/UserPreferences.php
> +            if ($value == "") {
We could also add a condition where `$key` can only be `hide_db` or `only_db` but I think it's not required.

2021-02-09 18:00 UTC, williamdes requested changes
This will maybe have side effects on users wanting to remove the value set by the config

2021-02-11 18:47 UTC, mauriciofauth requested changes
This is not the correct solution. The issue is that after changing a setting through the Settings page, the value in the `config.inc.php` is ignored.

2021-02-12 06:52 UTC, shucon commented
What do you propose? What should be the desired behaviour when there's a value in both?

2021-04-01 18:07 UTC, closed without merging