remove inline events
phpmyadmin/phpmyadmin pull request #16630
Opened 2021-02-09 16:27 UTC by Thomas1664

### Description

Added event handlers for some inline events

Partially fixes #13270 

Before submitting pull request, please review the following checklist:

- [x] Make sure you have read our [CONTRIBUTING.md](https://github.com/phpmyadmin/phpmyadmin/blob/master/CONTRIBUTING.md) document.
- [x] Make sure you are making a pull request against the correct branch. For example, for bug fixes in a released version use the corresponding QA branch and for new features use the _master_ branch. If you have a doubt, you can ask as a comment in the bug report or on the mailing list.
- [ ] Every commit has proper `Signed-off-by` line as described in our [DCO](https://github.com/phpmyadmin/phpmyadmin/blob/master/DCO). This ensures that the work you're submitting is your own creation.
- [x] Every commit has a descriptive commit message.
- [] Every commit is needed on its own, if you have just minor fixes to previous commits, you can squash them.
- [] Any new functionality is covered by tests.

2021-02-09 16:30 UTC, williamdes commented on js/src/sql.js
> +        Functions.selectContent(this, sqlBoxLocked, true);
You can add `/* global sqlBoxLocked */ // js/functions.js` at the top of the file to fix the JS lint error

2021-02-09 16:31 UTC, williamdes approved these changes
The diff looks good

2021-02-09 18:43 UTC, mauriciofauth requested changes
Good work!

2021-02-09 18:43 UTC, mauriciofauth commented on js/src/sql.js
> +    });
These two events (`$('#select_all')` and `$('#unselect_all')`) can be moved to `js/src/database/search.js`.

Also, add an `.off` for each `.on` that you added in the `registerTeardown` function on the same file.

2021-02-11 11:45 UTC, Thomas1664 commented
Sign-off-by: Thomas Heinrichs

2021-02-14 20:59 UTC, mauriciofauth approved these changes

2021-02-16 00:22 UTC, merged

2021-02-16 00:22 UTC, williamdes commented
Merged, thank you Thomas !