Enhancement #16699: Designer warns when trying to create relationship…
phpmyadmin/phpmyadmin pull request #16747
Opened 2021-03-20 20:05 UTC by shucon

…s of different data types

Signed-off-by: Saksham Gupta <shucon01@gmail.com>

### Description

Please describe your pull request.

Fixes #

Before submitting pull request, please review the following checklist:

- [ ] Make sure you have read our [CONTRIBUTING.md](https://github.com/phpmyadmin/phpmyadmin/blob/master/CONTRIBUTING.md) document.
- [ ] Make sure you are making a pull request against the correct branch. For example, for bug fixes in a released version use the corresponding QA branch and for new features use the _master_ branch. If you have a doubt, you can ask as a comment in the bug report or on the mailing list.
- [ ] Every commit has proper `Signed-off-by` line as described in our [DCO](https://github.com/phpmyadmin/phpmyadmin/blob/master/DCO). This ensures that the work you're submitting is your own creation.
- [ ] Every commit has a descriptive commit message.
- [ ] Every commit is needed on its own, if you have just minor fixes to previous commits, you can squash them.
- [ ] Any new functionality is covered by tests.

2021-06-21 17:39 UTC, mauriciofauth requested changes

2021-06-21 17:39 UTC, mauriciofauth commented on js/src/designer/move.js
> +                DesignerMove.displayTable('layer_cnfrm_relation');
What does `cnfrm` mean? Please don't use this kind of abbreviations.

2021-06-21 18:49 UTC, williamdes commented on js/src/designer/move.js
> +    var left = prevX - (document.getElementById(name).offsetWidth >> 1);
`document.getElementById(name)` can be stored in a variable

2021-06-21 18:49 UTC, williamdes commented on js/src/designer/move.js
> +    $('input#cnfrm_rel').on('click', function () {
Same here for `cnfrm`

2021-06-21 18:49 UTC, williamdes commented on js/src/designer/move.js
> +        document.getElementById('layer_confirm_relation').style.display = 'none';
I think there is a better Jquery way to do this 🤔

2021-06-21 18:50 UTC, williamdes commented on templates/database/designer/main.twig
> +  <tr>
this feels a bit strange

2021-06-26 12:41 UTC, shucon commented on templates/database/designer/main.twig
> +  <tr>
The template is copied from other tables.

2021-07-20 19:17 UTC, williamdes commented on js/src/designer/move.js
> +        document.getElementById('layer_confirm_relation').style.display = 'none';
this should be jquery

2022-05-12 17:58 UTC, williamdes requested changes
I think there is a better way to make this feature and including more use cases like data types, feel free to open a new one

2022-05-12 17:58 UTC, closed without merging