drop nocache & server query string param from theme.css stylesheet
phpmyadmin/phpmyadmin pull request #16740
Opened 2021-03-18 20:44 UTC by fliespl

I have noticed that theme.css file is outside of cache scope due to unique &nocache= being appended on every request.

This is not expected in releases to public, since file is not cachable then (and should be).

Version query string param is enough for this use case since file will be fresh on new phpmyadmin version install.

Maybe some variable based on devel/production flow is needed here to allow easier changes in devel.

### Description

Please describe your pull request.

Fixes #

Before submitting pull request, please review the following checklist:

- [ ] Make sure you have read our [CONTRIBUTING.md](https://github.com/phpmyadmin/phpmyadmin/blob/master/CONTRIBUTING.md) document.
- [ ] Make sure you are making a pull request against the correct branch. For example, for bug fixes in a released version use the corresponding QA branch and for new features use the _master_ branch. If you have a doubt, you can ask as a comment in the bug report or on the mailing list.
- [ ] Every commit has proper `Signed-off-by` line as described in our [DCO](https://github.com/phpmyadmin/phpmyadmin/blob/master/DCO). This ensures that the work you're submitting is your own creation.
- [ ] Every commit has a descriptive commit message.
- [ ] Every commit is needed on its own, if you have just minor fixes to previous commits, you can squash them.
- [ ] Any new functionality is covered by tests.

2021-03-19 16:05 UTC, mauriciofauth requested changes
Thank you for your contribution.

Since `unique_value` is not used in this template anymore, you also have to remove the variable from `PhpMyAdmin\Header::getDisplay` and the `PhpMyAdmin\Config::getThemeUniqueValue` method.

2021-03-20 21:52 UTC, fliespl commented
> Thank you for your contribution.
> 
> Since `unique_value` is not used in this template anymore, you also have to remove the variable from `PhpMyAdmin\Header::getDisplay` and the `PhpMyAdmin\Config::getThemeUniqueValue` method.

Commit updated.

2021-03-21 00:11 UTC, williamdes approved these changes

2021-03-21 00:39 UTC, mauriciofauth approved these changes

2021-03-21 00:39 UTC, merged

2021-03-21 00:39 UTC, mauriciofauth commented
Merged, thanks for your contribution!