Fix #16404 Password generation fix after new user creation failure
phpmyadmin/phpmyadmin pull request #16809
Opened 2021-04-12 11:28 UTC by shucon

Signed-off-by: Saksham Gupta <shucon01@gmail.com>

### Description

Please describe your pull request.

Fixes #16404 

Before submitting pull request, please review the following checklist:

- [ ] Make sure you have read our [CONTRIBUTING.md](https://github.com/phpmyadmin/phpmyadmin/blob/master/CONTRIBUTING.md) document.
- [ ] Make sure you are making a pull request against the correct branch. For example, for bug fixes in a released version use the corresponding QA branch and for new features use the _master_ branch. If you have a doubt, you can ask as a comment in the bug report or on the mailing list.
- [ ] Every commit has proper `Signed-off-by` line as described in our [DCO](https://github.com/phpmyadmin/phpmyadmin/blob/master/DCO). This ensures that the work you're submitting is your own creation.
- [ ] Every commit has a descriptive commit message.
- [ ] Every commit is needed on its own, if you have just minor fixes to previous commits, you can squash them.
- [ ] Any new functionality is covered by tests.

2021-04-13 12:24 UTC, williamdes requested changes
This works fine but is invalid, the form does not go anymore to edit user form on success add

2021-04-13 18:40 UTC, williamdes commented on libraries/classes/Server/Privileges.php
> +                $_add_user_error || $_error,
do you have any idea why phpstan thinks that `Left side of || is always false.` ?

2021-04-13 18:40 UTC, williamdes approved these changes
Looks like a nice fix

2021-04-15 15:06 UTC, shucon commented
@sudo-bot Deploy PR

2021-04-15 15:10 UTC, shucon commented
@sudo-robot Deploy PR

2021-04-19 19:31 UTC, merged