Extract Server/Select HTML to Twig
phpmyadmin/phpmyadmin pull request #16875
Opened 2021-05-03 21:27 UTC by danielTiringer

### Description

Extract HTML from `libraries/classes/Server/Select.php` to Twig templates
There was a test suite already in place, but one test contained multiple scenarios, so that part required some tidying up too.

Fixes # 10481

Before submitting pull request, please review the following checklist:

- [X] Make sure you have read our [CONTRIBUTING.md](https://github.com/phpmyadmin/phpmyadmin/blob/master/CONTRIBUTING.md) document.
- [X] Make sure you are making a pull request against the correct branch. For example, for bug fixes in a released version use the corresponding QA branch and for new features use the _master_ branch. If you have a doubt, you can ask as a comment in the bug report or on the mailing list.
- [X] Every commit has proper `Signed-off-by` line as described in our [DCO](https://github.com/phpmyadmin/phpmyadmin/blob/master/DCO). This ensures that the work you're submitting is your own creation.
- [X] Every commit has a descriptive commit message.
- [X] Every commit is needed on its own, if you have just minor fixes to previous commits, you can squash them.
- [X] Any new functionality is covered by tests.

2021-05-03 22:00 UTC, williamdes commented on templates/server/select/index.twig
> +                        {{ server.label }}
```suggestion
                        {{- server.label -}}
```
That will remove the indentation spaces and keep the contents how it was

2021-05-03 22:01 UTC, williamdes commented on templates/server/select/index.twig
> +            {{ include('server/select/server_options.twig') }}
```suggestion
            {{ include 'server/select/server_options.twig' }}
```

2021-05-03 22:01 UTC, williamdes commented on templates/server/select/server_options.twig
> +        {{ server.label|escape }}
```suggestion
        {{- server.label|escape -}}
```

2021-05-03 22:01 UTC, williamdes approved these changes
Very good work !
I left some comments

2021-05-04 04:11 UTC, danielTiringer commented on templates/server/select/index.twig
> +                        {{ server.label }}
Thanks, I've got this amended!
There was one more that needed changing.

2021-05-04 04:19 UTC, danielTiringer commented on templates/server/select/index.twig
> +            {{ include('server/select/server_options.twig') }}
This is an [include function](https://twig.symfony.com/doc/3.x/functions/include.html), not an [include tag](https://twig.symfony.com/doc/3.x/tags/include.html), which is what the documentation recommended to use.

2021-05-04 08:57 UTC, williamdes commented on templates/server/select/index.twig
> +            {{ include('server/select/server_options.twig') }}
Thank you so much for the documentation !
Could you use a tag ? (because I did not find any use of an include in our code base)

2021-05-04 08:59 UTC, williamdes commented on test/classes/Server/SelectTest.php
> +    public function testRender($not_only_options, $omit_fieldset): void
```suggestion
    /**
     * Test for Select::render
     *
     * @dataProvider renderDataProvider
     */
    public function testRender(bool $not_only_options, bool $omit_fieldset): void
```

2021-05-04 09:00 UTC, williamdes commented on templates/server/select/index.twig
> +                    <strong>{{- server.label|escape -}}</strong>
```suggestion
                    <strong>{{ server.label|escape }}</strong>
```
You can remove these, the open an close tags are glued :)

2021-05-04 09:02 UTC, williamdes commented on libraries/classes/Server/Select.php
> +                    'selected' => $selected ? $selected : '',
```suggestion
                    'selected' => $selected ? 'true' : '',
```
Would it be more clear ?

2021-05-04 09:06 UTC, williamdes approved these changes
I did a final review, for me this is quite perfect some minor details to fix
Would you mind squashing the commits on your next push ?

(by the way GitHub seems not to detect you, maybe you did not add this email address to your account ? Anyway this has nothing to do with the PR ;) )

2021-05-04 11:49 UTC, danielTiringer commented on templates/server/select/index.twig
> +            {{ include('server/select/server_options.twig') }}
Sure, that is actually a decent option, as it limits the amount of variables given to the included template.

2021-05-04 11:53 UTC, danielTiringer commented
> I did a final review, for me this is quite perfect some minor details to fix
> Would you mind squashing the commits on your next push ?
> 
> (by the way GitHub seems not to detect you, maybe you did not add this email address to your account ? Anyway this has nothing to do with the PR ;) )

Thanks for the review! I believe I went through all of the comments.
Got the commits all squashed into one and force-pushed here.
And got the email address sorted out too. Local dotfile needed to be updated.

2021-05-04 12:47 UTC, williamdes approved these changes
Awesome !
Waiting to another team member to review it, will merge your work if no review is done in let's say one week

2021-05-04 12:50 UTC, williamdes commented
By the way if you know another language any contribution to the Translation would be awesome too, it's all automated and will be pushed for you to this repository.
See: https://hosted.weblate.org/languages/hu/phpmyadmin/ (for Hungarian, I did see you did a PR recently about Hungarian) or https://hosted.weblate.org/projects/phpmyadmin/ for any other language

2021-05-05 13:55 UTC, mauriciofauth requested changes
Thank you for your contribution!

2021-05-05 13:55 UTC, mauriciofauth commented on templates/server/select/server_options.twig
> +        {{- server.label|escape -}}
Escaping is enabled by default, you don't need explicitly use the `escape` filter.

2021-05-07 16:01 UTC, MauricioFauth approved these changes

2021-05-07 16:01 UTC, merged

2021-05-07 16:01 UTC, mauriciofauth commented
Merged, thanks for your contribution!