Extract NavigationTree->fastFilterHtml()'s HTML to Twig
phpmyadmin/phpmyadmin pull request #16878
Opened 2021-05-04 20:33 UTC by danielTiringer

### Description

Extract HTML from `libraries/classes/Navigation/NavigationTree.php`'s `fastFilterHtml()` to Twig templates

Fixes #14801

Before submitting pull request, please review the following checklist:

- [X] Make sure you have read our [CONTRIBUTING.md](https://github.com/phpmyadmin/phpmyadmin/blob/master/CONTRIBUTING.md) document.
- [X] Make sure you are making a pull request against the correct branch. For example, for bug fixes in a released version use the corresponding QA branch and for new features use the _master_ branch. If you have a doubt, you can ask as a comment in the bug report or on the mailing list.
- [X] Every commit has proper `Signed-off-by` line as described in our [DCO](https://github.com/phpmyadmin/phpmyadmin/blob/master/DCO). This ensures that the work you're submitting is your own creation.
- [X] Every commit has a descriptive commit message.
- [X] Every commit is needed on its own, if you have just minor fixes to previous commits, you can squash them.
- [X] Any new functionality is covered by tests.

2021-05-04 21:31 UTC, williamdes commented on templates/navigation/tree/fast_filter.twig
> +                id='55'
```suggestion
```
Seems to be a debug data you left

2021-05-04 21:34 UTC, williamdes approved these changes
💯 
I left one small comment

2021-05-05 14:12 UTC, mauriciofauth requested changes

2021-05-05 14:12 UTC, mauriciofauth commented on libraries/classes/Navigation/NavigationTree.php
> +                && (in_array($parent[0]->realName, self::SPECIAL_NODE_NAMES) || $isNewView)
`self::SPECIAL_NODE_NAMES` array is different that the `$haveAjax` array.

2021-05-05 14:12 UTC, mauriciofauth commented on libraries/classes/Navigation/NavigationTree.php
> +            'is_node_special' => true,
Is `is_node_special` always true?

2021-05-05 14:12 UTC, mauriciofauth commented on templates/navigation/tree/fast_filter.twig
> +                name="searchClause{% if is_node_special %}2{% endif %}"
```suggestion
                name="{{ is_node_special ? 'searchClause2' : 'searchClause' }}"
```

I prefer to not break this types of names.

2021-05-05 14:12 UTC, mauriciofauth commented on templates/navigation/tree/fast_filter.twig
> +    <li class="fast_filter db_fast_filter">
```suggestion
    <li class="fast_filter{{ not is_node_special ? ' db_fast_filter' }}">
```

2021-05-05 14:54 UTC, williamdes commented on templates/navigation/tree/fast_filter.twig
> +                name="searchClause{% if is_node_special %}2{% endif %}"
I agree because the full text version helps when searching for the occurrence in the code base

2021-05-05 18:48 UTC, danielTiringer commented on libraries/classes/Navigation/NavigationTree.php
> +            'is_node_special' => true,
Nope, I meant to change that to a variable but ended up forgetting.

2021-05-06 15:11 UTC, MauricioFauth approved these changes

2021-05-06 15:20 UTC, merged

2021-05-06 15:20 UTC, mauriciofauth commented
Merged, thanks for your contribution!