Enh 16482: Select All link for table-specific privileges
phpmyadmin/phpmyadmin pull request #16889
Opened 2021-05-07 19:01 UTC by shucon

Signed-off-by: Saksham Gupta <shucon01@gmail.com>

### Description

Please describe your pull request.

Fixes #16482 

Before submitting pull request, please review the following checklist:

- [ ] Make sure you have read our [CONTRIBUTING.md](https://github.com/phpmyadmin/phpmyadmin/blob/master/CONTRIBUTING.md) document.
- [ ] Make sure you are making a pull request against the correct branch. For example, for bug fixes in a released version use the corresponding QA branch and for new features use the _master_ branch. If you have a doubt, you can ask as a comment in the bug report or on the mailing list.
- [ ] Every commit has proper `Signed-off-by` line as described in our [DCO](https://github.com/phpmyadmin/phpmyadmin/blob/master/DCO). This ensures that the work you're submitting is your own creation.
- [ ] Every commit has a descriptive commit message.
- [ ] Every commit is needed on its own, if you have just minor fixes to previous commits, you can squash them.
- [ ] Any new functionality is covered by tests.

2021-05-07 22:07 UTC, MauricioFauth requested changes

2021-05-09 07:30 UTC, williamdes requested changes

2021-05-09 07:30 UTC, williamdes commented on js/src/server/privileges.js
> +        e.stopPropagation();
Stop would make more sense above, right?

2021-05-09 07:30 UTC, williamdes commented on js/src/server/privileges.js
> +        var method = id.split('_')[0];
This is terrible and will break, can use use a `data-` attribute instead?

2021-05-10 23:48 UTC, williamdes commented on templates/server/privileges/privileges_table.twig
> +      <button class="btn btn-secondary" id="select_priv_all" data-method="select" >{% trans 'Select all' %}</button><br/>
Not sure about the `<br>`, @mauriciofauth do you think this is okay ?

2021-05-10 23:49 UTC, williamdes commented on js/src/server/privileges.js
> +        var method = $(this)[0].getAttribute('data-method');
```suggestion
        var method = $(this).first().data('method');
```
That should work too
And avoid index errors

2021-05-11 01:19 UTC, MauricioFauth requested changes

2021-05-11 01:19 UTC, mauriciofauth commented on js/src/server/privileges.js
> +        var method = $(this)[0].getAttribute('data-method');
```suggestion
        const method = e.target.getAttribute('data-method');
```

2021-05-12 21:00 UTC, williamdes commented on templates/server/privileges/privileges_table.twig
> +        <button class="btn btn-link p-0" id="insert_priv_all" type="button"data-select-target="#select_insert_priv">
```suggestion
        <button class="btn btn-link p-0" id="insert_priv_all" type="button" data-select-target="#select_insert_priv">
```

2021-05-12 21:00 UTC, williamdes commented on yarn.lock
> +  integrity sha512-oJP/9NAdd9+x2Q+rfphB2RJCHjod70RcRLjosiPMMu5gjIfwVnOUGq2nbTjTUbmy0DJ/tFIVT30+Qe3nzl4TJg==
could you exclude this change ?

2021-05-13 11:36 UTC, shucon commented on yarn.lock
> +  integrity sha512-oJP/9NAdd9+x2Q+rfphB2RJCHjod70RcRLjosiPMMu5gjIfwVnOUGq2nbTjTUbmy0DJ/tFIVT30+Qe3nzl4TJg==
Sorry, committed that by mistake.

2021-05-28 22:53 UTC, williamdes commented on js/src/server/privileges.js
> +        var options = $(method).first().children();
Jquery has no `.selected(true);` or `.attr('selected', true);` to avoid the loop ?

2021-05-28 22:54 UTC, williamdes approved these changes

2021-05-31 15:05 UTC, shucon commented on js/src/server/privileges.js
> +        var options = $(method).first().children();
`.each()` is the closest I could find

2021-07-29 01:34 UTC, williamdes approved these changes
Works fine as expected

2021-07-29 01:38 UTC, merged