14801 - Extract small HTML elements from NavigationTree to Twig
phpmyadmin/phpmyadmin pull request #16880
Opened 2021-05-05 05:40 UTC by danielTiringer

### Description

Extract HTML from `libraries/classes/Navigation/NavigationTree.php`'s small functions to Twig templates

Ref #14801

Before submitting pull request, please review the following checklist:

- [X] Make sure you have read our [CONTRIBUTING.md](https://github.com/phpmyadmin/phpmyadmin/blob/master/CONTRIBUTING.md) document.
- [X] Make sure you are making a pull request against the correct branch. For example, for bug fixes in a released version use the corresponding QA branch and for new features use the _master_ branch. If you have a doubt, you can ask as a comment in the bug report or on the mailing list.
- [X] Every commit has proper `Signed-off-by` line as described in our [DCO](https://github.com/phpmyadmin/phpmyadmin/blob/master/DCO). This ensures that the work you're submitting is your own creation.
- [X] Every commit has a descriptive commit message.
- [X] Every commit is needed on its own, if you have just minor fixes to previous commits, you can squash them.
- [X] Any new functionality is covered by tests.

2021-05-05 08:02 UTC, williamdes approved these changes
💯

2021-05-05 18:27 UTC, mauriciofauth requested changes

2021-05-05 18:27 UTC, mauriciofauth commented on templates/navigation/tree/pagination_params.twig
> +        class="hide pos{{ position }}_nav"
Do not break the class name.

2021-05-05 18:27 UTC, mauriciofauth commented on libraries/classes/Navigation/NavigationTree.php
> +        return $this->template->render('/navigation/tree/pagination_params', $renderDetails);
```suggestion
        return $this->template->render('navigation/tree/pagination_params', $renderDetails);
```

2021-05-05 18:27 UTC, mauriciofauth commented on libraries/classes/Navigation/NavigationTree.php
> +        return $this->template->render('/navigation/tree/quick_warp', $renderDetails);
```suggestion
        return $this->template->render('navigation/tree/quick_warp', $renderDetails);
```

2021-05-07 15:58 UTC, merged

2021-05-07 15:58 UTC, mauriciofauth commented
Merged, thanks for your contribution!

2021-05-07 15:59 UTC, mauriciofauth approved these changes