Ref #13270 - fix(query.twig): Inline events removed
phpmyadmin/phpmyadmin pull request #16905
Opened 2021-05-16 13:43 UTC by Seezly

### Description

Added event handlers for some inline events.

Related to #13270

Before submitting pull request, please review the following checklist:

- [x] Make sure you have read our [CONTRIBUTING.md](https://github.com/phpmyadmin/phpmyadmin/blob/master/CONTRIBUTING.md) document.
- [x] Make sure you are making a pull request against the correct branch. For example, for bug fixes in a released version use the corresponding QA branch and for new features use the _master_ branch. If you have a doubt, you can ask as a comment in the bug report or on the mailing list.
- [x] Every commit has proper `Signed-off-by` line as described in our [DCO](https://github.com/phpmyadmin/phpmyadmin/blob/master/DCO). This ensures that the work you're submitting is your own creation.
- [x] Every commit has a descriptive commit message.
- [ ] Every commit is needed on its own, if you have just minor fixes to previous commits, you can squash them.
- [ ] Any new functionality is covered by tests.

2021-05-16 20:36 UTC, williamdes approved these changes

2021-05-20 22:02 UTC, mauriciofauth requested changes
Hi @Seezly, thanks for your contribution.

Before we can merge your pull request, you should fix the failing PHPUnit test.
See: https://github.com/phpmyadmin/phpmyadmin/pull/16905/checks?check_run_id=2595731279#step:9:177

You can run the test with the following command:
```
vendor/bin/phpunit
```

2021-07-08 14:27 UTC, williamdes commented
I am in favor of merging this, but I would note the feature is maybe broken (before this PR) because it requires `$cfg['CodemirrorEnable'] = false;` to work

2021-08-11 15:03 UTC, mauriciofauth approved these changes

2021-08-11 15:04 UTC, merged