Replace Export privileges group dialog with a modal
phpmyadmin/phpmyadmin pull request #16925
Opened 2021-05-28 16:39 UTC by shucon

### Description

Replaces the export privileges group jQuery UI dialog with a Bootstrap modal.

Before submitting pull request, please review the following checklist:

- [ ] Make sure you have read our [CONTRIBUTING.md](https://github.com/phpmyadmin/phpmyadmin/blob/master/CONTRIBUTING.md) document.
- [ ] Make sure you are making a pull request against the correct branch. For example, for bug fixes in a released version use the corresponding QA branch and for new features use the _master_ branch. If you have a doubt, you can ask as a comment in the bug report or on the mailing list.
- [ ] Every commit has proper `Signed-off-by` line as described in our [DCO](https://github.com/phpmyadmin/phpmyadmin/blob/master/DCO). This ensures that the work you're submitting is your own creation.
- [ ] Every commit has a descriptive commit message.
- [ ] Every commit is needed on its own, if you have just minor fixes to previous commits, you can squash them.
- [ ] Any new functionality is covered by tests.

2021-05-28 17:01 UTC, williamdes approved these changes
LGTM

2021-05-28 22:54 UTC, williamdes commented on js/src/server/privileges.js
> + * @param $msgbox
without types they are not very usefull ;)

2021-05-29 08:23 UTC, shucon commented on js/src/server/privileges.js
> + * @param $msgbox
Yeah, should I remove these comments?

2021-05-29 10:58 UTC, williamdes commented on js/src/server/privileges.js
> + * @param $msgbox
oh no no, just add types for them ;)

2021-05-29 17:33 UTC, williamdes commented on js/src/server/privileges.js
> +    }
```suggestion
    if (typeof data !== 'undefined' && data.success === true) {
        modal.find('.modal-body').first().html(data.message);
        $('#exportPrivilegesModalLabel').first().html(data.title);
        Functions.ajaxRemoveMessage(msgbox);
        // Attach syntax highlighted editor to export dialog
        Functions.getSqlEditor(modal.find('textarea'));
        return;
    }
    modal.modal('hide');
    Functions.ajaxShowMessage(data.error, false);
```

That will avoid the useless else

2021-05-29 17:33 UTC, williamdes approved these changes

2021-05-29 18:37 UTC, mauriciofauth requested changes
You can rename `templates/export_modal.twig` to `templates/server/privileges/export_modal.twig`

2021-05-29 18:37 UTC, mauriciofauth commented on libraries/classes/Controllers/Server/PrivilegesController.php
> +                $this->response->addHTML($tableController->getExportModal());
```suggestion
                $this->render('export_modal');
```

2021-05-29 18:37 UTC, mauriciofauth commented on libraries/classes/Controllers/Server/PrivilegesController.php
> +                $this->response->addHTML($databaseController->getExportModal());
```suggestion
                $this->render('export_modal');
```

2021-05-29 18:37 UTC, mauriciofauth commented on libraries/classes/Controllers/Database/PrivilegesController.php
> +        return $this->template->render('export_modal');
You can render the template directly, there is no need for this method.

2021-05-29 18:37 UTC, mauriciofauth commented on libraries/classes/Controllers/Table/PrivilegesController.php
> +        return $this->template->render('export_modal');
You can render the template directly, there is no need for this method.

2021-05-29 18:37 UTC, mauriciofauth commented on libraries/classes/Server/Privileges.php
> +        return $this->template->render('export_modal');
You can render the template directly, there is no need for this method.

2021-05-29 18:37 UTC, mauriciofauth commented on libraries/classes/Server/Privileges.php
> +                $usersOverview .= $this->getExportModal();
```suggestion
                $usersOverview .= $this->template->render('export_modal');
```

2021-05-31 20:27 UTC, mauriciofauth requested changes
For some reason, it's not working with the Bootstrap theme.

![image](https://user-images.githubusercontent.com/120970/120239770-65171980-c235-11eb-8295-7ebf85584a74.png)

2021-06-01 11:09 UTC, shucon commented
> For some reason, it's not working with the Bootstrap theme.
> 
> ![image](https://user-images.githubusercontent.com/120970/120239770-65171980-c235-11eb-8295-7ebf85584a74.png)

Was happening due to a race condition. Fixed it, thanks.

2021-06-01 11:28 UTC, williamdes commented on js/src/server/privileges.js
> + *
callback is type function :)

2021-06-01 11:32 UTC, shucon commented on js/src/server/privileges.js
> + *
Yeah, actually it didn't work. I'm seeing what's wrong.

2021-06-01 14:31 UTC, williamdes approved these changes

2021-07-27 01:33 UTC, merged