Add suport to the Mroonga engine
phpmyadmin/phpmyadmin pull request #16945
Opened 2021-06-06 21:45 UTC by josepsanzcamp

Add suport to the Mroonga engine

### Description

With this patch you can see the size of the Mroonga's tables

Fixes #

Before submitting pull request, please review the following checklist:

- [X] Make sure you have read our [CONTRIBUTING.md](https://github.com/phpmyadmin/phpmyadmin/blob/master/CONTRIBUTING.md) document.
- [X] Make sure you are making a pull request against the correct branch. For example, for bug fixes in a released version use the corresponding QA branch and for new features use the _master_ branch. If you have a doubt, you can ask as a comment in the bug report or on the mailing list.
- [ ] Every commit has proper `Signed-off-by` line as described in our [DCO](https://github.com/phpmyadmin/phpmyadmin/blob/master/DCO). This ensures that the work you're submitting is your own creation.
- [X] Every commit has a descriptive commit message.
- [ ] Every commit is needed on its own, if you have just minor fixes to previous commits, you can squash them.
- [ ] Any new functionality is covered by tests.

2021-06-06 22:23 UTC, williamdes commented
Hi @josepsanzcamp 
This was a very nice feature, can you push it back or do it on another branch ?

2021-06-07 02:45 UTC, josepsanzcamp commented
Hi @williamdes 

I have detected that the sort feature don't work because we must to put the correct size values inside the function getTablesFull located in the DatabaseInterface. I have another commit that solve the problem.

In a few minutes I will do another pull request with this improvement.

Josep.

2021-06-07 09:45 UTC, josepsanzcamp commented
I have fixed a bug when try to sort by rows, additionally I have created a function that returns the lengths of the data and index for the mroonga engine, this simplify the code and allow to be reused from other parts of the code.

2021-06-08 13:13 UTC, williamdes commented on libraries/classes/DatabaseInterface.php
> +        static $object_list=[];
I am not sure this `static` keyword is needed not is a good practice ;)
Could you run `composer run phpcs` and `composer run phpcbf` to fix the errors please ?

2021-06-08 13:14 UTC, williamdes commented on libraries/classes/DatabaseInterface.php
> +    private function getMroongaLengths(string $db_name, string $table_name) {
```suggestion
     * @param string $table_name Table name
     * @return int[]
     */
    private function getMroongaLengths(string $db_name, string $table_name): array {
```

2021-06-08 13:15 UTC, williamdes commented on libraries/classes/DatabaseInterface.php
> +                if(strncmp("${table_name}#${table_name}", $mroonga_name, strlen("${table_name}#${table_name}")) == 0) {
```suggestion
                if(strncmp($table_name . '#'. $table_name, $mroonga_name, strlen($table_name . '#'. $table_name)) === 0) {
```

2021-06-08 13:16 UTC, williamdes commented on libraries/classes/DatabaseInterface.php
> +                }
I think this else could be avoided by adding a continue in the if

2021-06-08 13:16 UTC, williamdes commented on libraries/classes/Controllers/Database/StructureController.php
> +    ) {
```suggestion
     * @return int[]
     */
    protected function getValuesForMroongaTable(
        array $currentTable,
        int $sumSize
    ): array {
```

2021-06-08 13:17 UTC, williamdes requested changes
Good work, some changes would make the code even nicer ;)
Could you post some SQL examples to help me reproduce and test your feature ?

2021-06-08 14:10 UTC, josepsanzcamp commented on libraries/classes/DatabaseInterface.php
> +        static $object_list=[];
Hi @williamdes 

The idea of this static array is to store the result of the command object_list to prevent that the next executions require to re-execute it, is a cache optimization.

I have used a static global variable because this data is only valid for the usage of this function. If you want to not use this feature, the other maner to do it is by defining a global variable in the class, but the usage is very specific of this function and how no other parts of the code must to access to it, I vote for use it in this case.

What do you want to do???

Related to the composer commands: I have executed the two composer commands to solve all problems related to the code styling, you can see it in the last commit.

Thanks in advance.

Josep.

2021-06-08 14:11 UTC, josepsanzcamp commented on libraries/classes/DatabaseInterface.php
> +    private function getMroongaLengths(string $db_name, string $table_name) {
OK, I have applied it in the last commit, thanks!!!

2021-06-08 14:11 UTC, josepsanzcamp commented on libraries/classes/DatabaseInterface.php
> +                if(strncmp("${table_name}#${table_name}", $mroonga_name, strlen("${table_name}#${table_name}")) == 0) {
OK, I have applied it in the last commit, thanks!!!

2021-06-08 14:13 UTC, josepsanzcamp commented on libraries/classes/DatabaseInterface.php
> +                }
I don't understand it, could you provide me an example??? the idea is to increment one variable or the other variable

2021-06-08 14:14 UTC, josepsanzcamp commented on libraries/classes/Controllers/Database/StructureController.php
> +    ) {
OK, I have applied it in the last commit, thanks!!!

2021-06-08 14:37 UTC, josepsanzcamp commented
Hi @williamdes 

This is a SQL example to create a Mroonga table:

`CREATE TABLE `idx_correo` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `search` mediumtext NOT NULL DEFAULT '',
  PRIMARY KEY (`id`),
  FULLTEXT KEY `idx_correo_search` (`search`)
) ENGINE=Mroonga AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4
`

Is it right for your unit test???

Josep.

2021-06-08 15:09 UTC, williamdes commented on libraries/classes/Controllers/Database/StructureController.php
> +        $formattedSize = $unit = '';
```suggestion
        $formattedSize = '';
        $unit = '';
```

2021-06-08 15:09 UTC, williamdes commented on libraries/classes/DatabaseInterface.php
> +                    if ($table_data['Engine'] != 'Mroonga') {
```suggestion
                    if ($table_data['Engine'] !== 'Mroonga') {
```

2021-06-08 15:10 UTC, williamdes commented on libraries/classes/DatabaseInterface.php
> +            }
```suggestion
            if (strncmp($index_prefix, $mroonga_name, strlen($index_prefix)) === 0) {
                $indexLength += $temp['disk_usage'];
                continue;
            }
            $dataLength += $temp['disk_usage'];
```

2021-06-08 15:11 UTC, williamdes commented on libraries/classes/DatabaseInterface.php
> +            if (strncmp($table_name, $mroonga_name, strlen($table_name)) != 0) {
```suggestion
            if (strncmp($table_name, $mroonga_name, strlen($table_name)) !== 0) {
```

2021-06-08 15:11 UTC, williamdes approved these changes

2021-06-08 15:12 UTC, williamdes commented on libraries/classes/DatabaseInterface.php
> +                }
I posted a suggestion :)

2021-06-08 15:13 UTC, williamdes commented
@sudo-robot deploy

2021-06-08 15:25 UTC, williamdes commented
![image](https://user-images.githubusercontent.com/7784660/121213361-70de8d80-c87e-11eb-9fcc-36eea7b1dbce.png)
I just installed Mroonga on the MariaDB 10.5 server (mariadb:10.5 on docker hub) and had this error.
Followed: https://mariadb.com/kb/en/about-mroonga/

2021-06-08 15:36 UTC, josepsanzcamp commented on libraries/classes/DatabaseInterface.php
> +            }
OK, now I understand your previous comments, thanks!!!

2021-06-08 15:41 UTC, josepsanzcamp commented on libraries/classes/Controllers/Database/StructureController.php
> +        $formattedSize = $unit = '';
OK, applied in the next commit, thanks!!!

2021-06-08 15:42 UTC, josepsanzcamp commented on libraries/classes/DatabaseInterface.php
> +                    if ($table_data['Engine'] != 'Mroonga') {
OK, applied in the next commit, thanks!!!

2021-06-08 15:44 UTC, josepsanzcamp commented on libraries/classes/DatabaseInterface.php
> +            }
OK, applied in the next commit, thanks!!!

2021-06-08 15:45 UTC, josepsanzcamp commented on libraries/classes/DatabaseInterface.php
> +            if (strncmp($table_name, $mroonga_name, strlen($table_name)) != 0) {
OK, applied in the next commit, thanks!!!

2021-06-08 17:04 UTC, josepsanzcamp commented
Hi @williamdes 

I have added some checks before to use the Mroonga dependent code, with this, if Mroonga is not available the result will be the same that the previous release that doesn't contains the Mroonga support.

Josep.

2021-06-08 19:27 UTC, williamdes commented
Hi @josepsanzcamp
I can confirm that I could create the table only after I installed the plugin.
So the plugin is installed and working.
The function you use seems not to be available for some reason, I will try to find out why

2021-06-08 20:53 UTC, josepsanzcamp commented
Hi @williamdes 

This error is caused by a bad instalation.

Generally, when you install mroonga from a package (deb or rpm), at the end of the setup will be executed a post-setup script that executes some sql queries to install and define functions.

I don't know how you are installed the mroonga plugin, but to solve this puntual problem, you can try to do the follow sql sentence:

```
CREATE FUNCTION mroonga_command RETURNS STRING
  SONAME 'ha_mroonga.so';
```

More info here: https://mariadb.com/kb/en/creating-mroonga-user-defined-functions/

Josep.

2021-06-10 00:09 UTC, williamdes commented on libraries/classes/DatabaseInterface.php
> +    public function hasMroongaEngine(): bool
🤔 returns bool :p ?

2021-06-10 00:12 UTC, williamdes commented
> CREATE FUNCTION mroonga_command RETURNS STRING
>   SONAME 'ha_mroonga.so';

Thank you, indeed I had a access denied to root user and not much more as an error so I just ignored it. Thank you for fixing the server and providing the query !
The code works fine

2021-06-10 00:13 UTC, williamdes commented on libraries/classes/Controllers/Database/StructureController.php
> +                // no break
```suggestion
                // no break, go to default case
```

2021-06-10 00:15 UTC, williamdes commented on libraries/classes/DatabaseInterface.php
> +                    }
```suggestion
                    if ($one_table_data['Engine'] !== 'Mroonga') {
                        continue;
                    }
                    if (! $this->hasMroongaEngine()) {
                        continue;
                    }
```
This would be optimal and avoid wasting a query that would fail anyway, right ?

2021-06-10 00:15 UTC, williamdes commented on libraries/classes/DatabaseInterface.php
> +                    if ($table_data['Engine'] !== 'Mroonga' || ! $this->hasMroongaEngine()) {
same :)

2021-06-10 05:05 UTC, josepsanzcamp commented on libraries/classes/DatabaseInterface.php
> +    public function hasMroongaEngine(): bool
Sorry, copy-paste error!!!

2021-06-10 05:05 UTC, josepsanzcamp commented on libraries/classes/Controllers/Database/StructureController.php
> +                // no break
Done

2021-06-10 05:05 UTC, josepsanzcamp commented on libraries/classes/DatabaseInterface.php
> +                    }
Done

2021-06-10 05:05 UTC, josepsanzcamp commented on libraries/classes/DatabaseInterface.php
> +                    if ($table_data['Engine'] !== 'Mroonga' || ! $this->hasMroongaEngine()) {
Done

2021-06-10 11:05 UTC, williamdes commented on libraries/classes/Controllers/Database/StructureController.php
> +     * @return array
```suggestion
     * @return int[]
```

2021-06-10 11:07 UTC, williamdes commented on libraries/classes/DatabaseInterface.php
> +        static $bool = null;
We have a Cache class in `$this->cache`, I think it would be the a solution to store the value
@mauriciofauth what do you think about this ?

2021-06-10 11:08 UTC, williamdes approved these changes
The code looks good, the `static $` should be fixed someway before merging

2021-06-10 22:15 UTC, williamdes commented on libraries/classes/DatabaseInterface.php
> +        if (! isset($this->object_list[__FUNCTION__])) {
Sorry to be picky, could you move this to the Cache class ? and use a string key or just make it specific on the Cache class ?

2021-06-10 22:20 UTC, williamdes commented on libraries/classes/DatabaseInterface.php
> +    /** @var object_list Store all mroonga cache */
I will explain why this is not very good:
- storing everything in the same array makes things not easy to analyse
- `@var object_list` is invalid and would be complicated to document since the stored objects/values and different
- it creates a property in a class that tries to stay small and slim
- having `__FUNCTION__` as a cache key is not very good, a string key would safer
- using this property will not allow tests to purge cache and will make testing difficult

Be sure I appreciate the effort you give and the code you make
I just try to give advice to make code as clean as possible

2021-06-11 05:34 UTC, josepsanzcamp commented on libraries/classes/DatabaseInterface.php
> +        if (! isset($this->object_list[__FUNCTION__])) {
Done

2021-06-11 05:35 UTC, josepsanzcamp commented on libraries/classes/DatabaseInterface.php
> +    /** @var object_list Store all mroonga cache */
Ok to all, but can you explain me what was the original problem with the static variable inside each function of the class??? why do you want to not use this feature of the language??? thanks in advance!!!

2021-06-11 10:01 UTC, williamdes commented on libraries/classes/DatabaseInterface.php
> +        $bool = $this->cache->getCachedTableContent(['mroonga_command']);
looks good, I will just have to check if it does not interfere with some code :)

2021-06-11 10:04 UTC, williamdes commented on libraries/classes/DatabaseInterface.php
> +    /** @var object_list Store all mroonga cache */
To explain: using a static variable in a function makes it impossible to test correctly. You will not be able to reset the "cached" value once it is set. If you want you can try to write tests for your feature (see: DatabaseInterfaceTest) ?

If you put it in a class you can workaround this by using some hack code:
https://github.com/phpmyadmin/phpmyadmin/blob/cce4bc993cb3459c877a5e1bec89cf646be7b963/test/classes/AbstractNetworkTestCase.php#L98-L105

2021-06-11 10:24 UTC, josepsanzcamp commented on libraries/classes/DatabaseInterface.php
> +    /** @var object_list Store all mroonga cache */
OK, I understand now your recomendation, thanks!!!

2021-06-11 10:25 UTC, josepsanzcamp commented on libraries/classes/DatabaseInterface.php
> +        $bool = $this->cache->getCachedTableContent(['mroonga_command']);
OK

2021-06-12 13:55 UTC, mauriciofauth approved these changes

2021-06-27 23:06 UTC, williamdes commented
Seems like I did once more the push mistake..
I re-created a branch for it on my fork with your commit: #16983
Sorry for the mistake, I think it is near ready to merge
I wrote some tests for the feature and discovered some details that could make the code slightly better and maybe also a bug

2021-07-11 18:38 UTC, williamdes commented
Thank you for pushing the change, I will fix up the branch and try not to make mistake once more :/

2021-07-11 19:59 UTC, williamdes commented on libraries/classes/StorageEngine.php
> +                if (in_array($mroongaData['type']['id'], [48, 49, 50, 51, 64, 65, 72])) {
Very good work @josepsanzcamp !
I like the links

2021-07-11 19:59 UTC, williamdes approved these changes

2021-07-11 20:19 UTC, williamdes commented
I think I will merge your work this week, just leaving open for other reviewers to comment if necessary

2021-07-13 18:57 UTC, merged