Replace zxcvbn by zxcvbn-ts
phpmyadmin/phpmyadmin pull request #16978
Opened 2021-06-23 18:00 UTC by Guileas

Signed-off-by: Gwénola ETHEVE <git@etheve.eu>

### Description

Replace zxcvbn by zxcvbn-ts

Fixes #16974

2021-06-23 18:20 UTC, mauriciofauth requested changes

2021-06-23 18:20 UTC, mauriciofauth commented on package.json
> -    "codemirror": "5.62.0",
I think removing these dependencies was a mistake.

2021-06-23 18:26 UTC, Guileas commented on package.json
> -    "codemirror": "5.62.0",
My bad ^^

2021-06-23 18:29 UTC, williamdes approved these changes
Very good work 💯

2021-06-23 18:34 UTC, mauriciofauth requested changes

2021-06-23 18:34 UTC, mauriciofauth commented on package.json
>      "updated-jqplot": "1.0.9",
```suggestion
    "updated-jqplot": "1.0.9"
```

2021-06-23 21:59 UTC, williamdes commented
@sudo-robot deploy

2021-06-24 07:16 UTC, MrWook commented
Hey, i really recommend that you are using the recommended set of options otherwise the scoring is pretty bad.

```
import { zxcvbn, ZxcvbnOptions } from '@zxcvbn-ts/core'
import zxcvbnCommonPackage from '@zxcvbn-ts/language-common'
import zxcvbnEnPackage from '@zxcvbn-ts/language-en'

const options = {
  graphs: zxcvbnCommonPackage.adjacencyGraphs,
  dictionary: {
    ...zxcvbnCommonPackage.dictionary,
    ...zxcvbnEnPackage.dictionary,
  },
}

ZxcvbnOptions.setOptions(options)
```

2021-06-24 07:26 UTC, williamdes commented
To achieve this you will need the sam technique as #16959 with webpack, to re-bundle the js bundle

2021-06-24 15:46 UTC, mauriciofauth approved these changes

2021-06-24 15:46 UTC, mauriciofauth commented
> To achieve this you will need the sam technique as #16959 with webpack, to re-bundle the js bundle

This can be done in a different pull request.

2021-06-27 17:10 UTC, merged