Add support for Keycloak Authentication
phpmyadmin/phpmyadmin pull request #17056
Opened 2021-08-06 10:34 UTC by davimenezesoli

This PR will fix the issue: https://github.com/phpmyadmin/phpmyadmin/issues/17052

Signed-off-by: Davi Menezes <davi.menezes@visma.com>

### Description

Please describe your pull request.

Fixes #

Before submitting pull request, please review the following checklist:

- [x] Make sure you have read our [CONTRIBUTING.md](https://github.com/phpmyadmin/phpmyadmin/blob/master/CONTRIBUTING.md) document.
- [x] Make sure you are making a pull request against the correct branch. For example, for bug fixes in a released version use the corresponding QA branch and for new features use the _master_ branch. If you have a doubt, you can ask as a comment in the bug report or on the mailing list.
- [x] Every commit has proper `Signed-off-by` line as described in our [DCO](https://github.com/phpmyadmin/phpmyadmin/blob/master/DCO). This ensures that the work you're submitting is your own creation.
- [x] Every commit has a descriptive commit message.
- [x] Every commit is needed on its own, if you have just minor fixes to previous commits, you can squash them.
- [x] Any new functionality is covered by tests.

2021-08-06 22:51 UTC, williamdes commented on libraries/classes/Plugins/Auth/AuthenticationKeycloak.php
> +        if (!isset($_COOKIE["kc-access"])) {
```suggestion
        if (!isset($_COOKIE['kc-access'])) {
```
`composer run phpcbf` will help you

2021-08-06 22:52 UTC, williamdes commented on libraries/classes/Plugins/Auth/AuthenticationKeycloak.php
> +     */
This one can be removed as it adds nothing to existing php typehints

2021-08-06 22:53 UTC, williamdes commented on libraries/classes/Plugins/Auth/AuthenticationKeycloak.php
> +use Lcobucci\JWT\Parser;
This would not work without adding the lib to composer.json

2021-08-06 22:53 UTC, williamdes commented
Hi @mauriciofauth 
Is it time to think about the plugin system for this ?

2021-08-07 02:01 UTC, mauriciofauth commented
> Hi @mauriciofauth 
> Is it time to think about the plugin system for this ?

Definitely. I already have an idea. I will work on that.

2021-08-09 10:24 UTC, mauriciofauth requested changes

2021-08-09 10:24 UTC, mauriciofauth commented on test/classes/Plugins/Auth/AuthenticationKeycloakTest.php
> +        $token = Mockery::mock(Token::class);
Could you replace Mockery with [PHPUnit's mock](https://phpunit.readthedocs.io/en/8.5/test-doubles.html#mock-objects)?

2021-08-09 12:13 UTC, davimenezesoli commented on test/classes/Plugins/Auth/AuthenticationKeycloakTest.php
> +        $token = Mockery::mock(Token::class);
I updated the tests to not mock it.

2021-08-10 19:33 UTC, williamdes commented on test/classes/Plugins/Auth/AuthenticationKeycloakTest.php
> +        $_COOKIE['kc-access'] = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c';
it has no secret configured somewhere ?

2021-08-13 09:20 UTC, davimenezesoli commented on test/classes/Plugins/Auth/AuthenticationKeycloakTest.php
> +        $_COOKIE['kc-access'] = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c';
No, this JWT token is set in the cookie and we read from it to authenticate the user or fail.

2021-08-13 13:50 UTC, williamdes commented on test/classes/Plugins/Auth/AuthenticationKeycloakTest.php
> +        $_COOKIE['kc-access'] = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c';
A jwt without a secret to verify it makes not sense to me
But it is maybe okay here as we decode the payload to get the data, but in one sense we can not trust the cookie value

2023-04-10 15:36 UTC, closed without merging