Fix table CSS
phpmyadmin/phpmyadmin pull request #17061
Opened 2021-08-07 22:41 UTC by lrb2

### Description

The tables generated by the `makeGrid` JS function used the `pma_table` CSS class instead of `pma-table` as used throughout the CSS styles, so many CSS rules were not being applied to these tables. In addition, the only two `pma_table` rules in each theme were also changed to `pma-table`.

Fixes #16804

2021-08-08 00:05 UTC, williamdes approved these changes
very nice fix !

2021-08-08 00:20 UTC, williamdes commented on themes/bootstrap/scss/_common.scss
> +.pma-table {
I am not sure this is a wanted side effect of this PR but it breaks css styles see the block above the table is wrong

2021-08-08 00:21 UTC, williamdes commented on themes/bootstrap/scss/_common.scss
> +.pma-table {
![image](https://user-images.githubusercontent.com/7784660/128616865-48a34fa8-69ac-44f3-9fd8-1b4aa8debeba.png)

2021-08-08 01:30 UTC, lrb2 commented on themes/bootstrap/scss/_common.scss
> +.pma-table {
Ah, I looked right over that and didn't realize that those styles didn't need to be applied to the other `pma-table`'s, just the ones that had been `pma_table`'s. I just updated my commit to fix that!

2021-08-08 13:58 UTC, mauriciofauth requested changes

2021-08-08 13:58 UTC, mauriciofauth commented on js/src/makegrid.js
> +    $(t).addClass('pma-table');
The `.pma-table` class is not the same as the `.pma_table` class. `.pma-table` is the style that was applied to the `table` HTML tag and was extracted to a CSS class. The `pma-` prefix was added to avoid conflict with the Bootstrap's `.table` class.

2021-08-08 23:26 UTC, lrb2 commented
Thanks for your comment @mauriciofauth! I found the solution that a few tables that use Bootstrap were still using the old `right` class instead of Bootstrap's `text-right`. I do think that it would be nice if the `pma_table` class was renamed to `pma-grid` (since it's made using the `makeGrid` function) or something because it's easy to confuse `pma-table` and `pma_table` right now. But if you're used to it then changing it might cause more harm than good.

2021-08-09 10:20 UTC, mauriciofauth approved these changes

2021-08-09 20:55 UTC, merged

2021-08-09 21:16 UTC, williamdes commented
For reference this was made on master and seems similar: d3c31fabd4012cd483ff268068d2399c36fb5b9f