Fix creation of unpartitioned tables
phpmyadmin/phpmyadmin pull request #17060
Opened 2021-08-07 21:11 UTC by lrb2

### Description

To fix the inability to create an unpartitioned table, the default value for the partition count input is now 1 instead of empty (0). Therefore, the input's minimum value is now 1 (instead of 2, which caused #17017). Partitions can still be created by increasing the value to 2 or greater, and partitioning can be easily canceled by decreasing the value back to 1. In prior versions, partitioning could only be canceled by manually typing '0' into the input, but with this change it can also be canceled using the arrows built into the number input element.

This fix also applies to creating subpartitions.

I have not been able to find any issues arising from `partition_count` being 1 instead of empty, since all uses of `partition_count` or `subpartition_count` that I have found check if it is greater than 1 before using it.

Fixes #17017

2021-08-08 00:25 UTC, williamdes requested changes
This works but the UI is not adding a line for the value of 1
Before it was doing it because the box had no value and onChange it created the line

That said `min=1` seems okay

2021-08-08 02:10 UTC, lrb2 commented
As far as I know, phpMyAdmin hasn't supported having only a single partition, at least it doesn't work on the demo server in 4.9 or 5.1. I was able to create a table with a single partition through manual SQL, and I can see the partition in phpMyAdmin, but I can't edit it. I could allow making a single partition (which would make the solution to this issue super easy), but I imagine there's a good reason not to just based on how many `> 1` checks there are, but I haven't really used partitions so I don't know. That said, I didn't think it was even possible to have only one partition so I'll try to implement a better solution.

2021-08-09 00:43 UTC, lrb2 commented
I found that the issue was caused by 069d8e13db2958012e09ef8b3b56f3195e35568b in `master`, which caused the input to show 0 (which is considered less than 2) instead of empty. The input will now be empty if (`sub`-)`partition_count` is 0 (yields false). I'm certain I was reproducing the issue in 5.1 yesterday, even when the input showed empty, but maybe something was cached somehow from when I tried it on `master`? Anyway, the issue was on `master` so this should be the solution.

2021-08-09 21:03 UTC, williamdes approved these changes
🚢

2021-08-09 21:30 UTC, merged