Fix #16067 - Make select elements where multiple items can be selected resizable
phpmyadmin/phpmyadmin pull request #17068
Opened 2021-08-11 03:30 UTC by lrb2

### Description

`<select multiple>` elements can now be resized vertically to make it easier to select multiple items.

![nNfrrIEBA4](https://user-images.githubusercontent.com/59065888/128964538-fa5b2b53-1eac-41b8-bcba-0c96ad2d8a40.gif)

Fixes #16067

2021-08-11 16:57 UTC, williamdes approved these changes

2021-08-22 21:00 UTC, williamdes commented
Hi @mauriciofauth 
Would you send this into QA ?

2021-08-22 21:28 UTC, mauriciofauth requested changes

2021-08-22 21:28 UTC, mauriciofauth commented on themes/bootstrap/scss/_common.scss
> +select[multiple] {
Could you please add this to a class instead of directly to the tag? You could add it to the Bootstrap's class for the select input.

2021-08-22 21:30 UTC, mauriciofauth commented
> Hi @mauriciofauth 
> Would you send this into QA ?

Sure!

2021-08-22 22:16 UTC, lrb2 commented on themes/bootstrap/scss/_common.scss
> +select[multiple] {
Sure. In that case, I think it would be best to put it into a separate class in case any `<select multiple>` elements must not be resizable. So few `<select multiple>` elements have been updated so far to use Bootstrap anyways that adding it to that class (`form-control` in Bootstrap 4.6, `form-select` in Bootstrap 5.0) wouldn't make the fix noticeable for a while.

2021-08-23 08:58 UTC, williamdes commented on themes/pmahomme/scss/_common.scss
> +.resize-vert {
Looks good, a full word would maybe be ever nicer

It triggers my French and makes it say resize-green 😆

2021-08-23 08:58 UTC, williamdes approved these changes

2021-08-23 16:01 UTC, williamdes approved these changes
💯

2021-08-23 16:03 UTC, williamdes commented
Hi @mauriciofauth 
If this version looks good to you I will merge this into QA

2021-08-23 16:17 UTC, mauriciofauth approved these changes

2021-08-23 18:22 UTC, merged