Fix #17062: Pagination issues when working with identically named tables in separate databases
phpmyadmin/phpmyadmin pull request #17070
Opened 2021-08-11 07:06 UTC by lrb2

### Description

Certain details, including the position in the table, are kept in `$_SESSION['tmpval']['query']` under the md5 hash of the SQL query. Since a query for any table named `test` (no matter which database) is `SELECT * FROM 'test'`, the query hash is identical for each table, even though they are in different databases. My change makes the hash dependent on the server and database as well, not just the query, so the hashes are no longer identical.

Fixes #17062

2021-08-21 23:42 UTC, williamdes commented
> This PR should be merged into master because $sqlMd5 is named $sql_md5 in QA_5_1.

Could you please rebase it onto QA_5_1, I will do the merge and fix the variable before the merge of QA -> master commits ?

I am a bit afraid the db property is not always available, will have another look at that

2021-08-22 04:58 UTC, lrb2 commented
I just rebased it. Note that the `providerSetConfigParamsForDisplayTable` function in ResultsTest.php (added in fa12894e5fd0d544a24820600111a3148cfaba96 on `master`) will have to be changed to use the new hash, which should be `27b1330f2076ef45d236f20839a92831`, instead of `0040c297a1a5a4cb1291b086b3ca965b`.

If there is no database specified, `properties['db']` is an empty string in master or null in QA_5_1. Even if it's null, the concatenation still works (at least in PHP 8). I haven't been able to imagine a possible combination of valid queries with and without a database where the resulting hash would be the same. However, when set, `properties['db']` uses the global value of `db` instead of the variable `$db` that was passed to the `executeQueryAndGetQueryResponse` function. I'm not sure when `$db` and `$GLOBALS['db']` are different, but if they are, there is a rare possibility that the hashes could be the same.

2021-08-22 07:30 UTC, williamdes requested changes
Thank you!

2021-08-22 07:30 UTC, williamdes approved these changes

2021-08-22 20:58 UTC, williamdes approved these changes
💯

2021-08-22 20:59 UTC, merged

2021-08-22 21:26 UTC, williamdes commented
I copied one of your previous commits into master branch to fix the tests
See: 13807a1049c1eb58f4acd61a7740387a1114631c