Replace Create view dialog with modal
phpmyadmin/phpmyadmin pull request #17128
Opened 2021-09-26 14:57 UTC by shucontech

Signed-off-by: Saksham Gupta <shucontech@gmail.com>

### Description

Before submitting pull request, please review the following checklist:

- [ ] Make sure you have read our [CONTRIBUTING.md](https://github.com/phpmyadmin/phpmyadmin/blob/master/CONTRIBUTING.md) document.
- [ ] Make sure you are making a pull request against the correct branch. For example, for bug fixes in a released version use the corresponding QA branch and for new features use the _master_ branch. If you have a doubt, you can ask as a comment in the bug report or on the mailing list.
- [ ] Every commit has proper `Signed-off-by` line as described in our [DCO](https://github.com/phpmyadmin/phpmyadmin/blob/master/DCO). This ensures that the work you're submitting is your own creation.
- [ ] Every commit has a descriptive commit message.
- [ ] Every commit is needed on its own, if you have just minor fixes to previous commits, you can squash them.
- [ ] Any new functionality is covered by tests.

2021-10-01 16:51 UTC, mauriciofauth requested changes

2021-10-01 16:51 UTC, mauriciofauth commented on themes/pmahomme/scss/_modal.scss
> +  max-width: 700px;
You should use Bootstrap's classes for this.
https://getbootstrap.com/docs/5.1/components/modal/#optional-sizes

2021-10-01 16:51 UTC, mauriciofauth commented on js/src/functions.js
> +            $('#createViewModal').on('shown.bs.modal', function () {
You should add `$('#createViewModal').modal('show');` after `$('#createViewModal').on('shown.bs.modal'`.

2021-10-28 15:38 UTC, MauricioFauth approved these changes

2021-10-28 15:39 UTC, merged