update privileges.rst button/link names to match phpMyAdmin v5.1.1
phpmyadmin/phpmyadmin pull request #17180
Opened 2021-11-05 18:10 UTC by joelmellon

### Description

Please describe your pull request.

Fixes #

Before submitting pull request, please review the following checklist:

- [ ] Make sure you have read our [CONTRIBUTING.md](https://github.com/phpmyadmin/phpmyadmin/blob/master/CONTRIBUTING.md) document.
- [ ] Make sure you are making a pull request against the correct branch. For example, for bug fixes in a released version use the corresponding QA branch and for new features use the _master_ branch. If you have a doubt, you can ask as a comment in the bug report or on the mailing list.
- [ ] Every commit has proper `Signed-off-by` line as described in our [DCO](https://github.com/phpmyadmin/phpmyadmin/blob/master/DCO). This ensures that the work you're submitting is your own creation.
- [ ] Every commit has a descriptive commit message.
- [ ] Every commit is needed on its own, if you have just minor fixes to previous commits, you can squash them.
- [ ] Any new functionality is covered by tests.

2021-11-07 13:40 UTC, mauriciofauth requested changes
Hi, @joelmellon. Thank you for your contribution.

Before we could merge your pull request, could you please add the `Signed-off-by` line in your commit? Or your can add a comment with this line in this PR and we'll add it for you.

2021-11-07 13:40 UTC, mauriciofauth commented on doc/privileges.rst
> +:guilabel:`User accounts` tab on the home page).
It's actually a link, not a tab. Although some themes make these links look like tabs.

2021-11-08 00:31 UTC, joelmellon commented
> add a comment with this line in this PR and we'll add it for you

Thanks, I hadn't cloned the repo, just a quick edit in GitHub. I don't need credit but if you must:

Signed-off-by: Joel Mellon <joelgmellon@gmail.com>

2021-11-08 01:09 UTC, mauriciofauth commented on doc/privileges.rst
> +:guilabel:`User accounts` tab on the home page).
```suggestion
:guilabel:`User accounts` link on the home page).
```

2021-11-08 01:11 UTC, merged

2021-11-08 01:11 UTC, mauriciofauth commented
Merged, thanks for your contribution!