Minor refactoring of InsertEdit.php
phpmyadmin/phpmyadmin pull request #17199
Opened 2021-11-21 19:52 UTC by kamil-tekiela

This is still minor refactoring despite many changes, as this class is in dire need of Value Objects and removal of globals, which I haven't touched in this PR. Static analysis and I are both restricted in the number of changes that can be made due to the fact that many of the values are typed as mixed. 

The goals of this refactoring:
- Removal of dead code
- Removal of redundant code
- Improving static analysis by providing type hints and type declarations
- Small refactorings to make code easier to read and spot bugs 

This PR does not:
- Change any functionality
- Add any new methods or classes
- Improve unit tests
- Change coding style

It seems that DbiDummy is broken. The tests send an empty array where the `$result` object is expected. The mock methods seem to be returning an integer. I'm not sure what the correct behaviour of this should be, but it looks like it doesn't actually test the right functionality. Am I wrong?

This code contains ABI break, but I hope it won't be a problem. I changed some parameters of private and public methods. It will work the same but callers need to pass different arguments now. 

For the explanation of each change, see the description in commits.

2021-11-22 00:34 UTC, williamdes requested changes
Very nice work, thanks a lot! 
I did a bit of review from my mobile
Will have to have another look

2021-11-22 00:34 UTC, williamdes commented on libraries/classes/InsertEdit.php
> +            $inputMinMax = ' min="' . $minMaxValues[0] . '" '
Not sure if the space should be added there or where the variable is used

2021-11-22 00:34 UTC, williamdes commented on libraries/classes/InsertEdit.php
> +     * @param string $field_MD5 array index as an MD5 to avoid having special characters
```suggestion
     * @param string $fieldHashMd5 array index as an MD5 to avoid having special characters
```
This is maybe better for our coding standard

2021-11-22 00:34 UTC, williamdes commented on libraries/classes/InsertEdit.php
> +        if ($files) {
This is a bit vague, could it be more precise?

2021-11-22 00:34 UTC, williamdes commented on libraries/classes/InsertEdit.php
> +    private function getColumnSize(array $column, string $spec_in_brackets): int
We use camel casing ;)

2021-11-22 00:34 UTC, williamdes commented on libraries/classes/InsertEdit.php
> +            $realNullValue = false;
Is it a bug fix?

2021-11-22 11:11 UTC, kamil-tekiela commented on libraries/classes/InsertEdit.php
> +            $inputMinMax = ' min="' . $minMaxValues[0] . '" '
It doesn't matter really, but if it looks better then I will roll it back. In cases like this, I would usually use `implode()` rather than string concatenation but I didn't want to change too much here.

2021-11-22 11:19 UTC, kamil-tekiela commented on libraries/classes/InsertEdit.php
> +        if ($files) {
I can make it a more strict comparison. I didn't want to change the functionality, but the string comes from Template render so it probably wouldn't hurt to check strictly for an empty string rather than a non-empty-string (which includes string `'0'`). I doubt that the template render would ever return string `'0'` so it should be safe, and we can make it more clear with the help of early return.

2021-11-22 11:24 UTC, kamil-tekiela commented on libraries/classes/InsertEdit.php
> +            $realNullValue = false;
I was not able to identify any buggy behaviour here. Technically it was possible to provide `true` here through the use of the parameter, but in all the uses I could find (including unit tests) it was always hardcoded to `false`. Was it a bug? I don't think so.

2021-11-22 11:34 UTC, williamdes commented on libraries/classes/InsertEdit.php
> +            $realNullValue = false;
Okay, thanks for the fix then ;)

2021-11-22 11:35 UTC, williamdes commented on libraries/classes/InsertEdit.php
> +                if ($insertId) {
could it be more specific ?

2021-11-22 11:36 UTC, williamdes approved these changes
Did not see anything alarming, did post some comments on minor things

2021-11-22 11:56 UTC, williamdes commented on libraries/classes/InsertEdit.php
>              }
The elses could be avoided by setting the value above the if

2021-11-22 11:58 UTC, williamdes commented on libraries/classes/InsertEdit.php
> +        if ($repopulate && $currentRow) {
since currentRow is an array, could we narrow down what we are checking here and further ?

2021-11-22 12:37 UTC, kamil-tekiela commented on libraries/classes/InsertEdit.php
> +                if ($insertId) {
Well... No. The value comes from `insertId()` that relies on undefined behaviour. It's unclear what the possible return values could be. The return value is type hinted as `int|false`, but I doubt that this is really the type of value that will be produced by this method. 

For the record, I removed the redundant check because `$insertId != 0` casts the value to an integer before comparison. This makes `$insertId !== false` redundant. The condition should therefore be `if($insertId != 0)`. But I think here is where I made a mistake/an assumption. If the returned value is an empty array (unlikely) or a non-empty non-numeric-string (possible) then the result of the comparison will be different. For this reason, I will add the `!= 0` back.

2021-11-22 13:05 UTC, kamil-tekiela commented on libraries/classes/InsertEdit.php
> +        if ($repopulate && $currentRow) {
Hmm, yeah. What are we checking here? 😀

2021-11-22 13:22 UTC, kamil-tekiela commented on libraries/classes/InsertEdit.php
> +        if ($repopulate && $currentRow) {
Ok, that's tough. `$repopulate` is a global. It has no defined structure. All we are really checking here is that both arrays are non-empty. I can only introduce `array_key_exists` here on `$repopulate`. 

I could remove the parameter altogether and replace it with the element that we need, but the problem is that I have absolutely no idea what this piece of code does. Unit tests don't cover this code and manual analysis of code flow leads me to madness... 

I will add `array_key_exists()` but if you have an idea on how to improve this piece of code, I would appreciate it.

2021-11-26 17:18 UTC, mauriciofauth approved these changes

2021-11-26 17:19 UTC, merged

2021-11-26 17:19 UTC, mauriciofauth commented
Merged. Thank you very much.

2021-11-26 19:56 UTC, williamdes commented on libraries/classes/InsertEdit.php
> +        if ($repopulate && $currentRow) {
Thank you for the `array_key_exists` ;)