Refactor DatabaseInterface.php
phpmyadmin/phpmyadmin pull request #17209
Opened 2021-11-26 13:54 UTC by kamil-tekiela

This PR improves code readability, performance and stability of DatabaseInterface.php. These are rather minor changes with the exception of adding a new internal method to simplify the code. 

For the explanation behind each change see commit descriptions.

2021-11-26 15:08 UTC, williamdes commented on libraries/classes/Database/CentralColumns.php
> +        return array_values(array_diff($columnNames, $existingColumns));
This is a bit hard to read, could you add a comment about what it does ?

2021-11-26 15:10 UTC, williamdes commented on libraries/classes/Plugins/Export/ExportMediawiki.php
> +            if ($column_names) {
maybe use count or `!= []` ?

2021-11-26 17:29 UTC, kamil-tekiela commented on libraries/classes/Database/CentralColumns.php
> +        return array_values(array_diff($columnNames, $existingColumns));
I'm am of opinion that clean code should be self-explanatory and for this reason I prefer to keep code comments to the minimum. I am a little surprised that this simplification is still confusing. It does exactly what the method name says in 3 lines of code. There is one line `selectDb()` that is confusing to me and I can't explain its purpose. 

Nonetheless, I have added a comment right above `return` to make it as clear as possible that this function returns a simple list of column names except the ones in central list of columns. Please let me know if this makes things any clearer. 

P.S. The method `getFromTable()` is confusing, but that's a separate topic not related to this PR.

2021-11-26 18:40 UTC, mauriciofauth requested changes

2021-11-26 18:40 UTC, mauriciofauth commented on libraries/classes/DatabaseInterface.php
> +     * @param int    $mode   either self::FETCH_ROW or self::FETCH_ASSOC
```suggestion
     * @param int    $mode   either self::FETCH_ROW or self::FETCH_ASSOC
     * @psalm-param self::FETCH_ROW|self::FETCH_ASSOC $mode
```

2021-11-26 19:46 UTC, kamil-tekiela commented on libraries/classes/DatabaseInterface.php
> +     * @param int    $mode   either self::FETCH_ROW or self::FETCH_ASSOC
Thanks for this suggestion. I have thought about it and decided that the solution I came up with was too limited in scope. I decided to rewrite this commit and change the parameter type. I moved the constants to the interface and refactored `fetchSingleRow()`. I replaced literal strings with constants. Hopefully this makes the code cleaner and easier to understand.

2021-11-26 20:04 UTC, williamdes commented on libraries/classes/Database/CentralColumns.php
> +        return array_values(array_diff($columnNames, $existingColumns));
It's very cool with the comment, that helps the brain clear the process between what values are kept from the diff

2021-11-26 20:06 UTC, williamdes commented on libraries/classes/DatabaseInterface.php
> +            if ($database) {
```suggestion
            if ($database !== null) {
```

2021-11-26 20:06 UTC, williamdes commented on libraries/classes/DatabaseInterface.php
> +        if (! $meta) {
The previous syntax was not better and more strict ?

2021-11-26 20:09 UTC, williamdes commented on libraries/classes/DatabaseInterface.php
> +        if ($locale) {
Given the non typed function at https://github.com/phpmyadmin/phpmyadmin/blob/70c43a98633dc475834a0a8d008d96e846dd2ec3/libraries/classes/Language.php#L111

I think it should be explicit
Please try to not widen the possible values that can make if conditions valid :)

2021-11-26 20:10 UTC, williamdes commented on libraries/classes/DatabaseInterface.php
> +            if ($result) {
should we check for false ?

2021-11-26 20:22 UTC, kamil-tekiela commented on libraries/classes/DatabaseInterface.php
> +        if ($locale) {
I haven't widened any condition. I have tried my best to not change any logic. In this case the condition remains the same. 

`empty()` is equivalent to `! isset($var) || ! $var`. See https://www.php.net/manual/en/function.empty.php
This means that `! empty()` is `! (! isset($var) || ! $var)`, which is `(isset($var) && $var)`.
Since we know that the variable is defined this becomes: `($var !== null && $var)` which can be simply written as `if($var)`. 

I have not widened the condition. The change I made has nothing to do with the type returned by the method. I am happy to narrow it down if you think it's safe, but as I said I tried not to change any logic.

2021-11-26 20:28 UTC, kamil-tekiela commented on libraries/classes/DatabaseInterface.php
> +            if ($database) {
I loosened the condition per your suggestion. Thanks.

2021-11-26 20:40 UTC, kamil-tekiela commented on libraries/classes/DatabaseInterface.php
> +        if (! $meta) {
I admit, this is one of the places where I took the liberty of changing the logic. It looks like I forgot to put the commit description. 

This was done because I believe the previous code was buggy. However, the change was related to few lines below it, where I changed it to `if ($nbColumns >= $i) {`. 

I think it is safe to revert back to previous syntax, which was a little bit more verbose, but clearer. According to the code, `getFieldsMeta()` can return `?array`. The condition can be `if($meta === null || $meta === [])`. The `|| $meta === []` is absolutely redundant as the code will behave exactly the same without it, so to make it really easy to read, let's keep it as `if($meta === null)`

2021-11-26 20:51 UTC, kamil-tekiela commented on libraries/classes/DatabaseInterface.php
> +            if ($result) {
Thanks for pointing this out, This looks wrong indeed. Let me investigate.

2021-11-26 22:35 UTC, kamil-tekiela commented on libraries/classes/DatabaseInterface.php
> +            if ($result) {
Thanks! The `if` statements were redundant. This function always returns an array. I removed them now. 

I then decided to add a return type to `fetchResult()` to catch similar issues. This led me to some Psalm fixes and errors in unit tests. All of this should be fixed in the latest commit.

2021-11-26 23:16 UTC, mauriciofauth approved these changes

2021-11-26 23:17 UTC, merged

2021-11-26 23:18 UTC, mauriciofauth commented
Merged. Thank you very much!

2021-11-28 20:34 UTC, williamdes reviewed
:100: