transfer the HTML content in InsertEdti.php for a twig file
phpmyadmin/phpmyadmin pull request #17211
Opened 2021-11-28 01:57 UTC by pedrohfpimentel

…ther_datatype.twig file

Signed-off-by: Pedro Henrique F. Pimentel <pedrohfpimentel@gmail.com>

### Description

Please describe your pull request.

Fixes #

Before submitting pull request, please review the following checklist:

- [ ] Make sure you have read our [CONTRIBUTING.md](https://github.com/phpmyadmin/phpmyadmin/blob/master/CONTRIBUTING.md) document.
- [ ] Make sure you are making a pull request against the correct branch. For example, for bug fixes in a released version use the corresponding QA branch and for new features use the _master_ branch. If you have a doubt, you can ask as a comment in the bug report or on the mailing list.
- [ ] Every commit has proper `Signed-off-by` line as described in our [DCO](https://github.com/phpmyadmin/phpmyadmin/blob/master/DCO). This ensures that the work you're submitting is your own creation.
- [ ] Every commit has a descriptive commit message.
- [ ] Every commit is needed on its own, if you have just minor fixes to previous commits, you can squash them.
- [ ] Any new functionality is covered by tests.

2021-11-28 20:38 UTC, williamdes commented on ,
> +Host = not found: 2(SERVFAIL)
This file was added by mistake :)

2021-11-29 17:19 UTC, mauriciofauth requested changes
Hi @pedrohfpimentel. Thanks for your contribution.

2021-11-29 17:19 UTC, mauriciofauth commented on templates/table/insert/value_column_for_other_datatype.twig
> +  {% if default_generated %}
Since the template have the `column` variable, you can move this condition into the template and remove the `default_generated` variable.

```suggestion
  {% if column.Extra matches '/(VIRTUAL|PERSISTENT|GENERATED)/' and 'DEFAULT_GENERATED' not in column.Extra %}
```

2021-11-29 17:19 UTC, mauriciofauth commented on libraries/classes/InsertEdit.php
> +            'html' => $htmlOutput,
Looks like you forgot to remove the `$htmlOutput` variable.

2021-11-29 17:19 UTC, mauriciofauth commented on libraries/classes/InsertEdit.php
> +            'columnNameAppendix' => $columnNameAppendix,
```suggestion
            'column_name_appendix' => $columnNameAppendix,
```

2022-03-04 15:24 UTC, closed without merging

2022-03-04 15:25 UTC, mauriciofauth commented
Merged in https://github.com/phpmyadmin/phpmyadmin/pull/17410. Thanks for your contribution.