Make $subPart non-nullable and remove redundant ?? when it's not null
phpmyadmin/phpmyadmin pull request #17223
Opened 2021-12-03 17:56 UTC by kamil-tekiela

The whole global `$sub_part` looks fishy, but I wasn't able to identify what purpose it actually fulfils as a global. To remove static analysis issues I removed `??` in places where it was clearly defined and made the parameter non-nullable. According to my analysis it was set to null only in a single place where it was not used anyway. 

Side note: I have been running Psalm and PHPStan with PHP 8.0 until now but recent changes have made it unmanageable so I had to downgrade to PHP 7.4. 7d3c84a88163237211b9908978d473e91657ce3f has reversed psalm-baseline.xml update so when I run `-set-baseline=` again it added the same lines once more. I don't know if it was intentional or not.

2021-12-03 19:15 UTC, mauriciofauth requested changes

2021-12-03 19:15 UTC, mauriciofauth commented on psalm-baseline.xml
> +  <file src="config.inc.php">
Psalm reported errors in your local config file. This should be ignored.

2021-12-03 19:33 UTC, kamil-tekiela commented on psalm-baseline.xml
> +  <file src="config.inc.php">
Of course, I forgot about it. That was stupid of me, thanks for explaining.

2021-12-03 19:37 UTC, mauriciofauth commented
> The whole global `$sub_part` looks fishy, but I wasn't able to identify what purpose it actually fulfils as a global.

This looks like a leftover from when the router was introduced in phpMyAdmin 5.1. This was part of the entry point file names. For example: `server_export.php`, `db_export.php` and `tbl_export.php`.

> Side note: I have been running Psalm and PHPStan with PHP 8.0 until now but recent changes have made it unmanageable so I had to downgrade to PHP 7.4. [7d3c84a](https://github.com/phpmyadmin/phpmyadmin/commit/7d3c84a88163237211b9908978d473e91657ce3f) has reversed psalm-baseline.xml update so when I run `-set-baseline=` again it added the same lines once more. I don't know if it was intentional or not.

In fact, there are some issues running PHPStan with PHP 8.0+. If we make PHPStan green with PHP 7, PHPStan with PHP 8 will fail and vice versa.

2021-12-03 20:22 UTC, kamil-tekiela commented
> This looks like a leftover from when the router was introduced in phpMyAdmin 5.1. This was part of the entry point file names. For example: `server_export.php`, `db_export.php` and `tbl_export.php`.

Thanks. I won't change it anymore at the moment. I still need to understand more about this codebase before I can confidently do bigger changes. 

> In fact, there are some issues running PHPStan with PHP 8.0+. If we make PHPStan green with PHP 7, PHPStan with PHP 8 will fail and vice versa.

Ok, it's not a problem for me. I can run it using PHP 7.4.

2021-12-03 21:50 UTC, williamdes approved these changes

2021-12-08 14:01 UTC, mauriciofauth approved these changes

2021-12-08 14:01 UTC, merged

2021-12-08 14:01 UTC, mauriciofauth commented
Merged, thanks for your contribution!