Refactor CreateAddField
phpmyadmin/phpmyadmin pull request #17233
Opened 2021-12-08 22:18 UTC by kamil-tekiela

This PR removes one private method which wasn't helping with anything and replaces it with simple `foreach` loops. It also removes some temporary variables that didn't help with readability. Finally, it changes the output by removing unnecessary whitespace from the generated SQL. Whitespace is not important and what I removed seems to be completely unnecessary.

2021-12-09 00:34 UTC, mauriciofauth requested changes

2021-12-09 00:34 UTC, mauriciofauth commented on libraries/classes/Controllers/Table/AddFieldController.php
> +            $sql_query = $createAddField->getColumnCreationQuery($table);
Please use camel case where possible.

2021-12-09 00:41 UTC, kamil-tekiela commented on libraries/classes/Controllers/Table/AddFieldController.php
> +            $sql_query = $createAddField->getColumnCreationQuery($table);
It's a global variable. Is it safe to rename it? If so, I think it needs to be done globally, right?

2021-12-10 01:17 UTC, mauriciofauth approved these changes

2021-12-10 01:17 UTC, merged

2021-12-10 01:17 UTC, mauriciofauth commented
Merged, thanks for your contribution!