fix themes cards heights
phpmyadmin/phpmyadmin pull request #17280
Opened 2022-01-09 23:33 UTC by faissaloux

Hello 👋🏻

In this PR I've fixed themes cards heights

# Before
![Screenshot 2022-01-10 002218](https://user-images.githubusercontent.com/60013703/148705701-b0982fbf-dacb-44bc-a953-d8a8642ba4c7.png)

# After
![Screenshot 2022-01-10 002227](https://user-images.githubusercontent.com/60013703/148705707-ce7dc306-f91c-41dc-a679-38da3d1ffc5c.png)

2022-02-05 17:28 UTC, mauriciofauth requested changes
I don't like this change because it stretches the image. Maybe cropping the image would be a better solution.

2022-02-05 18:17 UTC, faissaloux commented
@mauriciofauth Cropped!

![Screenshot 2022-02-05 191536](https://user-images.githubusercontent.com/60013703/152653880-e3c6ec43-a997-43fa-993d-94957e20fb37.png)

2022-02-05 18:58 UTC, mauriciofauth commented
Sorry, I meant cropping the image using CSS.

2022-02-06 00:20 UTC, faissaloux commented
@mauriciofauth done!

2022-02-06 00:24 UTC, williamdes approved these changes
The code looks good but I really think some bootstrap class could be used instead of the `height` attributes

2022-02-06 01:23 UTC, mauriciofauth commented
This makes the images have the same height, but the cards still could have different heights. This will help with that.

```diff
diff --git a/templates/home/themes.twig b/templates/home/themes.twig
index 3fbc4b4e40..604e8d7e90 100644
--- a/templates/home/themes.twig
+++ b/templates/home/themes.twig
@@ -3,7 +3,7 @@
   <div class="row row-cols-1 row-cols-md-2 row-cols-lg-3 row-cols-xl-4 g-4">
     {% for theme in themes %}
       <div class="col">
-        <div class="card">
+        <div class="card h-100">
           <img src="./themes/{{ theme.id }}/screen.png" class="card-img-top" alt="{{ 'Screenshot of the %s theme.'|trans|format(theme.name) }}">
           <div class="card-body">
             <h5 class="card-title">{{ theme.name }} <small>({{ theme.version }})</small></h5>
```

2022-02-06 18:24 UTC, faissaloux commented
@mauriciofauth Fixed!

2022-02-06 18:47 UTC, williamdes commented on themes/bootstrap/scss/_card.scss
> +      height: 100%;
`h-100` can replace this :)

2022-02-06 18:48 UTC, williamdes commented on themes/bootstrap/scss/_card.scss
> +    height: 140px;
maybe some boostrap class could remove the need for this fixed value, I am thinking about very large screens ^^

2022-02-06 19:55 UTC, faissaloux commented on themes/bootstrap/scss/_card.scss
> +      height: 100%;
Yeah right, I'll fix this :)

2022-02-06 20:17 UTC, faissaloux commented on themes/bootstrap/scss/_card.scss
> +    height: 140px;
What about `vh` unit!!

2022-02-07 00:05 UTC, williamdes commented on themes/bootstrap/scss/_card.scss
> +  height: 16vh;
https://caniuse.com/viewport-units
For the record

2022-02-07 00:06 UTC, williamdes approved these changes

2022-02-07 00:08 UTC, faissaloux commented on themes/bootstrap/scss/_card.scss
> +  height: 16vh;
Emmm yeah thank you ^^

2022-02-07 00:25 UTC, williamdes commented on themes/bootstrap/scss/_card.scss
> +  height: 16vh;
Saying this because we have https://github.com/phpmyadmin/phpmyadmin/blob/master/.browserslistrc to respect ;)

2022-02-07 11:37 UTC, mauriciofauth requested changes

2022-02-07 11:37 UTC, mauriciofauth commented on themes/bootstrap/scss/_card.scss
> +  height: 16vh;
You should extract this value into a variable.

2022-02-07 11:37 UTC, mauriciofauth commented on templates/home/themes.twig
> +        <div class="card h-100 mt-0">
This is redundant since cards do not have margin.
```suggestion
        <div class="card h-100">
```

2022-02-07 13:31 UTC, faissaloux commented on templates/home/themes.twig
> +        <div class="card h-100 mt-0">
Actually `.card` have a `margin-top: 2rem;` 😕

2022-02-07 13:35 UTC, faissaloux commented on themes/bootstrap/scss/_card.scss
> +  height: 16vh;
Oh! alright, good to know :)

2022-02-07 13:38 UTC, faissaloux commented on themes/bootstrap/scss/_card.scss
> +  height: 16vh;
Done!

2022-02-07 13:43 UTC, mauriciofauth commented on templates/home/themes.twig
> +        <div class="card h-100 mt-0">
Oh, I see what you mean. The pmahomme's card class has a top margin, however cards in general doesn't have margin. So applying the class to the HTML doesn't make sense.

2022-02-07 13:50 UTC, faissaloux commented on templates/home/themes.twig
> +        <div class="card h-100 mt-0">
Can I remove the margin-top from css! I think that's the option I have. Isn't it using elsewhere!!

2022-02-07 13:52 UTC, williamdes commented on templates/home/themes.twig
> +        <div class="card h-100 mt-0">
FYI: https://getbootstrap.com/docs/5.0/components/card/#variables

I am not sure this helps but in case here is the link where they could have defined the `margin-top` value

2022-02-07 13:57 UTC, faissaloux commented on templates/home/themes.twig
> +        <div class="card h-100 mt-0">
@williamdes No it's not bootstrap style, In `original` and `pmahomme` themes we have that `margin-top` for `.card`.

I wanted to remove it and it will be fixed but afraid it's used somewhere else !! 🤔

2022-02-07 14:00 UTC, williamdes commented on templates/home/themes.twig
> +        <div class="card h-100 mt-0">
Seems to have been added in f19f27942e315764667994c4a8f2f6c5542f12a6 by @mauriciofauth

2022-02-09 13:11 UTC, mauriciofauth commented on templates/home/themes.twig
> +        <div class="card h-100 mt-0">
@faissaloux You can leave the margin-top issue for another PR. The issue is that, for pmahomme and Original themes, the margin-top should only be applied if the card has a card-header.

2022-02-09 23:13 UTC, faissaloux commented on templates/home/themes.twig
> +        <div class="card h-100 mt-0">
@mauriciofauth Yeah exactly. But if we want to apply style to `.card` if only have `.card-header` we need to use js and there's no specific js files for specific theme (I guess) So in this case I think the `mt-0` class fixed this problem for themes cards and it have no other effects.

2022-04-22 02:23 UTC, merged

2022-04-22 02:23 UTC, mauriciofauth commented
Merged, thanks for your contribution!

2022-04-22 08:40 UTC, williamdes commented
@mauriciofauth should this be picked into 5.2 ?

2022-04-22 15:23 UTC, mauriciofauth commented
> @mauriciofauth should this be picked into 5.2 ?

I don't think it's needed. It's more like an enhancement than a fix.