Refactor getHtmlForDisplayedExportHeader
phpmyadmin/phpmyadmin pull request #17579
Opened 2022-06-02 22:07 UTC by kamil-tekiela

I just wanted to remove the GLOBAL that shouldn't be there, but I ended up splitting the method into 3 separate ones.

2022-06-02 22:44 UTC, kamil-tekiela commented
Unrelated, but the resulting textarea seems to overflow my screen.

2022-06-10 19:47 UTC, MauricioFauth requested changes

2022-06-10 19:47 UTC, MauricioFauth commented on libraries/classes/Export.php
> +        $postParams = array_filter($this->getPostParams($exportType), static fn ($value) => ! is_array($value));
Please use an anonymous function here. It should support PHP 7.2.

2022-06-11 04:20 UTC, MauricioFauth approved these changes

2022-06-11 04:20 UTC, merged