Changing password should respect AllowNoPassword #17262Update functions.js
phpmyadmin/phpmyadmin pull request #17613
Opened 2022-06-19 23:25 UTC by RamiRima

2022-06-19 23:30 UTC, williamdes requested changes
Please use a translation string in the controller file: https://github.com/phpmyadmin/phpmyadmin/blob/master/libraries/classes/Controllers/JavaScriptMessagesController.php#L40

By the way there is a typo in the sentence

2022-06-19 23:56 UTC, liviuconcioiu requested changes

2022-06-19 23:56 UTC, liviuconcioiu commented on libraries/classes/Controllers/JavaScriptMessagesController.php
> +                'You are trying to set this account to log in without a password but the configuration directive AllowNoPassword is false. If you procced, the account will not be able to log in throu
`You are trying to set this account to log in without a password but the configuration directive AllowNoPassword is false. If you proceed, the account will not be able to log in through phpMyAdmin. Do you wish to proceed?`

2022-06-20 00:09 UTC, liviuconcioiu requested changes

2022-06-20 00:09 UTC, liviuconcioiu commented on libraries/classes/Controllers/JavaScriptMessagesController.php
> +            'You are trying to set this account to log in without a password but the configuration directive AllowNoPassword is false. If you proceed, the account will not be able to log in through p
Can you remove the white space at the end?

2022-06-20 00:29 UTC, williamdes commented on js/src/functions.js
> +        }
I think this is not the proper way to do this, @MauricioFauth do you have some advice ?

You should run `yarn js-lint --fix` on this block of code

2022-07-18 18:25 UTC, MauricioFauth commented
Hi @RamiRima, thanks for your contribution.

As described in the issue, we should check if [`$GLOBALS['cfg']['Server']['AllowNoPassword'] === false`](https://docs.phpmyadmin.net/en/latest/config.html#cfg_Servers_AllowNoPassword) before warning the user.

Also, it's a best practice to use a different branch to open a pull request, this allows you to open more than one pull request.

2022-07-18 18:25 UTC, closed without merging