Update form.twig
phpmyadmin/phpmyadmin pull request #17633
Opened 2022-07-08 16:00 UTC by rodentooth

inserted focus script

### Description

Pull Request for suggested improvement: https://github.com/phpmyadmin/phpmyadmin/issues/17632

Fixes #

Before submitting pull request, please review the following checklist:

- [x] Make sure you have read our [CONTRIBUTING.md](https://github.com/phpmyadmin/phpmyadmin/blob/master/CONTRIBUTING.md) document.
- [x] Make sure you are making a pull request against the correct branch. For example, for bug fixes in a released version use the corresponding QA branch and for new features use the _master_ branch. If you have a doubt, you can ask as a comment in the bug report or on the mailing list.
- [x] Every commit has proper `Signed-off-by` line as described in our [DCO](https://github.com/phpmyadmin/phpmyadmin/blob/master/DCO). This ensures that the work you're submitting is your own creation.
- [x] Every commit has a descriptive commit message.
- [x] Every commit is needed on its own, if you have just minor fixes to previous commits, you can squash them.
- [x] Any new functionality is covered by tests.

2022-07-08 20:08 UTC, williamdes requested changes
I do not think this is the proper way to do this
@MauricioFauth what would you suggest?

2022-07-16 17:54 UTC, MauricioFauth requested changes
You should use [`autofocus`](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/autofocus) as suggested by @smalos.

2022-07-20 03:53 UTC, tuguldurCh approved these changes

2022-07-20 03:54 UTC, tuguldurCh reviewed
d

2022-11-25 21:20 UTC, closed without merging