Fixed find and replace using regex makes an invalid query if no matching result set found
phpmyadmin/phpmyadmin pull request #17641
Opened 2022-07-17 14:35 UTC by asprazz

Signed-off-by: Ankush Patil <aspraz2658@gmail.com>

### Description
When find and replace searching used with regex, at the time of replace empty CASE END condition was causing issue.

Fixes #17388 

Before submitting pull request, please review the following checklist:

- [x] Make sure you have read our [CONTRIBUTING.md](https://github.com/phpmyadmin/phpmyadmin/blob/master/CONTRIBUTING.md) document.
- [x] Make sure you are making a pull request against the correct branch. For example, for bug fixes in a released version use the corresponding QA branch and for new features use the _master_ branch. If you have a doubt, you can ask as a comment in the bug report or on the mailing list.
- [x] Every commit has proper `Signed-off-by` line as described in our [DCO](https://github.com/phpmyadmin/phpmyadmin/blob/master/DCO). This ensures that the work you're submitting is your own creation.
- [x] Every commit has a descriptive commit message.
- [x] Every commit is needed on its own, if you have just minor fixes to previous commits, you can squash them.
- [x] Any new functionality is covered by tests.

2022-07-17 14:49 UTC, williamdes approved these changes
Wow, you added a test, you rock ! 🥇 

@MauricioFauth are you okay with the new SQL behavior ?

2022-07-18 18:06 UTC, MauricioFauth requested changes
Thank you for contribution. The coding standard errors should be fixed before merging this pull request.

2022-07-18 18:09 UTC, MauricioFauth commented
> @MauricioFauth are you okay with the new SQL behavior ?

I'm okay. However a message saying that no results were found and not allowing to continue would be better. That could be done in `master` branch.

2022-07-19 18:51 UTC, closed without merging

2022-07-19 18:51 UTC, MauricioFauth commented
Merged, thanks for your contribution!

2022-07-20 04:31 UTC, asprazz commented
Their was one lint issue I meant to fix.... 
I was going to check the same. Any way thank you. Happy to help.