add gitHub action close stale issues
phpmyadmin/phpmyadmin pull request #17662
Opened 2022-07-25 23:26 UTC by NF11

Hi, this PR could help for https://github.com/phpmyadmin/phpmyadmin/issues/17488
Signed-off-by: Nassim FARES [nassim.fares.dz@gmail.com](mailto:nassim.fares.dz@gmail.com)
Fixes https://github.com/phpmyadmin/phpmyadmin/issues/17488

2022-07-26 16:38 UTC, MauricioFauth requested changes
Thank you for your contribution.

2022-07-26 16:38 UTC, MauricioFauth commented on .github/workflows/stale.yml
> +            This issue has been automatically marked as stale because it has not had
I don't think it's a good idea to close stale issues right now, only pull requests.

2022-07-26 16:55 UTC, williamdes commented on .github/workflows/stale.yml
> +            This issue has been automatically marked as stale because it has not had
I would even argue that I do not think we wave stale "issues"
Only stale issues with label: question

2022-07-26 19:10 UTC, NF11 commented on .github/workflows/stale.yml
> +            This issue has been automatically marked as stale because it has not had
I tried to follow what was on Probot Stale

2022-07-26 19:55 UTC, williamdes commented on .github/workflows/stale.yml
> +
You should add the permissions section, see other workflows for this and documentation :)

2022-07-26 19:56 UTC, williamdes commented on .github/workflows/stale.yml
> +          exempt-issue-labels: "type: pinned,type: security"
We do not have a security label and it is not used actually
Is there other ways to only mark stale question labels without any response?

2022-10-02 21:28 UTC, divinity76 commented
instead of marking as "wontfix", can we instead make a dedicated "stale" label?

2022-10-10 10:43 UTC, williamdes requested changes
Unfortunately I do not see any use of this change. Pull-requests do not require stale management.
Could you rather help me with label:"question" as they often go stale and cause me much work to keep up to date and do manually the closing.

The message I use:
> _Could not reproduce, closing since no feedback or no way of reproducing was found.
Comment if you find a way to reproduce this issue, or want to re-open for a valid reason._

2023-02-02 18:33 UTC, williamdes commented on .github/workflows/stale.yml
> +          only-pr-labels : "question"
```suggestion
          only-issue-labels: "question"
```

2023-02-02 18:33 UTC, williamdes commented on .github/workflows/stale.yml
> +            for your contributions.
This can be removed

2023-02-02 18:34 UTC, williamdes commented on .github/workflows/stale.yml
> +          exempt-pr-labels: "type: pinned,type: security"
```suggestion
```
This is not needed, but if we can post a ping message before closing it could be great

2023-03-10 15:27 UTC, williamdes approved these changes

2024-04-27 08:50 UTC, merged

2024-04-27 08:51 UTC, williamdes commented
Merged as 0d27683e941aca2556edc225cc51f6026d3644ae