Issue #17727 Started refactoring uses of $db and $table
phpmyadmin/phpmyadmin pull request #17729
Opened 2022-09-18 18:09 UTC by soloistic

### Description

Issue #17727 Started refactoring uses of $db and $table to use the Objects - DatabaseName and TableName

Changed uses related to Privileges

Created PR to know if changes are on the right track before refactoring more uses that spans multiple classes

Signed-off-by: Solomon Okunuga <soloistic1@gmail.com>

2022-09-18 18:11 UTC, williamdes approved these changes
The code look good. If this PR is not finished you can "Convert to draft" :)

2022-09-18 18:16 UTC, soloistic commented
Okay, happy to move back to Draft... Just wondered about Mauricio's comment:

"you don't need to change all cases before opening a pull request, you can change a small piece of code, test if it's working and then open a pull request. That will make your PR easier to review and merge."

What's a reasonable amount for a small piece of code in this context? Should I go for say 15-20 files at a time? More? Less?

2022-09-18 18:22 UTC, williamdes commented
> Okay, happy to move back to Draft... Just wondered about Mauricio's comment:
> 
> "you don't need to change all cases before opening a pull request, you can change a small piece of code, test if it's working and then open a pull request. That will make your PR easier to review and merge."
> 
> What's a reasonable amount for a small piece of code in this context? Should I go for say 15-20 files at a time? More? Less?

Oh no worries, it's just about if you want to change more things or not. For now I approved the code changes. It can be merged. But if you want to push more work convert it to a draft

2022-09-18 18:23 UTC, williamdes commented
> What's a reasonable amount for a small piece of code in this context? Should I go for say 15-20 files at a time? More? Less?

By group of end functions like you did is good for me, let's wait some feedback from @MauricioFauth first

2022-09-18 18:24 UTC, soloistic commented
> Oh no worries, it's just about if you want to change more things or not. For now I approved the code changes. It can be merged. But if you want to push more work convert it to a draft

Ahh right, makes sense now

2022-09-18 20:53 UTC, MauricioFauth requested changes
Thank you for your contribution.

2022-09-18 20:53 UTC, MauricioFauth commented on libraries/classes/Server/Privileges.php
> +    public function getAllPrivileges(DatabaseName $db, TableName $table = null): array
```suggestion
    public function getAllPrivileges(DatabaseName $db, ?TableName $table = null): array
```

2022-09-18 20:53 UTC, MauricioFauth commented on libraries/classes/Server/Privileges.php
>       *
You can safely remove this redundant information.

```suggestion
```

2022-09-18 20:53 UTC, MauricioFauth commented on libraries/classes/Server/Privileges.php
>       *
You can safely remove this redundant information.

```suggestion
```

2022-09-18 20:53 UTC, MauricioFauth commented on libraries/classes/Server/Privileges.php
>       *
You can safely remove this redundant information.

```suggestion
```

2022-09-18 20:53 UTC, MauricioFauth commented on libraries/classes/Server/Privileges.php
> +                WHERE \'' . $this->dbi->escapeString($db->getName()) . '\' LIKE `Db` AND NOT (' . $listOfComparedPrivileges . ')
The length of the line exceeds 120 characters.
```suggestion
                WHERE \'' . $this->dbi->escapeString($db->getName()) . '\' LIKE `Db` AND NOT ('
                . $listOfComparedPrivileges . ')
```

2022-09-18 20:53 UTC, MauricioFauth commented on libraries/classes/Server/Privileges.php
>       *
You can safely remove this redundant information.

```suggestion
```

2022-09-18 20:53 UTC, MauricioFauth commented on libraries/classes/Controllers/Table/PrivilegesController.php
> +        $table = TableName::fromValue($GLOBALS['table']);
I forgot to mention in the issue, but when an invalid name is provided, the `fromValue` method will throw an exception. This should be handled. 
However I added in 6792b17e72f28ec61a0a9b32055c751d34336e5e a new method called `tryFromValue` that returns `null` for invalid names.
`$GLOBALS['db']` and `$GLOBALS['table']` will hold an empty string for invalid names. So if `tryFromValue` returns `null`, you can assign an empty string (`$db !== null ? $db->getName() : ''`) as it's the current behavior.

2022-09-18 21:25 UTC, williamdes commented on libraries/classes/Server/Privileges.php
> +    public function getAllPrivileges(DatabaseName $db, TableName $table = null): array
i did think about that but maybe it's better we can not pass this param as null so we use the simpler syntax each time ?

2022-09-20 02:04 UTC, MauricioFauth commented on libraries/classes/Server/Privileges.php
> +    public function getAllPrivileges(DatabaseName $db, TableName $table = null): array
> i did think about that but maybe it's better we can not pass this param as null so we use the simpler syntax each time ?

It does not prevent passing `null` (See https://3v4l.org/8Jsqv). But it fail the coding standard check. https://github.com/phpmyadmin/phpmyadmin/actions/runs/3078113001/jobs/4973518771#step:8:36

2022-09-30 22:33 UTC, merged

2022-09-30 22:35 UTC, MauricioFauth commented
Merged, thanks for your contribution!

2022-09-30 22:40 UTC, soloistic commented
Thank you!
And apologies I couldn't return to finish it up. I got a bit swamped with other responsibilities.

2022-09-30 23:55 UTC, MauricioFauth commented
> Thank you! And apologies I couldn't return to finish it up. I got a bit swamped with other responsibilities.

You don't have to apologize. Thank you for you contribution.
I added the error handling and some tests in 135cd76d3b3d4a2ce805434632b286c915ad6dc9.