i refactored uses of [db] and [table]
phpmyadmin/phpmyadmin pull request #17744
Opened 2022-10-01 17:58 UTC by Adams-Ijachi

### Description

Please describe your pull request.
i refactored some instances $Global[db] and $Global[table] to use a value object

Fixes #17727

Before submitting pull request, please review the following checklist:

- [ ] Make sure you have read our [CONTRIBUTING.md](https://github.com/phpmyadmin/phpmyadmin/blob/master/CONTRIBUTING.md) document.
- [ ] Make sure you are making a pull request against the correct branch. For example, for bug fixes in a released version use the corresponding QA branch and for new features use the _master_ branch. If you have a doubt, you can ask as a comment in the bug report or on the mailing list.
- [ ] Every commit has proper `Signed-off-by` line as described in our [DCO](https://github.com/phpmyadmin/phpmyadmin/blob/master/DCO). This ensures that the work you're submitting is your own creation.
- [ ] Every commit has a descriptive commit message.
- [ ] Every commit is needed on its own, if you have just minor fixes to previous commits, you can squash them.
- [ ] Any new functionality is covered by tests.

2022-10-01 17:59 UTC, Adams-Ijachi commented
I just made this commit , i plan on making more but wanted to know if i am on the right path

2022-10-08 02:20 UTC, MauricioFauth requested changes

2022-10-08 02:20 UTC, MauricioFauth commented on libraries/classes/Controllers/CheckRelationsController.php
> +            $this->relation->fixPmaTables(DatabaseName::fromValue($GLOBALS['db']));
This method is expecting a string, not a DatabaseName object. You should first create the object, then pass the name as string. For example:

```suggestion
            $db = DatabaseName::tryFromValue($GLOBALS['db']);
            $this->relation->fixPmaTables($db !== null ? $db->getName() : '');
```

2022-10-08 02:20 UTC, MauricioFauth commented on libraries/classes/Controllers/CheckRelationsController.php
> +            'db' => DatabaseName::fromValue($GLOBALS['db']),
The key `'db'` is expecting a string value here.

2022-10-08 02:20 UTC, MauricioFauth commented on libraries/classes/Controllers/HomeController.php
> +            'table' => TableName::fromValue($GLOBALS['table']),
The `'db'` and `'table'` keys are expecting a string value here.

2023-02-20 16:14 UTC, MauricioFauth commented
Hi @Adams-Ijachi. Thank you for your contribution.
This pull request was replaced by https://github.com/phpmyadmin/phpmyadmin/pull/17829.
I hope to see more contributions from you.

2023-02-20 16:14 UTC, closed without merging