Use DatabaseName instead of string in tryColumnCreationQuery function
phpmyadmin/phpmyadmin pull request #17746
Opened 2022-10-02 08:26 UTC by umangbp

Signed-off-by: Umang Patel <umang.patel@healthengine.com.au>

### Description

This PR refactors tryColumnCreationQuery function and all its occurrences to use `DatabaseName` type instead of `string` type for db name

Before submitting pull request, please review the following checklist:

- [ ] Make sure you have read our [CONTRIBUTING.md](https://github.com/phpmyadmin/phpmyadmin/blob/master/CONTRIBUTING.md) document.
- [ ] Make sure you are making a pull request against the correct branch. For example, for bug fixes in a released version use the corresponding QA branch and for new features use the _master_ branch. If you have a doubt, you can ask as a comment in the bug report or on the mailing list.
- [ ] Every commit has proper `Signed-off-by` line as described in our [DCO](https://github.com/phpmyadmin/phpmyadmin/blob/master/DCO). This ensures that the work you're submitting is your own creation.
- [ ] Every commit has a descriptive commit message.
- [ ] Every commit is needed on its own, if you have just minor fixes to previous commits, you can squash them.
- [ ] Any new functionality is covered by tests.

2022-10-02 08:52 UTC, williamdes approved these changes

2022-10-03 03:12 UTC, umangbp commented
@williamdes @MauricioFauth Hey Guys, I am not sure why end to end tests are failing. It does not look like anything related to the changes I made is affecting it. Happy to receive any feedback if it's my changes failing that.

2022-10-03 13:44 UTC, umangbp commented
@williamdes can you please assign this issue to me.

2022-10-08 02:24 UTC, MauricioFauth requested changes

2022-10-08 02:24 UTC, MauricioFauth commented on libraries/classes/Controllers/Export/ExportController.php
> +                            DatabaseName::fromValue($GLOBALS['db']),
You are creating a new object each time, you could assign the database name to a variable. For example:

```php
$db = DatabaseName::fromValue($GLOBALS['db']);
```

2022-10-21 00:33 UTC, MauricioFauth approved these changes

2022-10-21 00:34 UTC, merged

2022-10-21 00:34 UTC, MauricioFauth commented
Merged, thanks for your contribution!

2022-10-29 14:25 UTC, williamdes reviewed
👍🏻

2024-12-19 02:07 UTC, williamdes reviewed
👁️ (sorry GH still review requests me)