Adding inputmode numeric to integer fields
phpmyadmin/phpmyadmin pull request #17753
Opened 2022-10-04 17:43 UTC by greew

### Description

To easier use phpMyAdmin on touch devices with virtual keyboards, adding the inputmode ensures that the correct virtual keyboard is shown per default when focusing the field.

See https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/inputmode for more information.

Ref:  #17745 

Signed-off-by: Jesper Skytte <jesper@skytte.it>

2022-10-04 20:39 UTC, williamdes approved these changes

2022-10-05 05:56 UTC, ibennetch approved these changes

2022-10-05 06:03 UTC, greew commented
As far as I can see, the failing test can't be on my part, as I haven't changed anything about the `$column` variable. 

Can you confirm that?

```
1) PhpMyAdmin\Tests\InsertEditTest::testGetHTMLinput
Undefined array key "Type"

/app/libraries/classes/InsertEdit.php:699
/app/test/classes/AbstractTestCase.php:223
/app/test/classes/InsertEditTest.php:1064
/app/vendor/phpunit/phpunit/phpunit:98
/app/vendor/bin/phpunit:123
```

2022-10-08 00:22 UTC, MauricioFauth requested changes
Hi, @greew. Thank you for your contribution.

2022-10-08 00:22 UTC, MauricioFauth commented on test/classes/InsertEditTest.php
> +        $column['True_Type'] = 'int';
The missing `$column['Type']` should be added.

```suggestion
        $column['True_Type'] = 'int';
        $column['Type'] = 'int(11)';
```

2022-10-08 00:22 UTC, MauricioFauth commented on test/classes/InsertEditTest.php
> +                30,
```suggestion
                11,
```

2022-10-08 00:22 UTC, MauricioFauth commented on test/classes/InsertEditTest.php
> +            . ' class="textfield datetimefield" c tabindex="25" inputmode="numeric" id="field_0_3">',
```suggestion
            '<input type="text" name="fieldsa" value="b" size="11" min="-2147483648" max="2147483647" data-type="INT"'
            . ' class="textfield" c tabindex="25" inputmode="numeric" id="field_0_3">',
```

2022-10-08 00:22 UTC, MauricioFauth commented on libraries/classes/InsertEdit.php
> +        $inputMode = '';
```suggestion
```

2022-10-08 00:22 UTC, MauricioFauth commented on libraries/classes/InsertEdit.php
>          if (in_array($column['True_Type'], $this->dbi->types->getIntegerTypes())) {
You can assign the condition value to use it later to add the input mode. 

```suggestion
        $isInteger = in_array($column['True_Type'], $this->dbi->types->getIntegerTypes());
        if ($isInteger) {
```

2022-10-08 00:22 UTC, MauricioFauth commented on libraries/classes/InsertEdit.php
> +            $inputMode = 'inputmode="numeric"';
```suggestion
```

2022-10-08 00:22 UTC, MauricioFauth commented on libraries/classes/InsertEdit.php
> +            . ($inputMode ? ' ' . $inputMode : '')
That way the HTML is not stored in variable, so it's more clear what's happening here.

```suggestion
            . ($isInteger ? ' inputmode="numeric"' : '')
```

2022-10-08 00:22 UTC, MauricioFauth commented on libraries/classes/InsertEdit.php
>              $extractedColumnspec = Util::extractColumnSpec($column['Type']);
The `$column['Type']` in this line is what caused the test to fail.

2022-10-08 00:22 UTC, MauricioFauth commented on test/classes/InsertEditTest.php
> +                'DATE',
```suggestion
                'NUMBER',
```

2022-10-09 06:55 UTC, greew commented
> [MauricioFauth](/MauricioFauth)

Great stuff! I'll look into it right away! :)

2022-10-09 06:58 UTC, greew commented on libraries/classes/InsertEdit.php
>              $extractedColumnspec = Util::extractColumnSpec($column['Type']);
That makes sense - thank you!

2022-10-09 08:21 UTC, williamdes approved these changes

2022-10-09 18:23 UTC, MauricioFauth approved these changes

2022-10-09 18:26 UTC, merged