Support UUID data type for MariaDB
phpmyadmin/phpmyadmin pull request #17767
Opened 2022-10-10 15:44 UTC by sureemo

### Description

Support UUID data type for `MariaDB` since version `10.7.0`

Reference issue: https://github.com/phpmyadmin/phpmyadmin/issues/17248

**Screenshots**

<img width="310" alt="Screen Shot 2565-10-10 at 22 01 44" src="https://user-images.githubusercontent.com/1849256/194904633-5ee1a236-f339-449d-84b0-626f3d089f12.png">

<img width="403" alt="Screen Shot 2565-10-10 at 22 02 20" src="https://user-images.githubusercontent.com/1849256/194904672-9e2f6661-4966-48d2-ba19-08d6d37af48c.png">

Signed-off-by: Mo Sureerat <sureemo@gmail.com>

2022-10-10 16:33 UTC, williamdes commented on libraries/classes/Types.php
> +    private function isUUIDEnabled(): bool
There is a class where such logic resides, in the folder query.
The class Compatibility

2022-10-10 18:18 UTC, sureemo commented on libraries/classes/Types.php
> +    private function isUUIDEnabled(): bool
thank you for suggestion, the method is now moved.

2022-10-11 00:09 UTC, MauricioFauth requested changes

2022-10-11 00:09 UTC, MauricioFauth commented on libraries/classes/DatabaseInterface.php
> +    public function setDatabaseVersion(string $database, string $version): void
I think it's better to use/improve the `DatabaseInterface::setVersion` function instead.

2022-10-11 00:12 UTC, MauricioFauth commented on libraries/classes/DatabaseInterface.php
> +    public function setDatabaseVersion(string $database, string $version): void
You can backport this function to QA_5_2:

https://github.com/phpmyadmin/phpmyadmin/blob/6785c97d22e764bb87cfa86eae199d5f7909297a/libraries/classes/DatabaseInterface.php#L2037-L2044

2022-10-11 06:05 UTC, sureemo commented on libraries/classes/DatabaseInterface.php
> +    public function setDatabaseVersion(string $database, string $version): void
thank you for suggestions, i have moved to `setVersion` but use logic from `postConnect`. please feel free to comment.

2022-10-11 07:18 UTC, williamdes commented on libraries/classes/DatabaseInterface.php
> +            $this->isMariaDb = true;
```suggestion
            $this->isMariaDb = true;
            return;
```
If isPercona is set to false by default we can quick exit here

2022-10-11 07:18 UTC, williamdes commented on libraries/classes/Query/Compatibility.php
> +        return $dbi->getVersion() >= self::UUID_SUPPORT_MARIADB_VERSION;
I think we can do like other methods and not use a const

2022-10-11 07:20 UTC, williamdes commented on test/classes/TypesTest.php
> +                    '0' => 'AES_DECRYPT',
I think you could avoid this by doing some `array_values` when you remove the uuid key

2022-10-11 07:29 UTC, williamdes approved these changes

2022-10-11 11:09 UTC, sureemo commented on libraries/classes/DatabaseInterface.php
> +            $this->isMariaDb = true;
Thank you to comment on this code, I think should it refresh value both `isMariaDb` and `isPercona` .. so remove condition check is better.

2022-10-11 11:09 UTC, sureemo commented on libraries/classes/Query/Compatibility.php
> +        return $dbi->getVersion() >= self::UUID_SUPPORT_MARIADB_VERSION;
updated as suggestion. thank you.

2022-10-11 11:09 UTC, sureemo commented on test/classes/TypesTest.php
> +                    '0' => 'AES_DECRYPT',
improve the code as suggestion. thank you.

2022-10-11 11:40 UTC, williamdes approved these changes

2022-10-11 12:07 UTC, kamil-tekiela requested changes

2022-10-11 12:07 UTC, kamil-tekiela commented on libraries/classes/Query/Compatibility.php
> +     * true if uuid is supported
```suggestion
     * Check whether the database supports UUID data type
```

2022-10-11 12:07 UTC, kamil-tekiela commented on libraries/classes/Query/Compatibility.php
> +        return $dbi->getVersion() >= 100700; // 10.7.0
```suggestion
        return $dbi->isMariaDB() && $dbi->getVersion() >= 100700; // 10.7.0
```

2022-10-11 14:32 UTC, MauricioFauth approved these changes

2022-10-11 15:00 UTC, williamdes approved these changes

2022-10-12 11:04 UTC, williamdes commented
Can I merge your work @sureemo ?

2022-10-12 11:06 UTC, sureemo commented
> Merge branch 'QA_5_2' into feature/issue-17248-add-uuid

of course. but there are some tests fail .. about context keywords .. still not find the root cause.

2022-10-12 15:59 UTC, sureemo commented
@williamdes build checks are green now. ready to be reviewed and merged. thank you ^_^

2022-10-12 16:41 UTC, MauricioFauth approved these changes

2022-10-12 17:18 UTC, williamdes approved these changes

2022-10-12 17:19 UTC, williamdes commented
Fixes: #17248

2022-10-12 17:36 UTC, merged