Make search input field types match columns types (integer and float)
phpmyadmin/phpmyadmin pull request #17765
Opened 2022-10-10 10:44 UTC by Bhuvi100

Signed-off-by: Bhuvi100 <gbhuvanesh100@gmail.com>

### Description

This PR adds type attribute as well as inputmode attribute to search value input fields which makes it easier for validation as well as for using phpMyAdmin on touch devices with virtual keyboards.

Fixes #17745 Input types should match the column type (reopened)

Signed-off-by: Bhuvi100 <gbhuvanesh100@gmail.com>

2022-10-10 10:54 UTC, williamdes commented on templates/table/search/input_box.twig
> +                data-type="INT"
this will be overridden by the next line `data-type="{{ column_data_type }}"`
Maybe `column_data_type` should be changed. You can change the value in the PHP code

2022-10-10 11:04 UTC, Bhuvi100 commented on templates/table/search/input_box.twig
> +                data-type="INT"
Actually it didn't override but still I have used column_data_type variable

2022-10-10 11:06 UTC, williamdes commented on libraries/classes/Types.php
> +    public function getFloatTypes()
```suggestion
    public function getFloatTypes(): array
```

2022-10-10 21:12 UTC, MauricioFauth requested changes

2022-10-10 21:12 UTC, MauricioFauth commented on libraries/classes/Controllers/Table/SearchController.php
> +            $is_integer = true;
```suggestion
        $isInteger = in_array($cleanType, $this->dbi->types->getIntegerTypes());
        $isFloat = in_array($cleanType, $this->dbi->types->getFloatTypes());
        if ($isInteger) {
```

2022-10-10 21:12 UTC, MauricioFauth commented on libraries/classes/Controllers/Table/SearchController.php
> +            $is_float = true;
```suggestion
```

2022-10-10 21:12 UTC, MauricioFauth commented on libraries/classes/Controllers/Table/SearchController.php
> +            'column_data_type' => $is_integer ? "INT" : ($is_float ? "FLOAT" : strtoupper($cleanType)),
```suggestion
            'column_data_type' => $isInteger ? 'INT' : ($isFloat ? 'FLOAT' : strtoupper($cleanType)),
```

2022-10-10 21:12 UTC, MauricioFauth commented on libraries/classes/Controllers/Table/SearchController.php
> +            'is_float' => $is_float,
```suggestion
            'is_integer' => $isInteger,
            'is_float' => $isFloat,
```

2022-10-11 07:58 UTC, williamdes approved these changes
For me this looks okay

2022-10-17 18:41 UTC, merged

2022-10-17 18:41 UTC, MauricioFauth commented
Merged, thanks for your contribution!