Issues/16276
phpmyadmin/phpmyadmin pull request #17795
Opened 2022-10-14 13:32 UTC by MrMadClown

# Description

As described in [#16276](https://github.com/phpmyadmin/phpmyadmin/issues/16276)

This PR aims to reduce the usage of SuperGlobals outside of Controllers.

2022-10-14 13:43 UTC, kamil-tekiela requested changes

2022-10-14 13:43 UTC, kamil-tekiela commented on libraries/classes/UrlRedirector.php
> +            ! is_scalar($url) || strlen((string) $url) === 0
```suggestion
            $url === null || $url === ''
```

2022-10-14 13:43 UTC, kamil-tekiela commented on libraries/classes/UrlRedirector.php
> +    public static function redirect(?string $url): void
```suggestion
    public static function redirect(string $url): void
```
It doesn't need to be nullable. Why not just provide an empty string instead? Then all the `(string)` can be removed and the check for `is_scalar` or `=== null` be removed too.

2022-10-14 13:43 UTC, kamil-tekiela commented on libraries/classes/ReplicationGui.php
> +        if (! empty($postUsername)) {
```suggestion
        if ($postUsername !== null && $postUsername !== '' && $postUsername !== '0') {
```
`empty` is bad because it hides typos. Please use more explicit check. In my experience the check for 0-string can be ignored, but please check the logic to make sure it's redundant.

2022-10-14 13:43 UTC, kamil-tekiela commented on libraries/classes/ReplicationGui.php
> +        if ($postUsername !== null && strlen($postUsername) === 0) {
```suggestion
        if ($postUsername !== null && $postUsername === '') {
```

2022-10-15 09:11 UTC, williamdes approved these changes

2022-10-15 09:20 UTC, kamil-tekiela requested changes

2022-10-15 09:20 UTC, kamil-tekiela commented on libraries/classes/ReplicationGui.php
> +     * @param null|string $connection               Primary connection
```suggestion
     * @param string|null $connection               Primary connection
```

2022-10-15 09:20 UTC, kamil-tekiela commented on libraries/classes/ReplicationGui.php
> +     * @param null|string $connection primary connection
```suggestion
     * @param string|null $connection primary connection
```

2022-10-15 09:20 UTC, kamil-tekiela commented on libraries/classes/ReplicationGui.php
> +        }else if ($postUsername !== null && $postUsername !== '0') {
```suggestion
        } elseif ($postUsername !== null && $postUsername !== '0') {
```

2022-10-15 09:20 UTC, kamil-tekiela commented on libraries/classes/ReplicationGui.php
> +    {
```suggestion
    ): string {
```

2022-10-15 09:20 UTC, kamil-tekiela commented on libraries/classes/ReplicationGui.php
> +        $srSkipErrorsCount,
I think the type should be nullable int, but if you are not sure then specifying the type in the phpdoc should be enough.

2022-10-15 09:20 UTC, kamil-tekiela commented on libraries/classes/ReplicationGui.php
> +    public function handleRequestForReplicaSkipError($srSkipErrorsCount): bool
Same here.

2022-10-15 09:27 UTC, MrMadClown commented on libraries/classes/ReplicationGui.php
> +        $srSkipErrorsCount,
Putting it in the phpdoc, should be a nullable int but the `* 1`  part threw me off, looks like it could also be a string

2022-10-15 09:29 UTC, kamil-tekiela commented on libraries/classes/ReplicationGui.php
> +        $srSkipErrorsCount,
then maybe a cast to int is in order in the controller...

2022-10-15 10:31 UTC, kamil-tekiela commented on libraries/classes/Controllers/Server/ReplicationController.php
> +                isset($_POST['sr_skip_errors_count']) ? (int)$_POST['sr_skip_errors_count'] : null,
Even better, use `1` as default then we don't need nullable type nor the ternary inside that method. Much simpler :).

2022-10-15 10:33 UTC, kamil-tekiela commented
Please also fix the issues from coding standard check https://github.com/phpmyadmin/phpmyadmin/actions/runs/3255197954/jobs/5344264915 and after that I think the PR will be ready to merge. Thanks.

2022-10-15 10:51 UTC, williamdes approved these changes

2022-10-15 11:02 UTC, MrMadClown commented
Why does the DCO check fail? is the `Signed-off-by...` not correct?

2022-10-15 11:07 UTC, kamil-tekiela commented
The signoff should be in the commit body, not in the commit message. i.e. use two newlines to separate commit message from signoff.

2022-10-15 11:09 UTC, williamdes commented
> The signoff should be in the commit body, not in the commit message. i.e. use two newlines to separate commit message from signoff.

You can squash your commits and add the signoff :)

2022-10-15 11:16 UTC, kamil-tekiela commented
@williamdes  The DCO check still failed. Do you know why?

2022-10-15 11:17 UTC, MrMadClown commented
@kamil-tekiela my default git config is work related. The signed-off-by didn't match.

2022-10-15 11:22 UTC, kamil-tekiela approved these changes
Good job!

2022-10-15 12:12 UTC, williamdes commented
> @williamdes The DCO check still failed. Do you know why?

Sometimes it expects some email but honestly we do not care about the email, just have some working one. The important part is having a real name before the email

2022-10-16 11:58 UTC, MrMadClown commented
But now it's fine right?

2022-10-18 14:42 UTC, MrMadClown commented
What's needed to get this merged? @williamdes Anything I can do?

2022-10-19 11:02 UTC, williamdes commented
> What's needed to get this merged? @williamdes Anything I can do?

I asked for another review if it passes it should get merged right after

2022-10-20 04:50 UTC, MauricioFauth approved these changes

2022-10-20 04:52 UTC, merged

2022-10-20 04:52 UTC, MauricioFauth commented
Merged, thanks for your contribution!