Bugfix/issue 17793 insert UUID
phpmyadmin/phpmyadmin pull request #17797
Opened 2022-10-15 00:42 UTC by sureemo

### Description

- Add/Change table schema - Add UUID in default options
  <img width="198" alt="Screen Shot 2565-10-15 at 04 13 22" src="https://user-images.githubusercontent.com/1849256/195960935-aa7ac164-bffb-48a3-b49e-e146f6915b29.png">
- Insert/Edit - Generate uuid only when not defined value and not check null option

Reference issue: https://github.com/phpmyadmin/phpmyadmin/issues/17793

Signed-off-by: Mo Sureerat <sureemo@gmail.com>

2022-10-15 04:55 UTC, MauricioFauth requested changes

2022-10-15 04:55 UTC, MauricioFauth commented on libraries/classes/InsertEdit.php
> +            if (in_array($column['True_Type'], ['bit', 'uuid'])) {
```suggestion
            if (in_array($column['True_Type'], ['bit', 'uuid'], true)) {
```

2022-10-15 04:55 UTC, MauricioFauth commented on libraries/classes/Util.php
> +        return Compatibility::isUUIDSupported($dbi);
We're using `$GLOBALS` instead of `global` for new code.
```suggestion
        return Compatibility::isUUIDSupported($GLOBALS['dbi']);
```

2022-10-15 08:08 UTC, sureemo commented on libraries/classes/InsertEdit.php
> +            if (in_array($column['True_Type'], ['bit', 'uuid'])) {
updated. thank you. ^_^

2022-10-15 08:08 UTC, sureemo commented on libraries/classes/Util.php
> +        return Compatibility::isUUIDSupported($dbi);
updated. thank you. ^_^

2022-10-15 08:53 UTC, williamdes commented on libraries/classes/Html/Generator.php
> +            $defaultFunction = '';
```suggestion
            return '';
```

2022-10-15 08:54 UTC, williamdes commented on libraries/classes/Html/Generator.php
> +            $defaultFunction = '';
Or is there some logic we want to enter below?

2022-10-15 08:55 UTC, williamdes commented on libraries/classes/Util.php
> +    public static function isUUIDSupported()
```suggestion
    public static function isUUIDSupported(): bool
```
phpdoc return can be removed

2022-10-15 08:57 UTC, williamdes approved these changes
It looks good, I will ask for another review
Maybe there is different ways for some changes

2022-10-15 12:07 UTC, sureemo commented on libraries/classes/Html/Generator.php
> +            $defaultFunction = '';
updated. thank you ^_^

2022-10-15 12:07 UTC, sureemo commented on libraries/classes/Util.php
> +    public static function isUUIDSupported()
updated. thank you ^_^

2022-10-20 18:56 UTC, MauricioFauth approved these changes

2022-10-20 18:57 UTC, merged

2022-10-20 18:57 UTC, MauricioFauth commented
Merged, thanks for your contribution!

2022-10-26 12:05 UTC, williamdes commented on test/classes/InsertEditTest.php
> +        // case 10
this turned out to be very difficult to know what was actually tested while merging into master