Fix:17772 Wrong styles for add button from central columns on MariaDB
phpmyadmin/phpmyadmin pull request #17808
Opened 2022-10-18 05:30 UTC by Arpit-Gulgulia

Signed-off-by: Arpit Gulgulia <arpitgulgulia@gmail.com>

### Description:- Fixes #17772

Before submitting pull request, please review the following checklist:

- [ ] Make sure you have read our [CONTRIBUTING.md](https://github.com/phpmyadmin/phpmyadmin/blob/master/CONTRIBUTING.md) document.
- [ ] Make sure you are making a pull request against the correct branch. For example, for bug fixes in a released version use the corresponding QA branch and for new features use the _master_ branch. If you have a doubt, you can ask as a comment in the bug report or on the mailing list.
- [ ] Every commit has proper `Signed-off-by` line as described in our [DCO](https://github.com/phpmyadmin/phpmyadmin/blob/master/DCO). This ensures that the work you're submitting is your own creation.
- [ ] Every commit has a descriptive commit message.
- [ ] Every commit is needed on its own, if you have just minor fixes to previous commits, you can squash them.
- [ ] Any new functionality is covered by tests.

2022-10-18 07:56 UTC, williamdes reviewed
Thank you, I will have a look and let you know

2022-10-21 01:09 UTC, MauricioFauth requested changes

2022-10-21 01:09 UTC, MauricioFauth commented on themes/pmahomme/scss/_common.scss
> +}
```suggestion
```

2022-10-21 03:55 UTC, Arpit-Gulgulia commented on templates/database/central_columns/main.twig
> +<table class="table table-borderless table-sm w-auto d-inline-block navigation centralColBg">
Thanks for your suggestion @MauricioFauth. I thought to not remove anything from existing styling to avoid any side impacts. I checked by removing the navigation class, everything seems good except the background color which becomes white, Maybe this is acceptable.

 I'm making changes as per your suggestion.
Thanks

2022-10-21 08:42 UTC, williamdes approved these changes

2022-10-24 16:35 UTC, Arpit-Gulgulia commented
@MauricioFauth, is it okay now?

2022-10-26 09:20 UTC, MauricioFauth approved these changes

2022-10-26 12:26 UTC, merged