Fix:13773 Export page of Setting is not responsive
phpmyadmin/phpmyadmin pull request #17801
Opened 2022-10-15 20:24 UTC by Arpit-Gulgulia

Signed-off-by: Arpit-Gulgulia <arpitgulgulia@gmail.com>

### Description

Please describe your pull request: Fix for 13773 

Fixes #13773 

Before submitting pull request, please review the following checklist:

- [ ] Make sure you have read our [CONTRIBUTING.md](https://github.com/phpmyadmin/phpmyadmin/blob/master/CONTRIBUTING.md) document.
- [ ] Make sure you are making a pull request against the correct branch. For example, for bug fixes in a released version use the corresponding QA branch and for new features use the _master_ branch. If you have a doubt, you can ask as a comment in the bug report or on the mailing list.
- [ ] Every commit has proper `Signed-off-by` line as described in our [DCO](https://github.com/phpmyadmin/phpmyadmin/blob/master/DCO). This ensures that the work you're submitting is your own creation.
- [ ] Every commit has a descriptive commit message.
- [ ] Every commit is needed on its own, if you have just minor fixes to previous commits, you can squash them.
- [ ] Any new functionality is covered by tests.

2022-10-15 20:29 UTC, Arpit-Gulgulia commented
After changes, the page looks like the attached screenshot on a small screen and a large screen.
**Mobile view:**
![image](https://user-images.githubusercontent.com/48010798/196006275-0d2b1d31-b621-46c3-b856-d49b4d68064f.png)

**Desktop view:**
![image](https://user-images.githubusercontent.com/48010798/196006299-70b31630-2dcb-46db-b772-bc8c6400260c.png)

Hope this will helps the users.

@williamdes , please review the changes.
Thanks

2022-10-15 23:19 UTC, williamdes approved these changes
Nice one, it can probably go to QA
Will test it soon

2022-10-17 18:10 UTC, Arpit-Gulgulia commented
> Nice one, it can probably go to QA Will test it soon

Hey @williamdes, did you get some time to test this? Hope it passed🙂
Please also add a hacktober-accepted tag.
Thanks!

2022-10-21 00:52 UTC, MauricioFauth requested changes

2022-10-21 00:52 UTC, MauricioFauth commented on templates/config/form_display/display.twig
> +        <a class="nav-link{{ loop.first ? ' active' }} mx-0 px-3 rounded-0" id="{{ id }}-tab" href="#{{ id }}" data-bs-toggle="tab" role="tab" aria-controls="{{ id }}" aria-selected="{{ loop.first ?
That is not needed.
```suggestion
        <a class="nav-link{{ loop.first ? ' active' }}" id="{{ id }}-tab" href="#{{ id }}" data-bs-toggle="tab" role="tab" aria-controls="{{ id }}" aria-selected="{{ loop.first ? 'true' : 'false' }}">{{ name }}</a>
```

2022-10-24 16:34 UTC, Arpit-Gulgulia commented
@MauricioFauth , are we good the changes?

2022-10-29 12:13 UTC, MauricioFauth approved these changes

2022-10-29 12:13 UTC, merged