Use ServerRequest Object to access POST-vars
phpmyadmin/phpmyadmin pull request #17817
Opened 2022-10-20 06:05 UTC by OliverMensahDev

Signed-off-by: Oliver Mensah <olivermensah96@gmail.com>

### Description

Please describe your pull request.

Fixes #

Before submitting pull request, please review the following checklist:

- [x] Make sure you have read our [CONTRIBUTING.md](https://github.com/phpmyadmin/phpmyadmin/blob/master/CONTRIBUTING.md) document.
- [x] Make sure you are making a pull request against the correct branch. For example, for bug fixes in a released version use the corresponding QA branch and for new features use the _master_ branch. If you have a doubt, you can ask as a comment in the bug report or on the mailing list.
- [x] Every commit has proper `Signed-off-by` line as described in our [DCO](https://github.com/phpmyadmin/phpmyadmin/blob/master/DCO). This ensures that the work you're submitting is your own creation.
- [x] Every commit has a descriptive commit message.
- [x] Every commit is needed on its own, if you have just minor fixes to previous commits, you can squash them.
- [ ] Any new functionality is covered by tests.

2022-10-20 09:09 UTC, kamil-tekiela commented on libraries/classes/Controllers/View/CreateController.php
> +                if (! isset($ajaxdialog)) {
I don't think it's possible for this value to be unset anymore.

2022-10-20 09:11 UTC, kamil-tekiela commented on libraries/classes/Controllers/View/CreateController.php
> +        $GLOBALS['sql_query'] = ! empty($sqlquery) ? $sqlquery : '';
How about providing a default `''` to `getParsedBodyParam`? We don't need this ternary.

2022-10-20 09:11 UTC, kamil-tekiela commented on libraries/classes/Controllers/View/CreateController.php
> +        if (isset($view) && is_array($view)) {
Is it possible for `$view` to be unset?

2022-10-20 10:28 UTC, OliverMensahDev commented on libraries/classes/Controllers/View/CreateController.php
> +                if (! isset($ajaxdialog)) {
$ajaxdialog could be null so isset condition there still holds, I think

2022-10-20 10:40 UTC, kamil-tekiela commented on libraries/classes/Controllers/View/CreateController.php
> +                if (! isset($ajaxdialog)) {
I think it's better to check for `$ajaxdialog === null` because `isset` can hide typos and should be avoided

2022-10-20 16:07 UTC, OliverMensahDev commented
@kamil-tekiela are we good?

2022-10-20 19:51 UTC, kamil-tekiela requested changes
Very good PR, but there are still some things that need to be fixed before it can be merged. Thank you for your work.

2022-10-20 19:51 UTC, kamil-tekiela commented on libraries/classes/Controllers/View/CreateController.php
>          // View name is a compulsory field
Can you move this comment down to the `if` statement?

2022-10-20 19:51 UTC, kamil-tekiela commented on libraries/classes/Controllers/View/CreateController.php
> +        if (isset($view['name']) && empty($view['name'])) {
```suggestion
        if (empty($view['name'])) {
```
Redundant check can be removed while you are at it.

2022-10-20 19:51 UTC, kamil-tekiela commented on libraries/classes/Controllers/View/CreateController.php
> +        if (isset($createview) || isset($alterview)) {
```suggestion
        if ($createview !== null || $alterview !== null) {
```

2022-10-20 19:51 UTC, kamil-tekiela commented on libraries/classes/Controllers/View/CreateController.php
> +            if (isset($createView)) {
```suggestion
            if ($createView !== null) {
```

2022-10-20 19:51 UTC, kamil-tekiela commented on libraries/classes/Controllers/View/CreateController.php
> +            $ajaxdialog = $request->getParsedBodyParam('ajax_dialog');
I'd probably extract it out of the `if` statement. Keep it together with the rest.

2022-10-20 19:51 UTC, kamil-tekiela commented on libraries/classes/Controllers/View/CreateController.php
> +            if (! isset($ajaxdialog)) {
```suggestion
            if ($ajaxdialog !== null) {
```

2022-10-20 19:51 UTC, kamil-tekiela commented on libraries/classes/Controllers/View/CreateController.php
> +            'ajax_dialog' => isset($ajaxdialog),
Yeah... that's a bug now. This is **precisely** why `isset` is an awful thing. The variable is undefined in this place and `isset` hides it, not only during runtime but also using static analysis.

Please remove the `isset` in favor of `!== null` and fix the bug by declaring the variable unconditionally.

2022-10-21 09:12 UTC, kamil-tekiela approved these changes
LGTM

2022-10-27 12:27 UTC, OliverMensahDev commented
@joshk @kamil-tekiela  @frandieguez any feedback on this?

2022-10-29 12:58 UTC, MauricioFauth approved these changes

2022-10-29 12:58 UTC, merged