#17817 Use ServerRequest Object to access POST-vars
phpmyadmin/phpmyadmin pull request #17819
Opened 2022-10-20 17:11 UTC by MrMadClown

### Description

As described in #17817

2022-10-20 20:16 UTC, kamil-tekiela requested changes
Just few small fixes.

2022-10-20 20:16 UTC, kamil-tekiela commented on libraries/classes/Controllers/Table/TrackingController.php
> +            && ! ($reportExport === 'sqldumpfile')
```suggestion
            && $reportExport !== 'sqldumpfile'
```

2022-10-20 20:16 UTC, kamil-tekiela commented on libraries/classes/Controllers/Table/TrackingController.php
> +            && ! ($toggleActivation === 'deactivate_now')
```suggestion
            && $toggleActivation !== 'deactivate_now'
```

2022-10-20 20:16 UTC, kamil-tekiela commented on libraries/classes/Controllers/Table/TrackingController.php
> +            if (is_array($selectedVersions) && count($selectedVersions) !== 0) {
```suggestion
            if (is_array($selectedVersions) && $selectedVersions !== []) {
```

2022-10-20 20:16 UTC, kamil-tekiela commented on libraries/classes/Controllers/Table/TrackingController.php
> +                $request->getParsedBodyParam('version'),
Maybe create a new variable for this instead of getting the param many times?

2022-10-20 20:18 UTC, kamil-tekiela commented on libraries/classes/Controllers/Server/ReplicationController.php
> +                 $request->getParsedBodyParam('username'),
```suggestion
                $request->getParsedBodyParam('username'),
```

2022-10-20 20:19 UTC, kamil-tekiela commented on libraries/classes/Controllers/Server/ReplicationController.php
> +                 $request->getParsedBodyParam('hostname')
```suggestion
                $request->getParsedBodyParam('hostname')
```

2022-10-21 04:43 UTC, MrMadClown commented on libraries/classes/Controllers/Server/ReplicationController.php
> +            if (!isset($params['repl_clear_scr'])) {
This was probably me hitting auto-reformat in the IDE out of habit, same with the alignments above

2022-10-21 09:20 UTC, kamil-tekiela approved these changes
LGTM but please fix the remaining coding style issues https://github.com/phpmyadmin/phpmyadmin/actions/runs/3294855920/jobs/5432806072

2022-10-29 14:57 UTC, MauricioFauth approved these changes

2022-10-29 14:57 UTC, merged