Use ServerRequest Object instead superglobals - CollationController
phpmyadmin/phpmyadmin pull request #17818
Opened 2022-10-20 14:47 UTC by pistej

Signed-off-by: Jozef Pistej <pistej2@gmail.com>

### Description

Please describe your pull request.

Fixes #

Before submitting pull request, please review the following checklist:

- [x] Make sure you have read our [CONTRIBUTING.md](https://github.com/phpmyadmin/phpmyadmin/blob/master/CONTRIBUTING.md) document.
- [x] Make sure you are making a pull request against the correct branch. For example, for bug fixes in a released version use the corresponding QA branch and for new features use the _master_ branch. If you have a doubt, you can ask as a comment in the bug report or on the mailing list.
- [x] Every commit has proper `Signed-off-by` line as described in our [DCO](https://github.com/phpmyadmin/phpmyadmin/blob/master/DCO). This ensures that the work you're submitting is your own creation.
- [x] Every commit has a descriptive commit message.
- [x] Every commit is needed on its own, if you have just minor fixes to previous commits, you can squash them.
- [x] Any new functionality is covered by tests.

2022-10-21 01:26 UTC, MauricioFauth requested changes

2022-10-21 01:26 UTC, MauricioFauth commented on libraries/classes/Controllers/Database/Operations/CollationController.php
> +        if (empty($request->getParsedBodyParam('db_collation'))) {
You should assign the value to a variable instead of calling `getParsedBodyParam` every time.
```suggestion
        $dbCollation = $request->getParsedBodyParam('db_collation');
        if (! is_string($dbCollation) || $dbCollation === '') {
```

2022-10-21 01:26 UTC, MauricioFauth commented on libraries/classes/Controllers/Database/Operations/CollationController.php
> +            . ' DEFAULT' . Util::getCharsetQueryPart($request->getParsedBodyParam('db_collation', ''));
```suggestion
            . ' DEFAULT' . Util::getCharsetQueryPart($dbCollation);
```

2022-10-21 01:26 UTC, MauricioFauth commented on libraries/classes/Controllers/Database/Operations/CollationController.php
> +                    . Util::getCharsetQueryPart($request->getParsedBodyParam('db_collation', ''));
```suggestion
                    . Util::getCharsetQueryPart($dbCollation);
```

2022-10-21 01:26 UTC, MauricioFauth commented on libraries/classes/Controllers/Database/Operations/CollationController.php
> +                );
```suggestion
                $this->operations->changeAllColumnsCollation($GLOBALS['db'], $tableName, $dbCollation);
```

2022-10-23 10:07 UTC, pistej commented on libraries/classes/Controllers/Database/Operations/CollationController.php
> +        if (empty($request->getParsedBodyParam('db_collation'))) {
missed that, updated, thx

2022-10-29 13:26 UTC, MauricioFauth approved these changes

2022-10-29 13:26 UTC, merged