Replaced superglobal in LintController
phpmyadmin/phpmyadmin pull request #17828
Opened 2022-10-23 15:55 UTC by Maria-Papa

Signed-off-by: Maria Papadopoulou <1maria.papa@gmail.com>

### Description

Please describe your pull request: This is a partial fix of the issue #17769.

Fixes #

Before submitting pull request, please review the following checklist:

- [X] Make sure you have read our [CONTRIBUTING.md](https://github.com/phpmyadmin/phpmyadmin/blob/master/CONTRIBUTING.md) document.
- [X] Make sure you are making a pull request against the correct branch. For example, for bug fixes in a released version use the corresponding QA branch and for new features use the _master_ branch. If you have a doubt, you can ask as a comment in the bug report or on the mailing list.
- [X] Every commit has proper `Signed-off-by` line as described in our [DCO](https://github.com/phpmyadmin/phpmyadmin/blob/master/DCO). This ensures that the work you're submitting is your own creation.
- [X] Every commit has a descriptive commit message.
- [X] Every commit is needed on its own, if you have just minor fixes to previous commits, you can squash them.
- [X] Any new functionality is covered by tests.

2022-10-23 17:33 UTC, williamdes approved these changes

2022-10-25 09:12 UTC, williamdes commented on libraries/classes/Controllers/Database/SqlController.php
> +            isset($delimiter)
```suggestion
            $delimiter !== null
```
it is always isset ;)

2022-10-25 09:12 UTC, williamdes commented on libraries/classes/Controllers/UserPasswordController.php
> +        if (isset($noPass])) {
same, it is always isset + typo fix
```suggestion
        if ($noPass !== null) {
```

2022-10-25 13:32 UTC, kamil-tekiela requested changes

2022-10-25 13:32 UTC, kamil-tekiela commented on libraries/classes/Controllers/Database/SearchController.php
> +        if (isset($request->getParsedBodyParam('submit_search'))) {
```suggestion
        if ($request->getParsedBodyParam('submit_search') !== null) {
```
It's definitely set. Maybe check for `!== null`?

2022-10-28 19:06 UTC, kamil-tekiela approved these changes
LGTM

2022-10-29 13:45 UTC, williamdes approved these changes

2022-10-29 17:22 UTC, MauricioFauth approved these changes

2022-10-29 17:22 UTC, merged