Abstract & CheckRelations Controllers - Refactored
phpmyadmin/phpmyadmin pull request #17829
Opened 2022-10-23 18:29 UTC by Maria-Papa

Signed-off-by: Maria Papadopoulou <1maria.papa@gmail.com>

### Description

Please describe your pull request: This is a partial fix of the issue #17727.
Controllers `AbstractController` & `CheckRelationsController` were refactored.

Fixes #

Before submitting pull request, please review the following checklist:

- [X] Make sure you have read our [CONTRIBUTING.md](https://github.com/phpmyadmin/phpmyadmin/blob/master/CONTRIBUTING.md) document.
- [X] Make sure you are making a pull request against the correct branch. For example, for bug fixes in a released version use the corresponding QA branch and for new features use the _master_ branch. If you have a doubt, you can ask as a comment in the bug report or on the mailing list.
- [X] Every commit has proper `Signed-off-by` line as described in our [DCO](https://github.com/phpmyadmin/phpmyadmin/blob/master/DCO). This ensures that the work you're submitting is your own creation.
- [X] Every commit has a descriptive commit message.
- [X] Every commit is needed on its own, if you have just minor fixes to previous commits, you can squash them.
- [X] Any new functionality is covered by tests.

2022-10-23 21:20 UTC, williamdes approved these changes

2022-10-25 13:27 UTC, kamil-tekiela commented on libraries/classes/Controllers/AbstractController.php
> +            $GLOBALS['is_db'] = $GLOBALS['dbi']->selectDb($db->getName());
That's not right. The `DatabaseName` value object ensures that the database name is not an empty string. It will throw `InvalidDatabaseName` if it's empty. If there's a requirement to handle this then you either should check that it's not empty string before creating the value object or catch the exception and recover from it. 

P.S. This whole method should be refactored as it currently both has side-effects and returns value.

2022-10-25 17:45 UTC, williamdes requested changes
Thank you @kamil-tekiela for the reviews, I missed the strlen part

2022-10-28 19:04 UTC, kamil-tekiela commented on libraries/classes/Controllers/AbstractController.php
> +        if (!empty($dbName)) {
I'm sorry but that's worse than what it was before. You need to either check if the `$GLOBALS['db']` is not en empty string before calling `DatabaseName::tryFromValue` or use try-catch.

2022-10-29 19:56 UTC, merged