Introducing quoteString()
phpmyadmin/phpmyadmin pull request #17866
Opened 2022-11-03 22:29 UTC by kamil-tekiela

I have started reviewing the usages of `DatabaseInterface::escapeString()` method. I found out that it's usually used correctly. However, it leads to somewhat messy code and several instances are undiscovered bugs. It seems to me that phpMyAdmin has followed the outdated `mysql_*` API technique and it got a little out of hand. 

I am not saying that **proper** string escaping is wrong. I think when it comes to a tool like phpMyAdmin, it makes a lot of sense that we should be able to build SQL queries with string literals properly formatted. Of course, when the SQL doesn't need to be presented to a user in a final form, we can use prepared statements with parameter binding. But I looked into it last year and this project is not yet ready for this. (for the curious: the biggest challenge would be to solve the issue of int/float types with PS). What's more important is that phpMyAdmin doesn't need to switch to prepared statements any time soon. What we have works, but we must ensure that we do it properly. String escaping is flawed because it's very easy to get wrong and break the resulting SQL. The important points are:
- Only string literals need to be escaped
- String literals must be enclosed with single quotes `'` and never double quotes `"` (see `NO_BACKSLASH_ESCAPES` mode)
- Not every SQL statement uses the same escaping. Some require double escaping. See [How should I escape characters inside this LIKE query?](https://stackoverflow.com/a/24590043/1839439). This makes escaping very context-dependent. 
- Escaping needs to be done by the client API that will execute the query. This is something that we can't control when it comes to generated SQL queries though. But phpMyAdmin uses two mysqli connections internally, so ideally the escaping should be done by the connection that will execute the SQL query. 
- Escaping should be done only when putting the string into SQL. It cannot be done earlier as this can lead to accidental reuse of the escaped variable in another context e.g. HTML output. 

There might be even more considerations I can't think of right now. But to the point now. PDO got things right. To avoid SQL injection due to `NO_BACKSLASH_ESCAPES` it doesn't expose any method for string escaping, but it does provide the [`PDO::quote()`](https://www.php.net/manual/en/pdo.quote.php) method. This solves points number 1 and 2 above. 

I propose to add a new method called `DatabaseInterface::quoteString()` that will do what PDO does. It will escape the string and put it in single quotes. I would also like to remove `DatabaseInterface::escapeString()` to prevent accidental usages, but it seems to me that this isn't so straightforward, for example, bookmarks use it to interpolate user input into bookmarked queries. This method is used ~750 times and sometimes it's not used correctly, which will make the review a rather long process. I would like to ask you what you think about this proposal and what do you see as the best way forward. 

This PR contains a demo code of what I am proposing.

@MauricioFauth @williamdes

2022-11-05 10:29 UTC, williamdes commented
Hello,

This took me two times to really understand this request, from what I understand I am okay with the proposal. 
I am okay with moving the escaping at the last moment as it will ensure things get right and will be ready for some conversions to prepared statements. 

It's confusing that it needs to be different for `LIKE`.

So I can say it looks right to fix the escaping 
Maybe this can get merged with some tests for the news methods. And following PRs can change the queries to the new way 

> But phpMyAdmin uses two mysqli connections internally, so ideally the escaping should be done by the connection that will execute the SQL query.

The second one is for phpMyAdmin configuration storage. It should be only one open if it is not configured.

2022-11-05 16:23 UTC, MauricioFauth approved these changes
I really like this method.
What about marking `escapeString` as `@deprecated` to avoid adding new usages of it, and opening an issue like "`escapeString` should be replaced with `quoteString`" and adding the "help wanted" tag.

2022-11-05 16:23 UTC, MauricioFauth commented on libraries/classes/DatabaseInterface.php
> +     * returns properly quoted string for use in MySQL queries
```suggestion
     * Returns properly quoted string for use in MySQL queries.
```

2022-11-05 16:23 UTC, MauricioFauth commented on libraries/classes/DatabaseInterface.php
> +     * @return string a MySQL quoted string
```suggestion
     * @psalm-return non-empty-string
```

2022-11-06 00:46 UTC, kamil-tekiela commented
I made it deprecated. Once this PR is merged an issue can be created. I decided to leave `LIKE` out of it for the moment because I want to do it in another PR.

2022-11-06 09:18 UTC, williamdes commented on libraries/classes/Dbal/DbalInterface.php
> +     * @psalm-return non-empty-string
```suggestion
     * @psalm-return non-empty-string
     * @psalm-taint-escape sql
```
I think it may work 
https://psalm.dev/docs/security_analysis/avoiding_false_positives/

2022-11-06 16:47 UTC, MauricioFauth requested changes

2022-11-06 16:47 UTC, MauricioFauth commented on libraries/classes/DatabaseInterface.php
> +     * @deprecated Use quoteString() instead.
```suggestion
     * @deprecated Use {@see quoteString()} instead.
```

2022-11-06 16:47 UTC, MauricioFauth commented on libraries/classes/Dbal/DbalInterface.php
> +     * @deprecated Use quoteString() instead.
```suggestion
     * @deprecated Use {@see quoteString()} instead.
```

2022-11-06 19:53 UTC, MauricioFauth approved these changes

2022-11-06 19:53 UTC, merged