Refactor BinlogController.php
phpmyadmin/phpmyadmin pull request #17873
Opened 2022-11-06 22:08 UTC by kamil-tekiela

I could not find `is_full_query` anywhere in the code so I have no idea what values we are actually expecting.

2022-11-06 22:36 UTC, williamdes commented
> I could not find `is_full_query` anywhere in the code so I have no idea what values we are actually expecting.

I think I will have to search in the history
It's probably an old parameter or a bug
https://github.com/phpmyadmin/phpmyadmin/search?q=is_full_query&type=code

2022-11-08 03:04 UTC, MauricioFauth requested changes

2022-11-08 03:04 UTC, MauricioFauth commented on libraries/classes/Controllers/Server/BinlogController.php
> +        if (! empty($request->getParsedBodyParam('is_full_query'))) {
```suggestion
        if ($request->getParsedBodyParam('is_full_query')) {
```

The `is_full_query` parameter is a flag and always has the value '`1`' when present. So, `if ($request->hasBodyParam('is_full_query')) {` will also work here.

You can see it been set here:
https://github.com/phpmyadmin/phpmyadmin/blob/97aac39a40cef8f0ec63f380be79e14c4633bd67/libraries/classes/Controllers/Server/BinlogController.php#L67-L71

And been unset here:
https://github.com/phpmyadmin/phpmyadmin/blob/97aac39a40cef8f0ec63f380be79e14c4633bd67/libraries/classes/Controllers/Server/BinlogController.php#L88-L91

2022-11-09 01:18 UTC, MauricioFauth approved these changes

2022-11-09 01:18 UTC, merged