Ref #17769 - ServerRequest Object instead superglobals - UserPasswordController
phpmyadmin/phpmyadmin pull request #17903
Opened 2022-11-18 00:16 UTC by ru-asdx

Signed-off-by: Evgeny Skorlov <eugene@skorlov.name>

### Description

Ref https://github.com/phpmyadmin/phpmyadmin/issues/17769

Before submitting pull request, please review the following checklist:

- [ ] Make sure you have read our [CONTRIBUTING.md](https://github.com/phpmyadmin/phpmyadmin/blob/master/CONTRIBUTING.md) document.
- [ ] Make sure you are making a pull request against the correct branch. For example, for bug fixes in a released version use the corresponding QA branch and for new features use the _master_ branch. If you have a doubt, you can ask as a comment in the bug report or on the mailing list.
- [ ] Every commit has proper `Signed-off-by` line as described in our [DCO](https://github.com/phpmyadmin/phpmyadmin/blob/master/DCO). This ensures that the work you're submitting is your own creation.
- [ ] Every commit has a descriptive commit message.
- [ ] Every commit is needed on its own, if you have just minor fixes to previous commits, you can squash them.
- [ ] Any new functionality is covered by tests.

2022-11-19 09:06 UTC, williamdes approved these changes

2022-11-20 23:57 UTC, kamil-tekiela requested changes

2022-11-20 23:57 UTC, kamil-tekiela commented on libraries/classes/Controllers/Normalization/FirstNormalForm/FirstStepController.php
> +        if (isset($normalizeTo) && in_array($normalizeTo, ['1nf', '2nf', '3nf'])) {
`$normalizeTo` is definitely set here, but it may be null. Please replace with `$normalizeTo !== null` or `is_array($normalizeTo)`

2022-11-21 09:12 UTC, williamdes approved these changes

2022-11-23 20:12 UTC, MauricioFauth approved these changes

2022-11-23 20:14 UTC, merged