Ref #17769 - Replace superglobals with ServerRequest in NavigationController
phpmyadmin/phpmyadmin pull request #17916
Opened 2022-11-22 03:30 UTC by ru-asdx

Signed-off-by: Evgeny Skorlov <eugene@skorlov.name>

### Description

Ref https://github.com/phpmyadmin/phpmyadmin/issues/17769

Replace superglobals with ServerRequest in NavigationController

2022-11-23 16:58 UTC, kamil-tekiela requested changes

2022-11-23 16:58 UTC, kamil-tekiela commented on libraries/classes/Controllers/NavigationController.php
> +        if ($request->getParsedBodyParam('reload') !== null) {
```suggestion
        if ($request->hasBodyParam('reload')) {
```

2022-11-23 16:58 UTC, kamil-tekiela commented on libraries/classes/Controllers/NavigationController.php
> +            if ($request->getParsedBodyParam('unhideNavItem') !== null) {
```suggestion
            if ($request->hasBodyParam('unhideNavItem')) {
```

2022-11-23 16:58 UTC, kamil-tekiela commented on libraries/classes/Controllers/NavigationController.php
> +            if ($request->getParsedBodyParam('showUnhideDialog') !== null) {
```suggestion
            if ($request->hasBodyParam('showUnhideDialog')) {
```

2022-11-25 19:44 UTC, williamdes approved these changes

2022-11-30 17:34 UTC, MauricioFauth approved these changes

2022-11-30 17:34 UTC, merged