Change text direction on selects for RTL
phpmyadmin/phpmyadmin pull request #17926
Opened 2022-11-26 00:26 UTC by liviuconcioiu

Signed-off-by: Liviu-Mihail Concioiu <liviu.concioiu@gmail.com>

### Description

This PR fixes text direction on selects for RTL languages.

Before:

![before](https://user-images.githubusercontent.com/25424343/204065422-6574d216-67ba-44d3-a08e-5d3d856fa89d.png)

After:

![after](https://user-images.githubusercontent.com/25424343/204065424-cf83bf6d-f899-419d-8e5c-2f65160da613.png)

Before submitting pull request, please review the following checklist:

- [x] Make sure you have read our [CONTRIBUTING.md](https://github.com/phpmyadmin/phpmyadmin/blob/master/CONTRIBUTING.md) document.
- [x] Make sure you are making a pull request against the correct branch. For example, for bug fixes in a released version use the corresponding QA branch and for new features use the _master_ branch. If you have a doubt, you can ask as a comment in the bug report or on the mailing list.
- [x] Every commit has proper `Signed-off-by` line as described in our [DCO](https://github.com/phpmyadmin/phpmyadmin/blob/master/DCO). This ensures that the work you're submitting is your own creation.
- [x] Every commit has a descriptive commit message.
- [x] Every commit is needed on its own, if you have just minor fixes to previous commits, you can squash them.
- [x] Any new functionality is covered by tests.

2022-11-26 00:32 UTC, williamdes approved these changes

2022-11-26 00:41 UTC, williamdes commented on templates/login/form.twig
> +          <select name="lang" class="form-select autosubmit" lang="{{ lang }}" dir="{{ text_dir }}" id="languageSelect" aria-labelledby="languageSelectLabel">
I am not sure for this one, I think the language list is english only. Not sure there is a text direction

2022-11-26 14:10 UTC, williamdes approved these changes
The diff looks good, is there more commits to be pushed ?

2022-11-26 14:51 UTC, liviuconcioiu commented
> The diff looks good, is there more commits to be pushed ?

No.

2022-11-28 16:35 UTC, iifawzi commented on libraries/classes/Language.php
> +        return in_array($this->code, ['ar', 'ar_LY', 'fa', 'he', 'ur']);
Do we really need to have a specific country locale here? `_LY`?
Isn't `ar` the code already? if it's not, I think it would be better to substr only the language `ar`, `en`.. from the code strings, otherwise, we will need to have a list of all the countries' dialects for all the languages  ( `ly`, `eg`, `sa`, .... ) in this array

2022-11-28 18:54 UTC, liviuconcioiu commented on libraries/classes/Language.php
> +        return in_array($this->code, ['ar', 'ar_LY', 'fa', 'he', 'ur']);
> Do we really need to have a specific country locale here? `_LY`? Isn't `ar` the code already? if it's not, I think it would be better to substr only the language `ar`, `en`.. from the code strings, otherwise, we will need to have a list of all the countries' dialects for all the languages ( `ly`, `eg`, `sa`, .... ) in this array

`ar_LY` is present only on the demo server [https://demo.phpmyadmin.net/QA_5_2/index.php?route=/](https://demo.phpmyadmin.net/QA_5_2/index.php?route=/) and not other dialects.

I'll use substr.

2022-11-28 19:01 UTC, iifawzi commented on libraries/classes/Language.php
> +        return in_array($this->code, ['ar', 'ar_LY', 'fa', 'he', 'ur']);
> ar_LY is present only on the demo server https://demo.phpmyadmin.net/QA_5_2/index.php?route=/ and not other dialects.

Ahh, ok, I thought that the locale code is being detected from the browser, not from a pre-defined list. 
I think it's fine having it in the array then, what do you think?

2022-11-28 19:04 UTC, liviuconcioiu commented on libraries/classes/Language.php
> +        return in_array($this->code, ['ar', 'ar_LY', 'fa', 'he', 'ur']);
> Ahh, ok, I thought that the locale code is being detected from the browser, not from a pre-defined list. I think it's fine having it in the array then, what do you think?

By looking at [https://hosted.weblate.org/projects/phpmyadmin/#languages](https://hosted.weblate.org/projects/phpmyadmin/#languages) only ar_LY is missing from RTL languages. There are no other translation, so it will be useless to use substr since it will slower the speed. I think the best way is to leave it in array, since no other translation are there. Either way, `ar_LY` is not shipped in the downloaded version (is only on demo).

2022-11-30 14:32 UTC, MauricioFauth requested changes
I think this change is semantically wrong. The options in these selects are in English and read left to right.
This is [an issue with Bootstrap](https://github.com/twbs/bootstrap/issues/37567) and should be fixed using CSS.

2022-11-30 16:37 UTC, MauricioFauth commented on templates/columns_definitions/column_attributes.twig
> +  <select lang="{{ lang }}" dir="{{ text_dir }}" name="field_collation[{{ column_number }}]" id="field_{{ column_number }}_{{ ci - ci_offset }}">
This is redundant, as the `<html>` tag already sets the `lang` and `dir` attributes with the same values.

https://github.com/phpmyadmin/phpmyadmin/blob/44a0844f4083f09f78330b9e0e3568d43ba859ca/templates/header.twig#L2

2022-11-30 16:38 UTC, closed without merging