Ref #17769 - Replace superglobals with ServerRequest in Import & Export Controllers
phpmyadmin/phpmyadmin pull request #17949
Opened 2022-12-05 04:00 UTC by ru-asdx

Signed-off-by: Evgeny Skorlov <eugene@skorlov.name>

### Description

Ref https://github.com/phpmyadmin/phpmyadmin/issues/17769

Fixes #

Replace superglobals with ServerRequest in Import & Export Controllers

2022-12-05 21:49 UTC, kamil-tekiela requested changes

2022-12-05 21:49 UTC, kamil-tekiela commented on libraries/classes/Controllers/Export/TablesController.php
> +        if ($request->getParsedBodyParam('selected_tbl') === null) {
Can it not be an empty string too? If not then using `hasBodyParam` would be more suitable.

2022-12-05 21:49 UTC, kamil-tekiela commented on libraries/classes/Controllers/Import/ImportController.php
> +            if ($request->hasBodyParam('parameterized') && $parameters !== null && is_array($parameters)) {
This is redundant. Either it's an array or null. It cannot be both.

2022-12-05 21:49 UTC, kamil-tekiela commented on libraries/classes/Controllers/Import/ImportController.php
> +            if ($request->getParsedBodyParam('rollback_query') !== null) {
```suggestion
            if ($request->hasBodyParam('rollback_query')) {
```

2022-12-05 21:49 UTC, kamil-tekiela commented on libraries/classes/Controllers/Import/ImportController.php
> +        if (is_array($postParams) && $postParams == [] && is_array($getParams) && $getParams == []) {
```suggestion
        if ($postParams === [] && $getParams === []) {
```

2022-12-05 21:49 UTC, kamil-tekiela commented on libraries/classes/Controllers/Import/ImportController.php
> +        if (! empty($id_bookmark)) {
Can you make this check more specific, please? Maybe move the cast above the if and then check against 0?

2022-12-05 21:49 UTC, kamil-tekiela commented on libraries/classes/Controllers/Import/ImportController.php
> +                        $request->getParsedBodyParam('action_bookmark_all') !== null
```suggestion
                        $request->hasBodyParam('action_bookmark_all')
```

2022-12-05 21:49 UTC, kamil-tekiela commented on libraries/classes/Controllers/Import/ImportController.php
> +                    if (! empty($bookmark_variable)) {
Please make this more specific too.

2022-12-05 21:49 UTC, kamil-tekiela commented on libraries/classes/Controllers/Import/ImportController.php
> +        if (! $GLOBALS['error'] && $request->getParsedBodyParam('skip') !== null) {
```suggestion
        if (! $GLOBALS['error'] && $request->hasBodyParam('skip')) {
```

2022-12-05 21:49 UTC, kamil-tekiela commented on libraries/classes/Controllers/Import/ImportController.php
> +        if (! empty($id_bookmark) && $action_bookmark == 2) {
I don't think `$action_bookmark` is defined in this scope.

2022-12-05 21:49 UTC, kamil-tekiela commented on libraries/classes/Controllers/Import/ImportController.php
> +        } elseif (! empty($id_bookmark) && $action_bookmark == 1) {
What type is `$id_bookmark`? Please make the check more specific.

2022-12-05 21:49 UTC, kamil-tekiela commented on libraries/classes/Controllers/Import/ImportController.php
> +                    $request->getParsedBodyParam('bkm_replace') !== null
```suggestion
                    $request->hasBodyParam('bkm_replace') 
```

2022-12-05 21:49 UTC, kamil-tekiela commented on libraries/classes/Controllers/Import/ImportController.php
> +                    $request->getParsedBodyParam('bkm_replace') !== null
```suggestion
                    $request->hasBodyParam('bkm_replace')
```

2022-12-05 21:49 UTC, kamil-tekiela commented on libraries/classes/Controllers/Import/ImportController.php
> +        if ($request->getParsedBodyParam('rollback_query') === null) {
```suggestion
        if (! $request->getParsedBodyParam('rollback_query')) {
```

2022-12-05 21:49 UTC, kamil-tekiela commented on libraries/classes/Controllers/Import/StatusController.php
> +        if ($request->getQueryParam('message') !== null) {
Are you sure it cannot be anything else then null? Why not use `hasQueryParam` instead?

2022-12-14 15:04 UTC, MauricioFauth approved these changes

2022-12-14 15:04 UTC, merged