Remove dead code in Navigation
phpmyadmin/phpmyadmin pull request #17969
Opened 2022-12-16 22:28 UTC by kamil-tekiela

Here's the commit that introduced this method https://github.com/phpmyadmin/phpmyadmin/commit/dfe8dc283a5caa631ae1a21380e188bf5b4489de
Since then, the images have been deleted (or renamed) and all other usages of this method are gone too. 

It's worth mentioning that these buttons (or links actually) do not show up on the UI without an image. There is JS code for them, but I have no idea what it does. The "collapse all" button might have been useful. Perhaps the buttons should get fixed again? @williamdes Any idea?

2022-12-17 05:19 UTC, williamdes commented
It's fixed now by 90f9e708cc6faca16a27b0d87f49e70231b3766c
Right ?

2022-12-17 08:06 UTC, liviuconcioiu commented
@williamdes Collapse all is fixed.

![collapse](https://user-images.githubusercontent.com/25424343/208232278-54713977-56ef-4cf6-a183-ca817c81ecc5.png)

2022-12-24 16:14 UTC, MauricioFauth requested changes

2022-12-24 16:14 UTC, MauricioFauth commented on libraries/classes/Navigation/NavigationTree.php
> -            's_collapseall',
This missing icon was fixed by 90f9e708cc6faca16a27b0d87f49e70231b3766c.

2023-01-07 22:53 UTC, kamil-tekiela commented on libraries/classes/Navigation/NavigationTree.php
> -            's_collapseall',
Sorry, but I got lost a little bit. Do you want me to add `ic_s_collapseall` to this button? What about the other button?
Even if I add the new class to this button it still won't show up. It has no content therefore it has no dimensions and no background. I'm not sure how these buttons were designed, can you suggest how to proceed here?

2023-01-27 14:21 UTC, MauricioFauth commented on libraries/classes/Navigation/NavigationTree.php
> -            's_collapseall',
This button wasn't working, but it's now fixed. When you click on a database, it expands the tree. You can use this button to collapse all items.

![collapse](https://user-images.githubusercontent.com/25424343/208232278-54713977-56ef-4cf6-a183-ca817c81ecc5.png)

2023-01-27 16:14 UTC, kamil-tekiela commented on libraries/classes/Navigation/NavigationTree.php
> -            's_collapseall',
Ahh ok. I got confused there. I reverted some of my changes.

2023-02-10 19:06 UTC, MauricioFauth approved these changes

2023-02-10 19:07 UTC, merged