Replace superglobals with serverrequest in PrivilegesController
phpmyadmin/phpmyadmin pull request #17977
Opened 2022-12-19 02:24 UTC by ru-asdx

Signed-off-by: Evgeny Skorlov <eugene@skorlov.name>

### Description

Ref https://github.com/phpmyadmin/phpmyadmin/issues/17769

Replace superglobals with ServerRequest in Server/PrivilegesController

2022-12-19 14:03 UTC, kamil-tekiela requested changes

2022-12-19 14:03 UTC, kamil-tekiela commented on libraries/classes/Controllers/Server/PrivilegesController.php
> +            && (! $request->hasBodyParam('submit_mult') || $request->getParsedBodyParam('submit_mult') !== 'export')
```suggestion
            && $request->getParsedBodyParam('submit_mult') !== 'export'
```
Redundant. null !== 'export'

2022-12-19 14:03 UTC, kamil-tekiela commented on libraries/classes/Controllers/Server/PrivilegesController.php
> +        if ($request->getParsedBodyParam('submit_mult') === 'export') {
What happened to `isset($_GET['export'])`?

2023-01-11 00:15 UTC, MauricioFauth approved these changes

2023-01-11 00:15 UTC, merged