Move getColumnMapFromSql() to SystemDatabase
phpmyadmin/phpmyadmin pull request #18047
Opened 2023-01-29 00:04 UTC by kamil-tekiela

2023-01-30 09:19 UTC, williamdes commented on libraries/classes/SystemColumn.php
> +class SystemColumn
It could have psalm sealed or readonly phpdoc tags that other classes have?

2023-01-30 09:19 UTC, williamdes approved these changes

2023-01-30 11:03 UTC, kamil-tekiela commented on libraries/classes/SystemColumn.php
> +class SystemColumn
Good idea. I added `@psalm-immutable`

2023-02-15 12:22 UTC, MauricioFauth approved these changes

2023-02-15 12:25 UTC, MauricioFauth requested changes

2023-02-15 12:25 UTC, MauricioFauth commented on libraries/classes/SystemColumn.php
> +    public $tableName;
```suggestion
    public readonly string $tableName;
```

2023-02-15 12:44 UTC, kamil-tekiela commented on libraries/classes/SystemColumn.php
> +    public $tableName;
Yeah, this is completely unnecessary now 😄

2023-02-15 13:54 UTC, MauricioFauth approved these changes

2023-02-15 13:54 UTC, merged