Added CF Turnstile example phpmyadmin
phpmyadmin/phpmyadmin pull request #18098
Opened 2023-02-15 09:47 UTC by SlushUwU

Added reCaptcha example for Cloudflare Turnstile config example

Cloudflare Developer Page for Turnstile: https://developers.cloudflare.com/turnstile/get-started/
Signed-off-by: SlushUwU <rology@satowa-network.eu>

2023-02-15 12:41 UTC, williamdes approved these changes
Awesome, thank you !
I will test it

2023-02-15 14:21 UTC, ibennetch approved these changes

2023-02-15 20:03 UTC, MauricioFauth requested changes

2023-02-15 20:03 UTC, MauricioFauth commented on doc/config.rst
> +++++++++++++++++++++++++
See: https://github.com/phpmyadmin/phpmyadmin/actions/runs/4182909630/jobs/7248968688#step:5:44
```
Warning, treated as error:
/home/runner/work/phpmyadmin/phpmyadmin/doc/config.rst:3969:Title underline too short.

reCaptcha using Turnstile
++++++++++++++++++++++++
make: *** [Makefile:73: html] Error 2
make: Leaving directory '/home/runner/work/phpmyadmin/phpmyadmin/doc'
```

```suggestion
reCaptcha using Turnstile
+++++++++++++++++++++++++
```

2023-02-20 13:04 UTC, Miriam001 approved these changes

2023-02-22 11:05 UTC, williamdes commented on doc/config.rst
> +    $cfg['CaptchaCsp'] = 'https://challenges.cloudflare.com/turnstile/v0/siteverify https://challenges.cloudflare.com/turnstile/v0/api.js https://static.cloudflareinsights.com/beacon.min.js/vaafb692b
```suggestion
    $cfg['CaptchaCsp'] = 'https://challenges.cloudflare.com/turnstile/v0/siteverify https://challenges.cloudflare.com/turnstile/v0/api.js https://static.cloudflareinsights.com/beacon.min.js/vaafb692b2aea4879b33c060';
```
This is a typo

2023-02-22 11:11 UTC, williamdes requested changes
This config throws 
```
Refused to frame 'https://challenges.cloudflare.com/' because it violates the following Content Security Policy directive: "default-src 'self' https://challenges.cloudflare.com/turnstile/v0/siteverify https://challenges.cloudflare.com/turnstile/v0/api.js https://static.cloudflareinsights.com/beacon.min.js/vaafb692b2aea4879b33c060". Note that 'frame-src' was not explicitly set, so 'default-src' is used as a fallback.
```
On my chrome

But with
```php
$cfg['CaptchaCsp'] = 'https://challenges.cloudflare.com https://static.cloudflareinsights.com';
```

It works

2023-02-22 11:33 UTC, SlushUwU commented
> 4161fff

Should be fixed in [4161fff](https://github.com/phpmyadmin/phpmyadmin/pull/18098/commits/4161ffff5d8ba4abfee2ecd0018718fa50403da3)

2023-02-22 12:00 UTC, williamdes commented on doc/config.rst
> +    $cfg['CaptchaCsp'] = 'https://challenges.cloudflare.com/turnstile/v0/siteverify https://challenges.cloudflare.com/turnstile/v0/api.js https://static.cloudflareinsights.com/beacon.min.js/vaafb692b
```suggestion
    $cfg['CaptchaCsp'] = 'https://challenges.cloudflare.com https://static.cloudflareinsights.com';
```

This is what I deployed on https://phpmyadmin-stable-snapshot.public-instance.eu/
I think it's best not to use things that can change like `vaafb692b2aea4879b33c060e79fe94621666317369993`
And `https://challenges.cloudflare.com/turnstile/v0/api.js` does not work since it's redirected
I doubt `https://challenges.cloudflare.com/turnstile/v0/siteverify ` is useful since it's called in the back-end, right ?

2023-02-22 12:11 UTC, williamdes commented on doc/config.rst
> +.. seealso:: `Turnstile Developer Guide <https://developers.cloudflare.com/turnstile/get-started/server-side-validation/>`
```suggestion
.. seealso:: `Turnstile Developer Guide <https://developers.cloudflare.com/turnstile/get-started/>` 
```

2023-02-22 12:12 UTC, williamdes approved these changes
Thank you for your contribution @SlushUwU !

2023-02-22 12:14 UTC, merged