Always use svg display in gis editor
phpmyadmin/phpmyadmin pull request #18182
Opened 2023-03-01 00:50 UTC by MoonE

Editing geometries with SRID should display with OpenLayers visualization. As that doesn't work this now always uses the svg viewer.

Fixing the OpenLayers visualization here would be rather complicated.

Will provide a complete fix for master branch shortly ...

2023-03-01 19:45 UTC, williamdes approved these changes
This is an acceptable workaround but feels weird
Is there no way it could be fixed in a proper way, is it too broken?

2023-03-05 16:46 UTC, MoonE commented
I'll have a look.

2023-04-05 14:27 UTC, MauricioFauth requested changes

2023-04-05 14:27 UTC, MauricioFauth commented on templates/gis_data_editor_form.twig
> +        <div id="placeholder"{{ srid != 0 and false ? ' class="hide"' }}>
```suggestion
        <div id="placeholder">
```

2023-04-05 14:27 UTC, MauricioFauth commented on templates/gis_data_editor_form.twig
> +            <input type="checkbox" id="choice" value="useBaseLayer"{{ srid != 0 and false ? ' checked="checked"' }}>
```suggestion
            <input type="checkbox" id="choice" value="useBaseLayer">
```

2023-08-26 18:59 UTC, MauricioFauth approved these changes

2023-08-26 19:00 UTC, merged