Refactor GisVisualization settings
phpmyadmin/phpmyadmin pull request #18218
Opened 2023-03-05 15:52 UTC by MoonE

This is a refactoring to  get better type safety in GisVisualization and GisVisualizationController
This gets rid of the `settings` and `userSpecifiedSettings` properties and instead stores the concrete values in class properties.

2023-03-06 22:49 UTC, kamil-tekiela approved these changes
Awesome work. Thank you. I was going to fix these params, but now I don't have to.

2023-03-06 22:49 UTC, kamil-tekiela commented on libraries/classes/Gis/GisVisualization.php
> +     * @param array<string,string|int> $options   Users specified options
Shouldn't this be `array<string,string|int|null>` if `labelColumn` is nullable?

2023-03-06 22:49 UTC, kamil-tekiela commented on psalm-baseline.xml
> +    </PossiblyUnusedMethod>
Can we not remove this method?

2023-03-06 23:01 UTC, MoonE commented on libraries/classes/Gis/GisVisualization.php
> +     * @param array<string,string|int> $options   Users specified options
Currently only GisVisualizationController uses the labelColumn option and if no label is needed the option is not set. 
Though it does makes sense to allow null, the `@psalm-param` annotation below also allows null.

2023-03-06 23:13 UTC, MoonE commented on psalm-baseline.xml
> +    </PossiblyUnusedMethod>
Yeah, the toImage and then also the toPng functions are not used.
Png was originally used for browsers without svg support. b2e498cbaf67b5ede9d2c198432e54a5e4340e3d

2023-03-10 00:25 UTC, williamdes commented on libraries/classes/Controllers/Table/GisVisualizationController.php
> +            if ($column_meta->name === '') {
can you add a comment on when this occurs ?

2023-03-10 00:27 UTC, williamdes commented on test/classes/Gis/GisVisualizationTest.php
> +        $this->dbi?->setVersion(['@@version' => '8.0.0']);
```suggestion
        $this->dbi->setVersion(['@@version' => '8.0.0']);
```
I do not see why we should allow it to soft fail, the test needs it ;)

2023-03-10 00:29 UTC, MoonE commented on libraries/classes/Controllers/Table/GisVisualizationController.php
> +            if ($column_meta->name === '') {
It does not, but it fixes a psalm warning.

In FieldMetadata, the name is default-initialized with empty string currently. I suspect this is just for tests and mysql will never return empty string. So it may be possible to assert non-empty string there.

2023-03-10 00:31 UTC, williamdes commented on libraries/classes/Controllers/Table/GisVisualizationController.php
> +            if ($column_meta->name === '') {
Then it's better to silence psalm with a comment rather than having dead code that will stay here for decades ^^

2023-03-10 00:31 UTC, williamdes approved these changes
Very good work !

And cool GPG signature (I probably already said it 😄)

2023-03-10 00:32 UTC, MoonE commented on test/classes/Gis/GisVisualizationTest.php
> +        $this->dbi?->setVersion(['@@version' => '8.0.0']);
This is also just a convenient way to ignore analyzer warnings. If you prefer, an `assert($this->dbi !== null)` would also work.

2023-03-13 14:33 UTC, MauricioFauth requested changes

2023-03-13 14:33 UTC, MauricioFauth commented on test/classes/Gis/GisVisualizationTest.php
> +    private DatabaseInterface|null $dbi = null;
Don't need `null` here. The `setUp()` method is treated as a constructor.

```suggestion
    private DatabaseInterface $dbi;
```

2023-03-13 21:01 UTC, MoonE commented on libraries/classes/Controllers/Table/GisVisualizationController.php
> +            if ($column_meta->name === '') {
I'll make a new PR and annotate FieldMetadata::name as `non-empty-string`. Then psalm will complain and this check can be removed.

2023-03-15 18:16 UTC, MauricioFauth approved these changes

2023-03-15 18:16 UTC, merged