Optimize getTrackingIcon
phpmyadmin/phpmyadmin pull request #18281
Opened 2023-03-20 19:43 UTC by kamil-tekiela

This is #18259 but with minimal changes for QA. No new classes and no refactoring. The /database/tracking/ optimization is also not included.

2023-03-20 20:06 UTC, williamdes approved these changes
🥇

2023-03-20 20:31 UTC, williamdes commented on libraries/classes/Tracker.php
> +     */
Okay, if I am the one to merge, I will redact this part
And do the merge into 6.0
A merge that will be empty since 6.0 has the changes IIRC

2023-03-20 20:43 UTC, kamil-tekiela commented on libraries/classes/Tracker.php
> +     */
So I actually have no idea what will Git do when you try to merge 5.2 into master. This is why I added the note. The merge should be empty, but if it's not then you need to manually adjust it.

2023-03-20 20:59 UTC, williamdes commented on libraries/classes/Tracker.php
> +     */
Git will try to merge all changes, and then I can edit the file and amend the merge
It will maybe complain before so I fix conflicts

What git GUI are you using ?

2023-03-20 21:06 UTC, kamil-tekiela commented on libraries/classes/Tracker.php
> +     */
I just tried `git merge getTrackingIcon`, and it just appended the new method. So you need to manually delete the method.

2023-03-20 22:03 UTC, MauricioFauth requested changes

2023-03-20 22:03 UTC, MauricioFauth commented on psalm-baseline.xml
> +  <file src="config.inc.php">
This shouldn't have to be included.

2023-03-21 08:54 UTC, williamdes commented on libraries/classes/Tracker.php
> +     */
Yup, delete git add && git commit --amend  and push the merge

2023-03-29 17:14 UTC, MauricioFauth approved these changes

2023-03-29 17:14 UTC, merged