Ref #17769 - Replace superglobals with serverrequest in controllers
phpmyadmin/phpmyadmin pull request #18294
Opened 2023-03-29 01:08 UTC by ru-asdx

### Description

Ref https://github.com/phpmyadmin/phpmyadmin/issues/17769

Replace superglobals with ServerRequest in

      libraries/classes/Controllers/Database/ImportController.php
      libraries/classes/Controllers/Server/ImportController.php
      libraries/classes/Controllers/Server/UserGroupsFormController.php
      libraries/classes/Controllers/Sql/SqlController.php
      libraries/classes/Controllers/Table/ChangeController.php
      libraries/classes/Controllers/Table/ExportController.php
      libraries/classes/Controllers/Table/ImportController.php
      libraries/classes/Controllers/Table/SqlController.php
      libraries/classes/Controllers/View/CreateController.php

2023-03-29 14:05 UTC, MauricioFauth requested changes
Hi. Thanks for your contribution. Could you please fix the tests?

2023-03-29 14:36 UTC, kamil-tekiela requested changes

2023-03-29 14:36 UTC, kamil-tekiela commented on libraries/classes/Controllers/Server/UserGroupsFormController.php
> +        if (strlen((string) $username) === 0) {
```suggestion
        /** @var string $username */
        $username = $request->getQueryParam('username', '');

        if ($username === '') {
```

2023-04-12 18:51 UTC, MauricioFauth approved these changes

2023-04-12 18:51 UTC, merged