Fixed the test cases
phpmyadmin/phpmyadmin pull request #18479
Opened 2023-06-02 13:46 UTC by SachinBahukhandi

### Description

Please describe your pull request.

Fixes #18457

2023-06-02 14:00 UTC, faissaloux requested changes

2023-06-06 08:59 UTC, SachinBahukhandi commented on test/classes/Config/ServerConfigChecksTest.php
> +     * Test for imports
I have fixed it. Thanks for pointing out!

2023-06-06 08:59 UTC, SachinBahukhandi commented on test/classes/Config/ServerConfigChecksTest.php
> +     * Test for imports
I have fixed it. Thanks for pointing out!

2023-06-07 22:09 UTC, faissaloux commented on test/classes/Config/ServerConfigChecksTest.php
> +     * Test for imports
You didn't correct this, either correct the description or remove it since the function name doesn't need more explanation

2023-06-07 22:09 UTC, faissaloux commented on test/classes/Config/ServerConfigChecksTest.php
> +     * Test for imports
You didn't correct this, either correct the description or remove it since the function name doesn't need more explanation

2023-06-07 22:55 UTC, faissaloux requested changes

2023-06-07 22:55 UTC, faissaloux commented on test/classes/Config/ServerConfigChecksTest.php
> +     * @requires extension zip
```suggestion
     * @requires extension sodium
```

2023-06-08 14:07 UTC, SachinBahukhandi commented on test/classes/Config/ServerConfigChecksTest.php
> +     * @requires extension zip
> 

Done. Kindly verify.

2023-06-08 14:54 UTC, faissaloux requested changes
Last changes for me

2023-06-08 14:54 UTC, faissaloux commented on test/classes/Config/ServerConfigChecksTest.php
>      public function testBlowfishWithInvalidSecret(): void
```suggestion
    /**
     * @requires extension bz2
     * @requires extension zip
     * @requires extension sodium
     */
    public function testBlowfishWithInvalidSecret(): void
```

2023-06-08 14:54 UTC, faissaloux commented on test/classes/Config/ServerConfigChecksTest.php
>      public function testBlowfishWithValidSecret(): void
```suggestion
    /**
     * @requires extension bz2
     * @requires extension zip
     * @requires extension sodium
     */
    public function testBlowfishWithValidSecret(): void
```

2023-06-08 17:15 UTC, SachinBahukhandi commented on test/classes/Config/ServerConfigChecksTest.php
>      public function testBlowfishWithValidSecret(): void
> 

Done. Please verify and mark as resolved, if it appears fine. Thanks!

2023-06-08 17:17 UTC, SachinBahukhandi commented on test/classes/Config/ServerConfigChecksTest.php
>      public function testBlowfishWithInvalidSecret(): void
> /**
>      * @requires extension bz2
>      * @requires extension zip
>      * @requires extension sodium
>      */

Done. Please verify and mark as resolved, if it appears fine. Thanks!

2023-06-08 17:21 UTC, faissaloux approved these changes

2023-06-08 17:23 UTC, faissaloux commented on test/classes/Config/ServerConfigChecksTest.php
>      public function testBlowfishWithValidSecret(): void
I don't have write access to resolve those conversations, @williamdes can do after his review.

2023-06-08 17:24 UTC, SachinBahukhandi commented on test/classes/Config/ServerConfigChecksTest.php
>      public function testBlowfishWithValidSecret(): void
Cool, no problem, I would do it.

2023-06-12 22:12 UTC, williamdes commented on test/classes/Config/ServerConfigChecksTest.php
> +     * @requires extension zip
is this true that this test requires the two extensions ?
what does it do on your end when you run the tests without the two lines ?

2023-06-12 22:13 UTC, williamdes commented on test/classes/Config/ServerConfigChecksTest.php
> +     */
I am not sure it makes sense to add this line because sodium is now bundled into PHP since 7.2.0

2023-06-12 22:31 UTC, faissaloux commented on test/classes/Config/ServerConfigChecksTest.php
> +     * @requires extension zip
Yes it does require both extensions `bz2` and `zip`

Here is the failing test
![Screenshot 2023-06-12 232537](https://github.com/phpmyadmin/phpmyadmin/assets/60013703/984476fb-f27c-4ec8-ae8b-93bed9e2f5e0)

After checking the `error`
![Screenshot 2023-06-12 232827](https://github.com/phpmyadmin/phpmyadmin/assets/60013703/92756d14-bc9d-4618-b69f-789059abb8a9)

2023-06-12 22:44 UTC, faissaloux commented on test/classes/Config/ServerConfigChecksTest.php
> +     */
But the tests fails when `sodium` is not enabled.

2023-06-13 08:22 UTC, williamdes commented on test/classes/Config/ServerConfigChecksTest.php
> +     */
Sodium can not be not enabled, how do you do that?

2023-06-13 12:17 UTC, faissaloux commented on test/classes/Config/ServerConfigChecksTest.php
> +     */
Yeah I can't on Linux but I can enable/disable it on Windows.

2023-06-13 16:16 UTC, faissaloux commented on test/classes/Config/ServerConfigChecksTest.php
> +     */
Yeah yeah you are right 😅 , `@requires extension sodium` should be removed

2023-06-13 16:46 UTC, williamdes commented on test/classes/Config/ServerConfigChecksTest.php
> +     */
That said we should add sodium to the checked extensions that phpmyadmin requires even if it's not possible to have it missing
since windows can
it would avoid some crashing while booting phpmyadmin on a weird php config
right @MauricioFauth?

2023-06-13 17:08 UTC, MauricioFauth commented on test/classes/Config/ServerConfigChecksTest.php
> +     */
I was going to say that it was already been checked, but it's not. We should definitely add that check.

2023-06-14 08:51 UTC, Seb33300 commented on test/classes/Config/ServerConfigChecksTest.php
> +     */
Sodium is a requirement in the `composer.json:
https://github.com/phpmyadmin/phpmyadmin/blob/a79eff2a894e31734031dd8f8f5386accd4fcc61/composer.json#L57

2023-06-14 12:29 UTC, faissaloux requested changes

2023-06-14 12:29 UTC, faissaloux commented on test/classes/Config/ServerConfigChecksTest.php
> +     */
```suggestion

```

2023-06-14 12:29 UTC, faissaloux commented on test/classes/Config/ServerConfigChecksTest.php
> +     */
```suggestion
    /**
     * @requires extension bz2
     * @requires extension zip
     */
```

2023-06-14 12:29 UTC, faissaloux commented on test/classes/Config/ServerConfigChecksTest.php
> +     */
```suggestion
    /**
     * @requires extension bz2
     * @requires extension zip
     */
```

2023-06-14 17:11 UTC, SachinBahukhandi commented on test/classes/Config/ServerConfigChecksTest.php
> +     */
Done

2023-06-14 17:25 UTC, SachinBahukhandi commented on test/classes/Config/ServerConfigChecksTest.php
> +     */
Done

2023-06-14 17:32 UTC, faissaloux approved these changes

2023-06-28 12:06 UTC, MauricioFauth approved these changes

2023-06-28 12:07 UTC, merged