a copy to the clipboard button for text output on the export page
phpmyadmin/phpmyadmin pull request #18534
Opened 2023-07-16 13:15 UTC by kamioon

### Description

This is a PR for adding a **copy** to the clipboard on the export page that was requested [here]  (https://github.com/phpmyadmin/phpmyadmin/issues/18529). 

<img width="454" alt="phpmyadmin_copy_export" src="https://github.com/phpmyadmin/phpmyadmin/assets/3734100/6c0d0d24-56cd-4a87-9c3d-1e8648042d5e">

To keep the text format copied to the clipboard temporary `input` has changed to the `textarea`.

#18529

2023-07-20 07:25 UTC, williamdes approved these changes
Very nice

2023-07-21 13:26 UTC, williamdes commented on js/src/modules/functions.ts
> +                copyText = String($(copyTarget).val());
```suggestion
                copyText = $(copyTarget).val();
```

2023-07-22 23:58 UTC, williamdes approved these changes
💯

2023-07-22 23:59 UTC, williamdes commented
Can you check why tests are not passing?

2023-07-23 09:44 UTC, williamdes requested changes
what was wrong with the previous version?

2023-07-23 09:45 UTC, kamioon commented
`[tsl] ERROR in /home/runner/work/phpmyadmin/phpmyadmin/js/src/modules/functions.ts(1522,17)
      TS2322: Type 'string | number | string[]' is not assignable to type 'string'.`
@williamdes the `.val()` returns a mixed type and that was the reason I had added the `String()`. I've changed a little bit more. separated them into two different functions and moved the copy message to a new function. I think it's better now. otherwise, reverting the two latest commits could work fine but your commit suggestion wouldn't be applied there.

2023-07-23 10:07 UTC, kamioon commented
> what was wrong with the previous version?

Sorry, I just saw that you had approved the previous one. I explained here the reason for failing the test and I think the new changes are cleaner than using the `copyQueryBtn` for two purposes. (it should handle two different text sources.)

> `[tsl] ERROR in /home/runner/work/phpmyadmin/phpmyadmin/js/src/modules/functions.ts(1522,17) TS2322: Type 'string | number | string[]' is not assignable to type 'string'.` @williamdes the `.val()` returns a mixed type and that was the reason I had added the `String()`. I've changed a little bit more. separated them into two different functions and moved the copy message to a new function. I think it's better now. otherwise, reverting the two latest commits could work fine but your commit suggestion wouldn't be applied there.

2023-07-23 10:33 UTC, williamdes commented on js/src/modules/functions.ts
> +
could you add a block of documentation like other functions to document the input and output
or much better: add typescript types

2023-07-23 10:33 UTC, williamdes approved these changes
Thank for explaining, looks okay
I left one minor comment about typing

2023-07-24 09:22 UTC, williamdes approved these changes
This really looks good

2024-04-28 12:02 UTC, merged