Remove all boolean uses of strcmp()
phpmyadmin/phpmyadmin pull request #18571
Opened 2023-07-24 19:50 UTC by kamil-tekiela

2023-07-25 16:42 UTC, williamdes approved these changes

2023-07-25 19:12 UTC, MauricioFauth requested changes

2023-07-25 19:12 UTC, MauricioFauth commented on libraries/classes/Plugins/Auth/AuthenticationHttp.php
> +        if (substr($this->user, 0, 6) === 'Basic ') {
```suggestion
        if (str_starts_with($this->user, 'Basic ')) {
```

2023-07-25 19:12 UTC, MauricioFauth commented on libraries/classes/Plugins/Import/ImportMediawiki.php
> +                if (mb_substr($curBufferLine, 0, 4) === '<!--') {
```suggestion
                if (str_starts_with($curBufferLine, '<!--')) {
```

2023-07-25 19:12 UTC, MauricioFauth commented on libraries/classes/Plugins/Import/ImportMediawiki.php
> +                    if (mb_substr($curBufferLine, 0, 4) === '-->') {
```suggestion
                    if (str_starts_with($curBufferLine, '-->')) {
```

2023-07-26 02:58 UTC, MauricioFauth approved these changes

2023-07-26 02:58 UTC, merged