Refactor the DbTableExists class
phpmyadmin/phpmyadmin pull request #18602
Opened 2023-08-05 22:32 UTC by MauricioFauth

- Changes static methods to instance methods
- Extract response handling to the controllers
- Add unit tests for the DbTableExists class
- Remove the AbstractController::hasDatabase() method

2023-08-05 23:13 UTC, kamil-tekiela requested changes
I like it! I wonder if we could have some helper method for:
```
$this->response->setRequestStatus(false);
$this->response->addJSON('message', Message::error(__('No databases selected.')));
```

2023-08-05 23:13 UTC, kamil-tekiela commented on libraries/classes/DbTableExists.php
> +        return str_starts_with($this->dbi->getError(), '#2014 ');
I am not a fan of this. This method belongs in Dbal if it belongs anywhere at all. We should not be lenient with errors, especially ones where we perform operations out of order.

2023-08-05 23:13 UTC, kamil-tekiela commented on libraries/classes/DbTableExists.php
> +        $result = $this->dbi->tryQuery(sprintf('SELECT COUNT(*) FROM %s;', Util::backquote($table)));
```suggestion
        $result = $this->dbi->tryQuery(sprintf('SELECT 1 FROM %s LIMIT 1;', Util::backquote($table)));
```
I believe this should be faster.

2023-08-05 23:13 UTC, kamil-tekiela commented on libraries/classes/DbTableExists.php
> +        return $result !== false && $result->numRows() > 0;
```suggestion
        return $result !== false;
```

2023-08-05 23:13 UTC, kamil-tekiela commented on libraries/classes/DbTableExists.php
> +        if ($this->dbi->selectDb($databaseName) || $this->hasCommandsOutOfSyncError()) {
This is an unexpected side effect from a method that looks like it just checks something and returns a result. But I don't know yet how to improve it, so let's leave it as it is and maybe something will come to me later.

2023-08-05 23:34 UTC, MauricioFauth commented on libraries/classes/DbTableExists.php
> +     * at this point we can't select the db, but it's not necessarily wrong.
This was introduced by b55ba34d43138b11b71d8eeae6b09ea160ded213. I don't want to remove this in this PR, but it's worth verifying if this could be removed later on.

2023-08-05 23:41 UTC, MauricioFauth commented on libraries/classes/DbTableExists.php
> +        $result = $this->dbi->tryQuery(sprintf('SELECT COUNT(*) FROM %s;', Util::backquote($table)));
If this is faster, then it can also improve the MySQL `sys.table_exists` procedure.

https://github.com/mysql/mysql-sys/blob/a1374ea7cf341b71fd1060136533ce01fe0bd57b/procedures/table_exists.sql#L141

2023-08-05 23:49 UTC, kamil-tekiela commented on libraries/classes/DbTableExists.php
> +        $result = $this->dbi->tryQuery(sprintf('SELECT COUNT(*) FROM %s;', Util::backquote($table)));
No, it won't. They don't execute it. They only prepare.

2023-08-06 00:04 UTC, MauricioFauth commented on libraries/classes/DbTableExists.php
> +        if (in_array($table->getName(), $this->tables, true)) {
> I wonder what exactly is the need for memorization here?

This is similar as the global variable that was used before. There are some places that it can be checked more than once. This can be removed after fixed those cases.

2023-08-06 04:42 UTC, merged