Remove obsolete code for stand-alone gis editor
phpmyadmin/phpmyadmin pull request #18726
Opened 2023-09-20 22:19 UTC by MoonE

This merges the changes done for the JS version into the twig file.
As I understand it there used  to be a non-js version of the gis editor,  which opended in a new window.

2023-09-20 23:11 UTC, MauricioFauth requested changes

2023-09-20 23:11 UTC, MauricioFauth commented on templates/gis_data_editor_form.twig
> +                            <a href="#" name="gis_data[{{ a }}][{{ type }}][add_point]" class="btn btn-secondary addJs addPoint">{% trans 'Add a point' %}</a>
You should use a `<button>` tag instead of `<a href="#">`.

2023-09-20 23:11 UTC, MauricioFauth commented on templates/gis_data_editor_form.twig
> +            <br>
The `<br>` tag should only be used for line breaks in texts. Here, you should use a `<div>` tag.

2023-09-20 23:20 UTC, MoonE commented on templates/gis_data_editor_form.twig
> +            <br>
Yeah the current html structure here isn't great. What I did is simply apply the changes done in JS to the twig template. So the structure is exactly the same as before.

2023-09-26 00:18 UTC, MauricioFauth approved these changes

2023-09-26 00:18 UTC, merged