Replaced superglobals with ServerRequest in ChangeRowsController
phpmyadmin/phpmyadmin pull request #18743
Opened 2023-10-02 17:25 UTC by dardvas

### Description

Replaced superglobals with ServerRequest in ChangeRowsController

2023-10-02 20:38 UTC, MauricioFauth requested changes

2023-10-02 20:38 UTC, MauricioFauth commented on src/Controllers/Table/ChangeRowsController.php
> +        $rowsToDeleteIsValid = ! isset($rowsToDelete) || ! is_array($rowsToDelete);
In this case, `isset` is redundant, because it's only checking if `$rowsToDelete` is not `null`, which `is_array` also checks, so the `isset` can be removed.

2023-10-03 21:40 UTC, MauricioFauth requested changes

2023-10-03 21:40 UTC, MauricioFauth commented on src/Controllers/Table/FindReplaceController.php
> +        if (!empty($request->getParsedBodyParam('replace'))) {
Please don't use empty. We prefer stricter comparisons. In this case you can use `ServerRequest::hasBodyParam()`.

```suggestion
        if ($request->hasBodyParam('replace')) {
```

2023-10-04 01:53 UTC, dardvas commented on src/Controllers/Table/FindReplaceController.php
> +        if (!empty($request->getParsedBodyParam('replace'))) {
Sure, makes sense, thanks!

2023-10-10 17:20 UTC, MauricioFauth requested changes
You should fix the tests.
- https://github.com/phpmyadmin/phpmyadmin/actions/runs/6410026164/job/17535125700?pr=18743#step:8:94
- https://github.com/phpmyadmin/phpmyadmin/actions/runs/6410026151/job/17535124606?pr=18743#step:8:33

You can run the tests with:
```
composer test
```
For PHPStan and Psalm, you can run:
```
composer update:baselines
```

2023-10-16 16:48 UTC, MauricioFauth approved these changes

2023-10-16 17:08 UTC, merged

2023-10-16 17:08 UTC, MauricioFauth commented
Merged. Thanks!

2023-10-17 14:15 UTC, dardvas commented
Thanks @MauricioFauth ! Sorry, got a bit busy with things :sweat_smile: