Refactor Results class
phpmyadmin/phpmyadmin pull request #18774
Opened 2023-10-21 19:58 UTC by kamil-tekiela

This PR mainly removes `$properties` property and carves out `Util::getUniqueCondition()` into a new class. 

The `$properties` property was causing a lot of unnecessary code. I didn't find any of it to actually be needed, despite some comments claiming it was needed. It must be a leftover from some previous refactorings.

2023-10-22 08:37 UTC, williamdes approved these changes
💯

2023-10-23 16:15 UTC, MauricioFauth requested changes

2023-10-23 16:15 UTC, MauricioFauth commented on src/UniqueCondition.php
> +        /** @infection-ignore-all */
Since it's a `foreach` instead of a `for`, you can remove this line now. The mutant was changing the `++$i` to a `--$i` causing an infinite loop.
```suggestion
```

2023-10-23 16:15 UTC, MauricioFauth commented on src/Display/Results.php
>          /** @infection-ignore-all */
```suggestion
```

2023-10-23 16:15 UTC, MauricioFauth commented on src/Display/Results.php
>          /** @infection-ignore-all */
```suggestion
```

2023-10-23 17:51 UTC, MauricioFauth approved these changes

2023-10-23 17:53 UTC, merged