Remove dead code and globals
phpmyadmin/phpmyadmin pull request #18848
Opened 2023-12-15 19:29 UTC by kamil-tekiela

This PR removes a large chunk of code which in my opinion is not in use. I tried to verify if and how it's used, but I was not able to identify any code path that would lead to its execution. If it's actually used then it should be implemented in a better way. I am 90% sure this is dead code and neither of these globals should have been global.

2023-12-16 00:47 UTC, MauricioFauth commented on src/Controllers/Sql/SqlController.php
> -        }
This was introduced by 4766676ee2e95c1ddf3bd708acc0f3fba5beccb4. I think the only way it have worked was by enabling PHP's `register_globals` directive.

2023-12-16 01:06 UTC, kamil-tekiela commented on src/Controllers/Sql/SqlController.php
> -        }
Makes sense. Then I suppose it hasn't worked for a number of years.

2023-12-16 01:17 UTC, MauricioFauth requested changes

2023-12-16 01:17 UTC, MauricioFauth commented on resources/templates/display/results/table.twig
> -                <input id="real_end_input" type="hidden" name="find_real_end" value="1">
There's more code related to this that should be removed as well.

https://github.com/phpmyadmin/phpmyadmin/blob/4a67d88e1dc73f250b39434154afa633a8661bb1/resources/js/src/database/structure.ts#L34

https://github.com/phpmyadmin/phpmyadmin/blob/4a67d88e1dc73f250b39434154afa633a8661bb1/resources/js/src/database/structure.ts#L422-L440

https://github.com/phpmyadmin/phpmyadmin/blob/4a67d88e1dc73f250b39434154afa633a8661bb1/src/Controllers/JavaScriptMessagesController.php#L68

2023-12-17 17:10 UTC, MauricioFauth approved these changes

2023-12-17 17:11 UTC, merged