Update to fix replication that broke with MySQL 8.4.0 removal of master and slave commands
phpmyadmin/phpmyadmin pull request #19153
Opened 2024-05-09 16:08 UTC by dlmorri75

### Description

Fixes and issue with replication that broke with MySQL 8.4.0 removal of depreciated master and slave replication commands.

Fixes #

Before submitting pull request, please review the following checklist:

- [ ] Make sure you have read our [CONTRIBUTING.md](https://github.com/phpmyadmin/phpmyadmin/blob/master/CONTRIBUTING.md) document.
- [ ] Make sure you are making a pull request against the correct branch. For example, for bug fixes in a released version use the corresponding QA branch and for new features use the _master_ branch. If you have a doubt, you can ask as a comment in the bug report or on the mailing list.
- [ ] Every commit has proper `Signed-off-by` line as described in our [DCO](https://github.com/phpmyadmin/phpmyadmin/blob/master/DCO). This ensures that the work you're submitting is your own creation.
- [ ] Every commit has a descriptive commit message.
- [ ] Every commit is needed on its own, if you have just minor fixes to previous commits, you can squash them.
- [ ] Any new functionality is covered by tests.

2024-09-02 21:26 UTC, MauricioFauth commented
- Related to #16197

2024-09-02 21:29 UTC, MauricioFauth requested changes
Thank you for your contribution. 

These changes will break for older versions of MySQL, as phpMyAdmin supports MySQL/MariaDB >= 5.5.

So, it should check if the server is MySQL >= 8.4 to use the new statements, otherwise use the old ones.

2024-10-22 20:26 UTC, kamil-tekiela commented on libraries/classes/Replication.php
> +                'SOURCE_HOST=\'' . $host . '\',' .
Shouldn't this use `quoteString()`?

2024-10-22 22:49 UTC, MauricioFauth commented on libraries/classes/Replication.php
> +                'SOURCE_HOST=\'' . $host . '\',' .
I thought so, but 5.2 doesn't have `quoteString` and those variables were escaped earlier using `escapeString`.

2024-10-24 02:07 UTC, merged

2024-10-24 02:08 UTC, MauricioFauth commented
@dlmorri75 Merged! Thanks!