Fixed can't access property getUnits, sourceProj is null
phpmyadmin/phpmyadmin pull request #19275
Opened 2024-08-29 20:01 UTC by SachinBahukhandi

### Description

Fixes the issue coming up upon entering an invalid SRID.
Now the function would execute only if the `sourceProj` is a valid object.

Fixes: https://github.com/phpmyadmin/phpmyadmin/issues/19266

2024-09-06 20:06 UTC, MauricioFauth requested changes

2024-09-06 20:06 UTC, MauricioFauth commented on resources/js/src/table/gis_visualization.ts
> +import { get as getProjection } from 'ol/proj.js';
Could you move that to the `resources/js/src/ol.mjs` file? We are not directly importing third-party dependencies yet.

2024-09-07 09:48 UTC, SachinBahukhandi commented on resources/js/src/table/gis_visualization.ts
> +import { get as getProjection } from 'ol/proj.js';
But won't we have to reimport the `ol.mjs` file inside the above file?

2024-09-07 21:30 UTC, MoonE commented on resources/js/src/table/gis_visualization.ts
> +import { get as getProjection } from 'ol/proj.js';
`ol` is availabe as a property of `window`
https://github.com/phpmyadmin/phpmyadmin/blob/71fac7eb4c992c28e619327341170e7f157e0b3e/resources/js/src/table/gis_visualization.ts#L437-L455

`OpenLayers.js` is  added in a script tag. 
https://github.com/phpmyadmin/phpmyadmin/blob/71fac7eb4c992c28e619327341170e7f157e0b3e/src/Controllers/Table/GisVisualizationController.php#L128

which is transpiled from `ol.mjs`
https://github.com/phpmyadmin/phpmyadmin/blob/71fac7eb4c992c28e619327341170e7f157e0b3e/webpack.config.cjs#L158-L183

2024-09-08 04:59 UTC, SachinBahukhandi commented on resources/js/src/table/gis_visualization.ts
> +import { get as getProjection } from 'ol/proj.js';
@MoonE thanks for the clarity. It was really helpful.

2024-09-08 04:59 UTC, SachinBahukhandi commented on resources/js/src/table/gis_visualization.ts
> +import { get as getProjection } from 'ol/proj.js';
@MauricioFauth please re-review.

2024-09-18 15:48 UTC, MauricioFauth approved these changes

2024-09-18 15:49 UTC, merged

2024-09-18 15:50 UTC, MauricioFauth commented
Merged! Thank you!