add optional support for binary data in database search
phpmyadmin/phpmyadmin pull request #19287
Opened 2024-09-16 21:07 UTC by GregorLohaus

Signed-off-by: Gregor Lohaus <lohausgregor@gmail.com>

### Description

Recently I had to search for some binary data in a database, globally. 
Unfortunately neither LIKE nor REGEXP work with hex literals, so i added an option to include matches on hexed column data in the database search module. 
I think some people could benefit from this.

2024-09-16 21:53 UTC, kamil-tekiela requested changes

2024-09-16 21:53 UTC, kamil-tekiela commented on src/Database/Search.php
> +    private array $criteriaSearchOptions;
Why is it an array of mixed values if you have only a single boolean?

2024-09-16 21:53 UTC, kamil-tekiela commented on src/Database/Search.php
> +        }
```suggestion
        $this->criteriaSearchOptions['include_hex_matches'] = isset($_POST['criteriaSearchOptionIncludeHex']);
```

2024-09-16 21:53 UTC, kamil-tekiela commented on src/Database/Search.php
> +                if (! ((bool) $this->criteriaSearchOptions['include_hex_matches'])) {
The cast is unnecessary since the only possible value is a boolean.

2024-09-16 21:53 UTC, kamil-tekiela commented on tests/unit/Database/SearchTest.php
> +                ['include_hex_matches' => null],
I see no reason to test `null`. Your condition checks if the value is set, so `['include_hex_matches' => null],` is unnecessary.

2024-09-17 00:13 UTC, GregorLohaus commented
@kamil-tekiela i have refactored this a bit adding a hidden input so the arraykey will always be set in the post request, i thought using an array might be a good idea if someone wanted to add more options in the future but i have changed this to use a boolean property for now

2024-09-17 00:34 UTC, GregorLohaus commented on src/Database/Search.php
> +                if (! ((bool) $this->criteriaSearchOptions['include_hex_matches'])) {
i think i did this to satisfy phpstan when the value could be unset but i removed the cast now

2024-09-17 00:39 UTC, GregorLohaus commented on src/Database/Search.php
> +        }
the value will now always be set to either '1' or '0' due to the added hidden input, i still have to check for isset because on the first page render the value is not set the and the empty check used for searchType is disallowed by phpstan config

2024-09-17 00:43 UTC, GregorLohaus commented on tests/unit/Database/SearchTest.php
> +                ['include_hex_matches' => null],
this was also done to satisfy phpstan

2024-09-18 19:26 UTC, MauricioFauth approved these changes

2024-09-18 19:51 UTC, merged

2024-09-18 19:52 UTC, MauricioFauth commented
Merged. Thank you!