allow query generator ops multiple values to accept values without qu…
phpmyadmin/phpmyadmin pull request #19294
Opened 2024-09-22 12:04 UTC by faissaloux

Hellooo 👋🏻 

### Current
We need to pass criteria text with quotes for each value to generate a valid query.

![image](https://github.com/user-attachments/assets/a9dde3b3-1141-4159-9141-8e5df83b6b56)

### After
To simplify, the user don't need to write the values with quotes any more.

```diff
- 'bouizakarne','guelmim'
+ bouizakarne,guelmim
```

![image](https://github.com/user-attachments/assets/9f26b592-192b-40d0-b951-d2b20d098c75)

2024-09-23 19:20 UTC, MauricioFauth requested changes
Does it still accepts using single quotes? What about a single value that has a comma?
I'm not sure if this should go to QA_5_2.

2024-09-23 19:20 UTC, MauricioFauth commented on js/src/functions.js
> +Functions.wrap = function (s, char) {
If this function is only used in a single place, it doesn't need to be in functions.js.

2024-09-29 22:36 UTC, MauricioFauth commented
> No it does not, if using single quotes it escapes them like if they belong to the value like any other character.

> This won't work because it counts as two separate values. Do you have any idea to solve this?

These are breaking changes.

The only way to accept not needing a quoted value is to also accept quoted values, as a quoted value fixes the comma issue. But accepting both ways could be very confusing.

I think a good solution is to only accept quoted values and add a button to edit the list, like the enum/set editor that exists when creating/editing a table.

2024-10-02 17:38 UTC, faissaloux commented
> I think a good solution is to only accept quoted values and add a button to edit the list, like the enum/set editor that exists when creating/editing a table.

Yeah this is the kind of the solution I thought about, but for addition too.

We need to be able to add values one by one (without quotes, quotes can be part of the value) and then can be edited or removed there on a list of values.

2024-10-13 02:15 UTC, faissaloux commented
@MauricioFauth

https://github.com/user-attachments/assets/166fd993-f5f0-417b-9476-1cd8b5707c84

2024-10-13 02:21 UTC, MauricioFauth commented
That's nice!

2024-10-15 15:49 UTC, MauricioFauth approved these changes
Great work! Thank you!

Could you please change the target branch to `master` instead of `QA_5_2`?

2024-10-15 21:10 UTC, faissaloux commented
@MauricioFauth

Retargeted to `master` and commits squashed!

2024-10-16 14:56 UTC, merged