ISSUE-17182 FK Relationship View constraint name natural ordering
phpmyadmin/phpmyadmin pull request #19323
Opened 2024-10-16 06:07 UTC by aonamrata

### Description

When `$cfg['NaturalOrder']=true` sort foreign keys list in Table > relationship view.

Fixes https://github.com/phpmyadmin/phpmyadmin/issues/17182

Before submitting pull request, please review the following checklist:

- [ ] Make sure you have read our [CONTRIBUTING.md](https://github.com/phpmyadmin/phpmyadmin/blob/master/CONTRIBUTING.md) document.
- [ ] Make sure you are making a pull request against the correct branch. For example, for bug fixes in a released version use the corresponding QA branch and for new features use the _master_ branch. If you have a doubt, you can ask as a comment in the bug report or on the mailing list.
- [ ] Every commit has proper `Signed-off-by` line as described in our [DCO](https://github.com/phpmyadmin/phpmyadmin/blob/master/DCO). This ensures that the work you're submitting is your own creation.
- [ ] Every commit has a descriptive commit message.
- [ ] Every commit is needed on its own, if you have just minor fixes to previous commits, you can squash them.
- [ ] Any new functionality is covered by tests.

2024-10-16 15:42 UTC, kamil-tekiela requested changes

2024-10-16 15:42 UTC, kamil-tekiela commented on src/Controllers/Table/RelationController.php
> +            usort($relationsForeign, 'PhpMyAdmin\Utils\ForeignKey::sortForeignKeys');
Why can this not be a first-class callable?

2024-10-16 15:42 UTC, kamil-tekiela commented on src/Utils/ForeignKey.php
> +    }
I am not sure why this function is necessary.

2024-10-18 09:33 UTC, aonamrata commented on src/Controllers/Table/RelationController.php
> +            usort($relationsForeign, 'PhpMyAdmin\Utils\ForeignKey::sortForeignKeys');
because we don't want to sort it by keys and $relationsForeign is array of PhpMyAdmin\SqlParser\Utils\ForeignKey Objects. I can make it an inline functions like 
```
            usort($relationsForeign, fn ($before, $after) => strnatcmp(
                $before->constraint, $after->constraint
            ));
```

2024-10-18 14:09 UTC, kamil-tekiela commented on src/Controllers/Table/RelationController.php
> +            usort($relationsForeign, 'PhpMyAdmin\Utils\ForeignKey::sortForeignKeys');
Yes, an inline function would make a lot more sense. Please make sure to use property types too.

2024-10-22 05:48 UTC, closed without merging

2024-10-22 05:59 UTC, aonamrata commented on src/Controllers/Table/RelationController.php
> +            usort($relationsForeign, 'PhpMyAdmin\Utils\ForeignKey::sortForeignKeys');
👍 @kamil-tekiela , I had to re-do the pull request with rebase so all commits were signed off. Ref https://github.com/phpmyadmin/phpmyadmin/pull/19331 is the new one.